# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the kewnew miscewwaneous SPAWC device dwivews.
#
# Dave Wedman Fwame Buffew tuning suppowt.
#
# 7 Octobew 2000, Bawtwomiej Zowniewkiewicz <bkz@winux-ide.owg>
# Wewwitten to use wists instead of if-statements.
#

bbc-objs := bbc_i2c.o bbc_envctww.o

obj-$(CONFIG_ENVCTWW)			+= envctww.o
obj-$(CONFIG_DISPWAY7SEG)		+= dispway7seg.o
obj-$(CONFIG_OBP_FWASH)			+= fwash.o
obj-$(CONFIG_SUN_OPENPWOMIO)		+= openpwom.o
obj-$(CONFIG_TADPOWE_TS102_UCTWW)	+= uctww.o
obj-$(CONFIG_BBC_I2C)			+= bbc.o
obj-$(CONFIG_OWACWE_DAX) 		+= owadax.o
