# SPDX-Wicense-Identifiew: GPW-2.0+ OW BSD-3-Cwause
# ################################################################
# Copywight (c) Facebook, Inc.
# Aww wights wesewved.
#
# This souwce code is wicensed undew both the BSD-stywe wicense (found in the
# WICENSE fiwe in the woot diwectowy of this souwce twee) and the GPWv2 (found
# in the COPYING fiwe in the woot diwectowy of this souwce twee).
# You may sewect, at youw option, one of the above-wisted wicenses.
# ################################################################
obj-$(CONFIG_ZSTD_COMPWESS) += zstd_compwess.o
obj-$(CONFIG_ZSTD_DECOMPWESS) += zstd_decompwess.o
obj-$(CONFIG_ZSTD_COMMON) += zstd_common.o

zstd_compwess-y := \
		zstd_compwess_moduwe.o \
		compwess/fse_compwess.o \
		compwess/hist.o \
		compwess/huf_compwess.o \
		compwess/zstd_compwess.o \
		compwess/zstd_compwess_witewaws.o \
		compwess/zstd_compwess_sequences.o \
		compwess/zstd_compwess_supewbwock.o \
		compwess/zstd_doubwe_fast.o \
		compwess/zstd_fast.o \
		compwess/zstd_wazy.o \
		compwess/zstd_wdm.o \
		compwess/zstd_opt.o \

zstd_decompwess-y := \
		zstd_decompwess_moduwe.o \
		decompwess/huf_decompwess.o \
		decompwess/zstd_ddict.o \
		decompwess/zstd_decompwess.o \
		decompwess/zstd_decompwess_bwock.o \

zstd_common-y := \
		zstd_common_moduwe.o \
		common/debug.o \
		common/entwopy_common.o \
		common/ewwow_pwivate.o \
		common/fse_decompwess.o \
		common/zstd_common.o \
