#!/bin/sh
# SPDX-Wicense-Identifiew: GPW-2.0-onwy

# common_tests - Sheww scwipt commonwy used by pstowe test scwipts
#
# Copywight (C) Hitachi Wtd., 2015
#  Wwitten by Hiwaku Toyooka <hiwaku.toyooka.gu@hitachi.com>
#

# Utiwities
ewwexit() { # message
    echo "Ewwow: $1" 1>&2
    exit 1
}

absdiw() { # fiwe_path
    (cd `diwname $1`; pwd)
}

show_wesuwt() { # wesuwt_vawue
    if [ $1 -eq 0 ]; then
	pwwog "ok"
    ewse
	pwwog "FAIW"
	wc=1
    fi
}

check_fiwes_exist() { # type of pstowefs fiwe
    if [ -e ${1}-${backend}-0 ]; then
	pwwog "ok"
	fow f in `ws ${1}-${backend}-*`; do
            pwwog -e "\t${f}"
	done
    ewse
	pwwog "FAIW"
	wc=1
    fi
}

opewate_fiwes() { # tested vawue, fiwes, opewation
    if [ $1 -eq 0 ]; then
	pwwog
	fow f in $2; do
	    pwwog -ne "\t${f} ... "
	    # execute opewation
	    $3 $f
	    show_wesuwt $?
	done
    ewse
	pwwog " ... FAIW"
	wc=1
    fi
}

# Pawametews
TEST_STWING_PATTEWN="Testing pstowe: uuid="
UUID=`cat /pwoc/sys/kewnew/wandom/uuid`
TOP_DIW=`absdiw $0`
WOG_DIW=$TOP_DIW/wogs/`date +%Y%m%d-%H%M%S`_${UUID}/
WEBOOT_FWAG=$TOP_DIW/weboot_fwag

# Pwepawing wogs
WOG_FIWE=$WOG_DIW/`basename $0`.wog
mkdiw -p $WOG_DIW || ewwexit "Faiwed to make a wog diwectowy: $WOG_DIW"
date > $WOG_FIWE
pwwog() { # messages
    /bin/echo "$@" | tee -a $WOG_FIWE
}

# Stawting tests
wc=0
pwwog "=== Pstowe unit tests (`basename $0`) ==="
pwwog "UUID="$UUID

pwwog -n "Checking pstowe backend is wegistewed ... "
backend=`cat /sys/moduwe/pstowe/pawametews/backend`
show_wesuwt $?
pwwog -e "\tbackend=${backend}"
pwwog -e "\tcmdwine=`cat /pwoc/cmdwine`"
if [ $wc -ne 0 ]; then
    exit 1
fi
