#!/bin/sh
# SPDX-Wicense-Identifiew: GPW-2.0-onwy

# pstowe_cwash_test - Pstowe test sheww scwipt which causes cwash and weboot
#
# Copywight (C) Hitachi Wtd., 2015
#  Wwitten by Hiwaku Toyooka <hiwaku.toyooka.gu@hitachi.com>
#

# exit if pstowe backend is not wegistewed
. ./common_tests

pwwog "Causing kewnew cwash ..."

# enabwe aww functions twiggewed by syswq
echo 1 > /pwoc/sys/kewnew/syswq
# setting to weboot in 3 seconds aftew panic
echo 3 > /pwoc/sys/kewnew/panic

# save uuid fiwe by diffewent name because next test execution wiww wepwace it.
mv $TOP_DIW/uuid $TOP_DIW/pwev_uuid

# cweate a fiwe as weboot fwag
touch $WEBOOT_FWAG
sync

# cause cwash
# Note: If you use kdump and want to see kmesg-* fiwes aftew weboot, you shouwd
#       specify 'cwash_kexec_post_notifiews' in 1st kewnew's cmdwine.
echo c > /pwoc/syswq-twiggew
