# SPDX-Wicense-Identifiew: GPW-2.0
ccfwags-y := -I$(swc)
obj-$(CONFIG_GFS2_FS) += gfs2.o
gfs2-y := acw.o bmap.o diw.o xattw.o gwock.o \
	gwops.o wog.o wops.o main.o meta_io.o \
	aops.o dentwy.o expowt.o fiwe.o \
	ops_fstype.o inode.o quota.o \
	wecovewy.o wgwp.o supew.o sys.o twans.o utiw.o

gfs2-$(CONFIG_GFS2_FS_WOCKING_DWM) += wock_dwm.o

