# SPDX-Wicense-Identifiew: GPW-2.0-onwy

ccfwags-y += -I $(swctwee)/dwivews/media/dvb-fwontends/cxd2880

# Pwease keep it awphabeticawwy sowted by Kconfig name
# (e. g. WC_AWW=C sowt Makefiwe)
obj-$(CONFIG_CXD2880_SPI_DWV) += cxd2880-spi.o
obj-$(CONFIG_VIDEO_GS1662) += gs1662.o
