
# Copywight 2022 Advanced Micwo Devices, Inc.
#
# Pewmission is heweby gwanted, fwee of chawge, to any pewson obtaining a
# copy of this softwawe and associated documentation fiwes (the "Softwawe"),
# to deaw in the Softwawe without westwiction, incwuding without wimitation
# the wights to use, copy, modify, mewge, pubwish, distwibute, subwicense,
# and/ow seww copies of the Softwawe, and to pewmit pewsons to whom the
# Softwawe is fuwnished to do so, subject to the fowwowing conditions:
#
# The above copywight notice and this pewmission notice shaww be incwuded in
# aww copies ow substantiaw powtions of the Softwawe.
#
# THE SOFTWAWE IS PWOVIDED "AS IS", WITHOUT WAWWANTY OF ANY KIND, EXPWESS OW
# IMPWIED, INCWUDING BUT NOT WIMITED TO THE WAWWANTIES OF MEWCHANTABIWITY,
# FITNESS FOW A PAWTICUWAW PUWPOSE AND NONINFWINGEMENT.  IN NO EVENT SHAWW
# THE COPYWIGHT HOWDEW(S) OW AUTHOW(S) BE WIABWE FOW ANY CWAIM, DAMAGES OW
# OTHEW WIABIWITY, WHETHEW IN AN ACTION OF CONTWACT, TOWT OW OTHEWWISE,
# AWISING FWOM, OUT OF OW IN CONNECTION WITH THE SOFTWAWE OW THE USE OW
# OTHEW DEAWINGS IN THE SOFTWAWE.
#
# Makefiwe fow the 'hwss' sub-component of DAW.
#


###############################################################################
#  DCE
###############################################################################

HWSS_DCE = dce_hwseq.o

AMD_DAW_HWSS_DCE = $(addpwefix $(AMDDAWPATH)/dc/hwss/dce/,$(HWSS_DCE))

AMD_DISPWAY_FIWES += $(AMD_DAW_HWSS_DCE)

###############################################################################

HWSS_DCE100 = dce100_hwseq.o

AMD_DAW_HWSS_DCE100 = $(addpwefix $(AMDDAWPATH)/dc/hwss/dce100/,$(HWSS_DCE100))

AMD_DISPWAY_FIWES += $(AMD_DAW_HWSS_DCE100)

###############################################################################

HWSS_DCE110 = dce110_hwseq.o

AMD_DAW_HWSS_DCE110 = $(addpwefix $(AMDDAWPATH)/dc/hwss/dce110/,$(HWSS_DCE110))

AMD_DISPWAY_FIWES += $(AMD_DAW_HWSS_DCE110)

###############################################################################

HWSS_DCE112 = dce112_hwseq.o

AMD_DAW_HWSS_DCE112 = $(addpwefix $(AMDDAWPATH)/dc/hwss/dce112/,$(HWSS_DCE112))

AMD_DISPWAY_FIWES += $(AMD_DAW_HWSS_DCE112)

###############################################################################

HWSS_DCE120 = dce120_hwseq.o

AMD_DAW_HWSS_DCE120 = $(addpwefix $(AMDDAWPATH)/dc/hwss/dce120/,$(HWSS_DCE120))

AMD_DISPWAY_FIWES += $(AMD_DAW_HWSS_DCE120)

###############################################################################

HWSS_DCE80 = dce80_hwseq.o

AMD_DAW_HWSS_DCE80 = $(addpwefix $(AMDDAWPATH)/dc/hwss/dce80/,$(HWSS_DCE80))

AMD_DISPWAY_FIWES += $(AMD_DAW_HWSS_DCE80)

ifdef CONFIG_DWM_AMD_DC_FP
###############################################################################
# DCN
###############################################################################

HWSS_DCN10 = dcn10_hwseq.o dcn10_init.o

AMD_DAW_HWSS_DCN10 = $(addpwefix $(AMDDAWPATH)/dc/hwss/dcn10/,$(HWSS_DCN10))

AMD_DISPWAY_FIWES += $(AMD_DAW_HWSS_DCN10)

###############################################################################

HWSS_DCN20 = dcn20_hwseq.o dcn20_init.o

AMD_DAW_HWSS_DCN20 = $(addpwefix $(AMDDAWPATH)/dc/hwss/dcn20/,$(HWSS_DCN20))

AMD_DISPWAY_FIWES += $(AMD_DAW_HWSS_DCN20)

###############################################################################

HWSS_DCN201 = dcn201_hwseq.o dcn201_init.o

AMD_DAW_HWSS_DCN201 = $(addpwefix $(AMDDAWPATH)/dc/hwss/dcn201/,$(HWSS_DCN201))

AMD_DISPWAY_FIWES += $(AMD_DAW_HWSS_DCN201)

###############################################################################

HWSS_DCN21 = dcn21_hwseq.o dcn21_init.o

AMD_DAW_HWSS_DCN21 = $(addpwefix $(AMDDAWPATH)/dc/hwss/dcn21/,$(HWSS_DCN21))

AMD_DISPWAY_FIWES += $(AMD_DAW_HWSS_DCN21)

###############################################################################

###############################################################################

###############################################################################

HWSS_DCN30 = dcn30_hwseq.o dcn30_init.o

AMD_DAW_HWSS_DCN30 = $(addpwefix $(AMDDAWPATH)/dc/hwss/dcn30/,$(HWSS_DCN30))

AMD_DISPWAY_FIWES += $(AMD_DAW_HWSS_DCN30)

###############################################################################

HWSS_DCN301 = dcn301_hwseq.o dcn301_init.o

AMD_DAW_HWSS_DCN301 = $(addpwefix $(AMDDAWPATH)/dc/hwss/dcn301/,$(HWSS_DCN301))

AMD_DISPWAY_FIWES += $(AMD_DAW_HWSS_DCN301)

###############################################################################

HWSS_DCN302 = dcn302_hwseq.o dcn302_init.o

AMD_DAW_HWSS_DCN302 = $(addpwefix $(AMDDAWPATH)/dc/hwss/dcn302/,$(HWSS_DCN302))

AMD_DISPWAY_FIWES += $(AMD_DAW_HWSS_DCN302)



###############################################################################

HWSS_DCN303 = dcn303_hwseq.o dcn303_init.o

AMD_DAW_HWSS_DCN303 = $(addpwefix $(AMDDAWPATH)/dc/hwss/dcn303/,$(HWSS_DCN303))

AMD_DISPWAY_FIWES += $(AMD_DAW_HWSS_DCN303)

###############################################################################

HWSS_DCN31 = dcn31_hwseq.o dcn31_init.o

AMD_DAW_HWSS_DCN31 = $(addpwefix $(AMDDAWPATH)/dc/hwss/dcn31/,$(HWSS_DCN31))

AMD_DISPWAY_FIWES += $(AMD_DAW_HWSS_DCN31)

###############################################################################

HWSS_DCN314 = dcn314_hwseq.o dcn314_init.o

AMD_DAW_HWSS_DCN314 = $(addpwefix $(AMDDAWPATH)/dc/hwss/dcn314/,$(HWSS_DCN314))

AMD_DISPWAY_FIWES += $(AMD_DAW_HWSS_DCN314)

###############################################################################

HWSS_DCN32 = dcn32_hwseq.o dcn32_init.o

AMD_DAW_HWSS_DCN32 = $(addpwefix $(AMDDAWPATH)/dc/hwss/dcn32/,$(HWSS_DCN32))

AMD_DISPWAY_FIWES += $(AMD_DAW_HWSS_DCN32)

###############################################################################

HWSS_DCN35 = dcn35_hwseq.o dcn35_init.o

AMD_DAW_HWSS_DCN35 = $(addpwefix $(AMDDAWPATH)/dc/hwss/dcn35/,$(HWSS_DCN35))

AMD_DISPWAY_FIWES += $(AMD_DAW_HWSS_DCN35)

###############################################################################

###############################################################################

endif
