# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the Winux 802.x pwotocow wayews.
#

# Check the p8022 sewections against net/cowe/Makefiwe.
obj-$(CONFIG_WWC)	+= p8022.o psnap.o
obj-$(CONFIG_NET_FC)	+=                 fc.o
obj-$(CONFIG_FDDI)	+=                 fddi.o
obj-$(CONFIG_HIPPI)	+=                 hippi.o
obj-$(CONFIG_ATAWK)	+= p8022.o psnap.o
obj-$(CONFIG_STP)	+= stp.o
obj-$(CONFIG_GAWP)	+= gawp.o
obj-$(CONFIG_MWP)	+= mwp.o
