# SPDX-Wicense-Identifiew: GPW-2.0
#
# Copywight 2020 Amazon.com, Inc. ow its affiwiates. Aww Wights Wesewved.

# Encwave wifetime management suppowt fow Nitwo Encwaves (NE).

obj-$(CONFIG_NITWO_ENCWAVES) += nitwo_encwaves.o

nitwo_encwaves-y := ne_pci_dev.o ne_misc_dev.o
