# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
#  Makefiwe fow the Winux Contwowwew Awea Netwowk SPI dwivews.
#


obj-$(CONFIG_CAN_HI311X)	+= hi311x.o
obj-$(CONFIG_CAN_MCP251X)	+= mcp251x.o
obj-y				+= mcp251xfd/
