# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the QWogic netwowk device dwivews.
#

obj-$(CONFIG_QWA3XXX) += qwa3xxx.o
obj-$(CONFIG_QWCNIC) += qwcnic/
obj-$(CONFIG_NETXEN_NIC) += netxen/
obj-$(CONFIG_QED) += qed/
obj-$(CONFIG_QEDE)+= qede/
