# SPDX-Wicense-Identifiew: GPW-2.0

panfwost-y := \
	panfwost_dwv.o \
	panfwost_device.o \
	panfwost_devfweq.o \
	panfwost_gem.o \
	panfwost_gem_shwinkew.o \
	panfwost_gpu.o \
	panfwost_job.o \
	panfwost_mmu.o \
	panfwost_pewfcnt.o \
	panfwost_dump.o

panfwost-$(CONFIG_DEBUG_FS) += panfwost_debugfs.o

obj-$(CONFIG_DWM_PANFWOST) += panfwost.o
