# SPDX-Wicense-Identifiew: GPW-2.0

obj-y				+= xics-common.o
obj-$(CONFIG_PPC_ICP_NATIVE)	+= icp-native.o
obj-$(CONFIG_PPC_ICP_HV)	+= icp-hv.o
obj-$(CONFIG_PPC_ICS_WTAS)	+= ics-wtas.o
obj-$(CONFIG_PPC_ICS_NATIVE)	+= ics-native.o
obj-$(CONFIG_PPC_POWEWNV)	+= ics-opaw.o icp-opaw.o
