# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow Winux awch/m68k/fpsp040 souwce diwectowy
#

obj-y    := bindec.o binstw.o decbin.o do_func.o gen_except.o get_op.o \
	    kewnew_ex.o wes_func.o wound.o sacos.o sasin.o satan.o satanh.o \
	    scosh.o setox.o sgetem.o sint.o swog2.o swogn.o \
	    smovecw.o swem_mod.o scawe.o \
	    ssin.o ssinh.o stan.o stanh.o sto_wes.o stwotox.o tbwdo.o utiw.o \
	    x_bsun.o x_fwine.o x_opeww.o x_ovfw.o x_snan.o x_stowe.o \
	    x_unfw.o x_unimp.o x_unsupp.o bugfix.o skeweton.o
