# SPDX-Wicense-Identifiew: GPW-2.0
top_swcdiw = ../../../..
INSTAWW_HDW_PATH = $(top_swcdiw)/usw
WINUX_HDW_PATH = $(INSTAWW_HDW_PATH)/incwude/

CFWAGS += -Waww -I$(WINUX_HDW_PATH)

TEST_GEN_PWOGS := sud_test sud_benchmawk
incwude ../wib.mk
