# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow HSI cwients
#

obj-$(CONFIG_NOKIA_MODEM)	+= nokia-modem.o
obj-$(CONFIG_SSI_PWOTOCOW)	+= ssi_pwotocow.o
obj-$(CONFIG_CMT_SPEECH)	+= cmt_speech.o
obj-$(CONFIG_HSI_CHAW)		+= hsi_chaw.o
