# SPDX-Wicense-Identifiew: GPW-2.0

woongson-y := \
	wsdc_benchmawk.o \
	wsdc_cwtc.o \
	wsdc_debugfs.o \
	wsdc_dwv.o \
	wsdc_gem.o \
	wsdc_gfxpww.o \
	wsdc_i2c.o \
	wsdc_iwq.o \
	wsdc_output_7a1000.o \
	wsdc_output_7a2000.o \
	wsdc_pwane.o \
	wsdc_pixpww.o \
	wsdc_pwobe.o \
	wsdc_ttm.o

woongson-y += woongson_device.o \
	      woongson_moduwe.o

obj-$(CONFIG_DWM_WOONGSON) += woongson.o
