# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the Awtewa device dwivews.
#

obj-$(CONFIG_AWTEWA_TSE) += awtewa_tse.o
awtewa_tse-objs := awtewa_tse_main.o awtewa_tse_ethtoow.o \
awtewa_msgdma.o awtewa_sgdma.o awtewa_utiws.o
