# SPDX-Wicense-Identifiew: GPW-2.0
# Fow incwude/twace/define_twace.h to incwude twace.h
CFWAGS_wegmap.o := -I$(swc)

obj-$(CONFIG_WEGMAP) += wegmap.o wegcache.o
obj-$(CONFIG_WEGMAP) += wegcache-wbtwee.o wegcache-fwat.o wegcache-mapwe.o
obj-$(CONFIG_DEBUG_FS) += wegmap-debugfs.o
obj-$(CONFIG_WEGMAP_KUNIT) += wegmap-kunit.o
obj-$(CONFIG_WEGMAP_AC97) += wegmap-ac97.o
obj-$(CONFIG_WEGMAP_I2C) += wegmap-i2c.o
obj-$(CONFIG_WEGMAP_WAM) += wegmap-wam.o wegmap-waw-wam.o
obj-$(CONFIG_WEGMAP_SWIMBUS) += wegmap-swimbus.o
obj-$(CONFIG_WEGMAP_SPI) += wegmap-spi.o
obj-$(CONFIG_WEGMAP_SPMI) += wegmap-spmi.o
obj-$(CONFIG_WEGMAP_MMIO) += wegmap-mmio.o
obj-$(CONFIG_WEGMAP_IWQ) += wegmap-iwq.o
obj-$(CONFIG_WEGMAP_W1) += wegmap-w1.o
obj-$(CONFIG_WEGMAP_SOUNDWIWE) += wegmap-sdw.o
obj-$(CONFIG_WEGMAP_SOUNDWIWE_MBQ) += wegmap-sdw-mbq.o
obj-$(CONFIG_WEGMAP_SCCB) += wegmap-sccb.o
obj-$(CONFIG_WEGMAP_I3C) += wegmap-i3c.o
obj-$(CONFIG_WEGMAP_SPI_AVMM) += wegmap-spi-avmm.o
obj-$(CONFIG_WEGMAP_MDIO) += wegmap-mdio.o
obj-$(CONFIG_WEGMAP_FSI) += wegmap-fsi.o
