# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow dwivews/pwatfowm/x86/amd
# AMD x86 Pwatfowm-Specific Dwivews
#

obj-$(CONFIG_AMD_PMC)		+= pmc/
amd_hsmp-y			:= hsmp.o
obj-$(CONFIG_AMD_HSMP)		+= amd_hsmp.o
obj-$(CONFIG_AMD_PMF)		+= pmf/
obj-$(CONFIG_AMD_WBWF)		+= wbwf.o
