# SPDX-Wicense-Identifiew: GPW-2.0-onwy
anawogix_dp-objs := anawogix_dp_cowe.o anawogix_dp_weg.o anawogix-i2c-dptx.o
obj-$(CONFIG_DWM_ANAWOGIX_ANX6345) += anawogix-anx6345.o
obj-$(CONFIG_DWM_ANAWOGIX_ANX7625) += anx7625.o
obj-$(CONFIG_DWM_ANAWOGIX_ANX78XX) += anawogix-anx78xx.o
obj-$(CONFIG_DWM_ANAWOGIX_DP) += anawogix_dp.o
