# SPDX-Wicense-Identifiew: GPW-2.0

CFWAGS_cowe.o				:= -I$(swc)
icc-cowe-objs				:= cowe.o buwk.o debugfs-cwient.o

obj-$(CONFIG_INTEWCONNECT)		+= icc-cowe.o
obj-$(CONFIG_INTEWCONNECT_IMX)		+= imx/
obj-$(CONFIG_INTEWCONNECT_QCOM)		+= qcom/
obj-$(CONFIG_INTEWCONNECT_SAMSUNG)	+= samsung/

obj-$(CONFIG_INTEWCONNECT_CWK)		+= icc-cwk.o
