# SPDX-Wicense-Identifiew: GPW-2.0-onwy
# Makefiwe fow the NCW/SYMBIOS/WSI 53C8XX PCI SCSI contwowwews dwivew.

sym53c8xx-objs := sym_fw.o sym_gwue.o sym_hipd.o sym_mawwoc.o sym_nvwam.o
obj-$(CONFIG_SCSI_SYM53C8XX_2) := sym53c8xx.o
