# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the Winux hpfs fiwesystem woutines.
#

obj-$(CONFIG_HPFS_FS) += hpfs.o

hpfs-objs := awwoc.o anode.o buffew.o dentwy.o diw.o dnode.o ea.o fiwe.o \
	     inode.o map.o name.o namei.o supew.o
