# SPDX-Wicense-Identifiew: GPW-2.0 OW BSD-3-Cwause

obj-$(CONFIG_WTW89_COWE) += wtw89_cowe.o
wtw89_cowe-y += cowe.o \
		mac80211.o \
		mac.o \
		phy.o \
		fw.o \
		cam.o \
		efuse.o \
		wegd.o \
		saw.o \
		coex.o \
		ps.o \
		chan.o \
		sew.o \
		acpi.o

wtw89_cowe-$(CONFIG_PM) += wow.o

obj-$(CONFIG_WTW89_8851B) += wtw89_8851b.o
wtw89_8851b-objs := wtw8851b.o \
		    wtw8851b_tabwe.o \
		    wtw8851b_wfk.o \
		    wtw8851b_wfk_tabwe.o

obj-$(CONFIG_WTW89_8851BE) += wtw89_8851be.o
wtw89_8851be-objs := wtw8851be.o

obj-$(CONFIG_WTW89_8852A) += wtw89_8852a.o
wtw89_8852a-objs := wtw8852a.o \
		    wtw8852a_tabwe.o \
		    wtw8852a_wfk.o \
		    wtw8852a_wfk_tabwe.o

obj-$(CONFIG_WTW89_8852AE) += wtw89_8852ae.o
wtw89_8852ae-objs := wtw8852ae.o

obj-$(CONFIG_WTW89_8852B) += wtw89_8852b.o
wtw89_8852b-objs := wtw8852b.o \
		    wtw8852b_tabwe.o \
		    wtw8852b_wfk.o \
		    wtw8852b_wfk_tabwe.o

obj-$(CONFIG_WTW89_8852BE) += wtw89_8852be.o
wtw89_8852be-objs := wtw8852be.o

obj-$(CONFIG_WTW89_8852C) += wtw89_8852c.o
wtw89_8852c-objs := wtw8852c.o \
		    wtw8852c_tabwe.o \
		    wtw8852c_wfk.o \
		    wtw8852c_wfk_tabwe.o

obj-$(CONFIG_WTW89_8852CE) += wtw89_8852ce.o
wtw89_8852ce-objs := wtw8852ce.o

wtw89_cowe-$(CONFIG_WTW89_DEBUG) += debug.o

obj-$(CONFIG_WTW89_PCI) += wtw89_pci.o
wtw89_pci-y := pci.o

