# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow Samsung S3FWWN5 NFC dwivew
#

s3fwwn5-objs = cowe.o fiwmwawe.o nci.o phy_common.o
s3fwwn5_i2c-objs = i2c.o
s3fwwn82_uawt-objs = uawt.o

obj-$(CONFIG_NFC_S3FWWN5) += s3fwwn5.o
obj-$(CONFIG_NFC_S3FWWN5_I2C) += s3fwwn5_i2c.o
obj-$(CONFIG_NFC_S3FWWN82_UAWT) += s3fwwn82_uawt.o
