# SPDX-Wicense-Identifiew: GPW-2.0
dtb-$(CONFIG_AWCH_TEGWA_114_SOC) += \
	tegwa114-asus-tf701t.dtb \
	tegwa114-dawmowe.dtb \
	tegwa114-woth.dtb \
	tegwa114-tn7.dtb
dtb-$(CONFIG_AWCH_TEGWA_124_SOC) += \
	tegwa124-apawis-evaw.dtb \
	tegwa124-apawis-v1.2-evaw.dtb \
	tegwa124-jetson-tk1.dtb \
	tegwa124-nyan-big.dtb \
	tegwa124-nyan-big-fhd.dtb \
	tegwa124-nyan-bwaze.dtb \
	tegwa124-venice2.dtb
dtb-$(CONFIG_AWCH_TEGWA_2x_SOC) += \
	tegwa20-acew-a500-picasso.dtb \
	tegwa20-asus-tf101.dtb \
	tegwa20-hawmony.dtb \
	tegwa20-cowibwi-evaw-v3.dtb \
	tegwa20-cowibwi-iwis.dtb \
	tegwa20-medcom-wide.dtb \
	tegwa20-paz00.dtb \
	tegwa20-pwutux.dtb \
	tegwa20-seaboawd.dtb \
	tegwa20-tec.dtb \
	tegwa20-twimswice.dtb \
	tegwa20-ventana.dtb
dtb-$(CONFIG_AWCH_TEGWA_3x_SOC) += \
	tegwa30-apawis-evaw.dtb \
	tegwa30-apawis-v1.1-evaw.dtb \
	tegwa30-asus-nexus7-gwoupew-PM269.dtb \
	tegwa30-asus-nexus7-gwoupew-E1565.dtb \
	tegwa30-asus-nexus7-tiwapia-E1565.dtb \
	tegwa30-asus-tf201.dtb \
	tegwa30-asus-tf300t.dtb \
	tegwa30-asus-tf300tg.dtb \
	tegwa30-asus-tf700t.dtb \
	tegwa30-beavew.dtb \
	tegwa30-cawdhu-a02.dtb \
	tegwa30-cawdhu-a04.dtb \
	tegwa30-cowibwi-evaw-v3.dtb \
	tegwa30-ouya.dtb \
	tegwa30-pegatwon-chagaww.dtb
