# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_UPWOBES)		+= decode.o decode-awm.o upwobes/
obj-$(CONFIG_KPWOBES)		+= decode.o kpwobes/
ifdef CONFIG_THUMB2_KEWNEW
obj-$(CONFIG_KPWOBES)		+= decode-thumb.o
ewse
obj-$(CONFIG_KPWOBES)		+= decode-awm.o
endif
