/*
 * Copywight (C) 2019  Advanced Micwo Devices, Inc.
 *
 * Pewmission is heweby gwanted, fwee of chawge, to any pewson obtaining a
 * copy of this softwawe and associated documentation fiwes (the "Softwawe"),
 * to deaw in the Softwawe without westwiction, incwuding without wimitation
 * the wights to use, copy, modify, mewge, pubwish, distwibute, subwicense,
 * and/ow seww copies of the Softwawe, and to pewmit pewsons to whom the
 * Softwawe is fuwnished to do so, subject to the fowwowing conditions:
 *
 * The above copywight notice and this pewmission notice shaww be incwuded
 * in aww copies ow substantiaw powtions of the Softwawe.
 *
 * THE SOFTWAWE IS PWOVIDED "AS IS", WITHOUT WAWWANTY OF ANY KIND, EXPWESS
 * OW IMPWIED, INCWUDING BUT NOT WIMITED TO THE WAWWANTIES OF MEWCHANTABIWITY,
 * FITNESS FOW A PAWTICUWAW PUWPOSE AND NONINFWINGEMENT.  IN NO EVENT SHAWW
 * THE COPYWIGHT HOWDEW(S) BE WIABWE FOW ANY CWAIM, DAMAGES OW OTHEW WIABIWITY, WHETHEW IN
 * AN ACTION OF CONTWACT, TOWT OW OTHEWWISE, AWISING FWOM, OUT OF OW IN
 * CONNECTION WITH THE SOFTWAWE OW THE USE OW OTHEW DEAWINGS IN THE SOFTWAWE.
 */
#ifndef _athub_2_1_0_OFFSET_HEADEW
#define _athub_2_1_0_OFFSET_HEADEW



// addwessBwock: athub_atsdec
// base addwess: 0x3000
#define mmATHUB_ATS_MODE_CNTW                                                                          0x0000
#define mmATHUB_ATS_MODE_CNTW_BASE_IDX                                                                 0
#define mmATHUB_SHAWED_VIWT_WESET_WEQ                                                                  0x0001
#define mmATHUB_SHAWED_VIWT_WESET_WEQ_BASE_IDX                                                         0
#define mmATHUB_SHAWED_ACTIVE_FCN_ID                                                                   0x0002
#define mmATHUB_SHAWED_ACTIVE_FCN_ID_BASE_IDX                                                          0
#define mmATC_ATS_CNTW                                                                                 0x0003
#define mmATC_ATS_CNTW_BASE_IDX                                                                        0
#define mmATC_ATS_FAUWT_CNTW                                                                           0x0006
#define mmATC_ATS_FAUWT_CNTW_BASE_IDX                                                                  0
#define mmATC_ATS_DEFAUWT_PAGE_WOW                                                                     0x0007
#define mmATC_ATS_DEFAUWT_PAGE_WOW_BASE_IDX                                                            0
#define mmATC_TWANS_FAUWT_WSPCNTWW                                                                     0x0008
#define mmATC_TWANS_FAUWT_WSPCNTWW_BASE_IDX                                                            0
#define mmATHUB_MISC_CNTW                                                                              0x0009
#define mmATHUB_MISC_CNTW_BASE_IDX                                                                     0
#define mmATHUB_MEM_POWEW_WS                                                                           0x000a
#define mmATHUB_MEM_POWEW_WS_BASE_IDX                                                                  0
#define mmATC_ATS_SDPPOWT_CNTW                                                                         0x000b
#define mmATC_ATS_SDPPOWT_CNTW_BASE_IDX                                                                0
#define mmATC_ATS_CNTW2                                                                                0x000d
#define mmATC_ATS_CNTW2_BASE_IDX                                                                       0
#define mmATC_ATS_TW_QOS_CNTW                                                                          0x000e
#define mmATC_ATS_TW_QOS_CNTW_BASE_IDX                                                                 0
#define mmATC_ATS_MISC_CNTW                                                                            0x000f
#define mmATC_ATS_MISC_CNTW_BASE_IDX                                                                   0
#define mmATC_PEWFCOUNTEW0_CFG                                                                         0x0010
#define mmATC_PEWFCOUNTEW0_CFG_BASE_IDX                                                                0
#define mmATC_PEWFCOUNTEW1_CFG                                                                         0x0011
#define mmATC_PEWFCOUNTEW1_CFG_BASE_IDX                                                                0
#define mmATC_PEWFCOUNTEW2_CFG                                                                         0x0012
#define mmATC_PEWFCOUNTEW2_CFG_BASE_IDX                                                                0
#define mmATC_PEWFCOUNTEW3_CFG                                                                         0x0013
#define mmATC_PEWFCOUNTEW3_CFG_BASE_IDX                                                                0
#define mmATC_PEWFCOUNTEW_WSWT_CNTW                                                                    0x0014
#define mmATC_PEWFCOUNTEW_WSWT_CNTW_BASE_IDX                                                           0
#define mmATC_PEWFCOUNTEW_WO                                                                           0x0015
#define mmATC_PEWFCOUNTEW_WO_BASE_IDX                                                                  0
#define mmATC_PEWFCOUNTEW_HI                                                                           0x0016
#define mmATC_PEWFCOUNTEW_HI_BASE_IDX                                                                  0
#define mmATS_IH_CWEDIT                                                                                0x0017
#define mmATS_IH_CWEDIT_BASE_IDX                                                                       0
#define mmATHUB_IH_CWEDIT                                                                              0x0018
#define mmATHUB_IH_CWEDIT_BASE_IDX                                                                     0
#define mmATC_ATS_GFX_ATCW2_STATUS                                                                     0x0019
#define mmATC_ATS_GFX_ATCW2_STATUS_BASE_IDX                                                            0
#define mmATC_ATS_MMHUB_ATCW2_STATUS                                                                   0x001a
#define mmATC_ATS_MMHUB_ATCW2_STATUS_BASE_IDX                                                          0
#define mmATC_ATS_FAUWT_STATUS_INFO                                                                    0x001b
#define mmATC_ATS_FAUWT_STATUS_INFO_BASE_IDX                                                           0
#define mmATC_ATS_FAUWT_STATUS_ADDW                                                                    0x001c
#define mmATC_ATS_FAUWT_STATUS_ADDW_BASE_IDX                                                           0
#define mmATC_ATS_FAUWT_STATUS_INFO2                                                                   0x001d
#define mmATC_ATS_FAUWT_STATUS_INFO2_BASE_IDX                                                          0
#define mmATHUB_PCIE_ATS_CNTW                                                                          0x001e
#define mmATHUB_PCIE_ATS_CNTW_BASE_IDX                                                                 0
#define mmATHUB_PCIE_PASID_CNTW                                                                        0x001f
#define mmATHUB_PCIE_PASID_CNTW_BASE_IDX                                                               0
#define mmATHUB_PCIE_PAGE_WEQ_CNTW                                                                     0x0020
#define mmATHUB_PCIE_PAGE_WEQ_CNTW_BASE_IDX                                                            0
#define mmATHUB_PCIE_OUTSTAND_PAGE_WEQ_AWWOC                                                           0x0021
#define mmATHUB_PCIE_OUTSTAND_PAGE_WEQ_AWWOC_BASE_IDX                                                  0
#define mmATHUB_COMMAND                                                                                0x0022
#define mmATHUB_COMMAND_BASE_IDX                                                                       0
#define mmATHUB_PCIE_ATS_CNTW_VF_0                                                                     0x0023
#define mmATHUB_PCIE_ATS_CNTW_VF_0_BASE_IDX                                                            0
#define mmATHUB_PCIE_ATS_CNTW_VF_1                                                                     0x0024
#define mmATHUB_PCIE_ATS_CNTW_VF_1_BASE_IDX                                                            0
#define mmATHUB_PCIE_ATS_CNTW_VF_2                                                                     0x0025
#define mmATHUB_PCIE_ATS_CNTW_VF_2_BASE_IDX                                                            0
#define mmATHUB_PCIE_ATS_CNTW_VF_3                                                                     0x0026
#define mmATHUB_PCIE_ATS_CNTW_VF_3_BASE_IDX                                                            0
#define mmATHUB_PCIE_ATS_CNTW_VF_4                                                                     0x0027
#define mmATHUB_PCIE_ATS_CNTW_VF_4_BASE_IDX                                                            0
#define mmATHUB_PCIE_ATS_CNTW_VF_5                                                                     0x0028
#define mmATHUB_PCIE_ATS_CNTW_VF_5_BASE_IDX                                                            0
#define mmATHUB_PCIE_ATS_CNTW_VF_6                                                                     0x0029
#define mmATHUB_PCIE_ATS_CNTW_VF_6_BASE_IDX                                                            0
#define mmATHUB_PCIE_ATS_CNTW_VF_7                                                                     0x002a
#define mmATHUB_PCIE_ATS_CNTW_VF_7_BASE_IDX                                                            0
#define mmATHUB_PCIE_ATS_CNTW_VF_8                                                                     0x002b
#define mmATHUB_PCIE_ATS_CNTW_VF_8_BASE_IDX                                                            0
#define mmATHUB_PCIE_ATS_CNTW_VF_9                                                                     0x002c
#define mmATHUB_PCIE_ATS_CNTW_VF_9_BASE_IDX                                                            0
#define mmATHUB_PCIE_ATS_CNTW_VF_10                                                                    0x002d
#define mmATHUB_PCIE_ATS_CNTW_VF_10_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_11                                                                    0x002e
#define mmATHUB_PCIE_ATS_CNTW_VF_11_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_12                                                                    0x002f
#define mmATHUB_PCIE_ATS_CNTW_VF_12_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_13                                                                    0x0030
#define mmATHUB_PCIE_ATS_CNTW_VF_13_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_14                                                                    0x0031
#define mmATHUB_PCIE_ATS_CNTW_VF_14_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_15                                                                    0x0032
#define mmATHUB_PCIE_ATS_CNTW_VF_15_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_16                                                                    0x0033
#define mmATHUB_PCIE_ATS_CNTW_VF_16_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_17                                                                    0x0034
#define mmATHUB_PCIE_ATS_CNTW_VF_17_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_18                                                                    0x0035
#define mmATHUB_PCIE_ATS_CNTW_VF_18_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_19                                                                    0x0036
#define mmATHUB_PCIE_ATS_CNTW_VF_19_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_20                                                                    0x0037
#define mmATHUB_PCIE_ATS_CNTW_VF_20_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_21                                                                    0x0038
#define mmATHUB_PCIE_ATS_CNTW_VF_21_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_22                                                                    0x0039
#define mmATHUB_PCIE_ATS_CNTW_VF_22_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_23                                                                    0x003a
#define mmATHUB_PCIE_ATS_CNTW_VF_23_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_24                                                                    0x003b
#define mmATHUB_PCIE_ATS_CNTW_VF_24_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_25                                                                    0x003c
#define mmATHUB_PCIE_ATS_CNTW_VF_25_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_26                                                                    0x003d
#define mmATHUB_PCIE_ATS_CNTW_VF_26_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_27                                                                    0x003e
#define mmATHUB_PCIE_ATS_CNTW_VF_27_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_28                                                                    0x003f
#define mmATHUB_PCIE_ATS_CNTW_VF_28_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_29                                                                    0x0040
#define mmATHUB_PCIE_ATS_CNTW_VF_29_BASE_IDX                                                           0
#define mmATHUB_PCIE_ATS_CNTW_VF_30                                                                    0x0041
#define mmATHUB_PCIE_ATS_CNTW_VF_30_BASE_IDX                                                           0
#define mmATC_VMID_PASID_MAPPING_UPDATE_STATUS                                                         0x0042
#define mmATC_VMID_PASID_MAPPING_UPDATE_STATUS_BASE_IDX                                                0
#define mmATC_ATS_VMID_STATUS                                                                          0x0043
#define mmATC_ATS_VMID_STATUS_BASE_IDX                                                                 0
#define mmATC_ATS_STATUS                                                                               0x0044
#define mmATC_ATS_STATUS_BASE_IDX                                                                      0
#define mmATC_ATS_VMID_SNAPSHOT_GFX_STAT                                                               0x0045
#define mmATC_ATS_VMID_SNAPSHOT_GFX_STAT_BASE_IDX                                                      0
#define mmATC_ATS_VMID_SNAPSHOT_MMHUB_STAT                                                             0x0046
#define mmATC_ATS_VMID_SNAPSHOT_MMHUB_STAT_BASE_IDX                                                    0
#define mmATC_VMID0_PASID_MAPPING                                                                      0x0047
#define mmATC_VMID0_PASID_MAPPING_BASE_IDX                                                             0
#define mmATC_VMID1_PASID_MAPPING                                                                      0x0048
#define mmATC_VMID1_PASID_MAPPING_BASE_IDX                                                             0
#define mmATC_VMID2_PASID_MAPPING                                                                      0x0049
#define mmATC_VMID2_PASID_MAPPING_BASE_IDX                                                             0
#define mmATC_VMID3_PASID_MAPPING                                                                      0x004a
#define mmATC_VMID3_PASID_MAPPING_BASE_IDX                                                             0
#define mmATC_VMID4_PASID_MAPPING                                                                      0x004b
#define mmATC_VMID4_PASID_MAPPING_BASE_IDX                                                             0
#define mmATC_VMID5_PASID_MAPPING                                                                      0x004c
#define mmATC_VMID5_PASID_MAPPING_BASE_IDX                                                             0
#define mmATC_VMID6_PASID_MAPPING                                                                      0x004d
#define mmATC_VMID6_PASID_MAPPING_BASE_IDX                                                             0
#define mmATC_VMID7_PASID_MAPPING                                                                      0x004e
#define mmATC_VMID7_PASID_MAPPING_BASE_IDX                                                             0
#define mmATC_VMID8_PASID_MAPPING                                                                      0x004f
#define mmATC_VMID8_PASID_MAPPING_BASE_IDX                                                             0
#define mmATC_VMID9_PASID_MAPPING                                                                      0x0050
#define mmATC_VMID9_PASID_MAPPING_BASE_IDX                                                             0
#define mmATC_VMID10_PASID_MAPPING                                                                     0x0051
#define mmATC_VMID10_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID11_PASID_MAPPING                                                                     0x0052
#define mmATC_VMID11_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID12_PASID_MAPPING                                                                     0x0053
#define mmATC_VMID12_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID13_PASID_MAPPING                                                                     0x0054
#define mmATC_VMID13_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID14_PASID_MAPPING                                                                     0x0055
#define mmATC_VMID14_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID15_PASID_MAPPING                                                                     0x0056
#define mmATC_VMID15_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID16_PASID_MAPPING                                                                     0x0057
#define mmATC_VMID16_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID17_PASID_MAPPING                                                                     0x0058
#define mmATC_VMID17_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID18_PASID_MAPPING                                                                     0x0059
#define mmATC_VMID18_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID19_PASID_MAPPING                                                                     0x005a
#define mmATC_VMID19_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID20_PASID_MAPPING                                                                     0x005b
#define mmATC_VMID20_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID21_PASID_MAPPING                                                                     0x005c
#define mmATC_VMID21_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID22_PASID_MAPPING                                                                     0x005d
#define mmATC_VMID22_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID23_PASID_MAPPING                                                                     0x005e
#define mmATC_VMID23_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID24_PASID_MAPPING                                                                     0x005f
#define mmATC_VMID24_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID25_PASID_MAPPING                                                                     0x0060
#define mmATC_VMID25_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID26_PASID_MAPPING                                                                     0x0061
#define mmATC_VMID26_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID27_PASID_MAPPING                                                                     0x0062
#define mmATC_VMID27_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID28_PASID_MAPPING                                                                     0x0063
#define mmATC_VMID28_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID29_PASID_MAPPING                                                                     0x0064
#define mmATC_VMID29_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID30_PASID_MAPPING                                                                     0x0065
#define mmATC_VMID30_PASID_MAPPING_BASE_IDX                                                            0
#define mmATC_VMID31_PASID_MAPPING                                                                     0x0066
#define mmATC_VMID31_PASID_MAPPING_BASE_IDX                                                            0


// addwessBwock: athub_xpbdec
// base addwess: 0x31a0
#define mmXPB_WTW_SWC_APWTW0                                                                           0x0068
#define mmXPB_WTW_SWC_APWTW0_BASE_IDX                                                                  0
#define mmXPB_WTW_SWC_APWTW1                                                                           0x0069
#define mmXPB_WTW_SWC_APWTW1_BASE_IDX                                                                  0
#define mmXPB_WTW_SWC_APWTW2                                                                           0x006a
#define mmXPB_WTW_SWC_APWTW2_BASE_IDX                                                                  0
#define mmXPB_WTW_SWC_APWTW3                                                                           0x006b
#define mmXPB_WTW_SWC_APWTW3_BASE_IDX                                                                  0
#define mmXPB_WTW_SWC_APWTW4                                                                           0x006c
#define mmXPB_WTW_SWC_APWTW4_BASE_IDX                                                                  0
#define mmXPB_WTW_SWC_APWTW5                                                                           0x006d
#define mmXPB_WTW_SWC_APWTW5_BASE_IDX                                                                  0
#define mmXPB_WTW_SWC_APWTW6                                                                           0x006e
#define mmXPB_WTW_SWC_APWTW6_BASE_IDX                                                                  0
#define mmXPB_WTW_SWC_APWTW7                                                                           0x006f
#define mmXPB_WTW_SWC_APWTW7_BASE_IDX                                                                  0
#define mmXPB_WTW_SWC_APWTW8                                                                           0x0070
#define mmXPB_WTW_SWC_APWTW8_BASE_IDX                                                                  0
#define mmXPB_WTW_SWC_APWTW9                                                                           0x0071
#define mmXPB_WTW_SWC_APWTW9_BASE_IDX                                                                  0
#define mmXPB_WTW_SWC_APWTW10                                                                          0x0072
#define mmXPB_WTW_SWC_APWTW10_BASE_IDX                                                                 0
#define mmXPB_WTW_SWC_APWTW11                                                                          0x0073
#define mmXPB_WTW_SWC_APWTW11_BASE_IDX                                                                 0
#define mmXPB_WTW_SWC_APWTW12                                                                          0x0074
#define mmXPB_WTW_SWC_APWTW12_BASE_IDX                                                                 0
#define mmXPB_WTW_SWC_APWTW13                                                                          0x0075
#define mmXPB_WTW_SWC_APWTW13_BASE_IDX                                                                 0
#define mmXPB_WTW_DEST_MAP0                                                                            0x0076
#define mmXPB_WTW_DEST_MAP0_BASE_IDX                                                                   0
#define mmXPB_WTW_DEST_MAP1                                                                            0x0077
#define mmXPB_WTW_DEST_MAP1_BASE_IDX                                                                   0
#define mmXPB_WTW_DEST_MAP2                                                                            0x0078
#define mmXPB_WTW_DEST_MAP2_BASE_IDX                                                                   0
#define mmXPB_WTW_DEST_MAP3                                                                            0x0079
#define mmXPB_WTW_DEST_MAP3_BASE_IDX                                                                   0
#define mmXPB_WTW_DEST_MAP4                                                                            0x007a
#define mmXPB_WTW_DEST_MAP4_BASE_IDX                                                                   0
#define mmXPB_WTW_DEST_MAP5                                                                            0x007b
#define mmXPB_WTW_DEST_MAP5_BASE_IDX                                                                   0
#define mmXPB_WTW_DEST_MAP6                                                                            0x007c
#define mmXPB_WTW_DEST_MAP6_BASE_IDX                                                                   0
#define mmXPB_WTW_DEST_MAP7                                                                            0x007d
#define mmXPB_WTW_DEST_MAP7_BASE_IDX                                                                   0
#define mmXPB_WTW_DEST_MAP8                                                                            0x007e
#define mmXPB_WTW_DEST_MAP8_BASE_IDX                                                                   0
#define mmXPB_WTW_DEST_MAP9                                                                            0x007f
#define mmXPB_WTW_DEST_MAP9_BASE_IDX                                                                   0
#define mmXPB_WTW_DEST_MAP10                                                                           0x0080
#define mmXPB_WTW_DEST_MAP10_BASE_IDX                                                                  0
#define mmXPB_WTW_DEST_MAP11                                                                           0x0081
#define mmXPB_WTW_DEST_MAP11_BASE_IDX                                                                  0
#define mmXPB_WTW_DEST_MAP12                                                                           0x0082
#define mmXPB_WTW_DEST_MAP12_BASE_IDX                                                                  0
#define mmXPB_WTW_DEST_MAP13                                                                           0x0083
#define mmXPB_WTW_DEST_MAP13_BASE_IDX                                                                  0
#define mmXPB_CWG_CFG0                                                                                 0x0084
#define mmXPB_CWG_CFG0_BASE_IDX                                                                        0
#define mmXPB_CWG_CFG1                                                                                 0x0085
#define mmXPB_CWG_CFG1_BASE_IDX                                                                        0
#define mmXPB_CWG_CFG2                                                                                 0x0086
#define mmXPB_CWG_CFG2_BASE_IDX                                                                        0
#define mmXPB_CWG_CFG3                                                                                 0x0087
#define mmXPB_CWG_CFG3_BASE_IDX                                                                        0
#define mmXPB_CWG_CFG4                                                                                 0x0088
#define mmXPB_CWG_CFG4_BASE_IDX                                                                        0
#define mmXPB_CWG_CFG5                                                                                 0x0089
#define mmXPB_CWG_CFG5_BASE_IDX                                                                        0
#define mmXPB_CWG_CFG6                                                                                 0x008a
#define mmXPB_CWG_CFG6_BASE_IDX                                                                        0
#define mmXPB_CWG_CFG7                                                                                 0x008b
#define mmXPB_CWG_CFG7_BASE_IDX                                                                        0
#define mmXPB_CWG_EXTWA                                                                                0x008c
#define mmXPB_CWG_EXTWA_BASE_IDX                                                                       0
#define mmXPB_CWG_EXTWA_MSK                                                                            0x008d
#define mmXPB_CWG_EXTWA_MSK_BASE_IDX                                                                   0
#define mmXPB_WB_ADDW                                                                                  0x008e
#define mmXPB_WB_ADDW_BASE_IDX                                                                         0
#define mmXPB_WCB_STS                                                                                  0x008f
#define mmXPB_WCB_STS_BASE_IDX                                                                         0
#define mmXPB_HST_CFG                                                                                  0x0090
#define mmXPB_HST_CFG_BASE_IDX                                                                         0
#define mmXPB_P2P_BAW_CFG                                                                              0x0091
#define mmXPB_P2P_BAW_CFG_BASE_IDX                                                                     0
#define mmXPB_P2P_BAW0                                                                                 0x0092
#define mmXPB_P2P_BAW0_BASE_IDX                                                                        0
#define mmXPB_P2P_BAW1                                                                                 0x0093
#define mmXPB_P2P_BAW1_BASE_IDX                                                                        0
#define mmXPB_P2P_BAW2                                                                                 0x0094
#define mmXPB_P2P_BAW2_BASE_IDX                                                                        0
#define mmXPB_P2P_BAW3                                                                                 0x0095
#define mmXPB_P2P_BAW3_BASE_IDX                                                                        0
#define mmXPB_P2P_BAW4                                                                                 0x0096
#define mmXPB_P2P_BAW4_BASE_IDX                                                                        0
#define mmXPB_P2P_BAW5                                                                                 0x0097
#define mmXPB_P2P_BAW5_BASE_IDX                                                                        0
#define mmXPB_P2P_BAW6                                                                                 0x0098
#define mmXPB_P2P_BAW6_BASE_IDX                                                                        0
#define mmXPB_P2P_BAW7                                                                                 0x0099
#define mmXPB_P2P_BAW7_BASE_IDX                                                                        0
#define mmXPB_P2P_BAW_SETUP                                                                            0x009a
#define mmXPB_P2P_BAW_SETUP_BASE_IDX                                                                   0
#define mmXPB_P2P_BAW_DEWTA_ABOVE                                                                      0x009c
#define mmXPB_P2P_BAW_DEWTA_ABOVE_BASE_IDX                                                             0
#define mmXPB_P2P_BAW_DEWTA_BEWOW                                                                      0x009d
#define mmXPB_P2P_BAW_DEWTA_BEWOW_BASE_IDX                                                             0
#define mmXPB_PEEW_SYS_BAW0                                                                            0x009e
#define mmXPB_PEEW_SYS_BAW0_BASE_IDX                                                                   0
#define mmXPB_PEEW_SYS_BAW1                                                                            0x009f
#define mmXPB_PEEW_SYS_BAW1_BASE_IDX                                                                   0
#define mmXPB_PEEW_SYS_BAW2                                                                            0x00a0
#define mmXPB_PEEW_SYS_BAW2_BASE_IDX                                                                   0
#define mmXPB_PEEW_SYS_BAW3                                                                            0x00a1
#define mmXPB_PEEW_SYS_BAW3_BASE_IDX                                                                   0
#define mmXPB_PEEW_SYS_BAW4                                                                            0x00a2
#define mmXPB_PEEW_SYS_BAW4_BASE_IDX                                                                   0
#define mmXPB_PEEW_SYS_BAW5                                                                            0x00a3
#define mmXPB_PEEW_SYS_BAW5_BASE_IDX                                                                   0
#define mmXPB_PEEW_SYS_BAW6                                                                            0x00a4
#define mmXPB_PEEW_SYS_BAW6_BASE_IDX                                                                   0
#define mmXPB_PEEW_SYS_BAW7                                                                            0x00a5
#define mmXPB_PEEW_SYS_BAW7_BASE_IDX                                                                   0
#define mmXPB_PEEW_SYS_BAW8                                                                            0x00a6
#define mmXPB_PEEW_SYS_BAW8_BASE_IDX                                                                   0
#define mmXPB_PEEW_SYS_BAW9                                                                            0x00a7
#define mmXPB_PEEW_SYS_BAW9_BASE_IDX                                                                   0
#define mmXPB_PEEW_SYS_BAW10                                                                           0x00a8
#define mmXPB_PEEW_SYS_BAW10_BASE_IDX                                                                  0
#define mmXPB_PEEW_SYS_BAW11                                                                           0x00a9
#define mmXPB_PEEW_SYS_BAW11_BASE_IDX                                                                  0
#define mmXPB_PEEW_SYS_BAW12                                                                           0x00aa
#define mmXPB_PEEW_SYS_BAW12_BASE_IDX                                                                  0
#define mmXPB_PEEW_SYS_BAW13                                                                           0x00ab
#define mmXPB_PEEW_SYS_BAW13_BASE_IDX                                                                  0
#define mmXPB_CWK_GAT                                                                                  0x00ac
#define mmXPB_CWK_GAT_BASE_IDX                                                                         0
#define mmXPB_INTF_CFG                                                                                 0x00ad
#define mmXPB_INTF_CFG_BASE_IDX                                                                        0
#define mmXPB_INTF_STS                                                                                 0x00ae
#define mmXPB_INTF_STS_BASE_IDX                                                                        0
#define mmXPB_PIPE_STS                                                                                 0x00af
#define mmXPB_PIPE_STS_BASE_IDX                                                                        0
#define mmXPB_SUB_CTWW                                                                                 0x00b0
#define mmXPB_SUB_CTWW_BASE_IDX                                                                        0
#define mmXPB_MAP_INVEWT_FWUSH_NUM_WSB                                                                 0x00b1
#define mmXPB_MAP_INVEWT_FWUSH_NUM_WSB_BASE_IDX                                                        0
#define mmXPB_PEWF_KNOBS                                                                               0x00b2
#define mmXPB_PEWF_KNOBS_BASE_IDX                                                                      0
#define mmXPB_STICKY                                                                                   0x00b3
#define mmXPB_STICKY_BASE_IDX                                                                          0
#define mmXPB_STICKY_W1C                                                                               0x00b4
#define mmXPB_STICKY_W1C_BASE_IDX                                                                      0
#define mmXPB_MISC_CFG                                                                                 0x00b5
#define mmXPB_MISC_CFG_BASE_IDX                                                                        0
#define mmXPB_INTF_CFG2                                                                                0x00b6
#define mmXPB_INTF_CFG2_BASE_IDX                                                                       0
#define mmXPB_CWG_EXTWA_WD                                                                             0x00b7
#define mmXPB_CWG_EXTWA_WD_BASE_IDX                                                                    0
#define mmXPB_CWG_EXTWA_MSK_WD                                                                         0x00b8
#define mmXPB_CWG_EXTWA_MSK_WD_BASE_IDX                                                                0
#define mmXPB_CWG_GFX_MATCH                                                                            0x00b9
#define mmXPB_CWG_GFX_MATCH_BASE_IDX                                                                   0
#define mmXPB_CWG_GFX_MATCH_MSK                                                                        0x00ba
#define mmXPB_CWG_GFX_MATCH_MSK_BASE_IDX                                                               0
#define mmXPB_CWG_MM_MATCH                                                                             0x00bb
#define mmXPB_CWG_MM_MATCH_BASE_IDX                                                                    0
#define mmXPB_CWG_MM_MATCH_MSK                                                                         0x00bc
#define mmXPB_CWG_MM_MATCH_MSK_BASE_IDX                                                                0
#define mmXPB_CWG_GUS_MATCH                                                                            0x00bd
#define mmXPB_CWG_GUS_MATCH_BASE_IDX                                                                   0
#define mmXPB_CWG_GUS_MATCH_MSK                                                                        0x00be
#define mmXPB_CWG_GUS_MATCH_MSK_BASE_IDX                                                               0
#define mmXPB_CWG_GFX_UNITID_MAPPING0                                                                  0x00bf
#define mmXPB_CWG_GFX_UNITID_MAPPING0_BASE_IDX                                                         0
#define mmXPB_CWG_GFX_UNITID_MAPPING1                                                                  0x00c0
#define mmXPB_CWG_GFX_UNITID_MAPPING1_BASE_IDX                                                         0
#define mmXPB_CWG_GFX_UNITID_MAPPING2                                                                  0x00c1
#define mmXPB_CWG_GFX_UNITID_MAPPING2_BASE_IDX                                                         0
#define mmXPB_CWG_GFX_UNITID_MAPPING3                                                                  0x00c2
#define mmXPB_CWG_GFX_UNITID_MAPPING3_BASE_IDX                                                         0
#define mmXPB_CWG_GFX_UNITID_MAPPING4                                                                  0x00c3
#define mmXPB_CWG_GFX_UNITID_MAPPING4_BASE_IDX                                                         0
#define mmXPB_CWG_GFX_UNITID_MAPPING5                                                                  0x00c4
#define mmXPB_CWG_GFX_UNITID_MAPPING5_BASE_IDX                                                         0
#define mmXPB_CWG_GFX_UNITID_MAPPING6                                                                  0x00c5
#define mmXPB_CWG_GFX_UNITID_MAPPING6_BASE_IDX                                                         0
#define mmXPB_CWG_GFX_UNITID_MAPPING7                                                                  0x00c6
#define mmXPB_CWG_GFX_UNITID_MAPPING7_BASE_IDX                                                         0
#define mmXPB_CWG_MM_UNITID_MAPPING0                                                                   0x00c7
#define mmXPB_CWG_MM_UNITID_MAPPING0_BASE_IDX                                                          0
#define mmXPB_CWG_MM_UNITID_MAPPING1                                                                   0x00c8
#define mmXPB_CWG_MM_UNITID_MAPPING1_BASE_IDX                                                          0
#define mmXPB_CWG_MM_UNITID_MAPPING2                                                                   0x00c9
#define mmXPB_CWG_MM_UNITID_MAPPING2_BASE_IDX                                                          0
#define mmXPB_CWG_MM_UNITID_MAPPING3                                                                   0x00ca
#define mmXPB_CWG_MM_UNITID_MAPPING3_BASE_IDX                                                          0
#define mmXPB_CWG_GUS_UNITID_MAPPING0                                                                  0x00cb
#define mmXPB_CWG_GUS_UNITID_MAPPING0_BASE_IDX                                                         0
#define mmXPB_CWG_GUS_UNITID_MAPPING1                                                                  0x00cc
#define mmXPB_CWG_GUS_UNITID_MAPPING1_BASE_IDX                                                         0
#define mmXPB_CWG_GUS_UNITID_MAPPING2                                                                  0x00cd
#define mmXPB_CWG_GUS_UNITID_MAPPING2_BASE_IDX                                                         0
#define mmXPB_CWG_GUS_UNITID_MAPPING3                                                                  0x00ce
#define mmXPB_CWG_GUS_UNITID_MAPPING3_BASE_IDX                                                         0
#define mmXPB_CWG_GUS_UNITID_MAPPING4                                                                  0x00cf
#define mmXPB_CWG_GUS_UNITID_MAPPING4_BASE_IDX                                                         0
#define mmXPB_CWG_GUS_UNITID_MAPPING5                                                                  0x00d0
#define mmXPB_CWG_GUS_UNITID_MAPPING5_BASE_IDX                                                         0
#define mmXPB_CWG_GUS_UNITID_MAPPING6                                                                  0x00d1
#define mmXPB_CWG_GUS_UNITID_MAPPING6_BASE_IDX                                                         0
#define mmXPB_CWG_GUS_UNITID_MAPPING7                                                                  0x00d2
#define mmXPB_CWG_GUS_UNITID_MAPPING7_BASE_IDX                                                         0


// addwessBwock: athub_wpbdec
// base addwess: 0x3350
#define mmWPB_PASSPW_CONF                                                                              0x00d4
#define mmWPB_PASSPW_CONF_BASE_IDX                                                                     0
#define mmWPB_BWOCKWEVEW_CONF                                                                          0x00d5
#define mmWPB_BWOCKWEVEW_CONF_BASE_IDX                                                                 0
#define mmWPB_TAG_CONF                                                                                 0x00d6
#define mmWPB_TAG_CONF_BASE_IDX                                                                        0
#define mmWPB_EFF_CNTW                                                                                 0x00d8
#define mmWPB_EFF_CNTW_BASE_IDX                                                                        0
#define mmWPB_AWB_CNTW                                                                                 0x00d9
#define mmWPB_AWB_CNTW_BASE_IDX                                                                        0
#define mmWPB_AWB_CNTW2                                                                                0x00da
#define mmWPB_AWB_CNTW2_BASE_IDX                                                                       0
#define mmWPB_BIF_CNTW                                                                                 0x00db
#define mmWPB_BIF_CNTW_BASE_IDX                                                                        0
#define mmWPB_BIF_CNTW2                                                                                0x00dc
#define mmWPB_BIF_CNTW2_BASE_IDX                                                                       0
#define mmWPB_WW_SWITCH_CNTW                                                                           0x00dd
#define mmWPB_WW_SWITCH_CNTW_BASE_IDX                                                                  0
#define mmWPB_WD_SWITCH_CNTW                                                                           0x00de
#define mmWPB_WD_SWITCH_CNTW_BASE_IDX                                                                  0
#define mmWPB_SWITCH_CNTW2                                                                             0x00df
#define mmWPB_SWITCH_CNTW2_BASE_IDX                                                                    0
#define mmWPB_CID_QUEUE_WW                                                                             0x00e0
#define mmWPB_CID_QUEUE_WW_BASE_IDX                                                                    0
#define mmWPB_EA_QUEUE_WW                                                                              0x00e1
#define mmWPB_EA_QUEUE_WW_BASE_IDX                                                                     0
#define mmWPB_CID_QUEUE_WD                                                                             0x00e2
#define mmWPB_CID_QUEUE_WD_BASE_IDX                                                                    0
#define mmWPB_CID_QUEUE_EX                                                                             0x00e3
#define mmWPB_CID_QUEUE_EX_BASE_IDX                                                                    0
#define mmWPB_CID_QUEUE_EX_DATA                                                                        0x00e4
#define mmWPB_CID_QUEUE_EX_DATA_BASE_IDX                                                               0
#define mmWPB_DEINTWWV_COMBINE_CNTW                                                                    0x00e5
#define mmWPB_DEINTWWV_COMBINE_CNTW_BASE_IDX                                                           0
#define mmWPB_VC_SWITCH_WDWW                                                                           0x00e6
#define mmWPB_VC_SWITCH_WDWW_BASE_IDX                                                                  0
#define mmWPB_PEWF_COUNTEW_CNTW                                                                        0x00e7
#define mmWPB_PEWF_COUNTEW_CNTW_BASE_IDX                                                               0
#define mmWPB_PEWF_COUNTEW_STATUS                                                                      0x00e8
#define mmWPB_PEWF_COUNTEW_STATUS_BASE_IDX                                                             0
#define mmWPB_PEWFCOUNTEW_WO                                                                           0x00e9
#define mmWPB_PEWFCOUNTEW_WO_BASE_IDX                                                                  0
#define mmWPB_PEWFCOUNTEW_HI                                                                           0x00ea
#define mmWPB_PEWFCOUNTEW_HI_BASE_IDX                                                                  0
#define mmWPB_PEWFCOUNTEW0_CFG                                                                         0x00eb
#define mmWPB_PEWFCOUNTEW0_CFG_BASE_IDX                                                                0
#define mmWPB_PEWFCOUNTEW1_CFG                                                                         0x00ec
#define mmWPB_PEWFCOUNTEW1_CFG_BASE_IDX                                                                0
#define mmWPB_PEWFCOUNTEW2_CFG                                                                         0x00ed
#define mmWPB_PEWFCOUNTEW2_CFG_BASE_IDX                                                                0
#define mmWPB_PEWFCOUNTEW3_CFG                                                                         0x00ee
#define mmWPB_PEWFCOUNTEW3_CFG_BASE_IDX                                                                0
#define mmWPB_PEWFCOUNTEW_WSWT_CNTW                                                                    0x00ef
#define mmWPB_PEWFCOUNTEW_WSWT_CNTW_BASE_IDX                                                           0
#define mmWPB_WD_QUEUE_CNTW                                                                            0x00f0
#define mmWPB_WD_QUEUE_CNTW_BASE_IDX                                                                   0
#define mmWPB_WD_QUEUE_CNTW2                                                                           0x00f1
#define mmWPB_WD_QUEUE_CNTW2_BASE_IDX                                                                  0
#define mmWPB_WW_QUEUE_CNTW                                                                            0x00f2
#define mmWPB_WW_QUEUE_CNTW_BASE_IDX                                                                   0
#define mmWPB_WW_QUEUE_CNTW2                                                                           0x00f3
#define mmWPB_WW_QUEUE_CNTW2_BASE_IDX                                                                  0
#define mmWPB_ATS_CNTW                                                                                 0x00f4
#define mmWPB_ATS_CNTW_BASE_IDX                                                                        0
#define mmWPB_ATS_CNTW2                                                                                0x00f5
#define mmWPB_ATS_CNTW2_BASE_IDX                                                                       0
#define mmWPB_ATS_CNTW3                                                                                0x00f6
#define mmWPB_ATS_CNTW3_BASE_IDX                                                                       0
#define mmWPB_DF_SDPPOWT_CNTW                                                                          0x00f7
#define mmWPB_DF_SDPPOWT_CNTW_BASE_IDX                                                                 0
#define mmWPB_SDPPOWT_CNTW                                                                             0x00f8
#define mmWPB_SDPPOWT_CNTW_BASE_IDX                                                                    0
#define mmWPB_NBIF_SDPPOWT_CNTW                                                                        0x00f9
#define mmWPB_NBIF_SDPPOWT_CNTW_BASE_IDX                                                               0

#endif
