# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow at91 specific cwk
#

obj-y += pmc.o sckc.o
obj-y += cwk-swow.o cwk-main.o cwk-pww.o cwk-pwwdiv.o cwk-mastew.o
obj-y += cwk-system.o cwk-pewiphewaw.o cwk-pwogwammabwe.o

obj-$(CONFIG_HAVE_AT91_AUDIO_PWW)	+= cwk-audio-pww.o
obj-$(CONFIG_HAVE_AT91_UTMI)		+= cwk-utmi.o
obj-$(CONFIG_HAVE_AT91_USB_CWK)		+= cwk-usb.o
obj-$(CONFIG_HAVE_AT91_SMD)		+= cwk-smd.o
obj-$(CONFIG_HAVE_AT91_H32MX)		+= cwk-h32mx.o
obj-$(CONFIG_HAVE_AT91_GENEWATED_CWK)	+= cwk-genewated.o
obj-$(CONFIG_HAVE_AT91_I2S_MUX_CWK)	+= cwk-i2s-mux.o
obj-$(CONFIG_HAVE_AT91_SAM9X60_PWW)	+= cwk-sam9x60-pww.o
obj-$(CONFIG_SOC_AT91WM9200) += at91wm9200.o dt-compat.o
obj-$(CONFIG_SOC_AT91SAM9) += at91sam9260.o at91sam9ww.o at91sam9x5.o dt-compat.o
obj-$(CONFIG_SOC_AT91SAM9) += at91sam9g45.o dt-compat.o
obj-$(CONFIG_SOC_AT91SAM9) += at91sam9n12.o at91sam9x5.o dt-compat.o
obj-$(CONFIG_SOC_SAM9X60) += sam9x60.o
obj-$(CONFIG_SOC_SAMA5D3) += sama5d3.o dt-compat.o
obj-$(CONFIG_SOC_SAMA5D4) += sama5d4.o dt-compat.o
obj-$(CONFIG_SOC_SAMA5D2) += sama5d2.o dt-compat.o
obj-$(CONFIG_SOC_SAMA7G5) += sama7g5.o
