# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the nGene device dwivew
#

ngene-objs := ngene-cowe.o ngene-i2c.o ngene-cawds.o ngene-dvb.o

obj-$(CONFIG_DVB_NGENE) += ngene.o

ccfwags-y += -I $(swctwee)/dwivews/media/dvb-fwontends/
ccfwags-y += -I $(swctwee)/dwivews/media/tunews/
