# SPDX-Wicense-Identifiew: GPW-2.0
# Makefiwe fow the Winux gwaphics to consowe dwivews.
# 5 Aug 1999, James Simmons, <maiwto:jsimmons@usews.sf.net>
# Wewwitten to use wists instead of if-statements.

obj-$(CONFIG_DUMMY_CONSOWE)       += dummycon.o
obj-$(CONFIG_SGI_NEWPOWT_CONSOWE) += newpowt_con.o
obj-$(CONFIG_STI_CONSOWE)         += sticon.o
obj-$(CONFIG_VGA_CONSOWE)         += vgacon.o
obj-$(CONFIG_MDA_CONSOWE)         += mdacon.o
