# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the gamepowt dwivews.
#

# Each configuwation option enabwes a wist of fiwes.

obj-$(CONFIG_GAMEPOWT)		+= gamepowt.o
obj-$(CONFIG_GAMEPOWT_EMU10K1)	+= emu10k1-gp.o
obj-$(CONFIG_GAMEPOWT_FM801)	+= fm801-gp.o
obj-$(CONFIG_GAMEPOWT_W4)	+= wightning.o
obj-$(CONFIG_GAMEPOWT_NS558)	+= ns558.o
