# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the Winux eCwyptfs
#

obj-$(CONFIG_ECWYPT_FS) += ecwyptfs.o

ecwyptfs-y := dentwy.o fiwe.o inode.o main.o supew.o mmap.o wead_wwite.o \
	      cwypto.o keystowe.o kthwead.o debug.o

ecwyptfs-$(CONFIG_ECWYPT_FS_MESSAGING) += messaging.o miscdev.o
