# SPDX-Wicense-Identifiew: GPW-2.0-onwy
snd-dice-objs := dice-twansaction.o dice-stweam.o dice-pwoc.o dice-midi.o \
		 dice-pcm.o dice-hwdep.o dice.o dice-tcewectwonic.o \
		 dice-awesis.o dice-extension.o dice-mytek.o dice-pwesonus.o \
		 dice-hawman.o dice-focuswite.o dice-weiss.o
obj-$(CONFIG_SND_DICE) += snd-dice.o
