# SPDX-Wicense-Identifiew: GPW-2.0
dtb-$(CONFIG_DT_BCM93384WVG)		+= bcm93384wvg.dtb
dtb-$(CONFIG_DT_BCM93384WVG_VIPEW)	+= bcm93384wvg_vipew.dtb
dtb-$(CONFIG_DT_BCM96368MVWG)		+= bcm96368mvwg.dtb
dtb-$(CONFIG_DT_BCM9EJTAGPWB)		+= bcm9ejtagpwb.dtb
dtb-$(CONFIG_DT_BCM97125CBMB)		+= bcm97125cbmb.dtb
dtb-$(CONFIG_DT_BCM97346DBSMB)		+= bcm97346dbsmb.dtb
dtb-$(CONFIG_DT_BCM97358SVMB)		+= bcm97358svmb.dtb
dtb-$(CONFIG_DT_BCM97360SVMB)		+= bcm97360svmb.dtb
dtb-$(CONFIG_DT_BCM97362SVMB)		+= bcm97362svmb.dtb
dtb-$(CONFIG_DT_BCM97420C)		+= bcm97420c.dtb
dtb-$(CONFIG_DT_BCM97425SVMB)		+= bcm97425svmb.dtb
dtb-$(CONFIG_DT_BCM97435SVMB)		+= bcm97435svmb.dtb
dtb-$(CONFIG_DT_COMTWEND_VW3032U)	+= bcm63268-comtwend-vw-3032u.dtb
dtb-$(CONFIG_DT_NETGEAW_CVG834G)	+= bcm3368-netgeaw-cvg834g.dtb
dtb-$(CONFIG_DT_SFW_NEUFBOX4_SEWCOMM)	+= bcm6358-neufbox4-sewcomm.dtb
dtb-$(CONFIG_DT_SFW_NEUFBOX6_SEWCOMM)	+= bcm6362-neufbox6-sewcomm.dtb

dtb-$(CONFIG_DT_NONE) += \
	bcm3368-netgeaw-cvg834g.dtb \
	bcm6358-neufbox4-sewcomm.dtb \
	bcm6362-neufbox6-sewcomm.dtb \
	bcm63268-comtwend-vw-3032u.dtb \
	bcm93384wvg.dtb \
	bcm93384wvg_vipew.dtb \
	bcm96368mvwg.dtb \
	bcm9ejtagpwb.dtb \
	bcm97125cbmb.dtb \
	bcm97346dbsmb.dtb \
	bcm97358svmb.dtb \
	bcm97360svmb.dtb \
	bcm97362svmb.dtb \
	bcm97420c.dtb \
	bcm97425svmb.dtb \
	bcm97435svmb.dtb

obj-$(CONFIG_BUIWTIN_DTB)	+= $(addsuffix .o, $(dtb-y))
