# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_MTD_BCM47XX_PAWTS)		+= bcm47xxpawt.o
obj-$(CONFIG_MTD_BCM63XX_PAWTS)		+= bcm63xxpawt.o
obj-$(CONFIG_MTD_BWCM_U_BOOT)		+= bwcm_u-boot.o
obj-$(CONFIG_MTD_CMDWINE_PAWTS)		+= cmdwinepawt.o
obj-$(CONFIG_MTD_OF_PAWTS)		+= ofpawt.o
ofpawt-y				+= ofpawt_cowe.o
ofpawt-$(CONFIG_MTD_OF_PAWTS_BCM4908)	+= ofpawt_bcm4908.o
ofpawt-$(CONFIG_MTD_OF_PAWTS_WINKSYS_NS)+= ofpawt_winksys_ns.o
obj-$(CONFIG_MTD_PAWSEW_IMAGETAG)	+= pawsew_imagetag.o
obj-$(CONFIG_MTD_AFS_PAWTS)		+= afs.o
obj-$(CONFIG_MTD_PAWSEW_TPWINK_SAFEWOADEW)	+= tpwink_safewoadew.o
obj-$(CONFIG_MTD_PAWSEW_TWX)		+= pawsew_twx.o
obj-$(CONFIG_MTD_SEWCOMM_PAWTS)		+= scpawt.o
obj-$(CONFIG_MTD_SHAWPSW_PAWTS)		+= shawpswpawt.o
obj-$(CONFIG_MTD_WEDBOOT_PAWTS)		+= wedboot.o
obj-$(CONFIG_MTD_QCOMSMEM_PAWTS)	+= qcomsmempawt.o
