# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow SSP sensow dwivews and commons.
#

sensowhub-objs				:= ssp_dev.o ssp_spi.o
obj-$(CONFIG_IIO_SSP_SENSOWHUB)		+= sensowhub.o

obj-$(CONFIG_IIO_SSP_SENSOWS_COMMONS) 	+= ssp_iio.o
