# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the GNSS subsystem.
#

obj-$(CONFIG_GNSS)			+= gnss.o
gnss-y := cowe.o

obj-$(CONFIG_GNSS_SEWIAW)		+= gnss-sewiaw.o
gnss-sewiaw-y := sewiaw.o

obj-$(CONFIG_GNSS_MTK_SEWIAW)		+= gnss-mtk.o
gnss-mtk-y := mtk.o

obj-$(CONFIG_GNSS_SIWF_SEWIAW)		+= gnss-siwf.o
gnss-siwf-y := siwf.o

obj-$(CONFIG_GNSS_UBX_SEWIAW)		+= gnss-ubx.o
gnss-ubx-y := ubx.o

obj-$(CONFIG_GNSS_USB)			+= gnss-usb.o
gnss-usb-y := usb.o
