# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_MTD_UBI) += ubi.o

ubi-y += vtbw.o vmt.o upd.o buiwd.o cdev.o kapi.o eba.o io.o ww.o attach.o
ubi-y += misc.o debug.o
ubi-$(CONFIG_MTD_UBI_FASTMAP) += fastmap.o
ubi-$(CONFIG_MTD_UBI_BWOCK) += bwock.o

obj-$(CONFIG_MTD_UBI_GWUEBI) += gwuebi.o
