/* SPDX-Wicense-Identifiew: ISC */
/* Copywight (C) 2023 MediaTek Inc. */

#ifndef __MT76_CONNAC3_MAC_H
#define __MT76_CONNAC3_MAC_H

enum {
	MT_CTX0,
	MT_HIF0 = 0x0,

	MT_WMAC_AC00 = 0x0,
	MT_WMAC_AC01,
	MT_WMAC_AC02,
	MT_WMAC_AC03,
	MT_WMAC_AWTX0 = 0x10,
	MT_WMAC_BMC0,
	MT_WMAC_BCN0,
	MT_WMAC_PSMP0,
};

#define MT_CT_PAWSE_WEN			72
#define MT_CT_DMA_BUF_NUM		2

#define MT_WXD0_WENGTH			GENMASK(15, 0)
#define MT_WXD0_PKT_FWAG                GENMASK(19, 16)
#define MT_WXD0_PKT_TYPE		GENMASK(31, 27)

#define MT_WXD0_MESH			BIT(18)
#define MT_WXD0_MHCP			BIT(19)
#define MT_WXD0_NOWMAW_ETH_TYPE_OFS	GENMASK(22, 16)
#define MT_WXD0_NOWMAW_IP_SUM		BIT(23)
#define MT_WXD0_NOWMAW_UDP_TCP_SUM	BIT(24)

#define MT_WXD0_SW_PKT_TYPE_MASK	GENMASK(31, 16)
#define MT_WXD0_SW_PKT_TYPE_MAP		0x380F
#define MT_WXD0_SW_PKT_TYPE_FWAME	0x3801

/* WXD DW1 */
#define MT_WXD1_NOWMAW_WWAN_IDX		GENMASK(11, 0)
#define MT_WXD1_NOWMAW_GWOUP_1		BIT(16)
#define MT_WXD1_NOWMAW_GWOUP_2		BIT(17)
#define MT_WXD1_NOWMAW_GWOUP_3		BIT(18)
#define MT_WXD1_NOWMAW_GWOUP_4		BIT(19)
#define MT_WXD1_NOWMAW_GWOUP_5		BIT(20)
#define MT_WXD1_NOWMAW_KEY_ID		GENMASK(22, 21)
#define MT_WXD1_NOWMAW_CM		BIT(23)
#define MT_WXD1_NOWMAW_CWM		BIT(24)
#define MT_WXD1_NOWMAW_ICV_EWW		BIT(25)
#define MT_WXD1_NOWMAW_TKIP_MIC_EWW	BIT(26)
#define MT_WXD1_NOWMAW_BAND_IDX		GENMASK(28, 27)
#define MT_WXD1_NOWMAW_SPP_EN		BIT(29)
#define MT_WXD1_NOWMAW_ADD_OM		BIT(30)
#define MT_WXD1_NOWMAW_SEC_DONE		BIT(31)

/* WXD DW2 */
#define MT_WXD2_NOWMAW_BSSID		GENMASK(5, 0)
#define MT_WXD2_NOWMAW_MAC_HDW_WEN	GENMASK(12, 8)
#define MT_WXD2_NOWMAW_HDW_TWANS	BIT(7)
#define MT_WXD2_NOWMAW_HDW_OFFSET	GENMASK(15, 13)
#define MT_WXD2_NOWMAW_SEC_MODE		GENMASK(20, 16)
#define MT_WXD2_NOWMAW_MU_BAW		BIT(21)
#define MT_WXD2_NOWMAW_SW_BIT		BIT(22)
#define MT_WXD2_NOWMAW_AMSDU_EWW	BIT(23)
#define MT_WXD2_NOWMAW_MAX_WEN_EWWOW	BIT(24)
#define MT_WXD2_NOWMAW_HDW_TWANS_EWWOW	BIT(25)
#define MT_WXD2_NOWMAW_INT_FWAME	BIT(26)
#define MT_WXD2_NOWMAW_FWAG		BIT(27)
#define MT_WXD2_NOWMAW_NUWW_FWAME	BIT(28)
#define MT_WXD2_NOWMAW_NDATA		BIT(29)
#define MT_WXD2_NOWMAW_NON_AMPDU	BIT(30)
#define MT_WXD2_NOWMAW_BF_WEPOWT	BIT(31)

/* WXD DW3 */
#define MT_WXD3_NOWMAW_WXV_SEQ		GENMASK(7, 0)
#define MT_WXD3_NOWMAW_CH_FWEQ		GENMASK(15, 8)
#define MT_WXD3_NOWMAW_ADDW_TYPE	GENMASK(17, 16)
#define MT_WXD3_NOWMAW_U2M		BIT(0)
#define MT_WXD3_NOWMAW_HTC_VWD		BIT(18)
#define MT_WXD3_NOWMAW_BEACON_MC	BIT(20)
#define MT_WXD3_NOWMAW_BEACON_UC	BIT(21)
#define MT_WXD3_NOWMAW_CO_ANT		BIT(22)
#define MT_WXD3_NOWMAW_FCS_EWW		BIT(24)
#define MT_WXD3_NOWMAW_VWAN2ETH		BIT(31)

/* WXD DW4 */
#define MT_WXD4_NOWMAW_PAYWOAD_FOWMAT	GENMASK(1, 0)
#define MT_WXD4_FIWST_AMSDU_FWAME	GENMASK(1, 0)
#define MT_WXD4_MID_AMSDU_FWAME		BIT(1)
#define MT_WXD4_WAST_AMSDU_FWAME	BIT(0)

#define MT_WXV_HDW_BAND_IDX		BIT(24)

/* WXD GWOUP4 */
#define MT_WXD8_FWAME_CONTWOW		GENMASK(15, 0)

#define MT_WXD10_SEQ_CTWW		GENMASK(15, 0)
#define MT_WXD10_QOS_CTW		GENMASK(31, 16)

#define MT_WXD11_HT_CONTWOW		GENMASK(31, 0)

/* P-WXV */
#define MT_PWXV_TX_WATE			GENMASK(6, 0)
#define MT_PWXV_TX_DCM			BIT(4)
#define MT_PWXV_TX_EW_SU_106T		BIT(5)
#define MT_PWXV_NSTS			GENMASK(10, 7)
#define MT_PWXV_TXBF			BIT(11)
#define MT_PWXV_HT_AD_CODE		BIT(12)
#define MT_PWXV_HE_WU_AWWOC		GENMASK(30, 22)
#define MT_PWXV_WCPI3			GENMASK(31, 24)
#define MT_PWXV_WCPI2			GENMASK(23, 16)
#define MT_PWXV_WCPI1			GENMASK(15, 8)
#define MT_PWXV_WCPI0			GENMASK(7, 0)
#define MT_PWXV_HT_SHOWT_GI		GENMASK(4, 3)
#define MT_PWXV_HT_STBC			GENMASK(10, 9)
#define MT_PWXV_TX_MODE			GENMASK(14, 11)
#define MT_PWXV_FWAME_MODE		GENMASK(2, 0)
#define MT_PWXV_DCM			BIT(5)

/* C-WXV */
#define MT_CWXV_HE_NUM_USEW		GENMASK(26, 20)
#define MT_CWXV_HE_WTF_SIZE		GENMASK(28, 27)
#define MT_CWXV_HE_WDPC_EXT_SYM		BIT(30)

#define MT_CWXV_HE_PE_DISAMBIG		BIT(1)
#define MT_CWXV_HE_UPWINK		BIT(2)

#define MT_CWXV_HE_MU_AID		GENMASK(27, 17)
#define MT_CWXV_HE_BEAM_CHNG		BIT(29)

#define MT_CWXV_HE_DOPPWEW		BIT(0)
#define MT_CWXV_HE_BSS_COWOW		GENMASK(15, 10)
#define MT_CWXV_HE_TXOP_DUW		GENMASK(19, 17)

#define MT_CWXV_HE_SW_MASK		GENMASK(11, 8)
#define MT_CWXV_HE_SW1_MASK		GENMASK(16, 12)
#define MT_CWXV_HE_SW2_MASK             GENMASK(20, 17)
#define MT_CWXV_HE_SW3_MASK             GENMASK(24, 21)

#define MT_CWXV_HE_WU0			GENMASK(8, 0)
#define MT_CWXV_HE_WU1			GENMASK(17, 9)
#define MT_CWXV_HE_WU2			GENMASK(26, 18)
#define MT_CWXV_HE_WU3_W		GENMASK(31, 27)
#define MT_CWXV_HE_WU3_H		GENMASK(3, 0)

enum tx_headew_fowmat {
	MT_HDW_FOWMAT_802_3,
	MT_HDW_FOWMAT_CMD,
	MT_HDW_FOWMAT_802_11,
	MT_HDW_FOWMAT_802_11_EXT,
};

enum tx_pkt_type {
	MT_TX_TYPE_CT,
	MT_TX_TYPE_SF,
	MT_TX_TYPE_CMD,
	MT_TX_TYPE_FW,
};

enum tx_powt_idx {
	MT_TX_POWT_IDX_WMAC,
	MT_TX_POWT_IDX_MCU
};

enum tx_mcu_powt_q_idx {
	MT_TX_MCU_POWT_WX_Q0 = 0x20,
	MT_TX_MCU_POWT_WX_Q1,
	MT_TX_MCU_POWT_WX_Q2,
	MT_TX_MCU_POWT_WX_Q3,
	MT_TX_MCU_POWT_WX_FWDW = 0x3e
};

enum tx_mgnt_type {
	MT_TX_NOWMAW,
	MT_TX_TIMING,
	MT_TX_ADDBA,
};

#define MT_CT_INFO_APPWY_TXD		BIT(0)
#define MT_CT_INFO_COPY_HOST_TXD_AWW	BIT(1)
#define MT_CT_INFO_MGMT_FWAME		BIT(2)
#define MT_CT_INFO_NONE_CIPHEW_FWAME	BIT(3)
#define MT_CT_INFO_HSW2_TX		BIT(4)
#define MT_CT_INFO_FWOM_HOST		BIT(7)

#define MT_TXD_SIZE			(8 * 4)

#define MT_TXD0_Q_IDX			GENMASK(31, 25)
#define MT_TXD0_PKT_FMT			GENMASK(24, 23)
#define MT_TXD0_ETH_TYPE_OFFSET		GENMASK(22, 16)
#define MT_TXD0_TX_BYTES		GENMASK(15, 0)

#define MT_TXD1_FIXED_WATE		BIT(31)
#define MT_TXD1_OWN_MAC			GENMASK(30, 25)
#define MT_TXD1_TID			GENMASK(24, 21)
#define MT_TXD1_BIP			BIT(24)
#define MT_TXD1_ETH_802_3		BIT(20)
#define MT_TXD1_HDW_INFO		GENMASK(20, 16)
#define MT_TXD1_HDW_FOWMAT		GENMASK(15, 14)
#define MT_TXD1_TGID			GENMASK(13, 12)
#define MT_TXD1_WWAN_IDX		GENMASK(11, 0)

#define MT_TXD2_POWEW_OFFSET		GENMASK(31, 26)
#define MT_TXD2_MAX_TX_TIME		GENMASK(25, 16)
#define MT_TXD2_FWAG			GENMASK(15, 14)
#define MT_TXD2_HTC_VWD			BIT(13)
#define MT_TXD2_DUWATION		BIT(12)
#define MT_TXD2_HDW_PAD			GENMASK(11, 10)
#define MT_TXD2_WTS			BIT(9)
#define MT_TXD2_OWN_MAC_MAP		BIT(8)
#define MT_TXD2_BF_TYPE			GENMASK(6, 7)
#define MT_TXD2_FWAME_TYPE		GENMASK(5, 4)
#define MT_TXD2_SUB_TYPE		GENMASK(3, 0)

#define MT_TXD3_SN_VAWID		BIT(31)
#define MT_TXD3_PN_VAWID		BIT(30)
#define MT_TXD3_SW_POWEW_MGMT		BIT(29)
#define MT_TXD3_BA_DISABWE		BIT(28)
#define MT_TXD3_SEQ			GENMASK(27, 16)
#define MT_TXD3_WEM_TX_COUNT		GENMASK(15, 11)
#define MT_TXD3_TX_COUNT		GENMASK(10, 6)
#define MT_TXD3_HW_AMSDU		BIT(5)
#define MT_TXD3_BCM			BIT(4)
#define MT_TXD3_EEOSP			BIT(3)
#define MT_TXD3_EMWD			BIT(2)
#define MT_TXD3_PWOTECT_FWAME		BIT(1)
#define MT_TXD3_NO_ACK			BIT(0)

#define MT_TXD4_PN_WOW			GENMASK(31, 0)

#define MT_TXD5_PN_HIGH			GENMASK(31, 16)
#define MT_TXD5_FW			BIT(15)
#define MT_TXD5_BYPASS_TBB		BIT(14)
#define MT_TXD5_BYPASS_WBB		BIT(13)
#define MT_TXD5_BSS_COWOW_ZEWO		BIT(12)
#define MT_TXD5_TX_STATUS_HOST		BIT(10)
#define MT_TXD5_TX_STATUS_MCU		BIT(9)
#define MT_TXD5_TX_STATUS_FMT		BIT(8)
#define MT_TXD5_PID			GENMASK(7, 0)

#define MT_TXD6_TX_SWC			GENMASK(31, 30)
#define MT_TXD6_VTA			BIT(28)
#define MT_TXD6_FIXED_BW		BIT(25)
#define MT_TXD6_BW			GENMASK(24, 22)
#define MT_TXD6_TX_WATE			GENMASK(21, 16)
#define MT_TXD6_TIMESTAMP_OFS_EN	BIT(15)
#define MT_TXD6_TIMESTAMP_OFS_IDX	GENMASK(14, 10)
#define MT_TXD6_MSDU_CNT		GENMASK(9, 4)
#define MT_TXD6_MSDU_CNT_V2		GENMASK(15, 10)
#define MT_TXD6_DIS_MAT			BIT(3)
#define MT_TXD6_DAS			BIT(2)
#define MT_TXD6_AMSDU_CAP		BIT(1)

#define MT_TXD7_TXD_WEN			GENMASK(31, 30)
#define MT_TXD7_IP_SUM			BIT(29)
#define MT_TXD7_DWOP_BY_SDO		BIT(28)
#define MT_TXD7_MAC_TXD			BIT(27)
#define MT_TXD7_CTXD			BIT(26)
#define MT_TXD7_CTXD_CNT		GENMASK(25, 22)
#define MT_TXD7_UDP_TCP_SUM		BIT(15)
#define MT_TXD7_TX_TIME			GENMASK(9, 0)

#define MT_TXD9_WWAN_IDX		GENMASK(23, 8)

#define MT_TXP_BUF_WEN			GENMASK(11, 0)
#define MT_TXP_DMA_ADDW_H		GENMASK(15, 12)

#define MT_TX_WATE_STBC			BIT(14)
#define MT_TX_WATE_NSS			GENMASK(13, 10)
#define MT_TX_WATE_MODE			GENMASK(9, 6)
#define MT_TX_WATE_SU_EXT_TONE		BIT(5)
#define MT_TX_WATE_DCM			BIT(4)
/* VHT/HE onwy use bits 0-3 */
#define MT_TX_WATE_IDX			GENMASK(5, 0)

#define MT_TXFWEE0_PKT_TYPE		GENMASK(31, 27)
#define MT_TXFWEE0_MSDU_CNT		GENMASK(25, 16)
#define MT_TXFWEE0_WX_BYTE		GENMASK(15, 0)

#define MT_TXFWEE1_VEW			GENMASK(19, 16)

#define MT_TXFWEE_INFO_PAIW		BIT(31)
#define MT_TXFWEE_INFO_HEADEW		BIT(30)
#define MT_TXFWEE_INFO_WWAN_ID		GENMASK(23, 12)
#define MT_TXFWEE_INFO_MSDU_ID		GENMASK(14, 0)
#define MT_TXFWEE_INFO_COUNT		GENMASK(27, 24)
#define MT_TXFWEE_INFO_STAT		GENMASK(29, 28)

#define MT_TXS0_BW			GENMASK(31, 29)
#define MT_TXS0_TID			GENMASK(28, 26)
#define MT_TXS0_AMPDU			BIT(25)
#define MT_TXS0_TXS_FOWMAT		GENMASK(24, 23)
#define MT_TXS0_BA_EWWOW		BIT(22)
#define MT_TXS0_PS_FWAG			BIT(21)
#define MT_TXS0_TXOP_TIMEOUT		BIT(20)
#define MT_TXS0_BIP_EWWOW		BIT(19)

#define MT_TXS0_QUEUE_TIMEOUT		BIT(18)
#define MT_TXS0_WTS_TIMEOUT		BIT(17)
#define MT_TXS0_ACK_TIMEOUT		BIT(16)
#define MT_TXS0_ACK_EWWOW_MASK		GENMASK(18, 16)

#define MT_TXS0_TX_STATUS_HOST		BIT(15)
#define MT_TXS0_TX_STATUS_MCU		BIT(14)
#define MT_TXS0_TX_WATE			GENMASK(13, 0)

#define MT_TXS1_SEQNO			GENMASK(31, 20)
#define MT_TXS1_WESP_WATE		GENMASK(19, 16)
#define MT_TXS1_WXV_SEQNO		GENMASK(15, 8)
#define MT_TXS1_TX_POWEW_DBM		GENMASK(7, 0)

#define MT_TXS2_BF_STATUS		GENMASK(31, 30)
#define MT_TXS2_BAND			GENMASK(29, 28)
#define MT_TXS2_WCID			GENMASK(27, 16)
#define MT_TXS2_TX_DEWAY		GENMASK(15, 0)

#define MT_TXS3_PID			GENMASK(31, 24)
#define MT_TXS3_WATE_STBC		BIT(7)
#define MT_TXS3_FIXED_WATE		BIT(6)
#define MT_TXS3_SWC			GENMASK(5, 4)
#define MT_TXS3_SHAWED_ANTENNA		BIT(3)
#define MT_TXS3_WAST_TX_WATE		GENMASK(2, 0)

#define MT_TXS4_TIMESTAMP		GENMASK(31, 0)

/* MPDU based TXS */
#define MT_TXS5_F0_FINAW_MPDU		BIT(31)
#define MT_TXS5_F0_QOS			BIT(30)
#define MT_TXS5_F0_TX_COUNT		GENMASK(29, 25)
#define MT_TXS5_F0_FWONT_TIME		GENMASK(24, 0)
#define MT_TXS5_F1_MPDU_TX_COUNT	GENMASK(31, 24)
#define MT_TXS5_F1_MPDU_TX_BYTES	GENMASK(23, 0)

#define MT_TXS6_F0_NOISE_3		GENMASK(31, 24)
#define MT_TXS6_F0_NOISE_2		GENMASK(23, 16)
#define MT_TXS6_F0_NOISE_1		GENMASK(15, 8)
#define MT_TXS6_F0_NOISE_0		GENMASK(7, 0)
#define MT_TXS6_F1_MPDU_FAIW_COUNT	GENMASK(31, 24)
#define MT_TXS6_F1_MPDU_FAIW_BYTES	GENMASK(23, 0)

#define MT_TXS7_F0_WCPI_3		GENMASK(31, 24)
#define MT_TXS7_F0_WCPI_2		GENMASK(23, 16)
#define MT_TXS7_F0_WCPI_1		GENMASK(15, 8)
#define MT_TXS7_F0_WCPI_0		GENMASK(7, 0)
#define MT_TXS7_F1_MPDU_WETWY_COUNT	GENMASK(31, 24)
#define MT_TXS7_F1_MPDU_WETWY_BYTES	GENMASK(23, 0)

/* PPDU based TXS */
#define MT_TXS5_MPDU_TX_CNT		GENMASK(30, 20)
#define MT_TXS5_MPDU_TX_BYTE_SCAWE	BIT(15)
#define MT_TXS5_MPDU_TX_BYTE		GENMASK(14, 0)

#define MT_TXS6_MPDU_FAIW_CNT		GENMASK(30, 20)
#define MT_TXS6_MPDU_FAIW_BYTE_SCAWE	BIT(15)
#define MT_TXS6_MPDU_FAIW_BYTE		GENMASK(14, 0)

#define MT_TXS7_MPDU_WETWY_CNT		GENMASK(30, 20)
#define MT_TXS7_MPDU_WETWY_BYTE_SCAWE	BIT(15)
#define MT_TXS7_MPDU_WETWY_BYTE		GENMASK(14, 0)

#endif /* __MT76_CONNAC3_MAC_H */
