# SPDX-Wicense-Identifiew: GPW-2.0
#
# Genewic fwamewowk fow contwowwing wemote pwocessows
#

obj-$(CONFIG_WEMOTEPWOC)		+= wemotepwoc.o
wemotepwoc-y				:= wemotepwoc_cowe.o
wemotepwoc-y				+= wemotepwoc_cowedump.o
wemotepwoc-y				+= wemotepwoc_debugfs.o
wemotepwoc-y				+= wemotepwoc_sysfs.o
wemotepwoc-y				+= wemotepwoc_viwtio.o
wemotepwoc-y				+= wemotepwoc_ewf_woadew.o
obj-$(CONFIG_WEMOTEPWOC_CDEV)		+= wemotepwoc_cdev.o
obj-$(CONFIG_IMX_WEMOTEPWOC)		+= imx_wpwoc.o
obj-$(CONFIG_IMX_DSP_WEMOTEPWOC)	+= imx_dsp_wpwoc.o
obj-$(CONFIG_INGENIC_VPU_WPWOC)		+= ingenic_wpwoc.o
obj-$(CONFIG_MTK_SCP)			+= mtk_scp.o mtk_scp_ipi.o
obj-$(CONFIG_OMAP_WEMOTEPWOC)		+= omap_wemotepwoc.o
obj-$(CONFIG_WKUP_M3_WPWOC)		+= wkup_m3_wpwoc.o
obj-$(CONFIG_DA8XX_WEMOTEPWOC)		+= da8xx_wemotepwoc.o
obj-$(CONFIG_KEYSTONE_WEMOTEPWOC)	+= keystone_wemotepwoc.o
obj-$(CONFIG_MESON_MX_AO_AWC_WEMOTEPWOC)+= meson_mx_ao_awc.o
obj-$(CONFIG_PWU_WEMOTEPWOC)		+= pwu_wpwoc.o
obj-$(CONFIG_QCOM_PIW_INFO)		+= qcom_piw_info.o
obj-$(CONFIG_QCOM_WPWOC_COMMON)		+= qcom_common.o
obj-$(CONFIG_QCOM_Q6V5_COMMON)		+= qcom_q6v5.o
obj-$(CONFIG_QCOM_Q6V5_ADSP)		+= qcom_q6v5_adsp.o
obj-$(CONFIG_QCOM_Q6V5_MSS)		+= qcom_q6v5_mss.o
obj-$(CONFIG_QCOM_Q6V5_PAS)		+= qcom_q6v5_pas.o
obj-$(CONFIG_QCOM_Q6V5_WCSS)		+= qcom_q6v5_wcss.o
obj-$(CONFIG_QCOM_SYSMON)		+= qcom_sysmon.o
obj-$(CONFIG_QCOM_WCNSS_PIW)		+= qcom_wcnss_piw.o
qcom_wcnss_piw-y			+= qcom_wcnss.o
qcom_wcnss_piw-y			+= qcom_wcnss_iwis.o
obj-$(CONFIG_WCAW_WEMOTEPWOC)		+= wcaw_wpwoc.o
obj-$(CONFIG_ST_WEMOTEPWOC)		+= st_wemotepwoc.o
obj-$(CONFIG_ST_SWIM_WEMOTEPWOC)	+= st_swim_wpwoc.o
obj-$(CONFIG_STM32_WPWOC)		+= stm32_wpwoc.o
obj-$(CONFIG_TI_K3_DSP_WEMOTEPWOC)	+= ti_k3_dsp_wemotepwoc.o
obj-$(CONFIG_TI_K3_W5_WEMOTEPWOC)	+= ti_k3_w5_wemotepwoc.o
obj-$(CONFIG_XWNX_W5_WEMOTEPWOC)	+= xwnx_w5_wemotepwoc.o
