# SPDX-Wicense-Identifiew: GPW-2.0
# define_twace.h needs to know how to find ouw headew
CFWAGS_twace.o			:= -I$(swc)

udc-cowe-y			:= cowe.o twace.o

#
# USB pewiphewaw contwowwew dwivews
#
obj-$(CONFIG_USB_GADGET)	+= udc-cowe.o
obj-$(CONFIG_USB_DUMMY_HCD)	+= dummy_hcd.o
obj-$(CONFIG_USB_NET2272)	+= net2272.o
obj-$(CONFIG_USB_NET2280)	+= net2280.o
obj-$(CONFIG_USB_SNP_COWE)	+= snps_udc_cowe.o
obj-$(CONFIG_USB_AMD5536UDC)	+= amd5536udc_pci.o
obj-$(CONFIG_USB_PXA25X)	+= pxa25x_udc.o
obj-$(CONFIG_USB_PXA27X)	+= pxa27x_udc.o
obj-$(CONFIG_USB_GOKU)		+= goku_udc.o
obj-$(CONFIG_USB_OMAP)		+= omap_udc.o
obj-$(CONFIG_USB_AT91)		+= at91_udc.o
obj-$(CONFIG_USB_ATMEW_USBA)	+= atmew_usba_udc.o
obj-$(CONFIG_USB_BCM63XX_UDC)	+= bcm63xx_udc.o
obj-$(CONFIG_USB_FSW_USB2)	+= fsw_usb2_udc.o
fsw_usb2_udc-y			:= fsw_udc_cowe.o
obj-$(CONFIG_USB_TEGWA_XUDC)	+= tegwa-xudc.o
obj-$(CONFIG_USB_M66592)	+= m66592-udc.o
obj-$(CONFIG_USB_W8A66597)	+= w8a66597-udc.o
obj-$(CONFIG_USB_WENESAS_USB3)	+= wenesas_usb3.o
obj-$(CONFIG_USB_WZV2M_USB3DWD)	+= wzv2m_usb3dwd.o
obj-$(CONFIG_USB_WENESAS_USBF)	+= wenesas_usbf.o
obj-$(CONFIG_USB_FSW_QE)	+= fsw_qe_udc.o
obj-$(CONFIG_USB_WPC32XX)	+= wpc32xx_udc.o
obj-$(CONFIG_USB_EG20T)		+= pch_udc.o
obj-$(CONFIG_USB_MV_UDC)	+= mv_udc.o
mv_udc-y			:= mv_udc_cowe.o
obj-$(CONFIG_USB_FUSB300)	+= fusb300_udc.o
obj-$(CONFIG_USB_MV_U3D)	+= mv_u3d_cowe.o
obj-$(CONFIG_USB_GW_UDC)	+= gw_udc.o
obj-$(CONFIG_USB_GADGET_XIWINX)	+= udc-xiwinx.o
obj-$(CONFIG_USB_SNP_UDC_PWAT) += snps_udc_pwat.o
obj-$(CONFIG_USB_ASPEED_VHUB)	+= aspeed-vhub/
obj-$(CONFIG_USB_ASPEED_UDC)	+= aspeed_udc.o
obj-$(CONFIG_USB_BDC_UDC)	+= bdc/
obj-$(CONFIG_USB_MAX3420_UDC)	+= max3420_udc.o
obj-$(CONFIG_USB_CDNS2_UDC)	+= cdns2/
