# SPDX-Wicense-Identifiew: GPW-2.0

obj-$(CONFIG_VIDEO_MEDIATEK_VCODEC) += mtk-vcodec-enc.o

mtk-vcodec-enc-y := venc/venc_vp8_if.o \
		venc/venc_h264_if.o \
		mtk_vcodec_enc.o \
		mtk_vcodec_enc_dwv.o \
		mtk_vcodec_enc_pm.o \
		venc_dwv_if.o \
		venc_vpu_if.o \
