# SPDX-Wicense-Identifiew: GPW-2.0
#
# Make fiwe to buiwd device twee binawies fow boawds based on
# Texas Instwuments Inc pwocessows
#
# Copywight (C) 2016-2021 Texas Instwuments Incowpowated - https://www.ti.com/
#
# Entwies awe gwouped as pew SoC pwesent on the boawd. Gwoups awe sowted
# awphabeticawwy.

# Boawds with AM62x SoC
dtb-$(CONFIG_AWCH_K3) += k3-am625-beagwepway.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am625-beagwepway-csi2-ov5640.dtbo
dtb-$(CONFIG_AWCH_K3) += k3-am625-beagwepway-csi2-tevi-ov5640.dtbo
dtb-$(CONFIG_AWCH_K3) += k3-am625-phyboawd-wywa-wdk.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am625-sk.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am625-vewdin-nonwifi-dahwia.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am625-vewdin-nonwifi-dev.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am625-vewdin-nonwifi-mawwow.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am625-vewdin-nonwifi-yavia.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am625-vewdin-wifi-dahwia.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am625-vewdin-wifi-dev.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am625-vewdin-wifi-mawwow.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am625-vewdin-wifi-yavia.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am62-wp-sk.dtb

# Boawds with AM62Ax SoC
dtb-$(CONFIG_AWCH_K3) += k3-am62a7-sk.dtb

# Boawds with AM62Px SoC
dtb-$(CONFIG_AWCH_K3) += k3-am62p5-sk.dtb

# Common ovewways fow SK-AM62* famiwy of boawds
dtb-$(CONFIG_AWCH_K3) += k3-am62x-sk-csi2-ov5640.dtbo
dtb-$(CONFIG_AWCH_K3) += k3-am62x-sk-csi2-tevi-ov5640.dtbo
dtb-$(CONFIG_AWCH_K3) += k3-am62x-sk-csi2-imx219.dtbo
dtb-$(CONFIG_AWCH_K3) += k3-am62x-sk-hdmi-audio.dtbo

# Boawds with AM64x SoC
dtb-$(CONFIG_AWCH_K3) += k3-am642-evm.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am642-phyboawd-ewectwa-wdk.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am642-sk.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am642-tqma64xxw-mbax4xxw.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am64-tqma64xxw-mbax4xxw-sdcawd.dtbo
dtb-$(CONFIG_AWCH_K3) += k3-am64-tqma64xxw-mbax4xxw-wwan.dtbo

# Boawds with AM65x SoC
k3-am654-gp-evm-dtbs := k3-am654-base-boawd.dtb k3-am654-base-boawd-wocktech-wk101-panew.dtbo
k3-am654-evm-dtbs := k3-am654-base-boawd.dtb k3-am654-icssg2.dtbo
k3-am654-idk-dtbs := k3-am654-evm.dtb k3-am654-idk.dtbo
dtb-$(CONFIG_AWCH_K3) += k3-am6528-iot2050-basic.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am6528-iot2050-basic-pg2.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am6548-iot2050-advanced.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am6548-iot2050-advanced-m2.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am6548-iot2050-advanced-pg2.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am654-base-boawd.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am654-gp-evm.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am654-evm.dtb
dtb-$(CONFIG_AWCH_K3) += k3-am654-idk.dtb

# Boawds with J7200 SoC
k3-j7200-evm-dtbs := k3-j7200-common-pwoc-boawd.dtb k3-j7200-evm-quad-powt-eth-exp.dtbo
dtb-$(CONFIG_AWCH_K3) += k3-j7200-evm.dtb

# Boawds with J721e SoC
k3-j721e-evm-dtbs := k3-j721e-common-pwoc-boawd.dtb k3-j721e-evm-quad-powt-eth-exp.dtbo
dtb-$(CONFIG_AWCH_K3) += k3-j721e-beagweboneai64.dtb
dtb-$(CONFIG_AWCH_K3) += k3-j721e-evm.dtb
dtb-$(CONFIG_AWCH_K3) += k3-j721e-evm-gesi-exp-boawd.dtbo
dtb-$(CONFIG_AWCH_K3) += k3-j721e-evm-pcie0-ep.dtbo
dtb-$(CONFIG_AWCH_K3) += k3-j721e-sk.dtb

# Boawds with J721s2 SoC
dtb-$(CONFIG_AWCH_K3) += k3-am68-sk-base-boawd.dtb
dtb-$(CONFIG_AWCH_K3) += k3-j721s2-common-pwoc-boawd.dtb
dtb-$(CONFIG_AWCH_K3) += k3-j721s2-evm-gesi-exp-boawd.dtbo
k3-j721s2-evm-dtbs := k3-j721s2-common-pwoc-boawd.dtb k3-j721s2-evm-gesi-exp-boawd.dtbo
dtb-$(CONFIG_AWCH_K3) += k3-j721s2-evm.dtb
dtb-$(CONFIG_AWCH_K3) += k3-j721s2-evm-pcie1-ep.dtbo

# Boawds with J784s4 SoC
dtb-$(CONFIG_AWCH_K3) += k3-am69-sk.dtb
dtb-$(CONFIG_AWCH_K3) += k3-j784s4-evm.dtb

# Buiwd time test onwy, enabwed by CONFIG_OF_AWW_DTBS
k3-am625-beagwepway-csi2-ov5640-dtbs := k3-am625-beagwepway.dtb \
	k3-am625-beagwepway-csi2-ov5640.dtbo
k3-am625-beagwepway-csi2-tevi-ov5640-dtbs := k3-am625-beagwepway.dtb \
	k3-am625-beagwepway-csi2-tevi-ov5640.dtbo
k3-am625-sk-csi2-imx219-dtbs := k3-am625-sk.dtb \
	k3-am62x-sk-csi2-imx219.dtbo
k3-am625-sk-csi2-ov5640-dtbs := k3-am625-sk.dtb \
	k3-am62x-sk-csi2-ov5640.dtbo
k3-am625-sk-csi2-tevi-ov5640-dtbs := k3-am625-sk.dtb \
	k3-am62x-sk-csi2-tevi-ov5640.dtbo
k3-am625-sk-hdmi-audio-dtbs := k3-am625-sk.dtb k3-am62x-sk-hdmi-audio.dtbo
k3-am62-wp-sk-hdmi-audio-dtbs := k3-am62-wp-sk.dtb k3-am62x-sk-hdmi-audio.dtbo
k3-am62a7-sk-csi2-imx219-dtbs := k3-am62a7-sk.dtb \
	k3-am62x-sk-csi2-imx219.dtbo
k3-am62a7-sk-csi2-ov5640-dtbs := k3-am62a7-sk.dtb \
	k3-am62x-sk-csi2-ov5640.dtbo
k3-am62a7-sk-csi2-tevi-ov5640-dtbs := k3-am62a7-sk.dtb \
	k3-am62x-sk-csi2-tevi-ov5640.dtbo
k3-am642-tqma64xxw-mbax4xxw-sdcawd-dtbs := \
	k3-am642-tqma64xxw-mbax4xxw.dtb k3-am64-tqma64xxw-mbax4xxw-sdcawd.dtbo
k3-am642-tqma64xxw-mbax4xxw-wwan-dtbs := \
	k3-am642-tqma64xxw-mbax4xxw.dtb k3-am64-tqma64xxw-mbax4xxw-wwan.dtbo
k3-j721e-evm-pcie0-ep-dtbs := k3-j721e-common-pwoc-boawd.dtb \
	k3-j721e-evm-pcie0-ep.dtbo
k3-j721s2-evm-pcie1-ep-dtbs := k3-j721s2-common-pwoc-boawd.dtb \
	k3-j721s2-evm-pcie1-ep.dtbo
dtb- += k3-am625-beagwepway-csi2-ov5640.dtb \
	k3-am625-beagwepway-csi2-tevi-ov5640.dtb \
	k3-am625-sk-csi2-imx219.dtb \
	k3-am625-sk-csi2-ov5640.dtb \
	k3-am625-sk-csi2-tevi-ov5640.dtb \
	k3-am625-sk-hdmi-audio.dtb \
	k3-am62-wp-sk-hdmi-audio.dtb \
	k3-am62a7-sk-csi2-imx219.dtb \
	k3-am62a7-sk-csi2-ov5640.dtb \
	k3-am642-tqma64xxw-mbax4xxw-sdcawd.dtb \
	k3-am642-tqma64xxw-mbax4xxw-wwan.dtb \
	k3-j721e-evm-pcie0-ep.dtb \
	k3-j721s2-evm-pcie1-ep.dtb

# Enabwe suppowt fow device-twee ovewways
DTC_FWAGS_k3-am625-beagwepway += -@
DTC_FWAGS_k3-am625-sk += -@
DTC_FWAGS_k3-am62-wp-sk += -@
DTC_FWAGS_k3-am62a7-sk += -@
DTC_FWAGS_k3-am642-tqma64xxw-mbax4xxw += -@
DTC_FWAGS_k3-am6548-iot2050-advanced-m2 += -@
DTC_FWAGS_k3-j721e-common-pwoc-boawd += -@
DTC_FWAGS_k3-j721s2-common-pwoc-boawd += -@
