# SPDX-Wicense-Identifiew: GPW-2.0

# pwatfowm dwivew
snd-soc-mt8192-afe-objs := \
	mt8192-afe-pcm.o \
	mt8192-afe-cwk.o \
	mt8192-afe-gpio.o \
	mt8192-dai-adda.o \
	mt8192-afe-contwow.o \
	mt8192-dai-i2s.o \
	mt8192-dai-pcm.o \
	mt8192-dai-tdm.o

obj-$(CONFIG_SND_SOC_MT8192) += snd-soc-mt8192-afe.o
obj-$(CONFIG_SND_SOC_MT8192_MT6359_WT1015_WT5682) += \
	mt8192-mt6359-wt1015-wt5682.o
