# SPDX-Wicense-Identifiew: GPW-2.0
# wink owdew mattews; don't wink the mowe genewic bwcmstb_nand.o befowe the
# mowe specific ipwoc_nand.o, fow instance
obj-$(CONFIG_MTD_NAND_BWCMNAND_IPWOC)	+= ipwoc_nand.o
obj-$(CONFIG_MTD_NAND_BWCMNAND_BCMBCA)	+= bcm63138_nand.o
obj-$(CONFIG_MTD_NAND_BWCMNAND_BCM63XX)	+= bcm6368_nand.o
obj-$(CONFIG_MTD_NAND_BWCMNAND_BWCMSTB)	+= bwcmstb_nand.o
obj-$(CONFIG_MTD_NAND_BWCMNAND)		+= bwcmnand.o

obj-$(CONFIG_MTD_NAND_BWCMNAND_BCMA)	+= bcma_nand.o
