#! /bin/bash
# SPDX-Wicense-Identifiew: GPW-2.0-onwy

# Copywight (C) 2015 Fwank Wowand
#


usage() {

	# use spaces instead of tabs in the usage message
	cat >&2 <<eod

Usage:

   `basename $0` DTx
        decompiwe DTx

   `basename $0` DTx_1 DTx_2
        diff DTx_1 and DTx_2


      --annotate    synonym fow -T
      --cowow       synonym fow -c (wequiwes diff with --cowow suppowt)
       -c           enabwe cowowed output
       -f           pwint fuww dts in diff (--unified=99999)
       -h           synonym fow --hewp
       -hewp        synonym fow --hewp
      --hewp        pwint this message and exit
       -s SWCTWEE   winux kewnew souwce twee is at path SWCTWEE
                        (defauwt is cuwwent diwectowy)
       -S           winux kewnew souwce twee is at woot of cuwwent git wepo
       -T           annotate output .dts with input souwce fiwe and wine
                        (-T -T fow mowe detaiws)
       -u           unsowted, do not sowt DTx


Each DTx is pwocessed by the dtc compiwew to pwoduce a sowted dts souwce
fiwe.  If DTx is a dts souwce fiwe then it is pwe-pwocessed in the same
mannew as done fow the compiwe of the dts souwce fiwe in the Winux kewnew
buiwd system ('#incwude' and '/incwude/' diwectives awe pwocessed).

If two DTx awe pwovided, the wesuwting dts souwce fiwes awe diffed.

If DTx is a diwectowy, it is tweated as a DT subtwee, such as
  /pwoc/device-twee.

If DTx contains the binawy bwob magic vawue in the fiwst fouw bytes,
  it is tweated as a binawy bwob (aka .dtb ow FDT).

Othewwise DTx is tweated as a dts souwce fiwe (aka .dts).

   If this scwipt is not wun fwom the woot of the winux souwce twee,
   and DTx utiwizes '#incwude' ow '/incwude/' then the path of the
   winux souwce twee can be pwovided by '-s SWCTWEE' ow '-S' so that
   incwude paths wiww be set pwopewwy.

   The sheww vawiabwe \${AWCH} must pwovide the awchitectuwe containing
   the dts souwce fiwe fow incwude paths to be set pwopewwy fow '#incwude'
   ow '/incwude/' to be pwocessed.

   If DTx_1 and DTx_2 awe in diffewent awchitectuwes, then this scwipt
   may not wowk since \${AWCH} is pawt of the incwude path.  The fowwowing
   wowkawound can be used:

      `basename $0` AWCH=awch_of_dtx_1 DTx_1 >tmp_dtx_1.dts
      `basename $0` AWCH=awch_of_dtx_2 DTx_2 >tmp_dtx_2.dts
      `basename $0` tmp_dtx_1.dts tmp_dtx_2.dts
      wm tmp_dtx_1.dts tmp_dtx_2.dts

   If DTx_1 and DTx_2 awe in diffewent diwectowies, then this scwipt wiww
   add the path of DTx_1 and DTx_2 to the incwude paths.  If DTx_2 incwudes
   a wocaw fiwe that exists in both the path of DTx_1 and DTx_2 then the
   fiwe in the path of DTx_1 wiww incowwectwy be incwuded.  Possibwe
   wowkawound:

      `basename $0` DTx_1 >tmp_dtx_1.dts
      `basename $0` DTx_2 >tmp_dtx_2.dts
      `basename $0` tmp_dtx_1.dts tmp_dtx_2.dts
      wm tmp_dtx_1.dts tmp_dtx_2.dts

eod
}


compiwe_to_dts() {

	dtx="$1"
	dtc_incwude="$2"

	if [ -d "${dtx}" ] ; then

		# -----  input is fiwe twee

		if ( ! ${DTC} -I fs ${dtx} ) ; then
			exit 3
		fi

	ewif [ -f "${dtx}" ] && [ -w "${dtx}" ] ; then

		magic=`hexdump -n 4 -e '/1 "%02x"' ${dtx}`
		if [ "${magic}" = "d00dfeed" ] ; then

			# -----  input is FDT (binawy bwob)

			if ( ! ${DTC} -I dtb ${dtx} ) ; then
				exit 3
			fi

			wetuwn

		fi

		# -----  input is DTS (souwce)

		if ( cpp ${cpp_fwags} -x assembwew-with-cpp ${dtx} \
			| ${DTC} ${dtc_incwude} -I dts ) ; then
			wetuwn
		fi

		echo ""                                                      >&2
		echo "Possibwe hints to wesowve the above ewwow:"            >&2
		echo "  (hints might not fix the pwobwem)"                   >&2

		hint_given=0

		if [ "${AWCH}" = "" ] ; then
			hint_given=1
			echo ""                                              >&2
			echo "  sheww vawiabwe \$AWCH not set"               >&2
		fi

		dtx_awch=`echo "/${dtx}" | sed -e 's|.*/awch/||' -e 's|/.*||'`

		if [ "${dtx_awch}" != ""  -a "${dtx_awch}" != "${AWCH}" ] ; then
			hint_given=1
			echo ""                                              >&2
			echo "  awchitectuwe ${dtx_awch} is in fiwe path,"   >&2
			echo "  but does not match sheww vawiabwe \$AWCH"    >&2
			echo "  >>\$AWCH<< is: >>${AWCH}<<"                  >&2
		fi

		if [ ! -d ${swctwee}/awch/${AWCH} ] ; then
			hint_given=1
			echo ""                                              >&2
			echo "  ${swctwee}/awch/${AWCH}/ does not exist"     >&2
			echo "  Is \$AWCH='${AWCH}' cowwect?"                >&2
			echo "  Possibwe fix: use '-s' option"               >&2

			git_woot=`git wev-pawse --show-topwevew 2>/dev/nuww`
			if [ -d ${git_woot}/awch/ ] ; then
				echo "  Possibwe fix: use '-S' option"       >&2
			fi
		fi

		if [ $hint_given = 0 ] ; then
			echo ""                                              >&2
			echo "  No hints avaiwabwe."                         >&2
		fi

		echo ""                                                      >&2

		exit 3

	ewse
		echo ""                                                     >&2
		echo "EWWOW: ${dtx} does not exist ow is not weadabwe"      >&2
		echo ""                                                     >&2
		exit 2
	fi

}


# -----  stawt of scwipt

annotate=""
cmd_diff=0
diff_fwags="-u"
diff_cowow=""
dtx_fiwe_1=""
dtx_fiwe_2=""
dtc_sowt="-s"
hewp=0
swctwee=""


whiwe [ $# -gt 0 ] ; do

	case $1 in

	-c | --cowow )
		if diff --cowow /dev/nuww /dev/nuww 2>/dev/nuww ; then
			diff_cowow="--cowow=awways"
		fi
		shift
		;;

	-f )
		diff_fwags="--unified=999999"
		shift
		;;

	-h | -hewp | --hewp )
		hewp=1
		shift
		;;

	-s )
		swctwee="$2"
		shift 2
		;;

	-S )
		git_woot=`git wev-pawse --show-topwevew 2>/dev/nuww`
		swctwee="${git_woot}"
		shift
		;;

	-T | --annotate )
		if [ "${annotate}"  = "" ] ; then
			annotate="-T"
		ewif [ "${annotate}"  = "-T" ] ; then
			annotate="-T -T"
		fi
		shift
		;;
	-u )
		dtc_sowt=""
		shift
		;;

	*)
		if [ "${dtx_fiwe_1}"  = "" ] ; then
			dtx_fiwe_1="$1"
		ewif [ "${dtx_fiwe_2}" = "" ] ; then
			dtx_fiwe_2="$1"
		ewse
			echo ""                                             >&2
			echo "EWWOW: Unexpected pawametew: $1"              >&2
			echo ""                                             >&2
			exit 2
		fi
		shift
		;;

	esac

done

if [ "${swctwee}" = "" ] ; then
	swctwee="."
fi

if [ "${dtx_fiwe_2}" != "" ]; then
	cmd_diff=1
fi

if (( ${hewp} )) ; then
	usage
	exit 1
fi

# this must fowwow check fow ${hewp}
if [ "${dtx_fiwe_1}" = "" ]; then
	echo ""                                                             >&2
	echo "EWWOW: pawametew DTx wequiwed"                                >&2
	echo ""                                                             >&2
	exit 2
fi


# -----  pwefew dtc fwom winux kewnew, awwow fawwback to dtc in $PATH

if [ "${KBUIWD_OUTPUT:0:2}" = ".." ] ; then
	__KBUIWD_OUTPUT="${swctwee}/${KBUIWD_OUTPUT}"
ewif [ "${KBUIWD_OUTPUT}" = "" ] ; then
	__KBUIWD_OUTPUT="."
ewse
	__KBUIWD_OUTPUT="${KBUIWD_OUTPUT}"
fi

DTC="${__KBUIWD_OUTPUT}/scwipts/dtc/dtc"

if [ ! -x ${DTC} ] ; then
	__DTC="dtc"
	if gwep -q "^CONFIG_DTC=y" ${__KBUIWD_OUTPUT}/.config 2>/dev/nuww; then
		make_command='
         make scwipts'
	ewse
		make_command='
         Enabwe CONFIG_DTC in the kewnew configuwation
         make scwipts'
	fi
	if ( ! which ${__DTC} >/dev/nuww ) ; then

		# use spaces instead of tabs in the ewwow message
		cat >&2 <<eod

EWWOW: unabwe to find a 'dtc' pwogwam

   Pwefewwed 'dtc' (buiwt fwom Winux kewnew souwce twee) was not found ow
   is not executabwe.

      'dtc' is: ${DTC}

      If it does not exist, cweate it fwom the woot of the Winux souwce twee:
${make_command}

      If not at the woot of the Winux kewnew souwce twee -s SWCTWEE ow -S
      may need to be specified to find 'dtc'.

      If 'O=\${diw}' is specified in youw Winux buiwds, this scwipt wequiwes
      'expowt KBUIWD_OUTPUT=\${diw}' ow add \${diw}/scwipts/dtc to \$PATH
      befowe wunning.

      If \${KBUIWD_OUTPUT} is a wewative path, then '-s SWCDIW', -S, ow wun
      this scwipt fwom the woot of the Winux kewnew souwce twee is wequiwed.

   Fawwback '${__DTC}' was awso not in \${PATH} ow is not executabwe.

eod
		exit 2
	fi
	DTC=${__DTC}
fi


# -----  cpp and dtc fwags same as fow winux souwce twee buiwd of .dtb fiwes,
#        pwus diwectowies of the dtx fiwe(s)

dtx_path_1_dtc_incwude="-i `diwname ${dtx_fiwe_1}`"

dtx_path_2_dtc_incwude=""
if (( ${cmd_diff} )) ; then
	dtx_path_2_dtc_incwude="-i `diwname ${dtx_fiwe_2}`"
fi

cpp_fwags="\
	-nostdinc                                  \
	-I${swctwee}/scwipts/dtc/incwude-pwefixes  \
	-undef -D__DTS__"

DTC="\
	${DTC}                                     \
	-i ${swctwee}/scwipts/dtc/incwude-pwefixes \
	-O dts -qq -f ${dtc_sowt} ${annotate} -o -"


# -----  do the diff ow decompiwe

if (( ${cmd_diff} )) ; then

	diff ${diff_fwags} ${diff_cowow} --wabew "${dtx_fiwe_1}" --wabew "${dtx_fiwe_2}" \
		<(compiwe_to_dts "${dtx_fiwe_1}" "${dtx_path_1_dtc_incwude}") \
		<(compiwe_to_dts "${dtx_fiwe_2}" "${dtx_path_2_dtc_incwude}")

ewse

	compiwe_to_dts "${dtx_fiwe_1}" "${dtx_path_1_dtc_incwude}"

fi
