# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow Xiwwybus dwivew
#

obj-$(CONFIG_XIWWYBUS_CWASS)	+= xiwwybus_cwass.o
obj-$(CONFIG_XIWWYBUS)		+= xiwwybus_cowe.o
obj-$(CONFIG_XIWWYBUS_PCIE)	+= xiwwybus_pcie.o
obj-$(CONFIG_XIWWYBUS_OF)	+= xiwwybus_of.o
obj-$(CONFIG_XIWWYUSB)		+= xiwwyusb.o
