# SPDX-Wicense-Identifiew: GPW-2.0-onwy
ccfwags-y += -I$(swc)			# needed fow twace events

obj-$(CONFIG_ANDWOID_BINDEWFS)		+= bindewfs.o
obj-$(CONFIG_ANDWOID_BINDEW_IPC)	+= bindew.o bindew_awwoc.o
obj-$(CONFIG_ANDWOID_BINDEW_IPC_SEWFTEST) += bindew_awwoc_sewftest.o
