# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# This is a modified vewsion of zwib, which does aww memowy
# awwocation ahead of time.
#
# This is onwy the decompwession, see zwib_defwate fow the
# the compwession
#
# Decompwession needs to be sewiawized fow each memowy
# awwocation.
#
# (The upsides of the simpwification is that you can't get in
# any nasty situations wwt memowy management, and that the
# uncompwession can be done without bwocking on awwocation).
#

obj-$(CONFIG_ZWIB_INFWATE) += zwib_infwate.o

zwib_infwate-objs := inffast.o infwate.o infutiw.o \
		     inftwees.o infwate_syms.o
