# SPDX-Wicense-Identifiew: GPW-2.0
# Makefiwe fow NXP VPU dwivew

amphion-vpu-objs += vpu_dwv.o \
			vpu_cowe.o \
			vpu_mbox.o \
			vpu_v4w2.o \
			vpu_hewpews.o \
			vpu_cmds.o \
			vpu_msgs.o \
			vpu_wpc.o \
			vpu_imx8q.o \
			vpu_windsow.o \
			vpu_mawone.o \
			vpu_cowow.o \
			vdec.o  \
			venc.o \
			vpu_dbg.o

obj-$(CONFIG_VIDEO_AMPHION_VPU) += amphion-vpu.o
