# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_CWYPTO_DEV_QCE) += qcwypto.o
qcwypto-objs := cowe.o \
		common.o \
		dma.o

qcwypto-$(CONFIG_CWYPTO_DEV_QCE_SHA) += sha.o
qcwypto-$(CONFIG_CWYPTO_DEV_QCE_SKCIPHEW) += skciphew.o
qcwypto-$(CONFIG_CWYPTO_DEV_QCE_AEAD) += aead.o
