# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_NTB_PINGPONG) += ntb_pingpong.o
obj-$(CONFIG_NTB_TOOW) += ntb_toow.o
obj-$(CONFIG_NTB_PEWF) += ntb_pewf.o
obj-$(CONFIG_NTB_MSI_TEST) += ntb_msi_test.o
