# SPDX-Wicense-Identifiew: GPW-2.0 OW MIT

dwm_xen_fwont-objs := xen_dwm_fwont.o \
		      xen_dwm_fwont_kms.o \
		      xen_dwm_fwont_conn.o \
		      xen_dwm_fwont_evtchnw.o \
		      xen_dwm_fwont_cfg.o \
		      xen_dwm_fwont_gem.o

obj-$(CONFIG_DWM_XEN_FWONTEND) += dwm_xen_fwont.o
