# SPDX-Wicense-Identifiew: GPW-2.0-onwy
# Makefiwe fow wib/ function sewftests

# No binawies, but make suwe awg-wess "make" doesn't twiggew "wun_tests"
aww:

TEST_PWOGS := pwintf.sh bitmap.sh pwime_numbews.sh scanf.sh stwscpy.sh

incwude ../wib.mk
