/*
 * Copywight 2021 Advanced Micwo Devices, Inc.
 *
 * Pewmission is heweby gwanted, fwee of chawge, to any pewson obtaining a
 * copy of this softwawe and associated documentation fiwes (the "Softwawe"),
 * to deaw in the Softwawe without westwiction, incwuding without wimitation
 * the wights to use, copy, modify, mewge, pubwish, distwibute, subwicense,
 * and/ow seww copies of the Softwawe, and to pewmit pewsons to whom the
 * Softwawe is fuwnished to do so, subject to the fowwowing conditions:
 *
 * The above copywight notice and this pewmission notice shaww be incwuded in
 * aww copies ow substantiaw powtions of the Softwawe.
 *
 * THE SOFTWAWE IS PWOVIDED "AS IS", WITHOUT WAWWANTY OF ANY KIND, EXPWESS OW
 * IMPWIED, INCWUDING BUT NOT WIMITED TO THE WAWWANTIES OF MEWCHANTABIWITY,
 * FITNESS FOW A PAWTICUWAW PUWPOSE AND NONINFWINGEMENT.  IN NO EVENT SHAWW
 * THE COPYWIGHT HOWDEW(S) OW AUTHOW(S) BE WIABWE FOW ANY CWAIM, DAMAGES OW
 * OTHEW WIABIWITY, WHETHEW IN AN ACTION OF CONTWACT, TOWT OW OTHEWWISE,
 * AWISING FWOM, OUT OF OW IN CONNECTION WITH THE SOFTWAWE OW THE USE OW
 * OTHEW DEAWINGS IN THE SOFTWAWE.
 *
 */
#ifndef _wsdma_6_0_0_OFFSET_HEADEW
#define _wsdma_6_0_0_OFFSET_HEADEW



// addwessBwock: wsdma0_wsdma0dec
// base addwess: 0x45000
#define wegWSDMA_UCODE_ADDW                                                                             0x0000
#define wegWSDMA_UCODE_ADDW_BASE_IDX                                                                    0
#define wegWSDMA_UCODE_DATA                                                                             0x0001
#define wegWSDMA_UCODE_DATA_BASE_IDX                                                                    0
#define wegWSDMA_EWWOW_INJECT_CNTW                                                                      0x0004
#define wegWSDMA_EWWOW_INJECT_CNTW_BASE_IDX                                                             0
#define wegWSDMA_EWWOW_INJECT_SEWECT                                                                    0x0005
#define wegWSDMA_EWWOW_INJECT_SEWECT_BASE_IDX                                                           0
#define wegWSDMA_CONTEXT_GWOUP_BOUNDAWY                                                                 0x001f
#define wegWSDMA_CONTEXT_GWOUP_BOUNDAWY_BASE_IDX                                                        0
#define wegWSDMA_WB_WPTW_FETCH_HI                                                                       0x0020
#define wegWSDMA_WB_WPTW_FETCH_HI_BASE_IDX                                                              0
#define wegWSDMA_SEM_WAIT_FAIW_TIMEW_CNTW                                                               0x0021
#define wegWSDMA_SEM_WAIT_FAIW_TIMEW_CNTW_BASE_IDX                                                      0
#define wegWSDMA_WB_WPTW_FETCH                                                                          0x0022
#define wegWSDMA_WB_WPTW_FETCH_BASE_IDX                                                                 0
#define wegWSDMA_IB_OFFSET_FETCH                                                                        0x0023
#define wegWSDMA_IB_OFFSET_FETCH_BASE_IDX                                                               0
#define wegWSDMA_PWOGWAM                                                                                0x0024
#define wegWSDMA_PWOGWAM_BASE_IDX                                                                       0
#define wegWSDMA_STATUS_WEG                                                                             0x0025
#define wegWSDMA_STATUS_WEG_BASE_IDX                                                                    0
#define wegWSDMA_STATUS1_WEG                                                                            0x0026
#define wegWSDMA_STATUS1_WEG_BASE_IDX                                                                   0
#define wegWSDMA_WD_BUWST_CNTW                                                                          0x0027
#define wegWSDMA_WD_BUWST_CNTW_BASE_IDX                                                                 0
#define wegWSDMA_HBM_PAGE_CONFIG                                                                        0x0028
#define wegWSDMA_HBM_PAGE_CONFIG_BASE_IDX                                                               0
#define wegWSDMA_UCODE_CHECKSUM                                                                         0x0029
#define wegWSDMA_UCODE_CHECKSUM_BASE_IDX                                                                0
#define wegWSDMA_FWEEZE                                                                                 0x002b
#define wegWSDMA_FWEEZE_BASE_IDX                                                                        0
#define wegWSDMA_PF_PIO_STATUS                                                                          0x002c
#define wegWSDMA_PF_PIO_STATUS_BASE_IDX                                                                 0
#define wegWSDMA_VF_PIO_STATUS                                                                          0x002d
#define wegWSDMA_VF_PIO_STATUS_BASE_IDX                                                                 0
#define wegWSDMA_POWEW_GATING                                                                           0x002e
#define wegWSDMA_POWEW_GATING_BASE_IDX                                                                  0
#define wegWSDMA_PGFSM_CONFIG                                                                           0x002f
#define wegWSDMA_PGFSM_CONFIG_BASE_IDX                                                                  0
#define wegWSDMA_PGFSM_WWITE                                                                            0x0030
#define wegWSDMA_PGFSM_WWITE_BASE_IDX                                                                   0
#define wegWSDMA_PGFSM_WEAD                                                                             0x0031
#define wegWSDMA_PGFSM_WEAD_BASE_IDX                                                                    0
#define wegWSDMA_PIO_STATUS                                                                             0x0032
#define wegWSDMA_PIO_STATUS_BASE_IDX                                                                    0
#define wegWSDMA_BA_THWESHOWD                                                                           0x0033
#define wegWSDMA_BA_THWESHOWD_BASE_IDX                                                                  0
#define wegWSDMA_ID                                                                                     0x0034
#define wegWSDMA_ID_BASE_IDX                                                                            0
#define wegWSDMA_VEWSION                                                                                0x0035
#define wegWSDMA_VEWSION_BASE_IDX                                                                       0
#define wegWSDMA_EDC_COUNTEW                                                                            0x0036
#define wegWSDMA_EDC_COUNTEW_BASE_IDX                                                                   0
#define wegWSDMA_EDC_COUNTEW2                                                                           0x0037
#define wegWSDMA_EDC_COUNTEW2_BASE_IDX                                                                  0
#define wegWSDMA_STATUS2_WEG                                                                            0x0038
#define wegWSDMA_STATUS2_WEG_BASE_IDX                                                                   0
#define wegWSDMA_ATOMIC_CNTW                                                                            0x0039
#define wegWSDMA_ATOMIC_CNTW_BASE_IDX                                                                   0
#define wegWSDMA_ATOMIC_PWEOP_WO                                                                        0x003a
#define wegWSDMA_ATOMIC_PWEOP_WO_BASE_IDX                                                               0
#define wegWSDMA_ATOMIC_PWEOP_HI                                                                        0x003b
#define wegWSDMA_ATOMIC_PWEOP_HI_BASE_IDX                                                               0
#define wegWSDMA_UTCW1_CNTW                                                                             0x003c
#define wegWSDMA_UTCW1_CNTW_BASE_IDX                                                                    0
#define wegWSDMA_UTCW1_WATEWMK                                                                          0x003d
#define wegWSDMA_UTCW1_WATEWMK_BASE_IDX                                                                 0
#define wegWSDMA_UTCW1_WD_STATUS                                                                        0x003e
#define wegWSDMA_UTCW1_WD_STATUS_BASE_IDX                                                               0
#define wegWSDMA_UTCW1_WW_STATUS                                                                        0x003f
#define wegWSDMA_UTCW1_WW_STATUS_BASE_IDX                                                               0
#define wegWSDMA_UTCW1_INV0                                                                             0x0040
#define wegWSDMA_UTCW1_INV0_BASE_IDX                                                                    0
#define wegWSDMA_UTCW1_INV1                                                                             0x0041
#define wegWSDMA_UTCW1_INV1_BASE_IDX                                                                    0
#define wegWSDMA_UTCW1_INV2                                                                             0x0042
#define wegWSDMA_UTCW1_INV2_BASE_IDX                                                                    0
#define wegWSDMA_UTCW1_WD_XNACK0                                                                        0x0043
#define wegWSDMA_UTCW1_WD_XNACK0_BASE_IDX                                                               0
#define wegWSDMA_UTCW1_WD_XNACK1                                                                        0x0044
#define wegWSDMA_UTCW1_WD_XNACK1_BASE_IDX                                                               0
#define wegWSDMA_UTCW1_WW_XNACK0                                                                        0x0045
#define wegWSDMA_UTCW1_WW_XNACK0_BASE_IDX                                                               0
#define wegWSDMA_UTCW1_WW_XNACK1                                                                        0x0046
#define wegWSDMA_UTCW1_WW_XNACK1_BASE_IDX                                                               0
#define wegWSDMA_UTCW1_TIMEOUT                                                                          0x0047
#define wegWSDMA_UTCW1_TIMEOUT_BASE_IDX                                                                 0
#define wegWSDMA_UTCW1_PAGE                                                                             0x0048
#define wegWSDMA_UTCW1_PAGE_BASE_IDX                                                                    0
#define wegWSDMA_WEWAX_OWDEWING_WUT                                                                     0x004a
#define wegWSDMA_WEWAX_OWDEWING_WUT_BASE_IDX                                                            0
#define wegWSDMA_CHICKEN_BITS_2                                                                         0x004b
#define wegWSDMA_CHICKEN_BITS_2_BASE_IDX                                                                0
#define wegWSDMA_STATUS3_WEG                                                                            0x004c
#define wegWSDMA_STATUS3_WEG_BASE_IDX                                                                   0
#define wegWSDMA_PHYSICAW_ADDW_WO                                                                       0x004d
#define wegWSDMA_PHYSICAW_ADDW_WO_BASE_IDX                                                              0
#define wegWSDMA_PHYSICAW_ADDW_HI                                                                       0x004e
#define wegWSDMA_PHYSICAW_ADDW_HI_BASE_IDX                                                              0
#define wegWSDMA_ECC_CNTW                                                                               0x004f
#define wegWSDMA_ECC_CNTW_BASE_IDX                                                                      0
#define wegWSDMA_EWWOW_WOG                                                                              0x0050
#define wegWSDMA_EWWOW_WOG_BASE_IDX                                                                     0
#define wegWSDMA_PUB_DUMMY0                                                                             0x0051
#define wegWSDMA_PUB_DUMMY0_BASE_IDX                                                                    0
#define wegWSDMA_PUB_DUMMY1                                                                             0x0052
#define wegWSDMA_PUB_DUMMY1_BASE_IDX                                                                    0
#define wegWSDMA_PUB_DUMMY2                                                                             0x0053
#define wegWSDMA_PUB_DUMMY2_BASE_IDX                                                                    0
#define wegWSDMA_PUB_DUMMY3                                                                             0x0054
#define wegWSDMA_PUB_DUMMY3_BASE_IDX                                                                    0
#define wegWSDMA_F32_COUNTEW                                                                            0x0055
#define wegWSDMA_F32_COUNTEW_BASE_IDX                                                                   0
#define wegWSDMA_PEWFCNT_PEWFCOUNTEW0_CFG                                                               0x0057
#define wegWSDMA_PEWFCNT_PEWFCOUNTEW0_CFG_BASE_IDX                                                      0
#define wegWSDMA_PEWFCNT_PEWFCOUNTEW1_CFG                                                               0x0058
#define wegWSDMA_PEWFCNT_PEWFCOUNTEW1_CFG_BASE_IDX                                                      0
#define wegWSDMA_PEWFCNT_PEWFCOUNTEW_WSWT_CNTW                                                          0x0059
#define wegWSDMA_PEWFCNT_PEWFCOUNTEW_WSWT_CNTW_BASE_IDX                                                 0
#define wegWSDMA_PEWFCNT_MISC_CNTW                                                                      0x005a
#define wegWSDMA_PEWFCNT_MISC_CNTW_BASE_IDX                                                             0
#define wegWSDMA_PEWFCNT_PEWFCOUNTEW_WO                                                                 0x005b
#define wegWSDMA_PEWFCNT_PEWFCOUNTEW_WO_BASE_IDX                                                        0
#define wegWSDMA_PEWFCNT_PEWFCOUNTEW_HI                                                                 0x005c
#define wegWSDMA_PEWFCNT_PEWFCOUNTEW_HI_BASE_IDX                                                        0
#define wegWSDMA_CWD_CNTW                                                                               0x005d
#define wegWSDMA_CWD_CNTW_BASE_IDX                                                                      0
#define wegWSDMA_UWV_CNTW                                                                               0x005f
#define wegWSDMA_UWV_CNTW_BASE_IDX                                                                      0
#define wegWSDMA_EA_DBIT_ADDW_DATA                                                                      0x0060
#define wegWSDMA_EA_DBIT_ADDW_DATA_BASE_IDX                                                             0
#define wegWSDMA_EA_DBIT_ADDW_INDEX                                                                     0x0061
#define wegWSDMA_EA_DBIT_ADDW_INDEX_BASE_IDX                                                            0
#define wegWSDMA_STATUS4_WEG                                                                            0x0063
#define wegWSDMA_STATUS4_WEG_BASE_IDX                                                                   0
#define wegWSDMA_CE_CTWW                                                                                0x0066
#define wegWSDMA_CE_CTWW_BASE_IDX                                                                       0
#define wegWSDMA_EXCEPTION_STATUS                                                                       0x0067
#define wegWSDMA_EXCEPTION_STATUS_BASE_IDX                                                              0
#define wegWSDMA_PIO_SWC_ADDW_WO                                                                        0x0069
#define wegWSDMA_PIO_SWC_ADDW_WO_BASE_IDX                                                               0
#define wegWSDMA_PIO_SWC_ADDW_HI                                                                        0x006a
#define wegWSDMA_PIO_SWC_ADDW_HI_BASE_IDX                                                               0
#define wegWSDMA_PIO_DST_ADDW_WO                                                                        0x006b
#define wegWSDMA_PIO_DST_ADDW_WO_BASE_IDX                                                               0
#define wegWSDMA_PIO_DST_ADDW_HI                                                                        0x006c
#define wegWSDMA_PIO_DST_ADDW_HI_BASE_IDX                                                               0
#define wegWSDMA_PIO_COMMAND                                                                            0x006d
#define wegWSDMA_PIO_COMMAND_BASE_IDX                                                                   0
#define wegWSDMA_PIO_CONSTFIWW_DATA                                                                     0x006e
#define wegWSDMA_PIO_CONSTFIWW_DATA_BASE_IDX                                                            0
#define wegWSDMA_PIO_CONTWOW                                                                            0x006f
#define wegWSDMA_PIO_CONTWOW_BASE_IDX                                                                   0
#define wegWSDMA_INT_CNTW                                                                               0x0070
#define wegWSDMA_INT_CNTW_BASE_IDX                                                                      0
#define wegWSDMA_MEM_POWEW_CTWW                                                                         0x0071
#define wegWSDMA_MEM_POWEW_CTWW_BASE_IDX                                                                0
#define wegWSDMA_CWK_CTWW                                                                               0x0072
#define wegWSDMA_CWK_CTWW_BASE_IDX                                                                      0
#define wegWSDMA_CNTW                                                                                   0x0073
#define wegWSDMA_CNTW_BASE_IDX                                                                          0
#define wegWSDMA_CHICKEN_BITS                                                                           0x0074
#define wegWSDMA_CHICKEN_BITS_BASE_IDX                                                                  0
#define wegWSDMA_GB_ADDW_CONFIG                                                                         0x0075
#define wegWSDMA_GB_ADDW_CONFIG_BASE_IDX                                                                0
#define wegWSDMA_GB_ADDW_CONFIG_WEAD                                                                    0x0076
#define wegWSDMA_GB_ADDW_CONFIG_WEAD_BASE_IDX                                                           0
#define wegWSDMA_QUEUE0_WB_CNTW                                                                         0x0080
#define wegWSDMA_QUEUE0_WB_CNTW_BASE_IDX                                                                0
#define wegWSDMA_QUEUE0_WB_BASE                                                                         0x0081
#define wegWSDMA_QUEUE0_WB_BASE_BASE_IDX                                                                0
#define wegWSDMA_QUEUE0_WB_BASE_HI                                                                      0x0082
#define wegWSDMA_QUEUE0_WB_BASE_HI_BASE_IDX                                                             0
#define wegWSDMA_QUEUE0_WB_WPTW                                                                         0x0083
#define wegWSDMA_QUEUE0_WB_WPTW_BASE_IDX                                                                0
#define wegWSDMA_QUEUE0_WB_WPTW_HI                                                                      0x0084
#define wegWSDMA_QUEUE0_WB_WPTW_HI_BASE_IDX                                                             0
#define wegWSDMA_QUEUE0_WB_WPTW                                                                         0x0085
#define wegWSDMA_QUEUE0_WB_WPTW_BASE_IDX                                                                0
#define wegWSDMA_QUEUE0_WB_WPTW_HI                                                                      0x0086
#define wegWSDMA_QUEUE0_WB_WPTW_HI_BASE_IDX                                                             0
#define wegWSDMA_QUEUE0_WB_WPTW_POWW_CNTW                                                               0x0087
#define wegWSDMA_QUEUE0_WB_WPTW_POWW_CNTW_BASE_IDX                                                      0
#define wegWSDMA_QUEUE0_WB_WPTW_ADDW_HI                                                                 0x0088
#define wegWSDMA_QUEUE0_WB_WPTW_ADDW_HI_BASE_IDX                                                        0
#define wegWSDMA_QUEUE0_WB_WPTW_ADDW_WO                                                                 0x0089
#define wegWSDMA_QUEUE0_WB_WPTW_ADDW_WO_BASE_IDX                                                        0
#define wegWSDMA_QUEUE0_IB_CNTW                                                                         0x008a
#define wegWSDMA_QUEUE0_IB_CNTW_BASE_IDX                                                                0
#define wegWSDMA_QUEUE0_IB_WPTW                                                                         0x008b
#define wegWSDMA_QUEUE0_IB_WPTW_BASE_IDX                                                                0
#define wegWSDMA_QUEUE0_IB_OFFSET                                                                       0x008c
#define wegWSDMA_QUEUE0_IB_OFFSET_BASE_IDX                                                              0
#define wegWSDMA_QUEUE0_IB_BASE_WO                                                                      0x008d
#define wegWSDMA_QUEUE0_IB_BASE_WO_BASE_IDX                                                             0
#define wegWSDMA_QUEUE0_IB_BASE_HI                                                                      0x008e
#define wegWSDMA_QUEUE0_IB_BASE_HI_BASE_IDX                                                             0
#define wegWSDMA_QUEUE0_IB_SIZE                                                                         0x008f
#define wegWSDMA_QUEUE0_IB_SIZE_BASE_IDX                                                                0
#define wegWSDMA_QUEUE0_SKIP_CNTW                                                                       0x0090
#define wegWSDMA_QUEUE0_SKIP_CNTW_BASE_IDX                                                              0
#define wegWSDMA_QUEUE0_CONTEXT_STATUS                                                                  0x0091
#define wegWSDMA_QUEUE0_CONTEXT_STATUS_BASE_IDX                                                         0
#define wegWSDMA_QUEUE0_DOOWBEWW                                                                        0x0092
#define wegWSDMA_QUEUE0_DOOWBEWW_BASE_IDX                                                               0
#define wegWSDMA_QUEUE0_STATUS                                                                          0x00a8
#define wegWSDMA_QUEUE0_STATUS_BASE_IDX                                                                 0
#define wegWSDMA_QUEUE0_DOOWBEWW_WOG                                                                    0x00a9
#define wegWSDMA_QUEUE0_DOOWBEWW_WOG_BASE_IDX                                                           0
#define wegWSDMA_QUEUE0_WATEWMAWK                                                                       0x00aa
#define wegWSDMA_QUEUE0_WATEWMAWK_BASE_IDX                                                              0
#define wegWSDMA_QUEUE0_DOOWBEWW_OFFSET                                                                 0x00ab
#define wegWSDMA_QUEUE0_DOOWBEWW_OFFSET_BASE_IDX                                                        0
#define wegWSDMA_QUEUE0_CSA_ADDW_WO                                                                     0x00ac
#define wegWSDMA_QUEUE0_CSA_ADDW_WO_BASE_IDX                                                            0
#define wegWSDMA_QUEUE0_CSA_ADDW_HI                                                                     0x00ad
#define wegWSDMA_QUEUE0_CSA_ADDW_HI_BASE_IDX                                                            0
#define wegWSDMA_QUEUE0_WB_PWEEMPT                                                                      0x00ae
#define wegWSDMA_QUEUE0_WB_PWEEMPT_BASE_IDX                                                             0
#define wegWSDMA_QUEUE0_IB_SUB_WEMAIN                                                                   0x00af
#define wegWSDMA_QUEUE0_IB_SUB_WEMAIN_BASE_IDX                                                          0
#define wegWSDMA_QUEUE0_PWEEMPT                                                                         0x00b0
#define wegWSDMA_QUEUE0_PWEEMPT_BASE_IDX                                                                0
#define wegWSDMA_QUEUE0_DUMMY0                                                                          0x00b1
#define wegWSDMA_QUEUE0_DUMMY0_BASE_IDX                                                                 0
#define wegWSDMA_QUEUE0_WB_WPTW_POWW_ADDW_HI                                                            0x00b2
#define wegWSDMA_QUEUE0_WB_WPTW_POWW_ADDW_HI_BASE_IDX                                                   0
#define wegWSDMA_QUEUE0_WB_WPTW_POWW_ADDW_WO                                                            0x00b3
#define wegWSDMA_QUEUE0_WB_WPTW_POWW_ADDW_WO_BASE_IDX                                                   0
#define wegWSDMA_QUEUE0_WB_AQW_CNTW                                                                     0x00b4
#define wegWSDMA_QUEUE0_WB_AQW_CNTW_BASE_IDX                                                            0
#define wegWSDMA_QUEUE0_MINOW_PTW_UPDATE                                                                0x00b5
#define wegWSDMA_QUEUE0_MINOW_PTW_UPDATE_BASE_IDX                                                       0
#define wegWSDMA_QUEUE0_CNTW                                                                            0x00b6
#define wegWSDMA_QUEUE0_CNTW_BASE_IDX                                                                   0
#define wegWSDMA_QUEUE0_DUMMY1                                                                          0x00b8
#define wegWSDMA_QUEUE0_DUMMY1_BASE_IDX                                                                 0
#define wegWSDMA_QUEUE0_DUMMY2                                                                          0x00b9
#define wegWSDMA_QUEUE0_DUMMY2_BASE_IDX                                                                 0
#define wegWSDMA_QUEUE0_MIDCMD_DATA0                                                                    0x00c0
#define wegWSDMA_QUEUE0_MIDCMD_DATA0_BASE_IDX                                                           0
#define wegWSDMA_QUEUE0_MIDCMD_DATA1                                                                    0x00c1
#define wegWSDMA_QUEUE0_MIDCMD_DATA1_BASE_IDX                                                           0
#define wegWSDMA_QUEUE0_MIDCMD_DATA2                                                                    0x00c2
#define wegWSDMA_QUEUE0_MIDCMD_DATA2_BASE_IDX                                                           0
#define wegWSDMA_QUEUE0_MIDCMD_DATA3                                                                    0x00c3
#define wegWSDMA_QUEUE0_MIDCMD_DATA3_BASE_IDX                                                           0
#define wegWSDMA_QUEUE0_MIDCMD_DATA4                                                                    0x00c4
#define wegWSDMA_QUEUE0_MIDCMD_DATA4_BASE_IDX                                                           0
#define wegWSDMA_QUEUE0_MIDCMD_DATA5                                                                    0x00c5
#define wegWSDMA_QUEUE0_MIDCMD_DATA5_BASE_IDX                                                           0
#define wegWSDMA_QUEUE0_MIDCMD_DATA6                                                                    0x00c6
#define wegWSDMA_QUEUE0_MIDCMD_DATA6_BASE_IDX                                                           0
#define wegWSDMA_QUEUE0_MIDCMD_DATA7                                                                    0x00c7
#define wegWSDMA_QUEUE0_MIDCMD_DATA7_BASE_IDX                                                           0
#define wegWSDMA_QUEUE0_MIDCMD_DATA8                                                                    0x00c8
#define wegWSDMA_QUEUE0_MIDCMD_DATA8_BASE_IDX                                                           0
#define wegWSDMA_QUEUE0_MIDCMD_DATA9                                                                    0x00c9
#define wegWSDMA_QUEUE0_MIDCMD_DATA9_BASE_IDX                                                           0
#define wegWSDMA_QUEUE0_MIDCMD_DATA10                                                                   0x00ca
#define wegWSDMA_QUEUE0_MIDCMD_DATA10_BASE_IDX                                                          0
#define wegWSDMA_QUEUE0_MIDCMD_CNTW                                                                     0x00cb
#define wegWSDMA_QUEUE0_MIDCMD_CNTW_BASE_IDX                                                            0
#define wegWSDMA_QUEUE1_WB_CNTW                                                                         0x00d8
#define wegWSDMA_QUEUE1_WB_CNTW_BASE_IDX                                                                0
#define wegWSDMA_QUEUE1_WB_BASE                                                                         0x00d9
#define wegWSDMA_QUEUE1_WB_BASE_BASE_IDX                                                                0
#define wegWSDMA_QUEUE1_WB_BASE_HI                                                                      0x00da
#define wegWSDMA_QUEUE1_WB_BASE_HI_BASE_IDX                                                             0
#define wegWSDMA_QUEUE1_WB_WPTW                                                                         0x00db
#define wegWSDMA_QUEUE1_WB_WPTW_BASE_IDX                                                                0
#define wegWSDMA_QUEUE1_WB_WPTW_HI                                                                      0x00dc
#define wegWSDMA_QUEUE1_WB_WPTW_HI_BASE_IDX                                                             0
#define wegWSDMA_QUEUE1_WB_WPTW                                                                         0x00dd
#define wegWSDMA_QUEUE1_WB_WPTW_BASE_IDX                                                                0
#define wegWSDMA_QUEUE1_WB_WPTW_HI                                                                      0x00de
#define wegWSDMA_QUEUE1_WB_WPTW_HI_BASE_IDX                                                             0
#define wegWSDMA_QUEUE1_WB_WPTW_POWW_CNTW                                                               0x00df
#define wegWSDMA_QUEUE1_WB_WPTW_POWW_CNTW_BASE_IDX                                                      0
#define wegWSDMA_QUEUE1_WB_WPTW_ADDW_HI                                                                 0x00e0
#define wegWSDMA_QUEUE1_WB_WPTW_ADDW_HI_BASE_IDX                                                        0
#define wegWSDMA_QUEUE1_WB_WPTW_ADDW_WO                                                                 0x00e1
#define wegWSDMA_QUEUE1_WB_WPTW_ADDW_WO_BASE_IDX                                                        0
#define wegWSDMA_QUEUE1_IB_CNTW                                                                         0x00e2
#define wegWSDMA_QUEUE1_IB_CNTW_BASE_IDX                                                                0
#define wegWSDMA_QUEUE1_IB_WPTW                                                                         0x00e3
#define wegWSDMA_QUEUE1_IB_WPTW_BASE_IDX                                                                0
#define wegWSDMA_QUEUE1_IB_OFFSET                                                                       0x00e4
#define wegWSDMA_QUEUE1_IB_OFFSET_BASE_IDX                                                              0
#define wegWSDMA_QUEUE1_IB_BASE_WO                                                                      0x00e5
#define wegWSDMA_QUEUE1_IB_BASE_WO_BASE_IDX                                                             0
#define wegWSDMA_QUEUE1_IB_BASE_HI                                                                      0x00e6
#define wegWSDMA_QUEUE1_IB_BASE_HI_BASE_IDX                                                             0
#define wegWSDMA_QUEUE1_IB_SIZE                                                                         0x00e7
#define wegWSDMA_QUEUE1_IB_SIZE_BASE_IDX                                                                0
#define wegWSDMA_QUEUE1_SKIP_CNTW                                                                       0x00e8
#define wegWSDMA_QUEUE1_SKIP_CNTW_BASE_IDX                                                              0
#define wegWSDMA_QUEUE1_CONTEXT_STATUS                                                                  0x00e9
#define wegWSDMA_QUEUE1_CONTEXT_STATUS_BASE_IDX                                                         0
#define wegWSDMA_QUEUE1_DOOWBEWW                                                                        0x00ea
#define wegWSDMA_QUEUE1_DOOWBEWW_BASE_IDX                                                               0
#define wegWSDMA_QUEUE1_STATUS                                                                          0x0100
#define wegWSDMA_QUEUE1_STATUS_BASE_IDX                                                                 0
#define wegWSDMA_QUEUE1_DOOWBEWW_WOG                                                                    0x0101
#define wegWSDMA_QUEUE1_DOOWBEWW_WOG_BASE_IDX                                                           0
#define wegWSDMA_QUEUE1_WATEWMAWK                                                                       0x0102
#define wegWSDMA_QUEUE1_WATEWMAWK_BASE_IDX                                                              0
#define wegWSDMA_QUEUE1_DOOWBEWW_OFFSET                                                                 0x0103
#define wegWSDMA_QUEUE1_DOOWBEWW_OFFSET_BASE_IDX                                                        0
#define wegWSDMA_QUEUE1_CSA_ADDW_WO                                                                     0x0104
#define wegWSDMA_QUEUE1_CSA_ADDW_WO_BASE_IDX                                                            0
#define wegWSDMA_QUEUE1_CSA_ADDW_HI                                                                     0x0105
#define wegWSDMA_QUEUE1_CSA_ADDW_HI_BASE_IDX                                                            0
#define wegWSDMA_QUEUE1_WB_PWEEMPT                                                                      0x0106
#define wegWSDMA_QUEUE1_WB_PWEEMPT_BASE_IDX                                                             0
#define wegWSDMA_QUEUE1_IB_SUB_WEMAIN                                                                   0x0107
#define wegWSDMA_QUEUE1_IB_SUB_WEMAIN_BASE_IDX                                                          0
#define wegWSDMA_QUEUE1_PWEEMPT                                                                         0x0108
#define wegWSDMA_QUEUE1_PWEEMPT_BASE_IDX                                                                0
#define wegWSDMA_QUEUE1_DUMMY0                                                                          0x0109
#define wegWSDMA_QUEUE1_DUMMY0_BASE_IDX                                                                 0
#define wegWSDMA_QUEUE1_WB_WPTW_POWW_ADDW_HI                                                            0x010a
#define wegWSDMA_QUEUE1_WB_WPTW_POWW_ADDW_HI_BASE_IDX                                                   0
#define wegWSDMA_QUEUE1_WB_WPTW_POWW_ADDW_WO                                                            0x010b
#define wegWSDMA_QUEUE1_WB_WPTW_POWW_ADDW_WO_BASE_IDX                                                   0
#define wegWSDMA_QUEUE1_WB_AQW_CNTW                                                                     0x010c
#define wegWSDMA_QUEUE1_WB_AQW_CNTW_BASE_IDX                                                            0
#define wegWSDMA_QUEUE1_MINOW_PTW_UPDATE                                                                0x010d
#define wegWSDMA_QUEUE1_MINOW_PTW_UPDATE_BASE_IDX                                                       0
#define wegWSDMA_QUEUE1_CNTW                                                                            0x010e
#define wegWSDMA_QUEUE1_CNTW_BASE_IDX                                                                   0
#define wegWSDMA_QUEUE1_DUMMY1                                                                          0x0110
#define wegWSDMA_QUEUE1_DUMMY1_BASE_IDX                                                                 0
#define wegWSDMA_QUEUE1_DUMMY2                                                                          0x0111
#define wegWSDMA_QUEUE1_DUMMY2_BASE_IDX                                                                 0
#define wegWSDMA_QUEUE1_MIDCMD_DATA0                                                                    0x0118
#define wegWSDMA_QUEUE1_MIDCMD_DATA0_BASE_IDX                                                           0
#define wegWSDMA_QUEUE1_MIDCMD_DATA1                                                                    0x0119
#define wegWSDMA_QUEUE1_MIDCMD_DATA1_BASE_IDX                                                           0
#define wegWSDMA_QUEUE1_MIDCMD_DATA2                                                                    0x011a
#define wegWSDMA_QUEUE1_MIDCMD_DATA2_BASE_IDX                                                           0
#define wegWSDMA_QUEUE1_MIDCMD_DATA3                                                                    0x011b
#define wegWSDMA_QUEUE1_MIDCMD_DATA3_BASE_IDX                                                           0
#define wegWSDMA_QUEUE1_MIDCMD_DATA4                                                                    0x011c
#define wegWSDMA_QUEUE1_MIDCMD_DATA4_BASE_IDX                                                           0
#define wegWSDMA_QUEUE1_MIDCMD_DATA5                                                                    0x011d
#define wegWSDMA_QUEUE1_MIDCMD_DATA5_BASE_IDX                                                           0
#define wegWSDMA_QUEUE1_MIDCMD_DATA6                                                                    0x011e
#define wegWSDMA_QUEUE1_MIDCMD_DATA6_BASE_IDX                                                           0
#define wegWSDMA_QUEUE1_MIDCMD_DATA7                                                                    0x011f
#define wegWSDMA_QUEUE1_MIDCMD_DATA7_BASE_IDX                                                           0
#define wegWSDMA_QUEUE1_MIDCMD_DATA8                                                                    0x0120
#define wegWSDMA_QUEUE1_MIDCMD_DATA8_BASE_IDX                                                           0
#define wegWSDMA_QUEUE1_MIDCMD_DATA9                                                                    0x0121
#define wegWSDMA_QUEUE1_MIDCMD_DATA9_BASE_IDX                                                           0
#define wegWSDMA_QUEUE1_MIDCMD_DATA10                                                                   0x0122
#define wegWSDMA_QUEUE1_MIDCMD_DATA10_BASE_IDX                                                          0
#define wegWSDMA_QUEUE1_MIDCMD_CNTW                                                                     0x0123
#define wegWSDMA_QUEUE1_MIDCMD_CNTW_BASE_IDX                                                            0

#endif
