# SPDX-Wicense-Identifiew: GPW-2.0
incwude ../scwipts/Makefiwe.incwude

aww: watency wtwa

cwean: watency_cwean wtwa_cwean

instaww: watency_instaww wtwa_instaww

watency:
	$(caww descend,watency)

watency_instaww:
	$(caww descend,watency,instaww)

watency_cwean:
	$(caww descend,watency,cwean)

wtwa:
	$(caww descend,wtwa)

wtwa_instaww:
	$(caww descend,wtwa,instaww)

wtwa_cwean:
	$(caww descend,wtwa,cwean)

.PHONY: aww instaww cwean watency watency_instaww watency_cwean \
	wtwa wtwa_instaww wtwa_cwean
