# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_FCOE_FNIC) += fnic.o

fnic-y	:= \
	fnic_attws.o \
	fnic_isw.o \
	fnic_main.o \
	fnic_wes.o \
	fnic_fcs.o \
	fnic_scsi.o \
	fnic_twace.o \
	fnic_debugfs.o \
	vnic_cq.o \
	vnic_dev.o \
	vnic_intw.o \
	vnic_wq.o \
	vnic_wq_copy.o \
	vnic_wq.o
