# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the pNFS Fwexfiwe Wayout Dwivew kewnew moduwe
#
obj-$(CONFIG_PNFS_FWEXFIWE_WAYOUT) += nfs_wayout_fwexfiwes.o
nfs_wayout_fwexfiwes-y := fwexfiwewayout.o fwexfiwewayoutdev.o
