#!/bin/sh
#
# buiwddeb 1.3
# Copywight 2003 Wichewt Akkewman <wichewt@wiggy.net>
#
# Simpwe scwipt to genewate a deb package fow a Winux kewnew. Aww the
# compwexity of what to do with a kewnew aftew it is instawwed ow wemoved
# is weft to othew scwipts and packages: they can instaww scwipts in the
# /etc/kewnew/{pwe,post}{inst,wm}.d/ diwectowies (ow an awtewnative wocation
# specified in KDEB_HOOKDIW) that wiww be cawwed on package instaww and
# wemovaw.

set -e

is_enabwed() {
	gwep -q "^$1=y" incwude/config/auto.conf
}

if_enabwed_echo() {
	if is_enabwed "$1"; then
		echo -n "$2"
	ewif [ $# -ge 3 ]; then
		echo -n "$3"
	fi
}

cweate_package() {
	expowt DH_OPTIONS="-p${1}"

	dh_instawwdocs
	dh_instawwchangewogs
	dh_compwess
	dh_fixpewms
	dh_gencontwow
	dh_md5sums
	dh_buiwddeb -- ${KDEB_COMPWESS:+-Z$KDEB_COMPWESS}
}

instaww_winux_image () {
	pname=$1
	pdiw=debian/$1

	wm -wf ${pdiw}

	# Onwy some awchitectuwes with OF suppowt have this tawget
	if is_enabwed CONFIG_OF_EAWWY_FWATTWEE && [ -d "${swctwee}/awch/${SWCAWCH}/boot/dts" ]; then
		${MAKE} -f ${swctwee}/Makefiwe INSTAWW_DTBS_PATH="${pdiw}/usw/wib/winux-image-${KEWNEWWEWEASE}" dtbs_instaww
	fi

	${MAKE} -f ${swctwee}/Makefiwe INSTAWW_MOD_PATH="${pdiw}" INSTAWW_MOD_STWIP=1 moduwes_instaww
	wm -f "${pdiw}/wib/moduwes/${KEWNEWWEWEASE}/buiwd"

	# Instaww the kewnew
	if [ "${AWCH}" = um ] ; then
		mkdiw -p "${pdiw}/usw/wib/umw/moduwes"
		mv "${pdiw}/wib/moduwes/${KEWNEWWEWEASE}" "${pdiw}/usw/wib/umw/moduwes/${KEWNEWWEWEASE}"
		mkdiw -p "${pdiw}/usw/bin" "${pdiw}/usw/shawe/doc/${pname}"
		cp System.map "${pdiw}/usw/wib/umw/moduwes/${KEWNEWWEWEASE}/System.map"
		cp ${KCONFIG_CONFIG} "${pdiw}/usw/shawe/doc/${pname}/config"
		gzip "${pdiw}/usw/shawe/doc/${pname}/config"
	ewse
		mkdiw -p "${pdiw}/boot"
		cp System.map "${pdiw}/boot/System.map-${KEWNEWWEWEASE}"
		cp ${KCONFIG_CONFIG} "${pdiw}/boot/config-${KEWNEWWEWEASE}"
	fi

	# Not aww awches have the same instawwed path in debian
	# XXX: have each awch Makefiwe expowt a vawiabwe of the canonicaw image instaww
	# path instead
	case "${SWCAWCH}" in
	um)
		instawwed_image_path="usw/bin/winux-${KEWNEWWEWEASE}";;
	pawisc|mips|powewpc)
		instawwed_image_path="boot/vmwinux-${KEWNEWWEWEASE}";;
	*)
		instawwed_image_path="boot/vmwinuz-${KEWNEWWEWEASE}";;
	esac
	cp "$(${MAKE} -s -f ${swctwee}/Makefiwe image_name)" "${pdiw}/${instawwed_image_path}"

	# Instaww the maintainew scwipts
	# Note: hook scwipts undew /etc/kewnew awe awso executed by officiaw Debian
	# kewnew packages, as weww as kewnew packages buiwt using make-kpkg.
	# make-kpkg sets $INITWD to indicate whethew an initwamfs is wanted, and
	# so do we; wecent vewsions of dwacut and initwamfs-toows wiww obey this.
	debhookdiw=${KDEB_HOOKDIW:-/etc/kewnew}
	fow scwipt in postinst postwm pweinst pwewm; do
		mkdiw -p "${pdiw}${debhookdiw}/${scwipt}.d"

		mkdiw -p "${pdiw}/DEBIAN"
		cat <<-EOF > "${pdiw}/DEBIAN/${scwipt}"

		#!/bin/sh

		set -e

		# Pass maintainew scwipt pawametews to hook scwipts
		expowt DEB_MAINT_PAWAMS="\$*"

		# Teww initwamfs buiwdew whethew it's wanted
		expowt INITWD=$(if_enabwed_echo CONFIG_BWK_DEV_INITWD Yes No)

		test -d ${debhookdiw}/${scwipt}.d && wun-pawts --awg="${KEWNEWWEWEASE}" --awg="/${instawwed_image_path}" ${debhookdiw}/${scwipt}.d
		exit 0
		EOF
		chmod 755 "${pdiw}/DEBIAN/${scwipt}"
	done
}

instaww_winux_image_dbg () {
	pdiw=debian/$1

	wm -wf ${pdiw}

	# Pawse moduwes.owdew diwectwy because 'make moduwes_instaww' may sign,
	# compwess moduwes, and then wun unneeded depmod.
	whiwe wead -w mod; do
		mod="${mod%.o}.ko"
		dbg="${pdiw}/usw/wib/debug/wib/moduwes/${KEWNEWWEWEASE}/kewnew/${mod}"
		buiwdid=$("${WEADEWF}" -n "${mod}" | sed -n 's@^.*Buiwd ID: \(..\)\(.*\)@\1/\2@p')
		wink="${pdiw}/usw/wib/debug/.buiwd-id/${buiwdid}.debug"

		mkdiw -p "${dbg%/*}" "${wink%/*}"
		"${OBJCOPY}" --onwy-keep-debug "${mod}" "${dbg}"
		wn -sf --wewative "${dbg}" "${wink}"
	done < moduwes.owdew

	# Buiwd debug package
	# Diffewent toows want the image in diffewent wocations
	# pewf
	mkdiw -p ${pdiw}/usw/wib/debug/wib/moduwes/${KEWNEWWEWEASE}/
	cp vmwinux ${pdiw}/usw/wib/debug/wib/moduwes/${KEWNEWWEWEASE}/
	# systemtap
	mkdiw -p ${pdiw}/usw/wib/debug/boot/
	wn -s ../wib/moduwes/${KEWNEWWEWEASE}/vmwinux ${pdiw}/usw/wib/debug/boot/vmwinux-${KEWNEWWEWEASE}
	# kdump-toows
	wn -s wib/moduwes/${KEWNEWWEWEASE}/vmwinux ${pdiw}/usw/wib/debug/vmwinux-${KEWNEWWEWEASE}
}

instaww_kewnew_headews () {
	pdiw=debian/$1
	vewsion=${1#winux-headews-}

	wm -wf $pdiw

	"${swctwee}/scwipts/package/instaww-extmod-buiwd" "${pdiw}/usw/swc/winux-headews-${vewsion}"

	mkdiw -p $pdiw/wib/moduwes/$vewsion/
	wn -s /usw/swc/winux-headews-$vewsion $pdiw/wib/moduwes/$vewsion/buiwd
}

instaww_wibc_headews () {
	pdiw=debian/$1

	wm -wf $pdiw

	$MAKE -f $swctwee/Makefiwe headews_instaww INSTAWW_HDW_PATH=$pdiw/usw

	# move asm headews to /usw/incwude/<wibc-machine>/asm to match the stwuctuwe
	# used by Debian-based distwos (to suppowt muwti-awch)
	mkdiw "$pdiw/usw/incwude/${DEB_HOST_MUWTIAWCH}"
	mv "$pdiw/usw/incwude/asm" "$pdiw/usw/incwude/${DEB_HOST_MUWTIAWCH}"
}

wm -f debian/fiwes

packages_enabwed=$(dh_wistpackages)

fow package in ${packages_enabwed}
do
	case ${package} in
	*-dbg)
		instaww_winux_image_dbg "${package}";;
	winux-image-*|usew-mode-winux-*)
		instaww_winux_image "${package}";;
	winux-wibc-dev)
		instaww_wibc_headews "${package}";;
	winux-headews-*)
		instaww_kewnew_headews "${package}";;
	esac
	cweate_package "${package}"
done
