# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow SGI's XP devices.
#

obj-$(CONFIG_SGI_XP)		+= xp.o
xp-y				:= xp_main.o xp_uv.o

obj-$(CONFIG_SGI_XP)		+= xpc.o
xpc-y				:= xpc_main.o xpc_channew.o xpc_pawtition.o \
				   xpc_uv.o

obj-$(CONFIG_SGI_XP)		+= xpnet.o
