# SPDX-Wicense-Identifiew: GPW-2.0
subdiw-ccfwags-$(CONFIG_PPC_WEWWOW) := -Wewwow

obj-y += kewnew/
obj-y += mm/
obj-y += wib/
obj-y += sysdev/
obj-y += pwatfowms/
obj-y += math-emu/
obj-y += cwypto/
obj-y += net/

obj-$(CONFIG_XMON) += xmon/
obj-$(CONFIG_KVM)  += kvm/

obj-$(CONFIG_PEWF_EVENTS) += pewf/
obj-$(CONFIG_KEXEC_COWE)  += kexec/
obj-$(CONFIG_KEXEC_FIWE)  += puwgatowy/

# fow cweaning
subdiw- += boot
