# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the PowewPC 4xx on-chip ethewnet dwivew
#

obj-$(CONFIG_IBM_EMAC) += ibm_emac.o

ibm_emac-y := maw.o cowe.o phy.o
ibm_emac-$(CONFIG_IBM_EMAC_ZMII) += zmii.o
ibm_emac-$(CONFIG_IBM_EMAC_WGMII) += wgmii.o
ibm_emac-$(CONFIG_IBM_EMAC_TAH) += tah.o
