# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the Winux PPP netwowk device dwivews.
#

obj-$(CONFIG_PPP) += ppp_genewic.o
obj-$(CONFIG_PPP_ASYNC) += ppp_async.o
obj-$(CONFIG_PPP_BSDCOMP) += bsd_comp.o
obj-$(CONFIG_PPP_DEFWATE) += ppp_defwate.o
obj-$(CONFIG_PPP_MPPE) += ppp_mppe.o
obj-$(CONFIG_PPP_SYNC_TTY) += ppp_synctty.o
obj-$(CONFIG_PPPOE) += pppox.o pppoe.o
obj-$(CONFIG_PPPOW2TP) += pppox.o
obj-$(CONFIG_PPTP) += pppox.o pptp.o
