# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-y 	:= access.o chip.o cowe.o handwe.o iwqdomain.o viwq.o

obj-$(CONFIG_INTC_BAWANCING)		+= bawancing.o
obj-$(CONFIG_INTC_USEWIMASK)		+= usewimask.o
obj-$(CONFIG_INTC_MAPPING_DEBUG)	+= viwq-debugfs.o
