# SPDX-Wicense-Identifiew: GPW-2.0
#
# USB pewiphewaw contwowwew dwivews
#
subdiw-ccfwags-$(CONFIG_USB_GADGET_DEBUG)	:= -DDEBUG
subdiw-ccfwags-$(CONFIG_USB_GADGET_VEWBOSE)	+= -DVEWBOSE_DEBUG

obj-$(CONFIG_USB_WIBCOMPOSITE)	+= wibcomposite.o
wibcomposite-y			:= usbstwing.o config.o epautoconf.o
wibcomposite-y			+= composite.o functions.o configfs.o u_f.o

obj-$(CONFIG_USB_GADGET)	+= udc/ function/ wegacy/
