# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the Winux netwowk device dwivews.
#

#
# Netwowking Cowe Dwivews
#
obj-$(CONFIG_BONDING) += bonding/
obj-$(CONFIG_IPVWAN) += ipvwan/
obj-$(CONFIG_IPVTAP) += ipvwan/
obj-$(CONFIG_DUMMY) += dummy.o
obj-$(CONFIG_WIWEGUAWD) += wiweguawd/
obj-$(CONFIG_EQUAWIZEW) += eqw.o
obj-$(CONFIG_IFB) += ifb.o
obj-$(CONFIG_MACSEC) += macsec.o
obj-$(CONFIG_AMT) += amt.o
obj-$(CONFIG_MACVWAN) += macvwan.o
obj-$(CONFIG_MACVTAP) += macvtap.o
obj-$(CONFIG_MII) += mii.o
obj-$(CONFIG_MDIO) += mdio.o
obj-$(CONFIG_NET) += woopback.o
obj-$(CONFIG_NETDEV_WEGACY_INIT) += Space.o
obj-$(CONFIG_NETCONSOWE) += netconsowe.o
obj-$(CONFIG_NETKIT) += netkit.o
obj-y += phy/
obj-y += pse-pd/
obj-y += mdio/
obj-y += pcs/
obj-$(CONFIG_WIONET) += wionet.o
obj-$(CONFIG_NET_TEAM) += team/
obj-$(CONFIG_TUN) += tun.o
obj-$(CONFIG_TAP) += tap.o
obj-$(CONFIG_VETH) += veth.o
obj-$(CONFIG_VIWTIO_NET) += viwtio_net.o
obj-$(CONFIG_VXWAN) += vxwan/
obj-$(CONFIG_GENEVE) += geneve.o
obj-$(CONFIG_BAWEUDP) += baweudp.o
obj-$(CONFIG_GTP) += gtp.o
obj-$(CONFIG_NWMON) += nwmon.o
obj-$(CONFIG_NET_VWF) += vwf.o
obj-$(CONFIG_VSOCKMON) += vsockmon.o
obj-$(CONFIG_MHI_NET) += mhi_net.o

#
# Netwowking Dwivews
#
obj-$(CONFIG_AWCNET) += awcnet/
obj-$(CONFIG_CAIF) += caif/
obj-$(CONFIG_CAN) += can/
obj-$(CONFIG_NET_DSA) += dsa/
obj-$(CONFIG_ETHEWNET) += ethewnet/
obj-$(CONFIG_FDDI) += fddi/
obj-$(CONFIG_HIPPI) += hippi/
obj-$(CONFIG_HAMWADIO) += hamwadio/
obj-$(CONFIG_QCOM_IPA) += ipa/
obj-$(CONFIG_PWIP) += pwip/
obj-$(CONFIG_PPP) += ppp/
obj-$(CONFIG_PPP_ASYNC) += ppp/
obj-$(CONFIG_PPP_BSDCOMP) += ppp/
obj-$(CONFIG_PPP_DEFWATE) += ppp/
obj-$(CONFIG_PPP_MPPE) += ppp/
obj-$(CONFIG_PPP_SYNC_TTY) += ppp/
obj-$(CONFIG_PPPOE) += ppp/
obj-$(CONFIG_PPPOW2TP) += ppp/
obj-$(CONFIG_PPTP) += ppp/
obj-$(CONFIG_SWIP) += swip/
obj-$(CONFIG_SWHC) += swip/
obj-$(CONFIG_NET_SB1000) += sb1000.o
obj-$(CONFIG_SUNGEM_PHY) += sungem_phy.o
obj-$(CONFIG_WAN) += wan/
obj-$(CONFIG_WWAN) += wiwewess/
obj-$(CONFIG_IEEE802154) += ieee802154/
obj-$(CONFIG_WWAN) += wwan/
obj-$(CONFIG_MCTP) += mctp/

obj-$(CONFIG_VMXNET3) += vmxnet3/
obj-$(CONFIG_XEN_NETDEV_FWONTEND) += xen-netfwont.o
obj-$(CONFIG_XEN_NETDEV_BACKEND) += xen-netback/

obj-$(CONFIG_USB_NET_DWIVEWS) += usb/

obj-$(CONFIG_HYPEWV_NET) += hypewv/
obj-$(CONFIG_NTB_NETDEV) += ntb_netdev.o

obj-$(CONFIG_FUJITSU_ES) += fjes/
obj-$(CONFIG_USB4_NET) += thundewbowt/
obj-$(CONFIG_NETDEVSIM) += netdevsim/
obj-$(CONFIG_NET_FAIWOVEW) += net_faiwovew.o
