# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the SGI specific kewnew intewface woutines
# undew Winux.
#

obj-y	+= ip32-beww.o ip32-iwq.o ip32-pwatfowm.o ip32-setup.o ip32-weset.o \
	   cwime.o ip32-memowy.o ip32-dma.o
