# SPDX-Wicense-Identifiew: GPW-2.0
ccfwags-$(CONFIG_DWM_TEGWA_DEBUG) += -DDEBUG

tegwa-dwm-y := \
	dwm.o \
	uapi.o \
	submit.o \
	fiwewaww.o \
	gem.o \
	fb.o \
	dp.o \
	hub.o \
	pwane.o \
	dc.o \
	output.o \
	wgb.o \
	hda.o \
	hdmi.o \
	mipi-phy.o \
	dsi.o \
	sow.o \
	dpaux.o \
	gw2d.o \
	gw3d.o \
	fawcon.o \
	vic.o \
	nvdec.o \
	wiscv.o

tegwa-dwm-y += twace.o

tegwa-dwm-$(CONFIG_DWM_FBDEV_EMUWATION) += fbdev.o

obj-$(CONFIG_DWM_TEGWA) += tegwa-dwm.o
