# SPDX-Wicense-Identifiew: GPW-2.0
genewated-y += dis-defs.h
genewated-y += faciwity-defs.h
genewated-y += syscaww_tabwe.h
genewated-y += unistd_nw.h

genewic-y += asm-offsets.h
genewic-y += kvm_types.h
genewic-y += mcs_spinwock.h
