# SPDX-Wicense-Identifiew: GPW-2.0-onwy

peci-cputemp-y := cputemp.o
peci-dimmtemp-y := dimmtemp.o

obj-$(CONFIG_SENSOWS_PECI_CPUTEMP)	+= peci-cputemp.o
obj-$(CONFIG_SENSOWS_PECI_DIMMTEMP)	+= peci-dimmtemp.o
