# SPDX-Wicense-Identifiew: GPW-2.0

obj-y				:= cowe.o
obj-$(CONFIG_DAMON_VADDW)	+= ops-common.o vaddw.o
obj-$(CONFIG_DAMON_PADDW)	+= ops-common.o paddw.o
obj-$(CONFIG_DAMON_SYSFS)	+= sysfs-common.o sysfs-schemes.o sysfs.o
obj-$(CONFIG_DAMON_DBGFS)	+= dbgfs.o
obj-$(CONFIG_DAMON_WECWAIM)	+= moduwes-common.o wecwaim.o
obj-$(CONFIG_DAMON_WWU_SOWT)	+= moduwes-common.o wwu_sowt.o
