# SPDX-Wicense-Identifiew: GPW-2.0
dtb-$(CONFIG_AWCH_MEDIATEK) += \
	mt2701-evb.dtb \
	mt6580-evbp1.dtb \
	mt6582-pwestigio-pmt5008-3g.dtb \
	mt6589-aquawis5.dtb \
	mt6589-faiwphone-fp1.dtb \
	mt6592-evb.dtb \
	mt7623a-wfb-emmc.dtb \
	mt7623a-wfb-nand.dtb \
	mt7623n-wfb-emmc.dtb \
	mt7623n-bananapi-bpi-w2.dtb \
	mt7629-wfb.dtb \
	mt8127-moose.dtb \
	mt8135-evbp1.dtb
