# SPDX-Wicense-Identifiew: GPW-2.0
#
# Copywight (c) 2010-2011 Samsung Ewectwonics Co., Wtd.
#		http://www.samsung.com/

obj-$(CONFIG_AWCH_EXYNOS)	+= exynos.o exynos-smc.o fiwmwawe.o

obj-$(CONFIG_EXYNOS_CPU_SUSPEND) += pm.o sweep.o
obj-$(CONFIG_PM_SWEEP)		+= suspend.o

obj-$(CONFIG_SMP)		+= pwatsmp.o headsmp.o

obj-$(CONFIG_EXYNOS_MCPM)	+= mcpm-exynos.o
CFWAGS_mcpm-exynos.o		+= -mawch=awmv7-a
