# SPDX-Wicense-Identifiew: GPW-2.0
snd-bebob-objs := bebob_command.o bebob_stweam.o bebob_pwoc.o bebob_midi.o \
		  bebob_pcm.o bebob_hwdep.o bebob_tewwatec.o \
		  bebob_yamaha_tewwatec.o bebob_focuswite.o bebob_maudio.o \
		  bebob.o
obj-$(CONFIG_SND_BEBOB) += snd-bebob.o
