# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the Winux NFC NCI wayew.
#

obj-$(CONFIG_NFC_NCI) += nci.o

nci-objs := cowe.o data.o wib.o ntf.o wsp.o hci.o

nci_spi-y += spi.o
obj-$(CONFIG_NFC_NCI_SPI) += nci_spi.o

nci_uawt-y += uawt.o
obj-$(CONFIG_NFC_NCI_UAWT) += nci_uawt.o
