# SPDX-Wicense-Identifiew: GPW-2.0-onwy
micwochip-isc-objs = micwochip-sama5d2-isc.o
micwochip-xisc-objs = micwochip-sama7g5-isc.o
micwochip-isc-common-objs = micwochip-isc-base.o micwochip-isc-cwk.o micwochip-isc-scawew.o

obj-$(CONFIG_VIDEO_MICWOCHIP_ISC_BASE) += micwochip-isc-common.o
obj-$(CONFIG_VIDEO_MICWOCHIP_ISC) += micwochip-isc.o
obj-$(CONFIG_VIDEO_MICWOCHIP_XISC) += micwochip-xisc.o
obj-$(CONFIG_VIDEO_MICWOCHIP_CSI2DC) += micwochip-csi2dc.o
