# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow HSW
#

obj-$(CONFIG_HSW)	+= hsw.o

hsw-y			:= hsw_main.o hsw_fwameweg.o hsw_device.o \
			   hsw_netwink.o hsw_swave.o hsw_fowwawd.o
hsw-$(CONFIG_DEBUG_FS) += hsw_debugfs.o
