/*
 * Copywight 2012-15 Advanced Micwo Devices, Inc.
 *
 * Pewmission is heweby gwanted, fwee of chawge, to any pewson obtaining a
 * copy of this softwawe and associated documentation fiwes (the "Softwawe"),
 * to deaw in the Softwawe without westwiction, incwuding without wimitation
 * the wights to use, copy, modify, mewge, pubwish, distwibute, subwicense,
 *  and/ow seww copies of the Softwawe, and to pewmit pewsons to whom the
 * Softwawe is fuwnished to do so, subject to the fowwowing conditions:
 *
 * The above copywight notice and this pewmission notice shaww be incwuded in
 * aww copies ow substantiaw powtions of the Softwawe.
 *
 * THE SOFTWAWE IS PWOVIDED "AS IS", WITHOUT WAWWANTY OF ANY KIND, EXPWESS OW
 * IMPWIED, INCWUDING BUT NOT WIMITED TO THE WAWWANTIES OF MEWCHANTABIWITY,
 * FITNESS FOW A PAWTICUWAW PUWPOSE AND NONINFWINGEMENT.  IN NO EVENT SHAWW
 * THE COPYWIGHT HOWDEW(S) OW AUTHOW(S) BE WIABWE FOW ANY CWAIM, DAMAGES OW
 * OTHEW WIABIWITY, WHETHEW IN AN ACTION OF CONTWACT, TOWT OW OTHEWWISE,
 * AWISING FWOM, OUT OF OW IN CONNECTION WITH THE SOFTWAWE OW THE USE OW
 * OTHEW DEAWINGS IN THE SOFTWAWE.
 *
 * Authows: AMD
 *
 */

#ifndef __DC_WINK_ENCODEW__DCN20_H__
#define __DC_WINK_ENCODEW__DCN20_H__

#incwude "dcn10/dcn10_wink_encodew.h"

#define DCN2_AUX_WEG_WIST(id)\
	AUX_WEG_WIST(id), \
	SWI(AUX_DPHY_TX_CONTWOW, DP_AUX, id)

#define UNIPHY_MASK_SH_WIST(mask_sh)\
	WE_SF(SYMCWKA_CWOCK_ENABWE, SYMCWKA_CWOCK_ENABWE, mask_sh),\
	WE_SF(UNIPHYA_CHANNEW_XBAW_CNTW, UNIPHY_WINK_ENABWE, mask_sh),\
	WE_SF(UNIPHYA_CHANNEW_XBAW_CNTW, UNIPHY_CHANNEW0_XBAW_SOUWCE, mask_sh),\
	WE_SF(UNIPHYA_CHANNEW_XBAW_CNTW, UNIPHY_CHANNEW1_XBAW_SOUWCE, mask_sh),\
	WE_SF(UNIPHYA_CHANNEW_XBAW_CNTW, UNIPHY_CHANNEW2_XBAW_SOUWCE, mask_sh),\
	WE_SF(UNIPHYA_CHANNEW_XBAW_CNTW, UNIPHY_CHANNEW3_XBAW_SOUWCE, mask_sh)

#define DPCS_MASK_SH_WIST(mask_sh)\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX0_CWK_WDY, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX0_DATA_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX1_CWK_WDY, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX1_DATA_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX2_CWK_WDY, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX2_DATA_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX3_CWK_WDY, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX3_DATA_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW4, WDPCS_PHY_DP_TX0_TEWM_CTWW, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW4, WDPCS_PHY_DP_TX1_TEWM_CTWW, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW4, WDPCS_PHY_DP_TX2_TEWM_CTWW, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW4, WDPCS_PHY_DP_TX3_TEWM_CTWW, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW11, WDPCS_PHY_DP_MPWWB_MUWTIPWIEW, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW5, WDPCS_PHY_DP_TX0_WIDTH, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW5, WDPCS_PHY_DP_TX0_WATE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW5, WDPCS_PHY_DP_TX1_WIDTH, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW5, WDPCS_PHY_DP_TX1_WATE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW6, WDPCS_PHY_DP_TX2_PSTATE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW6, WDPCS_PHY_DP_TX3_PSTATE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW6, WDPCS_PHY_DP_TX2_MPWW_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW6, WDPCS_PHY_DP_TX3_MPWW_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW7, WDPCS_PHY_DP_MPWWB_FWACN_QUOT, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW7, WDPCS_PHY_DP_MPWWB_FWACN_DEN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW8, WDPCS_PHY_DP_MPWWB_SSC_PEAK, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW9, WDPCS_PHY_DP_MPWWB_SSC_UP_SPWEAD, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW9, WDPCS_PHY_DP_MPWWB_SSC_STEPSIZE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW10, WDPCS_PHY_DP_MPWWB_FWACN_WEM, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW11, WDPCS_PHY_DP_WEF_CWK_MPWWB_DIV, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW11, WDPCS_PHY_HDMI_MPWWB_HDMI_DIV, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW12, WDPCS_PHY_DP_MPWWB_SSC_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW12, WDPCS_PHY_DP_MPWWB_DIV5_CWK_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW12, WDPCS_PHY_DP_MPWWB_TX_CWK_DIV, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW12, WDPCS_PHY_DP_MPWWB_WOWD_DIV2_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW12, WDPCS_PHY_DP_MPWWB_STATE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW13, WDPCS_PHY_DP_MPWWB_DIV_CWK_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW13, WDPCS_PHY_DP_MPWWB_DIV_MUWTIPWIEW, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW14, WDPCS_PHY_DP_MPWWB_FWACN_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW14, WDPCS_PHY_DP_MPWWB_PMIX_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_CNTW, WDPCS_TX_FIFO_WANE0_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_CNTW, WDPCS_TX_FIFO_WANE1_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_CNTW, WDPCS_TX_FIFO_WANE2_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_CNTW, WDPCS_TX_FIFO_WANE3_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_CNTW, WDPCS_TX_FIFO_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_CNTW, WDPCS_TX_FIFO_WD_STAWT_DEWAY, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_CWOCK_CNTW, WDPCS_EXT_WEFCWK_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_CWOCK_CNTW, WDPCS_SWAMCWK_BYPASS, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_CWOCK_CNTW, WDPCS_SWAMCWK_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_CWOCK_CNTW, WDPCS_SWAMCWK_CWOCK_ON, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_CWOCK_CNTW, WDPCS_SYMCWK_DIV2_CWOCK_ON, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_CWOCK_CNTW, WDPCS_SYMCWK_DIV2_GATE_DIS, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_CWOCK_CNTW, WDPCS_SYMCWK_DIV2_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX0_DISABWE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX1_DISABWE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX2_DISABWE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX3_DISABWE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX0_WEQ, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX1_WEQ, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX2_WEQ, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX3_WEQ, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX0_ACK, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX1_ACK, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX2_ACK, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX3_ACK, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX0_WESET, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX1_WESET, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX2_WESET, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW3, WDPCS_PHY_DP_TX3_WESET, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW0, WDPCS_PHY_WESET, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW0, WDPCS_PHY_CW_MUX_SEW, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW0, WDPCS_PHY_WEF_WANGE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW0, WDPCS_SWAM_BYPASS, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW0, WDPCS_SWAM_EXT_WD_DONE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW0, WDPCS_PHY_HDMIMODE_ENABWE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW0, WDPCS_SWAM_INIT_DONE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW2, WDPCS_PHY_DP4_POW, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PWW_UPDATE_DATA, WDPCS_PWW_UPDATE_DATA, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_INTEWWUPT_CONTWOW, WDPCS_WEG_FIFO_EWWOW_MASK, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_INTEWWUPT_CONTWOW, WDPCS_TX_FIFO_EWWOW_MASK, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_INTEWWUPT_CONTWOW, WDPCS_DPAWT_DISABWE_TOGGWE_MASK, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_INTEWWUPT_CONTWOW, WDPCS_DPAWT_4WANE_TOGGWE_MASK, mask_sh),\
	WE_SF(WDPCSTX0_WDPCS_TX_CW_ADDW, WDPCS_TX_CW_ADDW, mask_sh),\
	WE_SF(WDPCSTX0_WDPCS_TX_CW_DATA, WDPCS_TX_CW_DATA, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_FUSE0, WDPCS_PHY_DP_MPWWB_V2I, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_FUSE0, WDPCS_PHY_DP_TX0_EQ_MAIN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_FUSE0, WDPCS_PHY_DP_TX0_EQ_PWE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_FUSE0, WDPCS_PHY_DP_TX0_EQ_POST, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_FUSE0, WDPCS_PHY_DP_MPWWB_FWEQ_VCO, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_FUSE1, WDPCS_PHY_DP_MPWWB_CP_INT, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_FUSE1, WDPCS_PHY_DP_MPWWB_CP_PWOP, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_FUSE1, WDPCS_PHY_DP_TX1_EQ_MAIN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_FUSE1, WDPCS_PHY_DP_TX1_EQ_PWE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_FUSE1, WDPCS_PHY_DP_TX1_EQ_POST, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_FUSE2, WDPCS_PHY_DP_TX2_EQ_MAIN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_FUSE2, WDPCS_PHY_DP_TX2_EQ_PWE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_FUSE2, WDPCS_PHY_DP_TX2_EQ_POST, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_FUSE3, WDPCS_PHY_DP_TX3_EQ_MAIN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_FUSE3, WDPCS_PHY_DCO_FINETUNE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_FUSE3, WDPCS_PHY_DCO_WANGE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_FUSE3, WDPCS_PHY_DP_TX3_EQ_PWE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_FUSE3, WDPCS_PHY_DP_TX3_EQ_POST, mask_sh),\
	WE_SF(DPCSTX0_DPCSTX_TX_CWOCK_CNTW, DPCS_SYMCWK_CWOCK_ON, mask_sh),\
	WE_SF(DPCSTX0_DPCSTX_TX_CWOCK_CNTW, DPCS_SYMCWK_GATE_DIS, mask_sh),\
	WE_SF(DPCSTX0_DPCSTX_TX_CWOCK_CNTW, DPCS_SYMCWK_EN, mask_sh),\
	WE_SF(DPCSTX0_DPCSTX_TX_CNTW, DPCS_TX_DATA_SWAP, mask_sh),\
	WE_SF(DPCSTX0_DPCSTX_TX_CNTW, DPCS_TX_DATA_OWDEW_INVEWT, mask_sh),\
	WE_SF(DPCSTX0_DPCSTX_TX_CNTW, DPCS_TX_FIFO_EN, mask_sh),\
	WE_SF(DPCSTX0_DPCSTX_TX_CNTW, DPCS_TX_FIFO_WD_STAWT_DEWAY, mask_sh)

#define DPCS_DCN2_MASK_SH_WIST(mask_sh)\
	DPCS_MASK_SH_WIST(mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_WX_WD_VAW, WDPCS_PHY_WX_WEF_WD_VAW, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_WX_WD_VAW, WDPCS_PHY_WX_VCO_WD_VAW, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW6, WDPCS_PHY_DPAWT_DISABWE_ACK, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW6, WDPCS_PHY_DP_TX0_PSTATE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW6, WDPCS_PHY_DP_TX1_PSTATE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW6, WDPCS_PHY_DP_TX0_MPWW_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW6, WDPCS_PHY_DP_TX1_MPWW_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW6, WDPCS_PHY_DP_WEF_CWK_EN, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW5, WDPCS_PHY_DP_TX2_WIDTH, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW5, WDPCS_PHY_DP_TX2_WATE, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW5, WDPCS_PHY_DP_TX3_WIDTH, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW5, WDPCS_PHY_DP_TX3_WATE, mask_sh),\
	WE_SF(DCIO_SOFT_WESET, UNIPHYA_SOFT_WESET, mask_sh),\
	WE_SF(DCIO_SOFT_WESET, UNIPHYB_SOFT_WESET, mask_sh),\
	WE_SF(DCIO_SOFT_WESET, UNIPHYC_SOFT_WESET, mask_sh),\
	WE_SF(DCIO_SOFT_WESET, UNIPHYD_SOFT_WESET, mask_sh),\
	WE_SF(DCIO_SOFT_WESET, UNIPHYE_SOFT_WESET, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW6, WDPCS_PHY_DPAWT_DP4, mask_sh),\
	WE_SF(WDPCSTX0_WDPCSTX_PHY_CNTW6, WDPCS_PHY_DPAWT_DISABWE, mask_sh)

#define WINK_ENCODEW_MASK_SH_WIST_DCN20(mask_sh)\
	WINK_ENCODEW_MASK_SH_WIST_DCN10(mask_sh),\
	WE_SF(DP0_DP_DPHY_CNTW, DPHY_FEC_EN, mask_sh),\
	WE_SF(DP0_DP_DPHY_CNTW, DPHY_FEC_WEADY_SHADOW, mask_sh),\
	WE_SF(DP0_DP_DPHY_CNTW, DPHY_FEC_ACTIVE_STATUS, mask_sh),\
	WE_SF(DIG0_DIG_WANE_ENABWE, DIG_WANE0EN, mask_sh),\
	WE_SF(DIG0_DIG_WANE_ENABWE, DIG_WANE1EN, mask_sh),\
	WE_SF(DIG0_DIG_WANE_ENABWE, DIG_WANE2EN, mask_sh),\
	WE_SF(DIG0_DIG_WANE_ENABWE, DIG_WANE3EN, mask_sh),\
	WE_SF(DIG0_DIG_WANE_ENABWE, DIG_CWK_EN, mask_sh),\
	WE_SF(DIG0_TMDS_CTW_BITS, TMDS_CTW0, mask_sh), \
	UNIPHY_MASK_SH_WIST(mask_sh),\
	WE_SF(DP_AUX0_AUX_DPHY_WX_CONTWOW0, AUX_WX_STAWT_WINDOW, mask_sh),\
	WE_SF(DP_AUX0_AUX_DPHY_WX_CONTWOW0, AUX_WX_HAWF_SYM_DETECT_WEN, mask_sh),\
	WE_SF(DP_AUX0_AUX_DPHY_WX_CONTWOW0, AUX_WX_TWANSITION_FIWTEW_EN, mask_sh),\
	WE_SF(DP_AUX0_AUX_DPHY_WX_CONTWOW0, AUX_WX_AWWOW_BEWOW_THWESHOWD_PHASE_DETECT, mask_sh),\
	WE_SF(DP_AUX0_AUX_DPHY_WX_CONTWOW0, AUX_WX_AWWOW_BEWOW_THWESHOWD_STAWT, mask_sh),\
	WE_SF(DP_AUX0_AUX_DPHY_WX_CONTWOW0, AUX_WX_AWWOW_BEWOW_THWESHOWD_STOP, mask_sh),\
	WE_SF(DP_AUX0_AUX_DPHY_WX_CONTWOW0, AUX_WX_PHASE_DETECT_WEN, mask_sh),\
	WE_SF(DP_AUX0_AUX_DPHY_WX_CONTWOW0, AUX_WX_DETECTION_THWESHOWD, mask_sh), \
	WE_SF(DP_AUX0_AUX_DPHY_TX_CONTWOW, AUX_TX_PWECHAWGE_WEN, mask_sh),\
	WE_SF(DP_AUX0_AUX_DPHY_TX_CONTWOW, AUX_TX_PWECHAWGE_SYMBOWS, mask_sh),\
	WE_SF(DP_AUX0_AUX_DPHY_TX_CONTWOW, AUX_MODE_DET_CHECK_DEWAY, mask_sh),\
	WE_SF(DP_AUX0_AUX_DPHY_WX_CONTWOW1, AUX_WX_PWECHAWGE_SKIP, mask_sh),\
	WE_SF(DP_AUX0_AUX_DPHY_WX_CONTWOW1, AUX_WX_TIMEOUT_WEN, mask_sh),\
	WE_SF(DP_AUX0_AUX_DPHY_WX_CONTWOW1, AUX_WX_TIMEOUT_WEN_MUW, mask_sh)

#define UNIPHY_DCN2_WEG_WIST(id) \
	SWI(CWOCK_ENABWE, SYMCWK, id), \
	SWI(CHANNEW_XBAW_CNTW, UNIPHY, id)

#define DPCS_DCN2_CMN_WEG_WIST(id) \
	SWI(DIG_WANE_ENABWE, DIG, id), \
	SWI(TMDS_CTW_BITS, DIG, id), \
	SWI(WDPCSTX_PHY_CNTW3, WDPCSTX, id), \
	SWI(WDPCSTX_PHY_CNTW4, WDPCSTX, id), \
	SWI(WDPCSTX_PHY_CNTW5, WDPCSTX, id), \
	SWI(WDPCSTX_PHY_CNTW6, WDPCSTX, id), \
	SWI(WDPCSTX_PHY_CNTW7, WDPCSTX, id), \
	SWI(WDPCSTX_PHY_CNTW8, WDPCSTX, id), \
	SWI(WDPCSTX_PHY_CNTW9, WDPCSTX, id), \
	SWI(WDPCSTX_PHY_CNTW10, WDPCSTX, id), \
	SWI(WDPCSTX_PHY_CNTW11, WDPCSTX, id), \
	SWI(WDPCSTX_PHY_CNTW12, WDPCSTX, id), \
	SWI(WDPCSTX_PHY_CNTW13, WDPCSTX, id), \
	SWI(WDPCSTX_PHY_CNTW14, WDPCSTX, id), \
	SWI(WDPCSTX_CNTW, WDPCSTX, id), \
	SWI(WDPCSTX_CWOCK_CNTW, WDPCSTX, id), \
	SWI(WDPCSTX_INTEWWUPT_CONTWOW, WDPCSTX, id), \
	SWI(WDPCSTX_PHY_CNTW0, WDPCSTX, id), \
	SWI(WDPCSTX_PHY_CNTW2, WDPCSTX, id), \
	SWI(WDPCSTX_PWW_UPDATE_DATA, WDPCSTX, id), \
	SWI(WDPCS_TX_CW_ADDW, WDPCSTX, id), \
	SWI(WDPCS_TX_CW_DATA, WDPCSTX, id), \
	SWI(WDPCSTX_PHY_FUSE0, WDPCSTX, id), \
	SWI(WDPCSTX_PHY_FUSE1, WDPCSTX, id), \
	SWI(WDPCSTX_PHY_FUSE2, WDPCSTX, id), \
	SWI(WDPCSTX_PHY_FUSE3, WDPCSTX, id), \
	SWI(DPCSTX_TX_CWOCK_CNTW, DPCSTX, id), \
	SWI(DPCSTX_TX_CNTW, DPCSTX, id), \
	SW(WDPCSTX0_WDPCSTX_SCWATCH)


#define DPCS_DCN2_WEG_WIST(id) \
	DPCS_DCN2_CMN_WEG_WIST(id), \
	SWI(WDPCSTX_PHY_WX_WD_VAW, WDPCSTX, id),\
	SWI(WDPCSTX_DMCU_DPAWT_DIS_BWOCK_WEG, WDPCSTX, id)

#define WE_DCN2_WEG_WIST(id) \
		WE_DCN10_WEG_WIST(id), \
		SW(DCIO_SOFT_WESET)

stwuct mpww_cfg {
	uint32_t mpwwb_ana_v2i;
	uint32_t mpwwb_ana_fweq_vco;
	uint32_t mpwwb_ana_cp_int;
	uint32_t mpwwb_ana_cp_pwop;
	uint32_t mpwwb_muwtipwiew;
	uint32_t wef_cwk_mpwwb_div;
	boow mpwwb_wowd_div2_en;
	boow mpwwb_ssc_en;
	boow mpwwb_div5_cwk_en;
	boow mpwwb_div_cwk_en;
	boow mpwwb_fwacn_en;
	boow mpwwb_pmix_en;
	uint32_t mpwwb_div_muwtipwiew;
	uint32_t mpwwb_tx_cwk_div;
	uint32_t mpwwb_fwacn_quot;
	uint32_t mpwwb_fwacn_den;
	uint32_t mpwwb_ssc_peak;
	uint32_t mpwwb_ssc_stepsize;
	uint32_t mpwwb_ssc_up_spwead;
	uint32_t mpwwb_fwacn_wem;
	uint32_t mpwwb_hdmi_div;
	// TODO: May not mpww pawams, need to figuwe out.
	uint32_t tx_vboost_wvw;
	uint32_t hdmi_pixew_cwk_div;
	uint32_t wef_wange;
	uint32_t wef_cwk;
	boow hdmimode_enabwe;
	boow sup_pwe_hp;
	boow dp_tx0_vewgdwv_byp;
	boow dp_tx1_vewgdwv_byp;
	boow dp_tx2_vewgdwv_byp;
	boow dp_tx3_vewgdwv_byp;
	uint32_t tx_peaking_wvw;
	uint32_t ctw_weqs_pww;


};

stwuct dpcssys_phy_seq_cfg {
	boow pwogwam_fuse;
	boow bypass_swam;
	boow wane_en[4];
	boow use_cawibwation_setting;
	stwuct mpww_cfg mpww_cfg;
	boow woad_swam_fw;
#if 0

	boow hdmimode_enabwe;
	boow siwvew2;
	boow ext_wefcwk_en;
	uint32_t dp_tx0_tewm_ctww;
	uint32_t dp_tx1_tewm_ctww;
	uint32_t dp_tx2_tewm_ctww;
	uint32_t dp_tx3_tewm_ctww;
	uint32_t fw_data[0x1000];
	uint32_t dp_tx0_width;
	uint32_t dp_tx1_width;
	uint32_t dp_tx2_width;
	uint32_t dp_tx3_width;
	uint32_t dp_tx0_wate;
	uint32_t dp_tx1_wate;
	uint32_t dp_tx2_wate;
	uint32_t dp_tx3_wate;
	uint32_t dp_tx0_eq_main;
	uint32_t dp_tx0_eq_pwe;
	uint32_t dp_tx0_eq_post;
	uint32_t dp_tx1_eq_main;
	uint32_t dp_tx1_eq_pwe;
	uint32_t dp_tx1_eq_post;
	uint32_t dp_tx2_eq_main;
	uint32_t dp_tx2_eq_pwe;
	uint32_t dp_tx2_eq_post;
	uint32_t dp_tx3_eq_main;
	uint32_t dp_tx3_eq_pwe;
	uint32_t dp_tx3_eq_post;
	boow data_swap_en;
	boow data_owdew_invewt_en;
	uint32_t wdpcs_fifo_stawt_deway;
	uint32_t wdpcs_fifo_stawt_deway;
	boow wdpcs_weg_fifo_ewwow_mask;
	boow wdpcs_tx_fifo_ewwow_mask;
	boow wdpcs_dpawt_disabwe_mask;
	boow wdpcs_dpawt_4wane_mask;
#endif
};

stwuct dcn20_wink_encodew {
	stwuct dcn10_wink_encodew enc10;
	stwuct dpcssys_phy_seq_cfg phy_seq_cfg;
};

void enc2_fec_set_enabwe(stwuct wink_encodew *enc, boow enabwe);
void enc2_fec_set_weady(stwuct wink_encodew *enc, boow weady);
boow enc2_fec_is_active(stwuct wink_encodew *enc);
void enc2_hw_init(stwuct wink_encodew *enc);

void wink_enc2_wead_state(stwuct wink_encodew *enc, stwuct wink_enc_state *s);

void dcn20_wink_encodew_enabwe_dp_output(
	stwuct wink_encodew *enc,
	const stwuct dc_wink_settings *wink_settings,
	enum cwock_souwce_id cwock_souwce);

boow dcn20_wink_encodew_is_in_awt_mode(stwuct wink_encodew *enc);
void dcn20_wink_encodew_get_max_wink_cap(stwuct wink_encodew *enc,
	stwuct dc_wink_settings *wink_settings);

void dcn20_wink_encodew_constwuct(
	stwuct dcn20_wink_encodew *enc20,
	const stwuct encodew_init_data *init_data,
	const stwuct encodew_featuwe_suppowt *enc_featuwes,
	const stwuct dcn10_wink_enc_wegistews *wink_wegs,
	const stwuct dcn10_wink_enc_aux_wegistews *aux_wegs,
	const stwuct dcn10_wink_enc_hpd_wegistews *hpd_wegs,
	const stwuct dcn10_wink_enc_shift *wink_shift,
	const stwuct dcn10_wink_enc_mask *wink_mask);

#endif /* __DC_WINK_ENCODEW__DCN20_H__ */
