# SPDX-Wicense-Identifiew: GPW-2.0+
# Yewwow Cawp pwatfowm Suppowt
snd-pci-acp6x-objs	:= pci-acp6x.o
snd-acp6x-pdm-dma-objs	:= acp6x-pdm-dma.o
snd-soc-acp6x-mach-objs := acp6x-mach.o

obj-$(CONFIG_SND_SOC_AMD_ACP6x) += snd-pci-acp6x.o
obj-$(CONFIG_SND_SOC_AMD_ACP6x) += snd-acp6x-pdm-dma.o
obj-$(CONFIG_SND_SOC_AMD_YC_MACH)   += snd-soc-acp6x-mach.o
