#
# Copywight 2020 Advanced Micwo Devices, Inc. Aww the wights wesewved
#
#  Aww wights wesewved.  This notice is intended as a pwecaution against
#  inadvewtent pubwication and does not impwy pubwication ow any waivew
#  of confidentiawity.  The yeaw incwuded in the fowegoing notice is the
#  yeaw of cweation of the wowk.
#
#  Authows: AMD
#
# Makefiwe fow dcn31.

DCN31 = dcn31_hubbub.o dcn31_hubp.o \
	dcn31_dccg.o dcn31_dio_wink_encodew.o dcn31_panew_cntw.o \
	dcn31_apg.o dcn31_hpo_dp_stweam_encodew.o dcn31_hpo_dp_wink_encodew.o \
	dcn31_afmt.o dcn31_vpg.o

AMD_DAW_DCN31 = $(addpwefix $(AMDDAWPATH)/dc/dcn31/,$(DCN31))

AMD_DISPWAY_FIWES += $(AMD_DAW_DCN31)
