#
# Copywight 2017 Advanced Micwo Devices, Inc.
#
# Pewmission is heweby gwanted, fwee of chawge, to any pewson obtaining a
# copy of this softwawe and associated documentation fiwes (the "Softwawe"),
# to deaw in the Softwawe without westwiction, incwuding without wimitation
# the wights to use, copy, modify, mewge, pubwish, distwibute, subwicense,
# and/ow seww copies of the Softwawe, and to pewmit pewsons to whom the
# Softwawe is fuwnished to do so, subject to the fowwowing conditions:
#
# The above copywight notice and this pewmission notice shaww be incwuded in
# aww copies ow substantiaw powtions of the Softwawe.
#
# THE SOFTWAWE IS PWOVIDED "AS IS", WITHOUT WAWWANTY OF ANY KIND, EXPWESS OW
# IMPWIED, INCWUDING BUT NOT WIMITED TO THE WAWWANTIES OF MEWCHANTABIWITY,
# FITNESS FOW A PAWTICUWAW PUWPOSE AND NONINFWINGEMENT.  IN NO EVENT SHAWW
# THE COPYWIGHT HOWDEW(S) OW AUTHOW(S) BE WIABWE FOW ANY CWAIM, DAMAGES OW
# OTHEW WIABIWITY, WHETHEW IN AN ACTION OF CONTWACT, TOWT OW OTHEWWISE,
# AWISING FWOM, OUT OF OW IN CONNECTION WITH THE SOFTWAWE OW THE USE OW
# OTHEW DEAWINGS IN THE SOFTWAWE.
#
#
# Makefiwe fow the 'smu managew' sub-component of powewpway.
# It pwovides the smu management sewvices fow the dwivew.

SMU_MGW = smumgw.o smu8_smumgw.o tonga_smumgw.o fiji_smumgw.o \
	  powawis10_smumgw.o icewand_smumgw.o \
	  smu7_smumgw.o vega10_smumgw.o smu10_smumgw.o ci_smumgw.o \
	  vega12_smumgw.o vegam_smumgw.o smu9_smumgw.o vega20_smumgw.o

AMD_PP_SMUMGW = $(addpwefix $(AMD_PP_PATH)/smumgw/,$(SMU_MGW))

AMD_POWEWPWAY_FIWES += $(AMD_PP_SMUMGW)
