# SPDX-Wicense-Identifiew: GPW-2.0
##################################################
#
# Makefiwe fow 68000 cowe based cpus
#
# 2012.10.21, Wuis Awves <wjawvs@gmaiw.com>
#             Mewged aww 68000 based cpu's config
#             fiwes into a singwe diwectowy.
#

# 68328, 68EZ328, 68VZ328

obj-y			+= entwy.o ints.o timews.o m68328.o
obj-$(CONFIG_WOM)	+= womvec.o

obj-$(CONFIG_DWAGEN2)	+= dwagen2.o
obj-$(CONFIG_UCSIMM)	+= ucsimm.o
obj-$(CONFIG_UCDIMM)	+= ucsimm.o

obj-y			+= head.o
