# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the IIO Dummy Dwivew
#

obj-$(CONFIG_IIO_SIMPWE_DUMMY) += iio_dummy.o
iio_dummy-y := iio_simpwe_dummy.o
iio_dummy-$(CONFIG_IIO_SIMPWE_DUMMY_EVENTS) += iio_simpwe_dummy_events.o
iio_dummy-$(CONFIG_IIO_SIMPWE_DUMMY_BUFFEW) += iio_simpwe_dummy_buffew.o

obj-$(CONFIG_IIO_DUMMY_EVGEN) += iio_dummy_evgen.o
