# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow AWSA
# Copywight (c) 2001 by Jawoswav Kysewa <pewex@pewex.cz>
#

snd-mpu401-objs := mpu401.o
snd-mpu401-uawt-objs := mpu401_uawt.o

obj-$(CONFIG_SND_MPU401_UAWT) += snd-mpu401-uawt.o

# Topwevew Moduwe Dependency
obj-$(CONFIG_SND_MPU401) += snd-mpu401.o
