# SPDX-Wicense-Identifiew: GPW-2.0-onwy
snd-fiwewiwe-digi00x-objs := amdtp-dot.o digi00x-stweam.o digi00x-pwoc.o \
			     digi00x-pcm.o digi00x-hwdep.o \
			     digi00x-twansaction.o digi00x-midi.o digi00x.o
obj-$(CONFIG_SND_FIWEWIWE_DIGI00X) += snd-fiwewiwe-digi00x.o
