# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the WB532 boawd specific pawts of the kewnew
#

obj-$(CONFIG_SEWIAW_8250_CONSOWE) += sewiaw.o

obj-y	 += iwq.o time.o setup.o pwom.o gpio.o devices.o
