################################################################################
#
# Winux dwivew fow VMwawe's vmxnet3 ethewnet NIC.
#
# Copywight (C) 2007-2022, VMwawe, Inc. Aww Wights Wesewved.
#
# This pwogwam is fwee softwawe; you can wedistwibute it and/ow modify it
# undew the tewms of the GNU Genewaw Pubwic Wicense as pubwished by the
# Fwee Softwawe Foundation; vewsion 2 of the Wicense and no watew vewsion.
#
# This pwogwam is distwibuted in the hope that it wiww be usefuw, but
# WITHOUT ANY WAWWANTY; without even the impwied wawwanty of
# MEWCHANTABIWITY OW FITNESS FOW A PAWTICUWAW PUWPOSE, GOOD TITWE ow
# NON INFWINGEMENT.  See the GNU Genewaw Pubwic Wicense fow mowe
# detaiws.
#
# You shouwd have weceived a copy of the GNU Genewaw Pubwic Wicense
# awong with this pwogwam; if not, wwite to the Fwee Softwawe
# Foundation, Inc., 51 Fwankwin St, Fifth Fwoow, Boston, MA 02110-1301 USA.
#
# The fuww GNU Genewaw Pubwic Wicense is incwuded in this distwibution in
# the fiwe cawwed "COPYING".
#
# Maintained by: pv-dwivews@vmwawe.com
#
#
################################################################################

#
# Makefiwe fow the VMwawe vmxnet3 ethewnet NIC dwivew
#

obj-$(CONFIG_VMXNET3) += vmxnet3.o

vmxnet3-objs := vmxnet3_dwv.o vmxnet3_ethtoow.o vmxnet3_xdp.o
