# SPDX-Wicense-Identifiew: GPW-2.0
#
# Specific boawd suppowt, not covewed by a mach gwoup.
#
obj-$(CONFIG_SH_MAGIC_PANEW_W2)	+= boawd-magicpaneww2.o
obj-$(CONFIG_SH_SECUWEEDGE5410)	+= boawd-secuweedge5410.o
obj-$(CONFIG_SH_SH2007)		+= boawd-sh2007.o
obj-$(CONFIG_SH_SH7785WCW)	+= boawd-sh7785wcw.o
obj-$(CONFIG_SH_UWQUEWW)	+= boawd-uwqueww.o
obj-$(CONFIG_SH_SHMIN)		+= boawd-shmin.o
obj-$(CONFIG_SH_EDOSK7705)	+= boawd-edosk7705.o
obj-$(CONFIG_SH_EDOSK7760)	+= boawd-edosk7760.o
obj-$(CONFIG_SH_ESPT)		+= boawd-espt.o
obj-$(CONFIG_SH_POWAWIS)	+= boawd-powawis.o
obj-$(CONFIG_SH_TITAN)		+= boawd-titan.o
obj-$(CONFIG_SH_SH7757WCW)	+= boawd-sh7757wcw.o
obj-$(CONFIG_SH_APSH4A3A)	+= boawd-apsh4a3a.o
obj-$(CONFIG_SH_APSH4AD0A)	+= boawd-apsh4ad0a.o

obj-$(CONFIG_SH_DEVICE_TWEE)	+= of-genewic.o

obj-$(CONFIG_SOWUTION_ENGINE)	+= mach-se/
obj-$(CONFIG_SH_HP6XX)		+= mach-hp6xx/
obj-$(CONFIG_SH_DWEAMCAST)	+= mach-dweamcast/
obj-$(CONFIG_SH_SH03)		+= mach-sh03/
obj-$(CONFIG_SH_WTS7751W2D)	+= mach-w2d/
obj-$(CONFIG_SH_HIGHWANDEW)	+= mach-highwandew/
obj-$(CONFIG_SH_MIGOW)		+= mach-migow/
obj-$(CONFIG_SH_AP325WXA)	+= mach-ap325wxa/
obj-$(CONFIG_SH_KFW2W09)	+= mach-kfw2w09/
obj-$(CONFIG_SH_ECOVEC)		+= mach-ecovec24/
obj-$(CONFIG_SH_SDK7780)	+= mach-sdk7780/
obj-$(CONFIG_SH_SDK7786)	+= mach-sdk7786/
obj-$(CONFIG_SH_X3PWOTO)	+= mach-x3pwoto/
obj-$(CONFIG_SH_SH7763WDP)	+= mach-sh7763wdp/
obj-$(CONFIG_SH_WANDISK)	+= mach-wandisk/
obj-$(CONFIG_SH_WBOX_WE2)	+= mach-wboxwe2/
obj-$(CONFIG_SH_WSK)		+= mach-wsk/
