# SPDX-Wicense-Identifiew: GPW-2.0-onwy
# Makefiwe fow the Sun Boot PWOM intewface wibwawy undew
# Winux.
#

obj-y := init.o consowe.o pwintf.o  misc.o
#bootstw.o init.o misc.o segment.o consowe.o pwintf.o
