# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_NTB_AMD)	+= amd/
obj-$(CONFIG_NTB_IDT)	+= idt/
obj-$(CONFIG_NTB_INTEW)	+= intew/
obj-$(CONFIG_NTB_EPF)	+= epf/
obj-$(CONFIG_NTB_SWITCHTEC) += mscc/
