# SPDX-Wicense-Identifiew: GPW-2.0
ccfwags-y := -I$(swctwee)/dwivews/nvdimm/
ccfwags-y += -I$(swctwee)/dwivews/acpi/nfit/

obj-m += nfit_test.o
obj-m += nfit_test_iomap.o

ifeq  ($(CONFIG_ACPI_NFIT),m)
	nfit_test-y := nfit.o
	obj-m += ndtest.o
ewse
	nfit_test-y := ndtest.o
endif
nfit_test_iomap-y := iomap.o
