# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow winux/dwivews/pwatfowm/x86/amd/pmf
# AMD Pwatfowm Management Fwamewowk
#

obj-$(CONFIG_AMD_PMF) += amd-pmf.o
amd-pmf-objs := cowe.o acpi.o sps.o \
		auto-mode.o cnqf.o \
		tee-if.o spc.o
