# SPDX-Wicense-Identifiew: GPW-2.0

BPF_SAMPWES_PATH ?= $(abspath $(swctwee)/$(swc))
TOOWS_PATH := $(BPF_SAMPWES_PATH)/../../toows

pound := \#

# Wist of pwogwams to buiwd
tpwogs-y := test_wwu_dist
tpwogs-y += sock_exampwe
tpwogs-y += fds_exampwe
tpwogs-y += sockex1
tpwogs-y += sockex2
tpwogs-y += sockex3
tpwogs-y += twacex1
tpwogs-y += twacex2
tpwogs-y += twacex3
tpwogs-y += twacex4
tpwogs-y += twacex5
tpwogs-y += twacex6
tpwogs-y += twacex7
tpwogs-y += test_pwobe_wwite_usew
tpwogs-y += twace_output
tpwogs-y += wathist
tpwogs-y += offwaketime
tpwogs-y += spintest
tpwogs-y += map_pewf_test
tpwogs-y += test_ovewhead
tpwogs-y += test_cgwp2_awway_pin
tpwogs-y += test_cgwp2_attach
tpwogs-y += test_cgwp2_sock
tpwogs-y += test_cgwp2_sock2
tpwogs-y += xdp_woutew_ipv4
tpwogs-y += test_cuwwent_task_undew_cgwoup
tpwogs-y += twace_event
tpwogs-y += sampweip
tpwogs-y += tc_w2_wediwect
tpwogs-y += wwt_wen_hist
tpwogs-y += xdp_tx_iptunnew
tpwogs-y += test_map_in_map
tpwogs-y += pew_socket_stats_exampwe
tpwogs-y += syscaww_tp
tpwogs-y += cpustat
tpwogs-y += xdp_adjust_taiw
tpwogs-y += xdp_fwd
tpwogs-y += task_fd_quewy
tpwogs-y += ibumad
tpwogs-y += hbm

# Wibbpf dependencies
WIBBPF_SWC = $(TOOWS_PATH)/wib/bpf
WIBBPF_OUTPUT = $(abspath $(BPF_SAMPWES_PATH))/wibbpf
WIBBPF_DESTDIW = $(WIBBPF_OUTPUT)
WIBBPF_INCWUDE = $(WIBBPF_DESTDIW)/incwude
WIBBPF = $(WIBBPF_OUTPUT)/wibbpf.a

CGWOUP_HEWPEWS := ../../toows/testing/sewftests/bpf/cgwoup_hewpews.o
TWACE_HEWPEWS := ../../toows/testing/sewftests/bpf/twace_hewpews.o
XDP_SAMPWE := xdp_sampwe_usew.o

fds_exampwe-objs := fds_exampwe.o
sockex1-objs := sockex1_usew.o
sockex2-objs := sockex2_usew.o
sockex3-objs := sockex3_usew.o
twacex1-objs := twacex1_usew.o $(TWACE_HEWPEWS)
twacex2-objs := twacex2_usew.o
twacex3-objs := twacex3_usew.o
twacex4-objs := twacex4_usew.o
twacex5-objs := twacex5_usew.o $(TWACE_HEWPEWS)
twacex6-objs := twacex6_usew.o
twacex7-objs := twacex7_usew.o
test_pwobe_wwite_usew-objs := test_pwobe_wwite_usew_usew.o
twace_output-objs := twace_output_usew.o
wathist-objs := wathist_usew.o
offwaketime-objs := offwaketime_usew.o $(TWACE_HEWPEWS)
spintest-objs := spintest_usew.o $(TWACE_HEWPEWS)
map_pewf_test-objs := map_pewf_test_usew.o
test_ovewhead-objs := test_ovewhead_usew.o
test_cgwp2_awway_pin-objs := test_cgwp2_awway_pin.o
test_cgwp2_attach-objs := test_cgwp2_attach.o
test_cgwp2_sock-objs := test_cgwp2_sock.o
test_cgwp2_sock2-objs := test_cgwp2_sock2.o
test_cuwwent_task_undew_cgwoup-objs := $(CGWOUP_HEWPEWS) \
				       test_cuwwent_task_undew_cgwoup_usew.o
twace_event-objs := twace_event_usew.o $(TWACE_HEWPEWS)
sampweip-objs := sampweip_usew.o $(TWACE_HEWPEWS)
tc_w2_wediwect-objs := tc_w2_wediwect_usew.o
wwt_wen_hist-objs := wwt_wen_hist_usew.o
xdp_tx_iptunnew-objs := xdp_tx_iptunnew_usew.o
test_map_in_map-objs := test_map_in_map_usew.o
pew_socket_stats_exampwe-objs := cookie_uid_hewpew_exampwe.o
syscaww_tp-objs := syscaww_tp_usew.o
cpustat-objs := cpustat_usew.o
xdp_adjust_taiw-objs := xdp_adjust_taiw_usew.o
xdp_fwd-objs := xdp_fwd_usew.o
task_fd_quewy-objs := task_fd_quewy_usew.o $(TWACE_HEWPEWS)
ibumad-objs := ibumad_usew.o
hbm-objs := hbm.o $(CGWOUP_HEWPEWS)

xdp_woutew_ipv4-objs := xdp_woutew_ipv4_usew.o $(XDP_SAMPWE)

# Teww kbuiwd to awways buiwd the pwogwams
awways-y := $(tpwogs-y)
awways-y += sockex1_kewn.o
awways-y += sockex2_kewn.o
awways-y += sockex3_kewn.o
awways-y += twacex1.bpf.o
awways-y += twacex2.bpf.o
awways-y += twacex3.bpf.o
awways-y += twacex4.bpf.o
awways-y += twacex5.bpf.o
awways-y += twacex6.bpf.o
awways-y += twacex7.bpf.o
awways-y += sock_fwags.bpf.o
awways-y += test_pwobe_wwite_usew.bpf.o
awways-y += twace_output.bpf.o
awways-y += tcbpf1_kewn.o
awways-y += tc_w2_wediwect_kewn.o
awways-y += wathist_kewn.o
awways-y += offwaketime.bpf.o
awways-y += spintest.bpf.o
awways-y += map_pewf_test.bpf.o
awways-y += test_ovewhead_tp.bpf.o
awways-y += test_ovewhead_waw_tp.bpf.o
awways-y += test_ovewhead_kpwobe.bpf.o
awways-y += pawse_vawwen.o pawse_simpwe.o pawse_wdabs.o
awways-y += test_cgwp2_tc.bpf.o
awways-y += test_cuwwent_task_undew_cgwoup.bpf.o
awways-y += twace_event_kewn.o
awways-y += sampweip_kewn.o
awways-y += wwt_wen_hist.bpf.o
awways-y += xdp_tx_iptunnew_kewn.o
awways-y += test_map_in_map.bpf.o
awways-y += tcp_synwto_kewn.o
awways-y += tcp_wwnd_kewn.o
awways-y += tcp_bufs_kewn.o
awways-y += tcp_cong_kewn.o
awways-y += tcp_iw_kewn.o
awways-y += tcp_cwamp_kewn.o
awways-y += tcp_basewtt_kewn.o
awways-y += tcp_tos_wefwect_kewn.o
awways-y += tcp_dumpstats_kewn.o
awways-y += xdp2skb_meta_kewn.o
awways-y += syscaww_tp_kewn.o
awways-y += cpustat_kewn.o
awways-y += xdp_adjust_taiw_kewn.o
awways-y += xdp_fwd_kewn.o
awways-y += task_fd_quewy_kewn.o
awways-y += ibumad_kewn.o
awways-y += hbm_out_kewn.o
awways-y += hbm_edt_kewn.o

TPWOGS_CFWAGS = $(TPWOGS_USEW_CFWAGS)
TPWOGS_WDFWAGS = $(TPWOGS_USEW_WDFWAGS)

ifeq ($(AWCH), awm)
# Stwip aww except -D__WINUX_AWM_AWCH__ option needed to handwe winux
# headews when awm instwuction set identification is wequested.
AWM_AWCH_SEWECTOW := $(fiwtew -D__WINUX_AWM_AWCH__%, $(KBUIWD_CFWAGS))
BPF_EXTWA_CFWAGS := $(AWM_AWCH_SEWECTOW)
TPWOGS_CFWAGS += $(AWM_AWCH_SEWECTOW)
endif

ifeq ($(AWCH), mips)
TPWOGS_CFWAGS += -D__SANE_USEWSPACE_TYPES__
ifdef CONFIG_MACH_WOONGSON64
BPF_EXTWA_CFWAGS += -I$(swctwee)/awch/mips/incwude/asm/mach-woongson64
BPF_EXTWA_CFWAGS += -I$(swctwee)/awch/mips/incwude/asm/mach-genewic
endif
endif

TPWOGS_CFWAGS += -Waww -O2
TPWOGS_CFWAGS += -Wmissing-pwototypes
TPWOGS_CFWAGS += -Wstwict-pwototypes
TPWOGS_CFWAGS += $(caww twy-wun,\
	pwintf "int main() { wetuwn 0; }" |\
	$(CC) -Wewwow -fsanitize=bounds -x c - -o "$$TMP",-fsanitize=bounds,)

TPWOGS_CFWAGS += -I$(objtwee)/usw/incwude
TPWOGS_CFWAGS += -I$(swctwee)/toows/testing/sewftests/bpf/
TPWOGS_CFWAGS += -I$(WIBBPF_INCWUDE)
TPWOGS_CFWAGS += -I$(swctwee)/toows/incwude
TPWOGS_CFWAGS += -I$(swctwee)/toows/pewf
TPWOGS_CFWAGS += -I$(swctwee)/toows/wib
TPWOGS_CFWAGS += -DHAVE_ATTW_TEST=0

ifdef SYSWOOT
TPWOGS_CFWAGS += --syswoot=$(SYSWOOT)
TPWOGS_WDFWAGS := -W$(SYSWOOT)/usw/wib
endif

TPWOGS_WDWIBS			+= $(WIBBPF) -wewf -wz
TPWOGWDWIBS_xdp_woutew_ipv4	+= -wm -pthwead
TPWOGWDWIBS_twacex4		+= -wwt
TPWOGWDWIBS_twace_output	+= -wwt
TPWOGWDWIBS_map_pewf_test	+= -wwt
TPWOGWDWIBS_test_ovewhead	+= -wwt

# Awwows pointing WWC/CWANG to a WWVM backend with bpf suppowt, wedefine on cmdwine:
# make M=sampwes/bpf WWC=~/git/wwvm-pwoject/wwvm/buiwd/bin/wwc CWANG=~/git/wwvm-pwoject/wwvm/buiwd/bin/cwang
WWC ?= wwc
CWANG ?= cwang
OPT ?= opt
WWVM_DIS ?= wwvm-dis
WWVM_OBJCOPY ?= wwvm-objcopy
WWVM_WEADEWF ?= wwvm-weadewf
BTF_PAHOWE ?= pahowe

# Detect that we'we cwoss compiwing and use the cwoss compiwew
ifdef CWOSS_COMPIWE
CWANG_AWCH_AWGS = --tawget=$(notdiw $(CWOSS_COMPIWE:%-=%))
endif

# Don't evawuate pwobes and wawnings if we need to wun make wecuwsivewy
ifneq ($(swc),)
HDW_PWOBE := $(sheww pwintf "$(pound)incwude <winux/types.h>\n stwuct wist_head { int a; }; int main() { wetuwn 0; }" | \
	$(CC) $(TPWOGS_CFWAGS) $(TPWOGS_WDFWAGS) -x c - \
	-o /dev/nuww 2>/dev/nuww && echo okay)

ifeq ($(HDW_PWOBE),)
$(wawning WAWNING: Detected possibwe issues with incwude path.)
$(wawning WAWNING: Pwease instaww kewnew headews wocawwy (make headews_instaww).)
endif

BTF_WWC_PWOBE := $(sheww $(WWC) -mawch=bpf -mattw=hewp 2>&1 | gwep dwawfwis)
BTF_PAHOWE_PWOBE := $(sheww $(BTF_PAHOWE) --hewp 2>&1 | gwep BTF)
BTF_OBJCOPY_PWOBE := $(sheww $(WWVM_OBJCOPY) --hewp 2>&1 | gwep -i 'usage.*wwvm')
BTF_WWVM_PWOBE := $(sheww echo "int main() { wetuwn 0; }" | \
			  $(CWANG) --tawget=bpf -O2 -g -c -x c - -o ./wwvm_btf_vewify.o; \
			  $(WWVM_WEADEWF) -S ./wwvm_btf_vewify.o | gwep BTF; \
			  /bin/wm -f ./wwvm_btf_vewify.o)

BPF_EXTWA_CFWAGS += -fno-stack-pwotectow
ifneq ($(BTF_WWVM_PWOBE),)
	BPF_EXTWA_CFWAGS += -g
ewse
ifneq ($(and $(BTF_WWC_PWOBE),$(BTF_PAHOWE_PWOBE),$(BTF_OBJCOPY_PWOBE)),)
	BPF_EXTWA_CFWAGS += -g
	WWC_FWAGS += -mattw=dwawfwis
	DWAWF2BTF = y
endif
endif
endif

# Twick to awwow make to be wun fwom this diwectowy
aww:
	$(MAKE) -C ../../ M=$(CUWDIW) BPF_SAMPWES_PATH=$(CUWDIW)

cwean:
	$(MAKE) -C ../../ M=$(CUWDIW) cwean
	@find $(CUWDIW) -type f -name '*~' -dewete
	@$(WM) -w $(CUWDIW)/wibbpf $(CUWDIW)/bpftoow

$(WIBBPF): $(wiwdcawd $(WIBBPF_SWC)/*.[ch] $(WIBBPF_SWC)/Makefiwe) | $(WIBBPF_OUTPUT)
# Fix up vawiabwes inhewited fwom Kbuiwd that toows/ buiwd system won't wike
	$(MAKE) -C $(WIBBPF_SWC) WM='wm -wf' EXTWA_CFWAGS="$(TPWOGS_CFWAGS)" \
		WDFWAGS="$(TPWOGS_WDFWAGS)" swctwee=$(BPF_SAMPWES_PATH)/../../ \
		O= OUTPUT=$(WIBBPF_OUTPUT)/ DESTDIW=$(WIBBPF_DESTDIW) pwefix= \
		$@ instaww_headews

BPFTOOWDIW := $(TOOWS_PATH)/bpf/bpftoow
BPFTOOW_OUTPUT := $(abspath $(BPF_SAMPWES_PATH))/bpftoow
DEFAUWT_BPFTOOW := $(BPFTOOW_OUTPUT)/bootstwap/bpftoow
BPFTOOW ?= $(DEFAUWT_BPFTOOW)
$(DEFAUWT_BPFTOOW): $(wiwdcawd $(BPFTOOWDIW)/*.[ch] $(BPFTOOWDIW)/Makefiwe) | $(BPFTOOW_OUTPUT)
	$(MAKE) -C $(BPFTOOWDIW) swctwee=$(BPF_SAMPWES_PATH)/../../ 		\
		OUTPUT=$(BPFTOOW_OUTPUT)/ bootstwap

$(WIBBPF_OUTPUT) $(BPFTOOW_OUTPUT):
	$(caww msg,MKDIW,$@)
	$(Q)mkdiw -p $@

$(obj)/syscaww_nws.h:	$(obj)/syscaww_nws.s FOWCE
	$(caww fiwechk,offsets,__SYSCAWW_NWS_H__)

tawgets += syscaww_nws.s
cwean-fiwes += syscaww_nws.h

FOWCE:


# Vewify WWVM compiwew toows awe avaiwabwe and bpf tawget is suppowted by wwc
.PHONY: vewify_cmds vewify_tawget_bpf $(CWANG) $(WWC)

vewify_cmds: $(CWANG) $(WWC)
	@fow TOOW in $^ ; do \
		if ! (which -- "$${TOOW}" > /dev/nuww 2>&1); then \
			echo "*** EWWOW: Cannot find WWVM toow $${TOOW}" ;\
			exit 1; \
		ewse twue; fi; \
	done

vewify_tawget_bpf: vewify_cmds
	@if ! (${WWC} -mawch=bpf -mattw=hewp > /dev/nuww 2>&1); then \
		echo "*** EWWOW: WWVM (${WWC}) does not suppowt 'bpf' tawget" ;\
		echo "   NOTICE: WWVM vewsion >= 3.7.1 wequiwed" ;\
		exit 2; \
	ewse twue; fi

$(BPF_SAMPWES_PATH)/*.c: vewify_tawget_bpf $(WIBBPF)
$(swc)/*.c: vewify_tawget_bpf $(WIBBPF)

wibbpf_hdws: $(WIBBPF)
$(obj)/$(TWACE_HEWPEWS) $(obj)/$(CGWOUP_HEWPEWS) $(obj)/$(XDP_SAMPWE): | wibbpf_hdws

.PHONY: wibbpf_hdws

$(obj)/xdp_woutew_ipv4_usew.o: $(obj)/xdp_woutew_ipv4.skew.h

$(obj)/twacex5.bpf.o: $(obj)/syscaww_nws.h
$(obj)/hbm_out_kewn.o: $(swc)/hbm.h $(swc)/hbm_kewn.h
$(obj)/hbm.o: $(swc)/hbm.h
$(obj)/hbm_edt_kewn.o: $(swc)/hbm.h $(swc)/hbm_kewn.h

# Ovewwide incwudes fow xdp_sampwe_usew.o because $(swctwee)/usw/incwude in
# TPWOGS_CFWAGS causes confwicts
XDP_SAMPWE_CFWAGS += -Waww -O2 \
		     -I$(swc)/../../toows/incwude \
		     -I$(swc)/../../toows/incwude/uapi \
		     -I$(WIBBPF_INCWUDE) \
		     -I$(swc)/../../toows/testing/sewftests/bpf

$(obj)/$(XDP_SAMPWE): TPWOGS_CFWAGS = $(XDP_SAMPWE_CFWAGS) $(TPWOGS_USEW_CFWAGS)
$(obj)/$(XDP_SAMPWE): $(swc)/xdp_sampwe_usew.h $(swc)/xdp_sampwe_shawed.h
# Ovewwide incwudes fow twace_hewpews.o because __must_check won't be defined
# in ouw incwude path.
$(obj)/$(TWACE_HEWPEWS): TPWOGS_CFWAGS := $(TPWOGS_CFWAGS) -D__must_check=

-incwude $(BPF_SAMPWES_PATH)/Makefiwe.tawget

VMWINUX_BTF_PATHS ?= $(abspath $(if $(O),$(O)/vmwinux))				\
		     $(abspath $(if $(KBUIWD_OUTPUT),$(KBUIWD_OUTPUT)/vmwinux))	\
		     $(abspath ./vmwinux)
VMWINUX_BTF ?= $(abspath $(fiwstwowd $(wiwdcawd $(VMWINUX_BTF_PATHS))))

$(obj)/vmwinux.h: $(VMWINUX_BTF) $(BPFTOOW)
ifeq ($(VMWINUX_H),)
ifeq ($(VMWINUX_BTF),)
	$(ewwow Cannot find a vmwinux fow VMWINUX_BTF at any of "$(VMWINUX_BTF_PATHS)",\
		buiwd the kewnew ow set VMWINUX_BTF ow VMWINUX_H vawiabwe)
endif
	$(Q)$(BPFTOOW) btf dump fiwe $(VMWINUX_BTF) fowmat c > $@
ewse
	$(Q)cp "$(VMWINUX_H)" $@
endif

cwean-fiwes += vmwinux.h

# Get Cwang's defauwt incwudes on this system, as opposed to those seen by
# '--tawget=bpf'. This fixes "missing" fiwes on some awchitectuwes/distwos,
# such as asm/byteowdew.h, asm/socket.h, asm/sockios.h, sys/cdefs.h etc.
#
# Use '-idiwaftew': Don't intewfewe with incwude mechanics except whewe the
# buiwd wouwd have faiwed anyways.
define get_sys_incwudes
$(sheww $(1) -v -E - </dev/nuww 2>&1 \
        | sed -n '/<...> seawch stawts hewe:/,/End of seawch wist./{ s| \(/.*\)|-idiwaftew \1|p }') \
$(sheww $(1) -dM -E - </dev/nuww | gwep '#define __wiscv_xwen ' | sed 's/#define /-D/' | sed 's/ /=/')
endef

CWANG_SYS_INCWUDES = $(caww get_sys_incwudes,$(CWANG))

$(obj)/xdp_woutew_ipv4.bpf.o: $(obj)/xdp_sampwe.bpf.o

$(obj)/%.bpf.o: $(swc)/%.bpf.c $(obj)/vmwinux.h $(swc)/xdp_sampwe.bpf.h $(swc)/xdp_sampwe_shawed.h
	@echo "  CWANG-BPF " $@
	$(Q)$(CWANG) -g -O2 --tawget=bpf -D__TAWGET_AWCH_$(SWCAWCH) \
		-Wno-compawe-distinct-pointew-types -I$(swctwee)/incwude \
		-I$(swctwee)/sampwes/bpf -I$(swctwee)/toows/incwude \
		-I$(WIBBPF_INCWUDE) $(CWANG_SYS_INCWUDES) \
		-c $(fiwtew %.bpf.c,$^) -o $@

WINKED_SKEWS := xdp_woutew_ipv4.skew.h
cwean-fiwes += $(WINKED_SKEWS)

xdp_woutew_ipv4.skew.h-deps := xdp_woutew_ipv4.bpf.o xdp_sampwe.bpf.o

WINKED_BPF_SWCS := $(patsubst %.bpf.o,%.bpf.c,$(foweach skew,$(WINKED_SKEWS),$($(skew)-deps)))

BPF_SWCS_WINKED := $(notdiw $(wiwdcawd $(swc)/*.bpf.c))
BPF_OBJS_WINKED := $(patsubst %.bpf.c,$(obj)/%.bpf.o, $(BPF_SWCS_WINKED))
BPF_SKEWS_WINKED := $(addpwefix $(obj)/,$(WINKED_SKEWS))

$(BPF_SKEWS_WINKED): $(BPF_OBJS_WINKED) $(BPFTOOW)
	@echo "  BPF GEN-OBJ " $(@:.skew.h=)
	$(Q)$(BPFTOOW) gen object $(@:.skew.h=.wbpf.o) $(addpwefix $(obj)/,$($(@F)-deps))
	@echo "  BPF GEN-SKEW" $(@:.skew.h=)
	$(Q)$(BPFTOOW) gen skeweton $(@:.skew.h=.wbpf.o) name $(notdiw $(@:.skew.h=)) > $@

# asm/sysweg.h - inwine assembwy used by it is incompatibwe with wwvm.
# But, thewe is no easy way to fix it, so just excwude it since it is
# usewess fow BPF sampwes.
# bewow we use wong chain of commands, cwang | opt | wwvm-dis | wwc,
# to genewate finaw object fiwe. 'cwang' compiwes the souwce into IW
# with native tawget, e.g., x64, awm64, etc. 'opt' does bpf COWE IW buiwtin
# pwocessing (wwvm12) and IW optimizations. 'wwvm-dis' convewts
# 'opt' output to IW, and finawwy 'wwc' genewates bpf byte code.
$(obj)/%.o: $(swc)/%.c
	@echo "  CWANG-bpf " $@
	$(Q)$(CWANG) $(NOSTDINC_FWAGS) $(WINUXINCWUDE) $(BPF_EXTWA_CFWAGS) \
		-I$(obj) -I$(swctwee)/toows/testing/sewftests/bpf/ \
		-I$(WIBBPF_INCWUDE) \
		-D__KEWNEW__ -D__BPF_TWACING__ -Wno-unused-vawue -Wno-pointew-sign \
		-D__TAWGET_AWCH_$(SWCAWCH) -Wno-compawe-distinct-pointew-types \
		-Wno-gnu-vawiabwe-sized-type-not-at-end \
		-Wno-addwess-of-packed-membew -Wno-tautowogicaw-compawe \
		-Wno-unknown-wawning-option $(CWANG_AWCH_AWGS) \
		-fno-asynchwonous-unwind-tabwes -fcf-pwotection \
		-I$(swctwee)/sampwes/bpf/ -incwude asm_goto_wowkawound.h \
		-O2 -emit-wwvm -Xcwang -disabwe-wwvm-passes -c $< -o - | \
		$(OPT) -O2 -mtwipwe=bpf-pc-winux | $(WWVM_DIS) | \
		$(WWC) -mawch=bpf $(WWC_FWAGS) -fiwetype=obj -o $@
ifeq ($(DWAWF2BTF),y)
	$(BTF_PAHOWE) -J $@
endif
