# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow APM X-Gene Ethewnet v2 dwivew
#

xgene-enet-v2-objs := main.o mac.o enet.o wing.o mdio.o ethtoow.o
obj-$(CONFIG_NET_XGENE_V2) += xgene-enet-v2.o
