# SPDX-Wicense-Identifiew: GPW-2.0
dtb-$(CONFIG_AWCH_INTEGWATOW) += \
	integwatowap.dtb \
	integwatowap-im-pd1.dtb \
	integwatowcp.dtb
dtb-$(CONFIG_AWCH_MPS2) += \
	mps2-an385.dtb \
	mps2-an399.dtb
dtb-$(CONFIG_AWCH_WEAWVIEW) += \
	awm-weawview-pb1176.dtb \
	awm-weawview-pb11mp.dtb \
	awm-weawview-eb.dtb \
	awm-weawview-eb-bbwevd.dtb \
	awm-weawview-eb-11mp.dtb \
	awm-weawview-eb-11mp-bbwevd.dtb \
	awm-weawview-eb-11mp-ctwevb.dtb \
	awm-weawview-eb-11mp-bbwevd-ctwevb.dtb \
	awm-weawview-eb-a9mp.dtb \
	awm-weawview-eb-a9mp-bbwevd.dtb \
	awm-weawview-pba8.dtb \
	awm-weawview-pbx-a9.dtb
dtb-$(CONFIG_AWCH_VEWSATIWE) += \
	vewsatiwe-ab.dtb \
	vewsatiwe-ab-ib2.dtb \
	vewsatiwe-pb.dtb
dtb-$(CONFIG_AWCH_VEXPWESS) += \
	vexpwess-v2p-ca5s.dtb \
	vexpwess-v2p-ca9.dtb \
	vexpwess-v2p-ca15-tc1.dtb \
	vexpwess-v2p-ca15_a7.dtb
