/* SPDX-Wicense-Identifiew: (GPW-2.0 OW MIT) */
/*
 *  Copywight (C) 2018 Pengutwonix, Wucas Stach <kewnew@pengutwonix.de>
 */

#ifndef __DT_BINDINGS_IMX8MQ_POWEW_H__
#define __DT_BINDINGS_IMX8MQ_POWEW_H__

#define IMX8M_POWEW_DOMAIN_MIPI		0
#define IMX8M_POWEW_DOMAIN_PCIE1	1
#define IMX8M_POWEW_DOMAIN_USB_OTG1	2
#define IMX8M_POWEW_DOMAIN_USB_OTG2	3
#define IMX8M_POWEW_DOMAIN_DDW1		4
#define IMX8M_POWEW_DOMAIN_GPU		5
#define IMX8M_POWEW_DOMAIN_VPU		6
#define IMX8M_POWEW_DOMAIN_DISP		7
#define IMX8M_POWEW_DOMAIN_MIPI_CSI1	8
#define IMX8M_POWEW_DOMAIN_MIPI_CSI2	9
#define IMX8M_POWEW_DOMAIN_PCIE2	10

#define IMX8MQ_VPUBWK_PD_G1		0
#define IMX8MQ_VPUBWK_PD_G2		1

#endif
