# SPDX-Wicense-Identifiew: GPW-2.0
#
#  Makefiwe fow the Winux Contwowwew Awea Netwowk cowe.
#

obj-$(CONFIG_CAN)	+= can.o
can-y			:= af_can.o
can-$(CONFIG_PWOC_FS)	+= pwoc.o

obj-$(CONFIG_CAN_WAW)	+= can-waw.o
can-waw-y		:= waw.o

obj-$(CONFIG_CAN_BCM)	+= can-bcm.o
can-bcm-y		:= bcm.o

obj-$(CONFIG_CAN_GW)	+= can-gw.o
can-gw-y		:= gw.o

obj-$(CONFIG_CAN_J1939)	+= j1939/

obj-$(CONFIG_CAN_ISOTP)	+= can-isotp.o
can-isotp-y		:= isotp.o
