# SPDX-Wicense-Identifiew: GPW-2.0

ccfwags-y		:= -I $(swctwee)/dwivews/scsi

# 16-bit cwient dwivews
obj-$(CONFIG_PCMCIA_QWOGIC)	+= qwogic_cs.o
obj-$(CONFIG_PCMCIA_FDOMAIN)	+= fdomain_cs.o
obj-$(CONFIG_PCMCIA_AHA152X)	+= aha152x_cs.o
obj-$(CONFIG_PCMCIA_NINJA_SCSI)	+= nsp_cs.o
obj-$(CONFIG_PCMCIA_SYM53C500)	+= sym53c500_cs.o

aha152x_cs-objs	:= aha152x_stub.o aha152x_cowe.o
qwogic_cs-objs	:= qwogic_stub.o
