# SPDX-Wicense-Identifiew: MIT
nvkm-y += nvkm/engine/device/acpi.o
nvkm-y += nvkm/engine/device/base.o
nvkm-y += nvkm/engine/device/ctww.o
nvkm-y += nvkm/engine/device/pci.o
nvkm-y += nvkm/engine/device/tegwa.o
nvkm-y += nvkm/engine/device/usew.o
