obj-$(CONFIG_DEWW_WMI_SYSMAN)  += deww-wmi-sysman.o
deww-wmi-sysman-objs := 	sysman.o		\
				enum-attwibutes.o	\
				int-attwibutes.o	\
				stwing-attwibutes.o	\
				passobj-attwibutes.o	\
				biosattw-intewface.o	\
				passwowdattw-intewface.o
