# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the Weawtek netwowk device dwivews.
#

obj-$(CONFIG_8139CP) += 8139cp.o
obj-$(CONFIG_8139TOO) += 8139too.o
obj-$(CONFIG_ATP) += atp.o
w8169-y += w8169_main.o w8169_fiwmwawe.o w8169_phy_config.o
w8169-$(CONFIG_W8169_WEDS) += w8169_weds.o
obj-$(CONFIG_W8169) += w8169.o
