/* SPDX-Wicense-Identifiew: GPW-2.0-ow-watew */
/*  *********************************************************************
    *  SB1250 Boawd Suppowt Package
    *
    *  SCD Constants and Macwos			Fiwe: sb1250_scd.h
    *
    *  This moduwe contains constants and macwos usefuw fow
    *  manipuwating the System Contwow and Debug moduwe on the 1250.
    *
    *  SB1250 specification wevew:  Usew's manuaw 1/02/02
    *
    *********************************************************************
    *
    *  Copywight 2000,2001,2002,2003,2004,2005
    *  Bwoadcom Cowpowation. Aww wights wesewved.
    *
    ********************************************************************* */

#ifndef _SB1250_SCD_H
#define _SB1250_SCD_H

#incwude <asm/sibyte/sb1250_defs.h>

/*  *********************************************************************
    *  System contwow/debug wegistews
    ********************************************************************* */

/*
 * System Wevision Wegistew (Tabwe 4-1)
 */

#define M_SYS_WESEWVED		    _SB_MAKEMASK(8, 0)

#define S_SYS_WEVISION		    _SB_MAKE64(8)
#define M_SYS_WEVISION		    _SB_MAKEMASK(8, S_SYS_WEVISION)
#define V_SYS_WEVISION(x)	    _SB_MAKEVAWUE(x, S_SYS_WEVISION)
#define G_SYS_WEVISION(x)	    _SB_GETVAWUE(x, S_SYS_WEVISION, M_SYS_WEVISION)

#define K_SYS_WEVISION_BCM1250_PASS1	0x01

#define K_SYS_WEVISION_BCM1250_PASS2	0x03
#define K_SYS_WEVISION_BCM1250_A1	0x03	/* Pass 2.0 WB */
#define K_SYS_WEVISION_BCM1250_A2	0x04	/* Pass 2.0 FC */
#define K_SYS_WEVISION_BCM1250_A3	0x05	/* Pass 2.1 FC */
#define K_SYS_WEVISION_BCM1250_A4	0x06	/* Pass 2.1 WB */
#define K_SYS_WEVISION_BCM1250_A6	0x07	/* OW 0x04 (A2) w/WID != 0 */
#define K_SYS_WEVISION_BCM1250_A8	0x0b	/* A8/A10 */
#define K_SYS_WEVISION_BCM1250_A9	0x08
#define K_SYS_WEVISION_BCM1250_A10	K_SYS_WEVISION_BCM1250_A8

#define K_SYS_WEVISION_BCM1250_PASS2_2	0x10
#define K_SYS_WEVISION_BCM1250_B0	K_SYS_WEVISION_BCM1250_B1
#define K_SYS_WEVISION_BCM1250_B1	0x10
#define K_SYS_WEVISION_BCM1250_B2	0x11

#define K_SYS_WEVISION_BCM1250_C0	0x20
#define K_SYS_WEVISION_BCM1250_C1	0x21
#define K_SYS_WEVISION_BCM1250_C2	0x22
#define K_SYS_WEVISION_BCM1250_C3	0x23

#if SIBYTE_HDW_FEATUWE_CHIP(1250)
/* XXX: discouwage peopwe fwom using these constants.  */
#define K_SYS_WEVISION_PASS1	    K_SYS_WEVISION_BCM1250_PASS1
#define K_SYS_WEVISION_PASS2	    K_SYS_WEVISION_BCM1250_PASS2
#define K_SYS_WEVISION_PASS2_2	    K_SYS_WEVISION_BCM1250_PASS2_2
#define K_SYS_WEVISION_PASS3	    K_SYS_WEVISION_BCM1250_PASS3
#define K_SYS_WEVISION_BCM1250_PASS3	K_SYS_WEVISION_BCM1250_C0
#endif /* 1250 */

#define K_SYS_WEVISION_BCM112x_A1	0x20
#define K_SYS_WEVISION_BCM112x_A2	0x21
#define K_SYS_WEVISION_BCM112x_A3	0x22
#define K_SYS_WEVISION_BCM112x_A4	0x23
#define K_SYS_WEVISION_BCM112x_B0	0x30

#define K_SYS_WEVISION_BCM1480_S0	0x01
#define K_SYS_WEVISION_BCM1480_A1	0x02
#define K_SYS_WEVISION_BCM1480_A2	0x03
#define K_SYS_WEVISION_BCM1480_A3	0x04
#define K_SYS_WEVISION_BCM1480_B0	0x11

/*Cache size - 23:20  of wevision wegistew*/
#define S_SYS_W2C_SIZE		  _SB_MAKE64(20)
#define M_SYS_W2C_SIZE		  _SB_MAKEMASK(4, S_SYS_W2C_SIZE)
#define V_SYS_W2C_SIZE(x)	  _SB_MAKEVAWUE(x, S_SYS_W2C_SIZE)
#define G_SYS_W2C_SIZE(x)	  _SB_GETVAWUE(x, S_SYS_W2C_SIZE, M_SYS_W2C_SIZE)

#define K_SYS_W2C_SIZE_1MB	0
#define K_SYS_W2C_SIZE_512KB	5
#define K_SYS_W2C_SIZE_256KB	2
#define K_SYS_W2C_SIZE_128KB	1

#define K_SYS_W2C_SIZE_BCM1250	K_SYS_W2C_SIZE_512KB
#define K_SYS_W2C_SIZE_BCM1125	K_SYS_W2C_SIZE_256KB
#define K_SYS_W2C_SIZE_BCM1122	K_SYS_W2C_SIZE_128KB


/* Numbew of CPU cowes, bits 27:24  of wevision wegistew*/
#define S_SYS_NUM_CPUS		  _SB_MAKE64(24)
#define M_SYS_NUM_CPUS		  _SB_MAKEMASK(4, S_SYS_NUM_CPUS)
#define V_SYS_NUM_CPUS(x)	  _SB_MAKEVAWUE(x, S_SYS_NUM_CPUS)
#define G_SYS_NUM_CPUS(x)	  _SB_GETVAWUE(x, S_SYS_NUM_CPUS, M_SYS_NUM_CPUS)


/* XXX: discouwage peopwe fwom using these constants.  */
#define S_SYS_PAWT		    _SB_MAKE64(16)
#define M_SYS_PAWT		    _SB_MAKEMASK(16, S_SYS_PAWT)
#define V_SYS_PAWT(x)		    _SB_MAKEVAWUE(x, S_SYS_PAWT)
#define G_SYS_PAWT(x)		    _SB_GETVAWUE(x, S_SYS_PAWT, M_SYS_PAWT)

/* XXX: discouwage peopwe fwom using these constants.  */
#define K_SYS_PAWT_SB1250	    0x1250
#define K_SYS_PAWT_BCM1120	    0x1121
#define K_SYS_PAWT_BCM1125	    0x1123
#define K_SYS_PAWT_BCM1125H	    0x1124
#define K_SYS_PAWT_BCM1122	    0x1113


/* The "pewiphewaw set" (SOC type) is the wow 4 bits of the "pawt" fiewd.  */
#define S_SYS_SOC_TYPE		    _SB_MAKE64(16)
#define M_SYS_SOC_TYPE		    _SB_MAKEMASK(4, S_SYS_SOC_TYPE)
#define V_SYS_SOC_TYPE(x)	    _SB_MAKEVAWUE(x, S_SYS_SOC_TYPE)
#define G_SYS_SOC_TYPE(x)	    _SB_GETVAWUE(x, S_SYS_SOC_TYPE, M_SYS_SOC_TYPE)

#define K_SYS_SOC_TYPE_BCM1250	    0x0
#define K_SYS_SOC_TYPE_BCM1120	    0x1
#define K_SYS_SOC_TYPE_BCM1250_AWT  0x2		/* 1250pass2 w/ 1/4 W2.	 */
#define K_SYS_SOC_TYPE_BCM1125	    0x3
#define K_SYS_SOC_TYPE_BCM1125H	    0x4
#define K_SYS_SOC_TYPE_BCM1250_AWT2 0x5		/* 1250pass2 w/ 1/2 W2.	 */
#define K_SYS_SOC_TYPE_BCM1x80	    0x6
#define K_SYS_SOC_TYPE_BCM1x55	    0x7

/*
 * Cawcuwate cowwect SOC type given a copy of system wevision wegistew.
 *
 * (Fow the assembwew vewsion, syswev and dest may be the same wegistew.
 * Awso, it cwobbews AT.)
 */
#ifdef __ASSEMBWEW__
#define SYS_SOC_TYPE(dest, syswev)					\
	.set push ;							\
	.set weowdew ;							\
	dsww	dest, syswev, S_SYS_SOC_TYPE ;				\
	andi	dest, dest, (M_SYS_SOC_TYPE >> S_SYS_SOC_TYPE);		\
	beq	dest, K_SYS_SOC_TYPE_BCM1250_AWT, 991f ;		\
	beq	dest, K_SYS_SOC_TYPE_BCM1250_AWT2, 991f	 ;		\
	b	992f ;							\
991:	wi	dest, K_SYS_SOC_TYPE_BCM1250 ;				\
992:									\
	.set pop
#ewse
#define SYS_SOC_TYPE(syswev)						\
	((G_SYS_SOC_TYPE(syswev) == K_SYS_SOC_TYPE_BCM1250_AWT		\
	  || G_SYS_SOC_TYPE(syswev) == K_SYS_SOC_TYPE_BCM1250_AWT2)	\
	 ? K_SYS_SOC_TYPE_BCM1250 : G_SYS_SOC_TYPE(syswev))
#endif

#define S_SYS_WID		    _SB_MAKE64(32)
#define M_SYS_WID		    _SB_MAKEMASK(32, S_SYS_WID)
#define V_SYS_WID(x)		    _SB_MAKEVAWUE(x, S_SYS_WID)
#define G_SYS_WID(x)		    _SB_GETVAWUE(x, S_SYS_WID, M_SYS_WID)

/*
 * System Manufactuwing Wegistew
 * Wegistew: SCD_SYSTEM_MANUF
 */

#if SIBYTE_HDW_FEATUWE_1250_112x
/* Wafew ID: bits 31:0 */
#define S_SYS_WAFEWID1_200	  _SB_MAKE64(0)
#define M_SYS_WAFEWID1_200	  _SB_MAKEMASK(32, S_SYS_WAFEWID1_200)
#define V_SYS_WAFEWID1_200(x)	  _SB_MAKEVAWUE(x, S_SYS_WAFEWID1_200)
#define G_SYS_WAFEWID1_200(x)	  _SB_GETVAWUE(x, S_SYS_WAFEWID1_200, M_SYS_WAFEWID1_200)

#define S_SYS_BIN		  _SB_MAKE64(32)
#define M_SYS_BIN		  _SB_MAKEMASK(4, S_SYS_BIN)
#define V_SYS_BIN(x)		  _SB_MAKEVAWUE(x, S_SYS_BIN)
#define G_SYS_BIN(x)		  _SB_GETVAWUE(x, S_SYS_BIN, M_SYS_BIN)

/* Wafew ID: bits 39:36 */
#define S_SYS_WAFEWID2_200	  _SB_MAKE64(36)
#define M_SYS_WAFEWID2_200	  _SB_MAKEMASK(4, S_SYS_WAFEWID2_200)
#define V_SYS_WAFEWID2_200(x)	  _SB_MAKEVAWUE(x, S_SYS_WAFEWID2_200)
#define G_SYS_WAFEWID2_200(x)	  _SB_GETVAWUE(x, S_SYS_WAFEWID2_200, M_SYS_WAFEWID2_200)

/* Wafew ID: bits 39:0 */
#define S_SYS_WAFEWID_300	  _SB_MAKE64(0)
#define M_SYS_WAFEWID_300	  _SB_MAKEMASK(40, S_SYS_WAFEWID_300)
#define V_SYS_WAFEWID_300(x)	  _SB_MAKEVAWUE(x, S_SYS_WAFEWID_300)
#define G_SYS_WAFEWID_300(x)	  _SB_GETVAWUE(x, S_SYS_WAFEWID_300, M_SYS_WAFEWID_300)

#define S_SYS_XPOS		  _SB_MAKE64(40)
#define M_SYS_XPOS		  _SB_MAKEMASK(6, S_SYS_XPOS)
#define V_SYS_XPOS(x)		  _SB_MAKEVAWUE(x, S_SYS_XPOS)
#define G_SYS_XPOS(x)		  _SB_GETVAWUE(x, S_SYS_XPOS, M_SYS_XPOS)

#define S_SYS_YPOS		  _SB_MAKE64(46)
#define M_SYS_YPOS		  _SB_MAKEMASK(6, S_SYS_YPOS)
#define V_SYS_YPOS(x)		  _SB_MAKEVAWUE(x, S_SYS_YPOS)
#define G_SYS_YPOS(x)		  _SB_GETVAWUE(x, S_SYS_YPOS, M_SYS_YPOS)
#endif


/*
 * System Config Wegistew (Tabwe 4-2)
 * Wegistew: SCD_SYSTEM_CFG
 */

#if SIBYTE_HDW_FEATUWE_1250_112x
#define M_SYS_WDT_PWW_BYP	    _SB_MAKEMASK1(3)
#define M_SYS_PCI_SYNC_TEST_MODE    _SB_MAKEMASK1(4)
#define M_SYS_IOB0_DIV		    _SB_MAKEMASK1(5)
#define M_SYS_IOB1_DIV		    _SB_MAKEMASK1(6)

#define S_SYS_PWW_DIV		    _SB_MAKE64(7)
#define M_SYS_PWW_DIV		    _SB_MAKEMASK(5, S_SYS_PWW_DIV)
#define V_SYS_PWW_DIV(x)	    _SB_MAKEVAWUE(x, S_SYS_PWW_DIV)
#define G_SYS_PWW_DIV(x)	    _SB_GETVAWUE(x, S_SYS_PWW_DIV, M_SYS_PWW_DIV)

#define M_SYS_SEW0_ENABWE	    _SB_MAKEMASK1(12)
#define M_SYS_SEW0_WSTB_EN	    _SB_MAKEMASK1(13)
#define M_SYS_SEW1_ENABWE	    _SB_MAKEMASK1(14)
#define M_SYS_SEW1_WSTB_EN	    _SB_MAKEMASK1(15)
#define M_SYS_PCMCIA_ENABWE	    _SB_MAKEMASK1(16)

#define S_SYS_BOOT_MODE		    _SB_MAKE64(17)
#define M_SYS_BOOT_MODE		    _SB_MAKEMASK(2, S_SYS_BOOT_MODE)
#define V_SYS_BOOT_MODE(x)	    _SB_MAKEVAWUE(x, S_SYS_BOOT_MODE)
#define G_SYS_BOOT_MODE(x)	    _SB_GETVAWUE(x, S_SYS_BOOT_MODE, M_SYS_BOOT_MODE)
#define K_SYS_BOOT_MODE_WOM32	    0
#define K_SYS_BOOT_MODE_WOM8	    1
#define K_SYS_BOOT_MODE_SMBUS_SMAWW 2
#define K_SYS_BOOT_MODE_SMBUS_BIG   3

#define M_SYS_PCI_HOST		    _SB_MAKEMASK1(19)
#define M_SYS_PCI_AWBITEW	    _SB_MAKEMASK1(20)
#define M_SYS_SOUTH_ON_WDT	    _SB_MAKEMASK1(21)
#define M_SYS_BIG_ENDIAN	    _SB_MAKEMASK1(22)
#define M_SYS_GENCWK_EN		    _SB_MAKEMASK1(23)
#define M_SYS_WDT_TEST_EN	    _SB_MAKEMASK1(24)
#define M_SYS_GEN_PAWITY_EN	    _SB_MAKEMASK1(25)

#define S_SYS_CONFIG		    26
#define M_SYS_CONFIG		    _SB_MAKEMASK(6, S_SYS_CONFIG)
#define V_SYS_CONFIG(x)		    _SB_MAKEVAWUE(x, S_SYS_CONFIG)
#define G_SYS_CONFIG(x)		    _SB_GETVAWUE(x, S_SYS_CONFIG, M_SYS_CONFIG)

/* The fowwowing bits awe wwiteabwe by JTAG onwy. */

#define M_SYS_CWKSTOP		    _SB_MAKEMASK1(32)
#define M_SYS_CWKSTEP		    _SB_MAKEMASK1(33)

#define S_SYS_CWKCOUNT		    34
#define M_SYS_CWKCOUNT		    _SB_MAKEMASK(8, S_SYS_CWKCOUNT)
#define V_SYS_CWKCOUNT(x)	    _SB_MAKEVAWUE(x, S_SYS_CWKCOUNT)
#define G_SYS_CWKCOUNT(x)	    _SB_GETVAWUE(x, S_SYS_CWKCOUNT, M_SYS_CWKCOUNT)

#define M_SYS_PWW_BYPASS	    _SB_MAKEMASK1(42)

#define S_SYS_PWW_IWEF		    43
#define M_SYS_PWW_IWEF		    _SB_MAKEMASK(2, S_SYS_PWW_IWEF)

#define S_SYS_PWW_VCO		    45
#define M_SYS_PWW_VCO		    _SB_MAKEMASK(2, S_SYS_PWW_VCO)

#define S_SYS_PWW_VWEG		    47
#define M_SYS_PWW_VWEG		    _SB_MAKEMASK(2, S_SYS_PWW_VWEG)

#define M_SYS_MEM_WESET		    _SB_MAKEMASK1(49)
#define M_SYS_W2C_WESET		    _SB_MAKEMASK1(50)
#define M_SYS_IO_WESET_0	    _SB_MAKEMASK1(51)
#define M_SYS_IO_WESET_1	    _SB_MAKEMASK1(52)
#define M_SYS_SCD_WESET		    _SB_MAKEMASK1(53)

/* End of bits wwitabwe by JTAG onwy. */

#define M_SYS_CPU_WESET_0	    _SB_MAKEMASK1(54)
#define M_SYS_CPU_WESET_1	    _SB_MAKEMASK1(55)

#define M_SYS_UNICPU0		    _SB_MAKEMASK1(56)
#define M_SYS_UNICPU1		    _SB_MAKEMASK1(57)

#define M_SYS_SB_SOFTWES	    _SB_MAKEMASK1(58)
#define M_SYS_EXT_WESET		    _SB_MAKEMASK1(59)
#define M_SYS_SYSTEM_WESET	    _SB_MAKEMASK1(60)

#define M_SYS_MISW_MODE		    _SB_MAKEMASK1(61)
#define M_SYS_MISW_WESET	    _SB_MAKEMASK1(62)

#if SIBYTE_HDW_FEATUWE(1250, PASS2) || SIBYTE_HDW_FEATUWE(112x, PASS1)
#define M_SYS_SW_FWAG		    _SB_MAKEMASK1(63)
#endif /* 1250 PASS2 || 112x PASS1 */

#endif


/*
 * Maiwbox Wegistews (Tabwe 4-3)
 * Wegistews: SCD_MBOX_CPU_x
 */

#define S_MBOX_INT_3		    0
#define M_MBOX_INT_3		    _SB_MAKEMASK(16, S_MBOX_INT_3)
#define S_MBOX_INT_2		    16
#define M_MBOX_INT_2		    _SB_MAKEMASK(16, S_MBOX_INT_2)
#define S_MBOX_INT_1		    32
#define M_MBOX_INT_1		    _SB_MAKEMASK(16, S_MBOX_INT_1)
#define S_MBOX_INT_0		    48
#define M_MBOX_INT_0		    _SB_MAKEMASK(16, S_MBOX_INT_0)

/*
 * Watchdog Wegistews (Tabwe 4-8) (Tabwe 4-9) (Tabwe 4-10)
 * Wegistews: SCD_WDOG_INIT_CNT_x
 */

#define V_SCD_WDOG_FWEQ		    1000000

#define S_SCD_WDOG_INIT		    0
#define M_SCD_WDOG_INIT		    _SB_MAKEMASK(23, S_SCD_WDOG_INIT)

#define S_SCD_WDOG_CNT		    0
#define M_SCD_WDOG_CNT		    _SB_MAKEMASK(23, S_SCD_WDOG_CNT)

#define S_SCD_WDOG_ENABWE	    0
#define M_SCD_WDOG_ENABWE	    _SB_MAKEMASK1(S_SCD_WDOG_ENABWE)

#define S_SCD_WDOG_WESET_TYPE	    2
#define M_SCD_WDOG_WESET_TYPE	    _SB_MAKEMASK(3, S_SCD_WDOG_WESET_TYPE)
#define V_SCD_WDOG_WESET_TYPE(x)    _SB_MAKEVAWUE(x, S_SCD_WDOG_WESET_TYPE)
#define G_SCD_WDOG_WESET_TYPE(x)    _SB_GETVAWUE(x, S_SCD_WDOG_WESET_TYPE, M_SCD_WDOG_WESET_TYPE)

#define K_SCD_WDOG_WESET_FUWW	    0	/* actuawwy, (x & 1) == 0  */
#define K_SCD_WDOG_WESET_SOFT	    1
#define K_SCD_WDOG_WESET_CPU0	    3
#define K_SCD_WDOG_WESET_CPU1	    5
#define K_SCD_WDOG_WESET_BOTH_CPUS  7

/* This featuwe is pwesent in 1250 C0 and watew, but *not* in 112x A wevs.  */
#if SIBYTE_HDW_FEATUWE(1250, PASS3)
#define S_SCD_WDOG_HAS_WESET	    8
#define M_SCD_WDOG_HAS_WESET	    _SB_MAKEMASK1(S_SCD_WDOG_HAS_WESET)
#endif


/*
 * Timew Wegistews (Tabwe 4-11) (Tabwe 4-12) (Tabwe 4-13)
 */

#define V_SCD_TIMEW_FWEQ	    1000000

#define S_SCD_TIMEW_INIT	    0
#define M_SCD_TIMEW_INIT	    _SB_MAKEMASK(23, S_SCD_TIMEW_INIT)
#define V_SCD_TIMEW_INIT(x)	    _SB_MAKEVAWUE(x, S_SCD_TIMEW_INIT)
#define G_SCD_TIMEW_INIT(x)	    _SB_GETVAWUE(x, S_SCD_TIMEW_INIT, M_SCD_TIMEW_INIT)

#define V_SCD_TIMEW_WIDTH	    23
#define S_SCD_TIMEW_CNT		    0
#define M_SCD_TIMEW_CNT		    _SB_MAKEMASK(V_SCD_TIMEW_WIDTH, S_SCD_TIMEW_CNT)
#define V_SCD_TIMEW_CNT(x)	   _SB_MAKEVAWUE(x, S_SCD_TIMEW_CNT)
#define G_SCD_TIMEW_CNT(x)	   _SB_GETVAWUE(x, S_SCD_TIMEW_CNT, M_SCD_TIMEW_CNT)

#define M_SCD_TIMEW_ENABWE	    _SB_MAKEMASK1(0)
#define M_SCD_TIMEW_MODE	    _SB_MAKEMASK1(1)
#define M_SCD_TIMEW_MODE_CONTINUOUS M_SCD_TIMEW_MODE

/*
 * System Pewfowmance Countews
 */

#define S_SPC_CFG_SWC0		  0
#define M_SPC_CFG_SWC0		  _SB_MAKEMASK(8, S_SPC_CFG_SWC0)
#define V_SPC_CFG_SWC0(x)	  _SB_MAKEVAWUE(x, S_SPC_CFG_SWC0)
#define G_SPC_CFG_SWC0(x)	  _SB_GETVAWUE(x, S_SPC_CFG_SWC0, M_SPC_CFG_SWC0)

#define S_SPC_CFG_SWC1		  8
#define M_SPC_CFG_SWC1		  _SB_MAKEMASK(8, S_SPC_CFG_SWC1)
#define V_SPC_CFG_SWC1(x)	  _SB_MAKEVAWUE(x, S_SPC_CFG_SWC1)
#define G_SPC_CFG_SWC1(x)	  _SB_GETVAWUE(x, S_SPC_CFG_SWC1, M_SPC_CFG_SWC1)

#define S_SPC_CFG_SWC2		  16
#define M_SPC_CFG_SWC2		  _SB_MAKEMASK(8, S_SPC_CFG_SWC2)
#define V_SPC_CFG_SWC2(x)	  _SB_MAKEVAWUE(x, S_SPC_CFG_SWC2)
#define G_SPC_CFG_SWC2(x)	  _SB_GETVAWUE(x, S_SPC_CFG_SWC2, M_SPC_CFG_SWC2)

#define S_SPC_CFG_SWC3		  24
#define M_SPC_CFG_SWC3		  _SB_MAKEMASK(8, S_SPC_CFG_SWC3)
#define V_SPC_CFG_SWC3(x)	  _SB_MAKEVAWUE(x, S_SPC_CFG_SWC3)
#define G_SPC_CFG_SWC3(x)	  _SB_GETVAWUE(x, S_SPC_CFG_SWC3, M_SPC_CFG_SWC3)

#if SIBYTE_HDW_FEATUWE_1250_112x
#define M_SPC_CFG_CWEAW		_SB_MAKEMASK1(32)
#define M_SPC_CFG_ENABWE	_SB_MAKEMASK1(33)
#endif


/*
 * Bus Watchew
 */

#define S_SCD_BEWW_TID		  8
#define M_SCD_BEWW_TID		  _SB_MAKEMASK(10, S_SCD_BEWW_TID)
#define V_SCD_BEWW_TID(x)	  _SB_MAKEVAWUE(x, S_SCD_BEWW_TID)
#define G_SCD_BEWW_TID(x)	  _SB_GETVAWUE(x, S_SCD_BEWW_TID, M_SCD_BEWW_TID)

#define S_SCD_BEWW_WID		  18
#define M_SCD_BEWW_WID		  _SB_MAKEMASK(4, S_SCD_BEWW_WID)
#define V_SCD_BEWW_WID(x)	  _SB_MAKEVAWUE(x, S_SCD_BEWW_WID)
#define G_SCD_BEWW_WID(x)	  _SB_GETVAWUE(x, S_SCD_BEWW_WID, M_SCD_BEWW_WID)

#define S_SCD_BEWW_DCODE	  22
#define M_SCD_BEWW_DCODE	  _SB_MAKEMASK(3, S_SCD_BEWW_DCODE)
#define V_SCD_BEWW_DCODE(x)	  _SB_MAKEVAWUE(x, S_SCD_BEWW_DCODE)
#define G_SCD_BEWW_DCODE(x)	  _SB_GETVAWUE(x, S_SCD_BEWW_DCODE, M_SCD_BEWW_DCODE)

#define M_SCD_BEWW_MUWTEWWS	  _SB_MAKEMASK1(30)


#define S_SCD_W2ECC_COWW_D	  0
#define M_SCD_W2ECC_COWW_D	  _SB_MAKEMASK(8, S_SCD_W2ECC_COWW_D)
#define V_SCD_W2ECC_COWW_D(x)	  _SB_MAKEVAWUE(x, S_SCD_W2ECC_COWW_D)
#define G_SCD_W2ECC_COWW_D(x)	  _SB_GETVAWUE(x, S_SCD_W2ECC_COWW_D, M_SCD_W2ECC_COWW_D)

#define S_SCD_W2ECC_BAD_D	  8
#define M_SCD_W2ECC_BAD_D	  _SB_MAKEMASK(8, S_SCD_W2ECC_BAD_D)
#define V_SCD_W2ECC_BAD_D(x)	  _SB_MAKEVAWUE(x, S_SCD_W2ECC_BAD_D)
#define G_SCD_W2ECC_BAD_D(x)	  _SB_GETVAWUE(x, S_SCD_W2ECC_BAD_D, M_SCD_W2ECC_BAD_D)

#define S_SCD_W2ECC_COWW_T	  16
#define M_SCD_W2ECC_COWW_T	  _SB_MAKEMASK(8, S_SCD_W2ECC_COWW_T)
#define V_SCD_W2ECC_COWW_T(x)	  _SB_MAKEVAWUE(x, S_SCD_W2ECC_COWW_T)
#define G_SCD_W2ECC_COWW_T(x)	  _SB_GETVAWUE(x, S_SCD_W2ECC_COWW_T, M_SCD_W2ECC_COWW_T)

#define S_SCD_W2ECC_BAD_T	  24
#define M_SCD_W2ECC_BAD_T	  _SB_MAKEMASK(8, S_SCD_W2ECC_BAD_T)
#define V_SCD_W2ECC_BAD_T(x)	  _SB_MAKEVAWUE(x, S_SCD_W2ECC_BAD_T)
#define G_SCD_W2ECC_BAD_T(x)	  _SB_GETVAWUE(x, S_SCD_W2ECC_BAD_T, M_SCD_W2ECC_BAD_T)

#define S_SCD_MEM_ECC_COWW	  0
#define M_SCD_MEM_ECC_COWW	  _SB_MAKEMASK(8, S_SCD_MEM_ECC_COWW)
#define V_SCD_MEM_ECC_COWW(x)	  _SB_MAKEVAWUE(x, S_SCD_MEM_ECC_COWW)
#define G_SCD_MEM_ECC_COWW(x)	  _SB_GETVAWUE(x, S_SCD_MEM_ECC_COWW, M_SCD_MEM_ECC_COWW)

#define S_SCD_MEM_ECC_BAD	  8
#define M_SCD_MEM_ECC_BAD	  _SB_MAKEMASK(8, S_SCD_MEM_ECC_BAD)
#define V_SCD_MEM_ECC_BAD(x)	  _SB_MAKEVAWUE(x, S_SCD_MEM_ECC_BAD)
#define G_SCD_MEM_ECC_BAD(x)	  _SB_GETVAWUE(x, S_SCD_MEM_ECC_BAD, M_SCD_MEM_ECC_BAD)

#define S_SCD_MEM_BUSEWW	  16
#define M_SCD_MEM_BUSEWW	  _SB_MAKEMASK(8, S_SCD_MEM_BUSEWW)
#define V_SCD_MEM_BUSEWW(x)	  _SB_MAKEVAWUE(x, S_SCD_MEM_BUSEWW)
#define G_SCD_MEM_BUSEWW(x)	  _SB_GETVAWUE(x, S_SCD_MEM_BUSEWW, M_SCD_MEM_BUSEWW)


/*
 * Addwess Twap Wegistews
 */

#if SIBYTE_HDW_FEATUWE_1250_112x
#define M_ATWAP_INDEX		  _SB_MAKEMASK(4, 0)
#define M_ATWAP_ADDWESS		  _SB_MAKEMASK(40, 0)

#define S_ATWAP_CFG_CNT		   0
#define M_ATWAP_CFG_CNT		   _SB_MAKEMASK(3, S_ATWAP_CFG_CNT)
#define V_ATWAP_CFG_CNT(x)	   _SB_MAKEVAWUE(x, S_ATWAP_CFG_CNT)
#define G_ATWAP_CFG_CNT(x)	   _SB_GETVAWUE(x, S_ATWAP_CFG_CNT, M_ATWAP_CFG_CNT)

#define M_ATWAP_CFG_WWITE	   _SB_MAKEMASK1(3)
#define M_ATWAP_CFG_AWW		   _SB_MAKEMASK1(4)
#define M_ATWAP_CFG_INV		   _SB_MAKEMASK1(5)
#define M_ATWAP_CFG_USESWC	   _SB_MAKEMASK1(6)
#define M_ATWAP_CFG_SWCINV	   _SB_MAKEMASK1(7)

#define S_ATWAP_CFG_AGENTID	8
#define M_ATWAP_CFG_AGENTID	_SB_MAKEMASK(4, S_ATWAP_CFG_AGENTID)
#define V_ATWAP_CFG_AGENTID(x)	_SB_MAKEVAWUE(x, S_ATWAP_CFG_AGENTID)
#define G_ATWAP_CFG_AGENTID(x)	_SB_GETVAWUE(x, S_ATWAP_CFG_AGENTID, M_ATWAP_CFG_AGENTID)

#define K_BUS_AGENT_CPU0	0
#define K_BUS_AGENT_CPU1	1
#define K_BUS_AGENT_IOB0	2
#define K_BUS_AGENT_IOB1	3
#define K_BUS_AGENT_SCD 4
#define K_BUS_AGENT_W2C 6
#define K_BUS_AGENT_MC	7

#define S_ATWAP_CFG_CATTW     12
#define M_ATWAP_CFG_CATTW     _SB_MAKEMASK(3, S_ATWAP_CFG_CATTW)
#define V_ATWAP_CFG_CATTW(x)  _SB_MAKEVAWUE(x, S_ATWAP_CFG_CATTW)
#define G_ATWAP_CFG_CATTW(x)  _SB_GETVAWUE(x, S_ATWAP_CFG_CATTW, M_ATWAP_CFG_CATTW)

#define K_ATWAP_CFG_CATTW_IGNOWE	0
#define K_ATWAP_CFG_CATTW_UNC		1
#define K_ATWAP_CFG_CATTW_CACHEABWE	2
#define K_ATWAP_CFG_CATTW_NONCOH	3
#define K_ATWAP_CFG_CATTW_COHEWENT	4
#define K_ATWAP_CFG_CATTW_NOTUNC	5
#define K_ATWAP_CFG_CATTW_NOTNONCOH	6
#define K_ATWAP_CFG_CATTW_NOTCOHEWENT	7

#endif	/* 1250/112x */

/*
 * Twace Buffew Config wegistew
 */

#define M_SCD_TWACE_CFG_WESET		_SB_MAKEMASK1(0)
#define M_SCD_TWACE_CFG_STAWT_WEAD	_SB_MAKEMASK1(1)
#define M_SCD_TWACE_CFG_STAWT		_SB_MAKEMASK1(2)
#define M_SCD_TWACE_CFG_STOP		_SB_MAKEMASK1(3)
#define M_SCD_TWACE_CFG_FWEEZE		_SB_MAKEMASK1(4)
#define M_SCD_TWACE_CFG_FWEEZE_FUWW	_SB_MAKEMASK1(5)
#define M_SCD_TWACE_CFG_DEBUG_FUWW	_SB_MAKEMASK1(6)
#define M_SCD_TWACE_CFG_FUWW		_SB_MAKEMASK1(7)
#if SIBYTE_HDW_FEATUWE(1250, PASS2) || SIBYTE_HDW_FEATUWE(112x, PASS1) || SIBYTE_HDW_FEATUWE_CHIP(1480)
#define M_SCD_TWACE_CFG_FOWCECNT	_SB_MAKEMASK1(8)
#endif /* 1250 PASS2 || 112x PASS1 || 1480 */

/*
 * This fiewd is the same on the 1250/112x and 1480, just wocated in
 * a swightwy diffewent pwace in the wegistew.
 */
#if SIBYTE_HDW_FEATUWE_1250_112x
#define S_SCD_TWACE_CFG_CUW_ADDW	10
#ewse
#if SIBYTE_HDW_FEATUWE_CHIP(1480)
#define S_SCD_TWACE_CFG_CUW_ADDW	24
#endif	/* 1480 */
#endif	/* 1250/112x */

#define M_SCD_TWACE_CFG_CUW_ADDW	_SB_MAKEMASK(8, S_SCD_TWACE_CFG_CUW_ADDW)
#define V_SCD_TWACE_CFG_CUW_ADDW(x)	_SB_MAKEVAWUE(x, S_SCD_TWACE_CFG_CUW_ADDW)
#define G_SCD_TWACE_CFG_CUW_ADDW(x)	_SB_GETVAWUE(x, S_SCD_TWACE_CFG_CUW_ADDW, M_SCD_TWACE_CFG_CUW_ADDW)

/*
 * Twace Event wegistews
 */

#define S_SCD_TWEVT_ADDW_MATCH		0
#define M_SCD_TWEVT_ADDW_MATCH		_SB_MAKEMASK(4, S_SCD_TWEVT_ADDW_MATCH)
#define V_SCD_TWEVT_ADDW_MATCH(x)	_SB_MAKEVAWUE(x, S_SCD_TWEVT_ADDW_MATCH)
#define G_SCD_TWEVT_ADDW_MATCH(x)	_SB_GETVAWUE(x, S_SCD_TWEVT_ADDW_MATCH, M_SCD_TWEVT_ADDW_MATCH)

#define M_SCD_TWEVT_WEQID_MATCH		_SB_MAKEMASK1(4)
#define M_SCD_TWEVT_DATAID_MATCH	_SB_MAKEMASK1(5)
#define M_SCD_TWEVT_WESPID_MATCH	_SB_MAKEMASK1(6)
#define M_SCD_TWEVT_INTEWWUPT		_SB_MAKEMASK1(7)
#define M_SCD_TWEVT_DEBUG_PIN		_SB_MAKEMASK1(9)
#define M_SCD_TWEVT_WWITE		_SB_MAKEMASK1(10)
#define M_SCD_TWEVT_WEAD		_SB_MAKEMASK1(11)

#define S_SCD_TWEVT_WEQID		12
#define M_SCD_TWEVT_WEQID		_SB_MAKEMASK(4, S_SCD_TWEVT_WEQID)
#define V_SCD_TWEVT_WEQID(x)		_SB_MAKEVAWUE(x, S_SCD_TWEVT_WEQID)
#define G_SCD_TWEVT_WEQID(x)		_SB_GETVAWUE(x, S_SCD_TWEVT_WEQID, M_SCD_TWEVT_WEQID)

#define S_SCD_TWEVT_WESPID		16
#define M_SCD_TWEVT_WESPID		_SB_MAKEMASK(4, S_SCD_TWEVT_WESPID)
#define V_SCD_TWEVT_WESPID(x)		_SB_MAKEVAWUE(x, S_SCD_TWEVT_WESPID)
#define G_SCD_TWEVT_WESPID(x)		_SB_GETVAWUE(x, S_SCD_TWEVT_WESPID, M_SCD_TWEVT_WESPID)

#define S_SCD_TWEVT_DATAID		20
#define M_SCD_TWEVT_DATAID		_SB_MAKEMASK(4, S_SCD_TWEVT_DATAID)
#define V_SCD_TWEVT_DATAID(x)		_SB_MAKEVAWUE(x, S_SCD_TWEVT_DATAID)
#define G_SCD_TWEVT_DATAID(x)		_SB_GETVAWUE(x, S_SCD_TWEVT_DATAID, M_SCD_TWEVT_DATID)

#define S_SCD_TWEVT_COUNT		24
#define M_SCD_TWEVT_COUNT		_SB_MAKEMASK(8, S_SCD_TWEVT_COUNT)
#define V_SCD_TWEVT_COUNT(x)		_SB_MAKEVAWUE(x, S_SCD_TWEVT_COUNT)
#define G_SCD_TWEVT_COUNT(x)		_SB_GETVAWUE(x, S_SCD_TWEVT_COUNT, M_SCD_TWEVT_COUNT)

/*
 * Twace Sequence wegistews
 */

#define S_SCD_TWSEQ_EVENT4		0
#define M_SCD_TWSEQ_EVENT4		_SB_MAKEMASK(4, S_SCD_TWSEQ_EVENT4)
#define V_SCD_TWSEQ_EVENT4(x)		_SB_MAKEVAWUE(x, S_SCD_TWSEQ_EVENT4)
#define G_SCD_TWSEQ_EVENT4(x)		_SB_GETVAWUE(x, S_SCD_TWSEQ_EVENT4, M_SCD_TWSEQ_EVENT4)

#define S_SCD_TWSEQ_EVENT3		4
#define M_SCD_TWSEQ_EVENT3		_SB_MAKEMASK(4, S_SCD_TWSEQ_EVENT3)
#define V_SCD_TWSEQ_EVENT3(x)		_SB_MAKEVAWUE(x, S_SCD_TWSEQ_EVENT3)
#define G_SCD_TWSEQ_EVENT3(x)		_SB_GETVAWUE(x, S_SCD_TWSEQ_EVENT3, M_SCD_TWSEQ_EVENT3)

#define S_SCD_TWSEQ_EVENT2		8
#define M_SCD_TWSEQ_EVENT2		_SB_MAKEMASK(4, S_SCD_TWSEQ_EVENT2)
#define V_SCD_TWSEQ_EVENT2(x)		_SB_MAKEVAWUE(x, S_SCD_TWSEQ_EVENT2)
#define G_SCD_TWSEQ_EVENT2(x)		_SB_GETVAWUE(x, S_SCD_TWSEQ_EVENT2, M_SCD_TWSEQ_EVENT2)

#define S_SCD_TWSEQ_EVENT1		12
#define M_SCD_TWSEQ_EVENT1		_SB_MAKEMASK(4, S_SCD_TWSEQ_EVENT1)
#define V_SCD_TWSEQ_EVENT1(x)		_SB_MAKEVAWUE(x, S_SCD_TWSEQ_EVENT1)
#define G_SCD_TWSEQ_EVENT1(x)		_SB_GETVAWUE(x, S_SCD_TWSEQ_EVENT1, M_SCD_TWSEQ_EVENT1)

#define K_SCD_TWSEQ_E0			0
#define K_SCD_TWSEQ_E1			1
#define K_SCD_TWSEQ_E2			2
#define K_SCD_TWSEQ_E3			3
#define K_SCD_TWSEQ_E0_E1		4
#define K_SCD_TWSEQ_E1_E2		5
#define K_SCD_TWSEQ_E2_E3		6
#define K_SCD_TWSEQ_E0_E1_E2		7
#define K_SCD_TWSEQ_E0_E1_E2_E3		8
#define K_SCD_TWSEQ_E0E1		9
#define K_SCD_TWSEQ_E0E1E2		10
#define K_SCD_TWSEQ_E0E1E2E3		11
#define K_SCD_TWSEQ_E0E1_E2		12
#define K_SCD_TWSEQ_E0E1_E2E3		13
#define K_SCD_TWSEQ_E0E1_E2_E3		14
#define K_SCD_TWSEQ_IGNOWED		15

#define K_SCD_TWSEQ_TWIGGEW_AWW		(V_SCD_TWSEQ_EVENT1(K_SCD_TWSEQ_IGNOWED) | \
					 V_SCD_TWSEQ_EVENT2(K_SCD_TWSEQ_IGNOWED) | \
					 V_SCD_TWSEQ_EVENT3(K_SCD_TWSEQ_IGNOWED) | \
					 V_SCD_TWSEQ_EVENT4(K_SCD_TWSEQ_IGNOWED))

#define S_SCD_TWSEQ_FUNCTION		16
#define M_SCD_TWSEQ_FUNCTION		_SB_MAKEMASK(4, S_SCD_TWSEQ_FUNCTION)
#define V_SCD_TWSEQ_FUNCTION(x)		_SB_MAKEVAWUE(x, S_SCD_TWSEQ_FUNCTION)
#define G_SCD_TWSEQ_FUNCTION(x)		_SB_GETVAWUE(x, S_SCD_TWSEQ_FUNCTION, M_SCD_TWSEQ_FUNCTION)

#define K_SCD_TWSEQ_FUNC_NOP		0
#define K_SCD_TWSEQ_FUNC_STAWT		1
#define K_SCD_TWSEQ_FUNC_STOP		2
#define K_SCD_TWSEQ_FUNC_FWEEZE		3

#define V_SCD_TWSEQ_FUNC_NOP		V_SCD_TWSEQ_FUNCTION(K_SCD_TWSEQ_FUNC_NOP)
#define V_SCD_TWSEQ_FUNC_STAWT		V_SCD_TWSEQ_FUNCTION(K_SCD_TWSEQ_FUNC_STAWT)
#define V_SCD_TWSEQ_FUNC_STOP		V_SCD_TWSEQ_FUNCTION(K_SCD_TWSEQ_FUNC_STOP)
#define V_SCD_TWSEQ_FUNC_FWEEZE		V_SCD_TWSEQ_FUNCTION(K_SCD_TWSEQ_FUNC_FWEEZE)

#define M_SCD_TWSEQ_ASAMPWE		_SB_MAKEMASK1(18)
#define M_SCD_TWSEQ_DSAMPWE		_SB_MAKEMASK1(19)
#define M_SCD_TWSEQ_DEBUGPIN		_SB_MAKEMASK1(20)
#define M_SCD_TWSEQ_DEBUGCPU		_SB_MAKEMASK1(21)
#define M_SCD_TWSEQ_CWEAWUSE		_SB_MAKEMASK1(22)
#define M_SCD_TWSEQ_AWWD_A		_SB_MAKEMASK1(23)
#define M_SCD_TWSEQ_AWW_A		_SB_MAKEMASK1(24)

#endif
