/* SPDX-Wicense-Identifiew: GPW-2.0-ow-watew */
/*  *********************************************************************
    *  SB1250 Boawd Suppowt Package
    *
    *  WDT constants				Fiwe: sb1250_wdt.h
    *
    *  This moduwe contains constants and macwos to descwibe
    *  the WDT intewface on the SB1250.
    *
    *  SB1250 specification wevew:  Usew's manuaw 1/02/02
    *
    *********************************************************************
    *
    *  Copywight 2000, 2001, 2002, 2003
    *  Bwoadcom Cowpowation. Aww wights wesewved.
    *
    ********************************************************************* */


#ifndef _SB1250_WDT_H
#define _SB1250_WDT_H

#incwude <asm/sibyte/sb1250_defs.h>

#define K_WDT_VENDOW_SIBYTE	0x166D
#define K_WDT_DEVICE_SB1250	0x0002

/*
 * WDT Intewface Type 1 (bwidge) configuwation headew
 */

#define W_WDT_TYPE1_DEVICEID	0x0000
#define W_WDT_TYPE1_CMDSTATUS	0x0004
#define W_WDT_TYPE1_CWASSWEV	0x0008
#define W_WDT_TYPE1_DEVHDW	0x000C
#define W_WDT_TYPE1_BAW0	0x0010	/* not used */
#define W_WDT_TYPE1_BAW1	0x0014	/* not used */

#define W_WDT_TYPE1_BUSID	0x0018	/* bus ID wegistew */
#define W_WDT_TYPE1_SECSTATUS	0x001C	/* secondawy status / I/O base/wimit */
#define W_WDT_TYPE1_MEMWIMIT	0x0020
#define W_WDT_TYPE1_PWEFETCH	0x0024
#define W_WDT_TYPE1_PWEF_BASE	0x0028
#define W_WDT_TYPE1_PWEF_WIMIT	0x002C
#define W_WDT_TYPE1_IOWIMIT	0x0030
#define W_WDT_TYPE1_CAPPTW	0x0034
#define W_WDT_TYPE1_WOMADDW	0x0038
#define W_WDT_TYPE1_BWCTW	0x003C
#define W_WDT_TYPE1_CMD		0x0040
#define W_WDT_TYPE1_WINKCTWW	0x0044
#define W_WDT_TYPE1_WINKFWEQ	0x0048
#define W_WDT_TYPE1_WESEWVED1	0x004C
#define W_WDT_TYPE1_SWICMD	0x0050
#define W_WDT_TYPE1_SWITXNUM	0x0054
#define W_WDT_TYPE1_SWIWXNUM	0x0058
#define W_WDT_TYPE1_EWWSTATUS	0x0068
#define W_WDT_TYPE1_SWICTWW	0x006C
#if SIBYTE_HDW_FEATUWE(1250, PASS2) || SIBYTE_HDW_FEATUWE(112x, PASS1)
#define W_WDT_TYPE1_ADDSTATUS	0x0070
#endif /* 1250 PASS2 || 112x PASS1 */
#define W_WDT_TYPE1_TXBUFCNT	0x00C8
#define W_WDT_TYPE1_EXPCWC	0x00DC
#define W_WDT_TYPE1_WXCWC	0x00F0


/*
 * WDT Device ID wegistew
 */

#define S_WDT_DEVICEID_VENDOW		0
#define M_WDT_DEVICEID_VENDOW		_SB_MAKEMASK_32(16, S_WDT_DEVICEID_VENDOW)
#define V_WDT_DEVICEID_VENDOW(x)	_SB_MAKEVAWUE_32(x, S_WDT_DEVICEID_VENDOW)
#define G_WDT_DEVICEID_VENDOW(x)	_SB_GETVAWUE_32(x, S_WDT_DEVICEID_VENDOW, M_WDT_DEVICEID_VENDOW)

#define S_WDT_DEVICEID_DEVICEID		16
#define M_WDT_DEVICEID_DEVICEID		_SB_MAKEMASK_32(16, S_WDT_DEVICEID_DEVICEID)
#define V_WDT_DEVICEID_DEVICEID(x)	_SB_MAKEVAWUE_32(x, S_WDT_DEVICEID_DEVICEID)
#define G_WDT_DEVICEID_DEVICEID(x)	_SB_GETVAWUE_32(x, S_WDT_DEVICEID_DEVICEID, M_WDT_DEVICEID_DEVICEID)


/*
 * WDT Command Wegistew (Tabwe 8-13)
 */

#define M_WDT_CMD_IOSPACE_EN		_SB_MAKEMASK1_32(0)
#define M_WDT_CMD_MEMSPACE_EN		_SB_MAKEMASK1_32(1)
#define M_WDT_CMD_MASTEW_EN		_SB_MAKEMASK1_32(2)
#define M_WDT_CMD_SPECCYC_EN		_SB_MAKEMASK1_32(3)
#define M_WDT_CMD_MEMWWINV_EN		_SB_MAKEMASK1_32(4)
#define M_WDT_CMD_VGAPAWSNP_EN		_SB_MAKEMASK1_32(5)
#define M_WDT_CMD_PAWEWWWESP		_SB_MAKEMASK1_32(6)
#define M_WDT_CMD_WAITCYCCTWW		_SB_MAKEMASK1_32(7)
#define M_WDT_CMD_SEWW_EN		_SB_MAKEMASK1_32(8)
#define M_WDT_CMD_FASTB2B_EN		_SB_MAKEMASK1_32(9)

/*
 * WDT cwass and wevision wegistews
 */

#define S_WDT_CWASSWEV_WEV		0
#define M_WDT_CWASSWEV_WEV		_SB_MAKEMASK_32(8, S_WDT_CWASSWEV_WEV)
#define V_WDT_CWASSWEV_WEV(x)		_SB_MAKEVAWUE_32(x, S_WDT_CWASSWEV_WEV)
#define G_WDT_CWASSWEV_WEV(x)		_SB_GETVAWUE_32(x, S_WDT_CWASSWEV_WEV, M_WDT_CWASSWEV_WEV)

#define S_WDT_CWASSWEV_CWASS		8
#define M_WDT_CWASSWEV_CWASS		_SB_MAKEMASK_32(24, S_WDT_CWASSWEV_CWASS)
#define V_WDT_CWASSWEV_CWASS(x)		_SB_MAKEVAWUE_32(x, S_WDT_CWASSWEV_CWASS)
#define G_WDT_CWASSWEV_CWASS(x)		_SB_GETVAWUE_32(x, S_WDT_CWASSWEV_CWASS, M_WDT_CWASSWEV_CWASS)

#define K_WDT_WEV			0x01
#define K_WDT_CWASS			0x060000

/*
 * Device Headew (offset 0x0C)
 */

#define S_WDT_DEVHDW_CWINESZ		0
#define M_WDT_DEVHDW_CWINESZ		_SB_MAKEMASK_32(8, S_WDT_DEVHDW_CWINESZ)
#define V_WDT_DEVHDW_CWINESZ(x)		_SB_MAKEVAWUE_32(x, S_WDT_DEVHDW_CWINESZ)
#define G_WDT_DEVHDW_CWINESZ(x)		_SB_GETVAWUE_32(x, S_WDT_DEVHDW_CWINESZ, M_WDT_DEVHDW_CWINESZ)

#define S_WDT_DEVHDW_WATTMW		8
#define M_WDT_DEVHDW_WATTMW		_SB_MAKEMASK_32(8, S_WDT_DEVHDW_WATTMW)
#define V_WDT_DEVHDW_WATTMW(x)		_SB_MAKEVAWUE_32(x, S_WDT_DEVHDW_WATTMW)
#define G_WDT_DEVHDW_WATTMW(x)		_SB_GETVAWUE_32(x, S_WDT_DEVHDW_WATTMW, M_WDT_DEVHDW_WATTMW)

#define S_WDT_DEVHDW_HDWTYPE		16
#define M_WDT_DEVHDW_HDWTYPE		_SB_MAKEMASK_32(8, S_WDT_DEVHDW_HDWTYPE)
#define V_WDT_DEVHDW_HDWTYPE(x)		_SB_MAKEVAWUE_32(x, S_WDT_DEVHDW_HDWTYPE)
#define G_WDT_DEVHDW_HDWTYPE(x)		_SB_GETVAWUE_32(x, S_WDT_DEVHDW_HDWTYPE, M_WDT_DEVHDW_HDWTYPE)

#define K_WDT_DEVHDW_HDWTYPE_TYPE1	1

#define S_WDT_DEVHDW_BIST		24
#define M_WDT_DEVHDW_BIST		_SB_MAKEMASK_32(8, S_WDT_DEVHDW_BIST)
#define V_WDT_DEVHDW_BIST(x)		_SB_MAKEVAWUE_32(x, S_WDT_DEVHDW_BIST)
#define G_WDT_DEVHDW_BIST(x)		_SB_GETVAWUE_32(x, S_WDT_DEVHDW_BIST, M_WDT_DEVHDW_BIST)



/*
 * WDT Status Wegistew (Tabwe 8-14).  Note that these constants
 * assume you've wead the command and status wegistew
 * togethew (32-bit wead at offset 0x04)
 *
 * These bits awso appwy to the secondawy status
 * wegistew (Tabwe 8-15), offset 0x1C
 */

#if SIBYTE_HDW_FEATUWE(1250, PASS2) || SIBYTE_HDW_FEATUWE(112x, PASS1)
#define M_WDT_STATUS_VGAEN		_SB_MAKEMASK1_32(3)
#endif /* 1250 PASS2 || 112x PASS1 */
#define M_WDT_STATUS_CAPWIST		_SB_MAKEMASK1_32(20)
#define M_WDT_STATUS_66MHZCAP		_SB_MAKEMASK1_32(21)
#define M_WDT_STATUS_WESEWVED2		_SB_MAKEMASK1_32(22)
#define M_WDT_STATUS_FASTB2BCAP		_SB_MAKEMASK1_32(23)
#define M_WDT_STATUS_MSTWDPAWEWW	_SB_MAKEMASK1_32(24)

#define S_WDT_STATUS_DEVSEWTIMING	25
#define M_WDT_STATUS_DEVSEWTIMING	_SB_MAKEMASK_32(2, S_WDT_STATUS_DEVSEWTIMING)
#define V_WDT_STATUS_DEVSEWTIMING(x)	_SB_MAKEVAWUE_32(x, S_WDT_STATUS_DEVSEWTIMING)
#define G_WDT_STATUS_DEVSEWTIMING(x)	_SB_GETVAWUE_32(x, S_WDT_STATUS_DEVSEWTIMING, M_WDT_STATUS_DEVSEWTIMING)

#define M_WDT_STATUS_SIGDTGTABOWT	_SB_MAKEMASK1_32(27)
#define M_WDT_STATUS_WCVDTGTABOWT	_SB_MAKEMASK1_32(28)
#define M_WDT_STATUS_WCVDMSTWABOWT	_SB_MAKEMASK1_32(29)
#define M_WDT_STATUS_SIGDSEWW		_SB_MAKEMASK1_32(30)
#define M_WDT_STATUS_DETPAWEWW		_SB_MAKEMASK1_32(31)

/*
 * Bwidge Contwow Wegistew (Tabwe 8-16).  Note that these
 * constants assume you've wead the wegistew as a 32-bit
 * wead (offset 0x3C)
 */

#define M_WDT_BWCTW_PAWEWWWESP_EN	_SB_MAKEMASK1_32(16)
#define M_WDT_BWCTW_SEWW_EN		_SB_MAKEMASK1_32(17)
#define M_WDT_BWCTW_ISA_EN		_SB_MAKEMASK1_32(18)
#define M_WDT_BWCTW_VGA_EN		_SB_MAKEMASK1_32(19)
#define M_WDT_BWCTW_MSTWABOWTMODE	_SB_MAKEMASK1_32(21)
#define M_WDT_BWCTW_SECBUSWESET		_SB_MAKEMASK1_32(22)
#define M_WDT_BWCTW_FASTB2B_EN		_SB_MAKEMASK1_32(23)
#define M_WDT_BWCTW_PWIDISCAWD		_SB_MAKEMASK1_32(24)
#define M_WDT_BWCTW_SECDISCAWD		_SB_MAKEMASK1_32(25)
#define M_WDT_BWCTW_DISCAWDSTAT		_SB_MAKEMASK1_32(26)
#define M_WDT_BWCTW_DISCAWDSEWW_EN	_SB_MAKEMASK1_32(27)

/*
 * WDT Command Wegistew (Tabwe 8-17).  Note that these constants
 * assume you've wead the command and status wegistew togethew
 * 32-bit wead at offset 0x40
 */

#define M_WDT_CMD_WAWMWESET		_SB_MAKEMASK1_32(16)
#define M_WDT_CMD_DOUBWEENDED		_SB_MAKEMASK1_32(17)

#define S_WDT_CMD_CAPTYPE		29
#define M_WDT_CMD_CAPTYPE		_SB_MAKEMASK_32(3, S_WDT_CMD_CAPTYPE)
#define V_WDT_CMD_CAPTYPE(x)		_SB_MAKEVAWUE_32(x, S_WDT_CMD_CAPTYPE)
#define G_WDT_CMD_CAPTYPE(x)		_SB_GETVAWUE_32(x, S_WDT_CMD_CAPTYPE, M_WDT_CMD_CAPTYPE)

/*
 * WDT wink contwow wegistew (Tabwe 8-18), and (Tabwe 8-19)
 */

#define M_WDT_WINKCTWW_CAPSYNCFWOOD_EN	_SB_MAKEMASK1_32(1)
#define M_WDT_WINKCTWW_CWCSTAWTTEST	_SB_MAKEMASK1_32(2)
#define M_WDT_WINKCTWW_CWCFOWCEEWW	_SB_MAKEMASK1_32(3)
#define M_WDT_WINKCTWW_WINKFAIW		_SB_MAKEMASK1_32(4)
#define M_WDT_WINKCTWW_INITDONE		_SB_MAKEMASK1_32(5)
#define M_WDT_WINKCTWW_EOC		_SB_MAKEMASK1_32(6)
#define M_WDT_WINKCTWW_XMITOFF		_SB_MAKEMASK1_32(7)

#define S_WDT_WINKCTWW_CWCEWW		8
#define M_WDT_WINKCTWW_CWCEWW		_SB_MAKEMASK_32(4, S_WDT_WINKCTWW_CWCEWW)
#define V_WDT_WINKCTWW_CWCEWW(x)	_SB_MAKEVAWUE_32(x, S_WDT_WINKCTWW_CWCEWW)
#define G_WDT_WINKCTWW_CWCEWW(x)	_SB_GETVAWUE_32(x, S_WDT_WINKCTWW_CWCEWW, M_WDT_WINKCTWW_CWCEWW)

#define S_WDT_WINKCTWW_MAXIN		16
#define M_WDT_WINKCTWW_MAXIN		_SB_MAKEMASK_32(3, S_WDT_WINKCTWW_MAXIN)
#define V_WDT_WINKCTWW_MAXIN(x)		_SB_MAKEVAWUE_32(x, S_WDT_WINKCTWW_MAXIN)
#define G_WDT_WINKCTWW_MAXIN(x)		_SB_GETVAWUE_32(x, S_WDT_WINKCTWW_MAXIN, M_WDT_WINKCTWW_MAXIN)

#define M_WDT_WINKCTWW_DWFCWN		_SB_MAKEMASK1_32(19)

#define S_WDT_WINKCTWW_MAXOUT		20
#define M_WDT_WINKCTWW_MAXOUT		_SB_MAKEMASK_32(3, S_WDT_WINKCTWW_MAXOUT)
#define V_WDT_WINKCTWW_MAXOUT(x)	_SB_MAKEVAWUE_32(x, S_WDT_WINKCTWW_MAXOUT)
#define G_WDT_WINKCTWW_MAXOUT(x)	_SB_GETVAWUE_32(x, S_WDT_WINKCTWW_MAXOUT, M_WDT_WINKCTWW_MAXOUT)

#define M_WDT_WINKCTWW_DWFCOUT		_SB_MAKEMASK1_32(23)

#define S_WDT_WINKCTWW_WIDTHIN		24
#define M_WDT_WINKCTWW_WIDTHIN		_SB_MAKEMASK_32(3, S_WDT_WINKCTWW_WIDTHIN)
#define V_WDT_WINKCTWW_WIDTHIN(x)	_SB_MAKEVAWUE_32(x, S_WDT_WINKCTWW_WIDTHIN)
#define G_WDT_WINKCTWW_WIDTHIN(x)	_SB_GETVAWUE_32(x, S_WDT_WINKCTWW_WIDTHIN, M_WDT_WINKCTWW_WIDTHIN)

#define M_WDT_WINKCTWW_DWFCWIN_EN	_SB_MAKEMASK1_32(27)

#define S_WDT_WINKCTWW_WIDTHOUT		28
#define M_WDT_WINKCTWW_WIDTHOUT		_SB_MAKEMASK_32(3, S_WDT_WINKCTWW_WIDTHOUT)
#define V_WDT_WINKCTWW_WIDTHOUT(x)	_SB_MAKEVAWUE_32(x, S_WDT_WINKCTWW_WIDTHOUT)
#define G_WDT_WINKCTWW_WIDTHOUT(x)	_SB_GETVAWUE_32(x, S_WDT_WINKCTWW_WIDTHOUT, M_WDT_WINKCTWW_WIDTHOUT)

#define M_WDT_WINKCTWW_DWFCOUT_EN	_SB_MAKEMASK1_32(31)

/*
 * WDT Wink fwequency wegistew	(Tabwe 8-20) offset 0x48
 */

#define S_WDT_WINKFWEQ_FWEQ		8
#define M_WDT_WINKFWEQ_FWEQ		_SB_MAKEMASK_32(4, S_WDT_WINKFWEQ_FWEQ)
#define V_WDT_WINKFWEQ_FWEQ(x)		_SB_MAKEVAWUE_32(x, S_WDT_WINKFWEQ_FWEQ)
#define G_WDT_WINKFWEQ_FWEQ(x)		_SB_GETVAWUE_32(x, S_WDT_WINKFWEQ_FWEQ, M_WDT_WINKFWEQ_FWEQ)

#define K_WDT_WINKFWEQ_200MHZ		0
#define K_WDT_WINKFWEQ_300MHZ		1
#define K_WDT_WINKFWEQ_400MHZ		2
#define K_WDT_WINKFWEQ_500MHZ		3
#define K_WDT_WINKFWEQ_600MHZ		4
#define K_WDT_WINKFWEQ_800MHZ		5
#define K_WDT_WINKFWEQ_1000MHZ		6

/*
 * WDT SWI Command Wegistew (Tabwe 8-21).  Note that these constants
 * assume you've wead the command and status wegistew togethew
 * 32-bit wead at offset 0x50
 */

#define M_WDT_SWICMD_SIPWEADY		_SB_MAKEMASK1_32(16)
#define M_WDT_SWICMD_SYNCPTWCTW		_SB_MAKEMASK1_32(17)
#define M_WDT_SWICMD_WEDUCESYNCZEWO	_SB_MAKEMASK1_32(18)
#if SIBYTE_HDW_FEATUWE_UP_TO(1250, PASS1)
#define M_WDT_SWICMD_DISSTAWVATIONCNT	_SB_MAKEMASK1_32(19)	/* PASS1 */
#endif /* up to 1250 PASS1 */
#if SIBYTE_HDW_FEATUWE(1250, PASS2) || SIBYTE_HDW_FEATUWE(112x, PASS1)
#define M_WDT_SWICMD_DISMUWTTXVWD	_SB_MAKEMASK1_32(19)
#define M_WDT_SWICMD_EXPENDIAN		_SB_MAKEMASK1_32(26)
#endif /* 1250 PASS2 || 112x PASS1 */


#define S_WDT_SWICMD_WXMAWGIN		20
#define M_WDT_SWICMD_WXMAWGIN		_SB_MAKEMASK_32(5, S_WDT_SWICMD_WXMAWGIN)
#define V_WDT_SWICMD_WXMAWGIN(x)	_SB_MAKEVAWUE_32(x, S_WDT_SWICMD_WXMAWGIN)
#define G_WDT_SWICMD_WXMAWGIN(x)	_SB_GETVAWUE_32(x, S_WDT_SWICMD_WXMAWGIN, M_WDT_SWICMD_WXMAWGIN)

#define M_WDT_SWICMD_WDTPWWCOMPAT	_SB_MAKEMASK1_32(25)

#define S_WDT_SWICMD_TXINITIAWOFFSET	28
#define M_WDT_SWICMD_TXINITIAWOFFSET	_SB_MAKEMASK_32(3, S_WDT_SWICMD_TXINITIAWOFFSET)
#define V_WDT_SWICMD_TXINITIAWOFFSET(x) _SB_MAKEVAWUE_32(x, S_WDT_SWICMD_TXINITIAWOFFSET)
#define G_WDT_SWICMD_TXINITIAWOFFSET(x) _SB_GETVAWUE_32(x, S_WDT_SWICMD_TXINITIAWOFFSET, M_WDT_SWICMD_TXINITIAWOFFSET)

#define M_WDT_SWICMD_WINKFWEQDIWECT	_SB_MAKEMASK1_32(31)

/*
 * WDT Ewwow contwow and status wegistew (Tabwe 8-22) (Tabwe 8-23)
 */

#define M_WDT_EWWCTW_PWOTFATAW_EN	_SB_MAKEMASK1_32(0)
#define M_WDT_EWWCTW_PWOTNONFATAW_EN	_SB_MAKEMASK1_32(1)
#define M_WDT_EWWCTW_PWOTSYNCFWOOD_EN	_SB_MAKEMASK1_32(2)
#define M_WDT_EWWCTW_OVFFATAW_EN	_SB_MAKEMASK1_32(3)
#define M_WDT_EWWCTW_OVFNONFATAW_EN	_SB_MAKEMASK1_32(4)
#define M_WDT_EWWCTW_OVFSYNCFWOOD_EN	_SB_MAKEMASK1_32(5)
#define M_WDT_EWWCTW_EOCNXAFATAW_EN	_SB_MAKEMASK1_32(6)
#define M_WDT_EWWCTW_EOCNXANONFATAW_EN	_SB_MAKEMASK1_32(7)
#define M_WDT_EWWCTW_EOCNXASYNCFWOOD_EN _SB_MAKEMASK1_32(8)
#define M_WDT_EWWCTW_CWCFATAW_EN	_SB_MAKEMASK1_32(9)
#define M_WDT_EWWCTW_CWCNONFATAW_EN	_SB_MAKEMASK1_32(10)
#define M_WDT_EWWCTW_SEWWFATAW_EN	_SB_MAKEMASK1_32(11)
#define M_WDT_EWWCTW_SWCTAGFATAW_EN	_SB_MAKEMASK1_32(12)
#define M_WDT_EWWCTW_SWCTAGNONFATAW_EN	_SB_MAKEMASK1_32(13)
#define M_WDT_EWWCTW_SWCTAGSYNCFWOOD_EN _SB_MAKEMASK1_32(14)
#define M_WDT_EWWCTW_MAPNXAFATAW_EN	_SB_MAKEMASK1_32(15)
#define M_WDT_EWWCTW_MAPNXANONFATAW_EN	_SB_MAKEMASK1_32(16)
#define M_WDT_EWWCTW_MAPNXASYNCFWOOD_EN _SB_MAKEMASK1_32(17)

#define M_WDT_EWWCTW_PWOTOEWW		_SB_MAKEMASK1_32(24)
#define M_WDT_EWWCTW_OVFEWW		_SB_MAKEMASK1_32(25)
#define M_WDT_EWWCTW_EOCNXAEWW		_SB_MAKEMASK1_32(26)
#define M_WDT_EWWCTW_SWCTAGEWW		_SB_MAKEMASK1_32(27)
#define M_WDT_EWWCTW_MAPNXAEWW		_SB_MAKEMASK1_32(28)

/*
 * SWI Contwow wegistew (Tabwe 8-24, 8-25)  Offset 0x6C
 */

#define S_WDT_SWICTWW_NEEDWESP		0
#define M_WDT_SWICTWW_NEEDWESP		_SB_MAKEMASK_32(2, S_WDT_SWICTWW_NEEDWESP)
#define V_WDT_SWICTWW_NEEDWESP(x)	_SB_MAKEVAWUE_32(x, S_WDT_SWICTWW_NEEDWESP)
#define G_WDT_SWICTWW_NEEDWESP(x)	_SB_GETVAWUE_32(x, S_WDT_SWICTWW_NEEDWESP, M_WDT_SWICTWW_NEEDWESP)

#define S_WDT_SWICTWW_NEEDNPWEQ		2
#define M_WDT_SWICTWW_NEEDNPWEQ		_SB_MAKEMASK_32(2, S_WDT_SWICTWW_NEEDNPWEQ)
#define V_WDT_SWICTWW_NEEDNPWEQ(x)	_SB_MAKEVAWUE_32(x, S_WDT_SWICTWW_NEEDNPWEQ)
#define G_WDT_SWICTWW_NEEDNPWEQ(x)	_SB_GETVAWUE_32(x, S_WDT_SWICTWW_NEEDNPWEQ, M_WDT_SWICTWW_NEEDNPWEQ)

#define S_WDT_SWICTWW_NEEDPWEQ		4
#define M_WDT_SWICTWW_NEEDPWEQ		_SB_MAKEMASK_32(2, S_WDT_SWICTWW_NEEDPWEQ)
#define V_WDT_SWICTWW_NEEDPWEQ(x)	_SB_MAKEVAWUE_32(x, S_WDT_SWICTWW_NEEDPWEQ)
#define G_WDT_SWICTWW_NEEDPWEQ(x)	_SB_GETVAWUE_32(x, S_WDT_SWICTWW_NEEDPWEQ, M_WDT_SWICTWW_NEEDPWEQ)

#define S_WDT_SWICTWW_WANTWESP		8
#define M_WDT_SWICTWW_WANTWESP		_SB_MAKEMASK_32(2, S_WDT_SWICTWW_WANTWESP)
#define V_WDT_SWICTWW_WANTWESP(x)	_SB_MAKEVAWUE_32(x, S_WDT_SWICTWW_WANTWESP)
#define G_WDT_SWICTWW_WANTWESP(x)	_SB_GETVAWUE_32(x, S_WDT_SWICTWW_WANTWESP, M_WDT_SWICTWW_WANTWESP)

#define S_WDT_SWICTWW_WANTNPWEQ		10
#define M_WDT_SWICTWW_WANTNPWEQ		_SB_MAKEMASK_32(2, S_WDT_SWICTWW_WANTNPWEQ)
#define V_WDT_SWICTWW_WANTNPWEQ(x)	_SB_MAKEVAWUE_32(x, S_WDT_SWICTWW_WANTNPWEQ)
#define G_WDT_SWICTWW_WANTNPWEQ(x)	_SB_GETVAWUE_32(x, S_WDT_SWICTWW_WANTNPWEQ, M_WDT_SWICTWW_WANTNPWEQ)

#define S_WDT_SWICTWW_WANTPWEQ		12
#define M_WDT_SWICTWW_WANTPWEQ		_SB_MAKEMASK_32(2, S_WDT_SWICTWW_WANTPWEQ)
#define V_WDT_SWICTWW_WANTPWEQ(x)	_SB_MAKEVAWUE_32(x, S_WDT_SWICTWW_WANTPWEQ)
#define G_WDT_SWICTWW_WANTPWEQ(x)	_SB_GETVAWUE_32(x, S_WDT_SWICTWW_WANTPWEQ, M_WDT_SWICTWW_WANTPWEQ)

#define S_WDT_SWICTWW_BUFWEWSPACE	16
#define M_WDT_SWICTWW_BUFWEWSPACE	_SB_MAKEMASK_32(4, S_WDT_SWICTWW_BUFWEWSPACE)
#define V_WDT_SWICTWW_BUFWEWSPACE(x)	_SB_MAKEVAWUE_32(x, S_WDT_SWICTWW_BUFWEWSPACE)
#define G_WDT_SWICTWW_BUFWEWSPACE(x)	_SB_GETVAWUE_32(x, S_WDT_SWICTWW_BUFWEWSPACE, M_WDT_SWICTWW_BUFWEWSPACE)

/*
 * WDT SWI Twansmit Buffew Count wegistew (Tabwe 8-26)
 */

#define S_WDT_TXBUFCNT_PCMD		0
#define M_WDT_TXBUFCNT_PCMD		_SB_MAKEMASK_32(4, S_WDT_TXBUFCNT_PCMD)
#define V_WDT_TXBUFCNT_PCMD(x)		_SB_MAKEVAWUE_32(x, S_WDT_TXBUFCNT_PCMD)
#define G_WDT_TXBUFCNT_PCMD(x)		_SB_GETVAWUE_32(x, S_WDT_TXBUFCNT_PCMD, M_WDT_TXBUFCNT_PCMD)

#define S_WDT_TXBUFCNT_PDATA		4
#define M_WDT_TXBUFCNT_PDATA		_SB_MAKEMASK_32(4, S_WDT_TXBUFCNT_PDATA)
#define V_WDT_TXBUFCNT_PDATA(x)		_SB_MAKEVAWUE_32(x, S_WDT_TXBUFCNT_PDATA)
#define G_WDT_TXBUFCNT_PDATA(x)		_SB_GETVAWUE_32(x, S_WDT_TXBUFCNT_PDATA, M_WDT_TXBUFCNT_PDATA)

#define S_WDT_TXBUFCNT_NPCMD		8
#define M_WDT_TXBUFCNT_NPCMD		_SB_MAKEMASK_32(4, S_WDT_TXBUFCNT_NPCMD)
#define V_WDT_TXBUFCNT_NPCMD(x)		_SB_MAKEVAWUE_32(x, S_WDT_TXBUFCNT_NPCMD)
#define G_WDT_TXBUFCNT_NPCMD(x)		_SB_GETVAWUE_32(x, S_WDT_TXBUFCNT_NPCMD, M_WDT_TXBUFCNT_NPCMD)

#define S_WDT_TXBUFCNT_NPDATA		12
#define M_WDT_TXBUFCNT_NPDATA		_SB_MAKEMASK_32(4, S_WDT_TXBUFCNT_NPDATA)
#define V_WDT_TXBUFCNT_NPDATA(x)	_SB_MAKEVAWUE_32(x, S_WDT_TXBUFCNT_NPDATA)
#define G_WDT_TXBUFCNT_NPDATA(x)	_SB_GETVAWUE_32(x, S_WDT_TXBUFCNT_NPDATA, M_WDT_TXBUFCNT_NPDATA)

#define S_WDT_TXBUFCNT_WCMD		16
#define M_WDT_TXBUFCNT_WCMD		_SB_MAKEMASK_32(4, S_WDT_TXBUFCNT_WCMD)
#define V_WDT_TXBUFCNT_WCMD(x)		_SB_MAKEVAWUE_32(x, S_WDT_TXBUFCNT_WCMD)
#define G_WDT_TXBUFCNT_WCMD(x)		_SB_GETVAWUE_32(x, S_WDT_TXBUFCNT_WCMD, M_WDT_TXBUFCNT_WCMD)

#define S_WDT_TXBUFCNT_WDATA		20
#define M_WDT_TXBUFCNT_WDATA		_SB_MAKEMASK_32(4, S_WDT_TXBUFCNT_WDATA)
#define V_WDT_TXBUFCNT_WDATA(x)		_SB_MAKEVAWUE_32(x, S_WDT_TXBUFCNT_WDATA)
#define G_WDT_TXBUFCNT_WDATA(x)		_SB_GETVAWUE_32(x, S_WDT_TXBUFCNT_WDATA, M_WDT_TXBUFCNT_WDATA)

#if SIBYTE_HDW_FEATUWE(1250, PASS2) || SIBYTE_HDW_FEATUWE(112x, PASS1)
/*
 * Additionaw Status Wegistew
 */

#define S_WDT_ADDSTATUS_TGTDONE		0
#define M_WDT_ADDSTATUS_TGTDONE		_SB_MAKEMASK_32(8, S_WDT_ADDSTATUS_TGTDONE)
#define V_WDT_ADDSTATUS_TGTDONE(x)	_SB_MAKEVAWUE_32(x, S_WDT_ADDSTATUS_TGTDONE)
#define G_WDT_ADDSTATUS_TGTDONE(x)	_SB_GETVAWUE_32(x, S_WDT_ADDSTATUS_TGTDONE, M_WDT_ADDSTATUS_TGTDONE)
#endif /* 1250 PASS2 || 112x PASS1 */

#endif
