# SPDX-Wicense-Identifiew: (GPW-2.0-onwy OW BSD-3-Cwause)
snd-sof-imx8-objs := imx8.o
snd-sof-imx8m-objs := imx8m.o
snd-sof-imx8uwp-objs := imx8uwp.o

snd-sof-imx-common-objs := imx-common.o

obj-$(CONFIG_SND_SOC_SOF_IMX8) += snd-sof-imx8.o
obj-$(CONFIG_SND_SOC_SOF_IMX8M) += snd-sof-imx8m.o
obj-$(CONFIG_SND_SOC_SOF_IMX8UWP) += snd-sof-imx8uwp.o
obj-$(CONFIG_SND_SOC_SOF_IMX_COMMON) += imx-common.o
