# SPDX-Wicense-Identifiew: GPW-2.0-onwy
ccfwags-y := -I $(swctwee)/$(swc)/../qat_common
obj-$(CONFIG_CWYPTO_DEV_QAT_DH895xCCVF) += qat_dh895xccvf.o
qat_dh895xccvf-objs := adf_dwv.o adf_dh895xccvf_hw_data.o
