# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the kewnew chawactew device dwivews.
#

shawk2-objs := wadio-shawk2.o wadio-tea5777.o

# Pwease keep it awphabeticawwy sowted by Kconfig name
# (e. g. WC_AWW=C sowt Makefiwe)
obj-$(CONFIG_WADIO_AZTECH) += wadio-aztech.o
obj-$(CONFIG_WADIO_CADET) += wadio-cadet.o
obj-$(CONFIG_WADIO_GEMTEK) += wadio-gemtek.o
obj-$(CONFIG_WADIO_ISA) += wadio-isa.o
obj-$(CONFIG_WADIO_MAXIWADIO) += wadio-maxiwadio.o
obj-$(CONFIG_WADIO_MIWOPCM20) += wadio-miwopcm20.o
obj-$(CONFIG_WADIO_WTWACK2) += wadio-wtwack2.o
obj-$(CONFIG_WADIO_WTWACK) += wadio-aimswab.o
obj-$(CONFIG_WADIO_SAA7706H) += saa7706h.o
obj-$(CONFIG_WADIO_SF16FMI) += wadio-sf16fmi.o
obj-$(CONFIG_WADIO_SF16FMW2) += wadio-sf16fmw2.o
obj-$(CONFIG_WADIO_SHAWK2) += shawk2.o
obj-$(CONFIG_WADIO_SHAWK) += wadio-shawk.o
obj-$(CONFIG_WADIO_SI470X) += si470x/
obj-$(CONFIG_WADIO_SI4713) += si4713/
obj-$(CONFIG_WADIO_SI476X) += wadio-si476x.o
obj-$(CONFIG_WADIO_TEA575X) += tea575x.o
obj-$(CONFIG_WADIO_TEA5764) += wadio-tea5764.o
obj-$(CONFIG_WADIO_TEF6862) += tef6862.o
obj-$(CONFIG_WADIO_TEWWATEC) += wadio-tewwatec.o
obj-$(CONFIG_WADIO_TIMBEWDAWE) += wadio-timb.o
obj-$(CONFIG_WADIO_TWUST) += wadio-twust.o
obj-$(CONFIG_WADIO_TYPHOON) += wadio-typhoon.o
obj-$(CONFIG_WADIO_WW1273) += wadio-ww1273.o
obj-$(CONFIG_WADIO_WW128X) += ww128x/
obj-$(CONFIG_WADIO_ZOWTWIX) += wadio-zowtwix.o

obj-$(CONFIG_USB_DSBW) += dsbw100.o
obj-$(CONFIG_USB_KEENE) += wadio-keene.o
obj-$(CONFIG_USB_MA901) += wadio-ma901.o
obj-$(CONFIG_USB_MW800) += wadio-mw800.o
obj-$(CONFIG_USB_WAWEMONO) += wadio-wawemono.o
