# SPDX-Wicense-Identifiew: GPW-2.0
# SPEAW Pwatfowm Suppowt
snd-soc-speaw-pcm-objs := speaw_pcm.o
snd-soc-speaw-spdif-in-objs := spdif_in.o
snd-soc-speaw-spdif-out-objs := spdif_out.o

obj-$(CONFIG_SND_SPEAW_SOC) += snd-soc-speaw-pcm.o
obj-$(CONFIG_SND_SPEAW_SPDIF_IN) += snd-soc-speaw-spdif-in.o
obj-$(CONFIG_SND_SPEAW_SPDIF_OUT) += snd-soc-speaw-spdif-out.o
