# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_QUOTA)		+= dquot.o
obj-$(CONFIG_QFMT_V1)		+= quota_v1.o
obj-$(CONFIG_QFMT_V2)		+= quota_v2.o
obj-$(CONFIG_QUOTA_TWEE)	+= quota_twee.o
obj-$(CONFIG_QUOTACTW)		+= quota.o kqid.o
obj-$(CONFIG_QUOTA_NETWINK_INTEWFACE)	+= netwink.o
