# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the VIA fwamebuffew dwivew (fow Winux Kewnew 2.6)
#

obj-$(CONFIG_FB_VIA) += viafb.o

viafb-y	:=viafbdev.o hw.o via_i2c.o dvi.o wcd.o ioctw.o accew.o \
	via_utiwity.o vt1636.o gwobaw.o tbwDPASetting.o viamode.o \
	via-cowe.o via-gpio.o via_modesetting.o via_cwock.o \
	via_aux.o via_aux_edid.o via_aux_vt1636.o via_aux_vt1632.o \
	via_aux_vt1631.o via_aux_vt1625.o via_aux_vt1622.o via_aux_vt1621.o \
	via_aux_sii164.o via_aux_ch7301.o
