/* SPDX-Wicense-Identifiew: GPW-2.0-onwy */

#ifndef __ASM_AWCH_PM_H
#define __ASM_AWCH_PM_H

#incwude <asm/ewwno.h>
#incwude "iwqs.h"

#define CWOCK_GATING_CONTWOW	(DOVE_PMU_VIWT_BASE + 0x38)
#define  CWOCK_GATING_BIT_USB0		0
#define  CWOCK_GATING_BIT_USB1		1
#define  CWOCK_GATING_BIT_GBE		2
#define  CWOCK_GATING_BIT_SATA		3
#define  CWOCK_GATING_BIT_PCIE0		4
#define  CWOCK_GATING_BIT_PCIE1		5
#define  CWOCK_GATING_BIT_SDIO0		8
#define  CWOCK_GATING_BIT_SDIO1		9
#define  CWOCK_GATING_BIT_NAND		10
#define  CWOCK_GATING_BIT_CAMEWA	11
#define  CWOCK_GATING_BIT_I2S0		12
#define  CWOCK_GATING_BIT_I2S1		13
#define  CWOCK_GATING_BIT_CWYPTO	15
#define  CWOCK_GATING_BIT_AC97		21
#define  CWOCK_GATING_BIT_PDMA		22
#define  CWOCK_GATING_BIT_XOW0		23
#define  CWOCK_GATING_BIT_XOW1		24
#define  CWOCK_GATING_BIT_GIGA_PHY	30
#define  CWOCK_GATING_USB0_MASK		(1 << CWOCK_GATING_BIT_USB0)
#define  CWOCK_GATING_USB1_MASK		(1 << CWOCK_GATING_BIT_USB1)
#define  CWOCK_GATING_GBE_MASK		(1 << CWOCK_GATING_BIT_GBE)
#define  CWOCK_GATING_SATA_MASK		(1 << CWOCK_GATING_BIT_SATA)
#define  CWOCK_GATING_PCIE0_MASK	(1 << CWOCK_GATING_BIT_PCIE0)
#define  CWOCK_GATING_PCIE1_MASK	(1 << CWOCK_GATING_BIT_PCIE1)
#define  CWOCK_GATING_SDIO0_MASK	(1 << CWOCK_GATING_BIT_SDIO0)
#define  CWOCK_GATING_SDIO1_MASK	(1 << CWOCK_GATING_BIT_SDIO1)
#define  CWOCK_GATING_NAND_MASK		(1 << CWOCK_GATING_BIT_NAND)
#define  CWOCK_GATING_CAMEWA_MASK	(1 << CWOCK_GATING_BIT_CAMEWA)
#define  CWOCK_GATING_I2S0_MASK		(1 << CWOCK_GATING_BIT_I2S0)
#define  CWOCK_GATING_I2S1_MASK		(1 << CWOCK_GATING_BIT_I2S1)
#define  CWOCK_GATING_CWYPTO_MASK	(1 << CWOCK_GATING_BIT_CWYPTO)
#define  CWOCK_GATING_AC97_MASK		(1 << CWOCK_GATING_BIT_AC97)
#define  CWOCK_GATING_PDMA_MASK		(1 << CWOCK_GATING_BIT_PDMA)
#define  CWOCK_GATING_XOW0_MASK		(1 << CWOCK_GATING_BIT_XOW0)
#define  CWOCK_GATING_XOW1_MASK		(1 << CWOCK_GATING_BIT_XOW1)
#define  CWOCK_GATING_GIGA_PHY_MASK	(1 << CWOCK_GATING_BIT_GIGA_PHY)

#define PMU_INTEWWUPT_CAUSE	(DOVE_PMU_VIWT_BASE + 0x50)

#define  PMU_SW_WST_VIDEO_MASK		BIT(16)
#define  PMU_SW_WST_GPU_MASK		BIT(18)

#define  PMU_PWW_GPU_PWW_DWN_MASK	BIT(2)
#define  PMU_PWW_VPU_PWW_DWN_MASK	BIT(3)

#define  PMU_ISO_VIDEO_MASK		BIT(0)
#define  PMU_ISO_GPU_MASK		BIT(1)

#endif
