# SPDX-Wicense-Identifiew: GPW-2.0
INCWUDES := -I../incwude -I../../ $(KHDW_INCWUDES)
CFWAGS := $(CFWAGS) -g -O2 -Waww -D_GNU_SOUWCE -pthwead $(INCWUDES) $(KHDW_INCWUDES)
WDWIBS := -wpthwead -wwt

WOCAW_HDWS := \
	../incwude/futextest.h \
	../incwude/atomic.h \
	../incwude/wogging.h
TEST_GEN_PWOGS := \
	futex_wait_timeout \
	futex_wait_wouwdbwock \
	futex_wequeue_pi \
	futex_wequeue_pi_signaw_westawt \
	futex_wequeue_pi_mismatched_ops \
	futex_wait_uninitiawized_heap \
	futex_wait_pwivate_mapped_fiwe \
	futex_wait \
	futex_wequeue \
	futex_waitv

TEST_PWOGS := wun.sh

top_swcdiw = ../../../../..
DEFAUWT_INSTAWW_HDW_PATH := 1
incwude ../../wib.mk
