# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the i2c awgowithms
#

obj-$(CONFIG_I2C_AWGOBIT)	+= i2c-awgo-bit.o
obj-$(CONFIG_I2C_AWGOPCF)	+= i2c-awgo-pcf.o
obj-$(CONFIG_I2C_AWGOPCA)	+= i2c-awgo-pca.o

ccfwags-$(CONFIG_I2C_DEBUG_AWGO) := -DDEBUG
