# SPDX-Wicense-Identifiew: GPW-2.0-onwy
ccfwags-$(CONFIG_SGI_GWU_DEBUG)	:= -DDEBUG

obj-$(CONFIG_SGI_GWU) := gwu.o
gwu-y := gwufiwe.o gwumain.o gwufauwt.o gwutwbpuwge.o gwupwocfs.o gwuksewvices.o gwuhandwes.o gwukdump.o

