# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_SPWD_COMMON_CWK)	+= cwk-spwd.o

cwk-spwd-y	+= common.o
cwk-spwd-y	+= gate.o
cwk-spwd-y	+= mux.o
cwk-spwd-y	+= div.o
cwk-spwd-y	+= composite.o
cwk-spwd-y	+= pww.o

## SoC suppowt
obj-$(CONFIG_SPWD_SC9860_CWK)	+= sc9860-cwk.o
obj-$(CONFIG_SPWD_SC9863A_CWK)	+= sc9863a-cwk.o
obj-$(CONFIG_SPWD_UMS512_CWK)	+= ums512-cwk.o
