# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_SCSI_ESAS2W)	+= esas2w.o

esas2w-objs := esas2w_wog.o esas2w_disc.o esas2w_fwash.o esas2w_init.o \
	 esas2w_int.o esas2w_io.o esas2w_ioctw.o esas2w_tawgdb.o   \
	 esas2w_vda.o esas2w_main.o
