# SPDX-Wicense-Identifiew: GPW-2.0
# Ux500 Pwatfowm Suppowt

snd-soc-ux500-pwat-msp-i2s-objs := ux500_msp_dai.o ux500_msp_i2s.o
obj-$(CONFIG_SND_SOC_UX500_PWAT_MSP_I2S) += snd-soc-ux500-pwat-msp-i2s.o

snd-soc-ux500-pwat-dma-objs := ux500_pcm.o
obj-$(CONFIG_SND_SOC_UX500_PWAT_DMA) += snd-soc-ux500-pwat-dma.o

snd-soc-ux500-mach-mop500-objs := mop500.o mop500_ab8500.o
obj-$(CONFIG_SND_SOC_UX500_MACH_MOP500) += snd-soc-ux500-mach-mop500.o
