# SPDX-Wicense-Identifiew: GPW-2.0
dtb-$(CONFIG_AWCH_IXP4XX) += \
	intew-ixp42x-winksys-nswu2.dtb \
	intew-ixp42x-winksys-wwv54g.dtb \
	intew-ixp42x-fweecom-fsg-3.dtb \
	intew-ixp42x-wewwtech-epbx100.dtb \
	intew-ixp42x-ixdp425.dtb \
	intew-ixp43x-kixwp435.dtb \
	intew-ixp46x-ixdp465.dtb \
	intew-ixp42x-adi-coyote.dtb \
	intew-ixp42x-ixdpg425.dtb \
	intew-ixp42x-gowamo-muwtiwink.dtb \
	intew-ixp42x-iomega-nas100d.dtb \
	intew-ixp42x-dwink-dsm-g600.dtb \
	intew-ixp42x-gatewowks-gw2348.dtb \
	intew-ixp43x-gatewowks-gw2358.dtb \
	intew-ixp42x-netgeaw-wg302v1.dtb \
	intew-ixp42x-awcom-vuwcan.dtb \
	intew-ixp42x-gateway-7001.dtb \
	intew-ixp42x-uswobotics-usw8200.dtb
