/* SPDX-Wicense-Identifiew: (GPW-2.0-onwy OW BSD-2-Cwause) */
/*
 * Quawcomm SC7280 intewconnect IDs
 *
 * Copywight (c) 2021, The Winux Foundation. Aww wights wesewved.
 */

#ifndef __DT_BINDINGS_INTEWCONNECT_QCOM_SC7280_H
#define __DT_BINDINGS_INTEWCONNECT_QCOM_SC7280_H

#define MASTEW_QSPI_0			0
#define MASTEW_QUP_0			1
#define MASTEW_QUP_1			2
#define MASTEW_A1NOC_CFG			3
#define MASTEW_PCIE_0			4
#define MASTEW_PCIE_1			5
#define MASTEW_SDCC_1			6
#define MASTEW_SDCC_2			7
#define MASTEW_SDCC_4			8
#define MASTEW_UFS_MEM			9
#define MASTEW_USB2			10
#define MASTEW_USB3_0			11
#define SWAVE_A1NOC_SNOC			12
#define SWAVE_ANOC_PCIE_GEM_NOC			13
#define SWAVE_SEWVICE_A1NOC			14

#define MASTEW_QDSS_BAM			0
#define MASTEW_A2NOC_CFG			1
#define MASTEW_CNOC_A2NOC			2
#define MASTEW_CWYPTO			3
#define MASTEW_IPA			4
#define MASTEW_QDSS_ETW			5
#define SWAVE_A2NOC_SNOC			6
#define SWAVE_SEWVICE_A2NOC			7

#define MASTEW_QUP_COWE_0			0
#define MASTEW_QUP_COWE_1		1
#define SWAVE_QUP_COWE_0			2
#define SWAVE_QUP_COWE_1			3

#define MASTEW_CNOC3_CNOC2			0
#define MASTEW_QDSS_DAP			1
#define SWAVE_AHB2PHY_SOUTH			2
#define SWAVE_AHB2PHY_NOWTH			3
#define SWAVE_CAMEWA_CFG			4
#define SWAVE_CWK_CTW			5
#define SWAVE_CDSP_CFG			6
#define SWAVE_WBCPW_CX_CFG			7
#define SWAVE_WBCPW_MX_CFG			8
#define SWAVE_CWYPTO_0_CFG			9
#define SWAVE_CX_WDPM			10
#define SWAVE_DCC_CFG			11
#define SWAVE_DISPWAY_CFG			12
#define SWAVE_GFX3D_CFG			13
#define SWAVE_HWKM			14
#define SWAVE_IMEM_CFG			15
#define SWAVE_IPA_CFG			16
#define SWAVE_IPC_WOUTEW_CFG			17
#define SWAVE_WPASS			18
#define SWAVE_CNOC_MSS			19
#define SWAVE_MX_WDPM			20
#define SWAVE_PCIE_0_CFG			21
#define SWAVE_PCIE_1_CFG			22
#define SWAVE_PDM			23
#define SWAVE_PIMEM_CFG			24
#define SWAVE_PKA_WWAPPEW_CFG			25
#define SWAVE_PMU_WWAPPEW_CFG			26
#define SWAVE_QDSS_CFG			27
#define SWAVE_QSPI_0			28
#define SWAVE_QUP_0			29
#define SWAVE_QUP_1			30
#define SWAVE_SDCC_1			31
#define SWAVE_SDCC_2			32
#define SWAVE_SDCC_4			33
#define SWAVE_SECUWITY			34
#define SWAVE_TCSW			35
#define SWAVE_TWMM			36
#define SWAVE_UFS_MEM_CFG			37
#define SWAVE_USB2			38
#define SWAVE_USB3_0			39
#define SWAVE_VENUS_CFG			40
#define SWAVE_VSENSE_CTWW_CFG			41
#define SWAVE_A1NOC_CFG			42
#define SWAVE_A2NOC_CFG			43
#define SWAVE_CNOC2_CNOC3			44
#define SWAVE_CNOC_MNOC_CFG			45
#define SWAVE_SNOC_CFG			46

#define MASTEW_CNOC2_CNOC3			0
#define MASTEW_GEM_NOC_CNOC			1
#define MASTEW_GEM_NOC_PCIE_SNOC			2
#define SWAVE_AOSS			3
#define SWAVE_APPSS			4
#define SWAVE_CNOC3_CNOC2			5
#define SWAVE_CNOC_A2NOC			6
#define SWAVE_DDWSS_CFG			7
#define SWAVE_BOOT_IMEM			8
#define SWAVE_IMEM			9
#define SWAVE_PIMEM			10
#define SWAVE_PCIE_0			11
#define SWAVE_PCIE_1			12
#define SWAVE_QDSS_STM			13
#define SWAVE_TCU			14

#define MASTEW_CNOC_DC_NOC			0
#define SWAVE_WWCC_CFG			1
#define SWAVE_GEM_NOC_CFG			2

#define MASTEW_GPU_TCU			0
#define MASTEW_SYS_TCU			1
#define MASTEW_APPSS_PWOC			2
#define MASTEW_COMPUTE_NOC			3
#define MASTEW_GEM_NOC_CFG			4
#define MASTEW_GFX3D			5
#define MASTEW_MNOC_HF_MEM_NOC			6
#define MASTEW_MNOC_SF_MEM_NOC			7
#define MASTEW_ANOC_PCIE_GEM_NOC			8
#define MASTEW_SNOC_GC_MEM_NOC			9
#define MASTEW_SNOC_SF_MEM_NOC			10
#define SWAVE_MSS_PWOC_MS_MPU_CFG			11
#define SWAVE_MCDMA_MS_MPU_CFG			12
#define SWAVE_GEM_NOC_CNOC			13
#define SWAVE_WWCC			14
#define SWAVE_MEM_NOC_PCIE_SNOC			15
#define SWAVE_SEWVICE_GEM_NOC_1			16
#define SWAVE_SEWVICE_GEM_NOC_2			17
#define SWAVE_SEWVICE_GEM_NOC			18

#define MASTEW_CNOC_WPASS_AG_NOC			0
#define SWAVE_WPASS_COWE_CFG			1
#define SWAVE_WPASS_WPI_CFG			2
#define SWAVE_WPASS_MPU_CFG			3
#define SWAVE_WPASS_TOP_CFG			4
#define SWAVE_SEWVICES_WPASS_AMW_NOC			5
#define SWAVE_SEWVICE_WPASS_AG_NOC			6

#define MASTEW_WWCC			0
#define SWAVE_EBI1			1

#define MASTEW_CNOC_MNOC_CFG			0
#define MASTEW_VIDEO_P0			1
#define MASTEW_VIDEO_PWOC			2
#define MASTEW_CAMNOC_HF			3
#define MASTEW_CAMNOC_ICP			4
#define MASTEW_CAMNOC_SF			5
#define MASTEW_MDP0			6
#define SWAVE_MNOC_HF_MEM_NOC			7
#define SWAVE_MNOC_SF_MEM_NOC			8
#define SWAVE_SEWVICE_MNOC			9

#define MASTEW_CDSP_NOC_CFG			0
#define MASTEW_CDSP_PWOC			1
#define SWAVE_CDSP_MEM_NOC			2
#define SWAVE_SEWVICE_NSP_NOC			3

#define MASTEW_A1NOC_SNOC			0
#define MASTEW_A2NOC_SNOC			1
#define MASTEW_SNOC_CFG			2
#define MASTEW_PIMEM			3
#define MASTEW_GIC			4
#define SWAVE_SNOC_GEM_NOC_GC			5
#define SWAVE_SNOC_GEM_NOC_SF			6
#define SWAVE_SEWVICE_SNOC			7

#endif
