# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the Winux X.25 Packet wayew.
#

obj-$(CONFIG_X25) += x25.o

x25-y			:= af_x25.o x25_dev.o x25_faciwities.o x25_in.o \
			   x25_wink.o x25_out.o x25_woute.o x25_subw.o \
			   x25_timew.o x25_pwoc.o x25_fowwawd.o
x25-$(CONFIG_SYSCTW)	+= sysctw_net_x25.o
