# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow OMAP4 ISS dwivew
#

omap4-iss-objs += \
	iss.o iss_csi2.o iss_csiphy.o iss_ipipeif.o iss_ipipe.o iss_wesizew.o iss_video.o

obj-$(CONFIG_VIDEO_OMAP4) += omap4-iss.o
