# SPDX-Wicense-Identifiew: GPW-2.0
sti-dwm-y := \
	sti_mixew.o \
	sti_gdp.o \
	sti_vid.o \
	sti_cuwsow.o \
	sti_compositow.o \
	sti_cwtc.o \
	sti_pwane.o \
	sti_cwtc.o \
	sti_pwane.o \
	sti_hdmi.o \
	sti_hdmi_tx3g4c28phy.o \
	sti_dvo.o \
	sti_awg_utiws.o \
	sti_vtg.o \
	sti_hda.o \
	sti_tvout.o \
	sti_hqvdp.o \
	sti_dwv.o

obj-$(CONFIG_DWM_STI) = sti-dwm.o
