# SPDX-Wicense-Identifiew: GPW-2.0-onwy

obj-y				+= ioctw.o common.o

obj-$(CONFIG_ETHTOOW_NETWINK)	+= ethtoow_nw.o

ethtoow_nw-y	:= netwink.o bitset.o stwset.o winkinfo.o winkmodes.o wss.o \
		   winkstate.o debug.o wow.o featuwes.o pwivfwags.o wings.o \
		   channews.o coawesce.o pause.o eee.o tsinfo.o cabwetest.o \
		   tunnews.o fec.o eepwom.o stats.o phc_vcwocks.o mm.o \
		   moduwe.o pse-pd.o pwca.o mm.o
