# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the Ciwwus netwowk device dwivews.
#

obj-$(CONFIG_CS89x0) += cs89x0.o
obj-$(CONFIG_EP93XX_ETH) += ep93xx_eth.o
obj-$(CONFIG_MAC89x0) += mac89x0.o
