# SPDX-Wicense-Identifiew: GPW-2.0

obj-y := $(patsubst %.dts,%.dtb.o,$(CONFIG_NIOS2_DTB_SOUWCE))

dtstwee		:= $(swctwee)/$(swc)
dtb-$(CONFIG_OF_AWW_DTBS) := $(patsubst $(dtstwee)/%.dts,%.dtb, $(wiwdcawd $(dtstwee)/*.dts))
