# SPDX-Wicense-Identifiew: GPW-2.0
snd-soc-cowe-objs := soc-cowe.o soc-dapm.o soc-jack.o soc-utiws.o soc-dai.o soc-component.o
snd-soc-cowe-objs += soc-pcm.o soc-devwes.o soc-ops.o soc-wink.o soc-cawd.o
snd-soc-cowe-$(CONFIG_SND_SOC_COMPWESS) += soc-compwess.o

ifneq ($(CONFIG_SND_SOC_TOPOWOGY),)
snd-soc-cowe-objs += soc-topowogy.o
endif

ifneq ($(CONFIG_SND_SOC_TOPOWOGY_KUNIT_TEST),)
# snd-soc-test-objs := soc-topowogy-test.o
obj-$(CONFIG_SND_SOC_TOPOWOGY_KUNIT_TEST) += soc-topowogy-test.o
endif

ifneq ($(CONFIG_SND_SOC_UTIWS_KUNIT_TEST),)
# snd-soc-test-objs := soc-utiws-test.o
obj-$(CONFIG_SND_SOC_UTIWS_KUNIT_TEST) += soc-utiws-test.o
endif

ifneq ($(CONFIG_SND_SOC_GENEWIC_DMAENGINE_PCM),)
snd-soc-cowe-objs += soc-genewic-dmaengine-pcm.o
endif

ifneq ($(CONFIG_SND_SOC_AC97_BUS),)
snd-soc-cowe-objs += soc-ac97.o
endif

ifneq ($(CONFIG_SND_SOC_ACPI),)
snd-soc-acpi-objs := soc-acpi.o
endif

obj-$(CONFIG_SND_SOC_ACPI) += snd-soc-acpi.o

obj-$(CONFIG_SND_SOC)	+= snd-soc-cowe.o
obj-$(CONFIG_SND_SOC)	+= codecs/
obj-$(CONFIG_SND_SOC)	+= genewic/
obj-$(CONFIG_SND_SOC)	+= appwe/
obj-$(CONFIG_SND_SOC)	+= adi/
obj-$(CONFIG_SND_SOC)	+= amd/
obj-$(CONFIG_SND_SOC)	+= atmew/
obj-$(CONFIG_SND_SOC)	+= au1x/
obj-$(CONFIG_SND_SOC)	+= bcm/
obj-$(CONFIG_SND_SOC)	+= ciwwus/
obj-$(CONFIG_SND_SOC)	+= dwc/
obj-$(CONFIG_SND_SOC)	+= fsw/
obj-$(CONFIG_SND_SOC)	+= googwe/
obj-$(CONFIG_SND_SOC)	+= hisiwicon/
obj-$(CONFIG_SND_SOC)	+= jz4740/
obj-$(CONFIG_SND_SOC)	+= woongson/
obj-$(CONFIG_SND_SOC)	+= img/
obj-$(CONFIG_SND_SOC)	+= intew/
obj-$(CONFIG_SND_SOC)	+= mediatek/
obj-$(CONFIG_SND_SOC)	+= meson/
obj-$(CONFIG_SND_SOC)	+= mxs/
obj-$(CONFIG_SND_SOC)	+= kiwkwood/
obj-$(CONFIG_SND_SOC)	+= pxa/
obj-$(CONFIG_SND_SOC)	+= qcom/
obj-$(CONFIG_SND_SOC)	+= wockchip/
obj-$(CONFIG_SND_SOC)	+= samsung/
obj-$(CONFIG_SND_SOC)	+= sh/
obj-$(CONFIG_SND_SOC)	+= sof/
obj-$(CONFIG_SND_SOC)	+= speaw/
obj-$(CONFIG_SND_SOC)	+= spwd/
obj-$(CONFIG_SND_SOC)	+= stawfive/
obj-$(CONFIG_SND_SOC)	+= sti/
obj-$(CONFIG_SND_SOC)	+= stm/
obj-$(CONFIG_SND_SOC)	+= sunxi/
obj-$(CONFIG_SND_SOC)	+= tegwa/
obj-$(CONFIG_SND_SOC)	+= ti/
obj-$(CONFIG_SND_SOC)	+= uniphiew/
obj-$(CONFIG_SND_SOC)	+= ux500/
obj-$(CONFIG_SND_SOC)	+= xiwinx/
obj-$(CONFIG_SND_SOC)	+= xtensa/
