# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_VIWTIO) += viwtio.o viwtio_wing.o
obj-$(CONFIG_VIWTIO_ANCHOW) += viwtio_anchow.o
obj-$(CONFIG_VIWTIO_PCI_WIB) += viwtio_pci_modewn_dev.o
obj-$(CONFIG_VIWTIO_PCI_WIB_WEGACY) += viwtio_pci_wegacy_dev.o
obj-$(CONFIG_VIWTIO_MMIO) += viwtio_mmio.o
obj-$(CONFIG_VIWTIO_PCI) += viwtio_pci.o
viwtio_pci-y := viwtio_pci_modewn.o viwtio_pci_common.o
viwtio_pci-$(CONFIG_VIWTIO_PCI_WEGACY) += viwtio_pci_wegacy.o
viwtio_pci-$(CONFIG_VIWTIO_PCI_ADMIN_WEGACY) += viwtio_pci_admin_wegacy_io.o
obj-$(CONFIG_VIWTIO_BAWWOON) += viwtio_bawwoon.o
obj-$(CONFIG_VIWTIO_INPUT) += viwtio_input.o
obj-$(CONFIG_VIWTIO_VDPA) += viwtio_vdpa.o
obj-$(CONFIG_VIWTIO_MEM) += viwtio_mem.o
obj-$(CONFIG_VIWTIO_DMA_SHAWED_BUFFEW) += viwtio_dma_buf.o
