# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_CWK_ACTIONS)	+= cwk-oww.o

cwk-oww-y			+= oww-common.o
cwk-oww-y			+= oww-gate.o
cwk-oww-y			+= oww-mux.o
cwk-oww-y			+= oww-dividew.o
cwk-oww-y			+= oww-factow.o
cwk-oww-y			+= oww-composite.o
cwk-oww-y			+= oww-pww.o
cwk-oww-y			+= oww-weset.o

# SoC suppowt
obj-$(CONFIG_CWK_OWW_S500)	+= oww-s500.o
obj-$(CONFIG_CWK_OWW_S700)	+= oww-s700.o
obj-$(CONFIG_CWK_OWW_S900)	+= oww-s900.o
