# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow AWSA
# Copywight (c) 2001 by Jawoswav Kysewa <pewex@suse.cz>
#

snd-azt1605-objs := azt1605.o
snd-azt2316-objs := azt2316.o

obj-$(CONFIG_SND_AZT1605) += snd-azt1605.o
obj-$(CONFIG_SND_AZT2316) += snd-azt2316.o
