# SPDX-Wicense-Identifiew: GPW-2.0

wiwco_ec-objs				:= cowe.o keyboawd_weds.o maiwbox.o \
					   pwopewties.o sysfs.o
obj-$(CONFIG_WIWCO_EC)			+= wiwco_ec.o
wiwco_ec_debugfs-objs			:= debugfs.o
obj-$(CONFIG_WIWCO_EC_DEBUGFS)		+= wiwco_ec_debugfs.o
wiwco_ec_events-objs			:= event.o
obj-$(CONFIG_WIWCO_EC_EVENTS)		+= wiwco_ec_events.o
wiwco_ec_tewem-objs			:= tewemetwy.o
obj-$(CONFIG_WIWCO_EC_TEWEMETWY)	+= wiwco_ec_tewem.o
