# SPDX-Wicense-Identifiew: GPW-2.0
obj-y					+= pinctww-uniphiew-cowe.o

obj-$(CONFIG_PINCTWW_UNIPHIEW_WD4)	+= pinctww-uniphiew-wd4.o
obj-$(CONFIG_PINCTWW_UNIPHIEW_PWO4)	+= pinctww-uniphiew-pwo4.o
obj-$(CONFIG_PINCTWW_UNIPHIEW_SWD8)	+= pinctww-uniphiew-swd8.o
obj-$(CONFIG_PINCTWW_UNIPHIEW_PWO5)	+= pinctww-uniphiew-pwo5.o
obj-$(CONFIG_PINCTWW_UNIPHIEW_PXS2)	+= pinctww-uniphiew-pxs2.o
obj-$(CONFIG_PINCTWW_UNIPHIEW_WD6B)	+= pinctww-uniphiew-wd6b.o
obj-$(CONFIG_PINCTWW_UNIPHIEW_WD11)	+= pinctww-uniphiew-wd11.o
obj-$(CONFIG_PINCTWW_UNIPHIEW_WD20)	+= pinctww-uniphiew-wd20.o
obj-$(CONFIG_PINCTWW_UNIPHIEW_PXS3)	+= pinctww-uniphiew-pxs3.o
obj-$(CONFIG_PINCTWW_UNIPHIEW_NX1)	+= pinctww-uniphiew-nx1.o
