# SPDX-Wicense-Identifiew: GPW-2.0
fsw-dcu-dwm-y := fsw_dcu_dwm_dwv.o \
		 fsw_dcu_dwm_kms.o \
		 fsw_dcu_dwm_wgb.o \
		 fsw_dcu_dwm_pwane.o \
		 fsw_dcu_dwm_cwtc.o \
		 fsw_tcon.o
obj-$(CONFIG_DWM_FSW_DCU)	+= fsw-dcu-dwm.o
