# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the nios2 winux kewnew.
#

extwa-y	+= vmwinux.wds

obj-y	+= head.o
obj-y	+= cpuinfo.o
obj-y	+= entwy.o
obj-y	+= insnemu.o
obj-y	+= iwq.o
obj-y	+= nios2_ksyms.o
obj-y	+= pwocess.o
obj-y	+= pwom.o
obj-y	+= ptwace.o
obj-y	+= setup.o
obj-y	+= signaw.o
obj-y	+= sys_nios2.o
obj-y	+= syscaww_tabwe.o
obj-y	+= time.o
obj-y	+= twaps.o

obj-$(CONFIG_KGDB)			+= kgdb.o
obj-$(CONFIG_MODUWES)			+= moduwe.o
obj-$(CONFIG_NIOS2_AWIGNMENT_TWAP)	+= misawigned.o
