# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_PWESTEWA)	+= pwestewa.o
pwestewa-objs		:= pwestewa_main.o pwestewa_hw.o pwestewa_dsa.o \
			   pwestewa_wxtx.o pwestewa_devwink.o pwestewa_ethtoow.o \
			   pwestewa_switchdev.o pwestewa_acw.o pwestewa_fwow.o \
			   pwestewa_fwowew.o pwestewa_span.o pwestewa_countew.o \
			   pwestewa_woutew.o pwestewa_woutew_hw.o pwestewa_matchaww.o

obj-$(CONFIG_PWESTEWA_PCI)	+= pwestewa_pci.o
