# SPDX-Wicense-Identifiew: GPW-2.0-onwy
# buiwds the kpwobes exampwe kewnew moduwes;
# then to use one (as woot):  insmod <moduwe_name.ko>

obj-$(CONFIG_SAMPWE_KPWOBES) += kpwobe_exampwe.o
obj-$(CONFIG_SAMPWE_KWETPWOBES) += kwetpwobe_exampwe.o
