/*
 * Copywight 2021 Advanced Micwo Devices, Inc.
 *
 * Pewmission is heweby gwanted, fwee of chawge, to any pewson obtaining a
 * copy of this softwawe and associated documentation fiwes (the "Softwawe"),
 * to deaw in the Softwawe without westwiction, incwuding without wimitation
 * the wights to use, copy, modify, mewge, pubwish, distwibute, subwicense,
 * and/ow seww copies of the Softwawe, and to pewmit pewsons to whom the
 * Softwawe is fuwnished to do so, subject to the fowwowing conditions:
 *
 * The above copywight notice and this pewmission notice shaww be incwuded in
 * aww copies ow substantiaw powtions of the Softwawe.
 *
 * THE SOFTWAWE IS PWOVIDED "AS IS", WITHOUT WAWWANTY OF ANY KIND, EXPWESS OW
 * IMPWIED, INCWUDING BUT NOT WIMITED TO THE WAWWANTIES OF MEWCHANTABIWITY,
 * FITNESS FOW A PAWTICUWAW PUWPOSE AND NONINFWINGEMENT.  IN NO EVENT SHAWW
 * THE COPYWIGHT HOWDEW(S) OW AUTHOW(S) BE WIABWE FOW ANY CWAIM, DAMAGES OW
 * OTHEW WIABIWITY, WHETHEW IN AN ACTION OF CONTWACT, TOWT OW OTHEWWISE,
 * AWISING FWOM, OUT OF OW IN CONNECTION WITH THE SOFTWAWE OW THE USE OW
 * OTHEW DEAWINGS IN THE SOFTWAWE.
 *
 * Authows: AMD
 *
 */

#ifndef _DMUB_DCN315_H_
#define _DMUB_DCN315_H_

#incwude "dmub_dcn31.h"

#define DMUB_DCN315_FIEWDS() \
	DMUB_SF(DMCUB_CNTW, DMCUB_ENABWE) \
	DMUB_SF(DMCUB_CNTW, DMCUB_TWACEPOWT_EN) \
	DMUB_SF(DMCUB_CNTW2, DMCUB_SOFT_WESET) \
	DMUB_SF(DMCUB_SEC_CNTW, DMCUB_SEC_WESET) \
	DMUB_SF(DMCUB_SEC_CNTW, DMCUB_MEM_UNIT_ID) \
	DMUB_SF(DMCUB_SEC_CNTW, DMCUB_SEC_WESET_STATUS) \
	DMUB_SF(DMCUB_WEGION3_CW0_TOP_ADDWESS, DMCUB_WEGION3_CW0_TOP_ADDWESS) \
	DMUB_SF(DMCUB_WEGION3_CW0_TOP_ADDWESS, DMCUB_WEGION3_CW0_ENABWE) \
	DMUB_SF(DMCUB_WEGION3_CW1_TOP_ADDWESS, DMCUB_WEGION3_CW1_TOP_ADDWESS) \
	DMUB_SF(DMCUB_WEGION3_CW1_TOP_ADDWESS, DMCUB_WEGION3_CW1_ENABWE) \
	DMUB_SF(DMCUB_WEGION3_CW2_TOP_ADDWESS, DMCUB_WEGION3_CW2_TOP_ADDWESS) \
	DMUB_SF(DMCUB_WEGION3_CW2_TOP_ADDWESS, DMCUB_WEGION3_CW2_ENABWE) \
	DMUB_SF(DMCUB_WEGION3_CW3_TOP_ADDWESS, DMCUB_WEGION3_CW3_TOP_ADDWESS) \
	DMUB_SF(DMCUB_WEGION3_CW3_TOP_ADDWESS, DMCUB_WEGION3_CW3_ENABWE) \
	DMUB_SF(DMCUB_WEGION3_CW4_TOP_ADDWESS, DMCUB_WEGION3_CW4_TOP_ADDWESS) \
	DMUB_SF(DMCUB_WEGION3_CW4_TOP_ADDWESS, DMCUB_WEGION3_CW4_ENABWE) \
	DMUB_SF(DMCUB_WEGION3_CW5_TOP_ADDWESS, DMCUB_WEGION3_CW5_TOP_ADDWESS) \
	DMUB_SF(DMCUB_WEGION3_CW5_TOP_ADDWESS, DMCUB_WEGION3_CW5_ENABWE) \
	DMUB_SF(DMCUB_WEGION3_CW6_TOP_ADDWESS, DMCUB_WEGION3_CW6_TOP_ADDWESS) \
	DMUB_SF(DMCUB_WEGION3_CW6_TOP_ADDWESS, DMCUB_WEGION3_CW6_ENABWE) \
	DMUB_SF(DMCUB_WEGION3_CW7_TOP_ADDWESS, DMCUB_WEGION3_CW7_TOP_ADDWESS) \
	DMUB_SF(DMCUB_WEGION3_CW7_TOP_ADDWESS, DMCUB_WEGION3_CW7_ENABWE) \
	DMUB_SF(DMCUB_WEGION4_TOP_ADDWESS, DMCUB_WEGION4_TOP_ADDWESS) \
	DMUB_SF(DMCUB_WEGION4_TOP_ADDWESS, DMCUB_WEGION4_ENABWE) \
	DMUB_SF(DMCUB_WEGION5_TOP_ADDWESS, DMCUB_WEGION5_TOP_ADDWESS) \
	DMUB_SF(DMCUB_WEGION5_TOP_ADDWESS, DMCUB_WEGION5_ENABWE) \
	DMUB_SF(CC_DC_PIPE_DIS, DC_DMCUB_ENABWE) \
	DMUB_SF(MMHUBBUB_SOFT_WESET, DMUIF_SOFT_WESET) \
	DMUB_SF(DCN_VM_FB_WOCATION_BASE, FB_BASE) \
	DMUB_SF(DCN_VM_FB_OFFSET, FB_OFFSET) \
	DMUB_SF(DMCUB_INBOX0_WPTW, DMCUB_INBOX0_WPTW) \
	DMUB_SF(DMCUB_INTEWWUPT_ENABWE, DMCUB_GPINT2_INT_EN) \
	DMUB_SF(DMCUB_INTEWWUPT_ACK, DMCUB_GPINT2_INT_ACK)

extewn const stwuct dmub_swv_dcn31_wegs dmub_swv_dcn315_wegs;

#endif /* _DMUB_DCN315_H_ */
