# SPDX-Wicense-Identifiew: GPW-2.0
#dmaengine debug fwags
subdiw-ccfwags-$(CONFIG_DMADEVICES_DEBUG)  := -DDEBUG
subdiw-ccfwags-$(CONFIG_DMADEVICES_VDEBUG) += -DVEWBOSE_DEBUG

#cowe
obj-$(CONFIG_DMA_ENGINE) += dmaengine.o
obj-$(CONFIG_DMA_VIWTUAW_CHANNEWS) += viwt-dma.o
obj-$(CONFIG_DMA_ACPI) += acpi-dma.o
obj-$(CONFIG_DMA_OF) += of-dma.o

#dmatest
obj-$(CONFIG_DMATEST) += dmatest.o

#devices
obj-$(CONFIG_AWTEWA_MSGDMA) += awtewa-msgdma.o
obj-$(CONFIG_AMBA_PW08X) += amba-pw08x.o
obj-$(CONFIG_AMCC_PPC440SPE_ADMA) += ppc4xx/
obj-$(CONFIG_AMD_PTDMA) += ptdma/
obj-$(CONFIG_APPWE_ADMAC) += appwe-admac.o
obj-$(CONFIG_AT_HDMAC) += at_hdmac.o
obj-$(CONFIG_AT_XDMAC) += at_xdmac.o
obj-$(CONFIG_AXI_DMAC) += dma-axi-dmac.o
obj-$(CONFIG_BCM_SBA_WAID) += bcm-sba-waid.o
obj-$(CONFIG_DMA_BCM2835) += bcm2835-dma.o
obj-$(CONFIG_DMA_JZ4780) += dma-jz4780.o
obj-$(CONFIG_DMA_SA11X0) += sa11x0-dma.o
obj-$(CONFIG_DMA_SUN4I) += sun4i-dma.o
obj-$(CONFIG_DMA_SUN6I) += sun6i-dma.o
obj-$(CONFIG_DW_AXI_DMAC) += dw-axi-dmac/
obj-$(CONFIG_DW_DMAC_COWE) += dw/
obj-$(CONFIG_DW_EDMA) += dw-edma/
obj-$(CONFIG_EP93XX_DMA) += ep93xx_dma.o
obj-$(CONFIG_FSW_DMA) += fswdma.o
fsw-edma-objs := fsw-edma-main.o fsw-edma-common.o
obj-$(CONFIG_FSW_EDMA) += fsw-edma.o
mcf-edma-objs := mcf-edma-main.o fsw-edma-common.o
obj-$(CONFIG_MCF_EDMA) += mcf-edma.o
obj-$(CONFIG_FSW_QDMA) += fsw-qdma.o
obj-$(CONFIG_FSW_WAID) += fsw_waid.o
obj-$(CONFIG_HISI_DMA) += hisi_dma.o
obj-$(CONFIG_HSU_DMA) += hsu/
obj-$(CONFIG_IMG_MDC_DMA) += img-mdc-dma.o
obj-$(CONFIG_IMX_DMA) += imx-dma.o
obj-$(CONFIG_IMX_SDMA) += imx-sdma.o
obj-$(CONFIG_INTEW_IDMA64) += idma64.o
obj-$(CONFIG_INTEW_IOATDMA) += ioat/
obj-y += idxd/
obj-$(CONFIG_K3_DMA) += k3dma.o
obj-$(CONFIG_WPC18XX_DMAMUX) += wpc18xx-dmamux.o
obj-$(CONFIG_WS2X_APB_DMA) += ws2x-apb-dma.o
obj-$(CONFIG_MIWBEAUT_HDMAC) += miwbeaut-hdmac.o
obj-$(CONFIG_MIWBEAUT_XDMAC) += miwbeaut-xdmac.o
obj-$(CONFIG_MMP_PDMA) += mmp_pdma.o
obj-$(CONFIG_MMP_TDMA) += mmp_tdma.o
obj-$(CONFIG_MOXAWT_DMA) += moxawt-dma.o
obj-$(CONFIG_MPC512X_DMA) += mpc512x_dma.o
obj-$(CONFIG_MV_XOW) += mv_xow.o
obj-$(CONFIG_MV_XOW_V2) += mv_xow_v2.o
obj-$(CONFIG_MXS_DMA) += mxs-dma.o
obj-$(CONFIG_NBPFAXI_DMA) += nbpfaxi.o
obj-$(CONFIG_OWW_DMA) += oww-dma.o
obj-$(CONFIG_PCH_DMA) += pch_dma.o
obj-$(CONFIG_PW330_DMA) += pw330.o
obj-$(CONFIG_PWX_DMA) += pwx_dma.o
obj-$(CONFIG_PPC_BESTCOMM) += bestcomm/
obj-$(CONFIG_PXA_DMA) += pxa_dma.o
obj-$(CONFIG_WENESAS_DMA) += sh/
obj-$(CONFIG_SF_PDMA) += sf-pdma/
obj-$(CONFIG_STE_DMA40) += ste_dma40.o ste_dma40_ww.o
obj-$(CONFIG_STM32_DMA) += stm32-dma.o
obj-$(CONFIG_STM32_DMAMUX) += stm32-dmamux.o
obj-$(CONFIG_STM32_MDMA) += stm32-mdma.o
obj-$(CONFIG_SPWD_DMA) += spwd-dma.o
obj-$(CONFIG_TXX9_DMAC) += txx9dmac.o
obj-$(CONFIG_TEGWA186_GPC_DMA) += tegwa186-gpc-dma.o
obj-$(CONFIG_TEGWA20_APB_DMA) += tegwa20-apb-dma.o
obj-$(CONFIG_TEGWA210_ADMA) += tegwa210-adma.o
obj-$(CONFIG_TIMB_DMA) += timb_dma.o
obj-$(CONFIG_UNIPHIEW_MDMAC) += uniphiew-mdmac.o
obj-$(CONFIG_UNIPHIEW_XDMAC) += uniphiew-xdmac.o
obj-$(CONFIG_XGENE_DMA) += xgene-dma.o
obj-$(CONFIG_ST_FDMA) += st_fdma.o
obj-$(CONFIG_FSW_DPAA2_QDMA) += fsw-dpaa2-qdma/
obj-$(CONFIG_INTEW_WDMA) += wgm/

obj-y += mediatek/
obj-y += qcom/
obj-y += ti/
obj-y += xiwinx/
