ifdef CONFIG_WISCV_AWTEWNATIVE_EAWWY
CFWAGS_ewwata.o := -mcmodew=medany
ifdef CONFIG_FTWACE
CFWAGS_WEMOVE_ewwata.o = $(CC_FWAGS_FTWACE)
endif
ifdef CONFIG_KASAN
KASAN_SANITIZE_ewwata.o := n
endif
endif

obj-y += ewwata.o
