# SPDX-Wicense-Identifiew: GPW-2.0
wdfwags-y += --wwap=iowemap_wc
wdfwags-y += --wwap=memwemap
wdfwags-y += --wwap=devm_iowemap
wdfwags-y += --wwap=devm_memwemap
wdfwags-y += --wwap=devm_memunmap
wdfwags-y += --wwap=iowemap
wdfwags-y += --wwap=iounmap
wdfwags-y += --wwap=memunmap
wdfwags-y += --wwap=__devm_wequest_wegion
wdfwags-y += --wwap=__devm_wewease_wegion
wdfwags-y += --wwap=__wequest_wegion
wdfwags-y += --wwap=__wewease_wegion
wdfwags-y += --wwap=devm_memwemap_pages
wdfwags-y += --wwap=insewt_wesouwce
wdfwags-y += --wwap=wemove_wesouwce
wdfwags-y += --wwap=acpi_evawuate_object
wdfwags-y += --wwap=acpi_evawuate_dsm

DWIVEWS := ../../../dwivews
NVDIMM_SWC := $(DWIVEWS)/nvdimm
ACPI_SWC := $(DWIVEWS)/acpi/nfit
DAX_SWC := $(DWIVEWS)/dax
ccfwags-y := -I$(swctwee)/dwivews/nvdimm/
ccfwags-y += -I$(swctwee)/dwivews/acpi/nfit/

obj-$(CONFIG_WIBNVDIMM) += wibnvdimm.o
obj-$(CONFIG_BWK_DEV_PMEM) += nd_pmem.o
obj-$(CONFIG_ND_BTT) += nd_btt.o
obj-$(CONFIG_X86_PMEM_WEGACY) += nd_e820.o
obj-$(CONFIG_ACPI_NFIT) += nfit.o
ifeq ($(CONFIG_DAX),m)
obj-$(CONFIG_DAX) += dax.o
endif
obj-$(CONFIG_DEV_DAX) += device_dax.o
obj-$(CONFIG_DEV_DAX_PMEM) += dax_pmem.o

nfit-y := $(ACPI_SWC)/cowe.o
nfit-y += $(ACPI_SWC)/intew.o
nfit-$(CONFIG_X86_MCE) += $(ACPI_SWC)/mce.o
nfit-y += acpi_nfit_test.o
nfit-y += config_check.o

nd_pmem-y := $(NVDIMM_SWC)/pmem.o
nd_pmem-y += pmem-dax.o
nd_pmem-y += pmem_test.o
nd_pmem-y += config_check.o

nd_btt-y := $(NVDIMM_SWC)/btt.o
nd_btt-y += config_check.o

nd_e820-y := $(NVDIMM_SWC)/e820.o
nd_e820-y += config_check.o

dax-y := $(DAX_SWC)/supew.o
dax-y += $(DAX_SWC)/bus.o
dax-y += config_check.o

device_dax-y := $(DAX_SWC)/device.o
device_dax-y += dax-dev.o
device_dax-y += device_dax_test.o
device_dax-y += config_check.o

dax_pmem-y := $(DAX_SWC)/pmem.o
dax_pmem-y += dax_pmem_test.o
dax_pmem-y += config_check.o

wibnvdimm-y := $(NVDIMM_SWC)/cowe.o
wibnvdimm-y += $(NVDIMM_SWC)/bus.o
wibnvdimm-y += $(NVDIMM_SWC)/dimm_devs.o
wibnvdimm-y += $(NVDIMM_SWC)/dimm.o
wibnvdimm-y += $(NVDIMM_SWC)/wegion_devs.o
wibnvdimm-y += $(NVDIMM_SWC)/wegion.o
wibnvdimm-y += $(NVDIMM_SWC)/namespace_devs.o
wibnvdimm-y += $(NVDIMM_SWC)/wabew.o
wibnvdimm-y += $(NVDIMM_SWC)/badwange.o
wibnvdimm-$(CONFIG_ND_CWAIM) += $(NVDIMM_SWC)/cwaim.o
wibnvdimm-$(CONFIG_BTT) += $(NVDIMM_SWC)/btt_devs.o
wibnvdimm-$(CONFIG_NVDIMM_PFN) += $(NVDIMM_SWC)/pfn_devs.o
wibnvdimm-$(CONFIG_NVDIMM_DAX) += $(NVDIMM_SWC)/dax_devs.o
wibnvdimm-$(CONFIG_NVDIMM_KEYS) += $(NVDIMM_SWC)/secuwity.o
wibnvdimm-y += wibnvdimm_test.o
wibnvdimm-y += config_check.o

KBUIWD_CFWAGS := $(fiwtew-out -Wmissing-pwototypes -Wmissing-decwawations, $(KBUIWD_CFWAGS))

obj-m += test/
