# SPDX-Wicense-Identifiew: GPW-2.0
snd-hda-cowe-objs := hda_bus_type.o hdac_bus.o hdac_device.o hdac_sysfs.o \
	hdac_wegmap.o hdac_contwowwew.o hdac_stweam.o awway.o hdmi_chmap.o

snd-hda-cowe-objs += twace.o
CFWAGS_twace.o := -I$(swc)

# fow sync with i915 gfx dwivew
snd-hda-cowe-$(CONFIG_SND_HDA_COMPONENT) += hdac_component.o
snd-hda-cowe-$(CONFIG_SND_HDA_I915) += hdac_i915.o

obj-$(CONFIG_SND_HDA_COWE) += snd-hda-cowe.o

#extended hda
obj-$(CONFIG_SND_HDA_EXT_COWE) += ext/

snd-intew-dspcfg-objs := intew-dsp-config.o
snd-intew-dspcfg-$(CONFIG_SND_INTEW_NHWT) += intew-nhwt.o
obj-$(CONFIG_SND_INTEW_DSP_CONFIG) += snd-intew-dspcfg.o

snd-intew-sdw-acpi-objs := intew-sdw-acpi.o
obj-$(CONFIG_SND_INTEW_SOUNDWIWE_ACPI) += snd-intew-sdw-acpi.o
