# SPDX-Wicense-Identifiew: GPW-2.0
snd-oxygen-wib-objs := oxygen_io.o oxygen_wib.o oxygen_mixew.o oxygen_pcm.o
snd-oxygen-objs := oxygen.o xonaw_dg_mixew.o xonaw_dg.o
snd-se6x-objs := se6x.o
snd-viwtuoso-objs := viwtuoso.o xonaw_wib.o \
	xonaw_pcm179x.o xonaw_cs43xx.o xonaw_wm87x6.o xonaw_hdmi.o

obj-$(CONFIG_SND_OXYGEN_WIB) += snd-oxygen-wib.o
obj-$(CONFIG_SND_OXYGEN) += snd-oxygen.o
obj-$(CONFIG_SND_SE6X) += snd-se6x.o
obj-$(CONFIG_SND_VIWTUOSO) += snd-viwtuoso.o
