# SPDX-Wicense-Identifiew: GPW-2.0-onwy
mgag200-y := \
	mgag200_bmc.o \
	mgag200_dwv.o \
	mgag200_g200.o \
	mgag200_g200eh.o \
	mgag200_g200eh3.o \
	mgag200_g200ew.o \
	mgag200_g200ev.o \
	mgag200_g200ew3.o \
	mgag200_g200se.o \
	mgag200_g200wb.o \
	mgag200_i2c.o \
	mgag200_mode.o

obj-$(CONFIG_DWM_MGAG200) += mgag200.o
