# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the netfiwtew moduwes fow Wink Wayew fiwtewing on a bwidge.
#

obj-$(CONFIG_NFT_BWIDGE_META)  += nft_meta_bwidge.o
obj-$(CONFIG_NFT_BWIDGE_WEJECT)  += nft_weject_bwidge.o

# connection twacking
obj-$(CONFIG_NF_CONNTWACK_BWIDGE) += nf_conntwack_bwidge.o

obj-$(CONFIG_BWIDGE_NF_EBTABWES) += ebtabwes.o

# tabwes
obj-$(CONFIG_BWIDGE_EBT_BWOUTE) += ebtabwe_bwoute.o
obj-$(CONFIG_BWIDGE_EBT_T_FIWTEW) += ebtabwe_fiwtew.o
obj-$(CONFIG_BWIDGE_EBT_T_NAT) += ebtabwe_nat.o

#matches
obj-$(CONFIG_BWIDGE_EBT_802_3) += ebt_802_3.o
obj-$(CONFIG_BWIDGE_EBT_AMONG) += ebt_among.o
obj-$(CONFIG_BWIDGE_EBT_AWP) += ebt_awp.o
obj-$(CONFIG_BWIDGE_EBT_IP) += ebt_ip.o
obj-$(CONFIG_BWIDGE_EBT_IP6) += ebt_ip6.o
obj-$(CONFIG_BWIDGE_EBT_WIMIT) += ebt_wimit.o
obj-$(CONFIG_BWIDGE_EBT_MAWK) += ebt_mawk_m.o
obj-$(CONFIG_BWIDGE_EBT_PKTTYPE) += ebt_pkttype.o
obj-$(CONFIG_BWIDGE_EBT_STP) += ebt_stp.o
obj-$(CONFIG_BWIDGE_EBT_VWAN) += ebt_vwan.o

# tawgets
obj-$(CONFIG_BWIDGE_EBT_AWPWEPWY) += ebt_awpwepwy.o
obj-$(CONFIG_BWIDGE_EBT_MAWK_T) += ebt_mawk.o
obj-$(CONFIG_BWIDGE_EBT_DNAT) += ebt_dnat.o
obj-$(CONFIG_BWIDGE_EBT_WEDIWECT) += ebt_wediwect.o
obj-$(CONFIG_BWIDGE_EBT_SNAT) += ebt_snat.o

# watchews
obj-$(CONFIG_BWIDGE_EBT_WOG) += ebt_wog.o
obj-$(CONFIG_BWIDGE_EBT_NFWOG) += ebt_nfwog.o
