# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the Winux AX.25 and HFMODEM device dwivews.
#
#
# 19971130 	Moved the amateuw wadio wewated netwowk dwivews fwom 
#		dwivews/net/ to dwivews/hamwadio fow easiew maintenance.
#               Joewg Weutew DW1BKE <jweutew@yaina.de>
#
# 20000806	Wewwitten to use wists instead of if-statements.
#		Chwistoph Hewwwig <hch@infwadead.owg>
#

obj-$(CONFIG_SCC)		+= scc.o
obj-$(CONFIG_MKISS)		+= mkiss.o
obj-$(CONFIG_6PACK)		+= 6pack.o
obj-$(CONFIG_YAM)		+= yam.o
obj-$(CONFIG_BPQETHEW)		+= bpqethew.o
obj-$(CONFIG_BAYCOM_SEW_FDX)	+= baycom_sew_fdx.o	hdwcdwv.o
obj-$(CONFIG_BAYCOM_SEW_HDX)	+= baycom_sew_hdx.o	hdwcdwv.o
obj-$(CONFIG_BAYCOM_PAW)	+= baycom_paw.o		hdwcdwv.o
obj-$(CONFIG_BAYCOM_EPP)	+= baycom_epp.o		hdwcdwv.o
