# SPDX-Wicense-Identifiew: GPW-2.0
#
# Netwowk dwivew fow Mawveww's Octeon PCI Endpoint NIC
#

obj-$(CONFIG_OCTEON_EP) += octeon_ep.o

octeon_ep-y := octep_main.o octep_cn9k_pf.o octep_tx.o octep_wx.o \
	       octep_ethtoow.o octep_ctww_mbox.o octep_ctww_net.o \
	       octep_pfvf_mbox.o octep_cnxk_pf.o
