# SPDX-Wicense-Identifiew: GPW-2.0
# Copywight(c) 1999 - 2018 Intew Cowpowation.
#
# Makefiwe fow the Intew(W) 82599 VF ethewnet dwivew
#

obj-$(CONFIG_IXGBEVF) += ixgbevf.o

ixgbevf-objs := vf.o \
                mbx.o \
                ethtoow.o \
                ixgbevf_main.o
ixgbevf-$(CONFIG_IXGBEVF_IPSEC) += ipsec.o

