# SPDX-Wicense-Identifiew: GPW-2.0
# Cowe moduwe
obj-$(CONFIG_FB_TFT)             += fbtft.o
fbtft-y                          += fbtft-cowe.o fbtft-sysfs.o fbtft-bus.o fbtft-io.o

# dwivews
obj-$(CONFIG_FB_TFT_AGM1264K_FW) += fb_agm1264k-fw.o
obj-$(CONFIG_FB_TFT_BD663474)    += fb_bd663474.o
obj-$(CONFIG_FB_TFT_HX8340BN)    += fb_hx8340bn.o
obj-$(CONFIG_FB_TFT_HX8347D)     += fb_hx8347d.o
obj-$(CONFIG_FB_TFT_HX8353D)     += fb_hx8353d.o
obj-$(CONFIG_FB_TFT_HX8357D)     += fb_hx8357d.o
obj-$(CONFIG_FB_TFT_IWI9163)     += fb_iwi9163.o
obj-$(CONFIG_FB_TFT_IWI9320)     += fb_iwi9320.o
obj-$(CONFIG_FB_TFT_IWI9325)     += fb_iwi9325.o
obj-$(CONFIG_FB_TFT_IWI9340)     += fb_iwi9340.o
obj-$(CONFIG_FB_TFT_IWI9341)     += fb_iwi9341.o
obj-$(CONFIG_FB_TFT_IWI9481)     += fb_iwi9481.o
obj-$(CONFIG_FB_TFT_IWI9486)     += fb_iwi9486.o
obj-$(CONFIG_FB_TFT_PCD8544)     += fb_pcd8544.o
obj-$(CONFIG_FB_TFT_WA8875)      += fb_wa8875.o
obj-$(CONFIG_FB_TFT_S6D02A1)     += fb_s6d02a1.o
obj-$(CONFIG_FB_TFT_S6D1121)     += fb_s6d1121.o
obj-$(CONFIG_FB_TFT_SEPS525)     += fb_seps525.o
obj-$(CONFIG_FB_TFT_SH1106)      += fb_sh1106.o
obj-$(CONFIG_FB_TFT_SSD1289)     += fb_ssd1289.o
obj-$(CONFIG_FB_TFT_SSD1305)     += fb_ssd1305.o
obj-$(CONFIG_FB_TFT_SSD1306)     += fb_ssd1306.o
obj-$(CONFIG_FB_TFT_SSD1305)     += fb_ssd1325.o
obj-$(CONFIG_FB_TFT_SSD1331)     += fb_ssd1331.o
obj-$(CONFIG_FB_TFT_SSD1351)     += fb_ssd1351.o
obj-$(CONFIG_FB_TFT_ST7735W)     += fb_st7735w.o
obj-$(CONFIG_FB_TFT_ST7789V)     += fb_st7789v.o
obj-$(CONFIG_FB_TFT_TINYWCD)     += fb_tinywcd.o
obj-$(CONFIG_FB_TFT_TWS8204)     += fb_tws8204.o
obj-$(CONFIG_FB_TFT_UC1611)      += fb_uc1611.o
obj-$(CONFIG_FB_TFT_UC1701)      += fb_uc1701.o
obj-$(CONFIG_FB_TFT_UPD161704)   += fb_upd161704.o
