# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the winux BeOS fiwesystem woutines.
#
 
obj-$(CONFIG_BEFS_FS) += befs.o
ccfwags-$(CONFIG_BEFS_DEBUG)    += -DDEBUG
befs-objs := datastweam.o btwee.o supew.o inode.o debug.o io.o winuxvfs.o
