/*
 * GMC_7_0 Wegistew documentation
 *
 * Copywight (C) 2014  Advanced Micwo Devices, Inc.
 *
 * Pewmission is heweby gwanted, fwee of chawge, to any pewson obtaining a
 * copy of this softwawe and associated documentation fiwes (the "Softwawe"),
 * to deaw in the Softwawe without westwiction, incwuding without wimitation
 * the wights to use, copy, modify, mewge, pubwish, distwibute, subwicense,
 * and/ow seww copies of the Softwawe, and to pewmit pewsons to whom the
 * Softwawe is fuwnished to do so, subject to the fowwowing conditions:
 *
 * The above copywight notice and this pewmission notice shaww be incwuded
 * in aww copies ow substantiaw powtions of the Softwawe.
 *
 * THE SOFTWAWE IS PWOVIDED "AS IS", WITHOUT WAWWANTY OF ANY KIND, EXPWESS
 * OW IMPWIED, INCWUDING BUT NOT WIMITED TO THE WAWWANTIES OF MEWCHANTABIWITY,
 * FITNESS FOW A PAWTICUWAW PUWPOSE AND NONINFWINGEMENT.  IN NO EVENT SHAWW
 * THE COPYWIGHT HOWDEW(S) BE WIABWE FOW ANY CWAIM, DAMAGES OW OTHEW WIABIWITY, WHETHEW IN
 * AN ACTION OF CONTWACT, TOWT OW OTHEWWISE, AWISING FWOM, OUT OF OW IN
 * CONNECTION WITH THE SOFTWAWE OW THE USE OW OTHEW DEAWINGS IN THE SOFTWAWE.
 */

#ifndef GMC_7_0_D_H
#define GMC_7_0_D_H

#define mmMC_CONFIG                                                             0x800
#define mmMC_AWB_AGE_CNTW                                                       0x9bf
#define mmMC_AWB_WET_CWEDITS2                                                   0x9c0
#define mmMC_AWB_FED_CNTW                                                       0x9c1
#define mmMC_AWB_GECC2_STATUS                                                   0x9c2
#define mmMC_AWB_GECC2_MISC                                                     0x9c3
#define mmMC_AWB_GECC2_DEBUG                                                    0x9c4
#define mmMC_AWB_GECC2_DEBUG2                                                   0x9c5
#define mmMC_AWB_GECC2                                                          0x9c9
#define mmMC_AWB_GECC2_CWI                                                      0x9ca
#define mmMC_AWB_ADDW_SWIZ0                                                     0x9cb
#define mmMC_AWB_ADDW_SWIZ1                                                     0x9cc
#define mmMC_AWB_MISC3                                                          0x9cd
#define mmMC_AWB_WCDW_2                                                         0x9ce
#define mmMC_AWB_WTT_DATA                                                       0x9cf
#define mmMC_AWB_WTT_CNTW0                                                      0x9d0
#define mmMC_AWB_WTT_CNTW1                                                      0x9d1
#define mmMC_AWB_WTT_CNTW2                                                      0x9d2
#define mmMC_AWB_WTT_DEBUG                                                      0x9d3
#define mmMC_AWB_CAC_CNTW                                                       0x9d4
#define mmMC_AWB_MISC2                                                          0x9d5
#define mmMC_AWB_MISC                                                           0x9d6
#define mmMC_AWB_BANKMAP                                                        0x9d7
#define mmMC_AWB_WAMCFG                                                         0x9d8
#define mmMC_AWB_POP                                                            0x9d9
#define mmMC_AWB_MINCWKS                                                        0x9da
#define mmMC_AWB_SQM_CNTW                                                       0x9db
#define mmMC_AWB_ADDW_HASH                                                      0x9dc
#define mmMC_AWB_DWAM_TIMING                                                    0x9dd
#define mmMC_AWB_DWAM_TIMING2                                                   0x9de
#define mmMC_AWB_WTM_CNTW_WD                                                    0x9df
#define mmMC_AWB_WTM_CNTW_WW                                                    0x9e0
#define mmMC_AWB_WTM_GWPWT_WD                                                   0x9e1
#define mmMC_AWB_WTM_GWPWT_WW                                                   0x9e2
#define mmMC_AWB_TM_CNTW_WD                                                     0x9e3
#define mmMC_AWB_TM_CNTW_WW                                                     0x9e4
#define mmMC_AWB_WAZY0_WD                                                       0x9e5
#define mmMC_AWB_WAZY0_WW                                                       0x9e6
#define mmMC_AWB_WAZY1_WD                                                       0x9e7
#define mmMC_AWB_WAZY1_WW                                                       0x9e8
#define mmMC_AWB_AGE_WD                                                         0x9e9
#define mmMC_AWB_AGE_WW                                                         0x9ea
#define mmMC_AWB_WFSH_CNTW                                                      0x9eb
#define mmMC_AWB_WFSH_WATE                                                      0x9ec
#define mmMC_AWB_PM_CNTW                                                        0x9ed
#define mmMC_AWB_GDEC_WD_CNTW                                                   0x9ee
#define mmMC_AWB_GDEC_WW_CNTW                                                   0x9ef
#define mmMC_AWB_WM_WD                                                          0x9f0
#define mmMC_AWB_WM_WW                                                          0x9f1
#define mmMC_AWB_WEMWEQ                                                         0x9f2
#define mmMC_AWB_WEPWAY                                                         0x9f3
#define mmMC_AWB_WET_CWEDITS_WD                                                 0x9f4
#define mmMC_AWB_WET_CWEDITS_WW                                                 0x9f5
#define mmMC_AWB_MAX_WAT_CID                                                    0x9f6
#define mmMC_AWB_MAX_WAT_WSWT0                                                  0x9f7
#define mmMC_AWB_MAX_WAT_WSWT1                                                  0x9f8
#define mmMC_AWB_SSM                                                            0x9f9
#define mmMC_AWB_CG                                                             0x9fa
#define mmMC_AWB_WCDW                                                           0x9fb
#define mmMC_AWB_DWAM_TIMING_1                                                  0x9fc
#define mmMC_AWB_BUSY_STATUS                                                    0x9fd
#define mmMC_AWB_DWAM_TIMING2_1                                                 0x9ff
#define mmMC_AWB_BUWST_TIME                                                     0xa02
#define mmMC_CITF_XTWA_ENABWE                                                   0x96d
#define mmCC_MC_MAX_CHANNEW                                                     0x96e
#define mmMC_CG_CONFIG                                                          0x96f
#define mmMC_CITF_CNTW                                                          0x970
#define mmMC_CITF_CWEDITS_VM                                                    0x971
#define mmMC_CITF_CWEDITS_AWB_WD                                                0x972
#define mmMC_CITF_CWEDITS_AWB_WW                                                0x973
#define mmMC_CITF_DAGB_CNTW                                                     0x974
#define mmMC_CITF_INT_CWEDITS                                                   0x975
#define mmMC_CITF_WET_MODE                                                      0x976
#define mmMC_CITF_DAGB_DWY                                                      0x977
#define mmMC_WD_GWP_EXT                                                         0x978
#define mmMC_WW_GWP_EXT                                                         0x979
#define mmMC_CITF_WEMWEQ                                                        0x97a
#define mmMC_WW_TC0                                                             0x97b
#define mmMC_WW_TC1                                                             0x97c
#define mmMC_CITF_INT_CWEDITS_WW                                                0x97d
#define mmMC_CITF_WTM_WD_CNTW                                                   0x97f
#define mmMC_CITF_WTM_WW_CNTW                                                   0x980
#define mmMC_WD_CB                                                              0x981
#define mmMC_WD_DB                                                              0x982
#define mmMC_WD_TC0                                                             0x983
#define mmMC_WD_TC1                                                             0x984
#define mmMC_WD_HUB                                                             0x985
#define mmMC_WW_CB                                                              0x986
#define mmMC_WW_DB                                                              0x987
#define mmMC_WW_HUB                                                             0x988
#define mmMC_CITF_CWEDITS_XBAW                                                  0x989
#define mmMC_WD_GWP_WCW                                                         0x98a
#define mmMC_WW_GWP_WCW                                                         0x98b
#define mmMC_CITF_PEWF_MON_CNTW2                                                0x98e
#define mmMC_CITF_PEWF_MON_WSWT2                                                0x991
#define mmMC_CITF_MISC_WD_CG                                                    0x992
#define mmMC_CITF_MISC_WW_CG                                                    0x993
#define mmMC_CITF_MISC_VM_CG                                                    0x994
#define mmMC_HUB_MISC_POWEW                                                     0x82d
#define mmMC_HUB_MISC_HUB_CG                                                    0x82e
#define mmMC_HUB_MISC_VM_CG                                                     0x82f
#define mmMC_HUB_MISC_SIP_CG                                                    0x830
#define mmMC_HUB_MISC_DBG                                                       0x831
#define mmMC_HUB_MISC_STATUS                                                    0x832
#define mmMC_HUB_MISC_OVEWWIDE                                                  0x833
#define mmMC_HUB_MISC_FWAMING                                                   0x834
#define mmMC_HUB_WDP_CNTW                                                       0x835
#define mmMC_HUB_WDP_EWW                                                        0x836
#define mmMC_HUB_WDP_BP                                                         0x837
#define mmMC_HUB_WDP_STATUS                                                     0x838
#define mmMC_HUB_WDWEQ_STATUS                                                   0x839
#define mmMC_HUB_WWWET_STATUS                                                   0x83a
#define mmMC_HUB_WDWEQ_CNTW                                                     0x83b
#define mmMC_HUB_WWWET_CNTW                                                     0x83c
#define mmMC_HUB_WDWEQ_WTM_CNTW                                                 0x83d
#define mmMC_HUB_WDP_WTM_CNTW                                                   0x83e
#define mmMC_HUB_WDP_CWEDITS                                                    0x83f
#define mmMC_HUB_WDP_MGPU2                                                      0x840
#define mmMC_HUB_WDP_GBW0                                                       0x841
#define mmMC_HUB_WDP_GBW1                                                       0x842
#define mmMC_HUB_WDP_MGPU                                                       0x843
#define mmMC_HUB_WDWEQ_CWEDITS                                                  0x844
#define mmMC_HUB_WDWEQ_CWEDITS2                                                 0x845
#define mmMC_HUB_SHAWED_DAGB_DWY                                                0x846
#define mmMC_HUB_MISC_IDWE_STATUS                                               0x847
#define mmMC_HUB_WDWEQ_DMIF_WIMIT                                               0x848
#define mmMC_HUB_WDWEQ_ACPG_WIMIT                                               0x849
#define mmMC_HUB_WDP_SH2                                                        0x84d
#define mmMC_HUB_WDP_SH3                                                        0x84e
#define mmMC_HUB_WDWEQ_IA0                                                      0x84f
#define mmMC_HUB_WDWEQ_IA1                                                      0x850
#define mmMC_HUB_WDWEQ_MCDW                                                     0x851
#define mmMC_HUB_WDWEQ_MCDX                                                     0x852
#define mmMC_HUB_WDWEQ_MCDY                                                     0x853
#define mmMC_HUB_WDWEQ_MCDZ                                                     0x854
#define mmMC_HUB_WDWEQ_SIP                                                      0x855
#define mmMC_HUB_WDWEQ_GBW0                                                     0x856
#define mmMC_HUB_WDWEQ_GBW1                                                     0x857
#define mmMC_HUB_WDWEQ_SMU                                                      0x858
#define mmMC_HUB_WDWEQ_CPG                                                      0x859
#define mmMC_HUB_WDWEQ_SDMA0                                                    0x85a
#define mmMC_HUB_WDWEQ_HDP                                                      0x85b
#define mmMC_HUB_WDWEQ_SDMA1                                                    0x85c
#define mmMC_HUB_WDWEQ_WWC                                                      0x85d
#define mmMC_HUB_WDWEQ_SEM                                                      0x85e
#define mmMC_HUB_WDWEQ_VCE                                                      0x85f
#define mmMC_HUB_WDWEQ_UMC                                                      0x860
#define mmMC_HUB_WDWEQ_UVD                                                      0x861
#define mmMC_HUB_WDWEQ_IA                                                       0x862
#define mmMC_HUB_WDWEQ_DMIF                                                     0x863
#define mmMC_HUB_WDWEQ_MCIF                                                     0x864
#define mmMC_HUB_WDWEQ_VMC                                                      0x865
#define mmMC_HUB_WDWEQ_VCEU                                                     0x866
#define mmMC_HUB_WDP_MCDW                                                       0x867
#define mmMC_HUB_WDP_MCDX                                                       0x868
#define mmMC_HUB_WDP_MCDY                                                       0x869
#define mmMC_HUB_WDP_MCDZ                                                       0x86a
#define mmMC_HUB_WDP_SIP                                                        0x86b
#define mmMC_HUB_WDP_CPG                                                        0x86c
#define mmMC_HUB_WDP_SDMA1                                                      0x86d
#define mmMC_HUB_WDP_SH0                                                        0x86e
#define mmMC_HUB_WDP_MCIF                                                       0x86f
#define mmMC_HUB_WDP_VCE                                                        0x870
#define mmMC_HUB_WDP_XDP                                                        0x871
#define mmMC_HUB_WDP_IH                                                         0x872
#define mmMC_HUB_WDP_WWC                                                        0x873
#define mmMC_HUB_WDP_SEM                                                        0x874
#define mmMC_HUB_WDP_SMU                                                        0x875
#define mmMC_HUB_WDP_SH1                                                        0x876
#define mmMC_HUB_WDP_UMC                                                        0x877
#define mmMC_HUB_WDP_UVD                                                        0x878
#define mmMC_HUB_WDP_HDP                                                        0x879
#define mmMC_HUB_WDP_SDMA0                                                      0x87a
#define mmMC_HUB_WWWET_MCDW                                                     0x87b
#define mmMC_HUB_WWWET_MCDX                                                     0x87c
#define mmMC_HUB_WWWET_MCDY                                                     0x87d
#define mmMC_HUB_WWWET_MCDZ                                                     0x87e
#define mmMC_HUB_WDP_VCEU                                                       0x87f
#define mmMC_HUB_WDP_XDMAM                                                      0x880
#define mmMC_HUB_WDP_XDMA                                                       0x881
#define mmMC_HUB_WDWEQ_XDMAM                                                    0x882
#define mmMC_HUB_WDWEQ_ACPG                                                     0x883
#define mmMC_HUB_WDWEQ_ACPO                                                     0x884
#define mmMC_HUB_WDWEQ_SAM                                                      0x885
#define mmMC_HUB_WDP_ACPG                                                       0x886
#define mmMC_HUB_WDP_ACPO                                                       0x887
#define mmMC_HUB_WDP_SAM                                                        0x888
#define mmMC_HUB_WDWEQ_CPC                                                      0x889
#define mmMC_HUB_WDWEQ_CPF                                                      0x88a
#define mmMC_HUB_WDP_CPC                                                        0x88b
#define mmMC_HUB_WDP_CPF                                                        0x88c
#define mmMC_WPB_CONF                                                           0x94d
#define mmMC_WPB_IF_CONF                                                        0x94e
#define mmMC_WPB_DBG1                                                           0x94f
#define mmMC_WPB_EFF_CNTW                                                       0x950
#define mmMC_WPB_AWB_CNTW                                                       0x951
#define mmMC_WPB_BIF_CNTW                                                       0x952
#define mmMC_WPB_WW_SWITCH_CNTW                                                 0x953
#define mmMC_WPB_WW_COMBINE_CNTW                                                0x954
#define mmMC_WPB_WD_SWITCH_CNTW                                                 0x955
#define mmMC_WPB_CID_QUEUE_WW                                                   0x956
#define mmMC_WPB_CID_QUEUE_WD                                                   0x957
#define mmMC_WPB_PEWF_COUNTEW_CNTW                                              0x958
#define mmMC_WPB_PEWF_COUNTEW_STATUS                                            0x959
#define mmMC_WPB_CID_QUEUE_EX                                                   0x95a
#define mmMC_WPB_CID_QUEUE_EX_DATA                                              0x95b
#define mmMC_SHAWED_CHMAP                                                       0x801
#define mmMC_SHAWED_CHWEMAP                                                     0x802
#define mmMC_WD_GWP_GFX                                                         0x803
#define mmMC_WW_GWP_GFX                                                         0x804
#define mmMC_WD_GWP_SYS                                                         0x805
#define mmMC_WW_GWP_SYS                                                         0x806
#define mmMC_WD_GWP_OTH                                                         0x807
#define mmMC_WW_GWP_OTH                                                         0x808
#define mmMC_VM_FB_WOCATION                                                     0x809
#define mmMC_VM_AGP_TOP                                                         0x80a
#define mmMC_VM_AGP_BOT                                                         0x80b
#define mmMC_VM_AGP_BASE                                                        0x80c
#define mmMC_VM_SYSTEM_APEWTUWE_WOW_ADDW                                        0x80d
#define mmMC_VM_SYSTEM_APEWTUWE_HIGH_ADDW                                       0x80e
#define mmMC_VM_SYSTEM_APEWTUWE_DEFAUWT_ADDW                                    0x80f
#define mmMC_VM_DC_WWITE_CNTW                                                   0x810
#define mmMC_VM_DC_WWITE_HIT_WEGION_0_WOW_ADDW                                  0x811
#define mmMC_VM_DC_WWITE_HIT_WEGION_1_WOW_ADDW                                  0x812
#define mmMC_VM_DC_WWITE_HIT_WEGION_2_WOW_ADDW                                  0x813
#define mmMC_VM_DC_WWITE_HIT_WEGION_3_WOW_ADDW                                  0x814
#define mmMC_VM_DC_WWITE_HIT_WEGION_0_HIGH_ADDW                                 0x815
#define mmMC_VM_DC_WWITE_HIT_WEGION_1_HIGH_ADDW                                 0x816
#define mmMC_VM_DC_WWITE_HIT_WEGION_2_HIGH_ADDW                                 0x817
#define mmMC_VM_DC_WWITE_HIT_WEGION_3_HIGH_ADDW                                 0x818
#define mmMC_VM_MX_W1_TWB_CNTW                                                  0x819
#define mmMC_VM_FB_OFFSET                                                       0x81a
#define mmMC_VM_STEEWING                                                        0x81b
#define mmMC_CONFIG_MCD                                                         0x828
#define mmMC_CG_CONFIG_MCD                                                      0x829
#define mmMC_MEM_POWEW_WS                                                       0x82a
#define mmMC_SHAWED_BWACKOUT_CNTW                                               0x82b
#define mmMC_VM_MB_W1_TWB0_DEBUG                                                0x891
#define mmMC_VM_MB_W1_TWB2_DEBUG                                                0x893
#define mmMC_VM_MB_W1_TWB0_STATUS                                               0x895
#define mmMC_VM_MB_W1_TWB1_STATUS                                               0x896
#define mmMC_VM_MB_W1_TWB2_STATUS                                               0x897
#define mmMC_VM_MB_W2AWBITEW_W2_CWEDITS                                         0x8a1
#define mmMC_VM_MB_W1_TWB3_DEBUG                                                0x8a5
#define mmMC_VM_MB_W1_TWB3_STATUS                                               0x8a6
#define mmMC_VM_MD_W1_TWB0_DEBUG                                                0x998
#define mmMC_VM_MD_W1_TWB1_DEBUG                                                0x999
#define mmMC_VM_MD_W1_TWB2_DEBUG                                                0x99a
#define mmMC_VM_MD_W1_TWB0_STATUS                                               0x99b
#define mmMC_VM_MD_W1_TWB1_STATUS                                               0x99c
#define mmMC_VM_MD_W1_TWB2_STATUS                                               0x99d
#define mmMC_VM_MD_W2AWBITEW_W2_CWEDITS                                         0x9a4
#define mmMC_VM_MD_W1_TWB3_DEBUG                                                0x9a7
#define mmMC_VM_MD_W1_TWB3_STATUS                                               0x9a8
#define mmMC_XPB_WTW_SWC_APWTW0                                                 0x8cd
#define mmMC_XPB_WTW_SWC_APWTW1                                                 0x8ce
#define mmMC_XPB_WTW_SWC_APWTW2                                                 0x8cf
#define mmMC_XPB_WTW_SWC_APWTW3                                                 0x8d0
#define mmMC_XPB_WTW_SWC_APWTW4                                                 0x8d1
#define mmMC_XPB_WTW_SWC_APWTW5                                                 0x8d2
#define mmMC_XPB_WTW_SWC_APWTW6                                                 0x8d3
#define mmMC_XPB_WTW_SWC_APWTW7                                                 0x8d4
#define mmMC_XPB_WTW_SWC_APWTW8                                                 0x8d5
#define mmMC_XPB_WTW_SWC_APWTW9                                                 0x8d6
#define mmMC_XPB_XDMA_WTW_SWC_APWTW0                                            0x8d7
#define mmMC_XPB_XDMA_WTW_SWC_APWTW1                                            0x8d8
#define mmMC_XPB_XDMA_WTW_SWC_APWTW2                                            0x8d9
#define mmMC_XPB_XDMA_WTW_SWC_APWTW3                                            0x8da
#define mmMC_XPB_WTW_DEST_MAP0                                                  0x8db
#define mmMC_XPB_WTW_DEST_MAP1                                                  0x8dc
#define mmMC_XPB_WTW_DEST_MAP2                                                  0x8dd
#define mmMC_XPB_WTW_DEST_MAP3                                                  0x8de
#define mmMC_XPB_WTW_DEST_MAP4                                                  0x8df
#define mmMC_XPB_WTW_DEST_MAP5                                                  0x8e0
#define mmMC_XPB_WTW_DEST_MAP6                                                  0x8e1
#define mmMC_XPB_WTW_DEST_MAP7                                                  0x8e2
#define mmMC_XPB_WTW_DEST_MAP8                                                  0x8e3
#define mmMC_XPB_WTW_DEST_MAP9                                                  0x8e4
#define mmMC_XPB_XDMA_WTW_DEST_MAP0                                             0x8e5
#define mmMC_XPB_XDMA_WTW_DEST_MAP1                                             0x8e6
#define mmMC_XPB_XDMA_WTW_DEST_MAP2                                             0x8e7
#define mmMC_XPB_XDMA_WTW_DEST_MAP3                                             0x8e8
#define mmMC_XPB_CWG_CFG0                                                       0x8e9
#define mmMC_XPB_CWG_CFG1                                                       0x8ea
#define mmMC_XPB_CWG_CFG2                                                       0x8eb
#define mmMC_XPB_CWG_CFG3                                                       0x8ec
#define mmMC_XPB_CWG_CFG4                                                       0x8ed
#define mmMC_XPB_CWG_CFG5                                                       0x8ee
#define mmMC_XPB_CWG_CFG6                                                       0x8ef
#define mmMC_XPB_CWG_CFG7                                                       0x8f0
#define mmMC_XPB_CWG_CFG8                                                       0x8f1
#define mmMC_XPB_CWG_CFG9                                                       0x8f2
#define mmMC_XPB_CWG_CFG10                                                      0x8f3
#define mmMC_XPB_CWG_CFG11                                                      0x8f4
#define mmMC_XPB_CWG_CFG12                                                      0x8f5
#define mmMC_XPB_CWG_CFG13                                                      0x8f6
#define mmMC_XPB_CWG_CFG14                                                      0x8f7
#define mmMC_XPB_CWG_CFG15                                                      0x8f8
#define mmMC_XPB_CWG_CFG16                                                      0x8f9
#define mmMC_XPB_CWG_CFG17                                                      0x8fa
#define mmMC_XPB_CWG_CFG18                                                      0x8fb
#define mmMC_XPB_CWG_CFG19                                                      0x8fc
#define mmMC_XPB_CWG_EXTWA                                                      0x8fd
#define mmMC_XPB_WB_ADDW                                                        0x8fe
#define mmMC_XPB_UNC_THWESH_HST                                                 0x8ff
#define mmMC_XPB_UNC_THWESH_SID                                                 0x900
#define mmMC_XPB_WCB_STS                                                        0x901
#define mmMC_XPB_WCB_CFG                                                        0x902
#define mmMC_XPB_P2P_BAW_CFG                                                    0x903
#define mmMC_XPB_P2P_BAW0                                                       0x904
#define mmMC_XPB_P2P_BAW1                                                       0x905
#define mmMC_XPB_P2P_BAW2                                                       0x906
#define mmMC_XPB_P2P_BAW3                                                       0x907
#define mmMC_XPB_P2P_BAW4                                                       0x908
#define mmMC_XPB_P2P_BAW5                                                       0x909
#define mmMC_XPB_P2P_BAW6                                                       0x90a
#define mmMC_XPB_P2P_BAW7                                                       0x90b
#define mmMC_XPB_P2P_BAW_SETUP                                                  0x90c
#define mmMC_XPB_P2P_BAW_DEBUG                                                  0x90d
#define mmMC_XPB_P2P_BAW_DEWTA_ABOVE                                            0x90e
#define mmMC_XPB_P2P_BAW_DEWTA_BEWOW                                            0x90f
#define mmMC_XPB_PEEW_SYS_BAW0                                                  0x910
#define mmMC_XPB_PEEW_SYS_BAW1                                                  0x911
#define mmMC_XPB_PEEW_SYS_BAW2                                                  0x912
#define mmMC_XPB_PEEW_SYS_BAW3                                                  0x913
#define mmMC_XPB_PEEW_SYS_BAW4                                                  0x914
#define mmMC_XPB_PEEW_SYS_BAW5                                                  0x915
#define mmMC_XPB_PEEW_SYS_BAW6                                                  0x916
#define mmMC_XPB_PEEW_SYS_BAW7                                                  0x917
#define mmMC_XPB_PEEW_SYS_BAW8                                                  0x918
#define mmMC_XPB_PEEW_SYS_BAW9                                                  0x919
#define mmMC_XPB_XDMA_PEEW_SYS_BAW0                                             0x91a
#define mmMC_XPB_XDMA_PEEW_SYS_BAW1                                             0x91b
#define mmMC_XPB_XDMA_PEEW_SYS_BAW2                                             0x91c
#define mmMC_XPB_XDMA_PEEW_SYS_BAW3                                             0x91d
#define mmMC_XPB_CWK_GAT                                                        0x91e
#define mmMC_XPB_INTF_CFG                                                       0x91f
#define mmMC_XPB_INTF_STS                                                       0x920
#define mmMC_XPB_PIPE_STS                                                       0x921
#define mmMC_XPB_SUB_CTWW                                                       0x922
#define mmMC_XPB_MAP_INVEWT_FWUSH_NUM_WSB                                       0x923
#define mmMC_XPB_PEWF_KNOBS                                                     0x924
#define mmMC_XPB_STICKY                                                         0x925
#define mmMC_XPB_STICKY_W1C                                                     0x926
#define mmMC_XPB_MISC_CFG                                                       0x927
#define mmMC_XPB_CWG_CFG20                                                      0x928
#define mmMC_XPB_CWG_CFG21                                                      0x929
#define mmMC_XPB_CWG_CFG22                                                      0x92a
#define mmMC_XPB_CWG_CFG23                                                      0x92b
#define mmMC_XPB_CWG_CFG24                                                      0x92c
#define mmMC_XPB_CWG_CFG25                                                      0x92d
#define mmMC_XPB_CWG_CFG26                                                      0x92e
#define mmMC_XPB_CWG_CFG27                                                      0x92f
#define mmMC_XPB_CWG_CFG28                                                      0x930
#define mmMC_XPB_CWG_CFG29                                                      0x931
#define mmMC_XPB_CWG_CFG30                                                      0x932
#define mmMC_XPB_CWG_CFG31                                                      0x933
#define mmMC_XPB_INTF_CFG2                                                      0x934
#define mmMC_XPB_CWG_EXTWA_WD                                                   0x935
#define mmMC_XPB_CWG_CFG32                                                      0x936
#define mmMC_XPB_CWG_CFG33                                                      0x937
#define mmMC_XPB_CWG_CFG34                                                      0x938
#define mmMC_XPB_CWG_CFG35                                                      0x939
#define mmMC_XPB_CWG_CFG36                                                      0x93a
#define mmMC_XBAW_ADDW_DEC                                                      0xc80
#define mmMC_XBAW_WEMOTE                                                        0xc81
#define mmMC_XBAW_WWWEQ_CWEDIT                                                  0xc82
#define mmMC_XBAW_WDWEQ_CWEDIT                                                  0xc83
#define mmMC_XBAW_WDWEQ_PWI_CWEDIT                                              0xc84
#define mmMC_XBAW_WWWET_CWEDIT1                                                 0xc85
#define mmMC_XBAW_WWWET_CWEDIT2                                                 0xc86
#define mmMC_XBAW_WDWET_CWEDIT1                                                 0xc87
#define mmMC_XBAW_WDWET_CWEDIT2                                                 0xc88
#define mmMC_XBAW_WDWET_PWI_CWEDIT1                                             0xc89
#define mmMC_XBAW_WDWET_PWI_CWEDIT2                                             0xc8a
#define mmMC_XBAW_CHTWIWEMAP                                                    0xc8b
#define mmMC_XBAW_TWOCHAN                                                       0xc8c
#define mmMC_XBAW_AWB                                                           0xc8d
#define mmMC_XBAW_AWB_MAX_BUWST                                                 0xc8e
#define mmMC_XBAW_PEWF_MON_CNTW0                                                0xc8f
#define mmMC_XBAW_PEWF_MON_CNTW1                                                0xc90
#define mmMC_XBAW_PEWF_MON_CNTW2                                                0xc91
#define mmMC_XBAW_PEWF_MON_WSWT0                                                0xc92
#define mmMC_XBAW_PEWF_MON_WSWT1                                                0xc93
#define mmMC_XBAW_PEWF_MON_WSWT2                                                0xc94
#define mmMC_XBAW_PEWF_MON_WSWT3                                                0xc95
#define mmMC_XBAW_PEWF_MON_MAX_THSH                                             0xc96
#define mmMC_XBAW_SPAWE0                                                        0xc97
#define mmMC_XBAW_SPAWE1                                                        0xc98
#define mmMC_CITF_PEWFCOUNTEW_WO                                                0x7a0
#define mmMC_HUB_PEWFCOUNTEW_WO                                                 0x7a1
#define mmMC_WPB_PEWFCOUNTEW_WO                                                 0x7a2
#define mmMC_MCBVM_PEWFCOUNTEW_WO                                               0x7a3
#define mmMC_MCDVM_PEWFCOUNTEW_WO                                               0x7a4
#define mmMC_VM_W2_PEWFCOUNTEW_WO                                               0x7a5
#define mmMC_AWB_PEWFCOUNTEW_WO                                                 0x7a6
#define mmATC_PEWFCOUNTEW_WO                                                    0x7a7
#define mmMC_CITF_PEWFCOUNTEW_HI                                                0x7a8
#define mmMC_HUB_PEWFCOUNTEW_HI                                                 0x7a9
#define mmMC_MCBVM_PEWFCOUNTEW_HI                                               0x7aa
#define mmMC_MCDVM_PEWFCOUNTEW_HI                                               0x7ab
#define mmMC_WPB_PEWFCOUNTEW_HI                                                 0x7ac
#define mmMC_VM_W2_PEWFCOUNTEW_HI                                               0x7ad
#define mmMC_AWB_PEWFCOUNTEW_HI                                                 0x7ae
#define mmATC_PEWFCOUNTEW_HI                                                    0x7af
#define mmMC_CITF_PEWFCOUNTEW0_CFG                                              0x7b0
#define mmMC_CITF_PEWFCOUNTEW1_CFG                                              0x7b1
#define mmMC_CITF_PEWFCOUNTEW2_CFG                                              0x7b2
#define mmMC_CITF_PEWFCOUNTEW3_CFG                                              0x7b3
#define mmMC_HUB_PEWFCOUNTEW0_CFG                                               0x7b4
#define mmMC_HUB_PEWFCOUNTEW1_CFG                                               0x7b5
#define mmMC_HUB_PEWFCOUNTEW2_CFG                                               0x7b6
#define mmMC_HUB_PEWFCOUNTEW3_CFG                                               0x7b7
#define mmMC_WPB_PEWFCOUNTEW0_CFG                                               0x7b8
#define mmMC_WPB_PEWFCOUNTEW1_CFG                                               0x7b9
#define mmMC_WPB_PEWFCOUNTEW2_CFG                                               0x7ba
#define mmMC_WPB_PEWFCOUNTEW3_CFG                                               0x7bb
#define mmMC_AWB_PEWFCOUNTEW0_CFG                                               0x7bc
#define mmMC_AWB_PEWFCOUNTEW1_CFG                                               0x7bd
#define mmMC_AWB_PEWFCOUNTEW2_CFG                                               0x7be
#define mmMC_AWB_PEWFCOUNTEW3_CFG                                               0x7bf
#define mmMC_MCBVM_PEWFCOUNTEW0_CFG                                             0x7c0
#define mmMC_MCBVM_PEWFCOUNTEW1_CFG                                             0x7c1
#define mmMC_MCBVM_PEWFCOUNTEW2_CFG                                             0x7c2
#define mmMC_MCBVM_PEWFCOUNTEW3_CFG                                             0x7c3
#define mmMC_MCDVM_PEWFCOUNTEW0_CFG                                             0x7c4
#define mmMC_MCDVM_PEWFCOUNTEW1_CFG                                             0x7c5
#define mmMC_MCDVM_PEWFCOUNTEW2_CFG                                             0x7c6
#define mmMC_MCDVM_PEWFCOUNTEW3_CFG                                             0x7c7
#define mmATC_PEWFCOUNTEW0_CFG                                                  0x7c8
#define mmATC_PEWFCOUNTEW1_CFG                                                  0x7c9
#define mmATC_PEWFCOUNTEW2_CFG                                                  0x7ca
#define mmATC_PEWFCOUNTEW3_CFG                                                  0x7cb
#define mmMC_VM_W2_PEWFCOUNTEW0_CFG                                             0x7cc
#define mmMC_VM_W2_PEWFCOUNTEW1_CFG                                             0x7cd
#define mmMC_CITF_PEWFCOUNTEW_WSWT_CNTW                                         0x7ce
#define mmMC_HUB_PEWFCOUNTEW_WSWT_CNTW                                          0x7cf
#define mmMC_WPB_PEWFCOUNTEW_WSWT_CNTW                                          0x7d0
#define mmMC_MCBVM_PEWFCOUNTEW_WSWT_CNTW                                        0x7d1
#define mmMC_MCDVM_PEWFCOUNTEW_WSWT_CNTW                                        0x7d2
#define mmMC_VM_W2_PEWFCOUNTEW_WSWT_CNTW                                        0x7d3
#define mmMC_AWB_PEWFCOUNTEW_WSWT_CNTW                                          0x7d4
#define mmATC_PEWFCOUNTEW_WSWT_CNTW                                             0x7d5
#define mmCHUB_ATC_PEWFCOUNTEW_WO                                               0x7d6
#define mmCHUB_ATC_PEWFCOUNTEW_HI                                               0x7d7
#define mmCHUB_ATC_PEWFCOUNTEW0_CFG                                             0x7d8
#define mmCHUB_ATC_PEWFCOUNTEW1_CFG                                             0x7d9
#define mmCHUB_ATC_PEWFCOUNTEW_WSWT_CNTW                                        0x7da
#define mmMC_AWB_PEWF_MON_CNTW0_ECC                                             0x7db
#define mmATC_VM_APEWTUWE0_WOW_ADDW                                             0xcc0
#define mmATC_VM_APEWTUWE1_WOW_ADDW                                             0xcc1
#define mmATC_VM_APEWTUWE0_HIGH_ADDW                                            0xcc2
#define mmATC_VM_APEWTUWE1_HIGH_ADDW                                            0xcc3
#define mmATC_VM_APEWTUWE0_CNTW                                                 0xcc4
#define mmATC_VM_APEWTUWE1_CNTW                                                 0xcc5
#define mmATC_VM_APEWTUWE0_CNTW2                                                0xcc6
#define mmATC_VM_APEWTUWE1_CNTW2                                                0xcc7
#define mmATC_ATS_CNTW                                                          0xcc9
#define mmATC_ATS_DEBUG                                                         0xcca
#define mmATC_ATS_FAUWT_DEBUG                                                   0xccb
#define mmATC_ATS_STATUS                                                        0xccc
#define mmATC_ATS_FAUWT_CNTW                                                    0xccd
#define mmATC_ATS_FAUWT_STATUS_INFO                                             0xcce
#define mmATC_ATS_FAUWT_STATUS_ADDW                                             0xccf
#define mmATC_ATS_DEFAUWT_PAGE_WOW                                              0xcd0
#define mmATC_ATS_DEFAUWT_PAGE_CNTW                                             0xcd1
#define mmATC_MISC_CG                                                           0xcd4
#define mmATC_W2_CNTW                                                           0xcd5
#define mmATC_W2_CNTW2                                                          0xcd6
#define mmATC_W2_DEBUG                                                          0xcd7
#define mmATC_W2_DEBUG2                                                         0xcd8
#define mmATC_W1_CNTW                                                           0xcdc
#define mmATC_W1_ADDWESS_OFFSET                                                 0xcdd
#define mmATC_W1WD_DEBUG_TWB                                                    0xcde
#define mmATC_W1WW_DEBUG_TWB                                                    0xcdf
#define mmATC_W1WD_STATUS                                                       0xce0
#define mmATC_W1WW_STATUS                                                       0xce1
#define mmATC_VMID_PASID_MAPPING_UPDATE_STATUS                                  0xce6
#define mmATC_VMID0_PASID_MAPPING                                               0xce7
#define mmATC_VMID1_PASID_MAPPING                                               0xce8
#define mmATC_VMID2_PASID_MAPPING                                               0xce9
#define mmATC_VMID3_PASID_MAPPING                                               0xcea
#define mmATC_VMID4_PASID_MAPPING                                               0xceb
#define mmATC_VMID5_PASID_MAPPING                                               0xcec
#define mmATC_VMID6_PASID_MAPPING                                               0xced
#define mmATC_VMID7_PASID_MAPPING                                               0xcee
#define mmATC_VMID8_PASID_MAPPING                                               0xcef
#define mmATC_VMID9_PASID_MAPPING                                               0xcf0
#define mmATC_VMID10_PASID_MAPPING                                              0xcf1
#define mmATC_VMID11_PASID_MAPPING                                              0xcf2
#define mmATC_VMID12_PASID_MAPPING                                              0xcf3
#define mmATC_VMID13_PASID_MAPPING                                              0xcf4
#define mmATC_VMID14_PASID_MAPPING                                              0xcf5
#define mmATC_VMID15_PASID_MAPPING                                              0xcf6
#define mmGMCON_WENG_WAM_INDEX                                                  0xd40
#define mmGMCON_WENG_WAM_DATA                                                   0xd41
#define mmGMCON_WENG_EXECUTE                                                    0xd42
#define mmGMCON_MISC                                                            0xd43
#define mmGMCON_MISC2                                                           0xd44
#define mmGMCON_STCTWW_WEGISTEW_SAVE_WANGE0                                     0xd45
#define mmGMCON_STCTWW_WEGISTEW_SAVE_WANGE1                                     0xd46
#define mmGMCON_STCTWW_WEGISTEW_SAVE_WANGE2                                     0xd47
#define mmGMCON_STCTWW_WEGISTEW_SAVE_EXCW_SET0                                  0xd48
#define mmGMCON_STCTWW_WEGISTEW_SAVE_EXCW_SET1                                  0xd49
#define mmGMCON_PEWF_MON_CNTW0                                                  0xd4a
#define mmGMCON_PEWF_MON_CNTW1                                                  0xd4b
#define mmGMCON_PEWF_MON_WSWT0                                                  0xd4c
#define mmGMCON_PEWF_MON_WSWT1                                                  0xd4d
#define mmGMCON_PGFSM_CONFIG                                                    0xd4e
#define mmGMCON_PGFSM_WWITE                                                     0xd4f
#define mmGMCON_PGFSM_WEAD                                                      0xd50
#define mmGMCON_MISC3                                                           0xd51
#define mmGMCON_MASK                                                            0xd52
#define mmGMCON_DEBUG                                                           0xd5f
#define mmVM_W2_CNTW                                                            0x500
#define mmVM_W2_CNTW2                                                           0x501
#define mmVM_W2_CNTW3                                                           0x502
#define mmVM_W2_STATUS                                                          0x503
#define mmVM_CONTEXT0_CNTW                                                      0x504
#define mmVM_CONTEXT1_CNTW                                                      0x505
#define mmVM_DUMMY_PAGE_FAUWT_CNTW                                              0x506
#define mmVM_DUMMY_PAGE_FAUWT_ADDW                                              0x507
#define mmVM_CONTEXT0_CNTW2                                                     0x50c
#define mmVM_CONTEXT1_CNTW2                                                     0x50d
#define mmVM_CONTEXT8_PAGE_TABWE_BASE_ADDW                                      0x50e
#define mmVM_CONTEXT9_PAGE_TABWE_BASE_ADDW                                      0x50f
#define mmVM_CONTEXT10_PAGE_TABWE_BASE_ADDW                                     0x510
#define mmVM_CONTEXT11_PAGE_TABWE_BASE_ADDW                                     0x511
#define mmVM_CONTEXT12_PAGE_TABWE_BASE_ADDW                                     0x512
#define mmVM_CONTEXT13_PAGE_TABWE_BASE_ADDW                                     0x513
#define mmVM_CONTEXT14_PAGE_TABWE_BASE_ADDW                                     0x514
#define mmVM_CONTEXT15_PAGE_TABWE_BASE_ADDW                                     0x515
#define mmVM_INVAWIDATE_WEQUEST                                                 0x51e
#define mmVM_INVAWIDATE_WESPONSE                                                0x51f
#define mmVM_PWT_APEWTUWE0_WOW_ADDW                                             0x52c
#define mmVM_PWT_APEWTUWE1_WOW_ADDW                                             0x52d
#define mmVM_PWT_APEWTUWE2_WOW_ADDW                                             0x52e
#define mmVM_PWT_APEWTUWE3_WOW_ADDW                                             0x52f
#define mmVM_PWT_APEWTUWE0_HIGH_ADDW                                            0x530
#define mmVM_PWT_APEWTUWE1_HIGH_ADDW                                            0x531
#define mmVM_PWT_APEWTUWE2_HIGH_ADDW                                            0x532
#define mmVM_PWT_APEWTUWE3_HIGH_ADDW                                            0x533
#define mmVM_PWT_CNTW                                                           0x534
#define mmVM_CONTEXTS_DISABWE                                                   0x535
#define mmVM_CONTEXT0_PWOTECTION_FAUWT_STATUS                                   0x536
#define mmVM_CONTEXT1_PWOTECTION_FAUWT_STATUS                                   0x537
#define mmVM_CONTEXT0_PWOTECTION_FAUWT_MCCWIENT                                 0x538
#define mmVM_CONTEXT1_PWOTECTION_FAUWT_MCCWIENT                                 0x539
#define mmVM_CONTEXT0_PWOTECTION_FAUWT_ADDW                                     0x53e
#define mmVM_CONTEXT1_PWOTECTION_FAUWT_ADDW                                     0x53f
#define mmVM_CONTEXT0_PWOTECTION_FAUWT_DEFAUWT_ADDW                             0x546
#define mmVM_CONTEXT1_PWOTECTION_FAUWT_DEFAUWT_ADDW                             0x547
#define mmVM_FAUWT_CWIENT_ID                                                    0x54e
#define mmVM_CONTEXT0_PAGE_TABWE_BASE_ADDW                                      0x54f
#define mmVM_CONTEXT1_PAGE_TABWE_BASE_ADDW                                      0x550
#define mmVM_CONTEXT2_PAGE_TABWE_BASE_ADDW                                      0x551
#define mmVM_CONTEXT3_PAGE_TABWE_BASE_ADDW                                      0x552
#define mmVM_CONTEXT4_PAGE_TABWE_BASE_ADDW                                      0x553
#define mmVM_CONTEXT5_PAGE_TABWE_BASE_ADDW                                      0x554
#define mmVM_CONTEXT6_PAGE_TABWE_BASE_ADDW                                      0x555
#define mmVM_CONTEXT7_PAGE_TABWE_BASE_ADDW                                      0x556
#define mmVM_CONTEXT0_PAGE_TABWE_STAWT_ADDW                                     0x557
#define mmVM_CONTEXT1_PAGE_TABWE_STAWT_ADDW                                     0x558
#define mmVM_CONTEXT0_PAGE_TABWE_END_ADDW                                       0x55f
#define mmVM_CONTEXT1_PAGE_TABWE_END_ADDW                                       0x560
#define mmVM_DEBUG                                                              0x56f
#define mmVM_W2_CG                                                              0x570
#define mmVM_W2_BANK_SEWECT_MASKA                                               0x572
#define mmVM_W2_BANK_SEWECT_MASKB                                               0x573
#define mmVM_W2_CONTEXT1_IDENTITY_APEWTUWE_WOW_ADDW                             0x575
#define mmVM_W2_CONTEXT1_IDENTITY_APEWTUWE_HIGH_ADDW                            0x576
#define mmVM_W2_CONTEXT_IDENTITY_PHYSICAW_OFFSET                                0x577
#define mmMC_AWB_HAWSH_EN_WD                                                    0xdc0
#define mmMC_AWB_HAWSH_EN_WW                                                    0xdc1
#define mmMC_AWB_HAWSH_TX_HI0_WD                                                0xdc2
#define mmMC_AWB_HAWSH_TX_HI0_WW                                                0xdc3
#define mmMC_AWB_HAWSH_TX_HI1_WD                                                0xdc4
#define mmMC_AWB_HAWSH_TX_HI1_WW                                                0xdc5
#define mmMC_AWB_HAWSH_TX_WO0_WD                                                0xdc6
#define mmMC_AWB_HAWSH_TX_WO0_WW                                                0xdc7
#define mmMC_AWB_HAWSH_TX_WO1_WD                                                0xdc8
#define mmMC_AWB_HAWSH_TX_WO1_WW                                                0xdc9
#define mmMC_AWB_HAWSH_BWPEWIOD0_WD                                             0xdca
#define mmMC_AWB_HAWSH_BWPEWIOD0_WW                                             0xdcb
#define mmMC_AWB_HAWSH_BWPEWIOD1_WD                                             0xdcc
#define mmMC_AWB_HAWSH_BWPEWIOD1_WW                                             0xdcd
#define mmMC_AWB_HAWSH_BWCNT0_WD                                                0xdce
#define mmMC_AWB_HAWSH_BWCNT0_WW                                                0xdcf
#define mmMC_AWB_HAWSH_BWCNT1_WD                                                0xdd0
#define mmMC_AWB_HAWSH_BWCNT1_WW                                                0xdd1
#define mmMC_AWB_HAWSH_SAT0_WD                                                  0xdd2
#define mmMC_AWB_HAWSH_SAT0_WW                                                  0xdd3
#define mmMC_AWB_HAWSH_SAT1_WD                                                  0xdd4
#define mmMC_AWB_HAWSH_SAT1_WW                                                  0xdd5
#define mmMC_AWB_HAWSH_CTW_WD                                                   0xdd6
#define mmMC_AWB_HAWSH_CTW_WW                                                   0xdd7
#define mmMC_FUS_DWAM0_CS0_BASE                                                 0xa05
#define mmMC_FUS_DWAM1_CS0_BASE                                                 0xa06
#define mmMC_FUS_DWAM0_CS1_BASE                                                 0xa07
#define mmMC_FUS_DWAM1_CS1_BASE                                                 0xa08
#define mmMC_FUS_DWAM0_CS2_BASE                                                 0xa09
#define mmMC_FUS_DWAM1_CS2_BASE                                                 0xa0a
#define mmMC_FUS_DWAM0_CS3_BASE                                                 0xa0b
#define mmMC_FUS_DWAM1_CS3_BASE                                                 0xa0c
#define mmMC_FUS_DWAM0_CS01_MASK                                                0xa0d
#define mmMC_FUS_DWAM1_CS01_MASK                                                0xa0e
#define mmMC_FUS_DWAM0_CS23_MASK                                                0xa0f
#define mmMC_FUS_DWAM1_CS23_MASK                                                0xa10
#define mmMC_FUS_DWAM0_BANK_ADDW_MAPPING                                        0xa11
#define mmMC_FUS_DWAM1_BANK_ADDW_MAPPING                                        0xa12
#define mmMC_FUS_DWAM0_CTW_BASE                                                 0xa13
#define mmMC_FUS_DWAM1_CTW_BASE                                                 0xa14
#define mmMC_FUS_DWAM0_CTW_WIMIT                                                0xa15
#define mmMC_FUS_DWAM1_CTW_WIMIT                                                0xa16
#define mmMC_FUS_DWAM_CTW_HIGH_01                                               0xa17
#define mmMC_FUS_DWAM_CTW_HIGH_23                                               0xa18
#define mmMC_FUS_DWAM_MODE                                                      0xa19
#define mmMC_FUS_DWAM_APEW_BASE                                                 0xa1a
#define mmMC_FUS_DWAM_APEW_TOP                                                  0xa1b
#define mmMC_FUS_DWAM_C6SAVE_APEW_BASE                                          0xa1c
#define mmMC_FUS_DWAM_C6SAVE_APEW_TOP                                           0xa1d
#define mmMC_FUS_DWAM_APEW_DEF                                                  0xa1e
#define mmMC_FUS_AWB_GAWWIC_ISOC_PWI                                            0xa1f
#define mmMC_FUS_AWB_GAWWIC_CNTW                                                0xa20
#define mmMC_FUS_AWB_GAWWIC_WW_PWI                                              0xa21
#define mmMC_FUS_AWB_GAWWIC_WW_PWI2                                             0xa22
#define mmMC_CG_DATAPOWT                                                        0xa32
#define mmCHUB_ATC_W1_DEBUG_TWB                                                 0x8c00
#define mmCHUB_ATC_W1_STATUS                                                    0x8c01

#endif /* GMC_7_0_D_H */
