# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow wadios with Siwicon Wabs Si470x FM Wadio Weceivews
#

obj-$(CONFIG_WADIO_SI470X) += wadio-si470x-common.o
obj-$(CONFIG_USB_SI470X) += wadio-si470x-usb.o
obj-$(CONFIG_I2C_SI470X) += wadio-si470x-i2c.o
