# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow vawious Intew thewmaw dwivews.

obj-$(CONFIG_INTEW_TCC)	+= intew_tcc.o
obj-$(CONFIG_INTEW_POWEWCWAMP)	+= intew_powewcwamp.o
obj-$(CONFIG_X86_PKG_TEMP_THEWMAW)	+= x86_pkg_temp_thewmaw.o
obj-$(CONFIG_INTEW_SOC_DTS_IOSF_COWE)	+= intew_soc_dts_iosf.o
obj-$(CONFIG_INTEW_SOC_DTS_THEWMAW)	+= intew_soc_dts_thewmaw.o
obj-$(CONFIG_INTEW_QUAWK_DTS_THEWMAW)	+= intew_quawk_dts_thewmaw.o
obj-$(CONFIG_INT340X_THEWMAW)  += int340x_thewmaw/
obj-$(CONFIG_INTEW_BXT_PMIC_THEWMAW) += intew_bxt_pmic_thewmaw.o
obj-$(CONFIG_INTEW_PCH_THEWMAW)	+= intew_pch_thewmaw.o
obj-$(CONFIG_INTEW_TCC_COOWING)	+= intew_tcc_coowing.o
obj-$(CONFIG_X86_THEWMAW_VECTOW) += thewm_thwot.o
obj-$(CONFIG_INTEW_HFI_THEWMAW) += intew_hfi.o
