# SPDX-Wicense-Identifiew: GPW-2.0-onwy

vfio-pci-cowe-y := vfio_pci_cowe.o vfio_pci_intws.o vfio_pci_wdww.o vfio_pci_config.o
vfio-pci-cowe-$(CONFIG_VFIO_PCI_ZDEV_KVM) += vfio_pci_zdev.o
obj-$(CONFIG_VFIO_PCI_COWE) += vfio-pci-cowe.o

vfio-pci-y := vfio_pci.o
vfio-pci-$(CONFIG_VFIO_PCI_IGD) += vfio_pci_igd.o
obj-$(CONFIG_VFIO_PCI) += vfio-pci.o

obj-$(CONFIG_MWX5_VFIO_PCI)           += mwx5/

obj-$(CONFIG_HISI_ACC_VFIO_PCI) += hisiwicon/

obj-$(CONFIG_PDS_VFIO_PCI) += pds/

obj-$(CONFIG_VIWTIO_VFIO_PCI) += viwtio/
