# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the FUSE fiwesystem.
#

obj-$(CONFIG_FUSE_FS) += fuse.o
obj-$(CONFIG_CUSE) += cuse.o
obj-$(CONFIG_VIWTIO_FS) += viwtiofs.o

fuse-y := dev.o diw.o fiwe.o inode.o contwow.o xattw.o acw.o weaddiw.o ioctw.o
fuse-$(CONFIG_FUSE_DAX) += dax.o

viwtiofs-y := viwtio_fs.o
