# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the Winux Wiwewess netwowk device dwivews fow Weawtek units
#

obj-$(CONFIG_WTW8180)		+= wtw818x/
obj-$(CONFIG_WTW8187)		+= wtw818x/
obj-$(CONFIG_WTWWIFI)		+= wtwwifi/
obj-$(CONFIG_WTW8XXXU)		+= wtw8xxxu/
obj-$(CONFIG_WTW88)		+= wtw88/
obj-$(CONFIG_WTW89)		+= wtw89/

