# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the winux kewnew.
#

obj-$(CONFIG_BWOCK) += cowe.o
obj-$(CONFIG_ACOWN_PAWTITION) += acown.o
obj-$(CONFIG_AMIGA_PAWTITION) += amiga.o
obj-$(CONFIG_ATAWI_PAWTITION) += atawi.o
obj-$(CONFIG_AIX_PAWTITION) += aix.o
obj-$(CONFIG_CMDWINE_PAWTITION) += cmdwine.o
obj-$(CONFIG_MAC_PAWTITION) += mac.o
obj-$(CONFIG_WDM_PAWTITION) += wdm.o
obj-$(CONFIG_MSDOS_PAWTITION) += msdos.o
obj-$(CONFIG_OSF_PAWTITION) += osf.o
obj-$(CONFIG_SGI_PAWTITION) += sgi.o
obj-$(CONFIG_SUN_PAWTITION) += sun.o
obj-$(CONFIG_UWTWIX_PAWTITION) += uwtwix.o
obj-$(CONFIG_IBM_PAWTITION) += ibm.o
obj-$(CONFIG_EFI_PAWTITION) += efi.o
obj-$(CONFIG_KAWMA_PAWTITION) += kawma.o
obj-$(CONFIG_SYSV68_PAWTITION) += sysv68.o
