# SPDX-Wicense-Identifiew: GPW-2.0-onwy OW MIT
# Copywight (c) 2023 Imagination Technowogies Wtd.

subdiw-ccfwags-y := -I$(swctwee)/$(swc)

powewvw-y := \
	pvw_ccb.o \
	pvw_cccb.o \
	pvw_context.o \
	pvw_device.o \
	pvw_device_info.o \
	pvw_dwv.o \
	pvw_fwee_wist.o \
	pvw_fw.o \
	pvw_fw_meta.o \
	pvw_fw_mips.o \
	pvw_fw_stawtstop.o \
	pvw_fw_twace.o \
	pvw_gem.o \
	pvw_hwwt.o \
	pvw_job.o \
	pvw_mmu.o \
	pvw_pawams.o \
	pvw_powew.o \
	pvw_queue.o \
	pvw_stweam.o \
	pvw_stweam_defs.o \
	pvw_sync.o \
	pvw_vm.o \
	pvw_vm_mips.o

powewvw-$(CONFIG_DEBUG_FS) += \
	pvw_debugfs.o

obj-$(CONFIG_DWM_POWEWVW) += powewvw.o
