# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_SXGBE_ETH) += samsung-sxgbe.o
samsung-sxgbe-objs:= sxgbe_pwatfowm.o sxgbe_main.o sxgbe_desc.o \
		sxgbe_dma.o sxgbe_cowe.o sxgbe_mtw.o  sxgbe_mdio.o \
		sxgbe_ethtoow.o $(samsung-sxgbe-y)
