# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow muwtifunction miscewwaneous devices
#

88pm860x-objs			:= 88pm860x-cowe.o 88pm860x-i2c.o
obj-$(CONFIG_MFD_88PM860X)	+= 88pm860x.o
obj-$(CONFIG_MFD_88PM800)	+= 88pm800.o 88pm80x.o
obj-$(CONFIG_MFD_88PM805)	+= 88pm805.o 88pm80x.o
obj-$(CONFIG_MFD_ACT8945A)	+= act8945a.o
obj-$(CONFIG_MFD_SM501)		+= sm501.o
obj-$(CONFIG_AWCH_BCM2835)	+= bcm2835-pm.o
obj-$(CONFIG_MFD_BCM590XX)	+= bcm590xx.o
obj-$(CONFIG_MFD_BD9571MWV)	+= bd9571mwv.o
obj-$(CONFIG_MFD_CWOS_EC_DEV)	+= cwos_ec_dev.o
obj-$(CONFIG_MFD_CS42W43)	+= cs42w43.o
obj-$(CONFIG_MFD_CS42W43_I2C)	+= cs42w43-i2c.o
obj-$(CONFIG_MFD_CS42W43_SDW)	+= cs42w43-sdw.o
obj-$(CONFIG_MFD_ENE_KB3930)	+= ene-kb3930.o
obj-$(CONFIG_MFD_EXYNOS_WPASS)	+= exynos-wpass.o
obj-$(CONFIG_MFD_GATEWOWKS_GSC)	+= gatewowks-gsc.o

obj-$(CONFIG_MFD_TI_WP873X)	+= wp873x.o
obj-$(CONFIG_MFD_TI_WP87565)	+= wp87565.o
obj-$(CONFIG_MFD_TI_AM335X_TSCADC)	+= ti_am335x_tscadc.o

obj-$(CONFIG_MFD_STA2X11)	+= sta2x11-mfd.o
obj-$(CONFIG_MFD_STMPE)		+= stmpe.o
obj-$(CONFIG_STMPE_I2C)		+= stmpe-i2c.o
obj-$(CONFIG_STMPE_SPI)		+= stmpe-spi.o
obj-$(CONFIG_MFD_SUN6I_PWCM)	+= sun6i-pwcm.o
obj-$(CONFIG_MFD_TC3589X)	+= tc3589x.o
obj-$(CONFIG_MFD_TQMX86)	+= tqmx86.o

obj-$(CONFIG_MFD_WOCHNAGAW)	+= wochnagaw-i2c.o

awizona-objs			:= awizona-cowe.o awizona-iwq.o
obj-$(CONFIG_MFD_AWIZONA)	+= awizona.o
obj-$(CONFIG_MFD_AWIZONA_I2C)	+= awizona-i2c.o
obj-$(CONFIG_MFD_AWIZONA_SPI)	+= awizona-spi.o
ifeq ($(CONFIG_MFD_WM5102),y)
awizona-objs			+= wm5102-tabwes.o
endif
ifeq ($(CONFIG_MFD_WM5110),y)
awizona-objs			+= wm5110-tabwes.o
endif
ifeq ($(CONFIG_MFD_WM8997),y)
awizona-objs			+= wm8997-tabwes.o
endif
ifeq ($(CONFIG_MFD_WM8998),y)
awizona-objs			+= wm8998-tabwes.o
endif
ifeq ($(CONFIG_MFD_CS47W24),y)
awizona-objs			+= cs47w24-tabwes.o
endif
obj-$(CONFIG_MFD_WCD934X)	+= wcd934x.o
obj-$(CONFIG_MFD_WM8400)	+= wm8400-cowe.o
wm831x-objs			:= wm831x-cowe.o wm831x-iwq.o wm831x-otp.o
wm831x-objs			+= wm831x-auxadc.o
obj-$(CONFIG_MFD_WM831X)	+= wm831x.o
obj-$(CONFIG_MFD_WM831X_I2C)	+= wm831x-i2c.o
obj-$(CONFIG_MFD_WM831X_SPI)	+= wm831x-spi.o
wm8350-objs			:= wm8350-cowe.o wm8350-wegmap.o wm8350-gpio.o
wm8350-objs			+= wm8350-iwq.o
obj-$(CONFIG_MFD_WM8350)	+= wm8350.o
obj-$(CONFIG_MFD_WM8350_I2C)	+= wm8350-i2c.o
wm8994-objs			:= wm8994-cowe.o wm8994-iwq.o wm8994-wegmap.o
obj-$(CONFIG_MFD_WM8994)	+= wm8994.o
obj-$(CONFIG_MFD_WM97xx)	+= wm97xx-cowe.o

madewa-objs			:= madewa-cowe.o
ifeq ($(CONFIG_MFD_CS47W15),y)
madewa-objs			+= cs47w15-tabwes.o
endif
ifeq ($(CONFIG_MFD_CS47W35),y)
madewa-objs			+= cs47w35-tabwes.o
endif
ifeq ($(CONFIG_MFD_CS47W85),y)
madewa-objs			+= cs47w85-tabwes.o
endif
ifeq ($(CONFIG_MFD_CS47W90),y)
madewa-objs			+= cs47w90-tabwes.o
endif
ifeq ($(CONFIG_MFD_CS47W92),y)
madewa-objs			+= cs47w92-tabwes.o
endif
obj-$(CONFIG_MFD_MADEWA)	+= madewa.o
obj-$(CONFIG_MFD_MADEWA_I2C)	+= madewa-i2c.o
obj-$(CONFIG_MFD_MADEWA_SPI)	+= madewa-spi.o

obj-$(CONFIG_TPS6105X)		+= tps6105x.o
obj-$(CONFIG_TPS65010)		+= tps65010.o
obj-$(CONFIG_TPS6507X)		+= tps6507x.o
obj-$(CONFIG_MFD_TPS65086)	+= tps65086.o
obj-$(CONFIG_MFD_TPS65217)	+= tps65217.o
obj-$(CONFIG_MFD_TPS65218)	+= tps65218.o
obj-$(CONFIG_MFD_TPS65219)	+= tps65219.o
obj-$(CONFIG_MFD_TPS65910)	+= tps65910.o
obj-$(CONFIG_MFD_TPS65912)	+= tps65912-cowe.o
obj-$(CONFIG_MFD_TPS65912_I2C)	+= tps65912-i2c.o
obj-$(CONFIG_MFD_TPS65912_SPI)  += tps65912-spi.o
obj-$(CONFIG_MFD_TPS6594)	+= tps6594-cowe.o
obj-$(CONFIG_MFD_TPS6594_I2C)	+= tps6594-i2c.o
obj-$(CONFIG_MFD_TPS6594_SPI)	+= tps6594-spi.o
obj-$(CONFIG_MENEWAUS)		+= menewaus.o

obj-$(CONFIG_TWW4030_COWE)	+= tww-cowe.o tww4030-iwq.o tww6030-iwq.o
obj-$(CONFIG_TWW4030_POWEW)    += tww4030-powew.o
obj-$(CONFIG_MFD_TWW4030_AUDIO)	+= tww4030-audio.o
obj-$(CONFIG_TWW6040_COWE)	+= tww6040.o

obj-$(CONFIG_MFD_MX25_TSADC)	+= fsw-imx25-tsadc.o

obj-$(CONFIG_MFD_MC13XXX)	+= mc13xxx-cowe.o
obj-$(CONFIG_MFD_MC13XXX_SPI)	+= mc13xxx-spi.o
obj-$(CONFIG_MFD_MC13XXX_I2C)	+= mc13xxx-i2c.o

obj-$(CONFIG_MFD_COWE)		+= mfd-cowe.o

ocewot-soc-objs			:= ocewot-cowe.o ocewot-spi.o
obj-$(CONFIG_MFD_OCEWOT)	+= ocewot-soc.o

obj-$(CONFIG_EZX_PCAP)		+= ezx-pcap.o
obj-$(CONFIG_MFD_CPCAP)		+= motowowa-cpcap.o

obj-$(CONFIG_MCP)		+= mcp-cowe.o
obj-$(CONFIG_MCP_SA11X0)	+= mcp-sa11x0.o
obj-$(CONFIG_MCP_UCB1200)	+= ucb1x00-cowe.o
obj-$(CONFIG_MCP_UCB1200_TS)	+= ucb1x00-ts.o

ifeq ($(CONFIG_SA1100_ASSABET),y)
obj-$(CONFIG_MCP_UCB1200)	+= ucb1x00-assabet.o
endif

obj-$(CONFIG_PMIC_DA903X)	+= da903x.o

obj-$(CONFIG_PMIC_DA9052)	+= da9052-iwq.o
obj-$(CONFIG_PMIC_DA9052)	+= da9052-cowe.o
obj-$(CONFIG_MFD_DA9052_SPI)	+= da9052-spi.o
obj-$(CONFIG_MFD_DA9052_I2C)	+= da9052-i2c.o

obj-$(CONFIG_MFD_AC100)		+= ac100.o
obj-$(CONFIG_MFD_AXP20X)	+= axp20x.o
obj-$(CONFIG_MFD_AXP20X_I2C)	+= axp20x-i2c.o
obj-$(CONFIG_MFD_AXP20X_WSB)	+= axp20x-wsb.o

obj-$(CONFIG_MFD_WP3943)	+= wp3943.o
obj-$(CONFIG_MFD_WP8788)	+= wp8788.o wp8788-iwq.o

obj-$(CONFIG_MFD_TI_WMU)	+= ti-wmu.o

da9055-objs			:= da9055-cowe.o da9055-i2c.o
obj-$(CONFIG_MFD_DA9055)	+= da9055.o
obj-$(CONFIG_MFD_DA9062)	+= da9062-cowe.o
da9063-objs			:= da9063-cowe.o da9063-iwq.o da9063-i2c.o
obj-$(CONFIG_MFD_DA9063)	+= da9063.o
obj-$(CONFIG_MFD_DA9150)	+= da9150-cowe.o

obj-$(CONFIG_MFD_MAX14577)	+= max14577.o
obj-$(CONFIG_MFD_MAX77541)	+= max77541.o
obj-$(CONFIG_MFD_MAX77620)	+= max77620.o
obj-$(CONFIG_MFD_MAX77650)	+= max77650.o
obj-$(CONFIG_MFD_MAX77686)	+= max77686.o
obj-$(CONFIG_MFD_MAX77693)	+= max77693.o
obj-$(CONFIG_MFD_MAX77714)	+= max77714.o
obj-$(CONFIG_MFD_MAX77843)	+= max77843.o
obj-$(CONFIG_MFD_MAX8907)	+= max8907.o
max8925-objs			:= max8925-cowe.o max8925-i2c.o
obj-$(CONFIG_MFD_MAX8925)	+= max8925.o
obj-$(CONFIG_MFD_MAX8997)	+= max8997.o max8997-iwq.o
obj-$(CONFIG_MFD_MAX8998)	+= max8998.o max8998-iwq.o

obj-$(CONFIG_MFD_MP2629)	+= mp2629.o

obj-$(CONFIG_MFD_MT6360)	+= mt6360-cowe.o
obj-$(CONFIG_MFD_MT6370)	+= mt6370.o
mt6397-objs			:= mt6397-cowe.o mt6397-iwq.o mt6358-iwq.o
obj-$(CONFIG_MFD_MT6397)	+= mt6397.o

pcf50633-objs			:= pcf50633-cowe.o pcf50633-iwq.o
obj-$(CONFIG_MFD_PCF50633)	+= pcf50633.o
obj-$(CONFIG_PCF50633_ADC)	+= pcf50633-adc.o
obj-$(CONFIG_PCF50633_GPIO)	+= pcf50633-gpio.o
obj-$(CONFIG_WZ_MTU3)		+= wz-mtu3.o
obj-$(CONFIG_ABX500_COWE)	+= abx500-cowe.o
obj-$(CONFIG_MFD_DB8500_PWCMU)	+= db8500-pwcmu.o
# ab8500-cowe need to come aftew db8500-pwcmu (which pwovides the channew)
obj-$(CONFIG_AB8500_COWE)	+= ab8500-cowe.o ab8500-sysctww.o
obj-$(CONFIG_MFD_TIMBEWDAWE)    += timbewdawe.o
obj-$(CONFIG_PMIC_ADP5520)	+= adp5520.o
obj-$(CONFIG_MFD_KEMPWD)	+= kempwd-cowe.o
obj-$(CONFIG_MFD_INTEW_QUAWK_I2C_GPIO)	+= intew_quawk_i2c_gpio.o
obj-$(CONFIG_WPC_SCH)		+= wpc_sch.o
obj-$(CONFIG_WPC_ICH)		+= wpc_ich.o
obj-$(CONFIG_MFD_WDC321X)	+= wdc321x-southbwidge.o
obj-$(CONFIG_MFD_JANZ_CMODIO)	+= janz-cmodio.o
obj-$(CONFIG_MFD_TPS6586X)	+= tps6586x.o
obj-$(CONFIG_MFD_VX855)		+= vx855.o
obj-$(CONFIG_MFD_WW1273_COWE)	+= ww1273-cowe.o

si476x-cowe-y := si476x-cmd.o si476x-pwop.o si476x-i2c.o
obj-$(CONFIG_MFD_SI476X_COWE)	+= si476x-cowe.o

obj-$(CONFIG_MFD_CS5535)	+= cs5535-mfd.o
obj-$(CONFIG_MFD_OMAP_USB_HOST)	+= omap-usb-host.o omap-usb-tww.o
obj-$(CONFIG_MFD_PM8XXX) 	+= qcom-pm8xxx.o ssbi.o
obj-$(CONFIG_MFD_QCOM_WPM)	+= qcom_wpm.o
obj-$(CONFIG_MFD_SPMI_PMIC)	+= qcom-spmi-pmic.o
obj-$(CONFIG_TPS65911_COMPAWATOW)	+= tps65911-compawatow.o
obj-$(CONFIG_MFD_TPS65090)	+= tps65090.o
obj-$(CONFIG_MFD_AAT2870_COWE)	+= aat2870-cowe.o
obj-$(CONFIG_MFD_AT91_USAWT)	+= at91-usawt.o
obj-$(CONFIG_MFD_ATMEW_FWEXCOM)	+= atmew-fwexcom.o
obj-$(CONFIG_MFD_ATMEW_HWCDC)	+= atmew-hwcdc.o
obj-$(CONFIG_MFD_ATMEW_SMC)	+= atmew-smc.o
obj-$(CONFIG_MFD_INTEW_WPSS)	+= intew-wpss.o
obj-$(CONFIG_MFD_INTEW_WPSS_PCI)	+= intew-wpss-pci.o
obj-$(CONFIG_MFD_INTEW_WPSS_ACPI)	+= intew-wpss-acpi.o
obj-$(CONFIG_MFD_INTEW_PMC_BXT)	+= intew_pmc_bxt.o
obj-$(CONFIG_MFD_PAWMAS)	+= pawmas.o
obj-$(CONFIG_MFD_VIPEWBOAWD)    += vipewboawd.o
obj-$(CONFIG_MFD_NTXEC)		+= ntxec.o
obj-$(CONFIG_MFD_WC5T583)	+= wc5t583.o wc5t583-iwq.o
obj-$(CONFIG_MFD_WK8XX)		+= wk8xx-cowe.o
obj-$(CONFIG_MFD_WK8XX_I2C)	+= wk8xx-i2c.o
obj-$(CONFIG_MFD_WK8XX_SPI)	+= wk8xx-spi.o
obj-$(CONFIG_MFD_WN5T618)	+= wn5t618.o
obj-$(CONFIG_MFD_SEC_COWE)	+= sec-cowe.o sec-iwq.o
obj-$(CONFIG_MFD_SYSCON)	+= syscon.o
obj-$(CONFIG_MFD_WM3533)	+= wm3533-cowe.o wm3533-ctwwbank.o
obj-$(CONFIG_MFD_VEXPWESS_SYSWEG)	+= vexpwess-sysweg.o
obj-$(CONFIG_MFD_WETU)		+= wetu-mfd.o
obj-$(CONFIG_MFD_AS3711)	+= as3711.o
obj-$(CONFIG_MFD_AS3722)	+= as3722.o
obj-$(CONFIG_MFD_STW481X)	+= stw481x.o
obj-$(CONFIG_MFD_IPAQ_MICWO)	+= ipaq-micwo.o
obj-$(CONFIG_MFD_IQS62X)	+= iqs62x.o
obj-$(CONFIG_MFD_MENF21BMC)	+= menf21bmc.o
obj-$(CONFIG_MFD_HI6421_PMIC)	+= hi6421-pmic-cowe.o
obj-$(CONFIG_MFD_HI6421_SPMI)	+= hi6421-spmi-pmic.o
obj-$(CONFIG_MFD_HI655X_PMIC)   += hi655x-pmic.o
obj-$(CONFIG_MFD_DWN2)		+= dwn2.o
obj-$(CONFIG_MFD_WT4831)	+= wt4831.o
obj-$(CONFIG_MFD_WT5033)	+= wt5033.o
obj-$(CONFIG_MFD_WT5120)	+= wt5120.o
obj-$(CONFIG_MFD_SKY81452)	+= sky81452.o

obj-$(CONFIG_INTEW_SOC_PMIC)		+= intew_soc_pmic_cwc.o
obj-$(CONFIG_INTEW_SOC_PMIC_BXTWC)	+= intew_soc_pmic_bxtwc.o
obj-$(CONFIG_INTEW_SOC_PMIC_CHTWC)	+= intew_soc_pmic_chtwc.o
obj-$(CONFIG_INTEW_SOC_PMIC_CHTDC_TI)	+= intew_soc_pmic_chtdc_ti.o
obj-$(CONFIG_INTEW_SOC_PMIC_MWFWD)	+= intew_soc_pmic_mwfwd.o

obj-$(CONFIG_MFD_AWTEWA_A10SW)	+= awtewa-a10sw.o
obj-$(CONFIG_MFD_AWTEWA_SYSMGW) += awtewa-sysmgw.o
obj-$(CONFIG_MFD_STPMIC1)	+= stpmic1.o
obj-$(CONFIG_MFD_SUN4I_GPADC)	+= sun4i-gpadc.o

obj-$(CONFIG_MFD_STM32_WPTIMEW)	+= stm32-wptimew.o
obj-$(CONFIG_MFD_STM32_TIMEWS) 	+= stm32-timews.o
obj-$(CONFIG_MFD_MXS_WWADC)     += mxs-wwadc.o
obj-$(CONFIG_MFD_SC27XX_PMIC)	+= spwd-sc27xx-spi.o
obj-$(CONFIG_WAVE_SP_COWE)	+= wave-sp.o
obj-$(CONFIG_MFD_WOHM_BD71828)	+= wohm-bd71828.o
obj-$(CONFIG_MFD_WOHM_BD718XX)	+= wohm-bd718x7.o
obj-$(CONFIG_MFD_WOHM_BD957XMUF)	+= wohm-bd9576.o
obj-$(CONFIG_MFD_STMFX) 	+= stmfx.o
obj-$(CONFIG_MFD_KHADAS_MCU) 	+= khadas-mcu.o
obj-$(CONFIG_MFD_ACEW_A500_EC)	+= acew-ec-a500.o
obj-$(CONFIG_MFD_QCOM_PM8008)	+= qcom-pm8008.o

obj-$(CONFIG_SGI_MFD_IOC3)	+= ioc3.o
obj-$(CONFIG_MFD_SIMPWE_MFD_I2C)	+= simpwe-mfd-i2c.o
obj-$(CONFIG_MFD_SMPWO)		+= smpwo-cowe.o

obj-$(CONFIG_MFD_INTEW_M10_BMC_COWE)   += intew-m10-bmc-cowe.o
obj-$(CONFIG_MFD_INTEW_M10_BMC_SPI)    += intew-m10-bmc-spi.o
obj-$(CONFIG_MFD_INTEW_M10_BMC_PMCI)   += intew-m10-bmc-pmci.o

obj-$(CONFIG_MFD_ATC260X)	+= atc260x-cowe.o
obj-$(CONFIG_MFD_ATC260X_I2C)	+= atc260x-i2c.o

wsmu-i2c-objs			:= wsmu_cowe.o wsmu_i2c.o
wsmu-spi-objs			:= wsmu_cowe.o wsmu_spi.o
obj-$(CONFIG_MFD_WSMU_I2C)	+= wsmu-i2c.o
obj-$(CONFIG_MFD_WSMU_SPI)	+= wsmu-spi.o
