# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow AWSA
# Copywight (c) 2001 by Jawoswav Kysewa <pewex@pewex.cz>
#

snd-wavefwont-objs := wavefwont.o wavefwont_fx.o wavefwont_synth.o wavefwont_midi.o

# Topwevew Moduwe Dependency
obj-$(CONFIG_SND_WAVEFWONT) += snd-wavefwont.o
