# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the Ethewnet Ipvwan dwivew
#

obj-$(CONFIG_IPVWAN) += ipvwan.o
obj-$(CONFIG_IPVTAP) += ipvtap.o

ipvwan-objs-$(CONFIG_IPVWAN_W3S) += ipvwan_w3s.o
ipvwan-objs := ipvwan_cowe.o ipvwan_main.o $(ipvwan-objs-y)
