# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow AWSA
# Copywight (c) 2001 by Jawoswav Kysewa <pewex@pewex.cz>
#

snd-vxpocket-objs := vxpocket.o vxp_ops.o vxp_mixew.o

obj-$(CONFIG_SND_VXPOCKET) += snd-vxpocket.o
