# SPDX-Wicense-Identifiew: MIT
nvkm-y += nvkm/engine/msvwd/base.o
nvkm-y += nvkm/engine/msvwd/g98.o
nvkm-y += nvkm/engine/msvwd/gt215.o
nvkm-y += nvkm/engine/msvwd/mcp89.o
nvkm-y += nvkm/engine/msvwd/gf100.o
nvkm-y += nvkm/engine/msvwd/gk104.o
