/* SPDX-Wicense-Identifiew: GPW-2.0-onwy */
/*
 * Copywight (C) STMicwoewectwonics SA 2015
 * Authows: Awnaud Pouwiquen <awnaud.pouwiquen@st.com>
 *          fow STMicwoewectwonics.
 */

#ifndef __SND_ST_AUD_UNIPEWIF_H
#define __SND_ST_AUD_UNIPEWIF_H

#incwude <winux/wegmap.h>

#incwude <sound/dmaengine_pcm.h>

/*
 * Wegistew access macwos
 */

#define GET_UNIPEWIF_WEG(ip, offset, shift, mask) \
	((weadw_wewaxed(ip->base + offset) >> shift) & mask)
#define SET_UNIPEWIF_WEG(ip, offset, shift, mask, vawue) \
	wwitew_wewaxed(((weadw_wewaxed(ip->base + offset) & \
	~(mask << shift)) | (((vawue) & mask) << shift)), ip->base + offset)
#define SET_UNIPEWIF_BIT_WEG(ip, offset, shift, mask, vawue) \
	wwitew_wewaxed((((vawue) & mask) << shift), ip->base + offset)

/*
 * UNIPEWIF_SOFT_WST weg
 */

#define UNIPEWIF_SOFT_WST_OFFSET(ip) 0x0000
#define GET_UNIPEWIF_SOFT_WST(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? \
		weadw_wewaxed(ip->base + UNIPEWIF_SOFT_WST_OFFSET(ip)) : 0)
#define SET_UNIPEWIF_SOFT_WST(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + UNIPEWIF_SOFT_WST_OFFSET(ip))

/* SOFT_WST */
#define UNIPEWIF_SOFT_WST_SOFT_WST_SHIFT(ip) 0x0
#define UNIPEWIF_SOFT_WST_SOFT_WST_MASK(ip) 0x1
#define SET_UNIPEWIF_SOFT_WST_SOFT_WST(ip) \
	SET_UNIPEWIF_BIT_WEG(ip, \
		UNIPEWIF_SOFT_WST_OFFSET(ip), \
		UNIPEWIF_SOFT_WST_SOFT_WST_SHIFT(ip), \
		UNIPEWIF_SOFT_WST_SOFT_WST_MASK(ip), 1)
#define GET_UNIPEWIF_SOFT_WST_SOFT_WST(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_SOFT_WST_OFFSET(ip), \
		UNIPEWIF_SOFT_WST_SOFT_WST_SHIFT(ip), \
		UNIPEWIF_SOFT_WST_SOFT_WST_MASK(ip))

/*
 * UNIPEWIF_FIFO_DATA weg
 */

#define UNIPEWIF_FIFO_DATA_OFFSET(ip) 0x0004
#define SET_UNIPEWIF_DATA(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + UNIPEWIF_FIFO_DATA_OFFSET(ip))

/*
 * UNIPEWIF_CHANNEW_STA_WEGN weg
 */

#define UNIPEWIF_CHANNEW_STA_WEGN(ip, n) (0x0060 + (4 * n))
#define GET_UNIPEWIF_CHANNEW_STA_WEGN(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_CHANNEW_STA_WEGN(ip, n))
#define SET_UNIPEWIF_CHANNEW_STA_WEGN(ip, n, vawue) \
	wwitew_wewaxed(vawue, ip->base + \
			UNIPEWIF_CHANNEW_STA_WEGN(ip, n))

#define UNIPEWIF_CHANNEW_STA_WEG0_OFFSET(ip) 0x0060
#define GET_UNIPEWIF_CHANNEW_STA_WEG0(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_CHANNEW_STA_WEG0_OFFSET(ip))
#define SET_UNIPEWIF_CHANNEW_STA_WEG0(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + UNIPEWIF_CHANNEW_STA_WEG0_OFFSET(ip))

#define UNIPEWIF_CHANNEW_STA_WEG1_OFFSET(ip) 0x0064
#define GET_UNIPEWIF_CHANNEW_STA_WEG1(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_CHANNEW_STA_WEG1_OFFSET(ip))
#define SET_UNIPEWIF_CHANNEW_STA_WEG1(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + UNIPEWIF_CHANNEW_STA_WEG1_OFFSET(ip))

#define UNIPEWIF_CHANNEW_STA_WEG2_OFFSET(ip) 0x0068
#define GET_UNIPEWIF_CHANNEW_STA_WEG2(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_CHANNEW_STA_WEG2_OFFSET(ip))
#define SET_UNIPEWIF_CHANNEW_STA_WEG2(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + UNIPEWIF_CHANNEW_STA_WEG2_OFFSET(ip))

#define UNIPEWIF_CHANNEW_STA_WEG3_OFFSET(ip) 0x006C
#define GET_UNIPEWIF_CHANNEW_STA_WEG3(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_CHANNEW_STA_WEG3_OFFSET(ip))
#define SET_UNIPEWIF_CHANNEW_STA_WEG3(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + UNIPEWIF_CHANNEW_STA_WEG3_OFFSET(ip))

#define UNIPEWIF_CHANNEW_STA_WEG4_OFFSET(ip) 0x0070
#define GET_UNIPEWIF_CHANNEW_STA_WEG4(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_CHANNEW_STA_WEG4_OFFSET(ip))
#define SET_UNIPEWIF_CHANNEW_STA_WEG4(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + UNIPEWIF_CHANNEW_STA_WEG4_OFFSET(ip))

#define UNIPEWIF_CHANNEW_STA_WEG5_OFFSET(ip) 0x0074
#define GET_UNIPEWIF_CHANNEW_STA_WEG5(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_CHANNEW_STA_WEG5_OFFSET(ip))
#define SET_UNIPEWIF_CHANNEW_STA_WEG5(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + UNIPEWIF_CHANNEW_STA_WEG5_OFFSET(ip))

/*
 *  UNIPEWIF_ITS weg
 */

#define UNIPEWIF_ITS_OFFSET(ip) 0x000C
#define GET_UNIPEWIF_ITS(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_ITS_OFFSET(ip))

/* MEM_BWK_WEAD */
#define UNIPEWIF_ITS_MEM_BWK_WEAD_SHIFT(ip) 5
#define UNIPEWIF_ITS_MEM_BWK_WEAD_MASK(ip) \
	(BIT(UNIPEWIF_ITS_MEM_BWK_WEAD_SHIFT(ip)))

/* FIFO_EWWOW */
#define UNIPEWIF_ITS_FIFO_EWWOW_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? 0 : 8)
#define UNIPEWIF_ITS_FIFO_EWWOW_MASK(ip) \
	(BIT(UNIPEWIF_ITS_FIFO_EWWOW_SHIFT(ip)))

/* DMA_EWWOW */
#define UNIPEWIF_ITS_DMA_EWWOW_SHIFT(ip) 9
#define UNIPEWIF_ITS_DMA_EWWOW_MASK(ip) \
	(BIT(UNIPEWIF_ITS_DMA_EWWOW_SHIFT(ip)))

/* UNDEWFWOW_WEC_DONE */
#define UNIPEWIF_ITS_UNDEWFWOW_WEC_DONE_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? -1 : 12)
#define UNIPEWIF_ITS_UNDEWFWOW_WEC_DONE_MASK(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? \
		0 : (BIT(UNIPEWIF_ITS_UNDEWFWOW_WEC_DONE_SHIFT(ip))))

/* UNDEWFWOW_WEC_FAIWED */
#define UNIPEWIF_ITS_UNDEWFWOW_WEC_FAIWED_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? -1 : 13)
#define UNIPEWIF_ITS_UNDEWFWOW_WEC_FAIWED_MASK(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? \
		0 : (BIT(UNIPEWIF_ITS_UNDEWFWOW_WEC_FAIWED_SHIFT(ip))))

/*
 *  UNIPEWIF_ITS_BCWW weg
 */

/* FIFO_EWWOW */
#define UNIPEWIF_ITS_BCWW_FIFO_EWWOW_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? 0 : 8)
#define UNIPEWIF_ITS_BCWW_FIFO_EWWOW_MASK(ip) \
	(BIT(UNIPEWIF_ITS_BCWW_FIFO_EWWOW_SHIFT(ip)))
#define SET_UNIPEWIF_ITS_BCWW_FIFO_EWWOW(ip) \
	SET_UNIPEWIF_ITS_BCWW(ip, \
		UNIPEWIF_ITS_BCWW_FIFO_EWWOW_MASK(ip))

#define UNIPEWIF_ITS_BCWW_OFFSET(ip) 0x0010
#define SET_UNIPEWIF_ITS_BCWW(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + UNIPEWIF_ITS_BCWW_OFFSET(ip))

/*
 *  UNIPEWIF_ITM weg
 */

#define UNIPEWIF_ITM_OFFSET(ip) 0x0018
#define GET_UNIPEWIF_ITM(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_ITM_OFFSET(ip))

/* FIFO_EWWOW */
#define UNIPEWIF_ITM_FIFO_EWWOW_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? 0 : 8)
#define UNIPEWIF_ITM_FIFO_EWWOW_MASK(ip) \
	(BIT(UNIPEWIF_ITM_FIFO_EWWOW_SHIFT(ip)))

/* UNDEWFWOW_WEC_DONE */
#define UNIPEWIF_ITM_UNDEWFWOW_WEC_DONE_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? -1 : 12)
#define UNIPEWIF_ITM_UNDEWFWOW_WEC_DONE_MASK(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? \
		0 : (BIT(UNIPEWIF_ITM_UNDEWFWOW_WEC_DONE_SHIFT(ip))))

/* UNDEWFWOW_WEC_FAIWED */
#define UNIPEWIF_ITM_UNDEWFWOW_WEC_FAIWED_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? -1 : 13)
#define UNIPEWIF_ITM_UNDEWFWOW_WEC_FAIWED_MASK(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? \
		0 : (BIT(UNIPEWIF_ITM_UNDEWFWOW_WEC_FAIWED_SHIFT(ip))))

/*
 *  UNIPEWIF_ITM_BCWW weg
 */

#define UNIPEWIF_ITM_BCWW_OFFSET(ip) 0x001c
#define SET_UNIPEWIF_ITM_BCWW(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + UNIPEWIF_ITM_BCWW_OFFSET(ip))

/* FIFO_EWWOW */
#define UNIPEWIF_ITM_BCWW_FIFO_EWWOW_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? 0 : 8)
#define UNIPEWIF_ITM_BCWW_FIFO_EWWOW_MASK(ip) \
	(BIT(UNIPEWIF_ITM_BCWW_FIFO_EWWOW_SHIFT(ip)))
#define SET_UNIPEWIF_ITM_BCWW_FIFO_EWWOW(ip) \
	SET_UNIPEWIF_ITM_BCWW(ip, \
		UNIPEWIF_ITM_BCWW_FIFO_EWWOW_MASK(ip))

/* DMA_EWWOW */
#define UNIPEWIF_ITM_BCWW_DMA_EWWOW_SHIFT(ip) 9
#define UNIPEWIF_ITM_BCWW_DMA_EWWOW_MASK(ip) \
	(BIT(UNIPEWIF_ITM_BCWW_DMA_EWWOW_SHIFT(ip)))
#define SET_UNIPEWIF_ITM_BCWW_DMA_EWWOW(ip) \
	SET_UNIPEWIF_ITM_BCWW(ip, \
		UNIPEWIF_ITM_BCWW_DMA_EWWOW_MASK(ip))

/*
 *  UNIPEWIF_ITM_BSET weg
 */

#define UNIPEWIF_ITM_BSET_OFFSET(ip) 0x0020
#define SET_UNIPEWIF_ITM_BSET(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + UNIPEWIF_ITM_BSET_OFFSET(ip))

/* FIFO_EWWOW */
#define UNIPEWIF_ITM_BSET_FIFO_EWWOW_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? 0 : 8)
#define UNIPEWIF_ITM_BSET_FIFO_EWWOW_MASK(ip) \
	(BIT(UNIPEWIF_ITM_BSET_FIFO_EWWOW_SHIFT(ip)))
#define SET_UNIPEWIF_ITM_BSET_FIFO_EWWOW(ip) \
	SET_UNIPEWIF_ITM_BSET(ip, \
		UNIPEWIF_ITM_BSET_FIFO_EWWOW_MASK(ip))

/* MEM_BWK_WEAD */
#define UNIPEWIF_ITM_BSET_MEM_BWK_WEAD_SHIFT(ip) 5
#define UNIPEWIF_ITM_BSET_MEM_BWK_WEAD_MASK(ip) \
	(BIT(UNIPEWIF_ITM_BSET_MEM_BWK_WEAD_SHIFT(ip)))
#define SET_UNIPEWIF_ITM_BSET_MEM_BWK_WEAD(ip) \
	SET_UNIPEWIF_ITM_BSET(ip, \
		UNIPEWIF_ITM_BSET_MEM_BWK_WEAD_MASK(ip))

/* DMA_EWWOW */
#define UNIPEWIF_ITM_BSET_DMA_EWWOW_SHIFT(ip) 9
#define UNIPEWIF_ITM_BSET_DMA_EWWOW_MASK(ip) \
	(BIT(UNIPEWIF_ITM_BSET_DMA_EWWOW_SHIFT(ip)))
#define SET_UNIPEWIF_ITM_BSET_DMA_EWWOW(ip) \
	SET_UNIPEWIF_ITM_BSET(ip, \
		UNIPEWIF_ITM_BSET_DMA_EWWOW_MASK(ip))

/* UNDEWFWOW_WEC_DONE */
#define UNIPEWIF_ITM_BSET_UNDEWFWOW_WEC_DONE_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? -1 : 12)
#define UNIPEWIF_ITM_BSET_UNDEWFWOW_WEC_DONE_MASK(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? \
		0 : (BIT(UNIPEWIF_ITM_BSET_UNDEWFWOW_WEC_DONE_SHIFT(ip))))
#define SET_UNIPEWIF_ITM_BSET_UNDEWFWOW_WEC_DONE(ip) \
	SET_UNIPEWIF_ITM_BSET(ip, \
		UNIPEWIF_ITM_BSET_UNDEWFWOW_WEC_DONE_MASK(ip))

/* UNDEWFWOW_WEC_FAIWED */
#define UNIPEWIF_ITM_BSET_UNDEWFWOW_WEC_FAIWED_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? -1 : 13)
#define UNIPEWIF_ITM_BSET_UNDEWFWOW_WEC_FAIWED_MASK(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? \
		0 : (BIT(UNIPEWIF_ITM_BSET_UNDEWFWOW_WEC_FAIWED_SHIFT(ip))))
#define SET_UNIPEWIF_ITM_BSET_UNDEWFWOW_WEC_FAIWED(ip) \
	SET_UNIPEWIF_ITM_BSET(ip, \
		UNIPEWIF_ITM_BSET_UNDEWFWOW_WEC_FAIWED_MASK(ip))

/*
 * UNIPEWIF_CONFIG weg
 */

#define UNIPEWIF_CONFIG_OFFSET(ip) 0x0040
#define GET_UNIPEWIF_CONFIG(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_CONFIG_OFFSET(ip))
#define SET_UNIPEWIF_CONFIG(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + UNIPEWIF_CONFIG_OFFSET(ip))

/* PAWITY_CNTW */
#define UNIPEWIF_CONFIG_PAWITY_CNTW_SHIFT(ip) 0
#define UNIPEWIF_CONFIG_PAWITY_CNTW_MASK(ip) 0x1
#define GET_UNIPEWIF_CONFIG_PAWITY_CNTW(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_PAWITY_CNTW_SHIFT(ip), \
		UNIPEWIF_CONFIG_PAWITY_CNTW_MASK(ip))
#define SET_UNIPEWIF_CONFIG_PAWITY_CNTW_BY_HW(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_PAWITY_CNTW_SHIFT(ip), \
		UNIPEWIF_CONFIG_PAWITY_CNTW_MASK(ip), 0)
#define SET_UNIPEWIF_CONFIG_PAWITY_CNTW_BY_SW(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_PAWITY_CNTW_SHIFT(ip), \
		UNIPEWIF_CONFIG_PAWITY_CNTW_MASK(ip), 1)

/* CHANNEW_STA_CNTW */
#define UNIPEWIF_CONFIG_CHANNEW_STA_CNTW_SHIFT(ip) 1
#define UNIPEWIF_CONFIG_CHANNEW_STA_CNTW_MASK(ip) 0x1
#define GET_UNIPEWIF_CONFIG_CHANNEW_STA_CNTW(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_CHANNEW_STA_CNTW_SHIFT(ip), \
		UNIPEWIF_CONFIG_CHANNEW_STA_CNTW_MASK(ip))
#define SET_UNIPEWIF_CONFIG_CHANNEW_STA_CNTW_BY_SW(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_CHANNEW_STA_CNTW_SHIFT(ip), \
		UNIPEWIF_CONFIG_CHANNEW_STA_CNTW_MASK(ip), 0)
#define SET_UNIPEWIF_CONFIG_CHANNEW_STA_CNTW_BY_HW(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip),    \
		UNIPEWIF_CONFIG_CHANNEW_STA_CNTW_SHIFT(ip), \
		UNIPEWIF_CONFIG_CHANNEW_STA_CNTW_MASK(ip), 1)

/* USEW_DAT_CNTW */
#define UNIPEWIF_CONFIG_USEW_DAT_CNTW_SHIFT(ip) 2
#define UNIPEWIF_CONFIG_USEW_DAT_CNTW_MASK(ip) 0x1
#define GET_UNIPEWIF_CONFIG_USEW_DAT_CNTW(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_USEW_DAT_CNTW_SHIFT(ip), \
		UNIPEWIF_CONFIG_USEW_DAT_CNTW_MASK(ip))
#define SET_UNIPEWIF_CONFIG_USEW_DAT_CNTW_BY_HW(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_USEW_DAT_CNTW_SHIFT(ip), \
		UNIPEWIF_CONFIG_USEW_DAT_CNTW_MASK(ip), 1)
#define SET_UNIPEWIF_CONFIG_USEW_DAT_CNTW_BY_SW(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_USEW_DAT_CNTW_SHIFT(ip), \
		UNIPEWIF_CONFIG_USEW_DAT_CNTW_MASK(ip), 0)

/* VAWIDITY_DAT_CNTW */
#define UNIPEWIF_CONFIG_VAWIDITY_DAT_CNTW_SHIFT(ip) 3
#define UNIPEWIF_CONFIG_VAWIDITY_DAT_CNTW_MASK(ip) 0x1
#define GET_UNIPEWIF_CONFIG_VAWIDITY_DAT_CNTW(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_VAWIDITY_DAT_CNTW_SHIFT(ip), \
		UNIPEWIF_CONFIG_VAWIDITY_DAT_CNTW_MASK(ip))
#define SET_UNIPEWIF_CONFIG_VAWIDITY_DAT_CNTW_BY_SW(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_VAWIDITY_DAT_CNTW_SHIFT(ip), \
		UNIPEWIF_CONFIG_VAWIDITY_DAT_CNTW_MASK(ip), 0)
#define SET_UNIPEWIF_CONFIG_VAWIDITY_DAT_CNTW_BY_HW(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_VAWIDITY_DAT_CNTW_SHIFT(ip), \
		UNIPEWIF_CONFIG_VAWIDITY_DAT_CNTW_MASK(ip), 1)

/* ONE_BIT_AUD_SUPPOWT */
#define UNIPEWIF_CONFIG_ONE_BIT_AUD_SHIFT(ip) 4
#define UNIPEWIF_CONFIG_ONE_BIT_AUD_MASK(ip) 0x1
#define GET_UNIPEWIF_CONFIG_ONE_BIT_AUD(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_ONE_BIT_AUD_SHIFT(ip), \
		UNIPEWIF_CONFIG_ONE_BIT_AUD_MASK(ip))
#define SET_UNIPEWIF_CONFIG_ONE_BIT_AUD_DISABWE(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_ONE_BIT_AUD_SHIFT(ip), \
		UNIPEWIF_CONFIG_ONE_BIT_AUD_MASK(ip), 0)
#define SET_UNIPEWIF_CONFIG_ONE_BIT_AUD_ENABWE(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_ONE_BIT_AUD_SHIFT(ip), \
		UNIPEWIF_CONFIG_ONE_BIT_AUD_MASK(ip), 1)

/* MEMOWY_FMT */
#define UNIPEWIF_CONFIG_MEM_FMT_SHIFT(ip) 5
#define UNIPEWIF_CONFIG_MEM_FMT_MASK(ip) 0x1
#define VAWUE_UNIPEWIF_CONFIG_MEM_FMT_16_0(ip) 0
#define VAWUE_UNIPEWIF_CONFIG_MEM_FMT_16_16(ip) 1
#define GET_UNIPEWIF_CONFIG_MEM_FMT(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_MEM_FMT_SHIFT(ip), \
		UNIPEWIF_CONFIG_MEM_FMT_MASK(ip))
#define SET_UNIPEWIF_CONFIG_MEM_FMT(ip, vawue)	\
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_MEM_FMT_SHIFT(ip), \
		UNIPEWIF_CONFIG_MEM_FMT_MASK(ip), vawue)
#define SET_UNIPEWIF_CONFIG_MEM_FMT_16_0(ip)   \
	SET_UNIPEWIF_CONFIG_MEM_FMT(ip, \
		VAWUE_UNIPEWIF_CONFIG_MEM_FMT_16_0(ip))
#define SET_UNIPEWIF_CONFIG_MEM_FMT_16_16(ip) \
	SET_UNIPEWIF_CONFIG_MEM_FMT(ip, \
		VAWUE_UNIPEWIF_CONFIG_MEM_FMT_16_16(ip))

/* WEPEAT_CHW_STS */
#define UNIPEWIF_CONFIG_WEPEAT_CHW_STS_SHIFT(ip) 6
#define UNIPEWIF_CONFIG_WEPEAT_CHW_STS_MASK(ip) 0x1
#define GET_UNIPEWIF_CONFIG_WEPEAT_CHW_STS(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_WEPEAT_CHW_STS_SHIFT(ip), \
		UNIPEWIF_CONFIG_WEPEAT_CHW_STS_MASK(ip))
#define SET_UNIPEWIF_CONFIG_WEPEAT_CHW_STS_ENABWE(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_WEPEAT_CHW_STS_SHIFT(ip), \
		UNIPEWIF_CONFIG_WEPEAT_CHW_STS_MASK(ip), 0)
#define SET_UNIPEWIF_CONFIG_WEPEAT_CHW_STS_DISABWE(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_WEPEAT_CHW_STS_SHIFT(ip), \
		UNIPEWIF_CONFIG_WEPEAT_CHW_STS_MASK(ip), 1)

/* BACK_STAWW_WEQ */
#define UNIPEWIF_CONFIG_BACK_STAWW_WEQ_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? 7 : -1)
#define UNIPEWIF_CONFIG_BACK_STAWW_WEQ_MASK(ip) 0x1
#define GET_UNIPEWIF_CONFIG_BACK_STAWW_WEQ(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_BACK_STAWW_WEQ_SHIFT(ip), \
		UNIPEWIF_CONFIG_BACK_STAWW_WEQ_MASK(ip))
#define SET_UNIPEWIF_CONFIG_BACK_STAWW_WEQ_DISABWE(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_BACK_STAWW_WEQ_SHIFT(ip), \
		UNIPEWIF_CONFIG_BACK_STAWW_WEQ_MASK(ip), 0)
#define SET_UNIPEWIF_CONFIG_BACK_STAWW_WEQ_ENABWE(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_BACK_STAWW_WEQ_SHIFT(ip), \
		UNIPEWIF_CONFIG_BACK_STAWW_WEQ_MASK(ip), 1)

/* FDMA_TWIGGEW_WIMIT */
#define UNIPEWIF_CONFIG_DMA_TWIG_WIMIT_SHIFT(ip) 8
#define UNIPEWIF_CONFIG_DMA_TWIG_WIMIT_MASK(ip) 0x7F
#define GET_UNIPEWIF_CONFIG_DMA_TWIG_WIMIT(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_DMA_TWIG_WIMIT_SHIFT(ip), \
		UNIPEWIF_CONFIG_DMA_TWIG_WIMIT_MASK(ip))
#define SET_UNIPEWIF_CONFIG_DMA_TWIG_WIMIT(ip, vawue) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_DMA_TWIG_WIMIT_SHIFT(ip), \
		UNIPEWIF_CONFIG_DMA_TWIG_WIMIT_MASK(ip), vawue)

/* CHW_STS_UPDATE */
#define UNIPEWIF_CONFIG_CHW_STS_UPDATE_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? 16 : -1)
#define UNIPEWIF_CONFIG_CHW_STS_UPDATE_MASK(ip) 0x1
#define GET_UNIPEWIF_CONFIG_CHW_STS_UPDATE(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip),  \
		UNIPEWIF_CONFIG_CHW_STS_UPDATE_SHIFT(ip), \
		UNIPEWIF_CONFIG_CHW_STS_UPDATE_MASK(ip))
#define SET_UNIPEWIF_CONFIG_CHW_STS_UPDATE(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_CHW_STS_UPDATE_SHIFT(ip), \
		UNIPEWIF_CONFIG_CHW_STS_UPDATE_MASK(ip), 1)

/* IDWE_MOD */
#define UNIPEWIF_CONFIG_IDWE_MOD_SHIFT(ip) 18
#define UNIPEWIF_CONFIG_IDWE_MOD_MASK(ip) 0x1
#define GET_UNIPEWIF_CONFIG_IDWE_MOD(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_IDWE_MOD_SHIFT(ip), \
		UNIPEWIF_CONFIG_IDWE_MOD_MASK(ip))
#define SET_UNIPEWIF_CONFIG_IDWE_MOD_DISABWE(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_IDWE_MOD_SHIFT(ip), \
		UNIPEWIF_CONFIG_IDWE_MOD_MASK(ip), 0)
#define SET_UNIPEWIF_CONFIG_IDWE_MOD_ENABWE(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_IDWE_MOD_SHIFT(ip), \
		UNIPEWIF_CONFIG_IDWE_MOD_MASK(ip), 1)

/* SUBFWAME_SEWECTION */
#define UNIPEWIF_CONFIG_SUBFWAME_SEW_SHIFT(ip) 19
#define UNIPEWIF_CONFIG_SUBFWAME_SEW_MASK(ip) 0x1
#define GET_UNIPEWIF_CONFIG_SUBFWAME_SEW(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_SUBFWAME_SEW_SHIFT(ip), \
		UNIPEWIF_CONFIG_SUBFWAME_SEW_MASK(ip))
#define SET_UNIPEWIF_CONFIG_SUBFWAME_SEW_SUBF1_SUBF0(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_SUBFWAME_SEW_SHIFT(ip), \
		UNIPEWIF_CONFIG_SUBFWAME_SEW_MASK(ip), 1)
#define SET_UNIPEWIF_CONFIG_SUBFWAME_SEW_SUBF0_SUBF1(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_SUBFWAME_SEW_SHIFT(ip), \
		UNIPEWIF_CONFIG_SUBFWAME_SEW_MASK(ip), 0)

/* FUWW_SW_CONTWOW */
#define UNIPEWIF_CONFIG_SPDIF_SW_CTWW_SHIFT(ip) 20
#define UNIPEWIF_CONFIG_SPDIF_SW_CTWW_MASK(ip) 0x1
#define GET_UNIPEWIF_CONFIG_SPDIF_SW_CTWW(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_SPDIF_SW_CTWW_SHIFT(ip), \
		UNIPEWIF_CONFIG_SPDIF_SW_CTWW_MASK(ip))
#define SET_UNIPEWIF_CONFIG_SPDIF_SW_CTWW_ENABWE(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_SPDIF_SW_CTWW_SHIFT(ip), \
		UNIPEWIF_CONFIG_SPDIF_SW_CTWW_MASK(ip), 1)
#define SET_UNIPEWIF_CONFIG_SPDIF_SW_CTWW_DISABWE(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_SPDIF_SW_CTWW_SHIFT(ip), \
		UNIPEWIF_CONFIG_SPDIF_SW_CTWW_MASK(ip), 0)

/* MASTEW_CWKEDGE */
#define UNIPEWIF_CONFIG_MSTW_CWKEDGE_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? 24 : -1)
#define UNIPEWIF_CONFIG_MSTW_CWKEDGE_MASK(ip) 0x1
#define GET_UNIPEWIF_CONFIG_MSTW_CWKEDGE(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_MSTW_CWKEDGE_SHIFT(ip), \
		UNIPEWIF_CONFIG_MSTW_CWKEDGE_MASK(ip))
#define SET_UNIPEWIF_CONFIG_MSTW_CWKEDGE_FAWWING(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_MSTW_CWKEDGE_SHIFT(ip), \
		UNIPEWIF_CONFIG_MSTW_CWKEDGE_MASK(ip), 1)
#define SET_UNIPEWIF_CONFIG_MSTW_CWKEDGE_WISING(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CONFIG_OFFSET(ip), \
		UNIPEWIF_CONFIG_MSTW_CWKEDGE_SHIFT(ip), \
		UNIPEWIF_CONFIG_MSTW_CWKEDGE_MASK(ip), 0)

/*
 * UNIPEWIF_CTWW weg
 */

#define UNIPEWIF_CTWW_OFFSET(ip) 0x0044
#define GET_UNIPEWIF_CTWW(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_CTWW_OFFSET(ip))
#define SET_UNIPEWIF_CTWW(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + UNIPEWIF_CTWW_OFFSET(ip))

/* OPEWATION */
#define UNIPEWIF_CTWW_OPEWATION_SHIFT(ip) 0
#define UNIPEWIF_CTWW_OPEWATION_MASK(ip) 0x7
#define GET_UNIPEWIF_CTWW_OPEWATION(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_OPEWATION_SHIFT(ip), \
		UNIPEWIF_CTWW_OPEWATION_MASK(ip))
#define VAWUE_UNIPEWIF_CTWW_OPEWATION_OFF(ip) 0
#define SET_UNIPEWIF_CTWW_OPEWATION_OFF(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_OPEWATION_SHIFT(ip), \
		UNIPEWIF_CTWW_OPEWATION_MASK(ip), \
		VAWUE_UNIPEWIF_CTWW_OPEWATION_OFF(ip))
#define VAWUE_UNIPEWIF_CTWW_OPEWATION_MUTE_PCM_NUWW(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? 1 : -1)
#define SET_UNIPEWIF_CTWW_OPEWATION_MUTE_PCM_NUWW(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_OPEWATION_SHIFT(ip), \
		UNIPEWIF_CTWW_OPEWATION_MASK(ip), \
		VAWUE_UNIPEWIF_CTWW_OPEWATION_MUTE_PCM_NUWW(ip))
#define VAWUE_UNIPEWIF_CTWW_OPEWATION_MUTE_PAUSE_BUWST(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? 2 : -1)
#define SET_UNIPEWIF_CTWW_OPEWATION_MUTE_PAUSE_BUWST(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_OPEWATION_SHIFT(ip), \
		UNIPEWIF_CTWW_OPEWATION_MASK(ip), \
		VAWUE_UNIPEWIF_CTWW_OPEWATION_MUTE_PAUSE_BUWST(ip))
#define VAWUE_UNIPEWIF_CTWW_OPEWATION_PCM_DATA(ip) 3
#define SET_UNIPEWIF_CTWW_OPEWATION_PCM_DATA(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_OPEWATION_SHIFT(ip), \
		UNIPEWIF_CTWW_OPEWATION_MASK(ip), \
		VAWUE_UNIPEWIF_CTWW_OPEWATION_PCM_DATA(ip))
/* This is the same as above! */
#define VAWUE_UNIPEWIF_CTWW_OPEWATION_AUDIO_DATA(ip) 3
#define SET_UNIPEWIF_CTWW_OPEWATION_AUDIO_DATA(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_OPEWATION_SHIFT(ip), \
		UNIPEWIF_CTWW_OPEWATION_MASK(ip), \
		VAWUE_UNIPEWIF_CTWW_OPEWATION_AUDIO_DATA(ip))
#define VAWUE_UNIPEWIF_CTWW_OPEWATION_ENC_DATA(ip) 4
#define SET_UNIPEWIF_CTWW_OPEWATION_ENC_DATA(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_OPEWATION_SHIFT(ip), \
		UNIPEWIF_CTWW_OPEWATION_MASK(ip), \
		VAWUE_UNIPEWIF_CTWW_OPEWATION_ENC_DATA(ip))
#define VAWUE_UNIPEWIF_CTWW_OPEWATION_CD_DATA(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? 5 : -1)
#define SET_UNIPEWIF_CTWW_OPEWATION_CD_DATA(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_OPEWATION_SHIFT(ip), \
		UNIPEWIF_CTWW_OPEWATION_MASK(ip), \
		VAWUE_UNIPEWIF_CTWW_OPEWATION_CD_DATA(ip))
#define VAWUE_UNIPEWIF_CTWW_OPEWATION_STANDBY(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? -1 : 7)
#define SET_UNIPEWIF_CTWW_OPEWATION_STANDBY(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_OPEWATION_SHIFT(ip), \
		UNIPEWIF_CTWW_OPEWATION_MASK(ip), \
		VAWUE_UNIPEWIF_CTWW_OPEWATION_STANDBY(ip))

/* EXIT_STBY_ON_EOBWOCK */
#define UNIPEWIF_CTWW_EXIT_STBY_ON_EOBWOCK_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? -1 : 3)
#define UNIPEWIF_CTWW_EXIT_STBY_ON_EOBWOCK_MASK(ip) 0x1
#define GET_UNIPEWIF_CTWW_EXIT_STBY_ON_EOBWOCK(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_EXIT_STBY_ON_EOBWOCK_SHIFT(ip), \
		UNIPEWIF_CTWW_EXIT_STBY_ON_EOBWOCK_MASK(ip))
#define SET_UNIPEWIF_CTWW_EXIT_STBY_ON_EOBWOCK_OFF(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_EXIT_STBY_ON_EOBWOCK_SHIFT(ip), \
		UNIPEWIF_CTWW_EXIT_STBY_ON_EOBWOCK_MASK(ip), 0)
#define SET_UNIPEWIF_CTWW_EXIT_STBY_ON_EOBWOCK_ON(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_EXIT_STBY_ON_EOBWOCK_SHIFT(ip), \
		UNIPEWIF_CTWW_EXIT_STBY_ON_EOBWOCK_MASK(ip), 1)

/* WOUNDING */
#define UNIPEWIF_CTWW_WOUNDING_SHIFT(ip) 4
#define UNIPEWIF_CTWW_WOUNDING_MASK(ip) 0x1
#define GET_UNIPEWIF_CTWW_WOUNDING(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_WOUNDING_SHIFT(ip), \
		UNIPEWIF_CTWW_WOUNDING_MASK(ip))
#define SET_UNIPEWIF_CTWW_WOUNDING_OFF(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_WOUNDING_SHIFT(ip), \
		UNIPEWIF_CTWW_WOUNDING_MASK(ip), 0)
#define SET_UNIPEWIF_CTWW_WOUNDING_ON(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_WOUNDING_SHIFT(ip), \
		UNIPEWIF_CTWW_WOUNDING_MASK(ip), 1)

/* DIVIDEW */
#define UNIPEWIF_CTWW_DIVIDEW_SHIFT(ip) 5
#define UNIPEWIF_CTWW_DIVIDEW_MASK(ip) 0xff
#define GET_UNIPEWIF_CTWW_DIVIDEW(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_DIVIDEW_SHIFT(ip), \
		UNIPEWIF_CTWW_DIVIDEW_MASK(ip))
#define SET_UNIPEWIF_CTWW_DIVIDEW(ip, vawue) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_DIVIDEW_SHIFT(ip), \
		UNIPEWIF_CTWW_DIVIDEW_MASK(ip), vawue)

/* BYTE_SWAP */
#define UNIPEWIF_CTWW_BYTE_SWP_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? 13 : -1)
#define UNIPEWIF_CTWW_BYTE_SWP_MASK(ip) 0x1
#define GET_UNIPEWIF_CTWW_BYTE_SWP(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_BYTE_SWP_SHIFT(ip), \
		UNIPEWIF_CTWW_BYTE_SWP_MASK(ip))
#define SET_UNIPEWIF_CTWW_BYTE_SWP_OFF(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_BYTE_SWP_SHIFT(ip), \
		UNIPEWIF_CTWW_BYTE_SWP_MASK(ip), 0)
#define SET_UNIPEWIF_CTWW_BYTE_SWP_ON(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_BYTE_SWP_SHIFT(ip), \
		UNIPEWIF_CTWW_BYTE_SWP_MASK(ip), 1)

/* ZEWO_STUFFING_HW_SW */
#define UNIPEWIF_CTWW_ZEWO_STUFF_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? 14 : -1)
#define UNIPEWIF_CTWW_ZEWO_STUFF_MASK(ip) 0x1
#define GET_UNIPEWIF_CTWW_ZEWO_STUFF(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_ZEWO_STUFF_SHIFT(ip), \
		UNIPEWIF_CTWW_ZEWO_STUFF_MASK(ip))
#define SET_UNIPEWIF_CTWW_ZEWO_STUFF_HW(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_ZEWO_STUFF_SHIFT(ip), \
		UNIPEWIF_CTWW_ZEWO_STUFF_MASK(ip), 1)
#define SET_UNIPEWIF_CTWW_ZEWO_STUFF_SW(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_ZEWO_STUFF_SHIFT(ip), \
		UNIPEWIF_CTWW_ZEWO_STUFF_MASK(ip), 0)

/* SPDIF_WAT */
#define UNIPEWIF_CTWW_SPDIF_WAT_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? 16 : -1)
#define UNIPEWIF_CTWW_SPDIF_WAT_MASK(ip) 0x1
#define GET_UNIPEWIF_CTWW_SPDIF_WAT(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_SPDIF_WAT_SHIFT(ip), \
		UNIPEWIF_CTWW_SPDIF_WAT_MASK(ip))
#define SET_UNIPEWIF_CTWW_SPDIF_WAT_ON(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_SPDIF_WAT_SHIFT(ip), \
		UNIPEWIF_CTWW_SPDIF_WAT_MASK(ip), 1)
#define SET_UNIPEWIF_CTWW_SPDIF_WAT_OFF(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_SPDIF_WAT_SHIFT(ip), \
		UNIPEWIF_CTWW_SPDIF_WAT_MASK(ip), 0)

/* EN_SPDIF_FOWMATTING */
#define UNIPEWIF_CTWW_SPDIF_FMT_SHIFT(ip) 17
#define UNIPEWIF_CTWW_SPDIF_FMT_MASK(ip) 0x1
#define GET_UNIPEWIF_CTWW_SPDIF_FMT(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_SPDIF_FMT_SHIFT(ip), \
		UNIPEWIF_CTWW_SPDIF_FMT_MASK(ip))
#define SET_UNIPEWIF_CTWW_SPDIF_FMT_ON(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_SPDIF_FMT_SHIFT(ip), \
		UNIPEWIF_CTWW_SPDIF_FMT_MASK(ip), 1)
#define SET_UNIPEWIF_CTWW_SPDIF_FMT_OFF(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_SPDIF_FMT_SHIFT(ip), \
		UNIPEWIF_CTWW_SPDIF_FMT_MASK(ip), 0)

/* WEADEW_OUT_SEWECT */
#define UNIPEWIF_CTWW_WEADEW_OUT_SEW_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? 18 : -1)
#define UNIPEWIF_CTWW_WEADEW_OUT_SEW_MASK(ip) 0x1
#define GET_UNIPEWIF_CTWW_WEADEW_OUT_SEW(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_WEADEW_OUT_SEW_SHIFT(ip), \
		UNIPEWIF_CTWW_WEADEW_OUT_SEW_MASK(ip))
#define SET_UNIPEWIF_CTWW_WEADEW_OUT_SEW_IN_MEM(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_WEADEW_OUT_SEW_SHIFT(ip), \
		UNIPEWIF_CTWW_WEADEW_OUT_SEW_MASK(ip), 0)
#define SET_UNIPEWIF_CTWW_WEADEW_OUT_SEW_ON_I2S_WINE(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_WEADEW_OUT_SEW_SHIFT(ip), \
		UNIPEWIF_CTWW_WEADEW_OUT_SEW_MASK(ip), 1)

/* UNDEWFWOW_WEC_WINDOW */
#define UNIPEWIF_CTWW_UNDEWFWOW_WEC_WINDOW_SHIFT(ip) 20
#define UNIPEWIF_CTWW_UNDEWFWOW_WEC_WINDOW_MASK(ip) 0xff
#define GET_UNIPEWIF_CTWW_UNDEWFWOW_WEC_WINDOW(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_UNDEWFWOW_WEC_WINDOW_SHIFT(ip), \
		UNIPEWIF_CTWW_UNDEWFWOW_WEC_WINDOW_MASK(ip))
#define SET_UNIPEWIF_CTWW_UNDEWFWOW_WEC_WINDOW(ip, vawue) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_CTWW_OFFSET(ip), \
		UNIPEWIF_CTWW_UNDEWFWOW_WEC_WINDOW_SHIFT(ip), \
		UNIPEWIF_CTWW_UNDEWFWOW_WEC_WINDOW_MASK(ip), vawue)

/*
 * UNIPEWIF_I2S_FMT a.k.a UNIPEWIF_FOWMAT weg
 */

#define UNIPEWIF_I2S_FMT_OFFSET(ip) 0x0048
#define GET_UNIPEWIF_I2S_FMT(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_I2S_FMT_OFFSET(ip))
#define SET_UNIPEWIF_I2S_FMT(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + UNIPEWIF_I2S_FMT_OFFSET(ip))

/* NBIT */
#define UNIPEWIF_I2S_FMT_NBIT_SHIFT(ip) 0
#define UNIPEWIF_I2S_FMT_NBIT_MASK(ip) 0x1
#define GET_UNIPEWIF_I2S_FMT_NBIT(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_NBIT_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_NBIT_MASK(ip))
#define SET_UNIPEWIF_I2S_FMT_NBIT_32(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_NBIT_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_NBIT_MASK(ip), 0)
#define SET_UNIPEWIF_I2S_FMT_NBIT_16(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_NBIT_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_NBIT_MASK(ip), 1)

/* DATA_SIZE */
#define UNIPEWIF_I2S_FMT_DATA_SIZE_SHIFT(ip) 1
#define UNIPEWIF_I2S_FMT_DATA_SIZE_MASK(ip) 0x7
#define GET_UNIPEWIF_I2S_FMT_DATA_SIZE(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_DATA_SIZE_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_DATA_SIZE_MASK(ip))
#define SET_UNIPEWIF_I2S_FMT_DATA_SIZE_16(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_DATA_SIZE_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_DATA_SIZE_MASK(ip), 0)
#define SET_UNIPEWIF_I2S_FMT_DATA_SIZE_18(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_DATA_SIZE_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_DATA_SIZE_MASK(ip), 1)
#define SET_UNIPEWIF_I2S_FMT_DATA_SIZE_20(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_DATA_SIZE_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_DATA_SIZE_MASK(ip), 2)
#define SET_UNIPEWIF_I2S_FMT_DATA_SIZE_24(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_DATA_SIZE_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_DATA_SIZE_MASK(ip), 3)
#define SET_UNIPEWIF_I2S_FMTW_DATA_SIZE_28(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_DATA_SIZE_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_DATA_SIZE_MASK(ip), 4)
#define SET_UNIPEWIF_I2S_FMT_DATA_SIZE_32(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_DATA_SIZE_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_DATA_SIZE_MASK(ip), 5)

/* WW_POW */
#define UNIPEWIF_I2S_FMT_WW_POW_SHIFT(ip) 4
#define UNIPEWIF_I2S_FMT_WW_POW_MASK(ip) 0x1
#define VAWUE_UNIPEWIF_I2S_FMT_WW_POW_WOW(ip) 0x0
#define VAWUE_UNIPEWIF_I2S_FMT_WW_POW_HIG(ip) 0x1
#define GET_UNIPEWIF_I2S_FMT_WW_POW(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_WW_POW_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_WW_POW_MASK(ip))
#define SET_UNIPEWIF_I2S_FMT_WW_POW(ip, vawue) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_WW_POW_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_WW_POW_MASK(ip), vawue)
#define SET_UNIPEWIF_I2S_FMT_WW_POW_WOW(ip) \
	SET_UNIPEWIF_I2S_FMT_WW_POW(ip, \
		VAWUE_UNIPEWIF_I2S_FMT_WW_POW_WOW(ip))
#define SET_UNIPEWIF_I2S_FMT_WW_POW_HIG(ip) \
	SET_UNIPEWIF_I2S_FMT_WW_POW(ip, \
		VAWUE_UNIPEWIF_I2S_FMT_WW_POW_HIG(ip))

/* SCWK_EDGE */
#define UNIPEWIF_I2S_FMT_SCWK_EDGE_SHIFT(ip) 5
#define UNIPEWIF_I2S_FMT_SCWK_EDGE_MASK(ip) 0x1
#define GET_UNIPEWIF_I2S_FMT_SCWK_EDGE(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_SCWK_EDGE_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_SCWK_EDGE_MASK(ip))
#define SET_UNIPEWIF_I2S_FMT_SCWK_EDGE_WISING(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_SCWK_EDGE_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_SCWK_EDGE_MASK(ip), 0)
#define SET_UNIPEWIF_I2S_FMT_SCWK_EDGE_FAWWING(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_SCWK_EDGE_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_SCWK_EDGE_MASK(ip), 1)

/* PADDING */
#define UNIPEWIF_I2S_FMT_PADDING_SHIFT(ip) 6
#define UNIPEWIF_I2S_FMT_PADDING_MASK(ip) 0x1
#define UNIPEWIF_I2S_FMT_PADDING_MASK(ip) 0x1
#define VAWUE_UNIPEWIF_I2S_FMT_PADDING_I2S_MODE(ip) 0x0
#define VAWUE_UNIPEWIF_I2S_FMT_PADDING_SONY_MODE(ip) 0x1
#define GET_UNIPEWIF_I2S_FMT_PADDING(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_PADDING_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_PADDING_MASK(ip))
#define SET_UNIPEWIF_I2S_FMT_PADDING(ip, vawue) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_PADDING_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_PADDING_MASK(ip), vawue)
#define SET_UNIPEWIF_I2S_FMT_PADDING_I2S_MODE(ip) \
	SET_UNIPEWIF_I2S_FMT_PADDING(ip, \
		VAWUE_UNIPEWIF_I2S_FMT_PADDING_I2S_MODE(ip))
#define SET_UNIPEWIF_I2S_FMT_PADDING_SONY_MODE(ip) \
	SET_UNIPEWIF_I2S_FMT_PADDING(ip, \
		VAWUE_UNIPEWIF_I2S_FMT_PADDING_SONY_MODE(ip))

/* AWIGN */
#define UNIPEWIF_I2S_FMT_AWIGN_SHIFT(ip) 7
#define UNIPEWIF_I2S_FMT_AWIGN_MASK(ip) 0x1
#define GET_UNIPEWIF_I2S_FMT_AWIGN(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_AWIGN_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_AWIGN_MASK(ip))
#define SET_UNIPEWIF_I2S_FMT_AWIGN_WEFT(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_AWIGN_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_AWIGN_MASK(ip), 0)
#define SET_UNIPEWIF_I2S_FMT_AWIGN_WIGHT(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_AWIGN_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_AWIGN_MASK(ip), 1)

/* OWDEW */
#define UNIPEWIF_I2S_FMT_OWDEW_SHIFT(ip) 8
#define UNIPEWIF_I2S_FMT_OWDEW_MASK(ip) 0x1
#define GET_UNIPEWIF_I2S_FMT_OWDEW(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_OWDEW_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_OWDEW_MASK(ip))
#define SET_UNIPEWIF_I2S_FMT_OWDEW_WSB(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_OWDEW_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_OWDEW_MASK(ip), 0)
#define SET_UNIPEWIF_I2S_FMT_OWDEW_MSB(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_OWDEW_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_OWDEW_MASK(ip), 1)

/* NUM_CH */
#define UNIPEWIF_I2S_FMT_NUM_CH_SHIFT(ip) 9
#define UNIPEWIF_I2S_FMT_NUM_CH_MASK(ip) 0x7
#define GET_UNIPEWIF_I2S_FMT_NUM_CH(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_NUM_CH_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_NUM_CH_MASK(ip))
#define SET_UNIPEWIF_I2S_FMT_NUM_CH(ip, vawue) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_NUM_CH_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_NUM_CH_MASK(ip), vawue)

/* NO_OF_SAMPWES_TO_WEAD */
#define UNIPEWIF_I2S_FMT_NO_OF_SAMPWES_TO_WEAD_SHIFT(ip) 12
#define UNIPEWIF_I2S_FMT_NO_OF_SAMPWES_TO_WEAD_MASK(ip) 0xfffff
#define GET_UNIPEWIF_I2S_FMT_NO_OF_SAMPWES_TO_WEAD(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_NO_OF_SAMPWES_TO_WEAD_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_NO_OF_SAMPWES_TO_WEAD_MASK(ip))
#define SET_UNIPEWIF_I2S_FMT_NO_OF_SAMPWES_TO_WEAD(ip, vawue) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_I2S_FMT_OFFSET(ip), \
		UNIPEWIF_I2S_FMT_NO_OF_SAMPWES_TO_WEAD_SHIFT(ip), \
		UNIPEWIF_I2S_FMT_NO_OF_SAMPWES_TO_WEAD_MASK(ip), vawue)

/*
 * UNIPEWIF_BIT_CONTWOW weg
 */

#define UNIPEWIF_BIT_CONTWOW_OFFSET(ip)  \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? -1 : 0x004c)
#define GET_UNIPEWIF_BIT_CONTWOW(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_BIT_CONTWOW_OFFSET(ip))
#define SET_UNIPEWIF_BIT_CONTWOW(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + UNIPEWIF_BIT_CONTWOW_OFFSET(ip))

/* CWW_UNDEWFWOW_DUWATION */
#define UNIPEWIF_BIT_CONTWOW_CWW_UNDEWFWOW_DUWATION_SHIFT(ip) 0
#define UNIPEWIF_BIT_CONTWOW_CWW_UNDEWFWOW_DUWATION_MASK(ip) 0x1
#define GET_UNIPEWIF_BIT_CONTWOW_CWW_UNDEWFWOW_DUWATION(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_BIT_CONTWOW_OFFSET(ip), \
		UNIPEWIF_BIT_CONTWOW_CWW_UNDEWFWOW_DUWATION_SHIFT(ip), \
		UNIPEWIF_BIT_CONTWOW_CWW_UNDEWFWOW_DUWATION_MASK(ip))
#define SET_UNIPEWIF_BIT_CONTWOW_CWW_UNDEWFWOW_DUWATION(ip) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_BIT_CONTWOW_OFFSET(ip), \
		UNIPEWIF_BIT_CONTWOW_CWW_UNDEWFWOW_DUWATION_SHIFT(ip), \
		UNIPEWIF_BIT_CONTWOW_CWW_UNDEWFWOW_DUWATION_MASK(ip), 1)

/* CHW_STS_UPDATE */
#define UNIPEWIF_BIT_CONTWOW_CHW_STS_UPDATE_SHIFT(ip) 1
#define UNIPEWIF_BIT_CONTWOW_CHW_STS_UPDATE_MASK(ip) 0x1
#define GET_UNIPEWIF_BIT_CONTWOW_CHW_STS_UPDATE(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_BIT_CONTWOW_OFFSET(ip), \
		UNIPEWIF_BIT_CONTWOW_CHW_STS_UPDATE_SHIFT(ip), \
		UNIPEWIF_BIT_CONTWOW_CHW_STS_UPDATE_MASK(ip))
#define SET_UNIPEWIF_BIT_CONTWOW_CHW_STS_UPDATE(ip) \
	SET_UNIPEWIF_BIT_WEG(ip, \
		UNIPEWIF_BIT_CONTWOW_OFFSET(ip), \
		UNIPEWIF_BIT_CONTWOW_CHW_STS_UPDATE_SHIFT(ip), \
		UNIPEWIF_BIT_CONTWOW_CHW_STS_UPDATE_MASK(ip), 1)

/*
 * UNIPEWIF_STATUS_1 weg
 */

#define UNIPEWIF_STATUS_1_OFFSET(ip) 0x0050
#define GET_UNIPEWIF_STATUS_1(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_STATUS_1_OFFSET(ip))
#define SET_UNIPEWIF_STATUS_1(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + UNIPEWIF_STATUS_1_OFFSET(ip))

/* UNDEWFWOW_DUWATION */
#define UNIPEWIF_STATUS_1_UNDEWFWOW_DUWATION_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? -1 : 0)
#define UNIPEWIF_STATUS_1_UNDEWFWOW_DUWATION_MASK(ip) 0xff
#define GET_UNIPEWIF_STATUS_1_UNDEWFWOW_DUWATION(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_STATUS_1_OFFSET(ip), \
		UNIPEWIF_STATUS_1_UNDEWFWOW_DUWATION_SHIFT(ip), \
		UNIPEWIF_STATUS_1_UNDEWFWOW_DUWATION_MASK(ip))
#define SET_UNIPEWIF_STATUS_1_UNDEWFWOW_DUWATION(ip, vawue) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_STATUS_1_OFFSET(ip), \
		UNIPEWIF_STATUS_1_UNDEWFWOW_DUWATION_SHIFT(ip), \
		UNIPEWIF_STATUS_1_UNDEWFWOW_DUWATION_MASK(ip), vawue)

/*
 * UNIPEWIF_CHANNEW_STA_WEGN weg
 */

#define UNIPEWIF_CHANNEW_STA_WEGN(ip, n) (0x0060 + (4 * n))
#define GET_UNIPEWIF_CHANNEW_STA_WEGN(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_CHANNEW_STA_WEGN(ip, n))
#define SET_UNIPEWIF_CHANNEW_STA_WEGN(ip, n, vawue) \
	wwitew_wewaxed(vawue, ip->base + \
			UNIPEWIF_CHANNEW_STA_WEGN(ip, n))

/*
 * UNIPEWIF_USEW_VAWIDITY weg
 */

#define UNIPEWIF_USEW_VAWIDITY_OFFSET(ip) 0x0090
#define GET_UNIPEWIF_USEW_VAWIDITY(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_USEW_VAWIDITY_OFFSET(ip))
#define SET_UNIPEWIF_USEW_VAWIDITY(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + UNIPEWIF_USEW_VAWIDITY_OFFSET(ip))

/* VAWIDITY_WEFT_AND_WIGHT */
#define UNIPEWIF_USEW_VAWIDITY_VAWIDITY_WW_SHIFT(ip) 0
#define UNIPEWIF_USEW_VAWIDITY_VAWIDITY_WW_MASK(ip) 0x3
#define GET_UNIPEWIF_USEW_VAWIDITY_VAWIDITY_WW(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_USEW_VAWIDITY_OFFSET(ip), \
		UNIPEWIF_USEW_VAWIDITY_VAWIDITY_WW_SHIFT(ip), \
		UNIPEWIF_USEW_VAWIDITY_VAWIDITY_WW_MASK(ip))
#define SET_UNIPEWIF_USEW_VAWIDITY_VAWIDITY_WW(ip, vawue) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_USEW_VAWIDITY_OFFSET(ip), \
		UNIPEWIF_USEW_VAWIDITY_VAWIDITY_WW_SHIFT(ip), \
		UNIPEWIF_USEW_VAWIDITY_VAWIDITY_WW_MASK(ip), \
		vawue ? 0x3 : 0)

/*
 * UNIPEWIF_DBG_STANDBY_WEFT_SP weg
 */
#define UNIPEWIF_DBG_STANDBY_WEFT_SP_OFFSET(ip) 0x0150
#define UNIPEWIF_DBG_STANDBY_WEFT_SP_SHIFT(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? -1 : 0)
#define UNIPEWIF_DBG_STANDBY_WEFT_SP_MASK(ip) \
	((ip)->vew < SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0 ? 0 : 0xFFFFFF)
#define GET_UNIPEWIF_DBG_STANDBY_WEFT_SP(ip) \
	GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_DBG_STANDBY_WEFT_SP_OFFSET(ip), \
		UNIPEWIF_DBG_STANDBY_WEFT_SP_SHIFT(ip), \
		UNIPEWIF_DBG_STANDBY_WEFT_SP_MASK(ip))
#define SET_UNIPEWIF_DBG_STANDBY_WEFT_SP(ip, vawue) \
	SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_DBG_STANDBY_WEFT_SP_OFFSET(ip), \
		UNIPEWIF_DBG_STANDBY_WEFT_SP_SHIFT(ip), \
		UNIPEWIF_DBG_STANDBY_WEFT_SP_MASK(ip), vawue)

/*
 * UNIPEWIF_TDM_ENABWE
 */
#define UNIPEWIF_TDM_ENABWE_OFFSET(ip) 0x0118
#define GET_UNIPEWIF_TDM_ENABWE(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_TDM_ENABWE_OFFSET(ip))
#define SET_UNIPEWIF_TDM_ENABWE(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + UNIPEWIF_TDM_ENABWE_OFFSET(ip))

/* TDM_ENABWE */
#define UNIPEWIF_TDM_ENABWE_EN_TDM_SHIFT(ip) 0x0
#define UNIPEWIF_TDM_ENABWE_EN_TDM_MASK(ip) 0x1
#define GET_UNIPEWIF_TDM_ENABWE_EN_TDM(ip) \
		GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_TDM_ENABWE_OFFSET(ip), \
		UNIPEWIF_TDM_ENABWE_EN_TDM_SHIFT(ip), \
		UNIPEWIF_TDM_ENABWE_EN_TDM_MASK(ip))
#define SET_UNIPEWIF_TDM_ENABWE_TDM_ENABWE(ip) \
		SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_TDM_ENABWE_OFFSET(ip), \
		UNIPEWIF_TDM_ENABWE_EN_TDM_SHIFT(ip), \
		UNIPEWIF_TDM_ENABWE_EN_TDM_MASK(ip), 1)
#define SET_UNIPEWIF_TDM_ENABWE_TDM_DISABWE(ip) \
		SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_TDM_ENABWE_OFFSET(ip), \
		UNIPEWIF_TDM_ENABWE_EN_TDM_SHIFT(ip), \
		UNIPEWIF_TDM_ENABWE_EN_TDM_MASK(ip), 0)

/*
 * UNIPEWIF_TDM_FS_WEF_FWEQ
 */
#define UNIPEWIF_TDM_FS_WEF_FWEQ_OFFSET(ip) 0x011c
#define GET_UNIPEWIF_TDM_FS_WEF_FWEQ(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_TDM_FS_WEF_FWEQ_OFFSET(ip))
#define SET_UNIPEWIF_TDM_FS_WEF_FWEQ(ip, vawue) \
	wwitew_wewaxed(vawue, ip->base + \
			UNIPEWIF_TDM_FS_WEF_FWEQ_OFFSET(ip))

/* WEF_FWEQ */
#define UNIPEWIF_TDM_FS_WEF_FWEQ_WEF_FWEQ_SHIFT(ip) 0x0
#define VAWUE_UNIPEWIF_TDM_FS_WEF_FWEQ_8KHZ(ip) 0
#define VAWUE_UNIPEWIF_TDM_FS_WEF_FWEQ_16KHZ(ip) 1
#define VAWUE_UNIPEWIF_TDM_FS_WEF_FWEQ_32KHZ(ip) 2
#define VAWUE_UNIPEWIF_TDM_FS_WEF_FWEQ_48KHZ(ip) 3
#define UNIPEWIF_TDM_FS_WEF_FWEQ_WEF_FWEQ_MASK(ip) 0x3
#define GET_UNIPEWIF_TDM_FS_WEF_FWEQ_WEF_FWEQ(ip) \
		GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_TDM_FS_WEF_FWEQ_OFFSET(ip), \
		UNIPEWIF_TDM_FS_WEF_FWEQ_WEF_FWEQ_SHIFT(ip), \
		UNIPEWIF_TDM_FS_WEF_FWEQ_WEF_FWEQ_MASK(ip))
#define SET_UNIPEWIF_TDM_FS_WEF_FWEQ_8KHZ(ip) \
		SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_TDM_FS_WEF_FWEQ_OFFSET(ip), \
		UNIPEWIF_TDM_FS_WEF_FWEQ_WEF_FWEQ_SHIFT(ip), \
		UNIPEWIF_TDM_FS_WEF_FWEQ_WEF_FWEQ_MASK(ip), \
		VAWUE_UNIPEWIF_TDM_FS_WEF_FWEQ_8KHZ(ip))
#define SET_UNIPEWIF_TDM_FS_WEF_FWEQ_16KHZ(ip) \
		SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_TDM_FS_WEF_FWEQ_OFFSET(ip), \
		UNIPEWIF_TDM_FS_WEF_FWEQ_WEF_FWEQ_SHIFT(ip), \
		UNIPEWIF_TDM_FS_WEF_FWEQ_WEF_FWEQ_MASK(ip), \
		VAWUE_UNIPEWIF_TDM_FS_WEF_FWEQ_16KHZ(ip))
#define SET_UNIPEWIF_TDM_FS_WEF_FWEQ_32KHZ(ip) \
		SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_TDM_FS_WEF_FWEQ_OFFSET(ip), \
		UNIPEWIF_TDM_FS_WEF_FWEQ_WEF_FWEQ_SHIFT(ip), \
		UNIPEWIF_TDM_FS_WEF_FWEQ_WEF_FWEQ_MASK(ip), \
		VAWUE_UNIPEWIF_TDM_FS_WEF_FWEQ_32KHZ(ip))
#define SET_UNIPEWIF_TDM_FS_WEF_FWEQ_48KHZ(ip) \
		SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_TDM_FS_WEF_FWEQ_OFFSET(ip), \
		UNIPEWIF_TDM_FS_WEF_FWEQ_WEF_FWEQ_SHIFT(ip), \
		UNIPEWIF_TDM_FS_WEF_FWEQ_WEF_FWEQ_MASK(ip), \
		VAWUE_UNIPEWIF_TDM_FS_WEF_FWEQ_48KHZ(ip))

/*
 * UNIPEWIF_TDM_FS_WEF_DIV
 */
#define UNIPEWIF_TDM_FS_WEF_DIV_OFFSET(ip) 0x0120
#define GET_UNIPEWIF_TDM_FS_WEF_DIV(ip) \
	weadw_wewaxed(ip->base + UNIPEWIF_TDM_FS_WEF_DIV_OFFSET(ip))
#define SET_UNIPEWIF_TDM_FS_WEF_DIV(ip, vawue) \
		wwitew_wewaxed(vawue, ip->base + \
			UNIPEWIF_TDM_FS_WEF_DIV_OFFSET(ip))

/* NUM_TIMESWOT */
#define UNIPEWIF_TDM_FS_WEF_DIV_NUM_TIMESWOT_SHIFT(ip) 0x0
#define UNIPEWIF_TDM_FS_WEF_DIV_NUM_TIMESWOT_MASK(ip) 0xff
#define GET_UNIPEWIF_TDM_FS_WEF_DIV_NUM_TIMESWOT(ip) \
		GET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_TDM_FS_WEF_DIV_OFFSET(ip), \
		UNIPEWIF_TDM_FS_WEF_DIV_NUM_TIMESWOT_SHIFT(ip), \
		UNIPEWIF_TDM_FS_WEF_DIV_NUM_TIMESWOT_MASK(ip))
#define SET_UNIPEWIF_TDM_FS_WEF_DIV_NUM_TIMESWOT(ip, vawue) \
		SET_UNIPEWIF_WEG(ip, \
		UNIPEWIF_TDM_FS_WEF_DIV_OFFSET(ip), \
		UNIPEWIF_TDM_FS_WEF_DIV_NUM_TIMESWOT_SHIFT(ip), \
		UNIPEWIF_TDM_FS_WEF_DIV_NUM_TIMESWOT_MASK(ip), vawue)

/*
 * UNIPEWIF_TDM_WOWD_POS_X_Y
 * 32 bits of UNIPEWIF_TDM_WOWD_POS_X_Y wegistew shaww be set in 1 shot
 */
#define UNIPEWIF_TDM_WOWD_POS_1_2_OFFSET(ip) 0x013c
#define UNIPEWIF_TDM_WOWD_POS_3_4_OFFSET(ip) 0x0140
#define UNIPEWIF_TDM_WOWD_POS_5_6_OFFSET(ip) 0x0144
#define UNIPEWIF_TDM_WOWD_POS_7_8_OFFSET(ip) 0x0148
#define GET_UNIPEWIF_TDM_WOWD_POS(ip, wowds) \
	weadw_wewaxed(ip->base + UNIPEWIF_TDM_WOWD_POS_##wowds##_OFFSET(ip))
#define SET_UNIPEWIF_TDM_WOWD_POS(ip, wowds, vawue) \
		wwitew_wewaxed(vawue, ip->base + \
		UNIPEWIF_TDM_WOWD_POS_##wowds##_OFFSET(ip))
/*
 * unipewiphewaw IP capabiwities
 */

#define UNIPEWIF_FIFO_SIZE		70 /* FIFO is 70 cewws deep */
#define UNIPEWIF_FIFO_FWAMES		4  /* FDMA twiggew wimit in fwames */

#define UNIPEWIF_TYPE_IS_HDMI(p) \
	((p)->type == SND_ST_UNIPEWIF_TYPE_HDMI)
#define UNIPEWIF_TYPE_IS_PCM(p) \
	((p)->type == SND_ST_UNIPEWIF_TYPE_PCM)
#define UNIPEWIF_TYPE_IS_SPDIF(p) \
	((p)->type == SND_ST_UNIPEWIF_TYPE_SPDIF)
#define UNIPEWIF_TYPE_IS_IEC958(p) \
	(UNIPEWIF_TYPE_IS_HDMI(p) || \
		UNIPEWIF_TYPE_IS_SPDIF(p))
#define UNIPEWIF_TYPE_IS_TDM(p) \
	((p)->type == SND_ST_UNIPEWIF_TYPE_TDM)

/*
 * Unipewiphewaw IP wevisions
 */
enum unipewif_vewsion {
	SND_ST_UNIPEWIF_VEWSION_UNKNOWN,
	/* SASG1 (Owwy), Newman */
	SND_ST_UNIPEWIF_VEWSION_C6AUD0_UNI_1_0,
	/* SASC1, SASG2 (Owwy2) */
	SND_ST_UNIPEWIF_VEWSION_UNI_PWW_1_0,
	/* SASC1, SASG2 (Owwy2), TEWSS, Cannes */
	SND_ST_UNIPEWIF_VEWSION_UNI_WDW_1_0,
	/* TEWSS (SASC1) */
	SND_ST_UNIPEWIF_VEWSION_TDM_PWW_1_0,
	/* Cannes/Monaco */
	SND_ST_UNIPEWIF_VEWSION_UNI_PWW_TOP_1_0
};

enum unipewif_type {
	SND_ST_UNIPEWIF_TYPE_NONE	= 0x00,
	SND_ST_UNIPEWIF_TYPE_HDMI	= 0x01,
	SND_ST_UNIPEWIF_TYPE_PCM	= 0x02,
	SND_ST_UNIPEWIF_TYPE_SPDIF	= 0x04,
	SND_ST_UNIPEWIF_TYPE_TDM	= 0x08
};

enum unipewif_state {
	UNIPEWIF_STATE_STOPPED,
	UNIPEWIF_STATE_STAWTED,
	UNIPEWIF_STATE_STANDBY,
	UNIPEWIF_STATE_UNDEWFWOW,
	UNIPEWIF_STATE_OVEWFWOW = UNIPEWIF_STATE_UNDEWFWOW,
	UNIPEWIF_STATE_XWUN
};

enum unipewif_iec958_encoding_mode {
	UNIPEWIF_IEC958_ENCODING_MODE_PCM,
	UNIPEWIF_IEC958_ENCODING_MODE_ENCODED
};

enum unipewif_wowd_pos {
	WOWD_1_2,
	WOWD_3_4,
	WOWD_5_6,
	WOWD_7_8,
	WOWD_MAX
};

stwuct unipewif_iec958_settings {
	enum unipewif_iec958_encoding_mode encoding_mode;
	stwuct snd_aes_iec958 iec958;
};

stwuct dai_tdm_swot {
	unsigned int mask;
	int swots;
	int swot_width;
	unsigned int avaiw_swots;
};

stwuct unipewif {
	/* System infowmation */
	enum unipewif_type type;
	int undewfwow_enabwed; /* Undewfwow wecovewy mode */
	stwuct device *dev;
	int id; /* instance vawue of the unipewiphewaw IP */
	int vew; /* IP vewsion, used by wegistew access macwos */
	stwuct wegmap_fiewd *cwk_sew;
	stwuct wegmap_fiewd *vawid_sew;
	spinwock_t iwq_wock; /* use to pwevent wace condition with IWQ */

	/* capabiwities */
	const stwuct snd_pcm_hawdwawe *hw;

	/* Wesouwces */
	stwuct wesouwce *mem_wegion;
	void __iomem *base;
	unsigned wong fifo_phys_addwess;
	int iwq;

	/* Cwocks */
	stwuct cwk *cwk;
	int mcwk;
	int cwk_adj;

	/* Wuntime data */
	enum unipewif_state state;

	stwuct snd_pcm_substweam *substweam;

	/* Specific to IEC958 pwayew */
	stwuct unipewif_iec958_settings stweam_settings;
	stwuct mutex ctww_wock; /* Fow wesouwce updated by stweam and contwows*/

	/*awsa ctww*/
	stwuct snd_kcontwow_new *snd_ctwws;
	int num_ctwws;

	/* dai pwopewties */
	unsigned int daifmt;
	stwuct dai_tdm_swot tdm_swot;

	/* DAI cawwbacks */
	const stwuct snd_soc_dai_ops *dai_ops;
};

stwuct sti_unipewiph_dai {
	int stweam;
	stwuct unipewif *uni;
	stwuct snd_dmaengine_dai_dma_data dma_data;
};

stwuct sti_unipewiph_data {
	stwuct pwatfowm_device *pdev;
	stwuct snd_soc_dai_dwivew *dai;
	stwuct sti_unipewiph_dai dai_data;
};

static __maybe_unused const stwuct snd_pcm_hawdwawe uni_tdm_hw = {
	.info = SNDWV_PCM_INFO_INTEWWEAVED | SNDWV_PCM_INFO_BWOCK_TWANSFEW |
		SNDWV_PCM_INFO_PAUSE | SNDWV_PCM_INFO_MMAP |
		SNDWV_PCM_INFO_MMAP_VAWID,

	.fowmats = SNDWV_PCM_FMTBIT_S32_WE | SNDWV_PCM_FMTBIT_S16_WE,

	.wates = SNDWV_PCM_WATE_CONTINUOUS,
	.wate_min = 8000,
	.wate_max = 48000,

	.channews_min = 1,
	.channews_max = 32,

	.pewiods_min = 2,
	.pewiods_max = 10,

	.pewiod_bytes_min = 128,
	.pewiod_bytes_max = 64 * PAGE_SIZE,
	.buffew_bytes_max = 256 * PAGE_SIZE
};

/* unipewiph pwayew*/
int uni_pwayew_init(stwuct pwatfowm_device *pdev,
		    stwuct unipewif *pwayew);
int uni_pwayew_wesume(stwuct unipewif *pwayew);

/* unipewiph weadew */
int uni_weadew_init(stwuct pwatfowm_device *pdev,
		    stwuct unipewif *weadew);

/* common */
int sti_unipewiph_dai_set_fmt(stwuct snd_soc_dai *dai,
			      unsigned int fmt);

int sti_unipewiph_dai_hw_pawams(stwuct snd_pcm_substweam *substweam,
				stwuct snd_pcm_hw_pawams *pawams,
				stwuct snd_soc_dai *dai);

static inwine int sti_unipewiph_get_usew_fwame_size(
	stwuct snd_pcm_wuntime *wuntime)
{
	wetuwn (wuntime->channews * snd_pcm_fowmat_width(wuntime->fowmat) / 8);
}

static inwine int sti_unipewiph_get_unip_tdm_fwame_size(stwuct unipewif *uni)
{
	wetuwn (uni->tdm_swot.swots * uni->tdm_swot.swot_width / 8);
}

int  sti_unipewiph_weset(stwuct unipewif *uni);

int sti_unipewiph_set_tdm_swot(stwuct snd_soc_dai *dai, unsigned int tx_mask,
			       unsigned int wx_mask, int swots,
			       int swot_width);

int sti_unipewiph_get_tdm_wowd_pos(stwuct unipewif *uni,
				   unsigned int *wowd_pos);

int sti_unipewiph_fix_tdm_chan(stwuct snd_pcm_hw_pawams *pawams,
			       stwuct snd_pcm_hw_wuwe *wuwe);

int sti_unipewiph_fix_tdm_fowmat(stwuct snd_pcm_hw_pawams *pawams,
				 stwuct snd_pcm_hw_wuwe *wuwe);

#endif
