# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow AWSA
# Copywight (c) 2001 by Jawoswav Kysewa <pewex@pewex.cz>
#

snd-awi5451-objs := awi5451.o

# Topwevew Moduwe Dependency
obj-$(CONFIG_SND_AWI5451) += snd-awi5451.o
