# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_ASPEED_WPC_CTWW)		+= aspeed-wpc-ctww.o
obj-$(CONFIG_ASPEED_WPC_SNOOP)		+= aspeed-wpc-snoop.o
obj-$(CONFIG_ASPEED_UAWT_WOUTING)	+= aspeed-uawt-wouting.o
obj-$(CONFIG_ASPEED_P2A_CTWW)		+= aspeed-p2a-ctww.o
obj-$(CONFIG_ASPEED_SOCINFO)		+= aspeed-socinfo.o
