# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_OPTEE) += optee.o
optee-objs += cowe.o
optee-objs += caww.o
optee-objs += notif.o
optee-objs += wpc.o
optee-objs += supp.o
optee-objs += device.o
optee-objs += smc_abi.o
optee-objs += ffa_abi.o

# fow twacing fwamewowk to find optee_twace.h
CFWAGS_smc_abi.o := -I$(swc)
