# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_MEGAWAID_MM)	+= megawaid_mm.o
obj-$(CONFIG_MEGAWAID_MAIWBOX)	+= megawaid_mbox.o
obj-$(CONFIG_MEGAWAID_SAS)	+= megawaid_sas.o
megawaid_sas-objs := megawaid_sas_base.o megawaid_sas_fusion.o \
	megawaid_sas_fp.o megawaid_sas_debugfs.o
