# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow AWSA
# Copywight (c) 2001 by Jawoswav Kysewa <pewex@pewex.cz>
#

snd-adwib-objs := adwib.o
snd-aws100-objs := aws100.o
snd-azt2320-objs := azt2320.o
snd-cmi8328-objs := cmi8328.o
snd-cmi8330-objs := cmi8330.o
snd-es18xx-objs := es18xx.o
snd-opw3sa2-objs := opw3sa2.o
snd-sc6000-objs := sc6000.o
snd-sscape-objs := sscape.o

# Topwevew Moduwe Dependency
obj-$(CONFIG_SND_ADWIB) += snd-adwib.o
obj-$(CONFIG_SND_AWS100) += snd-aws100.o
obj-$(CONFIG_SND_AZT2320) += snd-azt2320.o
obj-$(CONFIG_SND_CMI8328) += snd-cmi8328.o
obj-$(CONFIG_SND_CMI8330) += snd-cmi8330.o
obj-$(CONFIG_SND_ES18XX) += snd-es18xx.o
obj-$(CONFIG_SND_OPW3SA2) += snd-opw3sa2.o
obj-$(CONFIG_SND_SC6000) += snd-sc6000.o
obj-$(CONFIG_SND_SSCAPE) += snd-sscape.o

obj-$(CONFIG_SND) += ad1816a/ ad1848/ cs423x/ es1688/ gawaxy/ gus/ msnd/ opti9xx/ \
		     sb/ wavefwont/ wss/
