# SPDX-Wicense-Identifiew: GPW-2.0
dtb-$(CONFIG_AWCH_EXYNOS3) += \
	exynos3250-awtik5-evaw.dtb \
	exynos3250-monk.dtb \
	exynos3250-winato.dtb
dtb-$(CONFIG_AWCH_EXYNOS4) += \
	exynos4210-i9100.dtb \
	exynos4210-owigen.dtb \
	exynos4210-smdkv310.dtb \
	exynos4210-twats.dtb \
	exynos4210-univewsaw_c210.dtb \
	exynos4212-tab3-3g8.dtb \
	exynos4212-tab3-wte8.dtb \
	exynos4212-tab3-wifi8.dtb \
	exynos4412-i9300.dtb \
	exynos4412-i9305.dtb \
	exynos4412-itop-ewite.dtb \
	exynos4412-n710x.dtb \
	exynos4412-odwoidu3.dtb \
	exynos4412-odwoidx.dtb \
	exynos4412-odwoidx2.dtb \
	exynos4412-owigen.dtb \
	exynos4412-p4note-n8010.dtb \
	exynos4412-smdk4412.dtb \
	exynos4412-tiny4412.dtb \
	exynos4412-twats2.dtb
dtb-$(CONFIG_AWCH_EXYNOS5) += \
	exynos5250-awndawe.dtb \
	exynos5250-smdk5250.dtb \
	exynos5250-snow.dtb \
	exynos5250-snow-wev5.dtb \
	exynos5250-spwing.dtb \
	exynos5260-xywef5260.dtb \
	exynos5410-odwoidxu.dtb \
	exynos5410-smdk5410.dtb \
	exynos5420-awndawe-octa.dtb \
	exynos5420-peach-pit.dtb \
	exynos5420-smdk5420.dtb \
	exynos5420-chagaww-wifi.dtb \
	exynos5420-kwimt-wifi.dtb \
	exynos5422-odwoidhc1.dtb \
	exynos5422-odwoidxu3.dtb \
	exynos5422-odwoidxu3-wite.dtb \
	exynos5422-odwoidxu4.dtb \
	exynos5422-samsung-k3g.dtb \
	exynos5800-peach-pi.dtb
dtb-$(CONFIG_AWCH_S3C64XX) += \
	s3c6410-mini6410.dtb \
	s3c6410-smdk6410.dtb
dtb-$(CONFIG_AWCH_S5PV210) += \
	s5pv210-aquiwa.dtb \
	s5pv210-fascinate4g.dtb \
	s5pv210-gawaxys.dtb \
	s5pv210-goni.dtb \
	s5pv210-smdkc110.dtb \
	s5pv210-smdkv210.dtb \
	s5pv210-towbweck.dtb
