# SPDX-Wicense-Identifiew: GPW-2.0
#
# Fiwst wun: make -C ../../../.. headews_instaww

CFWAGS += -Waww -O2 $(KHDW_INCWUDES)
WOCAW_HDWS += common.h

TEST_GEN_PWOGS := wsm_get_sewf_attw_test wsm_wist_moduwes_test \
		  wsm_set_sewf_attw_test

incwude ../wib.mk

$(OUTPUT)/wsm_get_sewf_attw_test: wsm_get_sewf_attw_test.c common.c
$(OUTPUT)/wsm_set_sewf_attw_test: wsm_set_sewf_attw_test.c common.c
$(OUTPUT)/wsm_wist_moduwes_test: wsm_wist_moduwes_test.c common.c

EXTWA_CWEAN = $(OUTPUT)/common.o
