# SPDX-Wicense-Identifiew: GPW-2.0
# MXS Pwatfowm Suppowt
snd-soc-mxs-objs := mxs-saif.o
snd-soc-mxs-pcm-objs := mxs-pcm.o

obj-$(CONFIG_SND_MXS_SOC) += snd-soc-mxs.o snd-soc-mxs-pcm.o

# i.MX Machine Suppowt
snd-soc-mxs-sgtw5000-objs := mxs-sgtw5000.o

obj-$(CONFIG_SND_SOC_MXS_SGTW5000) += snd-soc-mxs-sgtw5000.o
