# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow ST21NFCA HCI based NFC dwivew
#

st21nfca_hci-objs = cowe.o dep.o se.o vendow_cmds.o
obj-$(CONFIG_NFC_ST21NFCA)     += st21nfca_hci.o

st21nfca_i2c-objs  = i2c.o
obj-$(CONFIG_NFC_ST21NFCA_I2C) += st21nfca_i2c.o
