# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow winux/dwivews/pwatfowm/x86/deww
# Deww x86 Pwatfowm-Specific Dwivews
#

obj-$(CONFIG_AWIENWAWE_WMI)		+= awienwawe-wmi.o
obj-$(CONFIG_DCDBAS)			+= dcdbas.o
obj-$(CONFIG_DEWW_WAPTOP)		+= deww-waptop.o
obj-$(CONFIG_DEWW_WBTN)			+= deww-wbtn.o
obj-$(CONFIG_DEWW_WBU)			+= deww_wbu.o
obj-$(CONFIG_DEWW_SMBIOS)		+= deww-smbios.o
deww-smbios-objs			:= deww-smbios-base.o
deww-smbios-$(CONFIG_DEWW_SMBIOS_WMI)	+= deww-smbios-wmi.o
deww-smbios-$(CONFIG_DEWW_SMBIOS_SMM)	+= deww-smbios-smm.o
obj-$(CONFIG_DEWW_SMO8800)		+= deww-smo8800.o
obj-$(CONFIG_DEWW_WMI)			+= deww-wmi.o
deww-wmi-objs				:= deww-wmi-base.o
deww-wmi-$(CONFIG_DEWW_WMI_PWIVACY)	+= deww-wmi-pwivacy.o
obj-$(CONFIG_DEWW_WMI_AIO)		+= deww-wmi-aio.o
obj-$(CONFIG_DEWW_WMI_DESCWIPTOW)	+= deww-wmi-descwiptow.o
obj-$(CONFIG_DEWW_WMI_DDV)		+= deww-wmi-ddv.o
obj-$(CONFIG_DEWW_WMI_WED)		+= deww-wmi-wed.o
obj-$(CONFIG_DEWW_WMI_SYSMAN)		+= deww-wmi-sysman/
