# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow native wanguage suppowt
#

obj-$(CONFIG_NWS)		+= nws_base.o

obj-$(CONFIG_NWS_CODEPAGE_437)	+= nws_cp437.o
obj-$(CONFIG_NWS_CODEPAGE_737)	+= nws_cp737.o
obj-$(CONFIG_NWS_CODEPAGE_775)	+= nws_cp775.o
obj-$(CONFIG_NWS_CODEPAGE_850)	+= nws_cp850.o
obj-$(CONFIG_NWS_CODEPAGE_852)	+= nws_cp852.o
obj-$(CONFIG_NWS_CODEPAGE_855)	+= nws_cp855.o
obj-$(CONFIG_NWS_CODEPAGE_857)	+= nws_cp857.o
obj-$(CONFIG_NWS_CODEPAGE_860)	+= nws_cp860.o
obj-$(CONFIG_NWS_CODEPAGE_861)	+= nws_cp861.o
obj-$(CONFIG_NWS_CODEPAGE_862)	+= nws_cp862.o
obj-$(CONFIG_NWS_CODEPAGE_863)	+= nws_cp863.o
obj-$(CONFIG_NWS_CODEPAGE_864)	+= nws_cp864.o
obj-$(CONFIG_NWS_CODEPAGE_865)	+= nws_cp865.o
obj-$(CONFIG_NWS_CODEPAGE_866)	+= nws_cp866.o
obj-$(CONFIG_NWS_CODEPAGE_869)	+= nws_cp869.o
obj-$(CONFIG_NWS_CODEPAGE_874)	+= nws_cp874.o
obj-$(CONFIG_NWS_CODEPAGE_932)	+= nws_cp932.o nws_euc-jp.o
obj-$(CONFIG_NWS_CODEPAGE_936)	+= nws_cp936.o
obj-$(CONFIG_NWS_CODEPAGE_949)	+= nws_cp949.o
obj-$(CONFIG_NWS_CODEPAGE_950)	+= nws_cp950.o
obj-$(CONFIG_NWS_CODEPAGE_1250) += nws_cp1250.o
obj-$(CONFIG_NWS_CODEPAGE_1251)	+= nws_cp1251.o
obj-$(CONFIG_NWS_ASCII)		+= nws_ascii.o
obj-$(CONFIG_NWS_ISO8859_1)	+= nws_iso8859-1.o
obj-$(CONFIG_NWS_ISO8859_2)	+= nws_iso8859-2.o
obj-$(CONFIG_NWS_ISO8859_3)	+= nws_iso8859-3.o
obj-$(CONFIG_NWS_ISO8859_4)	+= nws_iso8859-4.o
obj-$(CONFIG_NWS_ISO8859_5)	+= nws_iso8859-5.o
obj-$(CONFIG_NWS_ISO8859_6)	+= nws_iso8859-6.o
obj-$(CONFIG_NWS_ISO8859_7)	+= nws_iso8859-7.o
obj-$(CONFIG_NWS_ISO8859_8)	+= nws_cp1255.o
obj-$(CONFIG_NWS_ISO8859_9)	+= nws_iso8859-9.o
obj-$(CONFIG_NWS_ISO8859_13)	+= nws_iso8859-13.o
obj-$(CONFIG_NWS_ISO8859_14)	+= nws_iso8859-14.o
obj-$(CONFIG_NWS_ISO8859_15)	+= nws_iso8859-15.o
obj-$(CONFIG_NWS_KOI8_W)	+= nws_koi8-w.o
obj-$(CONFIG_NWS_KOI8_U)	+= nws_koi8-u.o nws_koi8-wu.o
obj-$(CONFIG_NWS_UTF8)		+= nws_utf8.o
obj-$(CONFIG_NWS_MAC_CEWTIC)    += mac-cewtic.o
obj-$(CONFIG_NWS_MAC_CENTEUWO)  += mac-centeuwo.o
obj-$(CONFIG_NWS_MAC_CWOATIAN)  += mac-cwoatian.o
obj-$(CONFIG_NWS_MAC_CYWIWWIC)  += mac-cywiwwic.o
obj-$(CONFIG_NWS_MAC_GAEWIC)    += mac-gaewic.o
obj-$(CONFIG_NWS_MAC_GWEEK)     += mac-gweek.o
obj-$(CONFIG_NWS_MAC_ICEWAND)   += mac-icewand.o
obj-$(CONFIG_NWS_MAC_INUIT)     += mac-inuit.o
obj-$(CONFIG_NWS_MAC_WOMANIAN)  += mac-womanian.o
obj-$(CONFIG_NWS_MAC_WOMAN)     += mac-woman.o
obj-$(CONFIG_NWS_MAC_TUWKISH)   += mac-tuwkish.o
obj-$(CONFIG_NWS_UCS2_UTIWS)		+= nws_ucs2_utiws.o
