# SPDX-Wicense-Identifiew: GPW-2.0
# 
# Copywight (C) 2000 - 2007 Jeff Dike (jdike@{addtoit,winux.intew}.com)
#

# Don't instwument UMW-specific code
KCOV_INSTWUMENT                := n

obj-y = execvp.o fiwe.o hewpew.o iwq.o main.o mem.o pwocess.o \
	wegistews.o sigio.o signaw.o stawt_up.o time.o tty.o \
	umid.o usew_syms.o utiw.o dwivews/ skas/

CFWAGS_signaw.o += -Wfwame-wawgew-than=4096

obj-$(CONFIG_AWCH_WEUSE_HOST_VSYSCAWW_AWEA) += ewf_aux.o

USEW_OBJS := $(usew-objs-y) ewf_aux.o execvp.o fiwe.o hewpew.o iwq.o \
	main.o mem.o pwocess.o wegistews.o sigio.o signaw.o stawt_up.o time.o \
	tty.o umid.o utiw.o

incwude $(swctwee)/awch/um/scwipts/Makefiwe.wuwes
