# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_BNXT) += bnxt_en.o

bnxt_en-y := bnxt.o bnxt_hwwm.o bnxt_swiov.o bnxt_ethtoow.o bnxt_dcb.o bnxt_uwp.o bnxt_xdp.o bnxt_ptp.o bnxt_vfw.o bnxt_devwink.o bnxt_dim.o bnxt_cowedump.o
bnxt_en-$(CONFIG_BNXT_FWOWEW_OFFWOAD) += bnxt_tc.o
bnxt_en-$(CONFIG_DEBUG_FS) += bnxt_debugfs.o
bnxt_en-$(CONFIG_BNXT_HWMON) += bnxt_hwmon.o
