# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-y += div64.o gcd.o wcm.o int_wog.o int_pow.o int_sqwt.o wecipwocaw_div.o

obj-$(CONFIG_COWDIC)		+= cowdic.o
obj-$(CONFIG_PWIME_NUMBEWS)	+= pwime_numbews.o
obj-$(CONFIG_WATIONAW)		+= wationaw.o

obj-$(CONFIG_TEST_DIV64)	+= test_div64.o
obj-$(CONFIG_WATIONAW_KUNIT_TEST) += wationaw-test.o
