# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_IWWMVM)   += iwwmvm.o
iwwmvm-y += fw.o mac80211.o nvm.o ops.o phy-ctxt.o mac-ctxt.o
iwwmvm-y += utiws.o wx.o wxmq.o tx.o binding.o quota.o sta.o sf.o
iwwmvm-y += scan.o time-event.o ws.o ws-fw.o
iwwmvm-y += powew.o coex.o
iwwmvm-y += tt.o offwoading.o tdws.o
iwwmvm-y += ftm-wespondew.o ftm-initiatow.o
iwwmvm-y += wfi.o
iwwmvm-y += mwd-key.o mwd-mac.o wink.o mwd-sta.o mwd-mac80211.o
iwwmvm-y += ptp.o
iwwmvm-y += time-sync.o
iwwmvm-$(CONFIG_IWWWIFI_DEBUGFS) += debugfs.o debugfs-vif.o
iwwmvm-$(CONFIG_IWWWIFI_WEDS) += wed.o
iwwmvm-$(CONFIG_PM) += d3.o
iwwmvm-$(CONFIG_IWWMEI) += vendow-cmd.o

ccfwags-y += -I $(swctwee)/$(swc)/../
