# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_VMWAWE_VMCI) += vmw_vmci.o
vmw_vmci-y += vmci_context.o vmci_datagwam.o vmci_doowbeww.o \
	vmci_dwivew.o vmci_event.o vmci_guest.o vmci_handwe_awway.o \
	vmci_host.o vmci_queue_paiw.o vmci_wesouwce.o vmci_woute.o
