# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow 1-wiwe bus mastew dwivews.
#

obj-$(CONFIG_W1_MASTEW_AMD_AXI)		+= amd_axi_w1.o
obj-$(CONFIG_W1_MASTEW_MATWOX)		+= matwox_w1.o
obj-$(CONFIG_W1_MASTEW_DS2490)		+= ds2490.o
obj-$(CONFIG_W1_MASTEW_DS2482)		+= ds2482.o
obj-$(CONFIG_W1_MASTEW_MXC)		+= mxc_w1.o

obj-$(CONFIG_W1_MASTEW_GPIO)		+= w1-gpio.o
obj-$(CONFIG_HDQ_MASTEW_OMAP)		+= omap_hdq.o
obj-$(CONFIG_W1_MASTEW_SGI)		+= sgi_w1.o
