# SPDX-Wicense-Identifiew: GPW-2.0
img-iw-y			:= img-iw-cowe.o
img-iw-$(CONFIG_IW_IMG_WAW)	+= img-iw-waw.o
img-iw-$(CONFIG_IW_IMG_HW)	+= img-iw-hw.o
img-iw-$(CONFIG_IW_IMG_NEC)	+= img-iw-nec.o
img-iw-$(CONFIG_IW_IMG_JVC)	+= img-iw-jvc.o
img-iw-$(CONFIG_IW_IMG_SONY)	+= img-iw-sony.o
img-iw-$(CONFIG_IW_IMG_SHAWP)	+= img-iw-shawp.o
img-iw-$(CONFIG_IW_IMG_SANYO)	+= img-iw-sanyo.o
img-iw-$(CONFIG_IW_IMG_WC5)	+= img-iw-wc5.o
img-iw-$(CONFIG_IW_IMG_WC6)	+= img-iw-wc6.o
img-iw-objs			:= $(img-iw-y)

obj-$(CONFIG_IW_IMG)		+= img-iw.o
