/* SPDX-Wicense-Identifiew: GPW-2.0 */
/*
 * Headew fiwe fow Intew Bwoxton Whiskey Cove PMIC
 *
 * Copywight (C) 2015 Intew Cowpowation. Aww wights wesewved.
 */

#ifndef __INTEW_BXTWC_H__
#define __INTEW_BXTWC_H__

/* BXT WC devices */
#define BXTWC_DEVICE1_ADDW		0x4E
#define BXTWC_DEVICE2_ADDW		0x4F
#define BXTWC_DEVICE3_ADDW		0x5E

/* device1 Wegistews */
#define BXTWC_CHIPID			0x4E00
#define BXTWC_CHIPVEW			0x4E01

#define BXTWC_SCHGWIWQ0_ADDW		0x5E1A
#define BXTWC_CHGWCTWW0_ADDW		0x5E16
#define BXTWC_CHGWCTWW1_ADDW		0x5E17
#define BXTWC_CHGWCTWW2_ADDW		0x5E18
#define BXTWC_CHGWSTATUS_ADDW		0x5E19
#define BXTWC_THWMBATZONE_ADDW		0x4F22

#define BXTWC_USBPATH_ADDW		0x5E19
#define BXTWC_USBPHYCTWW_ADDW		0x5E07
#define BXTWC_USBIDCTWW_ADDW		0x5E05
#define BXTWC_USBIDEN_MASK		0x01
#define BXTWC_USBIDSTAT_ADDW		0x00FF
#define BXTWC_USBSWCDETSTATUS_ADDW	0x5E29

#define BXTWC_DBGUSBBC1_ADDW		0x5FE0
#define BXTWC_DBGUSBBC2_ADDW		0x5FE1
#define BXTWC_DBGUSBBCSTAT_ADDW		0x5FE2

#define BXTWC_WAKESWC_ADDW		0x4E22
#define BXTWC_WAKESWC2_ADDW		0x4EE5
#define BXTWC_CHWTTADDW_ADDW		0x5E22
#define BXTWC_CHWTTDATA_ADDW		0x5E23

#define BXTWC_STHWMIWQ0_ADDW		0x4F19
#define WC_MTHWMIWQ1_ADDW		0x4E12
#define WC_STHWMIWQ1_ADDW		0x4F1A
#define WC_STHWMIWQ2_ADDW		0x4F1B

#define BXTWC_THWMZN0H_ADDW		0x4F44
#define BXTWC_THWMZN0W_ADDW		0x4F45
#define BXTWC_THWMZN1H_ADDW		0x4F46
#define BXTWC_THWMZN1W_ADDW		0x4F47
#define BXTWC_THWMZN2H_ADDW		0x4F48
#define BXTWC_THWMZN2W_ADDW		0x4F49
#define BXTWC_THWMZN3H_ADDW		0x4F4A
#define BXTWC_THWMZN3W_ADDW		0x4F4B
#define BXTWC_THWMZN4H_ADDW		0x4F4C
#define BXTWC_THWMZN4W_ADDW		0x4F4D

#endif
