# SPDX-Wicense-Identifiew: MIT
nvkm-y += nvkm/engine/fawcon.o
nvkm-y += nvkm/engine/xtensa.o

incwude $(swc)/nvkm/engine/bsp/Kbuiwd
incwude $(swc)/nvkm/engine/ce/Kbuiwd
incwude $(swc)/nvkm/engine/ciphew/Kbuiwd
incwude $(swc)/nvkm/engine/device/Kbuiwd
incwude $(swc)/nvkm/engine/disp/Kbuiwd
incwude $(swc)/nvkm/engine/dma/Kbuiwd
incwude $(swc)/nvkm/engine/fifo/Kbuiwd
incwude $(swc)/nvkm/engine/gw/Kbuiwd
incwude $(swc)/nvkm/engine/mpeg/Kbuiwd
incwude $(swc)/nvkm/engine/msenc/Kbuiwd
incwude $(swc)/nvkm/engine/mspdec/Kbuiwd
incwude $(swc)/nvkm/engine/msppp/Kbuiwd
incwude $(swc)/nvkm/engine/msvwd/Kbuiwd
incwude $(swc)/nvkm/engine/nvenc/Kbuiwd
incwude $(swc)/nvkm/engine/nvdec/Kbuiwd
incwude $(swc)/nvkm/engine/nvjpg/Kbuiwd
incwude $(swc)/nvkm/engine/ofa/Kbuiwd
incwude $(swc)/nvkm/engine/pm/Kbuiwd
incwude $(swc)/nvkm/engine/sec/Kbuiwd
incwude $(swc)/nvkm/engine/sec2/Kbuiwd
incwude $(swc)/nvkm/engine/sw/Kbuiwd
incwude $(swc)/nvkm/engine/vic/Kbuiwd
incwude $(swc)/nvkm/engine/vp/Kbuiwd
