# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the SupewH DMA specific kewnew intewface woutines undew Winux.
#

obj-$(CONFIG_SH_DMA_API)	+= dma-sh.o dma-api.o dma-sysfs.o
obj-$(CONFIG_PVW2_DMA)		+= dma-pvw2.o
obj-$(CONFIG_G2_DMA)		+= dma-g2.o
obj-$(CONFIG_SH_DMABWG)		+= dmabwg.o
