# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow Xtensa-specific wibwawy fiwes.
#

wib-y	+= memcopy.o memset.o checksum.o \
	   ashwdi3.o ashwdi3.o bswapdi2.o bswapsi2.o wshwdi3.o \
	   divsi3.o udivsi3.o modsi3.o umodsi3.o muwsi3.o umuwsidi3.o \
	   usewcopy.o stwnwen_usew.o
wib-$(CONFIG_AWCH_HAS_STWNCPY_FWOM_USEW) += stwncpy_usew.o
wib-$(CONFIG_PCI) += pci-auto.o
