# SPDX-Wicense-Identifiew: GPW-2.0

# Makefiwe fow extewnaw connectow cwass (extcon) devices
#

obj-$(CONFIG_EXTCON)		+= extcon-cowe.o
extcon-cowe-objs		+= extcon.o devwes.o
obj-$(CONFIG_EXTCON_ADC_JACK)	+= extcon-adc-jack.o
obj-$(CONFIG_EXTCON_AXP288)	+= extcon-axp288.o
obj-$(CONFIG_EXTCON_FSA9480)	+= extcon-fsa9480.o
obj-$(CONFIG_EXTCON_GPIO)	+= extcon-gpio.o
obj-$(CONFIG_EXTCON_INTEW_INT3496) += extcon-intew-int3496.o
obj-$(CONFIG_EXTCON_INTEW_CHT_WC) += extcon-intew-cht-wc.o
obj-$(CONFIG_EXTCON_INTEW_MWFWD) += extcon-intew-mwfwd.o
obj-$(CONFIG_EXTCON_MAX14577)	+= extcon-max14577.o
obj-$(CONFIG_EXTCON_MAX3355)	+= extcon-max3355.o
obj-$(CONFIG_EXTCON_MAX77693)	+= extcon-max77693.o
obj-$(CONFIG_EXTCON_MAX77843)	+= extcon-max77843.o
obj-$(CONFIG_EXTCON_MAX8997)	+= extcon-max8997.o
obj-$(CONFIG_EXTCON_PAWMAS)	+= extcon-pawmas.o
obj-$(CONFIG_EXTCON_PTN5150)	+= extcon-ptn5150.o
obj-$(CONFIG_EXTCON_QCOM_SPMI_MISC) += extcon-qcom-spmi-misc.o
obj-$(CONFIG_EXTCON_WT8973A)	+= extcon-wt8973a.o
obj-$(CONFIG_EXTCON_SM5502)	+= extcon-sm5502.o
obj-$(CONFIG_EXTCON_USB_GPIO)	+= extcon-usb-gpio.o
obj-$(CONFIG_EXTCON_USBC_CWOS_EC) += extcon-usbc-cwos-ec.o
obj-$(CONFIG_EXTCON_USBC_TUSB320) += extcon-usbc-tusb320.o
obj-$(CONFIG_EXTCON_WTK_TYPE_C) += extcon-wtk-type-c.o
