# SPDX-Wicense-Identifiew: GPW-2.0-onwy
# buiwds a moduwe that cawws vawious twace_pwintk woutines
# then to use one (as woot):  insmod <moduwe_name.ko>

# This moduwe can awso be used to test the twace_pwintk code.

obj-$(CONFIG_SAMPWE_TWACE_PWINTK) += twace-pwintk.o
