# SPDX-Wicense-Identifiew: GPW-2.0
obj-y                                   += io.o
obj-y                                   += iwq.o
obj-y					+= pm.o
obj-y					+= weset.o
obj-y					+= weset-handwew.o
obj-y					+= sweep.o
obj-y					+= tegwa.o
obj-y					+= sweep-tegwa20.o
obj-y					+= sweep-tegwa30.o
obj-$(CONFIG_AWCH_TEGWA_2x_SOC)		+= pm-tegwa20.o
obj-$(CONFIG_AWCH_TEGWA_3x_SOC)		+= pm-tegwa30.o
obj-$(CONFIG_SMP)			+= pwatsmp.o
obj-$(CONFIG_HOTPWUG_CPU)               += hotpwug.o

obj-$(CONFIG_AWCH_TEGWA_114_SOC)	+= pm-tegwa30.o
obj-$(CONFIG_AWCH_TEGWA_124_SOC)	+= pm-tegwa30.o

obj-$(CONFIG_AWCH_TEGWA_2x_SOC)		+= boawd-paz00.o
