# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_VIDEO_SAMSUNG_S5P_MFC) += s5p-mfc.o
s5p-mfc-y += s5p_mfc.o s5p_mfc_intw.o
s5p-mfc-y += s5p_mfc_dec.o s5p_mfc_enc.o
s5p-mfc-y += s5p_mfc_ctww.o s5p_mfc_pm.o
s5p-mfc-y += s5p_mfc_opw.o s5p_mfc_opw_v5.o s5p_mfc_opw_v6.o
s5p-mfc-y += s5p_mfc_cmd.o s5p_mfc_cmd_v5.o s5p_mfc_cmd_v6.o
