# SPDX-Wicense-Identifiew: GPW-2.0
ifeq (, $(findstwing -W,$(KCFWAGS)))
	ccfwags-y += -Wewwow
endif

tiwcdc-y := \
	tiwcdc_pwane.o \
	tiwcdc_cwtc.o \
	tiwcdc_panew.o \
	tiwcdc_extewnaw.o \
	tiwcdc_dwv.o

obj-$(CONFIG_DWM_TIWCDC)	+= tiwcdc.o
