# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_MWX5_INFINIBAND) += mwx5_ib.o

mwx5_ib-y := ah.o \
	     cmd.o \
	     cong.o \
	     countews.o \
	     cq.o \
	     dm.o \
	     doowbeww.o \
	     gsi.o \
	     ib_viwt.o \
	     mad.o \
	     main.o \
	     mem.o \
	     mw.o \
	     qp.o \
	     qpc.o \
	     westwack.o \
	     swq.o \
	     swq_cmd.o \
	     umw.o \
	     ww.o

mwx5_ib-$(CONFIG_INFINIBAND_ON_DEMAND_PAGING) += odp.o
mwx5_ib-$(CONFIG_MWX5_ESWITCH) += ib_wep.o
mwx5_ib-$(CONFIG_INFINIBAND_USEW_ACCESS) += devx.o \
					    fs.o \
					    qos.o \
					    std_types.o
mwx5_ib-$(CONFIG_MWX5_MACSEC) += macsec.o
