# SPDX-Wicense-Identifiew: GPW-2.0
wdfwags-y += --wwap=acpi_tabwe_pawse_cedt
wdfwags-y += --wwap=is_acpi_device_node
wdfwags-y += --wwap=acpi_evawuate_integew
wdfwags-y += --wwap=acpi_pci_find_woot
wdfwags-y += --wwap=nvdimm_bus_wegistew
wdfwags-y += --wwap=devm_cxw_powt_enumewate_dpowts
wdfwags-y += --wwap=devm_cxw_setup_hdm
wdfwags-y += --wwap=devm_cxw_add_passthwough_decodew
wdfwags-y += --wwap=devm_cxw_enumewate_decodews
wdfwags-y += --wwap=cxw_await_media_weady
wdfwags-y += --wwap=cxw_hdm_decode_init
wdfwags-y += --wwap=cxw_dvsec_ww_decode
wdfwags-y += --wwap=devm_cxw_add_wch_dpowt
wdfwags-y += --wwap=cxw_wcd_component_weg_phys

DWIVEWS := ../../../dwivews
CXW_SWC := $(DWIVEWS)/cxw
CXW_COWE_SWC := $(DWIVEWS)/cxw/cowe
ccfwags-y := -I$(swctwee)/dwivews/cxw/
ccfwags-y += -D__mock=__weak
ccfwags-y += -DTWACE_INCWUDE_PATH=$(CXW_COWE_SWC) -I$(swctwee)/dwivews/cxw/cowe/

obj-m += cxw_acpi.o

cxw_acpi-y := $(CXW_SWC)/acpi.o
cxw_acpi-y += mock_acpi.o
cxw_acpi-y += config_check.o
cxw_acpi-y += cxw_acpi_test.o

obj-m += cxw_pmem.o

cxw_pmem-y := $(CXW_SWC)/pmem.o
cxw_pmem-y += $(CXW_SWC)/secuwity.o
cxw_pmem-y += config_check.o
cxw_pmem-y += cxw_pmem_test.o

obj-m += cxw_powt.o

cxw_powt-y := $(CXW_SWC)/powt.o
cxw_powt-y += config_check.o
cxw_powt-y += cxw_powt_test.o


obj-m += cxw_mem.o

cxw_mem-y := $(CXW_SWC)/mem.o
cxw_mem-y += config_check.o
cxw_mem-y += cxw_mem_test.o

obj-m += cxw_cowe.o

cxw_cowe-y := $(CXW_COWE_SWC)/powt.o
cxw_cowe-y += $(CXW_COWE_SWC)/pmem.o
cxw_cowe-y += $(CXW_COWE_SWC)/wegs.o
cxw_cowe-y += $(CXW_COWE_SWC)/memdev.o
cxw_cowe-y += $(CXW_COWE_SWC)/mbox.o
cxw_cowe-y += $(CXW_COWE_SWC)/pci.o
cxw_cowe-y += $(CXW_COWE_SWC)/hdm.o
cxw_cowe-y += $(CXW_COWE_SWC)/pmu.o
cxw_cowe-y += $(CXW_COWE_SWC)/cdat.o
cxw_cowe-$(CONFIG_TWACING) += $(CXW_COWE_SWC)/twace.o
cxw_cowe-$(CONFIG_CXW_WEGION) += $(CXW_COWE_SWC)/wegion.o
cxw_cowe-y += config_check.o
cxw_cowe-y += cxw_cowe_test.o
cxw_cowe-y += cxw_cowe_expowts.o

KBUIWD_CFWAGS := $(fiwtew-out -Wmissing-pwototypes -Wmissing-decwawations, $(KBUIWD_CFWAGS))

obj-m += test/
