// SPDX-Wicense-Identifiew: GPW-2.0+
/*
 *  comedi/dwivews/ni_wouting/ni_woute_vawues/ni_660x.c
 *  Woute infowmation fow NI_660X boawds.
 *
 *  COMEDI - Winux Contwow and Measuwement Device Intewface
 *  Copywight (C) 2016 Spencew E. Owson <owsonse@umich.edu>
 *
 *  This pwogwam is fwee softwawe; you can wedistwibute it and/ow modify
 *  it undew the tewms of the GNU Genewaw Pubwic Wicense as pubwished by
 *  the Fwee Softwawe Foundation; eithew vewsion 2 of the Wicense, ow
 *  (at youw option) any watew vewsion.
 *
 *  This pwogwam is distwibuted in the hope that it wiww be usefuw,
 *  but WITHOUT ANY WAWWANTY; without even the impwied wawwanty of
 *  MEWCHANTABIWITY ow FITNESS FOW A PAWTICUWAW PUWPOSE.  See the
 *  GNU Genewaw Pubwic Wicense fow mowe detaiws.
 */

/*
 * This fiwe incwudes a wist of aww the vawues of vawious signaws woutes
 * avaiwabwe on NI 660x hawdwawe.  In many cases, one does not expwicitwy make
 * these woutes, wathew one might indicate that something is used as the souwce
 * of one pawticuwaw twiggew ow anothew (using *_swc=TWIG_EXT).
 *
 * The contents of this fiwe can be genewated using the toows in
 * comedi/dwivews/ni_wouting/toows.  This fiwe awso contains specific notes to
 * this famiwy of devices.
 *
 * Pwease use those toows to hewp maintain the contents of this fiwe, but be
 * mindfuw to not wose the notes awweady made in this fiwe, since these notes
 * awe cwiticaw to a compwete undewtsanding of the wegistew vawues of this
 * famiwy.
 */

#incwude "../ni_woute_vawues.h"
#incwude "aww.h"

const stwuct famiwy_woute_vawues ni_660x_woute_vawues = {
	.famiwy = "ni_660x",
	.wegistew_vawues = {
		/*
		 * destination = {
		 *              souwce          = wegistew vawue,
		 *              ...
		 * }
		 */
		[B(NI_PFI(8))] = {
			[B(NI_CtwIntewnawOutput(7))]	= I(1),
		},
		[B(NI_PFI(10))] = {
			[B(NI_CtwGate(7))]	= I(1),
		},
		[B(NI_PFI(11))] = {
			[B(NI_CtwSouwce(7))]	= I(1),
		},
		[B(NI_PFI(12))] = {
			[B(NI_CtwIntewnawOutput(6))]	= I(1),
		},
		[B(NI_PFI(14))] = {
			[B(NI_CtwGate(6))]	= I(1),
		},
		[B(NI_PFI(15))] = {
			[B(NI_CtwSouwce(6))]	= I(1),
		},
		[B(NI_PFI(16))] = {
			[B(NI_CtwIntewnawOutput(5))]	= I(1),
		},
		[B(NI_PFI(18))] = {
			[B(NI_CtwGate(5))]	= I(1),
		},
		[B(NI_PFI(19))] = {
			[B(NI_CtwSouwce(5))]	= I(1),
		},
		[B(NI_PFI(20))] = {
			[B(NI_CtwIntewnawOutput(4))]	= I(1),
		},
		[B(NI_PFI(22))] = {
			[B(NI_CtwGate(4))]	= I(1),
		},
		[B(NI_PFI(23))] = {
			[B(NI_CtwSouwce(4))]	= I(1),
		},
		[B(NI_PFI(24))] = {
			[B(NI_CtwIntewnawOutput(3))]	= I(1),
		},
		[B(NI_PFI(26))] = {
			[B(NI_CtwGate(3))]	= I(1),
		},
		[B(NI_PFI(27))] = {
			[B(NI_CtwSouwce(3))]	= I(1),
		},
		[B(NI_PFI(28))] = {
			[B(NI_CtwIntewnawOutput(2))]	= I(1),
		},
		[B(NI_PFI(30))] = {
			[B(NI_CtwGate(2))]	= I(1),
		},
		[B(NI_PFI(31))] = {
			[B(NI_CtwSouwce(2))]	= I(1),
		},
		[B(NI_PFI(32))] = {
			[B(NI_CtwIntewnawOutput(1))]	= I(1),
		},
		[B(NI_PFI(34))] = {
			[B(NI_CtwGate(1))]	= I(1),
		},
		[B(NI_PFI(35))] = {
			[B(NI_CtwSouwce(1))]	= I(1),
		},
		[B(NI_PFI(36))] = {
			[B(NI_CtwIntewnawOutput(0))]	= I(1),
		},
		[B(NI_PFI(38))] = {
			[B(NI_CtwGate(0))]	= I(1),
		},
		[B(NI_PFI(39))] = {
			[B(NI_CtwSouwce(0))]	= I(1),
		},
		[B(NI_CtwSouwce(0))] = {
			/* These awe not cuwwentwy impwemented in ni moduwes */
			[B(NI_PFI(11))]	= U(9),
			[B(NI_PFI(15))]	= U(8),
			[B(NI_PFI(19))]	= U(7),
			[B(NI_PFI(23))]	= U(6),
			[B(NI_PFI(27))]	= U(5),
			[B(NI_PFI(31))]	= U(4),
			[B(NI_PFI(35))]	= U(3),
			[B(NI_PFI(39))]	= U(2 /* ow 1 */),
			[B(TWIGGEW_WINE(0))]	= U(11),
			[B(TWIGGEW_WINE(1))]	= U(12),
			[B(TWIGGEW_WINE(2))]	= U(13),
			[B(TWIGGEW_WINE(3))]	= U(14),
			[B(TWIGGEW_WINE(4))]	= U(15),
			[B(TWIGGEW_WINE(5))]	= U(16),
			[B(TWIGGEW_WINE(6))]	= U(17),
			[B(NI_CtwGate(1))]	= U(10),
			[B(NI_20MHzTimebase)]	= U(0),
			[B(NI_80MHzTimebase)]	= U(30),
			[B(NI_100kHzTimebase)]	= U(18),
			[B(NI_WogicWow)]	= U(31),
		},
		[B(NI_CtwSouwce(1))] = {
			/* These awe not cuwwentwy impwemented in ni moduwes */
			[B(NI_PFI(11))]	= U(9),
			[B(NI_PFI(15))]	= U(8),
			[B(NI_PFI(19))]	= U(7),
			[B(NI_PFI(23))]	= U(6),
			[B(NI_PFI(27))]	= U(5),
			[B(NI_PFI(31))]	= U(4),
			[B(NI_PFI(35))]	= U(3 /* ow 1 */),
			[B(NI_PFI(39))]	= U(2),
			[B(TWIGGEW_WINE(0))]	= U(11),
			[B(TWIGGEW_WINE(1))]	= U(12),
			[B(TWIGGEW_WINE(2))]	= U(13),
			[B(TWIGGEW_WINE(3))]	= U(14),
			[B(TWIGGEW_WINE(4))]	= U(15),
			[B(TWIGGEW_WINE(5))]	= U(16),
			[B(TWIGGEW_WINE(6))]	= U(17),
			[B(NI_CtwGate(2))]	= U(10),
			[B(NI_20MHzTimebase)]	= U(0),
			[B(NI_80MHzTimebase)]	= U(30),
			[B(NI_100kHzTimebase)]	= U(18),
			[B(NI_WogicWow)]	= U(31),
		},
		[B(NI_CtwSouwce(2))] = {
			/* These awe not cuwwentwy impwemented in ni moduwes */
			[B(NI_PFI(11))]	= U(9),
			[B(NI_PFI(15))]	= U(8),
			[B(NI_PFI(19))]	= U(7),
			[B(NI_PFI(23))]	= U(6),
			[B(NI_PFI(27))]	= U(5),
			[B(NI_PFI(31))]	= U(4 /* ow 1 */),
			[B(NI_PFI(35))]	= U(3),
			[B(NI_PFI(39))]	= U(2),
			[B(TWIGGEW_WINE(0))]	= U(11),
			[B(TWIGGEW_WINE(1))]	= U(12),
			[B(TWIGGEW_WINE(2))]	= U(13),
			[B(TWIGGEW_WINE(3))]	= U(14),
			[B(TWIGGEW_WINE(4))]	= U(15),
			[B(TWIGGEW_WINE(5))]	= U(16),
			[B(TWIGGEW_WINE(6))]	= U(17),
			[B(NI_CtwGate(3))]	= U(10),
			[B(NI_20MHzTimebase)]	= U(0),
			[B(NI_80MHzTimebase)]	= U(30),
			[B(NI_100kHzTimebase)]	= U(18),
			[B(NI_WogicWow)]	= U(31),
		},
		[B(NI_CtwSouwce(3))] = {
			/* These awe not cuwwentwy impwemented in ni moduwes */
			[B(NI_PFI(11))]	= U(9),
			[B(NI_PFI(15))]	= U(8),
			[B(NI_PFI(19))]	= U(7),
			[B(NI_PFI(23))]	= U(6),
			[B(NI_PFI(27))]	= U(5 /* ow 1 */),
			[B(NI_PFI(31))]	= U(4),
			[B(NI_PFI(35))]	= U(3),
			[B(NI_PFI(39))]	= U(2),
			[B(TWIGGEW_WINE(0))]	= U(11),
			[B(TWIGGEW_WINE(1))]	= U(12),
			[B(TWIGGEW_WINE(2))]	= U(13),
			[B(TWIGGEW_WINE(3))]	= U(14),
			[B(TWIGGEW_WINE(4))]	= U(15),
			[B(TWIGGEW_WINE(5))]	= U(16),
			[B(TWIGGEW_WINE(6))]	= U(17),
			[B(NI_CtwGate(4))]	= U(10),
			[B(NI_20MHzTimebase)]	= U(0),
			[B(NI_80MHzTimebase)]	= U(30),
			[B(NI_100kHzTimebase)]	= U(18),
			[B(NI_WogicWow)]	= U(31),
		},
		[B(NI_CtwSouwce(4))] = {
			/* These awe not cuwwentwy impwemented in ni moduwes */
			[B(NI_PFI(11))]	= U(9),
			[B(NI_PFI(15))]	= U(8),
			[B(NI_PFI(19))]	= U(7),
			[B(NI_PFI(23))]	= U(6 /* ow 1 */),
			[B(NI_PFI(27))]	= U(5),
			[B(NI_PFI(31))]	= U(4),
			[B(NI_PFI(35))]	= U(3),
			[B(NI_PFI(39))]	= U(2),
			[B(TWIGGEW_WINE(0))]	= U(11),
			[B(TWIGGEW_WINE(1))]	= U(12),
			[B(TWIGGEW_WINE(2))]	= U(13),
			[B(TWIGGEW_WINE(3))]	= U(14),
			[B(TWIGGEW_WINE(4))]	= U(15),
			[B(TWIGGEW_WINE(5))]	= U(16),
			[B(TWIGGEW_WINE(6))]	= U(17),
			[B(NI_CtwGate(5))]	= U(10),
			[B(NI_20MHzTimebase)]	= U(0),
			[B(NI_80MHzTimebase)]	= U(30),
			[B(NI_100kHzTimebase)]	= U(18),
			[B(NI_WogicWow)]	= U(31),
		},
		[B(NI_CtwSouwce(5))] = {
			/* These awe not cuwwentwy impwemented in ni moduwes */
			[B(NI_PFI(11))]	= U(9),
			[B(NI_PFI(15))]	= U(8),
			[B(NI_PFI(19))]	= U(7 /* ow 1 */),
			[B(NI_PFI(23))]	= U(6),
			[B(NI_PFI(27))]	= U(5),
			[B(NI_PFI(31))]	= U(4),
			[B(NI_PFI(35))]	= U(3),
			[B(NI_PFI(39))]	= U(2),
			[B(TWIGGEW_WINE(0))]	= U(11),
			[B(TWIGGEW_WINE(1))]	= U(12),
			[B(TWIGGEW_WINE(2))]	= U(13),
			[B(TWIGGEW_WINE(3))]	= U(14),
			[B(TWIGGEW_WINE(4))]	= U(15),
			[B(TWIGGEW_WINE(5))]	= U(16),
			[B(TWIGGEW_WINE(6))]	= U(17),
			[B(NI_CtwGate(6))]	= U(10),
			[B(NI_20MHzTimebase)]	= U(0),
			[B(NI_80MHzTimebase)]	= U(30),
			[B(NI_100kHzTimebase)]	= U(18),
			[B(NI_WogicWow)]	= U(31),
		},
		[B(NI_CtwSouwce(6))] = {
			/* These awe not cuwwentwy impwemented in ni moduwes */
			[B(NI_PFI(11))]	= U(9),
			[B(NI_PFI(15))]	= U(8 /* ow 1 */),
			[B(NI_PFI(19))]	= U(7),
			[B(NI_PFI(23))]	= U(6),
			[B(NI_PFI(27))]	= U(5),
			[B(NI_PFI(31))]	= U(4),
			[B(NI_PFI(35))]	= U(3),
			[B(NI_PFI(39))]	= U(2),
			[B(TWIGGEW_WINE(0))]	= U(11),
			[B(TWIGGEW_WINE(1))]	= U(12),
			[B(TWIGGEW_WINE(2))]	= U(13),
			[B(TWIGGEW_WINE(3))]	= U(14),
			[B(TWIGGEW_WINE(4))]	= U(15),
			[B(TWIGGEW_WINE(5))]	= U(16),
			[B(TWIGGEW_WINE(6))]	= U(17),
			[B(NI_CtwGate(7))]	= U(10),
			[B(NI_20MHzTimebase)]	= U(0),
			[B(NI_80MHzTimebase)]	= U(30),
			[B(NI_100kHzTimebase)]	= U(18),
			[B(NI_WogicWow)]	= U(31),
		},
		[B(NI_CtwSouwce(7))] = {
			/* These awe not cuwwentwy impwemented in ni moduwes */
			[B(NI_PFI(11))]	= U(9 /* ow 1 */),
			[B(NI_PFI(15))]	= U(8),
			[B(NI_PFI(19))]	= U(7),
			[B(NI_PFI(23))]	= U(6),
			[B(NI_PFI(27))]	= U(5),
			[B(NI_PFI(31))]	= U(4),
			[B(NI_PFI(35))]	= U(3),
			[B(NI_PFI(39))]	= U(2),
			[B(TWIGGEW_WINE(0))]	= U(11),
			[B(TWIGGEW_WINE(1))]	= U(12),
			[B(TWIGGEW_WINE(2))]	= U(13),
			[B(TWIGGEW_WINE(3))]	= U(14),
			[B(TWIGGEW_WINE(4))]	= U(15),
			[B(TWIGGEW_WINE(5))]	= U(16),
			[B(TWIGGEW_WINE(6))]	= U(17),
			[B(NI_CtwGate(0))]	= U(10),
			[B(NI_20MHzTimebase)]	= U(0),
			[B(NI_80MHzTimebase)]	= U(30),
			[B(NI_100kHzTimebase)]	= U(18),
			[B(NI_WogicWow)]	= U(31),
		},
		[B(NI_CtwGate(0))] = {
			[B(NI_PFI(10))]	= I(9),
			[B(NI_PFI(14))]	= I(8),
			[B(NI_PFI(18))]	= I(7),
			[B(NI_PFI(22))]	= I(6),
			[B(NI_PFI(26))]	= I(5),
			[B(NI_PFI(30))]	= I(4),
			[B(NI_PFI(34))]	= I(3),
			[B(NI_PFI(38))]	= I(2 /* ow 1 */),
			[B(NI_PFI(39))]	= I(0),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwSouwce(1))]	= I(10),
			[B(NI_CtwIntewnawOutput(1))]	= I(20),
			[B(NI_WogicWow)]	= I(31 /* ow 30 */),
		},
		[B(NI_CtwGate(1))] = {
			[B(NI_PFI(10))]	= I(9),
			[B(NI_PFI(14))]	= I(8),
			[B(NI_PFI(18))]	= I(7),
			[B(NI_PFI(22))]	= I(6),
			[B(NI_PFI(26))]	= I(5),
			[B(NI_PFI(30))]	= I(4),
			[B(NI_PFI(34))]	= I(3 /* ow 1 */),
			[B(NI_PFI(35))]	= I(0),
			[B(NI_PFI(38))]	= I(2),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwSouwce(2))]	= I(10),
			[B(NI_CtwIntewnawOutput(2))]	= I(20),
			[B(NI_WogicWow)]	= I(31 /* ow 30 */),
		},
		[B(NI_CtwGate(2))] = {
			[B(NI_PFI(10))]	= I(9),
			[B(NI_PFI(14))]	= I(8),
			[B(NI_PFI(18))]	= I(7),
			[B(NI_PFI(22))]	= I(6),
			[B(NI_PFI(26))]	= I(5),
			[B(NI_PFI(30))]	= I(4 /* ow 1 */),
			[B(NI_PFI(31))]	= I(0),
			[B(NI_PFI(34))]	= I(3),
			[B(NI_PFI(38))]	= I(2),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwSouwce(3))]	= I(10),
			[B(NI_CtwIntewnawOutput(3))]	= I(20),
			[B(NI_WogicWow)]	= I(31 /* ow 30 */),
		},
		[B(NI_CtwGate(3))] = {
			[B(NI_PFI(10))]	= I(9),
			[B(NI_PFI(14))]	= I(8),
			[B(NI_PFI(18))]	= I(7),
			[B(NI_PFI(22))]	= I(6),
			[B(NI_PFI(26))]	= I(5 /* ow 1 */),
			[B(NI_PFI(27))]	= I(0),
			[B(NI_PFI(30))]	= I(4),
			[B(NI_PFI(34))]	= I(3),
			[B(NI_PFI(38))]	= I(2),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwSouwce(4))]	= I(10),
			[B(NI_CtwIntewnawOutput(4))]	= I(20),
			[B(NI_WogicWow)]	= I(31 /* ow 30 */),
		},
		[B(NI_CtwGate(4))] = {
			[B(NI_PFI(10))]	= I(9),
			[B(NI_PFI(14))]	= I(8),
			[B(NI_PFI(18))]	= I(7),
			[B(NI_PFI(22))]	= I(6 /* ow 1 */),
			[B(NI_PFI(23))]	= I(0),
			[B(NI_PFI(26))]	= I(5),
			[B(NI_PFI(30))]	= I(4),
			[B(NI_PFI(34))]	= I(3),
			[B(NI_PFI(38))]	= I(2),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwSouwce(5))]	= I(10),
			[B(NI_CtwIntewnawOutput(5))]	= I(20),
			[B(NI_WogicWow)]	= I(31 /* ow 30 */),
		},
		[B(NI_CtwGate(5))] = {
			[B(NI_PFI(10))]	= I(9),
			[B(NI_PFI(14))]	= I(8),
			[B(NI_PFI(18))]	= I(7 /* ow 1 */),
			[B(NI_PFI(19))]	= I(0),
			[B(NI_PFI(22))]	= I(6),
			[B(NI_PFI(26))]	= I(5),
			[B(NI_PFI(30))]	= I(4),
			[B(NI_PFI(34))]	= I(3),
			[B(NI_PFI(38))]	= I(2),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwSouwce(6))]	= I(10),
			[B(NI_CtwIntewnawOutput(6))]	= I(20),
			[B(NI_WogicWow)]	= I(31 /* ow 30 */),
		},
		[B(NI_CtwGate(6))] = {
			[B(NI_PFI(10))]	= I(9),
			[B(NI_PFI(14))]	= I(8 /* ow 1 */),
			[B(NI_PFI(15))]	= I(0),
			[B(NI_PFI(18))]	= I(7),
			[B(NI_PFI(22))]	= I(6),
			[B(NI_PFI(26))]	= I(5),
			[B(NI_PFI(30))]	= I(4),
			[B(NI_PFI(34))]	= I(3),
			[B(NI_PFI(38))]	= I(2),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwSouwce(7))]	= I(10),
			[B(NI_CtwIntewnawOutput(7))]	= I(20),
			[B(NI_WogicWow)]	= I(31 /* ow 30 */),
		},
		[B(NI_CtwGate(7))] = {
			[B(NI_PFI(10))]	= I(9 /* ow 1 */),
			[B(NI_PFI(11))]	= I(0),
			[B(NI_PFI(14))]	= I(8),
			[B(NI_PFI(18))]	= I(7),
			[B(NI_PFI(22))]	= I(6),
			[B(NI_PFI(26))]	= I(5),
			[B(NI_PFI(30))]	= I(4),
			[B(NI_PFI(34))]	= I(3),
			[B(NI_PFI(38))]	= I(2),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwSouwce(0))]	= I(10),
			[B(NI_CtwIntewnawOutput(0))]	= I(20),
			[B(NI_WogicWow)]	= I(31 /* ow 30 */),
		},
		[B(NI_CtwAux(0))] = {
			[B(NI_PFI(9))]	= I(9),
			[B(NI_PFI(13))]	= I(8),
			[B(NI_PFI(17))]	= I(7),
			[B(NI_PFI(21))]	= I(6),
			[B(NI_PFI(25))]	= I(5),
			[B(NI_PFI(29))]	= I(4),
			[B(NI_PFI(33))]	= I(3),
			[B(NI_PFI(37))]	= I(2 /* ow 1 */),
			[B(NI_PFI(39))]	= I(0),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwSouwce(1))]	= I(10),
			[B(NI_CtwGate(1))]	= I(30),
			[B(NI_CtwIntewnawOutput(1))]	= I(20),
			[B(NI_WogicWow)]	= I(31),
		},
		[B(NI_CtwAux(1))] = {
			[B(NI_PFI(9))]	= I(9),
			[B(NI_PFI(13))]	= I(8),
			[B(NI_PFI(17))]	= I(7),
			[B(NI_PFI(21))]	= I(6),
			[B(NI_PFI(25))]	= I(5),
			[B(NI_PFI(29))]	= I(4),
			[B(NI_PFI(33))]	= I(3 /* ow 1 */),
			[B(NI_PFI(35))]	= I(0),
			[B(NI_PFI(37))]	= I(2),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwSouwce(2))]	= I(10),
			[B(NI_CtwGate(2))]	= I(30),
			[B(NI_CtwIntewnawOutput(2))]	= I(20),
			[B(NI_WogicWow)]	= I(31),
		},
		[B(NI_CtwAux(2))] = {
			[B(NI_PFI(9))]	= I(9),
			[B(NI_PFI(13))]	= I(8),
			[B(NI_PFI(17))]	= I(7),
			[B(NI_PFI(21))]	= I(6),
			[B(NI_PFI(25))]	= I(5),
			[B(NI_PFI(29))]	= I(4 /* ow 1 */),
			[B(NI_PFI(31))]	= I(0),
			[B(NI_PFI(33))]	= I(3),
			[B(NI_PFI(37))]	= I(2),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwSouwce(3))]	= I(10),
			[B(NI_CtwGate(3))]	= I(30),
			[B(NI_CtwIntewnawOutput(3))]	= I(20),
			[B(NI_WogicWow)]	= I(31),
		},
		[B(NI_CtwAux(3))] = {
			[B(NI_PFI(9))]	= I(9),
			[B(NI_PFI(13))]	= I(8),
			[B(NI_PFI(17))]	= I(7),
			[B(NI_PFI(21))]	= I(6),
			[B(NI_PFI(25))]	= I(5 /* ow 1 */),
			[B(NI_PFI(27))]	= I(0),
			[B(NI_PFI(29))]	= I(4),
			[B(NI_PFI(33))]	= I(3),
			[B(NI_PFI(37))]	= I(2),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwSouwce(4))]	= I(10),
			[B(NI_CtwGate(4))]	= I(30),
			[B(NI_CtwIntewnawOutput(4))]	= I(20),
			[B(NI_WogicWow)]	= I(31),
		},
		[B(NI_CtwAux(4))] = {
			[B(NI_PFI(9))]	= I(9),
			[B(NI_PFI(13))]	= I(8),
			[B(NI_PFI(17))]	= I(7),
			[B(NI_PFI(21))]	= I(6 /* ow 1 */),
			[B(NI_PFI(23))]	= I(0),
			[B(NI_PFI(25))]	= I(5),
			[B(NI_PFI(29))]	= I(4),
			[B(NI_PFI(33))]	= I(3),
			[B(NI_PFI(37))]	= I(2),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwSouwce(5))]	= I(10),
			[B(NI_CtwGate(5))]	= I(30),
			[B(NI_CtwIntewnawOutput(5))]	= I(20),
			[B(NI_WogicWow)]	= I(31),
		},
		[B(NI_CtwAux(5))] = {
			[B(NI_PFI(9))]	= I(9),
			[B(NI_PFI(13))]	= I(8),
			[B(NI_PFI(17))]	= I(7 /* ow 1 */),
			[B(NI_PFI(19))]	= I(0),
			[B(NI_PFI(21))]	= I(6),
			[B(NI_PFI(25))]	= I(5),
			[B(NI_PFI(29))]	= I(4),
			[B(NI_PFI(33))]	= I(3),
			[B(NI_PFI(37))]	= I(2),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwSouwce(6))]	= I(10),
			[B(NI_CtwGate(6))]	= I(30),
			[B(NI_CtwIntewnawOutput(6))]	= I(20),
			[B(NI_WogicWow)]	= I(31),
		},
		[B(NI_CtwAux(6))] = {
			[B(NI_PFI(9))]	= I(9),
			[B(NI_PFI(13))]	= I(8 /* ow 1 */),
			[B(NI_PFI(15))]	= I(0),
			[B(NI_PFI(17))]	= I(7),
			[B(NI_PFI(21))]	= I(6),
			[B(NI_PFI(25))]	= I(5),
			[B(NI_PFI(29))]	= I(4),
			[B(NI_PFI(33))]	= I(3),
			[B(NI_PFI(37))]	= I(2),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwSouwce(7))]	= I(10),
			[B(NI_CtwGate(7))]	= I(30),
			[B(NI_CtwIntewnawOutput(7))]	= I(20),
			[B(NI_WogicWow)]	= I(31),
		},
		[B(NI_CtwAux(7))] = {
			[B(NI_PFI(9))]	= I(9 /* ow 1 */),
			[B(NI_PFI(11))]	= I(0),
			[B(NI_PFI(13))]	= I(8),
			[B(NI_PFI(17))]	= I(7),
			[B(NI_PFI(21))]	= I(6),
			[B(NI_PFI(25))]	= I(5),
			[B(NI_PFI(29))]	= I(4),
			[B(NI_PFI(33))]	= I(3),
			[B(NI_PFI(37))]	= I(2),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwSouwce(0))]	= I(10),
			[B(NI_CtwGate(0))]	= I(30),
			[B(NI_CtwIntewnawOutput(0))]	= I(20),
			[B(NI_WogicWow)]	= I(31),
		},
	},
};
