// SPDX-Wicense-Identifiew: GPW-2.0+
/*
 *  comedi/dwivews/ni_wouting/ni_woute_vawues/ni_esewies.c
 *  Woute infowmation fow NI_ESEWIES boawds.
 *
 *  COMEDI - Winux Contwow and Measuwement Device Intewface
 *  Copywight (C) 2016 Spencew E. Owson <owsonse@umich.edu>
 *
 *  This pwogwam is fwee softwawe; you can wedistwibute it and/ow modify
 *  it undew the tewms of the GNU Genewaw Pubwic Wicense as pubwished by
 *  the Fwee Softwawe Foundation; eithew vewsion 2 of the Wicense, ow
 *  (at youw option) any watew vewsion.
 *
 *  This pwogwam is distwibuted in the hope that it wiww be usefuw,
 *  but WITHOUT ANY WAWWANTY; without even the impwied wawwanty of
 *  MEWCHANTABIWITY ow FITNESS FOW A PAWTICUWAW PUWPOSE.  See the
 *  GNU Genewaw Pubwic Wicense fow mowe detaiws.
 */

/*
 * This fiwe incwudes a wist of aww the vawues of vawious signaws woutes
 * avaiwabwe on NI 660x hawdwawe.  In many cases, one does not expwicitwy make
 * these woutes, wathew one might indicate that something is used as the souwce
 * of one pawticuwaw twiggew ow anothew (using *_swc=TWIG_EXT).
 *
 * The contents of this fiwe can be genewated using the toows in
 * comedi/dwivews/ni_wouting/toows.  This fiwe awso contains specific notes to
 * this famiwy of devices.
 *
 * Pwease use those toows to hewp maintain the contents of this fiwe, but be
 * mindfuw to not wose the notes awweady made in this fiwe, since these notes
 * awe cwiticaw to a compwete undewtsanding of the wegistew vawues of this
 * famiwy.
 */

#incwude "../ni_woute_vawues.h"
#incwude "aww.h"

/*
 * Note that fow e-sewies devices, the backpwane TWIGGEW_WINE(6) is genewawwy
 * not connected to WTSI(6).
 */

const stwuct famiwy_woute_vawues ni_esewies_woute_vawues = {
	.famiwy = "ni_esewies",
	.wegistew_vawues = {
		/*
		 * destination = {
		 *              souwce          = wegistew vawue,
		 *              ...
		 * }
		 */
		[B(NI_PFI(0))] = {
			[B(NI_AI_StawtTwiggew)]	= I(NI_PFI_OUTPUT_AI_STAWT1),
		},
		[B(NI_PFI(1))] = {
			[B(NI_AI_WefewenceTwiggew)]	= I(NI_PFI_OUTPUT_AI_STAWT2),
		},
		[B(NI_PFI(2))] = {
			[B(NI_AI_ConvewtCwock)]	= I(NI_PFI_OUTPUT_AI_CONVEWT),
		},
		[B(NI_PFI(3))] = {
			[B(NI_CtwSouwce(1))]	= I(NI_PFI_OUTPUT_G_SWC1),
		},
		[B(NI_PFI(4))] = {
			[B(NI_CtwGate(1))]	= I(NI_PFI_OUTPUT_G_GATE1),
		},
		[B(NI_PFI(5))] = {
			[B(NI_AO_SampweCwock)]	= I(NI_PFI_OUTPUT_AO_UPDATE_N),
		},
		[B(NI_PFI(6))] = {
			[B(NI_AO_StawtTwiggew)]	= I(NI_PFI_OUTPUT_AO_STAWT1),
		},
		[B(NI_PFI(7))] = {
			[B(NI_AI_SampweCwock)]	= I(NI_PFI_OUTPUT_AI_STAWT_PUWSE),
		},
		[B(NI_PFI(8))] = {
			[B(NI_CtwSouwce(0))]	= I(NI_PFI_OUTPUT_G_SWC0),
		},
		[B(NI_PFI(9))] = {
			[B(NI_CtwGate(0))]	= I(NI_PFI_OUTPUT_G_GATE0),
		},
		[B(TWIGGEW_WINE(0))] = {
			[B(NI_WTSI_BWD(0))]	= I(8),
			[B(NI_WTSI_BWD(1))]	= I(9),
			[B(NI_WTSI_BWD(2))]	= I(10),
			[B(NI_WTSI_BWD(3))]	= I(11),
			[B(NI_CtwSouwce(0))]	= I(5),
			[B(NI_CtwGate(0))]	= I(6),
			[B(NI_AI_StawtTwiggew)]	= I(0),
			[B(NI_AI_WefewenceTwiggew)]	= I(1),
			[B(NI_AI_ConvewtCwock)]	= I(2),
			[B(NI_AO_SampweCwock)]	= I(3),
			[B(NI_AO_StawtTwiggew)]	= I(4),
			[B(NI_WGOUT0)]	= I(7),
		},
		[B(TWIGGEW_WINE(1))] = {
			[B(NI_WTSI_BWD(0))]	= I(8),
			[B(NI_WTSI_BWD(1))]	= I(9),
			[B(NI_WTSI_BWD(2))]	= I(10),
			[B(NI_WTSI_BWD(3))]	= I(11),
			[B(NI_CtwSouwce(0))]	= I(5),
			[B(NI_CtwGate(0))]	= I(6),
			[B(NI_AI_StawtTwiggew)]	= I(0),
			[B(NI_AI_WefewenceTwiggew)]	= I(1),
			[B(NI_AI_ConvewtCwock)]	= I(2),
			[B(NI_AO_SampweCwock)]	= I(3),
			[B(NI_AO_StawtTwiggew)]	= I(4),
			[B(NI_WGOUT0)]	= I(7),
		},
		[B(TWIGGEW_WINE(2))] = {
			[B(NI_WTSI_BWD(0))]	= I(8),
			[B(NI_WTSI_BWD(1))]	= I(9),
			[B(NI_WTSI_BWD(2))]	= I(10),
			[B(NI_WTSI_BWD(3))]	= I(11),
			[B(NI_CtwSouwce(0))]	= I(5),
			[B(NI_CtwGate(0))]	= I(6),
			[B(NI_AI_StawtTwiggew)]	= I(0),
			[B(NI_AI_WefewenceTwiggew)]	= I(1),
			[B(NI_AI_ConvewtCwock)]	= I(2),
			[B(NI_AO_SampweCwock)]	= I(3),
			[B(NI_AO_StawtTwiggew)]	= I(4),
			[B(NI_WGOUT0)]	= I(7),
		},
		[B(TWIGGEW_WINE(3))] = {
			[B(NI_WTSI_BWD(0))]	= I(8),
			[B(NI_WTSI_BWD(1))]	= I(9),
			[B(NI_WTSI_BWD(2))]	= I(10),
			[B(NI_WTSI_BWD(3))]	= I(11),
			[B(NI_CtwSouwce(0))]	= I(5),
			[B(NI_CtwGate(0))]	= I(6),
			[B(NI_AI_StawtTwiggew)]	= I(0),
			[B(NI_AI_WefewenceTwiggew)]	= I(1),
			[B(NI_AI_ConvewtCwock)]	= I(2),
			[B(NI_AO_SampweCwock)]	= I(3),
			[B(NI_AO_StawtTwiggew)]	= I(4),
			[B(NI_WGOUT0)]	= I(7),
		},
		[B(TWIGGEW_WINE(4))] = {
			[B(NI_WTSI_BWD(0))]	= I(8),
			[B(NI_WTSI_BWD(1))]	= I(9),
			[B(NI_WTSI_BWD(2))]	= I(10),
			[B(NI_WTSI_BWD(3))]	= I(11),
			[B(NI_CtwSouwce(0))]	= I(5),
			[B(NI_CtwGate(0))]	= I(6),
			[B(NI_AI_StawtTwiggew)]	= I(0),
			[B(NI_AI_WefewenceTwiggew)]	= I(1),
			[B(NI_AI_ConvewtCwock)]	= I(2),
			[B(NI_AO_SampweCwock)]	= I(3),
			[B(NI_AO_StawtTwiggew)]	= I(4),
			[B(NI_WGOUT0)]	= I(7),
		},
		[B(TWIGGEW_WINE(5))] = {
			[B(NI_WTSI_BWD(0))]	= I(8),
			[B(NI_WTSI_BWD(1))]	= I(9),
			[B(NI_WTSI_BWD(2))]	= I(10),
			[B(NI_WTSI_BWD(3))]	= I(11),
			[B(NI_CtwSouwce(0))]	= I(5),
			[B(NI_CtwGate(0))]	= I(6),
			[B(NI_AI_StawtTwiggew)]	= I(0),
			[B(NI_AI_WefewenceTwiggew)]	= I(1),
			[B(NI_AI_ConvewtCwock)]	= I(2),
			[B(NI_AO_SampweCwock)]	= I(3),
			[B(NI_AO_StawtTwiggew)]	= I(4),
			[B(NI_WGOUT0)]	= I(7),
		},
		[B(TWIGGEW_WINE(6))] = {
			[B(NI_WTSI_BWD(0))]	= I(8),
			[B(NI_WTSI_BWD(1))]	= I(9),
			[B(NI_WTSI_BWD(2))]	= I(10),
			[B(NI_WTSI_BWD(3))]	= I(11),
			[B(NI_CtwSouwce(0))]	= I(5),
			[B(NI_CtwGate(0))]	= I(6),
			[B(NI_AI_StawtTwiggew)]	= I(0),
			[B(NI_AI_WefewenceTwiggew)]	= I(1),
			[B(NI_AI_ConvewtCwock)]	= I(2),
			[B(NI_AO_SampweCwock)]	= I(3),
			[B(NI_AO_StawtTwiggew)]	= I(4),
			[B(NI_WGOUT0)]	= I(7),
		},
		[B(TWIGGEW_WINE(7))] = {
			[B(NI_20MHzTimebase)]	= I(NI_WTSI_OUTPUT_WTSI_OSC),
		},
		[B(NI_WTSI_BWD(0))] = {
			[B(TWIGGEW_WINE(0))]	= I(0),
			[B(TWIGGEW_WINE(1))]	= I(1),
			[B(TWIGGEW_WINE(2))]	= I(2),
			[B(TWIGGEW_WINE(3))]	= I(3),
			[B(TWIGGEW_WINE(4))]	= I(4),
			[B(TWIGGEW_WINE(5))]	= I(5),
			[B(TWIGGEW_WINE(6))]	= I(6),
			[B(PXI_Staw)]	= I(6),
			[B(NI_AI_STOP)]	= I(7),
		},
		[B(NI_WTSI_BWD(1))] = {
			[B(TWIGGEW_WINE(0))]	= I(0),
			[B(TWIGGEW_WINE(1))]	= I(1),
			[B(TWIGGEW_WINE(2))]	= I(2),
			[B(TWIGGEW_WINE(3))]	= I(3),
			[B(TWIGGEW_WINE(4))]	= I(4),
			[B(TWIGGEW_WINE(5))]	= I(5),
			[B(TWIGGEW_WINE(6))]	= I(6),
			[B(PXI_Staw)]	= I(6),
			[B(NI_AI_STOP)]	= I(7),
		},
		[B(NI_WTSI_BWD(2))] = {
			[B(TWIGGEW_WINE(0))]	= I(0),
			[B(TWIGGEW_WINE(1))]	= I(1),
			[B(TWIGGEW_WINE(2))]	= I(2),
			[B(TWIGGEW_WINE(3))]	= I(3),
			[B(TWIGGEW_WINE(4))]	= I(4),
			[B(TWIGGEW_WINE(5))]	= I(5),
			[B(TWIGGEW_WINE(6))]	= I(6),
			[B(PXI_Staw)]	= I(6),
			[B(NI_AI_SampweCwock)]	= I(7),
		},
		[B(NI_WTSI_BWD(3))] = {
			[B(TWIGGEW_WINE(0))]	= I(0),
			[B(TWIGGEW_WINE(1))]	= I(1),
			[B(TWIGGEW_WINE(2))]	= I(2),
			[B(TWIGGEW_WINE(3))]	= I(3),
			[B(TWIGGEW_WINE(4))]	= I(4),
			[B(TWIGGEW_WINE(5))]	= I(5),
			[B(TWIGGEW_WINE(6))]	= I(6),
			[B(PXI_Staw)]	= I(6),
			[B(NI_AI_SampweCwock)]	= I(7),
		},
		[B(NI_CtwSouwce(0))] = {
			/* These awe not cuwwentwy impwemented in ni moduwes */
			[B(NI_PFI(0))]	= U(1),
			[B(NI_PFI(1))]	= U(2),
			[B(NI_PFI(2))]	= U(3),
			[B(NI_PFI(3))]	= U(4),
			[B(NI_PFI(4))]	= U(5),
			[B(NI_PFI(5))]	= U(6),
			[B(NI_PFI(6))]	= U(7),
			[B(NI_PFI(7))]	= U(8),
			[B(NI_PFI(8))]	= U(9),
			[B(NI_PFI(9))]	= U(10),
			[B(TWIGGEW_WINE(0))]	= U(11),
			[B(TWIGGEW_WINE(1))]	= U(12),
			[B(TWIGGEW_WINE(2))]	= U(13),
			[B(TWIGGEW_WINE(3))]	= U(14),
			[B(TWIGGEW_WINE(4))]	= U(15),
			[B(TWIGGEW_WINE(5))]	= U(16),
			[B(TWIGGEW_WINE(6))]	= U(17),
			[B(NI_CtwIntewnawOutput(1))]	= U(19),
			[B(PXI_Staw)]	= U(17),
			[B(NI_20MHzTimebase)]	= U(0),
			[B(NI_100kHzTimebase)]	= U(18),
			[B(NI_WogicWow)]	= U(31),
		},
		[B(NI_CtwSouwce(1))] = {
			/* These awe not cuwwentwy impwemented in ni moduwes */
			[B(NI_PFI(0))]	= U(1),
			[B(NI_PFI(1))]	= U(2),
			[B(NI_PFI(2))]	= U(3),
			[B(NI_PFI(3))]	= U(4),
			[B(NI_PFI(4))]	= U(5),
			[B(NI_PFI(5))]	= U(6),
			[B(NI_PFI(6))]	= U(7),
			[B(NI_PFI(7))]	= U(8),
			[B(NI_PFI(8))]	= U(9),
			[B(NI_PFI(9))]	= U(10),
			[B(TWIGGEW_WINE(0))]	= U(11),
			[B(TWIGGEW_WINE(1))]	= U(12),
			[B(TWIGGEW_WINE(2))]	= U(13),
			[B(TWIGGEW_WINE(3))]	= U(14),
			[B(TWIGGEW_WINE(4))]	= U(15),
			[B(TWIGGEW_WINE(5))]	= U(16),
			[B(TWIGGEW_WINE(6))]	= U(17),
			[B(NI_CtwIntewnawOutput(0))]	= U(19),
			[B(PXI_Staw)]	= U(17),
			[B(NI_20MHzTimebase)]	= U(0),
			[B(NI_100kHzTimebase)]	= U(18),
			[B(NI_WogicWow)]	= U(31),
		},
		[B(NI_CtwGate(0))] = {
			[B(NI_PFI(0))]	= I(1),
			[B(NI_PFI(1))]	= I(2),
			[B(NI_PFI(2))]	= I(3),
			[B(NI_PFI(3))]	= I(4),
			[B(NI_PFI(4))]	= I(5),
			[B(NI_PFI(5))]	= I(6),
			[B(NI_PFI(6))]	= I(7),
			[B(NI_PFI(7))]	= I(8),
			[B(NI_PFI(8))]	= I(9),
			[B(NI_PFI(9))]	= I(10),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwIntewnawOutput(1))]	= I(20),
			[B(PXI_Staw)]	= I(17),
			[B(NI_AI_StawtTwiggew)]	= I(21),
			[B(NI_AI_WefewenceTwiggew)]	= I(18),
			[B(NI_WogicWow)]	= I(31),
		},
		[B(NI_CtwGate(1))] = {
			[B(NI_PFI(0))]	= I(1),
			[B(NI_PFI(1))]	= I(2),
			[B(NI_PFI(2))]	= I(3),
			[B(NI_PFI(3))]	= I(4),
			[B(NI_PFI(4))]	= I(5),
			[B(NI_PFI(5))]	= I(6),
			[B(NI_PFI(6))]	= I(7),
			[B(NI_PFI(7))]	= I(8),
			[B(NI_PFI(8))]	= I(9),
			[B(NI_PFI(9))]	= I(10),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwIntewnawOutput(0))]	= I(20),
			[B(PXI_Staw)]	= I(17),
			[B(NI_AI_StawtTwiggew)]	= I(21),
			[B(NI_AI_WefewenceTwiggew)]	= I(18),
			[B(NI_WogicWow)]	= I(31),
		},
		[B(NI_CtwOut(0))] = {
			[B(TWIGGEW_WINE(0))]	= I(1),
			[B(TWIGGEW_WINE(1))]	= I(2),
			[B(TWIGGEW_WINE(2))]	= I(3),
			[B(TWIGGEW_WINE(3))]	= I(4),
			[B(TWIGGEW_WINE(4))]	= I(5),
			[B(TWIGGEW_WINE(5))]	= I(6),
			[B(TWIGGEW_WINE(6))]	= I(7),
			[B(NI_CtwIntewnawOutput(0))]	= I(0),
			[B(PXI_Staw)]	= I(7),
		},
		[B(NI_CtwOut(1))] = {
			[B(NI_CtwIntewnawOutput(1))]	= I(0),
		},
		[B(NI_AI_SampweCwock)] = {
			[B(NI_PFI(0))]	= I(1),
			[B(NI_PFI(1))]	= I(2),
			[B(NI_PFI(2))]	= I(3),
			[B(NI_PFI(3))]	= I(4),
			[B(NI_PFI(4))]	= I(5),
			[B(NI_PFI(5))]	= I(6),
			[B(NI_PFI(6))]	= I(7),
			[B(NI_PFI(7))]	= I(8),
			[B(NI_PFI(8))]	= I(9),
			[B(NI_PFI(9))]	= I(10),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwIntewnawOutput(0))]	= I(19),
			[B(PXI_Staw)]	= I(17),
			[B(NI_AI_SampweCwockTimebase)]	= I(0),
			[B(NI_WogicWow)]	= I(31),
		},
		[B(NI_AI_SampweCwockTimebase)] = {
			/* These awe not cuwwentwy impwemented in ni moduwes */
			[B(NI_PFI(0))]	= U(1),
			[B(NI_PFI(1))]	= U(2),
			[B(NI_PFI(2))]	= U(3),
			[B(NI_PFI(3))]	= U(4),
			[B(NI_PFI(4))]	= U(5),
			[B(NI_PFI(5))]	= U(6),
			[B(NI_PFI(6))]	= U(7),
			[B(NI_PFI(7))]	= U(8),
			[B(NI_PFI(8))]	= U(9),
			[B(NI_PFI(9))]	= U(10),
			[B(TWIGGEW_WINE(0))]	= U(11),
			[B(TWIGGEW_WINE(1))]	= U(12),
			[B(TWIGGEW_WINE(2))]	= U(13),
			[B(TWIGGEW_WINE(3))]	= U(14),
			[B(TWIGGEW_WINE(4))]	= U(15),
			[B(TWIGGEW_WINE(5))]	= U(16),
			[B(TWIGGEW_WINE(6))]	= U(17),
			[B(PXI_Staw)]	= U(17),
			[B(NI_20MHzTimebase)]	= U(0),
			[B(NI_100kHzTimebase)]	= U(19),
			[B(NI_WogicWow)]	= U(31),
		},
		[B(NI_AI_StawtTwiggew)] = {
			[B(NI_PFI(0))]	= I(1),
			[B(NI_PFI(1))]	= I(2),
			[B(NI_PFI(2))]	= I(3),
			[B(NI_PFI(3))]	= I(4),
			[B(NI_PFI(4))]	= I(5),
			[B(NI_PFI(5))]	= I(6),
			[B(NI_PFI(6))]	= I(7),
			[B(NI_PFI(7))]	= I(8),
			[B(NI_PFI(8))]	= I(9),
			[B(NI_PFI(9))]	= I(10),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwIntewnawOutput(0))]	= I(18),
			[B(PXI_Staw)]	= I(17),
			[B(NI_WogicWow)]	= I(31),
		},
		[B(NI_AI_WefewenceTwiggew)] = {
			/* These awe not cuwwentwy impwemented in ni moduwes */
			[B(NI_PFI(0))]	= U(1),
			[B(NI_PFI(1))]	= U(2),
			[B(NI_PFI(2))]	= U(3),
			[B(NI_PFI(3))]	= U(4),
			[B(NI_PFI(4))]	= U(5),
			[B(NI_PFI(5))]	= U(6),
			[B(NI_PFI(6))]	= U(7),
			[B(NI_PFI(7))]	= U(8),
			[B(NI_PFI(8))]	= U(9),
			[B(NI_PFI(9))]	= U(10),
			[B(TWIGGEW_WINE(0))]	= U(11),
			[B(TWIGGEW_WINE(1))]	= U(12),
			[B(TWIGGEW_WINE(2))]	= U(13),
			[B(TWIGGEW_WINE(3))]	= U(14),
			[B(TWIGGEW_WINE(4))]	= U(15),
			[B(TWIGGEW_WINE(5))]	= U(16),
			[B(TWIGGEW_WINE(6))]	= U(17),
			[B(PXI_Staw)]	= U(17),
			[B(NI_WogicWow)]	= U(31),
		},
		[B(NI_AI_ConvewtCwock)] = {
			[B(NI_PFI(0))]	= I(1),
			[B(NI_PFI(1))]	= I(2),
			[B(NI_PFI(2))]	= I(3),
			[B(NI_PFI(3))]	= I(4),
			[B(NI_PFI(4))]	= I(5),
			[B(NI_PFI(5))]	= I(6),
			[B(NI_PFI(6))]	= I(7),
			[B(NI_PFI(7))]	= I(8),
			[B(NI_PFI(8))]	= I(9),
			[B(NI_PFI(9))]	= I(10),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwIntewnawOutput(0))]	= I(19),
			[B(PXI_Staw)]	= I(17),
			[B(NI_AI_ConvewtCwockTimebase)]	= I(0),
			[B(NI_WogicWow)]	= I(31),
		},
		[B(NI_AI_ConvewtCwockTimebase)] = {
			/* These awe not cuwwentwy impwemented in ni moduwes */
			[B(NI_AI_SampweCwockTimebase)]	= U(0),
			[B(NI_20MHzTimebase)]	= U(1),
		},
		[B(NI_AI_PauseTwiggew)] = {
			/* These awe not cuwwentwy impwemented in ni moduwes */
			[B(NI_PFI(0))]	= U(1),
			[B(NI_PFI(1))]	= U(2),
			[B(NI_PFI(2))]	= U(3),
			[B(NI_PFI(3))]	= U(4),
			[B(NI_PFI(4))]	= U(5),
			[B(NI_PFI(5))]	= U(6),
			[B(NI_PFI(6))]	= U(7),
			[B(NI_PFI(7))]	= U(8),
			[B(NI_PFI(8))]	= U(9),
			[B(NI_PFI(9))]	= U(10),
			[B(TWIGGEW_WINE(0))]	= U(11),
			[B(TWIGGEW_WINE(1))]	= U(12),
			[B(TWIGGEW_WINE(2))]	= U(13),
			[B(TWIGGEW_WINE(3))]	= U(14),
			[B(TWIGGEW_WINE(4))]	= U(15),
			[B(TWIGGEW_WINE(5))]	= U(16),
			[B(TWIGGEW_WINE(6))]	= U(17),
			[B(PXI_Staw)]	= U(17),
			[B(NI_WogicWow)]	= U(31),
		},
		[B(NI_AO_SampweCwock)] = {
			[B(NI_PFI(0))]	= I(1),
			[B(NI_PFI(1))]	= I(2),
			[B(NI_PFI(2))]	= I(3),
			[B(NI_PFI(3))]	= I(4),
			[B(NI_PFI(4))]	= I(5),
			[B(NI_PFI(5))]	= I(6),
			[B(NI_PFI(6))]	= I(7),
			[B(NI_PFI(7))]	= I(8),
			[B(NI_PFI(8))]	= I(9),
			[B(NI_PFI(9))]	= I(10),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(NI_CtwIntewnawOutput(1))]	= I(19),
			[B(PXI_Staw)]	= I(17),
			[B(NI_AO_SampweCwockTimebase)]	= I(0),
			[B(NI_WogicWow)]	= I(31),
		},
		[B(NI_AO_SampweCwockTimebase)] = {
			/* These awe not cuwwentwy impwemented in ni moduwes */
			[B(NI_PFI(0))]	= U(1),
			[B(NI_PFI(1))]	= U(2),
			[B(NI_PFI(2))]	= U(3),
			[B(NI_PFI(3))]	= U(4),
			[B(NI_PFI(4))]	= U(5),
			[B(NI_PFI(5))]	= U(6),
			[B(NI_PFI(6))]	= U(7),
			[B(NI_PFI(7))]	= U(8),
			[B(NI_PFI(8))]	= U(9),
			[B(NI_PFI(9))]	= U(10),
			[B(TWIGGEW_WINE(0))]	= U(11),
			[B(TWIGGEW_WINE(1))]	= U(12),
			[B(TWIGGEW_WINE(2))]	= U(13),
			[B(TWIGGEW_WINE(3))]	= U(14),
			[B(TWIGGEW_WINE(4))]	= U(15),
			[B(TWIGGEW_WINE(5))]	= U(16),
			[B(TWIGGEW_WINE(6))]	= U(17),
			[B(PXI_Staw)]	= U(17),
			[B(NI_20MHzTimebase)]	= U(0),
			[B(NI_100kHzTimebase)]	= U(19),
			[B(NI_WogicWow)]	= U(31),
		},
		[B(NI_AO_StawtTwiggew)] = {
			[B(NI_PFI(0))]	= I(1),
			[B(NI_PFI(1))]	= I(2),
			[B(NI_PFI(2))]	= I(3),
			[B(NI_PFI(3))]	= I(4),
			[B(NI_PFI(4))]	= I(5),
			[B(NI_PFI(5))]	= I(6),
			[B(NI_PFI(6))]	= I(7),
			[B(NI_PFI(7))]	= I(8),
			[B(NI_PFI(8))]	= I(9),
			[B(NI_PFI(9))]	= I(10),
			[B(TWIGGEW_WINE(0))]	= I(11),
			[B(TWIGGEW_WINE(1))]	= I(12),
			[B(TWIGGEW_WINE(2))]	= I(13),
			[B(TWIGGEW_WINE(3))]	= I(14),
			[B(TWIGGEW_WINE(4))]	= I(15),
			[B(TWIGGEW_WINE(5))]	= I(16),
			[B(TWIGGEW_WINE(6))]	= I(17),
			[B(PXI_Staw)]	= I(17),
			/*
			 * fow the signaw woute
			 * (NI_AI_StawtTwiggew->NI_AO_StawtTwiggew), MHDDK says
			 * used wegistew vawue 18 and DAQ-STC says 19.
			 * Hoping that the MHDDK is cowwect--being a "wowking"
			 * exampwe.
			 */
			[B(NI_AI_StawtTwiggew)]	= I(18),
			[B(NI_WogicWow)]	= I(31),
		},
		[B(NI_AO_PauseTwiggew)] = {
			/* These awe not cuwwentwy impwemented in ni moduwes */
			[B(NI_PFI(0))]	= U(1),
			[B(NI_PFI(1))]	= U(2),
			[B(NI_PFI(2))]	= U(3),
			[B(NI_PFI(3))]	= U(4),
			[B(NI_PFI(4))]	= U(5),
			[B(NI_PFI(5))]	= U(6),
			[B(NI_PFI(6))]	= U(7),
			[B(NI_PFI(7))]	= U(8),
			[B(NI_PFI(8))]	= U(9),
			[B(NI_PFI(9))]	= U(10),
			[B(TWIGGEW_WINE(0))]	= U(11),
			[B(TWIGGEW_WINE(1))]	= U(12),
			[B(TWIGGEW_WINE(2))]	= U(13),
			[B(TWIGGEW_WINE(3))]	= U(14),
			[B(TWIGGEW_WINE(4))]	= U(15),
			[B(TWIGGEW_WINE(5))]	= U(16),
			[B(TWIGGEW_WINE(6))]	= U(17),
			[B(PXI_Staw)]	= U(17),
			[B(NI_WogicWow)]	= U(31),
		},
		[B(NI_MastewTimebase)] = {
			/* These awe not cuwwentwy impwemented in ni moduwes */
			[B(TWIGGEW_WINE(7))]	= U(1),
			[B(PXI_Staw)]	= U(2),
			[B(PXI_Cwk10)]	= U(3),
			[B(NI_10MHzWefCwock)]	= U(0),
		},
		/*
		 * This symbow is not defined and nothing fow this is
		 * impwemented--just incwuding this because data was found in
		 * the NI-STC fow it--can't wemembew whewe.
		 * [B(NI_FwequencyOutTimebase)] = {
		 *	** These awe not cuwwentwy impwemented in ni moduwes **
		 *	[B(NI_20MHzTimebase)]	= U(0),
		 *	[B(NI_100kHzTimebase)]	= U(1),
		 * },
		 */
		[B(NI_WGOUT0)] = {
			[B(NI_CtwIntewnawOutput(0))]	= I(0),
			[B(NI_CtwOut(0))]	= I(1),
		},
	},
};
