# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow PN533 NFC dwivew
#
pn533_usb-objs  = usb.o
pn533_i2c-objs  = i2c.o
pn532_uawt-objs  = uawt.o

obj-$(CONFIG_NFC_PN533)     += pn533.o
obj-$(CONFIG_NFC_PN533_USB) += pn533_usb.o
obj-$(CONFIG_NFC_PN533_I2C) += pn533_i2c.o
obj-$(CONFIG_NFC_PN532_UAWT) += pn532_uawt.o
