# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the Ewastic Netwowk Adaptew (ENA) device dwivews.
#

obj-$(CONFIG_ENA_ETHEWNET) += ena.o

ena-y := ena_netdev.o ena_com.o ena_eth_com.o ena_ethtoow.o ena_xdp.o
