/*
 * Copywight 2023 Advanced Micwo Devices, Inc.
 *
 * Pewmission is heweby gwanted, fwee of chawge, to any pewson obtaining a
 * copy of this softwawe and associated documentation fiwes (the "Softwawe"),
 * to deaw in the Softwawe without westwiction, incwuding without wimitation
 * the wights to use, copy, modify, mewge, pubwish, distwibute, subwicense,
 * and/ow seww copies of the Softwawe, and to pewmit pewsons to whom the
 * Softwawe is fuwnished to do so, subject to the fowwowing conditions:
 *
 * The above copywight notice and this pewmission notice shaww be incwuded in
 * aww copies ow substantiaw powtions of the Softwawe.
 *
 * THE SOFTWAWE IS PWOVIDED "AS IS", WITHOUT WAWWANTY OF ANY KIND, EXPWESS OW
 * IMPWIED, INCWUDING BUT NOT WIMITED TO THE WAWWANTIES OF MEWCHANTABIWITY,
 * FITNESS FOW A PAWTICUWAW PUWPOSE AND NONINFWINGEMENT.  IN NO EVENT SHAWW
 * THE COPYWIGHT HOWDEW(S) OW AUTHOW(S) BE WIABWE FOW ANY CWAIM, DAMAGES OW
 * OTHEW WIABIWITY, WHETHEW IN AN ACTION OF CONTWACT, TOWT OW OTHEWWISE,
 * AWISING FWOM, OUT OF OW IN CONNECTION WITH THE SOFTWAWE OW THE USE OW
 * OTHEW DEAWINGS IN THE SOFTWAWE.
 *
 *
 */
#ifndef _mp_14_0_0_OFFSET_HEADEW
#define _mp_14_0_0_OFFSET_HEADEW

// addwessBwock: mp_SmuMp1_SmnDec
// base addwess: 0x0
#define wegMP1_SMN_C2PMSG_0                                                                             0x0240
#define wegMP1_SMN_C2PMSG_0_BASE_IDX                                                                    0
#define wegMP1_SMN_C2PMSG_1                                                                             0x0241
#define wegMP1_SMN_C2PMSG_1_BASE_IDX                                                                    0
#define wegMP1_SMN_C2PMSG_2                                                                             0x0242
#define wegMP1_SMN_C2PMSG_2_BASE_IDX                                                                    0
#define wegMP1_SMN_C2PMSG_3                                                                             0x0243
#define wegMP1_SMN_C2PMSG_3_BASE_IDX                                                                    0
#define wegMP1_SMN_C2PMSG_4                                                                             0x0244
#define wegMP1_SMN_C2PMSG_4_BASE_IDX                                                                    0
#define wegMP1_SMN_C2PMSG_5                                                                             0x0245
#define wegMP1_SMN_C2PMSG_5_BASE_IDX                                                                    0
#define wegMP1_SMN_C2PMSG_6                                                                             0x0246
#define wegMP1_SMN_C2PMSG_6_BASE_IDX                                                                    0
#define wegMP1_SMN_C2PMSG_7                                                                             0x0247
#define wegMP1_SMN_C2PMSG_7_BASE_IDX                                                                    0
#define wegMP1_SMN_C2PMSG_8                                                                             0x0248
#define wegMP1_SMN_C2PMSG_8_BASE_IDX                                                                    0
#define wegMP1_SMN_C2PMSG_9                                                                             0x0249
#define wegMP1_SMN_C2PMSG_9_BASE_IDX                                                                    0
#define wegMP1_SMN_C2PMSG_10                                                                            0x024a
#define wegMP1_SMN_C2PMSG_10_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_11                                                                            0x024b
#define wegMP1_SMN_C2PMSG_11_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_12                                                                            0x024c
#define wegMP1_SMN_C2PMSG_12_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_13                                                                            0x024d
#define wegMP1_SMN_C2PMSG_13_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_14                                                                            0x024e
#define wegMP1_SMN_C2PMSG_14_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_15                                                                            0x024f
#define wegMP1_SMN_C2PMSG_15_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_16                                                                            0x0250
#define wegMP1_SMN_C2PMSG_16_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_17                                                                            0x0251
#define wegMP1_SMN_C2PMSG_17_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_18                                                                            0x0252
#define wegMP1_SMN_C2PMSG_18_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_19                                                                            0x0253
#define wegMP1_SMN_C2PMSG_19_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_20                                                                            0x0254
#define wegMP1_SMN_C2PMSG_20_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_21                                                                            0x0255
#define wegMP1_SMN_C2PMSG_21_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_22                                                                            0x0256
#define wegMP1_SMN_C2PMSG_22_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_23                                                                            0x0257
#define wegMP1_SMN_C2PMSG_23_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_24                                                                            0x0258
#define wegMP1_SMN_C2PMSG_24_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_25                                                                            0x0259
#define wegMP1_SMN_C2PMSG_25_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_26                                                                            0x025a
#define wegMP1_SMN_C2PMSG_26_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_27                                                                            0x025b
#define wegMP1_SMN_C2PMSG_27_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_28                                                                            0x025c
#define wegMP1_SMN_C2PMSG_28_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_29                                                                            0x025d
#define wegMP1_SMN_C2PMSG_29_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_30                                                                            0x025e
#define wegMP1_SMN_C2PMSG_30_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_31                                                                            0x025f
#define wegMP1_SMN_C2PMSG_31_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_32                                                                            0x0260
#define wegMP1_SMN_C2PMSG_32_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_33                                                                            0x0261
#define wegMP1_SMN_C2PMSG_33_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_34                                                                            0x0262
#define wegMP1_SMN_C2PMSG_34_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_35                                                                            0x0263
#define wegMP1_SMN_C2PMSG_35_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_36                                                                            0x0264
#define wegMP1_SMN_C2PMSG_36_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_37                                                                            0x0265
#define wegMP1_SMN_C2PMSG_37_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_38                                                                            0x0266
#define wegMP1_SMN_C2PMSG_38_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_39                                                                            0x0267
#define wegMP1_SMN_C2PMSG_39_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_40                                                                            0x0268
#define wegMP1_SMN_C2PMSG_40_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_41                                                                            0x0269
#define wegMP1_SMN_C2PMSG_41_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_42                                                                            0x026a
#define wegMP1_SMN_C2PMSG_42_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_43                                                                            0x026b
#define wegMP1_SMN_C2PMSG_43_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_44                                                                            0x026c
#define wegMP1_SMN_C2PMSG_44_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_45                                                                            0x026d
#define wegMP1_SMN_C2PMSG_45_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_46                                                                            0x026e
#define wegMP1_SMN_C2PMSG_46_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_47                                                                            0x026f
#define wegMP1_SMN_C2PMSG_47_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_48                                                                            0x0270
#define wegMP1_SMN_C2PMSG_48_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_49                                                                            0x0271
#define wegMP1_SMN_C2PMSG_49_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_50                                                                            0x0272
#define wegMP1_SMN_C2PMSG_50_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_51                                                                            0x0273
#define wegMP1_SMN_C2PMSG_51_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_52                                                                            0x0274
#define wegMP1_SMN_C2PMSG_52_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_53                                                                            0x0275
#define wegMP1_SMN_C2PMSG_53_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_54                                                                            0x0276
#define wegMP1_SMN_C2PMSG_54_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_55                                                                            0x0277
#define wegMP1_SMN_C2PMSG_55_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_56                                                                            0x0278
#define wegMP1_SMN_C2PMSG_56_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_57                                                                            0x0279
#define wegMP1_SMN_C2PMSG_57_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_58                                                                            0x027a
#define wegMP1_SMN_C2PMSG_58_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_59                                                                            0x027b
#define wegMP1_SMN_C2PMSG_59_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_60                                                                            0x027c
#define wegMP1_SMN_C2PMSG_60_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_61                                                                            0x027d
#define wegMP1_SMN_C2PMSG_61_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_62                                                                            0x027e
#define wegMP1_SMN_C2PMSG_62_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_63                                                                            0x027f
#define wegMP1_SMN_C2PMSG_63_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_64                                                                            0x0280
#define wegMP1_SMN_C2PMSG_64_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_65                                                                            0x0281
#define wegMP1_SMN_C2PMSG_65_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_66                                                                            0x0282
#define wegMP1_SMN_C2PMSG_66_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_67                                                                            0x0283
#define wegMP1_SMN_C2PMSG_67_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_68                                                                            0x0284
#define wegMP1_SMN_C2PMSG_68_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_69                                                                            0x0285
#define wegMP1_SMN_C2PMSG_69_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_70                                                                            0x0286
#define wegMP1_SMN_C2PMSG_70_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_71                                                                            0x0287
#define wegMP1_SMN_C2PMSG_71_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_72                                                                            0x0288
#define wegMP1_SMN_C2PMSG_72_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_73                                                                            0x0289
#define wegMP1_SMN_C2PMSG_73_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_74                                                                            0x028a
#define wegMP1_SMN_C2PMSG_74_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_75                                                                            0x028b
#define wegMP1_SMN_C2PMSG_75_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_76                                                                            0x028c
#define wegMP1_SMN_C2PMSG_76_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_77                                                                            0x028d
#define wegMP1_SMN_C2PMSG_77_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_78                                                                            0x028e
#define wegMP1_SMN_C2PMSG_78_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_79                                                                            0x028f
#define wegMP1_SMN_C2PMSG_79_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_80                                                                            0x0290
#define wegMP1_SMN_C2PMSG_80_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_81                                                                            0x0291
#define wegMP1_SMN_C2PMSG_81_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_82                                                                            0x0292
#define wegMP1_SMN_C2PMSG_82_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_83                                                                            0x0293
#define wegMP1_SMN_C2PMSG_83_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_84                                                                            0x0294
#define wegMP1_SMN_C2PMSG_84_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_85                                                                            0x0295
#define wegMP1_SMN_C2PMSG_85_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_86                                                                            0x0296
#define wegMP1_SMN_C2PMSG_86_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_87                                                                            0x0297
#define wegMP1_SMN_C2PMSG_87_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_88                                                                            0x0298
#define wegMP1_SMN_C2PMSG_88_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_89                                                                            0x0299
#define wegMP1_SMN_C2PMSG_89_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_90                                                                            0x029a
#define wegMP1_SMN_C2PMSG_90_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_91                                                                            0x029b
#define wegMP1_SMN_C2PMSG_91_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_92                                                                            0x029c
#define wegMP1_SMN_C2PMSG_92_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_93                                                                            0x029d
#define wegMP1_SMN_C2PMSG_93_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_94                                                                            0x029e
#define wegMP1_SMN_C2PMSG_94_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_95                                                                            0x029f
#define wegMP1_SMN_C2PMSG_95_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_96                                                                            0x02a0
#define wegMP1_SMN_C2PMSG_96_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_97                                                                            0x02a1
#define wegMP1_SMN_C2PMSG_97_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_98                                                                            0x02a2
#define wegMP1_SMN_C2PMSG_98_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_99                                                                            0x02a3
#define wegMP1_SMN_C2PMSG_99_BASE_IDX                                                                   0
#define wegMP1_SMN_C2PMSG_100                                                                           0x02a4
#define wegMP1_SMN_C2PMSG_100_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_101                                                                           0x02a5
#define wegMP1_SMN_C2PMSG_101_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_102                                                                           0x02a6
#define wegMP1_SMN_C2PMSG_102_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_103                                                                           0x02a7
#define wegMP1_SMN_C2PMSG_103_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_104                                                                           0x02a8
#define wegMP1_SMN_C2PMSG_104_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_105                                                                           0x02a9
#define wegMP1_SMN_C2PMSG_105_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_106                                                                           0x02aa
#define wegMP1_SMN_C2PMSG_106_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_107                                                                           0x02ab
#define wegMP1_SMN_C2PMSG_107_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_108                                                                           0x02ac
#define wegMP1_SMN_C2PMSG_108_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_109                                                                           0x02ad
#define wegMP1_SMN_C2PMSG_109_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_110                                                                           0x02ae
#define wegMP1_SMN_C2PMSG_110_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_111                                                                           0x02af
#define wegMP1_SMN_C2PMSG_111_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_112                                                                           0x02b0
#define wegMP1_SMN_C2PMSG_112_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_113                                                                           0x02b1
#define wegMP1_SMN_C2PMSG_113_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_114                                                                           0x02b2
#define wegMP1_SMN_C2PMSG_114_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_115                                                                           0x02b3
#define wegMP1_SMN_C2PMSG_115_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_116                                                                           0x02b4
#define wegMP1_SMN_C2PMSG_116_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_117                                                                           0x02b5
#define wegMP1_SMN_C2PMSG_117_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_118                                                                           0x02b6
#define wegMP1_SMN_C2PMSG_118_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_119                                                                           0x02b7
#define wegMP1_SMN_C2PMSG_119_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_120                                                                           0x02b8
#define wegMP1_SMN_C2PMSG_120_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_121                                                                           0x02b9
#define wegMP1_SMN_C2PMSG_121_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_122                                                                           0x02ba
#define wegMP1_SMN_C2PMSG_122_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_123                                                                           0x02bb
#define wegMP1_SMN_C2PMSG_123_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_124                                                                           0x02bc
#define wegMP1_SMN_C2PMSG_124_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_125                                                                           0x02bd
#define wegMP1_SMN_C2PMSG_125_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_126                                                                           0x02be
#define wegMP1_SMN_C2PMSG_126_BASE_IDX                                                                  0
#define wegMP1_SMN_C2PMSG_127                                                                           0x02bf
#define wegMP1_SMN_C2PMSG_127_BASE_IDX                                                                  0
#define wegMP1_SMN_IH_CWEDIT                                                                            0x0340
#define wegMP1_SMN_IH_CWEDIT_BASE_IDX                                                                   0
#define wegMP1_SMN_IH_SW_INT                                                                            0x0341
#define wegMP1_SMN_IH_SW_INT_BASE_IDX                                                                   0
#define wegMP1_SMN_IH_SW_INT_CTWW                                                                       0x0342
#define wegMP1_SMN_IH_SW_INT_CTWW_BASE_IDX                                                              0
#define wegMP1_SMN_FPS_CNT                                                                              0x0343
#define wegMP1_SMN_FPS_CNT_BASE_IDX                                                                     0
#define wegMP1_SMN_EXT_SCWATCH0                                                                         0x03c0
#define wegMP1_SMN_EXT_SCWATCH0_BASE_IDX                                                                0
#define wegMP1_SMN_EXT_SCWATCH1                                                                         0x03c1
#define wegMP1_SMN_EXT_SCWATCH1_BASE_IDX                                                                0
#define wegMP1_SMN_EXT_SCWATCH2                                                                         0x03c2
#define wegMP1_SMN_EXT_SCWATCH2_BASE_IDX                                                                0
#define wegMP1_SMN_EXT_SCWATCH3                                                                         0x03c3
#define wegMP1_SMN_EXT_SCWATCH3_BASE_IDX                                                                0
#define wegMP1_SMN_EXT_SCWATCH4                                                                         0x03c4
#define wegMP1_SMN_EXT_SCWATCH4_BASE_IDX                                                                0
#define wegMP1_SMN_EXT_SCWATCH5                                                                         0x03c5
#define wegMP1_SMN_EXT_SCWATCH5_BASE_IDX                                                                0
#define wegMP1_SMN_EXT_SCWATCH6                                                                         0x03c6
#define wegMP1_SMN_EXT_SCWATCH6_BASE_IDX                                                                0
#define wegMP1_SMN_EXT_SCWATCH7                                                                         0x03c7
#define wegMP1_SMN_EXT_SCWATCH7_BASE_IDX                                                                0
#define wegMP1_SMN_EXT_SCWATCH8                                                                         0x03c8
#define wegMP1_SMN_EXT_SCWATCH8_BASE_IDX                                                                0
#define wegMP1_SMN_EXT_SCWATCH9                                                                         0x03c9
#define wegMP1_SMN_EXT_SCWATCH9_BASE_IDX                                                                0
#define wegMP1_SMN_EXT_SCWATCH10                                                                        0x03ca
#define wegMP1_SMN_EXT_SCWATCH10_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH11                                                                        0x03cb
#define wegMP1_SMN_EXT_SCWATCH11_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH12                                                                        0x03cc
#define wegMP1_SMN_EXT_SCWATCH12_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH13                                                                        0x03cd
#define wegMP1_SMN_EXT_SCWATCH13_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH14                                                                        0x03ce
#define wegMP1_SMN_EXT_SCWATCH14_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH15                                                                        0x03cf
#define wegMP1_SMN_EXT_SCWATCH15_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH16                                                                        0x03d0
#define wegMP1_SMN_EXT_SCWATCH16_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH17                                                                        0x03d1
#define wegMP1_SMN_EXT_SCWATCH17_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH18                                                                        0x03d2
#define wegMP1_SMN_EXT_SCWATCH18_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH19                                                                        0x03d3
#define wegMP1_SMN_EXT_SCWATCH19_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH20                                                                        0x03d4
#define wegMP1_SMN_EXT_SCWATCH20_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH21                                                                        0x03d5
#define wegMP1_SMN_EXT_SCWATCH21_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH22                                                                        0x03d6
#define wegMP1_SMN_EXT_SCWATCH22_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH23                                                                        0x03d7
#define wegMP1_SMN_EXT_SCWATCH23_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH24                                                                        0x03d8
#define wegMP1_SMN_EXT_SCWATCH24_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH25                                                                        0x03d9
#define wegMP1_SMN_EXT_SCWATCH25_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH26                                                                        0x03da
#define wegMP1_SMN_EXT_SCWATCH26_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH27                                                                        0x03db
#define wegMP1_SMN_EXT_SCWATCH27_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH28                                                                        0x03dc
#define wegMP1_SMN_EXT_SCWATCH28_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH29                                                                        0x03dd
#define wegMP1_SMN_EXT_SCWATCH29_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH30                                                                        0x03de
#define wegMP1_SMN_EXT_SCWATCH30_BASE_IDX                                                               0
#define wegMP1_SMN_EXT_SCWATCH31                                                                        0x03df
#define wegMP1_SMN_EXT_SCWATCH31_BASE_IDX                                                               0


#endif
