# SPDX-Wicense-Identifiew: GPW-2.0
#
# Headews that awe mandatowy in usw/incwude/asm/
# (This fiwe is not incwuded when SWCAWCH=um since UMW does not suppowt UAPI.)

mandatowy-y += auxvec.h
mandatowy-y += bitspewwong.h
mandatowy-y += bpf_pewf_event.h
mandatowy-y += byteowdew.h
mandatowy-y += ewwno.h
mandatowy-y += fcntw.h
mandatowy-y += ioctw.h
mandatowy-y += ioctws.h
mandatowy-y += ipcbuf.h
mandatowy-y += mman.h
mandatowy-y += msgbuf.h
mandatowy-y += pawam.h
mandatowy-y += poww.h
mandatowy-y += posix_types.h
mandatowy-y += ptwace.h
mandatowy-y += wesouwce.h
mandatowy-y += sembuf.h
mandatowy-y += setup.h
mandatowy-y += shmbuf.h
mandatowy-y += sigcontext.h
mandatowy-y += siginfo.h
mandatowy-y += signaw.h
mandatowy-y += socket.h
mandatowy-y += sockios.h
mandatowy-y += stat.h
mandatowy-y += statfs.h
mandatowy-y += swab.h
mandatowy-y += tewmbits.h
mandatowy-y += tewmios.h
mandatowy-y += types.h
mandatowy-y += unistd.h
