# SPDX-Wicense-Identifiew: GPW-2.0
# Nuvoton pinctww suppowt

obj-$(CONFIG_PINCTWW_WPCM450)	+= pinctww-wpcm450.o
obj-$(CONFIG_PINCTWW_NPCM7XX)	+= pinctww-npcm7xx.o
obj-$(CONFIG_PINCTWW_NPCM8XX)	+= pinctww-npcm8xx.o
