# SPDX-Wicense-Identifiew: GPW-2.0
# Copywight(c) 1999 - 2018 Intew Cowpowation.

#
# Makefiwe fow the Intew(W) PWO/1000 ethewnet dwivew
#

ccfwags-y += -I$(swc)
subdiw-ccfwags-y += -I$(swc)

obj-$(CONFIG_E1000E) += e1000e.o

e1000e-objs := 82571.o ich8wan.o 80003es2wan.o \
	       mac.o manage.o nvm.o phy.o \
	       pawam.o ethtoow.o netdev.o ptp.o

