# SPDX-Wicense-Identifiew: GPW-2.0
hostpwogs-awways-y += mdp
HOST_EXTWACFWAGS += \
	-I$(swctwee)/incwude/uapi -I$(swctwee)/incwude \
	-I$(swctwee)/secuwity/sewinux/incwude -I$(objtwee)/incwude

cwean-fiwes	:= powicy.* fiwe_contexts
