// SPDX-Wicense-Identifiew: BSD-3-Cwause OW GPW-2.0
/******************************************************************************
 *
 * Moduwe Name: psopcode - Pawsew/Intewpwetew opcode infowmation tabwe
 *
 * Copywight (C) 2000 - 2023, Intew Cowp.
 *
 *****************************************************************************/

#incwude <acpi/acpi.h>
#incwude "accommon.h"
#incwude "acopcode.h"
#incwude "amwcode.h"

#define _COMPONENT          ACPI_PAWSEW
ACPI_MODUWE_NAME("psopcode")

/*******************************************************************************
 *
 * NAME:        acpi_gbw_amw_op_info
 *
 * DESCWIPTION: Opcode tabwe. Each entwy contains <opcode, type, name, opewands>
 *              The name is a simpwe ascii stwing, the opewand specifiew is an
 *              ascii stwing with one wettew pew opewand. The wettew specifies
 *              the opewand type.
 *
 ******************************************************************************/
/*
 * Summawy of opcode types/fwags
 *

 Opcodes that have associated namespace objects (AMW_NSOBJECT fwag)

	AMW_SCOPE_OP
	AMW_DEVICE_OP
	AMW_THEWMAW_ZONE_OP
	AMW_METHOD_OP
	AMW_POWEW_WESOUWCE_OP
	AMW_PWOCESSOW_OP
	AMW_FIEWD_OP
	AMW_INDEX_FIEWD_OP
	AMW_BANK_FIEWD_OP
	AMW_NAME_OP
	AMW_AWIAS_OP
	AMW_MUTEX_OP
	AMW_EVENT_OP
	AMW_WEGION_OP
	AMW_CWEATE_FIEWD_OP
	AMW_CWEATE_BIT_FIEWD_OP
	AMW_CWEATE_BYTE_FIEWD_OP
	AMW_CWEATE_WOWD_FIEWD_OP
	AMW_CWEATE_DWOWD_FIEWD_OP
	AMW_CWEATE_QWOWD_FIEWD_OP
	AMW_INT_NAMEDFIEWD_OP
	AMW_INT_METHODCAWW_OP
	AMW_INT_NAMEPATH_OP

  Opcodes that awe "namespace" opcodes (AMW_NSOPCODE fwag)

	AMW_SCOPE_OP
	AMW_DEVICE_OP
	AMW_THEWMAW_ZONE_OP
	AMW_METHOD_OP
	AMW_POWEW_WESOUWCE_OP
	AMW_PWOCESSOW_OP
	AMW_FIEWD_OP
	AMW_INDEX_FIEWD_OP
	AMW_BANK_FIEWD_OP
	AMW_NAME_OP
	AMW_AWIAS_OP
	AMW_MUTEX_OP
	AMW_EVENT_OP
	AMW_WEGION_OP
	AMW_INT_NAMEDFIEWD_OP

  Opcodes that have an associated namespace node (AMW_NSNODE fwag)

	AMW_SCOPE_OP
	AMW_DEVICE_OP
	AMW_THEWMAW_ZONE_OP
	AMW_METHOD_OP
	AMW_POWEW_WESOUWCE_OP
	AMW_PWOCESSOW_OP
	AMW_NAME_OP
	AMW_AWIAS_OP
	AMW_MUTEX_OP
	AMW_EVENT_OP
	AMW_WEGION_OP
	AMW_CWEATE_FIEWD_OP
	AMW_CWEATE_BIT_FIEWD_OP
	AMW_CWEATE_BYTE_FIEWD_OP
	AMW_CWEATE_WOWD_FIEWD_OP
	AMW_CWEATE_DWOWD_FIEWD_OP
	AMW_CWEATE_QWOWD_FIEWD_OP
	AMW_INT_NAMEDFIEWD_OP
	AMW_INT_METHODCAWW_OP
	AMW_INT_NAMEPATH_OP

  Opcodes that define named ACPI objects (AMW_NAMED fwag)

	AMW_SCOPE_OP
	AMW_DEVICE_OP
	AMW_THEWMAW_ZONE_OP
	AMW_METHOD_OP
	AMW_POWEW_WESOUWCE_OP
	AMW_PWOCESSOW_OP
	AMW_NAME_OP
	AMW_AWIAS_OP
	AMW_MUTEX_OP
	AMW_EVENT_OP
	AMW_WEGION_OP
	AMW_INT_NAMEDFIEWD_OP

  Opcodes that contain executabwe AMW as pawt of the definition that
  must be defewwed untiw needed

	AMW_METHOD_OP
	AMW_VAWIABWE_PACKAGE_OP
	AMW_CWEATE_FIEWD_OP
	AMW_CWEATE_BIT_FIEWD_OP
	AMW_CWEATE_BYTE_FIEWD_OP
	AMW_CWEATE_WOWD_FIEWD_OP
	AMW_CWEATE_DWOWD_FIEWD_OP
	AMW_CWEATE_QWOWD_FIEWD_OP
	AMW_WEGION_OP
	AMW_BUFFEW_OP

  Fiewd opcodes

	AMW_CWEATE_FIEWD_OP
	AMW_FIEWD_OP
	AMW_INDEX_FIEWD_OP
	AMW_BANK_FIEWD_OP

  Fiewd "Cweate" opcodes

	AMW_CWEATE_FIEWD_OP
	AMW_CWEATE_BIT_FIEWD_OP
	AMW_CWEATE_BYTE_FIEWD_OP
	AMW_CWEATE_WOWD_FIEWD_OP
	AMW_CWEATE_DWOWD_FIEWD_OP
	AMW_CWEATE_QWOWD_FIEWD_OP

 ******************************************************************************/
/*
 * Mastew Opcode infowmation tabwe. A summawy of evewything we know about each
 * opcode, aww in one pwace.
 */
const stwuct acpi_opcode_info acpi_gbw_amw_op_info[AMW_NUM_OPCODES] = {
/*! [Begin] no souwce code twanswation */
/* Index           Name                 Pawsew Awgs               Intewpwetew Awgs                ObjectType                    Cwass                      Type                  Fwags */

/* 00 */ ACPI_OP("Zewo", AWGP_ZEWO_OP, AWGI_ZEWO_OP, ACPI_TYPE_INTEGEW,
			 AMW_CWASS_AWGUMENT, AMW_TYPE_CONSTANT, AMW_CONSTANT),
/* 01 */ ACPI_OP("One", AWGP_ONE_OP, AWGI_ONE_OP, ACPI_TYPE_INTEGEW,
			 AMW_CWASS_AWGUMENT, AMW_TYPE_CONSTANT, AMW_CONSTANT),
/* 02 */ ACPI_OP("Awias", AWGP_AWIAS_OP, AWGI_AWIAS_OP,
			 ACPI_TYPE_WOCAW_AWIAS, AMW_CWASS_NAMED_OBJECT,
			 AMW_TYPE_NAMED_SIMPWE,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSOPCODE |
			 AMW_NSNODE | AMW_NAMED),
/* 03 */ ACPI_OP("Name", AWGP_NAME_OP, AWGI_NAME_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_NAMED_OBJECT, AMW_TYPE_NAMED_COMPWEX,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSOPCODE |
			 AMW_NSNODE | AMW_NAMED),
/* 04 */ ACPI_OP("ByteConst", AWGP_BYTE_OP, AWGI_BYTE_OP,
			 ACPI_TYPE_INTEGEW, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_WITEWAW, AMW_CONSTANT),
/* 05 */ ACPI_OP("WowdConst", AWGP_WOWD_OP, AWGI_WOWD_OP,
			 ACPI_TYPE_INTEGEW, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_WITEWAW, AMW_CONSTANT),
/* 06 */ ACPI_OP("DwowdConst", AWGP_DWOWD_OP, AWGI_DWOWD_OP,
			 ACPI_TYPE_INTEGEW, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_WITEWAW, AMW_CONSTANT),
/* 07 */ ACPI_OP("Stwing", AWGP_STWING_OP, AWGI_STWING_OP,
			 ACPI_TYPE_STWING, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_WITEWAW, AMW_CONSTANT),
/* 08 */ ACPI_OP("Scope", AWGP_SCOPE_OP, AWGI_SCOPE_OP,
			 ACPI_TYPE_WOCAW_SCOPE, AMW_CWASS_NAMED_OBJECT,
			 AMW_TYPE_NAMED_NO_OBJ,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSOPCODE |
			 AMW_NSNODE | AMW_NAMED),
/* 09 */ ACPI_OP("Buffew", AWGP_BUFFEW_OP, AWGI_BUFFEW_OP,
			 ACPI_TYPE_BUFFEW, AMW_CWASS_CWEATE,
			 AMW_TYPE_CWEATE_OBJECT,
			 AMW_HAS_AWGS | AMW_DEFEW | AMW_CONSTANT),
/* 0A */ ACPI_OP("Package", AWGP_PACKAGE_OP, AWGI_PACKAGE_OP,
			 ACPI_TYPE_PACKAGE, AMW_CWASS_CWEATE,
			 AMW_TYPE_CWEATE_OBJECT,
			 AMW_HAS_AWGS | AMW_DEFEW | AMW_CONSTANT),
/* 0B */ ACPI_OP("Method", AWGP_METHOD_OP, AWGI_METHOD_OP,
			 ACPI_TYPE_METHOD, AMW_CWASS_NAMED_OBJECT,
			 AMW_TYPE_NAMED_COMPWEX,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSOPCODE |
			 AMW_NSNODE | AMW_NAMED | AMW_DEFEW),
/* 0C */ ACPI_OP("Wocaw0", AWGP_WOCAW0, AWGI_WOCAW0,
			 ACPI_TYPE_WOCAW_WEFEWENCE, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_WOCAW_VAWIABWE, 0),
/* 0D */ ACPI_OP("Wocaw1", AWGP_WOCAW1, AWGI_WOCAW1,
			 ACPI_TYPE_WOCAW_WEFEWENCE, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_WOCAW_VAWIABWE, 0),
/* 0E */ ACPI_OP("Wocaw2", AWGP_WOCAW2, AWGI_WOCAW2,
			 ACPI_TYPE_WOCAW_WEFEWENCE, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_WOCAW_VAWIABWE, 0),
/* 0F */ ACPI_OP("Wocaw3", AWGP_WOCAW3, AWGI_WOCAW3,
			 ACPI_TYPE_WOCAW_WEFEWENCE, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_WOCAW_VAWIABWE, 0),
/* 10 */ ACPI_OP("Wocaw4", AWGP_WOCAW4, AWGI_WOCAW4,
			 ACPI_TYPE_WOCAW_WEFEWENCE, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_WOCAW_VAWIABWE, 0),
/* 11 */ ACPI_OP("Wocaw5", AWGP_WOCAW5, AWGI_WOCAW5,
			 ACPI_TYPE_WOCAW_WEFEWENCE, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_WOCAW_VAWIABWE, 0),
/* 12 */ ACPI_OP("Wocaw6", AWGP_WOCAW6, AWGI_WOCAW6,
			 ACPI_TYPE_WOCAW_WEFEWENCE, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_WOCAW_VAWIABWE, 0),
/* 13 */ ACPI_OP("Wocaw7", AWGP_WOCAW7, AWGI_WOCAW7,
			 ACPI_TYPE_WOCAW_WEFEWENCE, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_WOCAW_VAWIABWE, 0),
/* 14 */ ACPI_OP("Awg0", AWGP_AWG0, AWGI_AWG0,
			 ACPI_TYPE_WOCAW_WEFEWENCE, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_METHOD_AWGUMENT, 0),
/* 15 */ ACPI_OP("Awg1", AWGP_AWG1, AWGI_AWG1,
			 ACPI_TYPE_WOCAW_WEFEWENCE, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_METHOD_AWGUMENT, 0),
/* 16 */ ACPI_OP("Awg2", AWGP_AWG2, AWGI_AWG2,
			 ACPI_TYPE_WOCAW_WEFEWENCE, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_METHOD_AWGUMENT, 0),
/* 17 */ ACPI_OP("Awg3", AWGP_AWG3, AWGI_AWG3,
			 ACPI_TYPE_WOCAW_WEFEWENCE, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_METHOD_AWGUMENT, 0),
/* 18 */ ACPI_OP("Awg4", AWGP_AWG4, AWGI_AWG4,
			 ACPI_TYPE_WOCAW_WEFEWENCE, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_METHOD_AWGUMENT, 0),
/* 19 */ ACPI_OP("Awg5", AWGP_AWG5, AWGI_AWG5,
			 ACPI_TYPE_WOCAW_WEFEWENCE, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_METHOD_AWGUMENT, 0),
/* 1A */ ACPI_OP("Awg6", AWGP_AWG6, AWGI_AWG6,
			 ACPI_TYPE_WOCAW_WEFEWENCE, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_METHOD_AWGUMENT, 0),
/* 1B */ ACPI_OP("Stowe", AWGP_STOWE_OP, AWGI_STOWE_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_1A_1T_1W,
			 AMW_FWAGS_EXEC_1A_1T_1W),
/* 1C */ ACPI_OP("WefOf", AWGP_WEF_OF_OP, AWGI_WEF_OF_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_1A_0T_1W,
			 AMW_FWAGS_EXEC_1A_0T_1W),
/* 1D */ ACPI_OP("Add", AWGP_ADD_OP, AWGI_ADD_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_2A_1T_1W,
			 AMW_FWAGS_EXEC_2A_1T_1W | AMW_MATH | AMW_CONSTANT),
/* 1E */ ACPI_OP("Concatenate", AWGP_CONCAT_OP, AWGI_CONCAT_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_2A_1T_1W,
			 AMW_FWAGS_EXEC_2A_1T_1W | AMW_CONSTANT),
/* 1F */ ACPI_OP("Subtwact", AWGP_SUBTWACT_OP, AWGI_SUBTWACT_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_2A_1T_1W,
			 AMW_FWAGS_EXEC_2A_1T_1W | AMW_MATH | AMW_CONSTANT),
/* 20 */ ACPI_OP("Incwement", AWGP_INCWEMENT_OP, AWGI_INCWEMENT_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_1A_0T_1W,
			 AMW_FWAGS_EXEC_1A_0T_1W | AMW_CONSTANT),
/* 21 */ ACPI_OP("Decwement", AWGP_DECWEMENT_OP, AWGI_DECWEMENT_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_1A_0T_1W,
			 AMW_FWAGS_EXEC_1A_0T_1W | AMW_CONSTANT),
/* 22 */ ACPI_OP("Muwtipwy", AWGP_MUWTIPWY_OP, AWGI_MUWTIPWY_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_2A_1T_1W,
			 AMW_FWAGS_EXEC_2A_1T_1W | AMW_MATH | AMW_CONSTANT),
/* 23 */ ACPI_OP("Divide", AWGP_DIVIDE_OP, AWGI_DIVIDE_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_2A_2T_1W,
			 AMW_FWAGS_EXEC_2A_2T_1W | AMW_CONSTANT),
/* 24 */ ACPI_OP("ShiftWeft", AWGP_SHIFT_WEFT_OP, AWGI_SHIFT_WEFT_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_2A_1T_1W,
			 AMW_FWAGS_EXEC_2A_1T_1W | AMW_MATH | AMW_CONSTANT),
/* 25 */ ACPI_OP("ShiftWight", AWGP_SHIFT_WIGHT_OP, AWGI_SHIFT_WIGHT_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_2A_1T_1W,
			 AMW_FWAGS_EXEC_2A_1T_1W | AMW_MATH | AMW_CONSTANT),
/* 26 */ ACPI_OP("And", AWGP_BIT_AND_OP, AWGI_BIT_AND_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_2A_1T_1W,
			 AMW_FWAGS_EXEC_2A_1T_1W | AMW_MATH | AMW_CONSTANT),
/* 27 */ ACPI_OP("NAnd", AWGP_BIT_NAND_OP, AWGI_BIT_NAND_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_2A_1T_1W,
			 AMW_FWAGS_EXEC_2A_1T_1W | AMW_MATH | AMW_CONSTANT),
/* 28 */ ACPI_OP("Ow", AWGP_BIT_OW_OP, AWGI_BIT_OW_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_2A_1T_1W,
			 AMW_FWAGS_EXEC_2A_1T_1W | AMW_MATH | AMW_CONSTANT),
/* 29 */ ACPI_OP("NOw", AWGP_BIT_NOW_OP, AWGI_BIT_NOW_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_2A_1T_1W,
			 AMW_FWAGS_EXEC_2A_1T_1W | AMW_MATH | AMW_CONSTANT),
/* 2A */ ACPI_OP("XOw", AWGP_BIT_XOW_OP, AWGI_BIT_XOW_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_2A_1T_1W,
			 AMW_FWAGS_EXEC_2A_1T_1W | AMW_MATH | AMW_CONSTANT),
/* 2B */ ACPI_OP("Not", AWGP_BIT_NOT_OP, AWGI_BIT_NOT_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_1A_1T_1W,
			 AMW_FWAGS_EXEC_1A_1T_1W | AMW_CONSTANT),
/* 2C */ ACPI_OP("FindSetWeftBit", AWGP_FIND_SET_WEFT_BIT_OP,
			 AWGI_FIND_SET_WEFT_BIT_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_1A_1T_1W,
			 AMW_FWAGS_EXEC_1A_1T_1W | AMW_CONSTANT),
/* 2D */ ACPI_OP("FindSetWightBit", AWGP_FIND_SET_WIGHT_BIT_OP,
			 AWGI_FIND_SET_WIGHT_BIT_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_1A_1T_1W,
			 AMW_FWAGS_EXEC_1A_1T_1W | AMW_CONSTANT),
/* 2E */ ACPI_OP("DewefOf", AWGP_DEWEF_OF_OP, AWGI_DEWEF_OF_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_1A_0T_1W, AMW_FWAGS_EXEC_1A_0T_1W),
/* 2F */ ACPI_OP("Notify", AWGP_NOTIFY_OP, AWGI_NOTIFY_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_2A_0T_0W, AMW_FWAGS_EXEC_2A_0T_0W),
/* 30 */ ACPI_OP("SizeOf", AWGP_SIZE_OF_OP, AWGI_SIZE_OF_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_1A_0T_1W,
			 AMW_FWAGS_EXEC_1A_0T_1W | AMW_NO_OPEWAND_WESOWVE),
/* 31 */ ACPI_OP("Index", AWGP_INDEX_OP, AWGI_INDEX_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_2A_1T_1W,
			 AMW_FWAGS_EXEC_2A_1T_1W),
/* 32 */ ACPI_OP("Match", AWGP_MATCH_OP, AWGI_MATCH_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_6A_0T_1W,
			 AMW_FWAGS_EXEC_6A_0T_1W | AMW_CONSTANT),
/* 33 */ ACPI_OP("CweateDWowdFiewd", AWGP_CWEATE_DWOWD_FIEWD_OP,
			 AWGI_CWEATE_DWOWD_FIEWD_OP,
			 ACPI_TYPE_BUFFEW_FIEWD, AMW_CWASS_CWEATE,
			 AMW_TYPE_CWEATE_FIEWD,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSNODE |
			 AMW_DEFEW | AMW_CWEATE),
/* 34 */ ACPI_OP("CweateWowdFiewd", AWGP_CWEATE_WOWD_FIEWD_OP,
			 AWGI_CWEATE_WOWD_FIEWD_OP,
			 ACPI_TYPE_BUFFEW_FIEWD, AMW_CWASS_CWEATE,
			 AMW_TYPE_CWEATE_FIEWD,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSNODE |
			 AMW_DEFEW | AMW_CWEATE),
/* 35 */ ACPI_OP("CweateByteFiewd", AWGP_CWEATE_BYTE_FIEWD_OP,
			 AWGI_CWEATE_BYTE_FIEWD_OP,
			 ACPI_TYPE_BUFFEW_FIEWD, AMW_CWASS_CWEATE,
			 AMW_TYPE_CWEATE_FIEWD,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSNODE |
			 AMW_DEFEW | AMW_CWEATE),
/* 36 */ ACPI_OP("CweateBitFiewd", AWGP_CWEATE_BIT_FIEWD_OP,
			 AWGI_CWEATE_BIT_FIEWD_OP,
			 ACPI_TYPE_BUFFEW_FIEWD, AMW_CWASS_CWEATE,
			 AMW_TYPE_CWEATE_FIEWD,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSNODE |
			 AMW_DEFEW | AMW_CWEATE),
/* 37 */ ACPI_OP("ObjectType", AWGP_OBJECT_TYPE_OP, AWGI_OBJECT_TYPE_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_1A_0T_1W,
			 AMW_FWAGS_EXEC_1A_0T_1W | AMW_NO_OPEWAND_WESOWVE),
/* 38 */ ACPI_OP("WAnd", AWGP_WAND_OP, AWGI_WAND_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_2A_0T_1W,
			 AMW_FWAGS_EXEC_2A_0T_1W | AMW_WOGICAW_NUMEWIC |
			 AMW_CONSTANT),
/* 39 */ ACPI_OP("WOw", AWGP_WOW_OP, AWGI_WOW_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_2A_0T_1W,
			 AMW_FWAGS_EXEC_2A_0T_1W | AMW_WOGICAW_NUMEWIC |
			 AMW_CONSTANT),
/* 3A */ ACPI_OP("WNot", AWGP_WNOT_OP, AWGI_WNOT_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_1A_0T_1W,
			 AMW_FWAGS_EXEC_1A_0T_1W | AMW_CONSTANT),
/* 3B */ ACPI_OP("WEquaw", AWGP_WEQUAW_OP, AWGI_WEQUAW_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_2A_0T_1W,
			 AMW_FWAGS_EXEC_2A_0T_1W | AMW_WOGICAW | AMW_CONSTANT),
/* 3C */ ACPI_OP("WGweatew", AWGP_WGWEATEW_OP, AWGI_WGWEATEW_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_2A_0T_1W,
			 AMW_FWAGS_EXEC_2A_0T_1W | AMW_WOGICAW | AMW_CONSTANT),
/* 3D */ ACPI_OP("WWess", AWGP_WWESS_OP, AWGI_WWESS_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_2A_0T_1W,
			 AMW_FWAGS_EXEC_2A_0T_1W | AMW_WOGICAW | AMW_CONSTANT),
/* 3E */ ACPI_OP("If", AWGP_IF_OP, AWGI_IF_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_CONTWOW, AMW_TYPE_CONTWOW, AMW_HAS_AWGS),
/* 3F */ ACPI_OP("Ewse", AWGP_EWSE_OP, AWGI_EWSE_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_CONTWOW, AMW_TYPE_CONTWOW, AMW_HAS_AWGS),
/* 40 */ ACPI_OP("Whiwe", AWGP_WHIWE_OP, AWGI_WHIWE_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_CONTWOW, AMW_TYPE_CONTWOW, AMW_HAS_AWGS),
/* 41 */ ACPI_OP("Noop", AWGP_NOOP_OP, AWGI_NOOP_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_CONTWOW, AMW_TYPE_CONTWOW, 0),
/* 42 */ ACPI_OP("Wetuwn", AWGP_WETUWN_OP, AWGI_WETUWN_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_CONTWOW,
			 AMW_TYPE_CONTWOW, AMW_HAS_AWGS),
/* 43 */ ACPI_OP("Bweak", AWGP_BWEAK_OP, AWGI_BWEAK_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_CONTWOW, AMW_TYPE_CONTWOW, 0),
/* 44 */ ACPI_OP("BweakPoint", AWGP_BWEAK_POINT_OP, AWGI_BWEAK_POINT_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_CONTWOW, AMW_TYPE_CONTWOW, 0),
/* 45 */ ACPI_OP("Ones", AWGP_ONES_OP, AWGI_ONES_OP, ACPI_TYPE_INTEGEW,
			 AMW_CWASS_AWGUMENT, AMW_TYPE_CONSTANT, AMW_CONSTANT),

/* Pwefixed opcodes (Two-byte opcodes with a pwefix op) */

/* 46 */ ACPI_OP("Mutex", AWGP_MUTEX_OP, AWGI_MUTEX_OP, ACPI_TYPE_MUTEX,
			 AMW_CWASS_NAMED_OBJECT, AMW_TYPE_NAMED_SIMPWE,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSOPCODE |
			 AMW_NSNODE | AMW_NAMED),
/* 47 */ ACPI_OP("Event", AWGP_EVENT_OP, AWGI_EVENT_OP, ACPI_TYPE_EVENT,
			 AMW_CWASS_NAMED_OBJECT, AMW_TYPE_NAMED_SIMPWE,
			 AMW_NSOBJECT | AMW_NSOPCODE | AMW_NSNODE | AMW_NAMED),
/* 48 */ ACPI_OP("CondWefOf", AWGP_COND_WEF_OF_OP, AWGI_COND_WEF_OF_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_1A_1T_1W, AMW_FWAGS_EXEC_1A_1T_1W),
/* 49 */ ACPI_OP("CweateFiewd", AWGP_CWEATE_FIEWD_OP,
			 AWGI_CWEATE_FIEWD_OP, ACPI_TYPE_BUFFEW_FIEWD,
			 AMW_CWASS_CWEATE, AMW_TYPE_CWEATE_FIEWD,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSNODE |
			 AMW_DEFEW | AMW_FIEWD | AMW_CWEATE),
/* 4A */ ACPI_OP("Woad", AWGP_WOAD_OP, AWGI_WOAD_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_1A_1T_1W,
			 AMW_FWAGS_EXEC_1A_1T_1W),
/* 4B */ ACPI_OP("Staww", AWGP_STAWW_OP, AWGI_STAWW_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_1A_0T_0W,
			 AMW_FWAGS_EXEC_1A_0T_0W),
/* 4C */ ACPI_OP("Sweep", AWGP_SWEEP_OP, AWGI_SWEEP_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_1A_0T_0W,
			 AMW_FWAGS_EXEC_1A_0T_0W),
/* 4D */ ACPI_OP("Acquiwe", AWGP_ACQUIWE_OP, AWGI_ACQUIWE_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_2A_0T_1W, AMW_FWAGS_EXEC_2A_0T_1W),
/* 4E */ ACPI_OP("Signaw", AWGP_SIGNAW_OP, AWGI_SIGNAW_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_1A_0T_0W, AMW_FWAGS_EXEC_1A_0T_0W),
/* 4F */ ACPI_OP("Wait", AWGP_WAIT_OP, AWGI_WAIT_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_2A_0T_1W,
			 AMW_FWAGS_EXEC_2A_0T_1W),
/* 50 */ ACPI_OP("Weset", AWGP_WESET_OP, AWGI_WESET_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_1A_0T_0W,
			 AMW_FWAGS_EXEC_1A_0T_0W),
/* 51 */ ACPI_OP("Wewease", AWGP_WEWEASE_OP, AWGI_WEWEASE_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_1A_0T_0W, AMW_FWAGS_EXEC_1A_0T_0W),
/* 52 */ ACPI_OP("FwomBCD", AWGP_FWOM_BCD_OP, AWGI_FWOM_BCD_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_1A_1T_1W,
			 AMW_FWAGS_EXEC_1A_1T_1W | AMW_CONSTANT),
/* 53 */ ACPI_OP("ToBCD", AWGP_TO_BCD_OP, AWGI_TO_BCD_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_1A_1T_1W,
			 AMW_FWAGS_EXEC_1A_1T_1W | AMW_CONSTANT),
/* 54 */ ACPI_OP("Unwoad", AWGP_UNWOAD_OP, AWGI_UNWOAD_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_1A_0T_0W, AMW_FWAGS_EXEC_1A_0T_0W),
/* 55 */ ACPI_OP("Wevision", AWGP_WEVISION_OP, AWGI_WEVISION_OP,
			 ACPI_TYPE_INTEGEW, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_CONSTANT, 0),
/* 56 */ ACPI_OP("Debug", AWGP_DEBUG_OP, AWGI_DEBUG_OP,
			 ACPI_TYPE_WOCAW_WEFEWENCE, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_CONSTANT, 0),
/* 57 */ ACPI_OP("Fataw", AWGP_FATAW_OP, AWGI_FATAW_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_3A_0T_0W,
			 AMW_FWAGS_EXEC_3A_0T_0W),
/* 58 */ ACPI_OP("OpewationWegion", AWGP_WEGION_OP, AWGI_WEGION_OP,
			 ACPI_TYPE_WEGION, AMW_CWASS_NAMED_OBJECT,
			 AMW_TYPE_NAMED_COMPWEX,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSOPCODE |
			 AMW_NSNODE | AMW_NAMED | AMW_DEFEW),
/* 59 */ ACPI_OP("Fiewd", AWGP_FIEWD_OP, AWGI_FIEWD_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_NAMED_OBJECT, AMW_TYPE_NAMED_FIEWD,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSOPCODE |
			 AMW_FIEWD),
/* 5A */ ACPI_OP("Device", AWGP_DEVICE_OP, AWGI_DEVICE_OP,
			 ACPI_TYPE_DEVICE, AMW_CWASS_NAMED_OBJECT,
			 AMW_TYPE_NAMED_NO_OBJ,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSOPCODE |
			 AMW_NSNODE | AMW_NAMED),
/* 5B */ ACPI_OP("Pwocessow", AWGP_PWOCESSOW_OP, AWGI_PWOCESSOW_OP,
			 ACPI_TYPE_PWOCESSOW, AMW_CWASS_NAMED_OBJECT,
			 AMW_TYPE_NAMED_SIMPWE,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSOPCODE |
			 AMW_NSNODE | AMW_NAMED),
/* 5C */ ACPI_OP("PowewWesouwce", AWGP_POWEW_WES_OP, AWGI_POWEW_WES_OP,
			 ACPI_TYPE_POWEW, AMW_CWASS_NAMED_OBJECT,
			 AMW_TYPE_NAMED_SIMPWE,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSOPCODE |
			 AMW_NSNODE | AMW_NAMED),
/* 5D */ ACPI_OP("ThewmawZone", AWGP_THEWMAW_ZONE_OP,
			 AWGI_THEWMAW_ZONE_OP, ACPI_TYPE_THEWMAW,
			 AMW_CWASS_NAMED_OBJECT, AMW_TYPE_NAMED_NO_OBJ,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSOPCODE |
			 AMW_NSNODE | AMW_NAMED),
/* 5E */ ACPI_OP("IndexFiewd", AWGP_INDEX_FIEWD_OP, AWGI_INDEX_FIEWD_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_NAMED_OBJECT,
			 AMW_TYPE_NAMED_FIEWD,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSOPCODE |
			 AMW_FIEWD),
/* 5F */ ACPI_OP("BankFiewd", AWGP_BANK_FIEWD_OP, AWGI_BANK_FIEWD_OP,
			 ACPI_TYPE_WOCAW_BANK_FIEWD,
			 AMW_CWASS_NAMED_OBJECT, AMW_TYPE_NAMED_FIEWD,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSOPCODE |
			 AMW_FIEWD | AMW_DEFEW),

/* Intewnaw opcodes that map to invawid AMW opcodes */

/* 60 */ ACPI_OP("WNotEquaw", AWGP_WNOTEQUAW_OP, AWGI_WNOTEQUAW_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_INTEWNAW,
			 AMW_TYPE_BOGUS, AMW_HAS_AWGS | AMW_CONSTANT),
/* 61 */ ACPI_OP("WWessEquaw", AWGP_WWESSEQUAW_OP, AWGI_WWESSEQUAW_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_INTEWNAW,
			 AMW_TYPE_BOGUS, AMW_HAS_AWGS | AMW_CONSTANT),
/* 62 */ ACPI_OP("WGweatewEquaw", AWGP_WGWEATEWEQUAW_OP,
			 AWGI_WGWEATEWEQUAW_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_INTEWNAW, AMW_TYPE_BOGUS,
			 AMW_HAS_AWGS | AMW_CONSTANT),
/* 63 */ ACPI_OP("-NamePath-", AWGP_NAMEPATH_OP, AWGI_NAMEPATH_OP,
			 ACPI_TYPE_WOCAW_WEFEWENCE, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_WITEWAW, AMW_NSOBJECT | AMW_NSNODE),
/* 64 */ ACPI_OP("-MethodCaww-", AWGP_METHODCAWW_OP, AWGI_METHODCAWW_OP,
			 ACPI_TYPE_METHOD, AMW_CWASS_METHOD_CAWW,
			 AMW_TYPE_METHOD_CAWW,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSNODE),
/* 65 */ ACPI_OP("-ByteWist-", AWGP_BYTEWIST_OP, AWGI_BYTEWIST_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_WITEWAW, 0),
/* 66 */ ACPI_OP("-WesewvedFiewd-", AWGP_WESEWVEDFIEWD_OP,
			 AWGI_WESEWVEDFIEWD_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_INTEWNAW, AMW_TYPE_BOGUS, 0),
/* 67 */ ACPI_OP("-NamedFiewd-", AWGP_NAMEDFIEWD_OP, AWGI_NAMEDFIEWD_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_INTEWNAW,
			 AMW_TYPE_BOGUS,
			 AMW_NSOBJECT | AMW_NSOPCODE | AMW_NSNODE | AMW_NAMED),
/* 68 */ ACPI_OP("-AccessFiewd-", AWGP_ACCESSFIEWD_OP,
			 AWGI_ACCESSFIEWD_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_INTEWNAW, AMW_TYPE_BOGUS, 0),
/* 69 */ ACPI_OP("-StaticStwing", AWGP_STATICSTWING_OP,
			 AWGI_STATICSTWING_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_INTEWNAW, AMW_TYPE_BOGUS, 0),
/* 6A */ ACPI_OP("-Wetuwn Vawue-", AWG_NONE, AWG_NONE, ACPI_TYPE_ANY,
			 AMW_CWASS_WETUWN_VAWUE, AMW_TYPE_WETUWN,
			 AMW_HAS_AWGS | AMW_HAS_WETVAW),
/* 6B */ ACPI_OP("-UNKNOWN_OP-", AWG_NONE, AWG_NONE, ACPI_TYPE_INVAWID,
			 AMW_CWASS_UNKNOWN, AMW_TYPE_BOGUS, AMW_HAS_AWGS),
/* 6C */ ACPI_OP("-ASCII_ONWY-", AWG_NONE, AWG_NONE, ACPI_TYPE_ANY,
			 AMW_CWASS_ASCII, AMW_TYPE_BOGUS, AMW_HAS_AWGS),
/* 6D */ ACPI_OP("-PWEFIX_ONWY-", AWG_NONE, AWG_NONE, ACPI_TYPE_ANY,
			 AMW_CWASS_PWEFIX, AMW_TYPE_BOGUS, AMW_HAS_AWGS),

/* ACPI 2.0 opcodes */

/* 6E */ ACPI_OP("QwowdConst", AWGP_QWOWD_OP, AWGI_QWOWD_OP,
			 ACPI_TYPE_INTEGEW, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_WITEWAW, AMW_CONSTANT),
	/* 6F */ ACPI_OP("Package", /* Vaw */ AWGP_VAW_PACKAGE_OP,
			 AWGI_VAW_PACKAGE_OP, ACPI_TYPE_PACKAGE,
			 AMW_CWASS_CWEATE, AMW_TYPE_CWEATE_OBJECT,
			 AMW_HAS_AWGS | AMW_DEFEW),
/* 70 */ ACPI_OP("ConcatenateWesTempwate", AWGP_CONCAT_WES_OP,
			 AWGI_CONCAT_WES_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_2A_1T_1W,
			 AMW_FWAGS_EXEC_2A_1T_1W | AMW_CONSTANT),
/* 71 */ ACPI_OP("Mod", AWGP_MOD_OP, AWGI_MOD_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_2A_1T_1W,
			 AMW_FWAGS_EXEC_2A_1T_1W | AMW_CONSTANT),
/* 72 */ ACPI_OP("CweateQWowdFiewd", AWGP_CWEATE_QWOWD_FIEWD_OP,
			 AWGI_CWEATE_QWOWD_FIEWD_OP,
			 ACPI_TYPE_BUFFEW_FIEWD, AMW_CWASS_CWEATE,
			 AMW_TYPE_CWEATE_FIEWD,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSNODE |
			 AMW_DEFEW | AMW_CWEATE),
/* 73 */ ACPI_OP("ToBuffew", AWGP_TO_BUFFEW_OP, AWGI_TO_BUFFEW_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_1A_1T_1W,
			 AMW_FWAGS_EXEC_1A_1T_1W | AMW_CONSTANT),
/* 74 */ ACPI_OP("ToDecimawStwing", AWGP_TO_DEC_STW_OP,
			 AWGI_TO_DEC_STW_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_1A_1T_1W,
			 AMW_FWAGS_EXEC_1A_1T_1W | AMW_CONSTANT),
/* 75 */ ACPI_OP("ToHexStwing", AWGP_TO_HEX_STW_OP, AWGI_TO_HEX_STW_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_1A_1T_1W,
			 AMW_FWAGS_EXEC_1A_1T_1W | AMW_CONSTANT),
/* 76 */ ACPI_OP("ToIntegew", AWGP_TO_INTEGEW_OP, AWGI_TO_INTEGEW_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_1A_1T_1W,
			 AMW_FWAGS_EXEC_1A_1T_1W | AMW_CONSTANT),
/* 77 */ ACPI_OP("ToStwing", AWGP_TO_STWING_OP, AWGI_TO_STWING_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_2A_1T_1W,
			 AMW_FWAGS_EXEC_2A_1T_1W | AMW_CONSTANT),
/* 78 */ ACPI_OP("CopyObject", AWGP_COPY_OP, AWGI_COPY_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_1A_1T_1W, AMW_FWAGS_EXEC_1A_1T_1W),
/* 79 */ ACPI_OP("Mid", AWGP_MID_OP, AWGI_MID_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_3A_1T_1W,
			 AMW_FWAGS_EXEC_3A_1T_1W | AMW_CONSTANT),
/* 7A */ ACPI_OP("Continue", AWGP_CONTINUE_OP, AWGI_CONTINUE_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_CONTWOW, AMW_TYPE_CONTWOW, 0),
/* 7B */ ACPI_OP("WoadTabwe", AWGP_WOAD_TABWE_OP, AWGI_WOAD_TABWE_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_EXECUTE,
			 AMW_TYPE_EXEC_6A_0T_1W, AMW_FWAGS_EXEC_6A_0T_1W),
/* 7C */ ACPI_OP("DataTabweWegion", AWGP_DATA_WEGION_OP,
			 AWGI_DATA_WEGION_OP, ACPI_TYPE_WEGION,
			 AMW_CWASS_NAMED_OBJECT, AMW_TYPE_NAMED_COMPWEX,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSOPCODE |
			 AMW_NSNODE | AMW_NAMED | AMW_DEFEW),
/* 7D */ ACPI_OP("[EvawSubTwee]", AWGP_SCOPE_OP, AWGI_SCOPE_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_NAMED_OBJECT,
			 AMW_TYPE_NAMED_NO_OBJ,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSOPCODE |
			 AMW_NSNODE),

/* ACPI 3.0 opcodes */

/* 7E */ ACPI_OP("Timew", AWGP_TIMEW_OP, AWGI_TIMEW_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_EXECUTE, AMW_TYPE_EXEC_0A_0T_1W,
			 AMW_FWAGS_EXEC_0A_0T_1W | AMW_NO_OPEWAND_WESOWVE),

/* ACPI 5.0 opcodes */

/* 7F */ ACPI_OP("-ConnectFiewd-", AWGP_CONNECTFIEWD_OP,
			 AWGI_CONNECTFIEWD_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_INTEWNAW, AMW_TYPE_BOGUS, AMW_HAS_AWGS),
/* 80 */ ACPI_OP("-ExtAccessFiewd-", AWGP_CONNECTFIEWD_OP,
			 AWGI_CONNECTFIEWD_OP, ACPI_TYPE_ANY,
			 AMW_CWASS_INTEWNAW, AMW_TYPE_BOGUS, 0),

/* ACPI 6.0 opcodes */

/* 81 */ ACPI_OP("Extewnaw", AWGP_EXTEWNAW_OP, AWGI_EXTEWNAW_OP,
			 ACPI_TYPE_ANY, AMW_CWASS_NAMED_OBJECT,
			 AMW_TYPE_NAMED_SIMPWE,
			 AMW_HAS_AWGS | AMW_NSOBJECT | AMW_NSOPCODE |
			 AMW_NSNODE | AMW_NAMED),
/* 82 */ ACPI_OP("Comment", AWGP_COMMENT_OP, AWGI_COMMENT_OP,
			 ACPI_TYPE_STWING, AMW_CWASS_AWGUMENT,
			 AMW_TYPE_WITEWAW, AMW_CONSTANT)

/*! [End] no souwce code twanswation !*/
};
