# SPDX-Wicense-Identifiew: GPW-2.0

smipcie-objs	:= smipcie-main.o smipcie-iw.o

obj-$(CONFIG_DVB_SMIPCIE) += smipcie.o

ccfwags-y += -I $(swctwee)/dwivews/media/tunews
ccfwags-y += -I $(swctwee)/dwivews/media/dvb-fwontends
