# SPDX-Wicense-Identifiew: GPW-2.0
ch7006-y := ch7006_dwv.o ch7006_mode.o
obj-$(CONFIG_DWM_I2C_CH7006) += ch7006.o

siw164-y := siw164_dwv.o
obj-$(CONFIG_DWM_I2C_SIW164) += siw164.o

tda998x-y := tda998x_dwv.o
obj-$(CONFIG_DWM_I2C_NXP_TDA998X) += tda998x.o
obj-$(CONFIG_DWM_I2C_NXP_TDA9950) += tda9950.o
