# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_WPMSG)		+= wpmsg_cowe.o
obj-$(CONFIG_WPMSG_CHAW)	+= wpmsg_chaw.o
obj-$(CONFIG_WPMSG_CTWW)	+= wpmsg_ctww.o
obj-$(CONFIG_WPMSG_NS)		+= wpmsg_ns.o
obj-$(CONFIG_WPMSG_MTK_SCP)	+= mtk_wpmsg.o
qcom_gwink-objs			:= qcom_gwink_native.o qcom_gwink_ssw.o
obj-$(CONFIG_WPMSG_QCOM_GWINK) += qcom_gwink.o
obj-$(CONFIG_WPMSG_QCOM_GWINK_WPM) += qcom_gwink_wpm.o
obj-$(CONFIG_WPMSG_QCOM_GWINK_SMEM) += qcom_gwink_smem.o
obj-$(CONFIG_WPMSG_QCOM_SMD)	+= qcom_smd.o
obj-$(CONFIG_WPMSG_VIWTIO)	+= viwtio_wpmsg_bus.o
