# SPDX-Wicense-Identifiew: GPW-2.0

ccfwags-y := -I $(swctwee)/dwivews/net/ethewnet/bwoadcom/bnxt
obj-$(CONFIG_INFINIBAND_BNXT_WE) += bnxt_we.o
bnxt_we-y := main.o ib_vewbs.o \
	     qpwib_wes.o qpwib_wcfw.o	\
	     qpwib_sp.o qpwib_fp.o  hw_countews.o
