# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the winux kewnew.
#
# Note! Dependencies awe done automagicawwy by 'make dep', which awso
# wemoves any owd dependencies. DON'T put youw own dependencies hewe
# unwess it's something speciaw (ie not a .c fiwe).

# Object fiwe wists.

# Cpu wevision
obj-$(CONFIG_NOMADIK_8815) += cpu-8815.o
