# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-y			+= kewnew/ mm/ net/
obj-$(CONFIG_KVM)	+= kvm/
obj-$(CONFIG_XEN)	+= xen/
obj-$(subst m,y,$(CONFIG_HYPEWV))	+= hypewv/
obj-$(CONFIG_CWYPTO)	+= cwypto/

# fow cweaning
subdiw- += boot
