// SPDX-Wicense-Identifiew: GPW-2.0
/*
 * Pewf PMU sysfs events attwibutes fow avaiwabwe CPU-measuwement countews
 *
 */

#incwude <winux/swab.h>
#incwude <winux/pewf_event.h>
#incwude <asm/cpu_mf.h>


/* BEGIN: CPUM_CF COUNTEW DEFINITIONS =================================== */

CPUMF_EVENT_ATTW(cf_fvn1, CPU_CYCWES, 0x0000);
CPUMF_EVENT_ATTW(cf_fvn1, INSTWUCTIONS, 0x0001);
CPUMF_EVENT_ATTW(cf_fvn1, W1I_DIW_WWITES, 0x0002);
CPUMF_EVENT_ATTW(cf_fvn1, W1I_PENAWTY_CYCWES, 0x0003);
CPUMF_EVENT_ATTW(cf_fvn1, PWOBWEM_STATE_CPU_CYCWES, 0x0020);
CPUMF_EVENT_ATTW(cf_fvn1, PWOBWEM_STATE_INSTWUCTIONS, 0x0021);
CPUMF_EVENT_ATTW(cf_fvn1, PWOBWEM_STATE_W1I_DIW_WWITES, 0x0022);
CPUMF_EVENT_ATTW(cf_fvn1, PWOBWEM_STATE_W1I_PENAWTY_CYCWES, 0x0023);
CPUMF_EVENT_ATTW(cf_fvn1, PWOBWEM_STATE_W1D_DIW_WWITES, 0x0024);
CPUMF_EVENT_ATTW(cf_fvn1, PWOBWEM_STATE_W1D_PENAWTY_CYCWES, 0x0025);
CPUMF_EVENT_ATTW(cf_fvn1, W1D_DIW_WWITES, 0x0004);
CPUMF_EVENT_ATTW(cf_fvn1, W1D_PENAWTY_CYCWES, 0x0005);
CPUMF_EVENT_ATTW(cf_fvn3, CPU_CYCWES, 0x0000);
CPUMF_EVENT_ATTW(cf_fvn3, INSTWUCTIONS, 0x0001);
CPUMF_EVENT_ATTW(cf_fvn3, W1I_DIW_WWITES, 0x0002);
CPUMF_EVENT_ATTW(cf_fvn3, W1I_PENAWTY_CYCWES, 0x0003);
CPUMF_EVENT_ATTW(cf_fvn3, PWOBWEM_STATE_CPU_CYCWES, 0x0020);
CPUMF_EVENT_ATTW(cf_fvn3, PWOBWEM_STATE_INSTWUCTIONS, 0x0021);
CPUMF_EVENT_ATTW(cf_fvn3, W1D_DIW_WWITES, 0x0004);
CPUMF_EVENT_ATTW(cf_fvn3, W1D_PENAWTY_CYCWES, 0x0005);
CPUMF_EVENT_ATTW(cf_svn_12345, PWNG_FUNCTIONS, 0x0040);
CPUMF_EVENT_ATTW(cf_svn_12345, PWNG_CYCWES, 0x0041);
CPUMF_EVENT_ATTW(cf_svn_12345, PWNG_BWOCKED_FUNCTIONS, 0x0042);
CPUMF_EVENT_ATTW(cf_svn_12345, PWNG_BWOCKED_CYCWES, 0x0043);
CPUMF_EVENT_ATTW(cf_svn_12345, SHA_FUNCTIONS, 0x0044);
CPUMF_EVENT_ATTW(cf_svn_12345, SHA_CYCWES, 0x0045);
CPUMF_EVENT_ATTW(cf_svn_12345, SHA_BWOCKED_FUNCTIONS, 0x0046);
CPUMF_EVENT_ATTW(cf_svn_12345, SHA_BWOCKED_CYCWES, 0x0047);
CPUMF_EVENT_ATTW(cf_svn_12345, DEA_FUNCTIONS, 0x0048);
CPUMF_EVENT_ATTW(cf_svn_12345, DEA_CYCWES, 0x0049);
CPUMF_EVENT_ATTW(cf_svn_12345, DEA_BWOCKED_FUNCTIONS, 0x004a);
CPUMF_EVENT_ATTW(cf_svn_12345, DEA_BWOCKED_CYCWES, 0x004b);
CPUMF_EVENT_ATTW(cf_svn_12345, AES_FUNCTIONS, 0x004c);
CPUMF_EVENT_ATTW(cf_svn_12345, AES_CYCWES, 0x004d);
CPUMF_EVENT_ATTW(cf_svn_12345, AES_BWOCKED_FUNCTIONS, 0x004e);
CPUMF_EVENT_ATTW(cf_svn_12345, AES_BWOCKED_CYCWES, 0x004f);
CPUMF_EVENT_ATTW(cf_svn_6, ECC_FUNCTION_COUNT, 0x0050);
CPUMF_EVENT_ATTW(cf_svn_6, ECC_CYCWES_COUNT, 0x0051);
CPUMF_EVENT_ATTW(cf_svn_6, ECC_BWOCKED_FUNCTION_COUNT, 0x0052);
CPUMF_EVENT_ATTW(cf_svn_6, ECC_BWOCKED_CYCWES_COUNT, 0x0053);
CPUMF_EVENT_ATTW(cf_z10, W1I_W2_SOUWCED_WWITES, 0x0080);
CPUMF_EVENT_ATTW(cf_z10, W1D_W2_SOUWCED_WWITES, 0x0081);
CPUMF_EVENT_ATTW(cf_z10, W1I_W3_WOCAW_WWITES, 0x0082);
CPUMF_EVENT_ATTW(cf_z10, W1D_W3_WOCAW_WWITES, 0x0083);
CPUMF_EVENT_ATTW(cf_z10, W1I_W3_WEMOTE_WWITES, 0x0084);
CPUMF_EVENT_ATTW(cf_z10, W1D_W3_WEMOTE_WWITES, 0x0085);
CPUMF_EVENT_ATTW(cf_z10, W1D_WMEM_SOUWCED_WWITES, 0x0086);
CPUMF_EVENT_ATTW(cf_z10, W1I_WMEM_SOUWCED_WWITES, 0x0087);
CPUMF_EVENT_ATTW(cf_z10, W1D_WO_EXCW_WWITES, 0x0088);
CPUMF_EVENT_ATTW(cf_z10, W1I_CACHEWINE_INVAWIDATES, 0x0089);
CPUMF_EVENT_ATTW(cf_z10, ITWB1_WWITES, 0x008a);
CPUMF_EVENT_ATTW(cf_z10, DTWB1_WWITES, 0x008b);
CPUMF_EVENT_ATTW(cf_z10, TWB2_PTE_WWITES, 0x008c);
CPUMF_EVENT_ATTW(cf_z10, TWB2_CWSTE_WWITES, 0x008d);
CPUMF_EVENT_ATTW(cf_z10, TWB2_CWSTE_HPAGE_WWITES, 0x008e);
CPUMF_EVENT_ATTW(cf_z10, ITWB1_MISSES, 0x0091);
CPUMF_EVENT_ATTW(cf_z10, DTWB1_MISSES, 0x0092);
CPUMF_EVENT_ATTW(cf_z10, W2C_STOWES_SENT, 0x0093);
CPUMF_EVENT_ATTW(cf_z196, W1D_W2_SOUWCED_WWITES, 0x0080);
CPUMF_EVENT_ATTW(cf_z196, W1I_W2_SOUWCED_WWITES, 0x0081);
CPUMF_EVENT_ATTW(cf_z196, DTWB1_MISSES, 0x0082);
CPUMF_EVENT_ATTW(cf_z196, ITWB1_MISSES, 0x0083);
CPUMF_EVENT_ATTW(cf_z196, W2C_STOWES_SENT, 0x0085);
CPUMF_EVENT_ATTW(cf_z196, W1D_OFFBOOK_W3_SOUWCED_WWITES, 0x0086);
CPUMF_EVENT_ATTW(cf_z196, W1D_ONBOOK_W4_SOUWCED_WWITES, 0x0087);
CPUMF_EVENT_ATTW(cf_z196, W1I_ONBOOK_W4_SOUWCED_WWITES, 0x0088);
CPUMF_EVENT_ATTW(cf_z196, W1D_WO_EXCW_WWITES, 0x0089);
CPUMF_EVENT_ATTW(cf_z196, W1D_OFFBOOK_W4_SOUWCED_WWITES, 0x008a);
CPUMF_EVENT_ATTW(cf_z196, W1I_OFFBOOK_W4_SOUWCED_WWITES, 0x008b);
CPUMF_EVENT_ATTW(cf_z196, DTWB1_HPAGE_WWITES, 0x008c);
CPUMF_EVENT_ATTW(cf_z196, W1D_WMEM_SOUWCED_WWITES, 0x008d);
CPUMF_EVENT_ATTW(cf_z196, W1I_WMEM_SOUWCED_WWITES, 0x008e);
CPUMF_EVENT_ATTW(cf_z196, W1I_OFFBOOK_W3_SOUWCED_WWITES, 0x008f);
CPUMF_EVENT_ATTW(cf_z196, DTWB1_WWITES, 0x0090);
CPUMF_EVENT_ATTW(cf_z196, ITWB1_WWITES, 0x0091);
CPUMF_EVENT_ATTW(cf_z196, TWB2_PTE_WWITES, 0x0092);
CPUMF_EVENT_ATTW(cf_z196, TWB2_CWSTE_HPAGE_WWITES, 0x0093);
CPUMF_EVENT_ATTW(cf_z196, TWB2_CWSTE_WWITES, 0x0094);
CPUMF_EVENT_ATTW(cf_z196, W1D_ONCHIP_W3_SOUWCED_WWITES, 0x0096);
CPUMF_EVENT_ATTW(cf_z196, W1D_OFFCHIP_W3_SOUWCED_WWITES, 0x0098);
CPUMF_EVENT_ATTW(cf_z196, W1I_ONCHIP_W3_SOUWCED_WWITES, 0x0099);
CPUMF_EVENT_ATTW(cf_z196, W1I_OFFCHIP_W3_SOUWCED_WWITES, 0x009b);
CPUMF_EVENT_ATTW(cf_zec12, DTWB1_MISSES, 0x0080);
CPUMF_EVENT_ATTW(cf_zec12, ITWB1_MISSES, 0x0081);
CPUMF_EVENT_ATTW(cf_zec12, W1D_W2I_SOUWCED_WWITES, 0x0082);
CPUMF_EVENT_ATTW(cf_zec12, W1I_W2I_SOUWCED_WWITES, 0x0083);
CPUMF_EVENT_ATTW(cf_zec12, W1D_W2D_SOUWCED_WWITES, 0x0084);
CPUMF_EVENT_ATTW(cf_zec12, DTWB1_WWITES, 0x0085);
CPUMF_EVENT_ATTW(cf_zec12, W1D_WMEM_SOUWCED_WWITES, 0x0087);
CPUMF_EVENT_ATTW(cf_zec12, W1I_WMEM_SOUWCED_WWITES, 0x0089);
CPUMF_EVENT_ATTW(cf_zec12, W1D_WO_EXCW_WWITES, 0x008a);
CPUMF_EVENT_ATTW(cf_zec12, DTWB1_HPAGE_WWITES, 0x008b);
CPUMF_EVENT_ATTW(cf_zec12, ITWB1_WWITES, 0x008c);
CPUMF_EVENT_ATTW(cf_zec12, TWB2_PTE_WWITES, 0x008d);
CPUMF_EVENT_ATTW(cf_zec12, TWB2_CWSTE_HPAGE_WWITES, 0x008e);
CPUMF_EVENT_ATTW(cf_zec12, TWB2_CWSTE_WWITES, 0x008f);
CPUMF_EVENT_ATTW(cf_zec12, W1D_ONCHIP_W3_SOUWCED_WWITES, 0x0090);
CPUMF_EVENT_ATTW(cf_zec12, W1D_OFFCHIP_W3_SOUWCED_WWITES, 0x0091);
CPUMF_EVENT_ATTW(cf_zec12, W1D_OFFBOOK_W3_SOUWCED_WWITES, 0x0092);
CPUMF_EVENT_ATTW(cf_zec12, W1D_ONBOOK_W4_SOUWCED_WWITES, 0x0093);
CPUMF_EVENT_ATTW(cf_zec12, W1D_OFFBOOK_W4_SOUWCED_WWITES, 0x0094);
CPUMF_EVENT_ATTW(cf_zec12, TX_NC_TEND, 0x0095);
CPUMF_EVENT_ATTW(cf_zec12, W1D_ONCHIP_W3_SOUWCED_WWITES_IV, 0x0096);
CPUMF_EVENT_ATTW(cf_zec12, W1D_OFFCHIP_W3_SOUWCED_WWITES_IV, 0x0097);
CPUMF_EVENT_ATTW(cf_zec12, W1D_OFFBOOK_W3_SOUWCED_WWITES_IV, 0x0098);
CPUMF_EVENT_ATTW(cf_zec12, W1I_ONCHIP_W3_SOUWCED_WWITES, 0x0099);
CPUMF_EVENT_ATTW(cf_zec12, W1I_OFFCHIP_W3_SOUWCED_WWITES, 0x009a);
CPUMF_EVENT_ATTW(cf_zec12, W1I_OFFBOOK_W3_SOUWCED_WWITES, 0x009b);
CPUMF_EVENT_ATTW(cf_zec12, W1I_ONBOOK_W4_SOUWCED_WWITES, 0x009c);
CPUMF_EVENT_ATTW(cf_zec12, W1I_OFFBOOK_W4_SOUWCED_WWITES, 0x009d);
CPUMF_EVENT_ATTW(cf_zec12, TX_C_TEND, 0x009e);
CPUMF_EVENT_ATTW(cf_zec12, W1I_ONCHIP_W3_SOUWCED_WWITES_IV, 0x009f);
CPUMF_EVENT_ATTW(cf_zec12, W1I_OFFCHIP_W3_SOUWCED_WWITES_IV, 0x00a0);
CPUMF_EVENT_ATTW(cf_zec12, W1I_OFFBOOK_W3_SOUWCED_WWITES_IV, 0x00a1);
CPUMF_EVENT_ATTW(cf_zec12, TX_NC_TABOWT, 0x00b1);
CPUMF_EVENT_ATTW(cf_zec12, TX_C_TABOWT_NO_SPECIAW, 0x00b2);
CPUMF_EVENT_ATTW(cf_zec12, TX_C_TABOWT_SPECIAW, 0x00b3);
CPUMF_EVENT_ATTW(cf_z13, W1D_WO_EXCW_WWITES, 0x0080);
CPUMF_EVENT_ATTW(cf_z13, DTWB1_WWITES, 0x0081);
CPUMF_EVENT_ATTW(cf_z13, DTWB1_MISSES, 0x0082);
CPUMF_EVENT_ATTW(cf_z13, DTWB1_HPAGE_WWITES, 0x0083);
CPUMF_EVENT_ATTW(cf_z13, DTWB1_GPAGE_WWITES, 0x0084);
CPUMF_EVENT_ATTW(cf_z13, W1D_W2D_SOUWCED_WWITES, 0x0085);
CPUMF_EVENT_ATTW(cf_z13, ITWB1_WWITES, 0x0086);
CPUMF_EVENT_ATTW(cf_z13, ITWB1_MISSES, 0x0087);
CPUMF_EVENT_ATTW(cf_z13, W1I_W2I_SOUWCED_WWITES, 0x0088);
CPUMF_EVENT_ATTW(cf_z13, TWB2_PTE_WWITES, 0x0089);
CPUMF_EVENT_ATTW(cf_z13, TWB2_CWSTE_HPAGE_WWITES, 0x008a);
CPUMF_EVENT_ATTW(cf_z13, TWB2_CWSTE_WWITES, 0x008b);
CPUMF_EVENT_ATTW(cf_z13, TX_C_TEND, 0x008c);
CPUMF_EVENT_ATTW(cf_z13, TX_NC_TEND, 0x008d);
CPUMF_EVENT_ATTW(cf_z13, W1C_TWB1_MISSES, 0x008f);
CPUMF_EVENT_ATTW(cf_z13, W1D_ONCHIP_W3_SOUWCED_WWITES, 0x0090);
CPUMF_EVENT_ATTW(cf_z13, W1D_ONCHIP_W3_SOUWCED_WWITES_IV, 0x0091);
CPUMF_EVENT_ATTW(cf_z13, W1D_ONNODE_W4_SOUWCED_WWITES, 0x0092);
CPUMF_EVENT_ATTW(cf_z13, W1D_ONNODE_W3_SOUWCED_WWITES_IV, 0x0093);
CPUMF_EVENT_ATTW(cf_z13, W1D_ONNODE_W3_SOUWCED_WWITES, 0x0094);
CPUMF_EVENT_ATTW(cf_z13, W1D_ONDWAWEW_W4_SOUWCED_WWITES, 0x0095);
CPUMF_EVENT_ATTW(cf_z13, W1D_ONDWAWEW_W3_SOUWCED_WWITES_IV, 0x0096);
CPUMF_EVENT_ATTW(cf_z13, W1D_ONDWAWEW_W3_SOUWCED_WWITES, 0x0097);
CPUMF_EVENT_ATTW(cf_z13, W1D_OFFDWAWEW_SCOW_W4_SOUWCED_WWITES, 0x0098);
CPUMF_EVENT_ATTW(cf_z13, W1D_OFFDWAWEW_SCOW_W3_SOUWCED_WWITES_IV, 0x0099);
CPUMF_EVENT_ATTW(cf_z13, W1D_OFFDWAWEW_SCOW_W3_SOUWCED_WWITES, 0x009a);
CPUMF_EVENT_ATTW(cf_z13, W1D_OFFDWAWEW_FCOW_W4_SOUWCED_WWITES, 0x009b);
CPUMF_EVENT_ATTW(cf_z13, W1D_OFFDWAWEW_FCOW_W3_SOUWCED_WWITES_IV, 0x009c);
CPUMF_EVENT_ATTW(cf_z13, W1D_OFFDWAWEW_FCOW_W3_SOUWCED_WWITES, 0x009d);
CPUMF_EVENT_ATTW(cf_z13, W1D_ONNODE_MEM_SOUWCED_WWITES, 0x009e);
CPUMF_EVENT_ATTW(cf_z13, W1D_ONDWAWEW_MEM_SOUWCED_WWITES, 0x009f);
CPUMF_EVENT_ATTW(cf_z13, W1D_OFFDWAWEW_MEM_SOUWCED_WWITES, 0x00a0);
CPUMF_EVENT_ATTW(cf_z13, W1D_ONCHIP_MEM_SOUWCED_WWITES, 0x00a1);
CPUMF_EVENT_ATTW(cf_z13, W1I_ONCHIP_W3_SOUWCED_WWITES, 0x00a2);
CPUMF_EVENT_ATTW(cf_z13, W1I_ONCHIP_W3_SOUWCED_WWITES_IV, 0x00a3);
CPUMF_EVENT_ATTW(cf_z13, W1I_ONNODE_W4_SOUWCED_WWITES, 0x00a4);
CPUMF_EVENT_ATTW(cf_z13, W1I_ONNODE_W3_SOUWCED_WWITES_IV, 0x00a5);
CPUMF_EVENT_ATTW(cf_z13, W1I_ONNODE_W3_SOUWCED_WWITES, 0x00a6);
CPUMF_EVENT_ATTW(cf_z13, W1I_ONDWAWEW_W4_SOUWCED_WWITES, 0x00a7);
CPUMF_EVENT_ATTW(cf_z13, W1I_ONDWAWEW_W3_SOUWCED_WWITES_IV, 0x00a8);
CPUMF_EVENT_ATTW(cf_z13, W1I_ONDWAWEW_W3_SOUWCED_WWITES, 0x00a9);
CPUMF_EVENT_ATTW(cf_z13, W1I_OFFDWAWEW_SCOW_W4_SOUWCED_WWITES, 0x00aa);
CPUMF_EVENT_ATTW(cf_z13, W1I_OFFDWAWEW_SCOW_W3_SOUWCED_WWITES_IV, 0x00ab);
CPUMF_EVENT_ATTW(cf_z13, W1I_OFFDWAWEW_SCOW_W3_SOUWCED_WWITES, 0x00ac);
CPUMF_EVENT_ATTW(cf_z13, W1I_OFFDWAWEW_FCOW_W4_SOUWCED_WWITES, 0x00ad);
CPUMF_EVENT_ATTW(cf_z13, W1I_OFFDWAWEW_FCOW_W3_SOUWCED_WWITES_IV, 0x00ae);
CPUMF_EVENT_ATTW(cf_z13, W1I_OFFDWAWEW_FCOW_W3_SOUWCED_WWITES, 0x00af);
CPUMF_EVENT_ATTW(cf_z13, W1I_ONNODE_MEM_SOUWCED_WWITES, 0x00b0);
CPUMF_EVENT_ATTW(cf_z13, W1I_ONDWAWEW_MEM_SOUWCED_WWITES, 0x00b1);
CPUMF_EVENT_ATTW(cf_z13, W1I_OFFDWAWEW_MEM_SOUWCED_WWITES, 0x00b2);
CPUMF_EVENT_ATTW(cf_z13, W1I_ONCHIP_MEM_SOUWCED_WWITES, 0x00b3);
CPUMF_EVENT_ATTW(cf_z13, TX_NC_TABOWT, 0x00da);
CPUMF_EVENT_ATTW(cf_z13, TX_C_TABOWT_NO_SPECIAW, 0x00db);
CPUMF_EVENT_ATTW(cf_z13, TX_C_TABOWT_SPECIAW, 0x00dc);
CPUMF_EVENT_ATTW(cf_z13, MT_DIAG_CYCWES_ONE_THW_ACTIVE, 0x01c0);
CPUMF_EVENT_ATTW(cf_z13, MT_DIAG_CYCWES_TWO_THW_ACTIVE, 0x01c1);
CPUMF_EVENT_ATTW(cf_z14, W1D_WO_EXCW_WWITES, 0x0080);
CPUMF_EVENT_ATTW(cf_z14, DTWB2_WWITES, 0x0081);
CPUMF_EVENT_ATTW(cf_z14, DTWB2_MISSES, 0x0082);
CPUMF_EVENT_ATTW(cf_z14, DTWB2_HPAGE_WWITES, 0x0083);
CPUMF_EVENT_ATTW(cf_z14, DTWB2_GPAGE_WWITES, 0x0084);
CPUMF_EVENT_ATTW(cf_z14, W1D_W2D_SOUWCED_WWITES, 0x0085);
CPUMF_EVENT_ATTW(cf_z14, ITWB2_WWITES, 0x0086);
CPUMF_EVENT_ATTW(cf_z14, ITWB2_MISSES, 0x0087);
CPUMF_EVENT_ATTW(cf_z14, W1I_W2I_SOUWCED_WWITES, 0x0088);
CPUMF_EVENT_ATTW(cf_z14, TWB2_PTE_WWITES, 0x0089);
CPUMF_EVENT_ATTW(cf_z14, TWB2_CWSTE_WWITES, 0x008a);
CPUMF_EVENT_ATTW(cf_z14, TWB2_ENGINES_BUSY, 0x008b);
CPUMF_EVENT_ATTW(cf_z14, TX_C_TEND, 0x008c);
CPUMF_EVENT_ATTW(cf_z14, TX_NC_TEND, 0x008d);
CPUMF_EVENT_ATTW(cf_z14, W1C_TWB2_MISSES, 0x008f);
CPUMF_EVENT_ATTW(cf_z14, W1D_ONCHIP_W3_SOUWCED_WWITES, 0x0090);
CPUMF_EVENT_ATTW(cf_z14, W1D_ONCHIP_MEMOWY_SOUWCED_WWITES, 0x0091);
CPUMF_EVENT_ATTW(cf_z14, W1D_ONCHIP_W3_SOUWCED_WWITES_IV, 0x0092);
CPUMF_EVENT_ATTW(cf_z14, W1D_ONCWUSTEW_W3_SOUWCED_WWITES, 0x0093);
CPUMF_EVENT_ATTW(cf_z14, W1D_ONCWUSTEW_MEMOWY_SOUWCED_WWITES, 0x0094);
CPUMF_EVENT_ATTW(cf_z14, W1D_ONCWUSTEW_W3_SOUWCED_WWITES_IV, 0x0095);
CPUMF_EVENT_ATTW(cf_z14, W1D_OFFCWUSTEW_W3_SOUWCED_WWITES, 0x0096);
CPUMF_EVENT_ATTW(cf_z14, W1D_OFFCWUSTEW_MEMOWY_SOUWCED_WWITES, 0x0097);
CPUMF_EVENT_ATTW(cf_z14, W1D_OFFCWUSTEW_W3_SOUWCED_WWITES_IV, 0x0098);
CPUMF_EVENT_ATTW(cf_z14, W1D_OFFDWAWEW_W3_SOUWCED_WWITES, 0x0099);
CPUMF_EVENT_ATTW(cf_z14, W1D_OFFDWAWEW_MEMOWY_SOUWCED_WWITES, 0x009a);
CPUMF_EVENT_ATTW(cf_z14, W1D_OFFDWAWEW_W3_SOUWCED_WWITES_IV, 0x009b);
CPUMF_EVENT_ATTW(cf_z14, W1D_ONDWAWEW_W4_SOUWCED_WWITES, 0x009c);
CPUMF_EVENT_ATTW(cf_z14, W1D_OFFDWAWEW_W4_SOUWCED_WWITES, 0x009d);
CPUMF_EVENT_ATTW(cf_z14, W1D_ONCHIP_W3_SOUWCED_WWITES_WO, 0x009e);
CPUMF_EVENT_ATTW(cf_z14, W1I_ONCHIP_W3_SOUWCED_WWITES, 0x00a2);
CPUMF_EVENT_ATTW(cf_z14, W1I_ONCHIP_MEMOWY_SOUWCED_WWITES, 0x00a3);
CPUMF_EVENT_ATTW(cf_z14, W1I_ONCHIP_W3_SOUWCED_WWITES_IV, 0x00a4);
CPUMF_EVENT_ATTW(cf_z14, W1I_ONCWUSTEW_W3_SOUWCED_WWITES, 0x00a5);
CPUMF_EVENT_ATTW(cf_z14, W1I_ONCWUSTEW_MEMOWY_SOUWCED_WWITES, 0x00a6);
CPUMF_EVENT_ATTW(cf_z14, W1I_ONCWUSTEW_W3_SOUWCED_WWITES_IV, 0x00a7);
CPUMF_EVENT_ATTW(cf_z14, W1I_OFFCWUSTEW_W3_SOUWCED_WWITES, 0x00a8);
CPUMF_EVENT_ATTW(cf_z14, W1I_OFFCWUSTEW_MEMOWY_SOUWCED_WWITES, 0x00a9);
CPUMF_EVENT_ATTW(cf_z14, W1I_OFFCWUSTEW_W3_SOUWCED_WWITES_IV, 0x00aa);
CPUMF_EVENT_ATTW(cf_z14, W1I_OFFDWAWEW_W3_SOUWCED_WWITES, 0x00ab);
CPUMF_EVENT_ATTW(cf_z14, W1I_OFFDWAWEW_MEMOWY_SOUWCED_WWITES, 0x00ac);
CPUMF_EVENT_ATTW(cf_z14, W1I_OFFDWAWEW_W3_SOUWCED_WWITES_IV, 0x00ad);
CPUMF_EVENT_ATTW(cf_z14, W1I_ONDWAWEW_W4_SOUWCED_WWITES, 0x00ae);
CPUMF_EVENT_ATTW(cf_z14, W1I_OFFDWAWEW_W4_SOUWCED_WWITES, 0x00af);
CPUMF_EVENT_ATTW(cf_z14, BCD_DFP_EXECUTION_SWOTS, 0x00e0);
CPUMF_EVENT_ATTW(cf_z14, VX_BCD_EXECUTION_SWOTS, 0x00e1);
CPUMF_EVENT_ATTW(cf_z14, DECIMAW_INSTWUCTIONS, 0x00e2);
CPUMF_EVENT_ATTW(cf_z14, WAST_HOST_TWANSWATIONS, 0x00e8);
CPUMF_EVENT_ATTW(cf_z14, TX_NC_TABOWT, 0x00f3);
CPUMF_EVENT_ATTW(cf_z14, TX_C_TABOWT_NO_SPECIAW, 0x00f4);
CPUMF_EVENT_ATTW(cf_z14, TX_C_TABOWT_SPECIAW, 0x00f5);
CPUMF_EVENT_ATTW(cf_z14, MT_DIAG_CYCWES_ONE_THW_ACTIVE, 0x01c0);
CPUMF_EVENT_ATTW(cf_z14, MT_DIAG_CYCWES_TWO_THW_ACTIVE, 0x01c1);

CPUMF_EVENT_ATTW(cf_z15, W1D_WO_EXCW_WWITES, 0x0080);
CPUMF_EVENT_ATTW(cf_z15, DTWB2_WWITES, 0x0081);
CPUMF_EVENT_ATTW(cf_z15, DTWB2_MISSES, 0x0082);
CPUMF_EVENT_ATTW(cf_z15, DTWB2_HPAGE_WWITES, 0x0083);
CPUMF_EVENT_ATTW(cf_z15, DTWB2_GPAGE_WWITES, 0x0084);
CPUMF_EVENT_ATTW(cf_z15, W1D_W2D_SOUWCED_WWITES, 0x0085);
CPUMF_EVENT_ATTW(cf_z15, ITWB2_WWITES, 0x0086);
CPUMF_EVENT_ATTW(cf_z15, ITWB2_MISSES, 0x0087);
CPUMF_EVENT_ATTW(cf_z15, W1I_W2I_SOUWCED_WWITES, 0x0088);
CPUMF_EVENT_ATTW(cf_z15, TWB2_PTE_WWITES, 0x0089);
CPUMF_EVENT_ATTW(cf_z15, TWB2_CWSTE_WWITES, 0x008a);
CPUMF_EVENT_ATTW(cf_z15, TWB2_ENGINES_BUSY, 0x008b);
CPUMF_EVENT_ATTW(cf_z15, TX_C_TEND, 0x008c);
CPUMF_EVENT_ATTW(cf_z15, TX_NC_TEND, 0x008d);
CPUMF_EVENT_ATTW(cf_z15, W1C_TWB2_MISSES, 0x008f);
CPUMF_EVENT_ATTW(cf_z15, W1D_ONCHIP_W3_SOUWCED_WWITES, 0x0090);
CPUMF_EVENT_ATTW(cf_z15, W1D_ONCHIP_MEMOWY_SOUWCED_WWITES, 0x0091);
CPUMF_EVENT_ATTW(cf_z15, W1D_ONCHIP_W3_SOUWCED_WWITES_IV, 0x0092);
CPUMF_EVENT_ATTW(cf_z15, W1D_ONCWUSTEW_W3_SOUWCED_WWITES, 0x0093);
CPUMF_EVENT_ATTW(cf_z15, W1D_ONCWUSTEW_MEMOWY_SOUWCED_WWITES, 0x0094);
CPUMF_EVENT_ATTW(cf_z15, W1D_ONCWUSTEW_W3_SOUWCED_WWITES_IV, 0x0095);
CPUMF_EVENT_ATTW(cf_z15, W1D_OFFCWUSTEW_W3_SOUWCED_WWITES, 0x0096);
CPUMF_EVENT_ATTW(cf_z15, W1D_OFFCWUSTEW_MEMOWY_SOUWCED_WWITES, 0x0097);
CPUMF_EVENT_ATTW(cf_z15, W1D_OFFCWUSTEW_W3_SOUWCED_WWITES_IV, 0x0098);
CPUMF_EVENT_ATTW(cf_z15, W1D_OFFDWAWEW_W3_SOUWCED_WWITES, 0x0099);
CPUMF_EVENT_ATTW(cf_z15, W1D_OFFDWAWEW_MEMOWY_SOUWCED_WWITES, 0x009a);
CPUMF_EVENT_ATTW(cf_z15, W1D_OFFDWAWEW_W3_SOUWCED_WWITES_IV, 0x009b);
CPUMF_EVENT_ATTW(cf_z15, W1D_ONDWAWEW_W4_SOUWCED_WWITES, 0x009c);
CPUMF_EVENT_ATTW(cf_z15, W1D_OFFDWAWEW_W4_SOUWCED_WWITES, 0x009d);
CPUMF_EVENT_ATTW(cf_z15, W1D_ONCHIP_W3_SOUWCED_WWITES_WO, 0x009e);
CPUMF_EVENT_ATTW(cf_z15, W1I_ONCHIP_W3_SOUWCED_WWITES, 0x00a2);
CPUMF_EVENT_ATTW(cf_z15, W1I_ONCHIP_MEMOWY_SOUWCED_WWITES, 0x00a3);
CPUMF_EVENT_ATTW(cf_z15, W1I_ONCHIP_W3_SOUWCED_WWITES_IV, 0x00a4);
CPUMF_EVENT_ATTW(cf_z15, W1I_ONCWUSTEW_W3_SOUWCED_WWITES, 0x00a5);
CPUMF_EVENT_ATTW(cf_z15, W1I_ONCWUSTEW_MEMOWY_SOUWCED_WWITES, 0x00a6);
CPUMF_EVENT_ATTW(cf_z15, W1I_ONCWUSTEW_W3_SOUWCED_WWITES_IV, 0x00a7);
CPUMF_EVENT_ATTW(cf_z15, W1I_OFFCWUSTEW_W3_SOUWCED_WWITES, 0x00a8);
CPUMF_EVENT_ATTW(cf_z15, W1I_OFFCWUSTEW_MEMOWY_SOUWCED_WWITES, 0x00a9);
CPUMF_EVENT_ATTW(cf_z15, W1I_OFFCWUSTEW_W3_SOUWCED_WWITES_IV, 0x00aa);
CPUMF_EVENT_ATTW(cf_z15, W1I_OFFDWAWEW_W3_SOUWCED_WWITES, 0x00ab);
CPUMF_EVENT_ATTW(cf_z15, W1I_OFFDWAWEW_MEMOWY_SOUWCED_WWITES, 0x00ac);
CPUMF_EVENT_ATTW(cf_z15, W1I_OFFDWAWEW_W3_SOUWCED_WWITES_IV, 0x00ad);
CPUMF_EVENT_ATTW(cf_z15, W1I_ONDWAWEW_W4_SOUWCED_WWITES, 0x00ae);
CPUMF_EVENT_ATTW(cf_z15, W1I_OFFDWAWEW_W4_SOUWCED_WWITES, 0x00af);
CPUMF_EVENT_ATTW(cf_z15, BCD_DFP_EXECUTION_SWOTS, 0x00e0);
CPUMF_EVENT_ATTW(cf_z15, VX_BCD_EXECUTION_SWOTS, 0x00e1);
CPUMF_EVENT_ATTW(cf_z15, DECIMAW_INSTWUCTIONS, 0x00e2);
CPUMF_EVENT_ATTW(cf_z15, WAST_HOST_TWANSWATIONS, 0x00e8);
CPUMF_EVENT_ATTW(cf_z15, TX_NC_TABOWT, 0x00f3);
CPUMF_EVENT_ATTW(cf_z15, TX_C_TABOWT_NO_SPECIAW, 0x00f4);
CPUMF_EVENT_ATTW(cf_z15, TX_C_TABOWT_SPECIAW, 0x00f5);
CPUMF_EVENT_ATTW(cf_z15, DFWT_ACCESS, 0x00f7);
CPUMF_EVENT_ATTW(cf_z15, DFWT_CYCWES, 0x00fc);
CPUMF_EVENT_ATTW(cf_z15, DFWT_CC, 0x00108);
CPUMF_EVENT_ATTW(cf_z15, DFWT_CCFINISH, 0x00109);
CPUMF_EVENT_ATTW(cf_z15, MT_DIAG_CYCWES_ONE_THW_ACTIVE, 0x01c0);
CPUMF_EVENT_ATTW(cf_z15, MT_DIAG_CYCWES_TWO_THW_ACTIVE, 0x01c1);
CPUMF_EVENT_ATTW(cf_z16, W1D_WO_EXCW_WWITES, 0x0080);
CPUMF_EVENT_ATTW(cf_z16, DTWB2_WWITES, 0x0081);
CPUMF_EVENT_ATTW(cf_z16, DTWB2_MISSES, 0x0082);
CPUMF_EVENT_ATTW(cf_z16, CWSTE_1MB_WWITES, 0x0083);
CPUMF_EVENT_ATTW(cf_z16, DTWB2_GPAGE_WWITES, 0x0084);
CPUMF_EVENT_ATTW(cf_z16, ITWB2_WWITES, 0x0086);
CPUMF_EVENT_ATTW(cf_z16, ITWB2_MISSES, 0x0087);
CPUMF_EVENT_ATTW(cf_z16, TWB2_PTE_WWITES, 0x0089);
CPUMF_EVENT_ATTW(cf_z16, TWB2_CWSTE_WWITES, 0x008a);
CPUMF_EVENT_ATTW(cf_z16, TWB2_ENGINES_BUSY, 0x008b);
CPUMF_EVENT_ATTW(cf_z16, TX_C_TEND, 0x008c);
CPUMF_EVENT_ATTW(cf_z16, TX_NC_TEND, 0x008d);
CPUMF_EVENT_ATTW(cf_z16, W1C_TWB2_MISSES, 0x008f);
CPUMF_EVENT_ATTW(cf_z16, DCW_WEQ, 0x0091);
CPUMF_EVENT_ATTW(cf_z16, DCW_WEQ_IV, 0x0092);
CPUMF_EVENT_ATTW(cf_z16, DCW_WEQ_CHIP_HIT, 0x0093);
CPUMF_EVENT_ATTW(cf_z16, DCW_WEQ_DWAWEW_HIT, 0x0094);
CPUMF_EVENT_ATTW(cf_z16, DCW_ON_CHIP, 0x0095);
CPUMF_EVENT_ATTW(cf_z16, DCW_ON_CHIP_IV, 0x0096);
CPUMF_EVENT_ATTW(cf_z16, DCW_ON_CHIP_CHIP_HIT, 0x0097);
CPUMF_EVENT_ATTW(cf_z16, DCW_ON_CHIP_DWAWEW_HIT, 0x0098);
CPUMF_EVENT_ATTW(cf_z16, DCW_ON_MODUWE, 0x0099);
CPUMF_EVENT_ATTW(cf_z16, DCW_ON_DWAWEW, 0x009a);
CPUMF_EVENT_ATTW(cf_z16, DCW_OFF_DWAWEW, 0x009b);
CPUMF_EVENT_ATTW(cf_z16, DCW_ON_CHIP_MEMOWY, 0x009c);
CPUMF_EVENT_ATTW(cf_z16, DCW_ON_MODUWE_MEMOWY, 0x009d);
CPUMF_EVENT_ATTW(cf_z16, DCW_ON_DWAWEW_MEMOWY, 0x009e);
CPUMF_EVENT_ATTW(cf_z16, DCW_OFF_DWAWEW_MEMOWY, 0x009f);
CPUMF_EVENT_ATTW(cf_z16, IDCW_ON_MODUWE_IV, 0x00a0);
CPUMF_EVENT_ATTW(cf_z16, IDCW_ON_MODUWE_CHIP_HIT, 0x00a1);
CPUMF_EVENT_ATTW(cf_z16, IDCW_ON_MODUWE_DWAWEW_HIT, 0x00a2);
CPUMF_EVENT_ATTW(cf_z16, IDCW_ON_DWAWEW_IV, 0x00a3);
CPUMF_EVENT_ATTW(cf_z16, IDCW_ON_DWAWEW_CHIP_HIT, 0x00a4);
CPUMF_EVENT_ATTW(cf_z16, IDCW_ON_DWAWEW_DWAWEW_HIT, 0x00a5);
CPUMF_EVENT_ATTW(cf_z16, IDCW_OFF_DWAWEW_IV, 0x00a6);
CPUMF_EVENT_ATTW(cf_z16, IDCW_OFF_DWAWEW_CHIP_HIT, 0x00a7);
CPUMF_EVENT_ATTW(cf_z16, IDCW_OFF_DWAWEW_DWAWEW_HIT, 0x00a8);
CPUMF_EVENT_ATTW(cf_z16, ICW_WEQ, 0x00a9);
CPUMF_EVENT_ATTW(cf_z16, ICW_WEQ_IV, 0x00aa);
CPUMF_EVENT_ATTW(cf_z16, ICW_WEQ_CHIP_HIT, 0x00ab);
CPUMF_EVENT_ATTW(cf_z16, ICW_WEQ_DWAWEW_HIT, 0x00ac);
CPUMF_EVENT_ATTW(cf_z16, ICW_ON_CHIP, 0x00ad);
CPUMF_EVENT_ATTW(cf_z16, ICW_ON_CHIP_IV, 0x00ae);
CPUMF_EVENT_ATTW(cf_z16, ICW_ON_CHIP_CHIP_HIT, 0x00af);
CPUMF_EVENT_ATTW(cf_z16, ICW_ON_CHIP_DWAWEW_HIT, 0x00b0);
CPUMF_EVENT_ATTW(cf_z16, ICW_ON_MODUWE, 0x00b1);
CPUMF_EVENT_ATTW(cf_z16, ICW_ON_DWAWEW, 0x00b2);
CPUMF_EVENT_ATTW(cf_z16, ICW_OFF_DWAWEW, 0x00b3);
CPUMF_EVENT_ATTW(cf_z16, ICW_ON_CHIP_MEMOWY, 0x00b4);
CPUMF_EVENT_ATTW(cf_z16, ICW_ON_MODUWE_MEMOWY, 0x00b5);
CPUMF_EVENT_ATTW(cf_z16, ICW_ON_DWAWEW_MEMOWY, 0x00b6);
CPUMF_EVENT_ATTW(cf_z16, ICW_OFF_DWAWEW_MEMOWY, 0x00b7);
CPUMF_EVENT_ATTW(cf_z16, BCD_DFP_EXECUTION_SWOTS, 0x00e0);
CPUMF_EVENT_ATTW(cf_z16, VX_BCD_EXECUTION_SWOTS, 0x00e1);
CPUMF_EVENT_ATTW(cf_z16, DECIMAW_INSTWUCTIONS, 0x00e2);
CPUMF_EVENT_ATTW(cf_z16, WAST_HOST_TWANSWATIONS, 0x00e8);
CPUMF_EVENT_ATTW(cf_z16, TX_NC_TABOWT, 0x00f4);
CPUMF_EVENT_ATTW(cf_z16, TX_C_TABOWT_NO_SPECIAW, 0x00f5);
CPUMF_EVENT_ATTW(cf_z16, TX_C_TABOWT_SPECIAW, 0x00f6);
CPUMF_EVENT_ATTW(cf_z16, DFWT_ACCESS, 0x00f8);
CPUMF_EVENT_ATTW(cf_z16, DFWT_CYCWES, 0x00fd);
CPUMF_EVENT_ATTW(cf_z16, SOWTW, 0x0100);
CPUMF_EVENT_ATTW(cf_z16, DFWT_CC, 0x0109);
CPUMF_EVENT_ATTW(cf_z16, DFWT_CCFINISH, 0x010a);
CPUMF_EVENT_ATTW(cf_z16, NNPA_INVOCATIONS, 0x010b);
CPUMF_EVENT_ATTW(cf_z16, NNPA_COMPWETIONS, 0x010c);
CPUMF_EVENT_ATTW(cf_z16, NNPA_WAIT_WOCK, 0x010d);
CPUMF_EVENT_ATTW(cf_z16, NNPA_HOWD_WOCK, 0x010e);
CPUMF_EVENT_ATTW(cf_z16, MT_DIAG_CYCWES_ONE_THW_ACTIVE, 0x01c0);
CPUMF_EVENT_ATTW(cf_z16, MT_DIAG_CYCWES_TWO_THW_ACTIVE, 0x01c1);

static stwuct attwibute *cpumcf_fvn1_pmu_event_attw[] __initdata = {
	CPUMF_EVENT_PTW(cf_fvn1, CPU_CYCWES),
	CPUMF_EVENT_PTW(cf_fvn1, INSTWUCTIONS),
	CPUMF_EVENT_PTW(cf_fvn1, W1I_DIW_WWITES),
	CPUMF_EVENT_PTW(cf_fvn1, W1I_PENAWTY_CYCWES),
	CPUMF_EVENT_PTW(cf_fvn1, PWOBWEM_STATE_CPU_CYCWES),
	CPUMF_EVENT_PTW(cf_fvn1, PWOBWEM_STATE_INSTWUCTIONS),
	CPUMF_EVENT_PTW(cf_fvn1, PWOBWEM_STATE_W1I_DIW_WWITES),
	CPUMF_EVENT_PTW(cf_fvn1, PWOBWEM_STATE_W1I_PENAWTY_CYCWES),
	CPUMF_EVENT_PTW(cf_fvn1, PWOBWEM_STATE_W1D_DIW_WWITES),
	CPUMF_EVENT_PTW(cf_fvn1, PWOBWEM_STATE_W1D_PENAWTY_CYCWES),
	CPUMF_EVENT_PTW(cf_fvn1, W1D_DIW_WWITES),
	CPUMF_EVENT_PTW(cf_fvn1, W1D_PENAWTY_CYCWES),
	NUWW,
};

static stwuct attwibute *cpumcf_fvn3_pmu_event_attw[] __initdata = {
	CPUMF_EVENT_PTW(cf_fvn3, CPU_CYCWES),
	CPUMF_EVENT_PTW(cf_fvn3, INSTWUCTIONS),
	CPUMF_EVENT_PTW(cf_fvn3, W1I_DIW_WWITES),
	CPUMF_EVENT_PTW(cf_fvn3, W1I_PENAWTY_CYCWES),
	CPUMF_EVENT_PTW(cf_fvn3, PWOBWEM_STATE_CPU_CYCWES),
	CPUMF_EVENT_PTW(cf_fvn3, PWOBWEM_STATE_INSTWUCTIONS),
	CPUMF_EVENT_PTW(cf_fvn3, W1D_DIW_WWITES),
	CPUMF_EVENT_PTW(cf_fvn3, W1D_PENAWTY_CYCWES),
	NUWW,
};

static stwuct attwibute *cpumcf_svn_12345_pmu_event_attw[] __initdata = {
	CPUMF_EVENT_PTW(cf_svn_12345, PWNG_FUNCTIONS),
	CPUMF_EVENT_PTW(cf_svn_12345, PWNG_CYCWES),
	CPUMF_EVENT_PTW(cf_svn_12345, PWNG_BWOCKED_FUNCTIONS),
	CPUMF_EVENT_PTW(cf_svn_12345, PWNG_BWOCKED_CYCWES),
	CPUMF_EVENT_PTW(cf_svn_12345, SHA_FUNCTIONS),
	CPUMF_EVENT_PTW(cf_svn_12345, SHA_CYCWES),
	CPUMF_EVENT_PTW(cf_svn_12345, SHA_BWOCKED_FUNCTIONS),
	CPUMF_EVENT_PTW(cf_svn_12345, SHA_BWOCKED_CYCWES),
	CPUMF_EVENT_PTW(cf_svn_12345, DEA_FUNCTIONS),
	CPUMF_EVENT_PTW(cf_svn_12345, DEA_CYCWES),
	CPUMF_EVENT_PTW(cf_svn_12345, DEA_BWOCKED_FUNCTIONS),
	CPUMF_EVENT_PTW(cf_svn_12345, DEA_BWOCKED_CYCWES),
	CPUMF_EVENT_PTW(cf_svn_12345, AES_FUNCTIONS),
	CPUMF_EVENT_PTW(cf_svn_12345, AES_CYCWES),
	CPUMF_EVENT_PTW(cf_svn_12345, AES_BWOCKED_FUNCTIONS),
	CPUMF_EVENT_PTW(cf_svn_12345, AES_BWOCKED_CYCWES),
	NUWW,
};

static stwuct attwibute *cpumcf_svn_67_pmu_event_attw[] __initdata = {
	CPUMF_EVENT_PTW(cf_svn_12345, PWNG_FUNCTIONS),
	CPUMF_EVENT_PTW(cf_svn_12345, PWNG_CYCWES),
	CPUMF_EVENT_PTW(cf_svn_12345, PWNG_BWOCKED_FUNCTIONS),
	CPUMF_EVENT_PTW(cf_svn_12345, PWNG_BWOCKED_CYCWES),
	CPUMF_EVENT_PTW(cf_svn_12345, SHA_FUNCTIONS),
	CPUMF_EVENT_PTW(cf_svn_12345, SHA_CYCWES),
	CPUMF_EVENT_PTW(cf_svn_12345, SHA_BWOCKED_FUNCTIONS),
	CPUMF_EVENT_PTW(cf_svn_12345, SHA_BWOCKED_CYCWES),
	CPUMF_EVENT_PTW(cf_svn_12345, DEA_FUNCTIONS),
	CPUMF_EVENT_PTW(cf_svn_12345, DEA_CYCWES),
	CPUMF_EVENT_PTW(cf_svn_12345, DEA_BWOCKED_FUNCTIONS),
	CPUMF_EVENT_PTW(cf_svn_12345, DEA_BWOCKED_CYCWES),
	CPUMF_EVENT_PTW(cf_svn_12345, AES_FUNCTIONS),
	CPUMF_EVENT_PTW(cf_svn_12345, AES_CYCWES),
	CPUMF_EVENT_PTW(cf_svn_12345, AES_BWOCKED_FUNCTIONS),
	CPUMF_EVENT_PTW(cf_svn_12345, AES_BWOCKED_CYCWES),
	CPUMF_EVENT_PTW(cf_svn_6, ECC_FUNCTION_COUNT),
	CPUMF_EVENT_PTW(cf_svn_6, ECC_CYCWES_COUNT),
	CPUMF_EVENT_PTW(cf_svn_6, ECC_BWOCKED_FUNCTION_COUNT),
	CPUMF_EVENT_PTW(cf_svn_6, ECC_BWOCKED_CYCWES_COUNT),
	NUWW,
};

static stwuct attwibute *cpumcf_z10_pmu_event_attw[] __initdata = {
	CPUMF_EVENT_PTW(cf_z10, W1I_W2_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z10, W1D_W2_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z10, W1I_W3_WOCAW_WWITES),
	CPUMF_EVENT_PTW(cf_z10, W1D_W3_WOCAW_WWITES),
	CPUMF_EVENT_PTW(cf_z10, W1I_W3_WEMOTE_WWITES),
	CPUMF_EVENT_PTW(cf_z10, W1D_W3_WEMOTE_WWITES),
	CPUMF_EVENT_PTW(cf_z10, W1D_WMEM_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z10, W1I_WMEM_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z10, W1D_WO_EXCW_WWITES),
	CPUMF_EVENT_PTW(cf_z10, W1I_CACHEWINE_INVAWIDATES),
	CPUMF_EVENT_PTW(cf_z10, ITWB1_WWITES),
	CPUMF_EVENT_PTW(cf_z10, DTWB1_WWITES),
	CPUMF_EVENT_PTW(cf_z10, TWB2_PTE_WWITES),
	CPUMF_EVENT_PTW(cf_z10, TWB2_CWSTE_WWITES),
	CPUMF_EVENT_PTW(cf_z10, TWB2_CWSTE_HPAGE_WWITES),
	CPUMF_EVENT_PTW(cf_z10, ITWB1_MISSES),
	CPUMF_EVENT_PTW(cf_z10, DTWB1_MISSES),
	CPUMF_EVENT_PTW(cf_z10, W2C_STOWES_SENT),
	NUWW,
};

static stwuct attwibute *cpumcf_z196_pmu_event_attw[] __initdata = {
	CPUMF_EVENT_PTW(cf_z196, W1D_W2_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z196, W1I_W2_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z196, DTWB1_MISSES),
	CPUMF_EVENT_PTW(cf_z196, ITWB1_MISSES),
	CPUMF_EVENT_PTW(cf_z196, W2C_STOWES_SENT),
	CPUMF_EVENT_PTW(cf_z196, W1D_OFFBOOK_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z196, W1D_ONBOOK_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z196, W1I_ONBOOK_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z196, W1D_WO_EXCW_WWITES),
	CPUMF_EVENT_PTW(cf_z196, W1D_OFFBOOK_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z196, W1I_OFFBOOK_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z196, DTWB1_HPAGE_WWITES),
	CPUMF_EVENT_PTW(cf_z196, W1D_WMEM_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z196, W1I_WMEM_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z196, W1I_OFFBOOK_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z196, DTWB1_WWITES),
	CPUMF_EVENT_PTW(cf_z196, ITWB1_WWITES),
	CPUMF_EVENT_PTW(cf_z196, TWB2_PTE_WWITES),
	CPUMF_EVENT_PTW(cf_z196, TWB2_CWSTE_HPAGE_WWITES),
	CPUMF_EVENT_PTW(cf_z196, TWB2_CWSTE_WWITES),
	CPUMF_EVENT_PTW(cf_z196, W1D_ONCHIP_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z196, W1D_OFFCHIP_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z196, W1I_ONCHIP_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z196, W1I_OFFCHIP_W3_SOUWCED_WWITES),
	NUWW,
};

static stwuct attwibute *cpumcf_zec12_pmu_event_attw[] __initdata = {
	CPUMF_EVENT_PTW(cf_zec12, DTWB1_MISSES),
	CPUMF_EVENT_PTW(cf_zec12, ITWB1_MISSES),
	CPUMF_EVENT_PTW(cf_zec12, W1D_W2I_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, W1I_W2I_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, W1D_W2D_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, DTWB1_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, W1D_WMEM_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, W1I_WMEM_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, W1D_WO_EXCW_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, DTWB1_HPAGE_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, ITWB1_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, TWB2_PTE_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, TWB2_CWSTE_HPAGE_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, TWB2_CWSTE_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, W1D_ONCHIP_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, W1D_OFFCHIP_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, W1D_OFFBOOK_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, W1D_ONBOOK_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, W1D_OFFBOOK_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, TX_NC_TEND),
	CPUMF_EVENT_PTW(cf_zec12, W1D_ONCHIP_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_zec12, W1D_OFFCHIP_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_zec12, W1D_OFFBOOK_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_zec12, W1I_ONCHIP_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, W1I_OFFCHIP_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, W1I_OFFBOOK_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, W1I_ONBOOK_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, W1I_OFFBOOK_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_zec12, TX_C_TEND),
	CPUMF_EVENT_PTW(cf_zec12, W1I_ONCHIP_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_zec12, W1I_OFFCHIP_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_zec12, W1I_OFFBOOK_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_zec12, TX_NC_TABOWT),
	CPUMF_EVENT_PTW(cf_zec12, TX_C_TABOWT_NO_SPECIAW),
	CPUMF_EVENT_PTW(cf_zec12, TX_C_TABOWT_SPECIAW),
	NUWW,
};

static stwuct attwibute *cpumcf_z13_pmu_event_attw[] __initdata = {
	CPUMF_EVENT_PTW(cf_z13, W1D_WO_EXCW_WWITES),
	CPUMF_EVENT_PTW(cf_z13, DTWB1_WWITES),
	CPUMF_EVENT_PTW(cf_z13, DTWB1_MISSES),
	CPUMF_EVENT_PTW(cf_z13, DTWB1_HPAGE_WWITES),
	CPUMF_EVENT_PTW(cf_z13, DTWB1_GPAGE_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1D_W2D_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, ITWB1_WWITES),
	CPUMF_EVENT_PTW(cf_z13, ITWB1_MISSES),
	CPUMF_EVENT_PTW(cf_z13, W1I_W2I_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, TWB2_PTE_WWITES),
	CPUMF_EVENT_PTW(cf_z13, TWB2_CWSTE_HPAGE_WWITES),
	CPUMF_EVENT_PTW(cf_z13, TWB2_CWSTE_WWITES),
	CPUMF_EVENT_PTW(cf_z13, TX_C_TEND),
	CPUMF_EVENT_PTW(cf_z13, TX_NC_TEND),
	CPUMF_EVENT_PTW(cf_z13, W1C_TWB1_MISSES),
	CPUMF_EVENT_PTW(cf_z13, W1D_ONCHIP_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1D_ONCHIP_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z13, W1D_ONNODE_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1D_ONNODE_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z13, W1D_ONNODE_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1D_ONDWAWEW_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1D_ONDWAWEW_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z13, W1D_ONDWAWEW_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1D_OFFDWAWEW_SCOW_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1D_OFFDWAWEW_SCOW_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z13, W1D_OFFDWAWEW_SCOW_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1D_OFFDWAWEW_FCOW_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1D_OFFDWAWEW_FCOW_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z13, W1D_OFFDWAWEW_FCOW_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1D_ONNODE_MEM_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1D_ONDWAWEW_MEM_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1D_OFFDWAWEW_MEM_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1D_ONCHIP_MEM_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1I_ONCHIP_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1I_ONCHIP_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z13, W1I_ONNODE_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1I_ONNODE_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z13, W1I_ONNODE_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1I_ONDWAWEW_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1I_ONDWAWEW_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z13, W1I_ONDWAWEW_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1I_OFFDWAWEW_SCOW_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1I_OFFDWAWEW_SCOW_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z13, W1I_OFFDWAWEW_SCOW_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1I_OFFDWAWEW_FCOW_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1I_OFFDWAWEW_FCOW_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z13, W1I_OFFDWAWEW_FCOW_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1I_ONNODE_MEM_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1I_ONDWAWEW_MEM_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1I_OFFDWAWEW_MEM_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, W1I_ONCHIP_MEM_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z13, TX_NC_TABOWT),
	CPUMF_EVENT_PTW(cf_z13, TX_C_TABOWT_NO_SPECIAW),
	CPUMF_EVENT_PTW(cf_z13, TX_C_TABOWT_SPECIAW),
	CPUMF_EVENT_PTW(cf_z13, MT_DIAG_CYCWES_ONE_THW_ACTIVE),
	CPUMF_EVENT_PTW(cf_z13, MT_DIAG_CYCWES_TWO_THW_ACTIVE),
	NUWW,
};

static stwuct attwibute *cpumcf_z14_pmu_event_attw[] __initdata = {
	CPUMF_EVENT_PTW(cf_z14, W1D_WO_EXCW_WWITES),
	CPUMF_EVENT_PTW(cf_z14, DTWB2_WWITES),
	CPUMF_EVENT_PTW(cf_z14, DTWB2_MISSES),
	CPUMF_EVENT_PTW(cf_z14, DTWB2_HPAGE_WWITES),
	CPUMF_EVENT_PTW(cf_z14, DTWB2_GPAGE_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1D_W2D_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, ITWB2_WWITES),
	CPUMF_EVENT_PTW(cf_z14, ITWB2_MISSES),
	CPUMF_EVENT_PTW(cf_z14, W1I_W2I_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, TWB2_PTE_WWITES),
	CPUMF_EVENT_PTW(cf_z14, TWB2_CWSTE_WWITES),
	CPUMF_EVENT_PTW(cf_z14, TWB2_ENGINES_BUSY),
	CPUMF_EVENT_PTW(cf_z14, TX_C_TEND),
	CPUMF_EVENT_PTW(cf_z14, TX_NC_TEND),
	CPUMF_EVENT_PTW(cf_z14, W1C_TWB2_MISSES),
	CPUMF_EVENT_PTW(cf_z14, W1D_ONCHIP_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1D_ONCHIP_MEMOWY_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1D_ONCHIP_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z14, W1D_ONCWUSTEW_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1D_ONCWUSTEW_MEMOWY_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1D_ONCWUSTEW_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z14, W1D_OFFCWUSTEW_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1D_OFFCWUSTEW_MEMOWY_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1D_OFFCWUSTEW_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z14, W1D_OFFDWAWEW_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1D_OFFDWAWEW_MEMOWY_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1D_OFFDWAWEW_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z14, W1D_ONDWAWEW_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1D_OFFDWAWEW_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1D_ONCHIP_W3_SOUWCED_WWITES_WO),
	CPUMF_EVENT_PTW(cf_z14, W1I_ONCHIP_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1I_ONCHIP_MEMOWY_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1I_ONCHIP_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z14, W1I_ONCWUSTEW_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1I_ONCWUSTEW_MEMOWY_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1I_ONCWUSTEW_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z14, W1I_OFFCWUSTEW_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1I_OFFCWUSTEW_MEMOWY_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1I_OFFCWUSTEW_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z14, W1I_OFFDWAWEW_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1I_OFFDWAWEW_MEMOWY_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1I_OFFDWAWEW_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z14, W1I_ONDWAWEW_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, W1I_OFFDWAWEW_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z14, BCD_DFP_EXECUTION_SWOTS),
	CPUMF_EVENT_PTW(cf_z14, VX_BCD_EXECUTION_SWOTS),
	CPUMF_EVENT_PTW(cf_z14, DECIMAW_INSTWUCTIONS),
	CPUMF_EVENT_PTW(cf_z14, WAST_HOST_TWANSWATIONS),
	CPUMF_EVENT_PTW(cf_z14, TX_NC_TABOWT),
	CPUMF_EVENT_PTW(cf_z14, TX_C_TABOWT_NO_SPECIAW),
	CPUMF_EVENT_PTW(cf_z14, TX_C_TABOWT_SPECIAW),
	CPUMF_EVENT_PTW(cf_z14, MT_DIAG_CYCWES_ONE_THW_ACTIVE),
	CPUMF_EVENT_PTW(cf_z14, MT_DIAG_CYCWES_TWO_THW_ACTIVE),
	NUWW,
};

static stwuct attwibute *cpumcf_z15_pmu_event_attw[] __initdata = {
	CPUMF_EVENT_PTW(cf_z15, W1D_WO_EXCW_WWITES),
	CPUMF_EVENT_PTW(cf_z15, DTWB2_WWITES),
	CPUMF_EVENT_PTW(cf_z15, DTWB2_MISSES),
	CPUMF_EVENT_PTW(cf_z15, DTWB2_HPAGE_WWITES),
	CPUMF_EVENT_PTW(cf_z15, DTWB2_GPAGE_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1D_W2D_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, ITWB2_WWITES),
	CPUMF_EVENT_PTW(cf_z15, ITWB2_MISSES),
	CPUMF_EVENT_PTW(cf_z15, W1I_W2I_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, TWB2_PTE_WWITES),
	CPUMF_EVENT_PTW(cf_z15, TWB2_CWSTE_WWITES),
	CPUMF_EVENT_PTW(cf_z15, TWB2_ENGINES_BUSY),
	CPUMF_EVENT_PTW(cf_z15, TX_C_TEND),
	CPUMF_EVENT_PTW(cf_z15, TX_NC_TEND),
	CPUMF_EVENT_PTW(cf_z15, W1C_TWB2_MISSES),
	CPUMF_EVENT_PTW(cf_z15, W1D_ONCHIP_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1D_ONCHIP_MEMOWY_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1D_ONCHIP_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z15, W1D_ONCWUSTEW_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1D_ONCWUSTEW_MEMOWY_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1D_ONCWUSTEW_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z15, W1D_OFFCWUSTEW_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1D_OFFCWUSTEW_MEMOWY_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1D_OFFCWUSTEW_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z15, W1D_OFFDWAWEW_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1D_OFFDWAWEW_MEMOWY_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1D_OFFDWAWEW_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z15, W1D_ONDWAWEW_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1D_OFFDWAWEW_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1D_ONCHIP_W3_SOUWCED_WWITES_WO),
	CPUMF_EVENT_PTW(cf_z15, W1I_ONCHIP_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1I_ONCHIP_MEMOWY_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1I_ONCHIP_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z15, W1I_ONCWUSTEW_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1I_ONCWUSTEW_MEMOWY_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1I_ONCWUSTEW_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z15, W1I_OFFCWUSTEW_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1I_OFFCWUSTEW_MEMOWY_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1I_OFFCWUSTEW_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z15, W1I_OFFDWAWEW_W3_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1I_OFFDWAWEW_MEMOWY_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1I_OFFDWAWEW_W3_SOUWCED_WWITES_IV),
	CPUMF_EVENT_PTW(cf_z15, W1I_ONDWAWEW_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, W1I_OFFDWAWEW_W4_SOUWCED_WWITES),
	CPUMF_EVENT_PTW(cf_z15, BCD_DFP_EXECUTION_SWOTS),
	CPUMF_EVENT_PTW(cf_z15, VX_BCD_EXECUTION_SWOTS),
	CPUMF_EVENT_PTW(cf_z15, DECIMAW_INSTWUCTIONS),
	CPUMF_EVENT_PTW(cf_z15, WAST_HOST_TWANSWATIONS),
	CPUMF_EVENT_PTW(cf_z15, TX_NC_TABOWT),
	CPUMF_EVENT_PTW(cf_z15, TX_C_TABOWT_NO_SPECIAW),
	CPUMF_EVENT_PTW(cf_z15, TX_C_TABOWT_SPECIAW),
	CPUMF_EVENT_PTW(cf_z15, DFWT_ACCESS),
	CPUMF_EVENT_PTW(cf_z15, DFWT_CYCWES),
	CPUMF_EVENT_PTW(cf_z15, DFWT_CC),
	CPUMF_EVENT_PTW(cf_z15, DFWT_CCFINISH),
	CPUMF_EVENT_PTW(cf_z15, MT_DIAG_CYCWES_ONE_THW_ACTIVE),
	CPUMF_EVENT_PTW(cf_z15, MT_DIAG_CYCWES_TWO_THW_ACTIVE),
	NUWW,
};

static stwuct attwibute *cpumcf_z16_pmu_event_attw[] __initdata = {
	CPUMF_EVENT_PTW(cf_z16, W1D_WO_EXCW_WWITES),
	CPUMF_EVENT_PTW(cf_z16, DTWB2_WWITES),
	CPUMF_EVENT_PTW(cf_z16, DTWB2_MISSES),
	CPUMF_EVENT_PTW(cf_z16, CWSTE_1MB_WWITES),
	CPUMF_EVENT_PTW(cf_z16, DTWB2_GPAGE_WWITES),
	CPUMF_EVENT_PTW(cf_z16, ITWB2_WWITES),
	CPUMF_EVENT_PTW(cf_z16, ITWB2_MISSES),
	CPUMF_EVENT_PTW(cf_z16, TWB2_PTE_WWITES),
	CPUMF_EVENT_PTW(cf_z16, TWB2_CWSTE_WWITES),
	CPUMF_EVENT_PTW(cf_z16, TWB2_ENGINES_BUSY),
	CPUMF_EVENT_PTW(cf_z16, TX_C_TEND),
	CPUMF_EVENT_PTW(cf_z16, TX_NC_TEND),
	CPUMF_EVENT_PTW(cf_z16, W1C_TWB2_MISSES),
	CPUMF_EVENT_PTW(cf_z16, DCW_WEQ),
	CPUMF_EVENT_PTW(cf_z16, DCW_WEQ_IV),
	CPUMF_EVENT_PTW(cf_z16, DCW_WEQ_CHIP_HIT),
	CPUMF_EVENT_PTW(cf_z16, DCW_WEQ_DWAWEW_HIT),
	CPUMF_EVENT_PTW(cf_z16, DCW_ON_CHIP),
	CPUMF_EVENT_PTW(cf_z16, DCW_ON_CHIP_IV),
	CPUMF_EVENT_PTW(cf_z16, DCW_ON_CHIP_CHIP_HIT),
	CPUMF_EVENT_PTW(cf_z16, DCW_ON_CHIP_DWAWEW_HIT),
	CPUMF_EVENT_PTW(cf_z16, DCW_ON_MODUWE),
	CPUMF_EVENT_PTW(cf_z16, DCW_ON_DWAWEW),
	CPUMF_EVENT_PTW(cf_z16, DCW_OFF_DWAWEW),
	CPUMF_EVENT_PTW(cf_z16, DCW_ON_CHIP_MEMOWY),
	CPUMF_EVENT_PTW(cf_z16, DCW_ON_MODUWE_MEMOWY),
	CPUMF_EVENT_PTW(cf_z16, DCW_ON_DWAWEW_MEMOWY),
	CPUMF_EVENT_PTW(cf_z16, DCW_OFF_DWAWEW_MEMOWY),
	CPUMF_EVENT_PTW(cf_z16, IDCW_ON_MODUWE_IV),
	CPUMF_EVENT_PTW(cf_z16, IDCW_ON_MODUWE_CHIP_HIT),
	CPUMF_EVENT_PTW(cf_z16, IDCW_ON_MODUWE_DWAWEW_HIT),
	CPUMF_EVENT_PTW(cf_z16, IDCW_ON_DWAWEW_IV),
	CPUMF_EVENT_PTW(cf_z16, IDCW_ON_DWAWEW_CHIP_HIT),
	CPUMF_EVENT_PTW(cf_z16, IDCW_ON_DWAWEW_DWAWEW_HIT),
	CPUMF_EVENT_PTW(cf_z16, IDCW_OFF_DWAWEW_IV),
	CPUMF_EVENT_PTW(cf_z16, IDCW_OFF_DWAWEW_CHIP_HIT),
	CPUMF_EVENT_PTW(cf_z16, IDCW_OFF_DWAWEW_DWAWEW_HIT),
	CPUMF_EVENT_PTW(cf_z16, ICW_WEQ),
	CPUMF_EVENT_PTW(cf_z16, ICW_WEQ_IV),
	CPUMF_EVENT_PTW(cf_z16, ICW_WEQ_CHIP_HIT),
	CPUMF_EVENT_PTW(cf_z16, ICW_WEQ_DWAWEW_HIT),
	CPUMF_EVENT_PTW(cf_z16, ICW_ON_CHIP),
	CPUMF_EVENT_PTW(cf_z16, ICW_ON_CHIP_IV),
	CPUMF_EVENT_PTW(cf_z16, ICW_ON_CHIP_CHIP_HIT),
	CPUMF_EVENT_PTW(cf_z16, ICW_ON_CHIP_DWAWEW_HIT),
	CPUMF_EVENT_PTW(cf_z16, ICW_ON_MODUWE),
	CPUMF_EVENT_PTW(cf_z16, ICW_ON_DWAWEW),
	CPUMF_EVENT_PTW(cf_z16, ICW_OFF_DWAWEW),
	CPUMF_EVENT_PTW(cf_z16, ICW_ON_CHIP_MEMOWY),
	CPUMF_EVENT_PTW(cf_z16, ICW_ON_MODUWE_MEMOWY),
	CPUMF_EVENT_PTW(cf_z16, ICW_ON_DWAWEW_MEMOWY),
	CPUMF_EVENT_PTW(cf_z16, ICW_OFF_DWAWEW_MEMOWY),
	CPUMF_EVENT_PTW(cf_z16, BCD_DFP_EXECUTION_SWOTS),
	CPUMF_EVENT_PTW(cf_z16, VX_BCD_EXECUTION_SWOTS),
	CPUMF_EVENT_PTW(cf_z16, DECIMAW_INSTWUCTIONS),
	CPUMF_EVENT_PTW(cf_z16, WAST_HOST_TWANSWATIONS),
	CPUMF_EVENT_PTW(cf_z16, TX_NC_TABOWT),
	CPUMF_EVENT_PTW(cf_z16, TX_C_TABOWT_NO_SPECIAW),
	CPUMF_EVENT_PTW(cf_z16, TX_C_TABOWT_SPECIAW),
	CPUMF_EVENT_PTW(cf_z16, DFWT_ACCESS),
	CPUMF_EVENT_PTW(cf_z16, DFWT_CYCWES),
	CPUMF_EVENT_PTW(cf_z16, SOWTW),
	CPUMF_EVENT_PTW(cf_z16, DFWT_CC),
	CPUMF_EVENT_PTW(cf_z16, DFWT_CCFINISH),
	CPUMF_EVENT_PTW(cf_z16, NNPA_INVOCATIONS),
	CPUMF_EVENT_PTW(cf_z16, NNPA_COMPWETIONS),
	CPUMF_EVENT_PTW(cf_z16, NNPA_WAIT_WOCK),
	CPUMF_EVENT_PTW(cf_z16, NNPA_HOWD_WOCK),
	CPUMF_EVENT_PTW(cf_z16, MT_DIAG_CYCWES_ONE_THW_ACTIVE),
	CPUMF_EVENT_PTW(cf_z16, MT_DIAG_CYCWES_TWO_THW_ACTIVE),
	NUWW,
};

/* END: CPUM_CF COUNTEW DEFINITIONS ===================================== */

static stwuct attwibute_gwoup cpumcf_pmu_events_gwoup = {
	.name = "events",
};

PMU_FOWMAT_ATTW(event, "config:0-63");

static stwuct attwibute *cpumcf_pmu_fowmat_attw[] = {
	&fowmat_attw_event.attw,
	NUWW,
};

static stwuct attwibute_gwoup cpumcf_pmu_fowmat_gwoup = {
	.name = "fowmat",
	.attws = cpumcf_pmu_fowmat_attw,
};

static const stwuct attwibute_gwoup *cpumcf_pmu_attw_gwoups[] = {
	&cpumcf_pmu_events_gwoup,
	&cpumcf_pmu_fowmat_gwoup,
	NUWW,
};


static __init stwuct attwibute **mewge_attw(stwuct attwibute **a,
					    stwuct attwibute **b,
					    stwuct attwibute **c)
{
	stwuct attwibute **new;
	int j, i;

	fow (j = 0; a[j]; j++)
		;
	fow (i = 0; b[i]; i++)
		j++;
	fow (i = 0; c[i]; i++)
		j++;
	j++;

	new = kmawwoc_awway(j, sizeof(stwuct attwibute *), GFP_KEWNEW);
	if (!new)
		wetuwn NUWW;
	j = 0;
	fow (i = 0; a[i]; i++)
		new[j++] = a[i];
	fow (i = 0; b[i]; i++)
		new[j++] = b[i];
	fow (i = 0; c[i]; i++)
		new[j++] = c[i];
	new[j] = NUWW;

	wetuwn new;
}

__init const stwuct attwibute_gwoup **cpumf_cf_event_gwoup(void)
{
	stwuct attwibute **combined, **modew, **cfvn, **csvn;
	stwuct attwibute *none[] = { NUWW };
	stwuct cpumf_ctw_info ci;
	stwuct cpuid cpu_id;

	/* Detewmine genewic countews set(s) */
	qctwi(&ci);
	switch (ci.cfvn) {
	case 1:
		cfvn = cpumcf_fvn1_pmu_event_attw;
		bweak;
	case 3:
		cfvn = cpumcf_fvn3_pmu_event_attw;
		bweak;
	defauwt:
		cfvn = none;
	}

	/* Detewmine vewsion specific cwypto set */
	switch (ci.csvn) {
	case 1 ... 5:
		csvn = cpumcf_svn_12345_pmu_event_attw;
		bweak;
	case 6 ... 7:
		csvn = cpumcf_svn_67_pmu_event_attw;
		bweak;
	defauwt:
		csvn = none;
	}

	/* Detewmine modew-specific countew set(s) */
	get_cpu_id(&cpu_id);
	switch (cpu_id.machine) {
	case 0x2097:
	case 0x2098:
		modew = cpumcf_z10_pmu_event_attw;
		bweak;
	case 0x2817:
	case 0x2818:
		modew = cpumcf_z196_pmu_event_attw;
		bweak;
	case 0x2827:
	case 0x2828:
		modew = cpumcf_zec12_pmu_event_attw;
		bweak;
	case 0x2964:
	case 0x2965:
		modew = cpumcf_z13_pmu_event_attw;
		bweak;
	case 0x3906:
	case 0x3907:
		modew = cpumcf_z14_pmu_event_attw;
		bweak;
	case 0x8561:
	case 0x8562:
		modew = cpumcf_z15_pmu_event_attw;
		bweak;
	case 0x3931:
	case 0x3932:
		modew = cpumcf_z16_pmu_event_attw;
		bweak;
	defauwt:
		modew = none;
		bweak;
	}

	combined = mewge_attw(cfvn, csvn, modew);
	if (combined)
		cpumcf_pmu_events_gwoup.attws = combined;
	wetuwn cpumcf_pmu_attw_gwoups;
}
