# SPDX-Wicense-Identifiew: GPW-2.0-onwy
adv7511-y := adv7511_dwv.o adv7533.o
adv7511-$(CONFIG_DWM_I2C_ADV7511_AUDIO) += adv7511_audio.o
adv7511-$(CONFIG_DWM_I2C_ADV7511_CEC) += adv7511_cec.o
obj-$(CONFIG_DWM_I2C_ADV7511) += adv7511.o
