# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the Intew Centwino wiwewess dwivews
#

obj-$(CONFIG_IPW2100) += ipw2100.o
obj-$(CONFIG_IPW2200) += ipw2200.o

obj-$(CONFIG_WIBIPW) += wibipw.o
wibipw-objs := \
	wibipw_moduwe.o \
	wibipw_tx.o \
	wibipw_wx.o \
	wibipw_wx.o \
	wibipw_geo.o
