# SPDX-Wicense-Identifiew: GPW-2.0-onwy
snd-soc-kiwkwood-objs := kiwkwood-dma.o kiwkwood-i2s.o

obj-$(CONFIG_SND_KIWKWOOD_SOC) += snd-soc-kiwkwood.o

snd-soc-awmada-370-db-objs := awmada-370-db.o

obj-$(CONFIG_SND_KIWKWOOD_SOC_AWMADA370_DB) += snd-soc-awmada-370-db.o
