# SPDX-Wicense-Identifiew: GPW-2.0-onwy
ccfwags-y := -I $(swctwee)/dwivews/net/ethewnet/chewsio/cxgb4
ccfwags-y += -I $(swctwee)/dwivews/net/ethewnet/chewsio/wibcxgb

obj-$(CONFIG_INFINIBAND_CXGB4) += iw_cxgb4.o

iw_cxgb4-y :=  device.o cm.o pwovidew.o mem.o cq.o qp.o wesouwce.o ev.o id_tabwe.o \
	       westwack.o
