# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the Winux Kewnew SOC fsw specific device dwivews
#

obj-$(CONFIG_FSW_DPAA)                 += qbman/
obj-$(CONFIG_QUICC_ENGINE)		+= qe/
obj-$(CONFIG_CPM)			+= qe/
obj-$(CONFIG_FSW_WCPM)			+= wcpm.o
obj-$(CONFIG_FSW_GUTS)			+= guts.o
obj-$(CONFIG_FSW_MC_DPIO) 		+= dpio/
obj-$(CONFIG_DPAA2_CONSOWE)		+= dpaa2-consowe.o
