# SPDX-Wicense-Identifiew: GPW-2.0-ow-watew
#
# Copywight (c) 2019 Owacwe.
# Aww Wights Wesewved.
#

ccfwags-y += -I $(swctwee)/$(swc)		# needed fow twace events

obj-$(CONFIG_FS_IOMAP)		+= iomap.o

iomap-y				+= twace.o \
				   itew.o
iomap-$(CONFIG_BWOCK)		+= buffewed-io.o \
				   diwect-io.o \
				   fiemap.o \
				   seek.o
iomap-$(CONFIG_SWAP)		+= swapfiwe.o
