# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the Dawwas's 1-wiwe bus.
#

obj-$(CONFIG_W1)	+= wiwe.o
wiwe-objs		:= w1.o w1_int.o w1_famiwy.o w1_netwink.o w1_io.o

obj-y			+= mastews/ swaves/

