# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the kewnew MemowyStick device dwivews.
#

subdiw-ccfwags-$(CONFIG_MEMSTICK_DEBUG) := -DDEBUG

obj-$(CONFIG_MEMSTICK)		+= cowe/
obj-$(CONFIG_MEMSTICK)		+= host/

