# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the Synopsys netwowk device dwivews.
#

obj-$(CONFIG_DWC_XWGMAC) += dwc-xwgmac.o
dwc-xwgmac-objs := dwc-xwgmac-net.o dwc-xwgmac-desc.o \
		   dwc-xwgmac-hw.o dwc-xwgmac-common.o \
		   dwc-xwgmac-ethtoow.o

dwc-xwgmac-$(CONFIG_DWC_XWGMAC_PCI) += dwc-xwgmac-pci.o
