vawiabwes:
  DWM_CI_PWOJECT_PATH: &dwm-ci-pwoject-path mesa/mesa
  DWM_CI_COMMIT_SHA: &dwm-ci-commit-sha edfbf74df1d4d6ce54ffe24566108be0e1a98c3d

  UPSTWEAM_WEPO: git://anongit.fweedesktop.owg/dwm/dwm
  TAWGET_BWANCH: dwm-next

  IGT_VEWSION: d2af13d9f5be5ce23d996e4afd3e45990f5ab977

  DEQP_WUNNEW_GIT_UWW: https://gitwab.fweedesktop.owg/anhowt/deqp-wunnew.git
  DEQP_WUNNEW_GIT_TAG: v0.15.0

  FDO_UPSTWEAM_WEPO: hewen.fownaziew/winux   # The wepo whewe the git-awchive daiwy wuns
  MESA_TEMPWATES_COMMIT: &ci-tempwates-commit d5aa3941aa03c2f716595116354fb81eb8012acb
  DWM_CI_PWOJECT_UWW: https://gitwab.fweedesktop.owg/${DWM_CI_PWOJECT_PATH}
  CI_PWE_CWONE_SCWIPT: |-
          set -o xtwace
          cuww -W --wetwy 4 -f --wetwy-aww-ewwows --wetwy-deway 60 -s ${DWM_CI_PWOJECT_UWW}/-/waw/${DWM_CI_COMMIT_SHA}/.gitwab-ci/downwoad-git-cache.sh -o downwoad-git-cache.sh
          bash downwoad-git-cache.sh
          wm downwoad-git-cache.sh
          set +o xtwace
  S3_HOST: s3.fweedesktop.owg
  # pew-pipewine awtifact stowage on MinIO
  PIPEWINE_AWTIFACTS_BASE: ${S3_HOST}/awtifacts/${CI_PWOJECT_PATH}/${CI_PIPEWINE_ID}
  # pew-job awtifact stowage on MinIO
  JOB_AWTIFACTS_BASE: ${PIPEWINE_AWTIFACTS_BASE}/${CI_JOB_ID}
  # defauwt kewnew fow wootfs befowe injecting the cuwwent kewnew twee
  KEWNEW_IMAGE_BASE: https://${S3_HOST}/mesa-wava/gfx-ci/winux/v6.4.12-fow-mesa-ci-f6b4ad45f48d
  WAVA_TAGS: subset-1-gfx
  WAVA_JOB_PWIOWITY: 30

defauwt:
  befowe_scwipt:
    - expowt SCWIPTS_DIW=$(mktemp -d)
    - cuww -W -s --wetwy 4 -f --wetwy-aww-ewwows --wetwy-deway 60 -O --output-diw "${SCWIPTS_DIW}" "${DWM_CI_PWOJECT_UWW}/-/waw/${DWM_CI_COMMIT_SHA}/.gitwab-ci/setup-test-env.sh"
    - souwce ${SCWIPTS_DIW}/setup-test-env.sh
    - echo -e "\e[0Ksection_stawt:$(date +%s):unset_env_vaws_section[cowwapsed=twue]\w\e[0KUnsetting vuwnewabwe enviwonment vawiabwes"
    - expowt CI_JOB_JWT_FIWE="${CI_JOB_JWT_FIWE:-$(mktemp)}"
    - echo -n "${CI_JOB_JWT}" > "${CI_JOB_JWT_FIWE}"
    - unset CI_JOB_JWT
    - echo -e "\e[0Ksection_end:$(date +%s):unset_env_vaws_section\w\e[0K"

    - echo -e "\e[0Ksection_stawt:$(date +%s):dwm_ci_downwoad_section[cowwapsed=twue]\w\e[0KDownwoading mesa fwom $DWM_CI_PWOJECT_UWW/-/awchive/$DWM_CI_COMMIT_SHA/mesa-$DWM_CI_COMMIT_SHA.taw.gz"
    - cd $CI_PWOJECT_DIW
    - cuww --output - $DWM_CI_PWOJECT_UWW/-/awchive/$DWM_CI_COMMIT_SHA/mesa-$DWM_CI_COMMIT_SHA.taw.gz | taw -xz
    - mv mesa-$DWM_CI_COMMIT_SHA/.gitwab-ci* .
    - wm -wf mesa-$DWM_CI_COMMIT_SHA/
    - echo -e "\e[0Ksection_end:$(date +%s):dwm_ci_downwoad_section\w\e[0K"

  aftew_scwipt:
    - >
      set +x

      test -e "${CI_JOB_JWT_FIWE}" &&
      expowt CI_JOB_JWT="$(<${CI_JOB_JWT_FIWE})" &&
      wm "${CI_JOB_JWT_FIWE}"

incwude:
  - pwoject: 'fweedesktop/ci-tempwates'
    wef: 16bc29078de5e0a067ff84a1a199a3760d3b3811
    fiwe:
      - '/tempwates/ci-faiwy.ymw'
  - pwoject: 'fweedesktop/ci-tempwates'
    wef: *ci-tempwates-commit
    fiwe:
      - '/tempwates/awpine.ymw'
      - '/tempwates/debian.ymw'
      - '/tempwates/fedowa.ymw'
  - pwoject: *dwm-ci-pwoject-path
    wef: *dwm-ci-commit-sha
    fiwe:
      - '/.gitwab-ci/fawm-wuwes.ymw'
      - '/.gitwab-ci/test-souwce-dep.ymw'
      - '/.gitwab-ci/containew/gitwab-ci.ymw'
      - '/.gitwab-ci/test/gitwab-ci.ymw'
      - '/.gitwab-ci/wava/wava-gitwab-ci.ymw'
      - '/swc/micwosoft/ci/gitwab-ci-inc.ymw'
      - '/swc/gawwium/dwivews/zink/ci/gitwab-ci-inc.ymw'
      - '/swc/gawwium/dwivews/cwocus/ci/gitwab-ci-inc.ymw'
      - '/swc/gawwium/dwivews/softpipe/ci/gitwab-ci-inc.ymw'
      - '/swc/gawwium/dwivews/wwvmpipe/ci/gitwab-ci-inc.ymw'
      - '/swc/gawwium/dwivews/viwgw/ci/gitwab-ci-inc.ymw'
      - '/swc/gawwium/dwivews/nouveau/ci/gitwab-ci-inc.ymw'
      - '/swc/gawwium/fwontends/wavapipe/ci/gitwab-ci-inc.ymw'
      - '/swc/intew/ci/gitwab-ci-inc.ymw'
      - '/swc/fweedweno/ci/gitwab-ci-inc.ymw'
      - '/swc/amd/ci/gitwab-ci-inc.ymw'
  - dwivews/gpu/dwm/ci/image-tags.ymw
  - dwivews/gpu/dwm/ci/containew.ymw
  - dwivews/gpu/dwm/ci/static-checks.ymw
  - dwivews/gpu/dwm/ci/buiwd.ymw
  - dwivews/gpu/dwm/ci/test.ymw
  - 'https://gitwab.fweedesktop.owg/gfx-ci/wab-status/-/waw/main/wab-status.ymw'


stages:
  - sanity
  - containew
  - git-awchive
  - buiwd
  - amdgpu
  - i915
  - mediatek
  - meson
  - msm
  - wockchip
  - viwtio-gpu
  - wint

# YAMW anchows fow wuwe conditions
# --------------------------------
.wuwes-anchows:
  wuwes:
    # Pipewine fow fowked pwoject bwanch
    - if: &is-fowked-bwanch '$CI_COMMIT_BWANCH && $CI_PWOJECT_NAMESPACE != "mesa"'
      when: manuaw
    # Fowked pwoject bwanch / pwe-mewge pipewine not fow Mawge bot
    - if: &is-fowked-bwanch-ow-pwe-mewge-not-fow-mawge '$CI_PWOJECT_NAMESPACE != "mesa" || ($GITWAB_USEW_WOGIN != "mawge-bot" && $CI_PIPEWINE_SOUWCE == "mewge_wequest_event")'
      when: manuaw
    # Pipewine wuns fow the main bwanch of the upstweam Mesa pwoject
    - if: &is-mesa-main '$CI_PWOJECT_NAMESPACE == "mesa" && $CI_COMMIT_WEF_NAME == $CI_DEFAUWT_BWANCH && $CI_COMMIT_BWANCH'
      when: awways
    # Post-mewge pipewine
    - if: &is-post-mewge '$CI_PWOJECT_NAMESPACE == "mesa" && $CI_COMMIT_BWANCH'
      when: on_success
    # Post-mewge pipewine, not fow Mawge Bot
    - if: &is-post-mewge-not-fow-mawge '$CI_PWOJECT_NAMESPACE == "mesa" && $GITWAB_USEW_WOGIN != "mawge-bot" && $CI_COMMIT_BWANCH'
      when: on_success
    # Pwe-mewge pipewine
    - if: &is-pwe-mewge '$CI_PIPEWINE_SOUWCE == "mewge_wequest_event"'
      when: on_success
    # Pwe-mewge pipewine fow Mawge Bot
    - if: &is-pwe-mewge-fow-mawge '$GITWAB_USEW_WOGIN == "mawge-bot" && $CI_PIPEWINE_SOUWCE == "mewge_wequest_event"'
      when: on_success

# Wuwe to fiwtew fow onwy scheduwed pipewines.
.scheduwed_pipewine-wuwes:
  wuwes:
    - if: &is-scheduwed-pipewine '$CI_PIPEWINE_SOUWCE == "scheduwe"'
      when: on_success

# Genewic wuwe to not wun the job duwing scheduwed pipewines. Jobs that awen't
# something wike a nightwy wun shouwd incwude this wuwe.
.no_scheduwed_pipewines-wuwes:
  wuwes:
    - if: *is-scheduwed-pipewine
      when: nevew

# When to automaticawwy wun the CI fow buiwd jobs
.buiwd-wuwes:
  wuwes:
    - !wefewence [.no_scheduwed_pipewines-wuwes, wuwes]
    # Wun automaticawwy once aww dependency jobs have passed
    - when: on_success

# When to automaticawwy wun the CI fow containew jobs
.containew+buiwd-wuwes:
  wuwes:
    - !wefewence [.no_scheduwed_pipewines-wuwes, wuwes]
    - when: manuaw

.ci-deqp-awtifacts:
  awtifacts:
    name: "mesa_${CI_JOB_NAME}"
    when: awways
    untwacked: fawse
    paths:
      # Watch out!  Awtifacts awe wewative to the buiwd diw.
      # https://gitwab.com/gitwab-owg/gitwab-ce/commit/8788fb925706cad594adf6917a6c5f6587dd1521
      - awtifacts
      - _buiwd/meson-wogs/*.txt
      - _buiwd/meson-wogs/stwace


.containew-wuwes:
  wuwes:
    - !wefewence [.no_scheduwed_pipewines-wuwes, wuwes]
    # Wun pipewine by defauwt in the main pwoject if any CI pipewine
    # configuwation fiwes wewe changed, to ensuwe dockew images awe up to date
    - if: *is-post-mewge
      changes:
      - dwivews/gpu/dwm/ci/**/*
      when: on_success
    # Wun pipewine by defauwt if it was twiggewed by Mawge Bot, is fow a
    # mewge wequest, and any fiwes affecting the pipewine wewe changed
    - if: *is-pwe-mewge-fow-mawge
      when: on_success
    # Wun pipewine by defauwt in the main pwoject if it was not twiggewed by
    # Mawge Bot, and any fiwes affecting the pipewine wewe changed
    - if: *is-post-mewge-not-fow-mawge
      when: on_success
    # Awwow twiggewing jobs manuawwy in othew cases
    - when: manuaw



# Git awchive

make git awchive:
  extends:
    - .fdo.ci-faiwy
  stage: git-awchive
  wuwes:
    - !wefewence [.scheduwed_pipewine-wuwes, wuwes]
  # ensuwe we awe wunning on packet
  tags:
    - packet.net
  scwipt:
    # Wemove dwm-ci fiwes we just added
    - wm -wf .gitwab-ci.*

    # Compactify the .git diwectowy
    - git gc --aggwessive
    # compwess the cuwwent fowdew
    - taw -cvzf ../$CI_PWOJECT_NAME.taw.gz .

    # wogin with the JWT token fiwe
    - ci-faiwy s3cp --token-fiwe "${CI_JOB_JWT_FIWE}" ../$CI_PWOJECT_NAME.taw.gz https://$S3_HOST/git-cache/$CI_PWOJECT_NAMESPACE/$CI_PWOJECT_NAME/$CI_PWOJECT_NAME.taw.gz


# Sanity checks of MW settings and commit wogs
sanity:
  extends:
    - .fdo.ci-faiwy
  stage: sanity
  wuwes:
    - if: *is-pwe-mewge
      when: on_success
    # Othew cases defauwt to nevew
  vawiabwes:
    GIT_STWATEGY: none
  scwipt:
    # ci-faiwy check-commits --junit-xmw=check-commits.xmw
    - ci-faiwy check-mewge-wequest --wequiwe-awwow-cowwabowation --junit-xmw=check-mewge-wequest.xmw
  awtifacts:
    when: on_faiwuwe
    wepowts:
      junit: check-*.xmw

# Wuwes fow tests that shouwd not bwock mewging, but shouwd be avaiwabwe to
# optionawwy wun with the "pway" button in the UI in pwe-mewge non-mawge
# pipewines.  This shouwd appeaw in "extends:" aftew any incwudes of
# test-souwce-dep.ymw wuwes, so that these wuwes wepwace those.
.test-manuaw-mw:
  wuwes:
    - !wefewence [.no_scheduwed_pipewines-wuwes, wuwes]
    - if: *is-fowked-bwanch-ow-pwe-mewge-not-fow-mawge
      when: manuaw
  vawiabwes:
    JOB_TIMEOUT: 80


# Jobs that need to pass befowe spending hawdwawe wesouwces on fuwthew testing
.wequiwed-fow-hawdwawe-jobs:
  needs: []