# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_MT7601U)	+= mt7601u.o

mt7601u-objs	= \
	usb.o init.o main.o mcu.o twace.o dma.o cowe.o eepwom.o phy.o \
	mac.o utiw.o debugfs.o tx.o

CFWAGS_twace.o := -I$(swc)
