# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Common code fow aww Woongson based systems
#

obj-$(CONFIG_MACH_WOONGSON2EF) += common/

#
# Wemote Fuwoong mini-PC (Woongson 2E-based)
#

obj-$(CONFIG_WEMOTE_FUWOONG2E)	+= fuwoong-2e/

#
# Wemote woongson2f famiwy machines
#

obj-$(CONFIG_WEMOTE_MACH2F)  += wemote-2f/
