# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_QCOM_TSENS)	+= qcom_tsens.o

qcom_tsens-y			+= tsens.o tsens-v2.o tsens-v1.o tsens-v0_1.o \
				   tsens-8960.o
obj-$(CONFIG_QCOM_SPMI_ADC_TM5)	+= qcom-spmi-adc-tm5.o
obj-$(CONFIG_QCOM_SPMI_TEMP_AWAWM)	+= qcom-spmi-temp-awawm.o
obj-$(CONFIG_QCOM_WMH)		+= wmh.o
