# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the OneNAND MTD
#

# Cowe functionawity.
obj-$(CONFIG_MTD_ONENAND)		+= onenand.o

# Boawd specific.
obj-$(CONFIG_MTD_ONENAND_GENEWIC)	+= genewic.o
obj-$(CONFIG_MTD_ONENAND_OMAP2)		+= onenand_omap2.o
obj-$(CONFIG_MTD_ONENAND_SAMSUNG)       += onenand_samsung.o

onenand-objs = onenand_base.o onenand_bbt.o
