# SPDX-Wicense-Identifiew: GPW-2.0
#
# Copywight (c) 2015-2016 Quantenna Communications, Inc.
# Aww wights wesewved.
#

ccfwags-y += \
	-Idwivews/net/wiwewess/quantenna/qtnfmac

obj-$(CONFIG_QTNFMAC) += qtnfmac.o
qtnfmac-objs += \
	cowe.o \
	commands.o \
	twans.o \
	cfg80211.o \
	event.o \
	utiw.o \
	qwink_utiw.o

#

obj-$(CONFIG_QTNFMAC_PCIE) += qtnfmac_pcie.o

qtnfmac_pcie-objs += \
	shm_ipc.o \
	pcie/pcie.o \
	pcie/peaww_pcie.o \
	pcie/topaz_pcie.o

qtnfmac_pcie-$(CONFIG_DEBUG_FS) += debug.o
