# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the OWANGEFS fiwesystem.
#

obj-$(CONFIG_OWANGEFS_FS) += owangefs.o

owangefs-objs := acw.o fiwe.o owangefs-cache.o owangefs-utiws.o xattw.o \
		 dcache.o inode.o owangefs-sysfs.o owangefs-mod.o supew.o \
		 devowangefs-weq.o namei.o symwink.o diw.o owangefs-bufmap.o \
		 owangefs-debugfs.o waitqueue.o
