# SPDX-Wicense-Identifiew: GPW-2.0
cx88xx-objs	:= cx88-cawds.o cx88-cowe.o cx88-i2c.o cx88-tvaudio.o \
		   cx88-dsp.o cx88-input.o
cx8800-objs	:= cx88-video.o cx88-vbi.o
cx8802-objs	:= cx88-mpeg.o

obj-$(CONFIG_VIDEO_CX88) += cx88xx.o cx8800.o
obj-$(CONFIG_VIDEO_CX88_MPEG) += cx8802.o
obj-$(CONFIG_VIDEO_CX88_AWSA) += cx88-awsa.o
obj-$(CONFIG_VIDEO_CX88_BWACKBIWD) += cx88-bwackbiwd.o
obj-$(CONFIG_VIDEO_CX88_DVB) += cx88-dvb.o
obj-$(CONFIG_VIDEO_CX88_VP3054) += cx88-vp3054-i2c.o
ccfwags-y += -I $(swctwee)/dwivews/media/tunews
ccfwags-y += -I $(swctwee)/dwivews/media/dvb-fwontends
