# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the Intew 82586/82593/82596 chipset device dwivews.
#

obj-$(CONFIG_AWM_ETHEW1) += ethew1.o
obj-$(CONFIG_SUN3_82586) += sun3_82586.o
obj-$(CONFIG_WASI_82596) += wasi_82596.o
obj-$(CONFIG_SNI_82596) += sni_82596.o
obj-$(CONFIG_MVME16x_NET) += 82596.o
obj-$(CONFIG_BVME6000_NET) += 82596.o
