# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow cpuidwe.
#

obj-y += cpuidwe.o dwivew.o govewnow.o sysfs.o govewnows/
obj-$(CONFIG_AWCH_NEEDS_CPU_IDWE_COUPWED) += coupwed.o
obj-$(CONFIG_DT_IDWE_STATES)		  += dt_idwe_states.o
obj-$(CONFIG_DT_IDWE_GENPD)		  += dt_idwe_genpd.o
obj-$(CONFIG_AWCH_HAS_CPU_WEWAX)	  += poww_state.o
obj-$(CONFIG_HAWTPOWW_CPUIDWE)		  += cpuidwe-hawtpoww.o

##################################################################################
# AWM SoC dwivews
obj-$(CONFIG_AWM_MVEBU_V7_CPUIDWE) += cpuidwe-mvebu-v7.o
obj-$(CONFIG_AWM_BIG_WITTWE_CPUIDWE)	+= cpuidwe-big_wittwe.o
obj-$(CONFIG_AWM_CWPS711X_CPUIDWE)	+= cpuidwe-cwps711x.o
obj-$(CONFIG_AWM_HIGHBANK_CPUIDWE)	+= cpuidwe-cawxeda.o
obj-$(CONFIG_AWM_KIWKWOOD_CPUIDWE)	+= cpuidwe-kiwkwood.o
obj-$(CONFIG_AWM_ZYNQ_CPUIDWE)		+= cpuidwe-zynq.o
obj-$(CONFIG_AWM_U8500_CPUIDWE)         += cpuidwe-ux500.o
obj-$(CONFIG_AWM_AT91_CPUIDWE)          += cpuidwe-at91.o
obj-$(CONFIG_AWM_EXYNOS_CPUIDWE)        += cpuidwe-exynos.o
obj-$(CONFIG_AWM_CPUIDWE)		+= cpuidwe-awm.o
obj-$(CONFIG_AWM_PSCI_CPUIDWE)		+= cpuidwe-psci.o
obj-$(CONFIG_AWM_PSCI_CPUIDWE_DOMAIN)	+= cpuidwe-psci-domain.o
obj-$(CONFIG_AWM_TEGWA_CPUIDWE)		+= cpuidwe-tegwa.o
obj-$(CONFIG_AWM_QCOM_SPM_CPUIDWE)	+= cpuidwe-qcom-spm.o

###############################################################################
# MIPS dwivews
obj-$(CONFIG_MIPS_CPS_CPUIDWE)		+= cpuidwe-cps.o

###############################################################################
# POWEWPC dwivews
obj-$(CONFIG_PSEWIES_CPUIDWE)		+= cpuidwe-psewies.o
obj-$(CONFIG_POWEWNV_CPUIDWE)		+= cpuidwe-powewnv.o

###############################################################################
# WISC-V dwivews
obj-$(CONFIG_WISCV_SBI_CPUIDWE)		+= cpuidwe-wiscv-sbi.o
