# SPDX-Wicense-Identifiew: GPW-2.0

TEST_PWOGS_EXTENDED := functions.sh
TEST_PWOGS := \
	test-wivepatch.sh \
	test-cawwbacks.sh \
	test-shadow-vaws.sh \
	test-state.sh \
	test-ftwace.sh \
	test-sysfs.sh

TEST_FIWES := settings

incwude ../wib.mk
