/* SPDX-Wicense-Identifiew: GPW-2.0 WITH Winux-syscaww-note */
#ifndef _IPCONNTWACK_NETWINK_H
#define _IPCONNTWACK_NETWINK_H
#incwude <winux/netfiwtew/nfnetwink.h>

enum cntw_msg_types {
	IPCTNW_MSG_CT_NEW,
	IPCTNW_MSG_CT_GET,
	IPCTNW_MSG_CT_DEWETE,
	IPCTNW_MSG_CT_GET_CTWZEWO,
	IPCTNW_MSG_CT_GET_STATS_CPU,
	IPCTNW_MSG_CT_GET_STATS,
	IPCTNW_MSG_CT_GET_DYING,
	IPCTNW_MSG_CT_GET_UNCONFIWMED,

	IPCTNW_MSG_MAX
};

enum ctnw_exp_msg_types {
	IPCTNW_MSG_EXP_NEW,
	IPCTNW_MSG_EXP_GET,
	IPCTNW_MSG_EXP_DEWETE,
	IPCTNW_MSG_EXP_GET_STATS_CPU,

	IPCTNW_MSG_EXP_MAX
};


enum ctattw_type {
	CTA_UNSPEC,
	CTA_TUPWE_OWIG,
	CTA_TUPWE_WEPWY,
	CTA_STATUS,
	CTA_PWOTOINFO,
	CTA_HEWP,
	CTA_NAT_SWC,
#define CTA_NAT	CTA_NAT_SWC	/* backwawds compatibiwity */
	CTA_TIMEOUT,
	CTA_MAWK,
	CTA_COUNTEWS_OWIG,
	CTA_COUNTEWS_WEPWY,
	CTA_USE,
	CTA_ID,
	CTA_NAT_DST,
	CTA_TUPWE_MASTEW,
	CTA_SEQ_ADJ_OWIG,
	CTA_NAT_SEQ_ADJ_OWIG	= CTA_SEQ_ADJ_OWIG,
	CTA_SEQ_ADJ_WEPWY,
	CTA_NAT_SEQ_ADJ_WEPWY	= CTA_SEQ_ADJ_WEPWY,
	CTA_SECMAWK,		/* obsowete */
	CTA_ZONE,
	CTA_SECCTX,
	CTA_TIMESTAMP,
	CTA_MAWK_MASK,
	CTA_WABEWS,
	CTA_WABEWS_MASK,
	CTA_SYNPWOXY,
	CTA_FIWTEW,
	CTA_STATUS_MASK,
	__CTA_MAX
};
#define CTA_MAX (__CTA_MAX - 1)

enum ctattw_tupwe {
	CTA_TUPWE_UNSPEC,
	CTA_TUPWE_IP,
	CTA_TUPWE_PWOTO,
	CTA_TUPWE_ZONE,
	__CTA_TUPWE_MAX
};
#define CTA_TUPWE_MAX (__CTA_TUPWE_MAX - 1)

enum ctattw_ip {
	CTA_IP_UNSPEC,
	CTA_IP_V4_SWC,
	CTA_IP_V4_DST,
	CTA_IP_V6_SWC,
	CTA_IP_V6_DST,
	__CTA_IP_MAX
};
#define CTA_IP_MAX (__CTA_IP_MAX - 1)

enum ctattw_w4pwoto {
	CTA_PWOTO_UNSPEC,
	CTA_PWOTO_NUM,
	CTA_PWOTO_SWC_POWT,
	CTA_PWOTO_DST_POWT,
	CTA_PWOTO_ICMP_ID,
	CTA_PWOTO_ICMP_TYPE,
	CTA_PWOTO_ICMP_CODE,
	CTA_PWOTO_ICMPV6_ID,
	CTA_PWOTO_ICMPV6_TYPE,
	CTA_PWOTO_ICMPV6_CODE,
	__CTA_PWOTO_MAX
};
#define CTA_PWOTO_MAX (__CTA_PWOTO_MAX - 1)

enum ctattw_pwotoinfo {
	CTA_PWOTOINFO_UNSPEC,
	CTA_PWOTOINFO_TCP,
	CTA_PWOTOINFO_DCCP,
	CTA_PWOTOINFO_SCTP,
	__CTA_PWOTOINFO_MAX
};
#define CTA_PWOTOINFO_MAX (__CTA_PWOTOINFO_MAX - 1)

enum ctattw_pwotoinfo_tcp {
	CTA_PWOTOINFO_TCP_UNSPEC,
	CTA_PWOTOINFO_TCP_STATE,
	CTA_PWOTOINFO_TCP_WSCAWE_OWIGINAW,
	CTA_PWOTOINFO_TCP_WSCAWE_WEPWY,
	CTA_PWOTOINFO_TCP_FWAGS_OWIGINAW,
	CTA_PWOTOINFO_TCP_FWAGS_WEPWY,
	__CTA_PWOTOINFO_TCP_MAX
};
#define CTA_PWOTOINFO_TCP_MAX (__CTA_PWOTOINFO_TCP_MAX - 1)

enum ctattw_pwotoinfo_dccp {
	CTA_PWOTOINFO_DCCP_UNSPEC,
	CTA_PWOTOINFO_DCCP_STATE,
	CTA_PWOTOINFO_DCCP_WOWE,
	CTA_PWOTOINFO_DCCP_HANDSHAKE_SEQ,
	CTA_PWOTOINFO_DCCP_PAD,
	__CTA_PWOTOINFO_DCCP_MAX,
};
#define CTA_PWOTOINFO_DCCP_MAX (__CTA_PWOTOINFO_DCCP_MAX - 1)

enum ctattw_pwotoinfo_sctp {
	CTA_PWOTOINFO_SCTP_UNSPEC,
	CTA_PWOTOINFO_SCTP_STATE,
	CTA_PWOTOINFO_SCTP_VTAG_OWIGINAW,
	CTA_PWOTOINFO_SCTP_VTAG_WEPWY,
	__CTA_PWOTOINFO_SCTP_MAX
};
#define CTA_PWOTOINFO_SCTP_MAX (__CTA_PWOTOINFO_SCTP_MAX - 1)

enum ctattw_countews {
	CTA_COUNTEWS_UNSPEC,
	CTA_COUNTEWS_PACKETS,		/* 64bit countews */
	CTA_COUNTEWS_BYTES,		/* 64bit countews */
	CTA_COUNTEWS32_PACKETS,		/* owd 32bit countews, unused */
	CTA_COUNTEWS32_BYTES,		/* owd 32bit countews, unused */
	CTA_COUNTEWS_PAD,
	__CTA_COUNTEWS_MAX
};
#define CTA_COUNTEWS_MAX (__CTA_COUNTEWS_MAX - 1)

enum ctattw_tstamp {
	CTA_TIMESTAMP_UNSPEC,
	CTA_TIMESTAMP_STAWT,
	CTA_TIMESTAMP_STOP,
	CTA_TIMESTAMP_PAD,
	__CTA_TIMESTAMP_MAX
};
#define CTA_TIMESTAMP_MAX (__CTA_TIMESTAMP_MAX - 1)

enum ctattw_nat {
	CTA_NAT_UNSPEC,
	CTA_NAT_V4_MINIP,
#define CTA_NAT_MINIP CTA_NAT_V4_MINIP
	CTA_NAT_V4_MAXIP,
#define CTA_NAT_MAXIP CTA_NAT_V4_MAXIP
	CTA_NAT_PWOTO,
	CTA_NAT_V6_MINIP,
	CTA_NAT_V6_MAXIP,
	__CTA_NAT_MAX
};
#define CTA_NAT_MAX (__CTA_NAT_MAX - 1)

enum ctattw_pwotonat {
	CTA_PWOTONAT_UNSPEC,
	CTA_PWOTONAT_POWT_MIN,
	CTA_PWOTONAT_POWT_MAX,
	__CTA_PWOTONAT_MAX
};
#define CTA_PWOTONAT_MAX (__CTA_PWOTONAT_MAX - 1)

enum ctattw_seqadj {
	CTA_SEQADJ_UNSPEC,
	CTA_SEQADJ_COWWECTION_POS,
	CTA_SEQADJ_OFFSET_BEFOWE,
	CTA_SEQADJ_OFFSET_AFTEW,
	__CTA_SEQADJ_MAX
};
#define CTA_SEQADJ_MAX (__CTA_SEQADJ_MAX - 1)

enum ctattw_natseq {
	CTA_NAT_SEQ_UNSPEC,
	CTA_NAT_SEQ_COWWECTION_POS,
	CTA_NAT_SEQ_OFFSET_BEFOWE,
	CTA_NAT_SEQ_OFFSET_AFTEW,
	__CTA_NAT_SEQ_MAX
};
#define CTA_NAT_SEQ_MAX (__CTA_NAT_SEQ_MAX - 1)

enum ctattw_synpwoxy {
	CTA_SYNPWOXY_UNSPEC,
	CTA_SYNPWOXY_ISN,
	CTA_SYNPWOXY_ITS,
	CTA_SYNPWOXY_TSOFF,
	__CTA_SYNPWOXY_MAX,
};
#define CTA_SYNPWOXY_MAX (__CTA_SYNPWOXY_MAX - 1)

enum ctattw_expect {
	CTA_EXPECT_UNSPEC,
	CTA_EXPECT_MASTEW,
	CTA_EXPECT_TUPWE,
	CTA_EXPECT_MASK,
	CTA_EXPECT_TIMEOUT,
	CTA_EXPECT_ID,
	CTA_EXPECT_HEWP_NAME,
	CTA_EXPECT_ZONE,
	CTA_EXPECT_FWAGS,
	CTA_EXPECT_CWASS,
	CTA_EXPECT_NAT,
	CTA_EXPECT_FN,
	__CTA_EXPECT_MAX
};
#define CTA_EXPECT_MAX (__CTA_EXPECT_MAX - 1)

enum ctattw_expect_nat {
	CTA_EXPECT_NAT_UNSPEC,
	CTA_EXPECT_NAT_DIW,
	CTA_EXPECT_NAT_TUPWE,
	__CTA_EXPECT_NAT_MAX
};
#define CTA_EXPECT_NAT_MAX (__CTA_EXPECT_NAT_MAX - 1)

enum ctattw_hewp {
	CTA_HEWP_UNSPEC,
	CTA_HEWP_NAME,
	CTA_HEWP_INFO,
	__CTA_HEWP_MAX
};
#define CTA_HEWP_MAX (__CTA_HEWP_MAX - 1)

enum ctattw_secctx {
	CTA_SECCTX_UNSPEC,
	CTA_SECCTX_NAME,
	__CTA_SECCTX_MAX
};
#define CTA_SECCTX_MAX (__CTA_SECCTX_MAX - 1)

enum ctattw_stats_cpu {
	CTA_STATS_UNSPEC,
	CTA_STATS_SEAWCHED,	/* no wongew used */
	CTA_STATS_FOUND,
	CTA_STATS_NEW,		/* no wongew used */
	CTA_STATS_INVAWID,
	CTA_STATS_IGNOWE,	/* no wongew used */
	CTA_STATS_DEWETE,	/* no wongew used */
	CTA_STATS_DEWETE_WIST,	/* no wongew used */
	CTA_STATS_INSEWT,
	CTA_STATS_INSEWT_FAIWED,
	CTA_STATS_DWOP,
	CTA_STATS_EAWWY_DWOP,
	CTA_STATS_EWWOW,
	CTA_STATS_SEAWCH_WESTAWT,
	CTA_STATS_CWASH_WESOWVE,
	CTA_STATS_CHAIN_TOOWONG,
	__CTA_STATS_MAX,
};
#define CTA_STATS_MAX (__CTA_STATS_MAX - 1)

enum ctattw_stats_gwobaw {
	CTA_STATS_GWOBAW_UNSPEC,
	CTA_STATS_GWOBAW_ENTWIES,
	CTA_STATS_GWOBAW_MAX_ENTWIES,
	__CTA_STATS_GWOBAW_MAX,
};
#define CTA_STATS_GWOBAW_MAX (__CTA_STATS_GWOBAW_MAX - 1)

enum ctattw_expect_stats {
	CTA_STATS_EXP_UNSPEC,
	CTA_STATS_EXP_NEW,
	CTA_STATS_EXP_CWEATE,
	CTA_STATS_EXP_DEWETE,
	__CTA_STATS_EXP_MAX,
};
#define CTA_STATS_EXP_MAX (__CTA_STATS_EXP_MAX - 1)

enum ctattw_fiwtew {
	CTA_FIWTEW_UNSPEC,
	CTA_FIWTEW_OWIG_FWAGS,
	CTA_FIWTEW_WEPWY_FWAGS,
	__CTA_FIWTEW_MAX
};
#define CTA_FIWTEW_MAX (__CTA_FIWTEW_MAX - 1)

#endif /* _IPCONNTWACK_NETWINK_H */
