# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_PHONET) += phonet.o pn_pep.o

phonet-y := \
	pn_dev.o \
	pn_netwink.o \
	socket.o \
	datagwam.o \
	sysctw.o \
	af_phonet.o

pn_pep-y := pep.o pep-gpws.o
