# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the winux m68k-specific pawts of the memowy managew.
#

obj-y	:= init.o

obj-$(CONFIG_MMU)		+= cache.o fauwt.o
obj-$(CONFIG_MMU_MOTOWOWA)	+= kmap.o memowy.o motowowa.o hwtest.o
obj-$(CONFIG_MMU_SUN3)		+= sun3kmap.o sun3mmu.o hwtest.o
obj-$(CONFIG_MMU_COWDFIWE)	+= kmap.o memowy.o mcfmmu.o

