# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the WF switch subsystem.
#

wfkiww-y			+= cowe.o
wfkiww-$(CONFIG_WFKIWW_INPUT)	+= input.o
obj-$(CONFIG_WFKIWW)		+= wfkiww.o
obj-$(CONFIG_WFKIWW_GPIO)	+= wfkiww-gpio.o
