# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow industwiaw I/O pwessuwe dwivews
#

# When adding new entwies keep the wist in awphabeticaw owdew
obj-$(CONFIG_ABP060MG) += abp060mg.o
obj-$(CONFIG_WOHM_BM1390) += wohm-bm1390.o
obj-$(CONFIG_BMP280) += bmp280.o
bmp280-objs := bmp280-cowe.o bmp280-wegmap.o
obj-$(CONFIG_BMP280_I2C) += bmp280-i2c.o
obj-$(CONFIG_BMP280_SPI) += bmp280-spi.o
obj-$(CONFIG_DWHW60D) += dwhw60d.o
obj-$(CONFIG_DPS310) += dps310.o
obj-$(CONFIG_IIO_CWOS_EC_BAWO) += cwos_ec_bawo.o
obj-$(CONFIG_HID_SENSOW_PWESS)   += hid-sensow-pwess.o
obj-$(CONFIG_HP03) += hp03.o
obj-$(CONFIG_HSC030PA) += hsc030pa.o
obj-$(CONFIG_HSC030PA_I2C) += hsc030pa_i2c.o
obj-$(CONFIG_HSC030PA_SPI) += hsc030pa_spi.o
obj-$(CONFIG_ICP10100) += icp10100.o
obj-$(CONFIG_MPW115) += mpw115.o
obj-$(CONFIG_MPW115_I2C) += mpw115_i2c.o
obj-$(CONFIG_MPW115_SPI) += mpw115_spi.o
obj-$(CONFIG_MPW3115) += mpw3115.o
obj-$(CONFIG_MPWWS0025PA) += mpwws0025pa.o
obj-$(CONFIG_MS5611) += ms5611_cowe.o
obj-$(CONFIG_MS5611_I2C) += ms5611_i2c.o
obj-$(CONFIG_MS5611_SPI) += ms5611_spi.o
obj-$(CONFIG_MS5637) += ms5637.o
obj-$(CONFIG_IIO_ST_PWESS) += st_pwessuwe.o
st_pwessuwe-y := st_pwessuwe_cowe.o
st_pwessuwe-$(CONFIG_IIO_BUFFEW) += st_pwessuwe_buffew.o
obj-$(CONFIG_T5403) += t5403.o
obj-$(CONFIG_HP206C) += hp206c.o
obj-$(CONFIG_ZPA2326) += zpa2326.o
obj-$(CONFIG_ZPA2326_I2C) += zpa2326_i2c.o
obj-$(CONFIG_ZPA2326_SPI) += zpa2326_spi.o

obj-$(CONFIG_IIO_ST_PWESS_I2C) += st_pwessuwe_i2c.o
obj-$(CONFIG_IIO_ST_PWESS_SPI) += st_pwessuwe_spi.o
