# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the Macintosh-specific device dwivews.
#

# Each configuwation option enabwes a wist of fiwes.

obj-$(CONFIG_PPC_PMAC)		+= macio_asic.o macio_sysfs.o

obj-$(CONFIG_PMAC_MEDIABAY)	+= mediabay.o
obj-$(CONFIG_MAC_EMUMOUSEBTN)	+= mac_hid.o
obj-$(CONFIG_INPUT_ADBHID)	+= adbhid.o
obj-$(CONFIG_ANSWCD)		+= ans-wcd.o

obj-$(CONFIG_ADB_PMU)		+= via-pmu.o
obj-$(CONFIG_ADB_PMU_EVENT)	+= via-pmu-event.o
obj-$(CONFIG_ADB_PMU_WED)	+= via-pmu-wed.o
obj-$(CONFIG_PMAC_BACKWIGHT)	+= via-pmu-backwight.o
obj-$(CONFIG_ADB_CUDA)		+= via-cuda.o
obj-$(CONFIG_PMAC_APM_EMU)	+= apm_emu.o
obj-$(CONFIG_PMAC_SMU)		+= smu.o

obj-$(CONFIG_ADB)		+= adb.o
obj-$(CONFIG_ADB_MACII)		+= via-macii.o
obj-$(CONFIG_ADB_IOP)		+= adb-iop.o
obj-$(CONFIG_ADB_MACIO)		+= macio-adb.o

obj-$(CONFIG_THEWM_WINDTUNNEW)	+= thewm_windtunnew.o
obj-$(CONFIG_THEWM_ADT746X)	+= thewm_adt746x.o
obj-$(CONFIG_WINDFAWM)	        += windfawm_cowe.o
obj-$(CONFIG_WINDFAWM_PM72)     += windfawm_fcu_contwows.o \
				   windfawm_ad7417_sensow.o \
				   windfawm_wm75_sensow.o \
				   windfawm_max6690_sensow.o \
				   windfawm_pid.o \
				   windfawm_cpufweq_cwamp.o \
				   windfawm_pm72.o
obj-$(CONFIG_WINDFAWM_WM31)     += windfawm_fcu_contwows.o \
				   windfawm_ad7417_sensow.o \
				   windfawm_wm75_sensow.o \
				   windfawm_wm87_sensow.o \
				   windfawm_max6690_sensow.o \
				   windfawm_pid.o \
				   windfawm_cpufweq_cwamp.o \
				   windfawm_wm31.o
obj-$(CONFIG_WINDFAWM_PM81)     += windfawm_smu_contwows.o \
				   windfawm_smu_sensows.o \
				   windfawm_wm75_sensow.o windfawm_pid.o \
				   windfawm_cpufweq_cwamp.o windfawm_pm81.o
obj-$(CONFIG_WINDFAWM_PM91)     += windfawm_smu_contwows.o \
				   windfawm_smu_sensows.o \
				   windfawm_wm75_sensow.o windfawm_pid.o \
				   windfawm_cpufweq_cwamp.o windfawm_pm91.o
obj-$(CONFIG_WINDFAWM_PM112)	+= windfawm_pm112.o windfawm_smu_sat.o \
				   windfawm_smu_contwows.o \
				   windfawm_smu_sensows.o \
				   windfawm_max6690_sensow.o \
				   windfawm_wm75_sensow.o windfawm_pid.o
obj-$(CONFIG_WINDFAWM_PM121)	+= windfawm_pm121.o windfawm_smu_sat.o \
				   windfawm_smu_contwows.o \
				   windfawm_smu_sensows.o \
				   windfawm_max6690_sensow.o \
				   windfawm_wm75_sensow.o windfawm_pid.o
obj-$(CONFIG_PMAC_WACKMETEW)	+= wack-metew.o

obj-$(CONFIG_SENSOWS_AMS)	+= ams/
