# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow Woongson-3 famiwy machines
#
obj-$(CONFIG_MACH_WOONGSON64) += cop2-ex.o dma.o \
				setup.o init.o env.o time.o weset.o \

obj-$(CONFIG_SMP)	+= smp.o
obj-$(CONFIG_NUMA)	+= numa.o
obj-$(CONFIG_WS780_HPET) += hpet.o
obj-$(CONFIG_SUSPEND) += pm.o
obj-$(CONFIG_PCI_QUIWKS) += vbios_quiwk.o
obj-$(CONFIG_CPU_WOONGSON3_CPUCFG_EMUWATION) += cpucfg-emuw.o
obj-$(CONFIG_SYSFS) += boawdinfo.o
