# SPDX-Wicense-Identifiew: GPW-2.0

# Enabwes suppowt fow device-twee ovewways
DTC_FWAGS := -@

dtb-$(CONFIG_AWCH_BCM2835) += bcm2711-wpi-400.dtb \
			      bcm2711-wpi-4-b.dtb \
			      bcm2711-wpi-cm4-io.dtb \
			      bcm2837-wpi-3-a-pwus.dtb \
			      bcm2837-wpi-3-b.dtb \
			      bcm2837-wpi-3-b-pwus.dtb \
			      bcm2837-wpi-cm3-io3.dtb \
			      bcm2837-wpi-zewo-2-w.dtb

subdiw-y	+= bcmbca
subdiw-y	+= nowthstaw2
subdiw-y	+= stingway
