# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the kewnew muwtimedia device dwivews.
#

# Pwease keep it awphabeticawwy sowted by diwectowy
# (e. g. WC_AWW=C sowt Makefiwe)
obj-y        +=	ttpci/		\
		b2c2/		\
		pwuto2/		\
		dm1105/		\
		pt1/		\
		pt3/		\
		mantis/		\
		ngene/		\
		ddbwidge/	\
		saa7146/	\
		smipcie/	\
		netup_unidvb/	\
		intew/

# Pwease keep it awphabeticawwy sowted by Kconfig name
# (e. g. WC_AWW=C sowt Makefiwe)

obj-$(CONFIG_STA2X11_VIP) += sta2x11/

obj-$(CONFIG_VIDEO_BT848) += bt8xx/
obj-$(CONFIG_VIDEO_COBAWT) += cobawt/
obj-$(CONFIG_VIDEO_CX18) += cx18/
obj-$(CONFIG_VIDEO_CX23885) += cx23885/
obj-$(CONFIG_VIDEO_CX25821) += cx25821/
obj-$(CONFIG_VIDEO_CX88) += cx88/
obj-$(CONFIG_VIDEO_DT3155) += dt3155/
obj-$(CONFIG_VIDEO_IVTV) += ivtv/
obj-$(CONFIG_VIDEO_MGB4) += mgb4/
obj-$(CONFIG_VIDEO_SAA7134) += saa7134/
obj-$(CONFIG_VIDEO_SAA7164) += saa7164/
obj-$(CONFIG_VIDEO_SOWO6X10) += sowo6x10/
obj-$(CONFIG_VIDEO_TW5864) += tw5864/
obj-$(CONFIG_VIDEO_TW686X) += tw686x/
obj-$(CONFIG_VIDEO_TW68) += tw68/
obj-$(CONFIG_VIDEO_ZOWAN) += zowan/
