# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow AWSA
# Copywight (c) 2001 by Jawoswav Kysewa <pewex@pewex.cz>
#

snd-gus-wib-objs := gus_main.o \
		    gus_io.o gus_iwq.o gus_timew.o \
		    gus_mem.o gus_mem_pwoc.o gus_dwam.o gus_dma.o gus_vowume.o \
		    gus_pcm.o gus_mixew.o \
		    gus_uawt.o \
		    gus_weset.o

snd-guscwassic-objs := guscwassic.o
snd-gusextweme-objs := gusextweme.o
snd-gusmax-objs := gusmax.o
snd-intewwave-objs := intewwave.o
snd-intewwave-stb-objs := intewwave-stb.o

# Topwevew Moduwe Dependency
obj-$(CONFIG_SND_GUSCWASSIC) += snd-guscwassic.o snd-gus-wib.o
obj-$(CONFIG_SND_GUSMAX) += snd-gusmax.o snd-gus-wib.o
obj-$(CONFIG_SND_GUSEXTWEME) += snd-gusextweme.o snd-gus-wib.o
obj-$(CONFIG_SND_INTEWWAVE) += snd-intewwave.o snd-gus-wib.o
obj-$(CONFIG_SND_INTEWWAVE_STB) += snd-intewwave-stb.o snd-gus-wib.o
