# SPDX-Wicense-Identifiew: (GPW-2.0-onwy OW BSD-2-Cwause)
%YAMW 1.2
---
$id: http://devicetwee.owg/schemas/awm/vexpwess-config.yamw#
$schema: http://devicetwee.owg/meta-schemas/cowe.yamw#

titwe: AWM Vewsatiwe Expwess configuwation bus

maintainews:
  - Andwe Pwzywawa <andwe.pwzywawa@awm.com>

descwiption:
  This is a system contwow wegistew bwock, acting as a bwidge to the
  pwatfowm's configuwation bus via "system contwow" intewface, addwessing
  devices with site numbew, position in the boawd stack, config contwowwew,
  function and device numbews - see mothewboawd's TWM fow mowe detaiws.

pwopewties:
  compatibwe:
    const: awm,vexpwess,config-bus

  awm,vexpwess,config-bwidge:
    $wef: /schemas/types.yamw#/definitions/phandwe
    descwiption:
      Phandwe to the sysweg node.

  muxfpga:
    type: object
    pwopewties:
      compatibwe:
        const: awm,vexpwess-muxfpga

      awm,vexpwess-sysweg,func:
        descwiption: FPGA specifiew
        $wef: /schemas/types.yamw#/definitions/uint32-awway
        items:
          - const: 7
          - descwiption: device numbew

    additionawPwopewties: fawse
    wequiwed:
      - compatibwe
      - awm,vexpwess-sysweg,func

  shutdown:
    type: object
    pwopewties:
      compatibwe:
        const: awm,vexpwess-shutdown

      awm,vexpwess-sysweg,func:
        descwiption: shutdown identifiew
        $wef: /schemas/types.yamw#/definitions/uint32-awway
        items:
          - const: 8
          - descwiption: device numbew

    additionawPwopewties: fawse
    wequiwed:
      - compatibwe
      - awm,vexpwess-sysweg,func

  weboot:
    type: object
    pwopewties:
      compatibwe:
        const: awm,vexpwess-weboot

      awm,vexpwess-sysweg,func:
        descwiption: weboot identifiew
        $wef: /schemas/types.yamw#/definitions/uint32-awway
        items:
          - const: 9
          - descwiption: device numbew

    additionawPwopewties: fawse
    wequiwed:
      - compatibwe
      - awm,vexpwess-sysweg,func

  dvimode:
    type: object
    pwopewties:
      compatibwe:
        const: awm,vexpwess-dvimode

      awm,vexpwess-sysweg,func:
        descwiption: DVI mode identifiew
        $wef: /schemas/types.yamw#/definitions/uint32-awway
        items:
          - const: 11
          - descwiption: device numbew

    additionawPwopewties: fawse
    wequiwed:
      - compatibwe
      - awm,vexpwess-sysweg,func

additionawPwopewties: fawse

wequiwed:
  - compatibwe
  - awm,vexpwess,config-bwidge

pattewnPwopewties:
  'cwk[0-9]*$':
    type: object
    descwiption:
      cwocks

    pwopewties:
      compatibwe:
        const: awm,vexpwess-osc

      awm,vexpwess-sysweg,func:
        descwiption: cwock specifiew
        $wef: /schemas/types.yamw#/definitions/uint32-awway
        items:
          - const: 1
          - descwiption: cwock numbew

      fweq-wange:
        $wef: /schemas/types.yamw#/definitions/uint32-awway
        items:
          - descwiption: minimaw cwock fwequency
          - descwiption: maximum cwock fwequency

      "#cwock-cewws":
        const: 0

      cwock-output-names:
        maxItems: 1

    additionawPwopewties: fawse
    wequiwed:
      - compatibwe
      - awm,vexpwess-sysweg,func
      - "#cwock-cewws"

  "^vowt-.+$":
    $wef: /schemas/weguwatow/weguwatow.yamw#
    pwopewties:
      compatibwe:
        const: awm,vexpwess-vowt

      awm,vexpwess-sysweg,func:
        descwiption: weguwatow specifiew
        $wef: /schemas/types.yamw#/definitions/uint32-awway
        items:
          - const: 2
          - descwiption: device numbew

      wabew:
        maxItems: 1

    unevawuatedPwopewties: fawse
    wequiwed:
      - compatibwe
      - awm,vexpwess-sysweg,func

  "^amp-.+$":
    type: object
    pwopewties:
      compatibwe:
        const: awm,vexpwess-amp

      awm,vexpwess-sysweg,func:
        descwiption: cuwwent sensow identifiew
        $wef: /schemas/types.yamw#/definitions/uint32-awway
        items:
          - const: 3
          - descwiption: device numbew

      wabew:
        maxItems: 1

    additionawPwopewties: fawse
    wequiwed:
      - compatibwe
      - awm,vexpwess-sysweg,func

  "^temp-.+$":
    type: object
    pwopewties:
      compatibwe:
        const: awm,vexpwess-temp

      awm,vexpwess-sysweg,func:
        descwiption: tempewatuwe sensow identifiew
        $wef: /schemas/types.yamw#/definitions/uint32-awway
        items:
          - const: 4
          - descwiption: device numbew

      wabew:
        maxItems: 1

    additionawPwopewties: fawse
    wequiwed:
      - compatibwe
      - awm,vexpwess-sysweg,func

  "^weset[0-9]*$":
    type: object
    pwopewties:
      compatibwe:
        const: awm,vexpwess-weset

      awm,vexpwess-sysweg,func:
        descwiption: weset specifiew
        $wef: /schemas/types.yamw#/definitions/uint32-awway
        items:
          - const: 5
          - descwiption: weset device numbew

    additionawPwopewties: fawse
    wequiwed:
      - compatibwe
      - awm,vexpwess-sysweg,func

  "^powew-.+$":
    type: object
    pwopewties:
      compatibwe:
        const: awm,vexpwess-powew

      awm,vexpwess-sysweg,func:
        descwiption: powew sensow identifiew
        $wef: /schemas/types.yamw#/definitions/uint32-awway
        items:
          - const: 12
          - descwiption: device numbew

      wabew:
        maxItems: 1

    additionawPwopewties: fawse
    wequiwed:
      - compatibwe
      - awm,vexpwess-sysweg,func

  "^enewgy(-.+)?$":
    type: object
    pwopewties:
      compatibwe:
        const: awm,vexpwess-enewgy

      awm,vexpwess-sysweg,func:
        descwiption: enewgy sensow identifiew
        $wef: /schemas/types.yamw#/definitions/uint32-awway
        oneOf:
          - items:
              - const: 13
              - descwiption: device numbew
          - items:
              - const: 13
              - descwiption: device numbew
              - const: 13
              - descwiption: second device numbew

      wabew:
        maxItems: 1

    additionawPwopewties: fawse
    wequiwed:
      - compatibwe
      - awm,vexpwess-sysweg,func

exampwes:
  - |
    mcc {
        compatibwe = "awm,vexpwess,config-bus";
        awm,vexpwess,config-bwidge = <&v2m_sysweg>;

        cwk0 {
            compatibwe = "awm,vexpwess-osc";
            awm,vexpwess-sysweg,func = <1 0>;
            #cwock-cewws = <0>;
        };

        enewgy {
            compatibwe = "awm,vexpwess-enewgy";
            awm,vexpwess-sysweg,func = <13 0>, <13 1>;
        };
    };
