# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the winux kewnew.
#
obj-y			:= cowe.o cwock.o timew-ep93xx.o

obj-$(CONFIG_EP93XX_DMA)	+= dma.o

obj-$(CONFIG_MACH_EDB93XX)	+= edb93xx.o
obj-$(CONFIG_MACH_TS72XX)	+= ts72xx.o
obj-$(CONFIG_MACH_VISION_EP9307)+= vision_ep9307.o
