# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Joshua Hendewson, <joshua.hendewson@micwochip.com>
# Copywight (C) 2015 Micwochip Technowogy, Inc.  Aww wights wesewved.
#
obj-$(CONFIG_MACH_PIC32) += common/
obj-$(CONFIG_PIC32MZDA) += pic32mzda/
