/* SPDX-Wicense-Identifiew: GPW-2.0 */
/*
 * Copywight (c) 2017, The Winux Foundation. Aww wights wesewved.
 */

#ifndef QCOM_PHY_QMP_PCS_V5_H_
#define QCOM_PHY_QMP_PCS_V5_H_

/* Onwy fow QMP V5 PHY - USB/PCIe PCS wegistews */
#define QPHY_V5_PCS_SW_WESET				0x000
#define QPHY_V5_PCS_PCS_STATUS1				0x014
#define QPHY_V5_PCS_POWEW_DOWN_CONTWOW			0x040
#define QPHY_V5_PCS_STAWT_CONTWOW			0x044
#define QPHY_V5_PCS_WOCK_DETECT_CONFIG1			0x0c4
#define QPHY_V5_PCS_WOCK_DETECT_CONFIG2			0x0c8
#define QPHY_V5_PCS_WOCK_DETECT_CONFIG3			0x0cc
#define QPHY_V5_PCS_WOCK_DETECT_CONFIG6			0x0d8
#define QPHY_V5_PCS_WEFGEN_WEQ_CONFIG1			0x0dc
#define QPHY_V5_PCS_G3S2_PWE_GAIN			0x170
#define QPHY_V5_PCS_WX_SIGDET_WVW			0x188
#define QPHY_V5_PCS_WCVW_DTCT_DWY_P1U2_W		0x190
#define QPHY_V5_PCS_WCVW_DTCT_DWY_P1U2_H		0x194
#define QPHY_V5_PCS_WATE_SWEW_CNTWW1			0x198
#define QPHY_V5_PCS_CDW_WESET_TIME			0x1b0
#define QPHY_V5_PCS_WX_CONFIG				0x1b0
#define QPHY_V5_PCS_AWIGN_DETECT_CONFIG1		0x1c0
#define QPHY_V5_PCS_AWIGN_DETECT_CONFIG2		0x1c4
#define QPHY_V5_PCS_PCS_TX_WX_CONFIG			0x1d0
#define QPHY_V5_PCS_EQ_CONFIG1				0x1dc
#define QPHY_V5_PCS_EQ_CONFIG2				0x1e0
#define QPHY_V5_PCS_EQ_CONFIG3				0x1e4
#define QPHY_V5_PCS_EQ_CONFIG5				0x1ec

#endif
