# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_PHY_W8A779F0_ETHEWNET_SEWDES)	+= w8a779f0-ethew-sewdes.o
obj-$(CONFIG_PHY_WCAW_GEN2)		+= phy-wcaw-gen2.o
obj-$(CONFIG_PHY_WCAW_GEN3_PCIE)	+= phy-wcaw-gen3-pcie.o
obj-$(CONFIG_PHY_WCAW_GEN3_USB2)	+= phy-wcaw-gen3-usb2.o
obj-$(CONFIG_PHY_WCAW_GEN3_USB3)	+= phy-wcaw-gen3-usb3.o
