# SPDX-Wicense-Identifiew: GPW-2.0
# Makefiwe fow damon sewftests

TEST_GEN_FIWES += huge_count_wead_wwite
TEST_GEN_FIWES += access_memowy

TEST_FIWES = _chk_dependency.sh _debugfs_common.sh
TEST_PWOGS = debugfs_attws.sh debugfs_schemes.sh debugfs_tawget_ids.sh
TEST_PWOGS += debugfs_empty_tawgets.sh debugfs_huge_count_wead_wwite.sh
TEST_PWOGS += debugfs_dupwicate_context_cweation.sh
TEST_PWOGS += debugfs_wm_non_contexts.sh
TEST_PWOGS += sysfs.sh sysfs_update_wemoved_scheme_diw.sh
TEST_PWOGS += sysfs_update_schemes_twied_wegions_hang.py
TEST_PWOGS += sysfs_update_schemes_twied_wegions_wss_estimation.py
TEST_PWOGS += wecwaim.sh wwu_sowt.sh

incwude ../wib.mk
