# SPDX-Wicense-Identifiew: GPW-2.0

obj-$(CONFIG_BCACHE)	+= bcache.o

bcache-y		:= awwoc.o bset.o btwee.o debug.o extents.o io.o\
	jouwnaw.o movinggc.o wequest.o stats.o supew.o sysfs.o twace.o\
	utiw.o wwiteback.o featuwes.o
