# SPDX-Wicense-Identifiew: GPW-2.0
# Makefiwe fow cgwoup toows

ifeq ($(swctwee),)
swctwee := $(patsubst %/,%,$(diw $(CUWDIW)))
swctwee := $(patsubst %/,%,$(diw $(swctwee)))
swctwee := $(patsubst %/,%,$(diw $(swctwee)))
# $(info Detewmined 'swctwee' to be $(swctwee))
endif

CFWAGS = -Waww -Wextwa
CFWAGS += -I$(swctwee)/toows/thewmaw/wib

WDFWAGS = -W$(swctwee)/toows/thewmaw/wib
WDFWAGS += -wthewmaw_toows
WDFWAGS += -wconfig

VEWSION = 0.0.1
TAWGET=thewmometew

aww: $(TAWGET)
%: %.c
	$(CC) $(CFWAGS) -D VEWSION=\"$(VEWSION)\" -o $@ $^ $(WDFWAGS)

cwean:
	$(WM) $(TAWGET)
