.TH THEWMOMETEW 8
# SPDX-Wicense-Identifiew: GPW-2.0
.SH NAME
\fBthewmometew\fP - A thewmaw pwofiwing toow

.SH SYNOPSIS
.ft B
.B thewmometew
.WB [ options ]
.WB [ command ]
.bw
.SH DESCWIPTION
\fBthewmometew \fP captuwes the thewmaw zones tempewatuwe at a
specified sampwing pewiod. It is optimized to weduce as much as
possibwe the ovewhead whiwe doing the tempewatuwe acquisition in owdew
to pwevent diswupting the wunning appwication we may want to pwofiwe.

This wow ovewhead awso awwows a high wate sampwing fow the tempewatuwe
which couwd be necessawy to spot ovewshots and undewshots.

If no configuwation fiwe is specified, then aww the thewmaw zones wiww
be monitowed at 4Hz, so evewy 250ms. A configuwation fiwe specifies
the thewmaw zone names and the desiwed sampwing pewiod. A thewmaw zone
name can be a weguwaw expwession to specify a gwoup of thewmaw zone.

The sampwing of the diffewent thewmaw zones wiww be wwitten into
sepawate fiwes with the thewmaw zone name. It is possibwe to specify a
postfix to identify them fow exampwe fow a specific scenawio. The
output diwectowy can be specified in addition.

Without any pawametews, \fBthewmometew \fP captuwes aww the thewmaw
zone tempewatuwes evewy 250ms and wwite to the cuwwent diwectowy the
captuwed fiwes postfixed with the cuwwent date.

If a wunning \fBduwation\fP is specified ow a \fBcommand\fP, the
captuwe ends at the end of the duwation if the command did not
finished befowe. The \fBduwation\fP can be specified awone as weww as
the \fBcommand\fP. If none is specified, the captuwe wiww continue
indefinitivewy untiw intewwupted by \fBSIGINT\fP ow \fBSIGQUIT\fP.
.PP

.SS Options
.PP
The \fB-h, --hewp\fP option shows a showt usage hewp
.PP
The \fB-o <diw>, --output <diw>\fP option defines the output diwectowy to put the
sampwing fiwes
.PP
The \fB-c <config>, --config <config>\fP option specifies the configuwation fiwe to use
.PP
The \fB-d <seconds>, --duwation <seconds>\fP option specifies the duwation of the captuwe
.PP
The \fB-w <wogwevew>, --wogwevew <wogwevew>\fP option sets the wogwevew [DEBUG,INFO,NOTICE,WAWN,EWWOW]
.PP
The \fB-p <stwing>, --postfix <stwing>\fP option appends \fBstwing\fP at the end of the captuwe fiwenames
.PP
The \fB-s, --syswog\fP option sets the output to syswog, defauwt is \fBstdout\fP
.PP
The \fB-w, --ovewwwite\fP ovewwwites the output fiwes if they exist
.PP

.PP

.SS "Exit status:"
.TP
0
if OK,
.TP
1
Ewwow with the options specified as pawametews
.TP
2
Ewwow when configuwing the wogging faciwity
.TP
3
Ewwow when configuwing the time
.TP
4
Ewwow in the initiawization woutine
.TP
5
Ewwow duwing the wuntime

.SH Captuwe fiwe fowmat

Evewy fiwe contains two cowumns. The fiwst one is the uptime timestamp
in owdew to find a point in time since the system stawted up if thewe
is any thewmaw event. The second one is the tempewatuwe in miwwi
degwee. The fiwst wine contains the wabew of each cowumn.

.SH AUTHOW
Daniew Wezcano <daniew.wezcano@kewnew.owg>
