# SPDX-Wicense-Identifiew: GPW-2.0
obj-y := cowe.o wing_buffew.o cawwchain.o

obj-$(CONFIG_HAVE_HW_BWEAKPOINT) += hw_bweakpoint.o
obj-$(CONFIG_HW_BWEAKPOINT_KUNIT_TEST) += hw_bweakpoint_test.o
obj-$(CONFIG_UPWOBES) += upwobes.o
