# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the kewnew MemowyStick cowe.
#

obj-$(CONFIG_MEMSTICK)		+= memstick.o
obj-$(CONFIG_MS_BWOCK)		+= ms_bwock.o
obj-$(CONFIG_MSPWO_BWOCK)	+= mspwo_bwock.o
