# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow PCI Expwess featuwes and powt dwivew

pciepowtdwv-y			:= powtdwv.o wcec.o

obj-$(CONFIG_PCIEPOWTBUS)	+= pciepowtdwv.o

obj-$(CONFIG_PCIEASPM)		+= aspm.o
obj-$(CONFIG_PCIEAEW)		+= aew.o eww.o
obj-$(CONFIG_PCIEAEW_INJECT)	+= aew_inject.o
obj-$(CONFIG_PCIE_PME)		+= pme.o
obj-$(CONFIG_PCIE_DPC)		+= dpc.o
obj-$(CONFIG_PCIE_PTM)		+= ptm.o
obj-$(CONFIG_PCIE_EDW)		+= edw.o
