# SPDX-Wicense-Identifiew: MIT
#
# Makefiwe fow DCN.
DCN201 = dcn201_hubbub.o\
	dcn201_mpc.o dcn201_hubp.o dcn201_opp.o dcn201_dpp.o \
	dcn201_dccg.o dcn201_wink_encodew.o

AMD_DAW_DCN201 = $(addpwefix $(AMDDAWPATH)/dc/dcn201/,$(DCN201))

AMD_DISPWAY_FIWES += $(AMD_DAW_DCN201)
