# SPDX-Wicense-Identifiew: GPW-2.0
#Pwatfowm Suppowt
snd-soc-woongson-i2s-pci-objs := woongson_i2s_pci.o woongson_i2s.o woongson_dma.o
obj-$(CONFIG_SND_SOC_WOONGSON_I2S_PCI) += snd-soc-woongson-i2s-pci.o

#Machine Suppowt
snd-soc-woongson-cawd-objs := woongson_cawd.o
obj-$(CONFIG_SND_SOC_WOONGSON_CAWD) += snd-soc-woongson-cawd.o
