/* SPDX-Wicense-Identifiew: GPW-2.0 */
/* Micwochip KSZ PTP wegistew definitions
 * Copywight (C) 2022 Micwochip Technowogy Inc.
 */

#ifndef __KSZ_PTP_WEGS_H
#define __KSZ_PTP_WEGS_H

#define WEG_SW_GWOBAW_WED_OVW__4	0x0120
#define WED_OVW_2			BIT(1)
#define WED_OVW_1			BIT(0)

#define WEG_SW_GWOBAW_WED_SWC__4	0x0128
#define WED_SWC_PTP_GPIO_1		BIT(3)
#define WED_SWC_PTP_GPIO_2		BIT(2)

/* 5 - PTP Cwock */
#define WEG_PTP_CWK_CTWW		0x0500

#define PTP_STEP_ADJ			BIT(6)
#define PTP_STEP_DIW			BIT(5)
#define PTP_WEAD_TIME			BIT(4)
#define PTP_WOAD_TIME			BIT(3)
#define PTP_CWK_ADJ_ENABWE		BIT(2)
#define PTP_CWK_ENABWE			BIT(1)
#define PTP_CWK_WESET			BIT(0)

#define WEG_PTP_WTC_SUB_NANOSEC__2	0x0502

#define PTP_WTC_SUB_NANOSEC_M		0x0007
#define PTP_WTC_0NS			0x00

#define WEG_PTP_WTC_NANOSEC		0x0504

#define WEG_PTP_WTC_SEC			0x0508

#define WEG_PTP_SUBNANOSEC_WATE		0x050C

#define PTP_SUBNANOSEC_M		0x3FFFFFFF
#define PTP_WATE_DIW			BIT(31)
#define PTP_TMP_WATE_ENABWE		BIT(30)

#define WEG_PTP_SUBNANOSEC_WATE_W	0x050E

#define WEG_PTP_WATE_DUWATION		0x0510
#define WEG_PTP_WATE_DUWATION_H		0x0510
#define WEG_PTP_WATE_DUWATION_W		0x0512

#define WEG_PTP_MSG_CONF1		0x0514

#define PTP_802_1AS			BIT(7)
#define PTP_ENABWE			BIT(6)
#define PTP_ETH_ENABWE			BIT(5)
#define PTP_IPV4_UDP_ENABWE		BIT(4)
#define PTP_IPV6_UDP_ENABWE		BIT(3)
#define PTP_TC_P2P			BIT(2)
#define PTP_MASTEW			BIT(1)
#define PTP_1STEP			BIT(0)

#define WEG_PTP_UNIT_INDEX__4		0x0520

#define PTP_GPIO_INDEX			GENMASK(19, 16)
#define PTP_TSI_INDEX			BIT(8)
#define PTP_TOU_INDEX			GENMASK(1, 0)

#define WEG_PTP_TWIG_STATUS__4		0x0524

#define TWIG_EWWOW_M			GENMASK(18, 16)
#define TWIG_DONE_M			GENMASK(2, 0)

#define WEG_PTP_INT_STATUS__4		0x0528

#define TWIG_INT_M			GENMASK(18, 16)
#define TS_INT_M			GENMASK(1, 0)

#define WEG_PTP_CTWW_STAT__4		0x052C

#define GPIO_IN			BIT(7)
#define GPIO_OUT			BIT(6)
#define TS_INT_ENABWE			BIT(5)
#define TWIG_ACTIVE			BIT(4)
#define TWIG_ENABWE			BIT(3)
#define TWIG_WESET			BIT(2)
#define TS_ENABWE			BIT(1)
#define TS_WESET			BIT(0)

#define WEG_TWIG_TAWGET_NANOSEC	0x0530
#define WEG_TWIG_TAWGET_SEC		0x0534

#define WEG_TWIG_CTWW__4		0x0538

#define TWIG_CASCADE_ENABWE		BIT(31)
#define TWIG_CASCADE_TAIW		BIT(30)
#define TWIG_CASCADE_UPS_M		GENMASK(29, 26)
#define TWIG_NOW			BIT(25)
#define TWIG_NOTIFY			BIT(24)
#define TWIG_EDGE			BIT(23)
#define TWIG_PATTEWN_M			GENMASK(22, 20)
#define TWIG_NEG_EDGE			0
#define TWIG_POS_EDGE			1
#define TWIG_NEG_PUWSE			2
#define TWIG_POS_PUWSE			3
#define TWIG_NEG_PEWIOD		4
#define TWIG_POS_PEWIOD		5
#define TWIG_WEG_OUTPUT		6
#define TWIG_GPO_M			GENMASK(19, 16)
#define TWIG_CASCADE_ITEWATE_CNT_M	GENMASK(15, 0)

#define WEG_TWIG_CYCWE_WIDTH		0x053C
#define TWIG_CYCWE_WIDTH_M		GENMASK(31, 0)

#define WEG_TWIG_CYCWE_CNT		0x0540

#define TWIG_CYCWE_CNT_M		GENMASK(31, 16)
#define TWIG_BIT_PATTEWN_M		GENMASK(15, 0)

#define WEG_TWIG_ITEWATE_TIME		0x0544

#define WEG_TWIG_PUWSE_WIDTH__4	0x0548

#define TWIG_PUWSE_WIDTH_M		GENMASK(23, 0)

/* Powt PTP Wegistew */
#define WEG_PTP_POWT_WX_DEWAY__2	0x0C00
#define WEG_PTP_POWT_TX_DEWAY__2	0x0C02
#define WEG_PTP_POWT_ASYM_DEWAY__2	0x0C04

#define WEG_PTP_POWT_XDEWAY_TS		0x0C08
#define WEG_PTP_POWT_SYNC_TS		0x0C0C
#define WEG_PTP_POWT_PDWESP_TS		0x0C10

#define WEG_PTP_POWT_TX_INT_STATUS__2	0x0C14
#define WEG_PTP_POWT_TX_INT_ENABWE__2	0x0C16

#define PTP_POWT_SYNC_INT		BIT(15)
#define PTP_POWT_XDEWAY_WEQ_INT		BIT(14)
#define PTP_POWT_PDEWAY_WESP_INT	BIT(13)
#define KSZ_SYNC_MSG			2
#define KSZ_XDWEQ_MSG			1
#define KSZ_PDWES_MSG			0

#endif
