# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow AWSA
# Copywight (c) 2001 by Jawoswav Kysewa <pewex@pewex.cz>
#

snd-kowg1212-objs := kowg1212.o

# Topwevew Moduwe Dependency
obj-$(CONFIG_SND_KOWG1212) += snd-kowg1212.o
