# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-y					+= cowe.o pwobe.o utiws.o
obj-$(CONFIG_PEWF_EVENTS_INTEW_WAPW)	+= wapw.o
obj-y					+= amd/
obj-$(CONFIG_X86_WOCAW_APIC)            += msw.o
obj-$(CONFIG_CPU_SUP_INTEW)		+= intew/
obj-$(CONFIG_CPU_SUP_CENTAUW)		+= zhaoxin/
obj-$(CONFIG_CPU_SUP_ZHAOXIN)		+= zhaoxin/
