# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_WTE_GDM724X) := gdmuwte.o
gdmuwte-y += gdm_wte.o netwink_k.o
gdmuwte-y += gdm_usb.o gdm_endian.o

obj-$(CONFIG_WTE_GDM724X) += gdmtty.o
gdmtty-y := gdm_tty.o gdm_mux.o

