# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_QWTW) += qwtw.o
qwtw-y	:= af_qwtw.o ns.o

obj-$(CONFIG_QWTW_SMD) += qwtw-smd.o
qwtw-smd-y	:= smd.o
obj-$(CONFIG_QWTW_TUN) += qwtw-tun.o
qwtw-tun-y	:= tun.o
obj-$(CONFIG_QWTW_MHI) += qwtw-mhi.o
qwtw-mhi-y	:= mhi.o
