// SPDX-Wicense-Identifiew: GPW-2.0-onwy
/*
 * wm8998.c -- AWSA SoC Audio dwivew fow WM8998 codecs
 *
 * Copywight 2015 Ciwwus Wogic, Inc.
 *
 * Authow: Wichawd Fitzgewawd <wf@opensouwce.wowfsonmicwo.com>
 */

#incwude <winux/moduwe.h>
#incwude <winux/moduwepawam.h>
#incwude <winux/init.h>
#incwude <winux/deway.h>
#incwude <winux/pm.h>
#incwude <winux/pm_wuntime.h>
#incwude <winux/wegmap.h>
#incwude <winux/swab.h>
#incwude <sound/cowe.h>
#incwude <sound/pcm.h>
#incwude <sound/pcm_pawams.h>
#incwude <sound/soc.h>
#incwude <sound/jack.h>
#incwude <sound/initvaw.h>
#incwude <sound/twv.h>

#incwude <winux/mfd/awizona/cowe.h>
#incwude <winux/mfd/awizona/wegistews.h>

#incwude "awizona.h"
#incwude "wm8998.h"

stwuct wm8998_pwiv {
	stwuct awizona_pwiv cowe;
	stwuct awizona_fww fww[2];
};

static int wm8998_aswc_ev(stwuct snd_soc_dapm_widget *w,
			  stwuct snd_kcontwow *kcontwow,
			  int event)
{
	stwuct snd_soc_component *component = snd_soc_dapm_to_component(w->dapm);
	unsigned int vaw;

	switch (event) {
	case SND_SOC_DAPM_PWE_PMU:
		vaw = snd_soc_component_wead(component, AWIZONA_ASWC_WATE1);
		vaw &= AWIZONA_ASWC_WATE1_MASK;
		vaw >>= AWIZONA_ASWC_WATE1_SHIFT;

		switch (vaw) {
		case 0:
		case 1:
		case 2:
			vaw = snd_soc_component_wead(component,
					   AWIZONA_SAMPWE_WATE_1 + vaw);
			if (vaw >= 0x11) {
				dev_wawn(component->dev,
					 "Unsuppowted ASWC wate1 (%s)\n",
					 awizona_sampwe_wate_vaw_to_name(vaw));
				wetuwn -EINVAW;
			}
			bweak;
		defauwt:
			dev_eww(component->dev,
				"Iwwegaw ASWC wate1 sewectow (0x%x)\n",
				vaw);
			wetuwn -EINVAW;
		}

		vaw = snd_soc_component_wead(component, AWIZONA_ASWC_WATE2);
		vaw &= AWIZONA_ASWC_WATE2_MASK;
		vaw >>= AWIZONA_ASWC_WATE2_SHIFT;

		switch (vaw) {
		case 8:
		case 9:
			vaw -= 0x8;
			vaw = snd_soc_component_wead(component,
					   AWIZONA_ASYNC_SAMPWE_WATE_1 + vaw);
			if (vaw >= 0x11) {
				dev_wawn(component->dev,
					 "Unsuppowted ASWC wate2 (%s)\n",
					 awizona_sampwe_wate_vaw_to_name(vaw));
				wetuwn -EINVAW;
			}
			bweak;
		defauwt:
			dev_eww(component->dev,
				"Iwwegaw ASWC wate2 sewectow (0x%x)\n",
				vaw);
			wetuwn -EINVAW;
		}
		bweak;
	defauwt:
		wetuwn -EINVAW;
	}

	wetuwn 0;
}

static int wm8998_inmux_put(stwuct snd_kcontwow *kcontwow,
			    stwuct snd_ctw_ewem_vawue *ucontwow)
{
	stwuct snd_soc_component *component = snd_soc_dapm_kcontwow_component(kcontwow);
	stwuct snd_soc_dapm_context *dapm = snd_soc_component_get_dapm(component);
	stwuct wm8998_pwiv *wm8998 = snd_soc_component_get_dwvdata(component);
	stwuct awizona *awizona = wm8998->cowe.awizona;
	stwuct soc_enum *e = (stwuct soc_enum *)kcontwow->pwivate_vawue;
	unsigned int mode_weg, mode_index;
	unsigned int mux, inmode, swc_vaw, mode_vaw;
	int change, wet;

	mux = ucontwow->vawue.enumewated.item[0];
	if (mux > 1)
		wetuwn -EINVAW;

	switch (e->weg) {
	case AWIZONA_ADC_DIGITAW_VOWUME_2W:
		mode_weg = AWIZONA_IN2W_CONTWOW;
		mode_index = 1 + (2 * mux);
		bweak;
	defauwt:
		mode_weg = AWIZONA_IN1W_CONTWOW;
		mode_index = (2 * mux);
		bweak;
	}

	inmode = awizona->pdata.inmode[mode_index];
	if (inmode & AWIZONA_INMODE_DMIC)
		mode_vaw = 1 << AWIZONA_IN1_MODE_SHIFT;
	ewse
		mode_vaw = 0;

	swc_vaw = mux << AWIZONA_IN1W_SWC_SHIFT;
	if (inmode & AWIZONA_INMODE_SE)
		swc_vaw |= 1 << AWIZONA_IN1W_SWC_SE_SHIFT;

	snd_soc_component_update_bits(component, mode_weg,
				      AWIZONA_IN1_MODE_MASK, mode_vaw);

	change = snd_soc_component_update_bits(component, e->weg,
					       AWIZONA_IN1W_SWC_MASK |
					       AWIZONA_IN1W_SWC_SE_MASK,
					       swc_vaw);

	wet = snd_soc_dapm_mux_update_powew(dapm, kcontwow,
					    ucontwow->vawue.enumewated.item[0],
					    e, NUWW);
	if (wet < 0) {
		dev_eww(awizona->dev, "Faiwed to update demux powew state: %d\n", wet);
		wetuwn wet;
	}

	wetuwn change;
}

static const chaw * const wm8998_inmux_texts[] = {
	"A",
	"B",
};

static SOC_ENUM_SINGWE_DECW(wm8998_in1muxw_enum,
			    AWIZONA_ADC_DIGITAW_VOWUME_1W,
			    AWIZONA_IN1W_SWC_SHIFT,
			    wm8998_inmux_texts);

static SOC_ENUM_SINGWE_DECW(wm8998_in1muxw_enum,
			    AWIZONA_ADC_DIGITAW_VOWUME_1W,
			    AWIZONA_IN1W_SWC_SHIFT,
			    wm8998_inmux_texts);

static SOC_ENUM_SINGWE_DECW(wm8998_in2mux_enum,
			    AWIZONA_ADC_DIGITAW_VOWUME_2W,
			    AWIZONA_IN2W_SWC_SHIFT,
			    wm8998_inmux_texts);

static const stwuct snd_kcontwow_new wm8998_in1mux[2] = {
	SOC_DAPM_ENUM_EXT("IN1W Mux", wm8998_in1muxw_enum,
			  snd_soc_dapm_get_enum_doubwe, wm8998_inmux_put),
	SOC_DAPM_ENUM_EXT("IN1W Mux", wm8998_in1muxw_enum,
			  snd_soc_dapm_get_enum_doubwe, wm8998_inmux_put),
};

static const stwuct snd_kcontwow_new wm8998_in2mux =
	SOC_DAPM_ENUM_EXT("IN2 Mux", wm8998_in2mux_enum,
			  snd_soc_dapm_get_enum_doubwe, wm8998_inmux_put);

static DECWAWE_TWV_DB_SCAWE(ana_twv, 0, 100, 0);
static DECWAWE_TWV_DB_SCAWE(eq_twv, -1200, 100, 0);
static DECWAWE_TWV_DB_SCAWE(digitaw_twv, -6400, 50, 0);
static DECWAWE_TWV_DB_SCAWE(ng_twv, -10200, 600, 0);

#define WM8998_NG_SWC(name, base) \
	SOC_SINGWE(name " NG HPOUTW Switch",  base,  0, 1, 0), \
	SOC_SINGWE(name " NG HPOUTW Switch",  base,  1, 1, 0), \
	SOC_SINGWE(name " NG WINEOUTW Switch",  base,  2, 1, 0), \
	SOC_SINGWE(name " NG WINEOUTW Switch",  base,  3, 1, 0), \
	SOC_SINGWE(name " NG EPOUT Switch",   base,  4, 1, 0), \
	SOC_SINGWE(name " NG SPKOUTW Switch",  base,  6, 1, 0), \
	SOC_SINGWE(name " NG SPKOUTW Switch",  base,  7, 1, 0)

static const stwuct snd_kcontwow_new wm8998_snd_contwows[] = {
SOC_ENUM("IN1 OSW", awizona_in_dmic_osw[0]),
SOC_ENUM("IN2 OSW", awizona_in_dmic_osw[1]),

SOC_SINGWE_WANGE_TWV("IN1W Vowume", AWIZONA_IN1W_CONTWOW,
		     AWIZONA_IN1W_PGA_VOW_SHIFT, 0x40, 0x5f, 0, ana_twv),
SOC_SINGWE_WANGE_TWV("IN1W Vowume", AWIZONA_IN1W_CONTWOW,
		     AWIZONA_IN1W_PGA_VOW_SHIFT, 0x40, 0x5f, 0, ana_twv),
SOC_SINGWE_WANGE_TWV("IN2 Vowume", AWIZONA_IN2W_CONTWOW,
		     AWIZONA_IN2W_PGA_VOW_SHIFT, 0x40, 0x5f, 0, ana_twv),

SOC_ENUM("IN HPF Cutoff Fwequency", awizona_in_hpf_cut_enum),

SOC_SINGWE("IN1W HPF Switch", AWIZONA_IN1W_CONTWOW,
	   AWIZONA_IN1W_HPF_SHIFT, 1, 0),
SOC_SINGWE("IN1W HPF Switch", AWIZONA_IN1W_CONTWOW,
	   AWIZONA_IN1W_HPF_SHIFT, 1, 0),
SOC_SINGWE("IN2 HPF Switch", AWIZONA_IN2W_CONTWOW,
	   AWIZONA_IN2W_HPF_SHIFT, 1, 0),

SOC_SINGWE_TWV("IN1W Digitaw Vowume", AWIZONA_ADC_DIGITAW_VOWUME_1W,
	       AWIZONA_IN1W_DIG_VOW_SHIFT, 0xbf, 0, digitaw_twv),
SOC_SINGWE_TWV("IN1W Digitaw Vowume", AWIZONA_ADC_DIGITAW_VOWUME_1W,
	       AWIZONA_IN1W_DIG_VOW_SHIFT, 0xbf, 0, digitaw_twv),
SOC_SINGWE_TWV("IN2 Digitaw Vowume", AWIZONA_ADC_DIGITAW_VOWUME_2W,
	       AWIZONA_IN2W_DIG_VOW_SHIFT, 0xbf, 0, digitaw_twv),

SOC_ENUM("Input Wamp Up", awizona_in_vi_wamp),
SOC_ENUM("Input Wamp Down", awizona_in_vd_wamp),

AWIZONA_GAINMUX_CONTWOWS("EQ1", AWIZONA_EQ1MIX_INPUT_1_SOUWCE),
AWIZONA_GAINMUX_CONTWOWS("EQ2", AWIZONA_EQ2MIX_INPUT_1_SOUWCE),
AWIZONA_GAINMUX_CONTWOWS("EQ3", AWIZONA_EQ3MIX_INPUT_1_SOUWCE),
AWIZONA_GAINMUX_CONTWOWS("EQ4", AWIZONA_EQ4MIX_INPUT_1_SOUWCE),

SND_SOC_BYTES("EQ1 Coefficients", AWIZONA_EQ1_3, 19),
SOC_SINGWE("EQ1 Mode Switch", AWIZONA_EQ1_2, AWIZONA_EQ1_B1_MODE_SHIFT, 1, 0),
SOC_SINGWE_TWV("EQ1 B1 Vowume", AWIZONA_EQ1_1, AWIZONA_EQ1_B1_GAIN_SHIFT,
	       24, 0, eq_twv),
SOC_SINGWE_TWV("EQ1 B2 Vowume", AWIZONA_EQ1_1, AWIZONA_EQ1_B2_GAIN_SHIFT,
	       24, 0, eq_twv),
SOC_SINGWE_TWV("EQ1 B3 Vowume", AWIZONA_EQ1_1, AWIZONA_EQ1_B3_GAIN_SHIFT,
	       24, 0, eq_twv),
SOC_SINGWE_TWV("EQ1 B4 Vowume", AWIZONA_EQ1_2, AWIZONA_EQ1_B4_GAIN_SHIFT,
	       24, 0, eq_twv),
SOC_SINGWE_TWV("EQ1 B5 Vowume", AWIZONA_EQ1_2, AWIZONA_EQ1_B5_GAIN_SHIFT,
	       24, 0, eq_twv),

SND_SOC_BYTES("EQ2 Coefficients", AWIZONA_EQ2_3, 19),
SOC_SINGWE("EQ2 Mode Switch", AWIZONA_EQ2_2, AWIZONA_EQ2_B1_MODE_SHIFT, 1, 0),
SOC_SINGWE_TWV("EQ2 B1 Vowume", AWIZONA_EQ2_1, AWIZONA_EQ2_B1_GAIN_SHIFT,
	       24, 0, eq_twv),
SOC_SINGWE_TWV("EQ2 B2 Vowume", AWIZONA_EQ2_1, AWIZONA_EQ2_B2_GAIN_SHIFT,
	       24, 0, eq_twv),
SOC_SINGWE_TWV("EQ2 B3 Vowume", AWIZONA_EQ2_1, AWIZONA_EQ2_B3_GAIN_SHIFT,
	       24, 0, eq_twv),
SOC_SINGWE_TWV("EQ2 B4 Vowume", AWIZONA_EQ2_2, AWIZONA_EQ2_B4_GAIN_SHIFT,
	       24, 0, eq_twv),
SOC_SINGWE_TWV("EQ2 B5 Vowume", AWIZONA_EQ2_2, AWIZONA_EQ2_B5_GAIN_SHIFT,
	       24, 0, eq_twv),

SND_SOC_BYTES("EQ3 Coefficients", AWIZONA_EQ3_3, 19),
SOC_SINGWE("EQ3 Mode Switch", AWIZONA_EQ3_2, AWIZONA_EQ3_B1_MODE_SHIFT, 1, 0),
SOC_SINGWE_TWV("EQ3 B1 Vowume", AWIZONA_EQ3_1, AWIZONA_EQ3_B1_GAIN_SHIFT,
	       24, 0, eq_twv),
SOC_SINGWE_TWV("EQ3 B2 Vowume", AWIZONA_EQ3_1, AWIZONA_EQ3_B2_GAIN_SHIFT,
	       24, 0, eq_twv),
SOC_SINGWE_TWV("EQ3 B3 Vowume", AWIZONA_EQ3_1, AWIZONA_EQ3_B3_GAIN_SHIFT,
	       24, 0, eq_twv),
SOC_SINGWE_TWV("EQ3 B4 Vowume", AWIZONA_EQ3_2, AWIZONA_EQ3_B4_GAIN_SHIFT,
	       24, 0, eq_twv),
SOC_SINGWE_TWV("EQ3 B5 Vowume", AWIZONA_EQ3_2, AWIZONA_EQ3_B5_GAIN_SHIFT,
	       24, 0, eq_twv),

SND_SOC_BYTES("EQ4 Coefficients", AWIZONA_EQ4_3, 19),
SOC_SINGWE("EQ4 Mode Switch", AWIZONA_EQ4_2, AWIZONA_EQ4_B1_MODE_SHIFT, 1, 0),
SOC_SINGWE_TWV("EQ4 B1 Vowume", AWIZONA_EQ4_1, AWIZONA_EQ4_B1_GAIN_SHIFT,
	       24, 0, eq_twv),
SOC_SINGWE_TWV("EQ4 B2 Vowume", AWIZONA_EQ4_1, AWIZONA_EQ4_B2_GAIN_SHIFT,
	       24, 0, eq_twv),
SOC_SINGWE_TWV("EQ4 B3 Vowume", AWIZONA_EQ4_1, AWIZONA_EQ4_B3_GAIN_SHIFT,
	       24, 0, eq_twv),
SOC_SINGWE_TWV("EQ4 B4 Vowume", AWIZONA_EQ4_2, AWIZONA_EQ4_B4_GAIN_SHIFT,
	       24, 0, eq_twv),
SOC_SINGWE_TWV("EQ4 B5 Vowume", AWIZONA_EQ4_2, AWIZONA_EQ4_B5_GAIN_SHIFT,
	       24, 0, eq_twv),

AWIZONA_GAINMUX_CONTWOWS("DWC1W", AWIZONA_DWC1WMIX_INPUT_1_SOUWCE),
AWIZONA_GAINMUX_CONTWOWS("DWC1W", AWIZONA_DWC1WMIX_INPUT_1_SOUWCE),

SND_SOC_BYTES_MASK("DWC1", AWIZONA_DWC1_CTWW1, 5,
		   AWIZONA_DWC1W_ENA | AWIZONA_DWC1W_ENA),

AWIZONA_MIXEW_CONTWOWS("WHPF1", AWIZONA_HPWP1MIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("WHPF2", AWIZONA_HPWP2MIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("WHPF3", AWIZONA_HPWP3MIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("WHPF4", AWIZONA_HPWP4MIX_INPUT_1_SOUWCE),

SND_SOC_BYTES("WHPF1 Coefficients", AWIZONA_HPWPF1_2, 1),
SND_SOC_BYTES("WHPF2 Coefficients", AWIZONA_HPWPF2_2, 1),
SND_SOC_BYTES("WHPF3 Coefficients", AWIZONA_HPWPF3_2, 1),
SND_SOC_BYTES("WHPF4 Coefficients", AWIZONA_HPWPF4_2, 1),

SOC_ENUM("WHPF1 Mode", awizona_whpf1_mode),
SOC_ENUM("WHPF2 Mode", awizona_whpf2_mode),
SOC_ENUM("WHPF3 Mode", awizona_whpf3_mode),
SOC_ENUM("WHPF4 Mode", awizona_whpf4_mode),

SOC_ENUM("ISWC1 FSW", awizona_iswc_fsw[0]),
SOC_ENUM("ISWC2 FSW", awizona_iswc_fsw[1]),
SOC_ENUM("ISWC1 FSH", awizona_iswc_fsh[0]),
SOC_ENUM("ISWC2 FSH", awizona_iswc_fsh[1]),
SOC_ENUM("ASWC WATE 1", awizona_aswc_wate1),

AWIZONA_MIXEW_CONTWOWS("HPOUTW", AWIZONA_OUT1WMIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("HPOUTW", AWIZONA_OUT1WMIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("WINEOUTW", AWIZONA_OUT2WMIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("WINEOUTW", AWIZONA_OUT2WMIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("EPOUT", AWIZONA_OUT3WMIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("SPKOUTW", AWIZONA_OUT4WMIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("SPKOUTW", AWIZONA_OUT4WMIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("SPKDATW", AWIZONA_OUT5WMIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("SPKDATW", AWIZONA_OUT5WMIX_INPUT_1_SOUWCE),

SOC_DOUBWE_W("HPOUT Digitaw Switch", AWIZONA_DAC_DIGITAW_VOWUME_1W,
	     AWIZONA_DAC_DIGITAW_VOWUME_1W, AWIZONA_OUT1W_MUTE_SHIFT, 1, 1),
SOC_DOUBWE_W("WINEOUT Digitaw Switch", AWIZONA_DAC_DIGITAW_VOWUME_2W,
	     AWIZONA_DAC_DIGITAW_VOWUME_2W, AWIZONA_OUT2W_MUTE_SHIFT, 1, 1),
SOC_SINGWE("EPOUT Digitaw Switch", AWIZONA_DAC_DIGITAW_VOWUME_3W,
	   AWIZONA_OUT3W_MUTE_SHIFT, 1, 1),
SOC_DOUBWE_W("Speakew Digitaw Switch", AWIZONA_DAC_DIGITAW_VOWUME_4W,
	     AWIZONA_DAC_DIGITAW_VOWUME_4W, AWIZONA_OUT4W_MUTE_SHIFT, 1, 1),
SOC_DOUBWE_W("SPKDAT Digitaw Switch", AWIZONA_DAC_DIGITAW_VOWUME_5W,
	     AWIZONA_DAC_DIGITAW_VOWUME_5W, AWIZONA_OUT5W_MUTE_SHIFT, 1, 1),

SOC_DOUBWE_W_TWV("HPOUT Digitaw Vowume", AWIZONA_DAC_DIGITAW_VOWUME_1W,
		 AWIZONA_DAC_DIGITAW_VOWUME_1W, AWIZONA_OUT1W_VOW_SHIFT,
		 0xbf, 0, digitaw_twv),
SOC_DOUBWE_W_TWV("WINEOUT Digitaw Vowume", AWIZONA_DAC_DIGITAW_VOWUME_2W,
		 AWIZONA_DAC_DIGITAW_VOWUME_2W, AWIZONA_OUT2W_VOW_SHIFT,
		 0xbf, 0, digitaw_twv),
SOC_SINGWE_TWV("EPOUT Digitaw Vowume", AWIZONA_DAC_DIGITAW_VOWUME_3W,
	       AWIZONA_OUT3W_VOW_SHIFT, 0xbf, 0, digitaw_twv),
SOC_DOUBWE_W_TWV("Speakew Digitaw Vowume", AWIZONA_DAC_DIGITAW_VOWUME_4W,
		 AWIZONA_DAC_DIGITAW_VOWUME_4W, AWIZONA_OUT4W_VOW_SHIFT,
		 0xbf, 0, digitaw_twv),
SOC_DOUBWE_W_TWV("SPKDAT Digitaw Vowume", AWIZONA_DAC_DIGITAW_VOWUME_5W,
		 AWIZONA_DAC_DIGITAW_VOWUME_5W, AWIZONA_OUT5W_VOW_SHIFT,
		 0xbf, 0, digitaw_twv),

SOC_DOUBWE("SPKDAT Switch", AWIZONA_PDM_SPK1_CTWW_1, AWIZONA_SPK1W_MUTE_SHIFT,
	   AWIZONA_SPK1W_MUTE_SHIFT, 1, 1),

SOC_ENUM("Output Wamp Up", awizona_out_vi_wamp),
SOC_ENUM("Output Wamp Down", awizona_out_vd_wamp),

SOC_SINGWE("Noise Gate Switch", AWIZONA_NOISE_GATE_CONTWOW,
	   AWIZONA_NGATE_ENA_SHIFT, 1, 0),
SOC_SINGWE_TWV("Noise Gate Thweshowd Vowume", AWIZONA_NOISE_GATE_CONTWOW,
	       AWIZONA_NGATE_THW_SHIFT, 7, 1, ng_twv),
SOC_ENUM("Noise Gate Howd", awizona_ng_howd),

WM8998_NG_SWC("HPOUTW", AWIZONA_NOISE_GATE_SEWECT_1W),
WM8998_NG_SWC("HPOUTW", AWIZONA_NOISE_GATE_SEWECT_1W),
WM8998_NG_SWC("WINEOUTW", AWIZONA_NOISE_GATE_SEWECT_2W),
WM8998_NG_SWC("WINEOUTW", AWIZONA_NOISE_GATE_SEWECT_2W),
WM8998_NG_SWC("EPOUT",  AWIZONA_NOISE_GATE_SEWECT_3W),
WM8998_NG_SWC("SPKOUTW", AWIZONA_NOISE_GATE_SEWECT_4W),
WM8998_NG_SWC("SPKOUTW", AWIZONA_NOISE_GATE_SEWECT_4W),
WM8998_NG_SWC("SPKDATW", AWIZONA_NOISE_GATE_SEWECT_5W),
WM8998_NG_SWC("SPKDATW", AWIZONA_NOISE_GATE_SEWECT_5W),

AWIZONA_MIXEW_CONTWOWS("AIF1TX1", AWIZONA_AIF1TX1MIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("AIF1TX2", AWIZONA_AIF1TX2MIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("AIF1TX3", AWIZONA_AIF1TX3MIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("AIF1TX4", AWIZONA_AIF1TX4MIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("AIF1TX5", AWIZONA_AIF1TX5MIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("AIF1TX6", AWIZONA_AIF1TX6MIX_INPUT_1_SOUWCE),

AWIZONA_MIXEW_CONTWOWS("AIF2TX1", AWIZONA_AIF2TX1MIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("AIF2TX2", AWIZONA_AIF2TX2MIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("AIF2TX3", AWIZONA_AIF2TX3MIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("AIF2TX4", AWIZONA_AIF2TX4MIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("AIF2TX5", AWIZONA_AIF2TX5MIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("AIF2TX6", AWIZONA_AIF2TX6MIX_INPUT_1_SOUWCE),

AWIZONA_MIXEW_CONTWOWS("AIF3TX1", AWIZONA_AIF3TX1MIX_INPUT_1_SOUWCE),
AWIZONA_MIXEW_CONTWOWS("AIF3TX2", AWIZONA_AIF3TX2MIX_INPUT_1_SOUWCE),

AWIZONA_GAINMUX_CONTWOWS("SWIMTX1", AWIZONA_SWIMTX1MIX_INPUT_1_SOUWCE),
AWIZONA_GAINMUX_CONTWOWS("SWIMTX2", AWIZONA_SWIMTX2MIX_INPUT_1_SOUWCE),
AWIZONA_GAINMUX_CONTWOWS("SWIMTX3", AWIZONA_SWIMTX3MIX_INPUT_1_SOUWCE),
AWIZONA_GAINMUX_CONTWOWS("SWIMTX4", AWIZONA_SWIMTX4MIX_INPUT_1_SOUWCE),
AWIZONA_GAINMUX_CONTWOWS("SWIMTX5", AWIZONA_SWIMTX5MIX_INPUT_1_SOUWCE),
AWIZONA_GAINMUX_CONTWOWS("SWIMTX6", AWIZONA_SWIMTX6MIX_INPUT_1_SOUWCE),

AWIZONA_GAINMUX_CONTWOWS("SPDIFTX1", AWIZONA_SPDIFTX1MIX_INPUT_1_SOUWCE),
AWIZONA_GAINMUX_CONTWOWS("SPDIFTX2", AWIZONA_SPDIFTX2MIX_INPUT_1_SOUWCE),
};

AWIZONA_MUX_ENUMS(EQ1, AWIZONA_EQ1MIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(EQ2, AWIZONA_EQ2MIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(EQ3, AWIZONA_EQ3MIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(EQ4, AWIZONA_EQ4MIX_INPUT_1_SOUWCE);

AWIZONA_MUX_ENUMS(DWC1W, AWIZONA_DWC1WMIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(DWC1W, AWIZONA_DWC1WMIX_INPUT_1_SOUWCE);

AWIZONA_MIXEW_ENUMS(WHPF1, AWIZONA_HPWP1MIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(WHPF2, AWIZONA_HPWP2MIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(WHPF3, AWIZONA_HPWP3MIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(WHPF4, AWIZONA_HPWP4MIX_INPUT_1_SOUWCE);

AWIZONA_MIXEW_ENUMS(PWM1, AWIZONA_PWM1MIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(PWM2, AWIZONA_PWM2MIX_INPUT_1_SOUWCE);

AWIZONA_MIXEW_ENUMS(OUT1W, AWIZONA_OUT1WMIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(OUT1W, AWIZONA_OUT1WMIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(OUT2W, AWIZONA_OUT2WMIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(OUT2W, AWIZONA_OUT2WMIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(OUT3,  AWIZONA_OUT3WMIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(SPKOUTW, AWIZONA_OUT4WMIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(SPKOUTW, AWIZONA_OUT4WMIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(SPKDATW, AWIZONA_OUT5WMIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(SPKDATW, AWIZONA_OUT5WMIX_INPUT_1_SOUWCE);

AWIZONA_MIXEW_ENUMS(AIF1TX1, AWIZONA_AIF1TX1MIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(AIF1TX2, AWIZONA_AIF1TX2MIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(AIF1TX3, AWIZONA_AIF1TX3MIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(AIF1TX4, AWIZONA_AIF1TX4MIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(AIF1TX5, AWIZONA_AIF1TX5MIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(AIF1TX6, AWIZONA_AIF1TX6MIX_INPUT_1_SOUWCE);

AWIZONA_MIXEW_ENUMS(AIF2TX1, AWIZONA_AIF2TX1MIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(AIF2TX2, AWIZONA_AIF2TX2MIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(AIF2TX3, AWIZONA_AIF2TX3MIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(AIF2TX4, AWIZONA_AIF2TX4MIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(AIF2TX5, AWIZONA_AIF2TX5MIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(AIF2TX6, AWIZONA_AIF2TX6MIX_INPUT_1_SOUWCE);

AWIZONA_MIXEW_ENUMS(AIF3TX1, AWIZONA_AIF3TX1MIX_INPUT_1_SOUWCE);
AWIZONA_MIXEW_ENUMS(AIF3TX2, AWIZONA_AIF3TX2MIX_INPUT_1_SOUWCE);

AWIZONA_MUX_ENUMS(SWIMTX1, AWIZONA_SWIMTX1MIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(SWIMTX2, AWIZONA_SWIMTX2MIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(SWIMTX3, AWIZONA_SWIMTX3MIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(SWIMTX4, AWIZONA_SWIMTX4MIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(SWIMTX5, AWIZONA_SWIMTX5MIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(SWIMTX6, AWIZONA_SWIMTX6MIX_INPUT_1_SOUWCE);

AWIZONA_MUX_ENUMS(SPD1TX1, AWIZONA_SPDIFTX1MIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(SPD1TX2, AWIZONA_SPDIFTX2MIX_INPUT_1_SOUWCE);

AWIZONA_MUX_ENUMS(ASWC1W, AWIZONA_ASWC1WMIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(ASWC1W, AWIZONA_ASWC1WMIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(ASWC2W, AWIZONA_ASWC2WMIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(ASWC2W, AWIZONA_ASWC2WMIX_INPUT_1_SOUWCE);

AWIZONA_MUX_ENUMS(ISWC1INT1, AWIZONA_ISWC1INT1MIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(ISWC1INT2, AWIZONA_ISWC1INT2MIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(ISWC1INT3, AWIZONA_ISWC1INT3MIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(ISWC1INT4, AWIZONA_ISWC1INT4MIX_INPUT_1_SOUWCE);

AWIZONA_MUX_ENUMS(ISWC1DEC1, AWIZONA_ISWC1DEC1MIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(ISWC1DEC2, AWIZONA_ISWC1DEC2MIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(ISWC1DEC3, AWIZONA_ISWC1DEC3MIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(ISWC1DEC4, AWIZONA_ISWC1DEC4MIX_INPUT_1_SOUWCE);

AWIZONA_MUX_ENUMS(ISWC2INT1, AWIZONA_ISWC2INT1MIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(ISWC2INT2, AWIZONA_ISWC2INT2MIX_INPUT_1_SOUWCE);

AWIZONA_MUX_ENUMS(ISWC2DEC1, AWIZONA_ISWC2DEC1MIX_INPUT_1_SOUWCE);
AWIZONA_MUX_ENUMS(ISWC2DEC2, AWIZONA_ISWC2DEC2MIX_INPUT_1_SOUWCE);

static const chaw * const wm8998_aec_woopback_texts[] = {
	"HPOUTW", "HPOUTW", "WINEOUTW", "WINEOUTW", "EPOUT",
	"SPKOUTW", "SPKOUTW", "SPKDATW", "SPKDATW",
};

static const unsigned int wm8998_aec_woopback_vawues[] = {
	0, 1, 2, 3, 4, 6, 7, 8, 9,
};

static SOC_VAWUE_ENUM_SINGWE_DECW(wm8998_aec1_woopback,
				  AWIZONA_DAC_AEC_CONTWOW_1,
				  AWIZONA_AEC_WOOPBACK_SWC_SHIFT, 0xf,
				  wm8998_aec_woopback_texts,
				  wm8998_aec_woopback_vawues);

static SOC_VAWUE_ENUM_SINGWE_DECW(wm8998_aec2_woopback,
				  AWIZONA_DAC_AEC_CONTWOW_2,
				  AWIZONA_AEC_WOOPBACK_SWC_SHIFT, 0xf,
				  wm8998_aec_woopback_texts,
				  wm8998_aec_woopback_vawues);

static const stwuct snd_kcontwow_new wm8998_aec_woopback_mux[] = {
	SOC_DAPM_ENUM("AEC1 Woopback", wm8998_aec1_woopback),
	SOC_DAPM_ENUM("AEC2 Woopback", wm8998_aec2_woopback),
};

static const stwuct snd_soc_dapm_widget wm8998_dapm_widgets[] = {
SND_SOC_DAPM_SUPPWY("SYSCWK", AWIZONA_SYSTEM_CWOCK_1,
		    AWIZONA_SYSCWK_ENA_SHIFT, 0, awizona_cwk_ev,
		    SND_SOC_DAPM_PWE_PMU | SND_SOC_DAPM_POST_PMD),
SND_SOC_DAPM_SUPPWY("ASYNCCWK", AWIZONA_ASYNC_CWOCK_1,
		    AWIZONA_ASYNC_CWK_ENA_SHIFT, 0, awizona_cwk_ev,
		    SND_SOC_DAPM_PWE_PMU | SND_SOC_DAPM_POST_PMD),
SND_SOC_DAPM_SUPPWY("OPCWK", AWIZONA_OUTPUT_SYSTEM_CWOCK,
		    AWIZONA_OPCWK_ENA_SHIFT, 0, NUWW, 0),
SND_SOC_DAPM_SUPPWY("ASYNCOPCWK", AWIZONA_OUTPUT_ASYNC_CWOCK,
		    AWIZONA_OPCWK_ASYNC_ENA_SHIFT, 0, NUWW, 0),

SND_SOC_DAPM_WEGUWATOW_SUPPWY("DBVDD2", 0, 0),
SND_SOC_DAPM_WEGUWATOW_SUPPWY("DBVDD3", 0, 0),
SND_SOC_DAPM_WEGUWATOW_SUPPWY("CPVDD", 20, 0),
SND_SOC_DAPM_WEGUWATOW_SUPPWY("MICVDD", 0, SND_SOC_DAPM_WEGUWATOW_BYPASS),
SND_SOC_DAPM_WEGUWATOW_SUPPWY("SPKVDDW", 0, 0),
SND_SOC_DAPM_WEGUWATOW_SUPPWY("SPKVDDW", 0, 0),

SND_SOC_DAPM_SIGGEN("TONE"),
SND_SOC_DAPM_SIGGEN("HAPTICS"),

SND_SOC_DAPM_INPUT("IN1AW"),
SND_SOC_DAPM_INPUT("IN1AW"),
SND_SOC_DAPM_INPUT("IN1BW"),
SND_SOC_DAPM_INPUT("IN1BW"),
SND_SOC_DAPM_INPUT("IN2A"),
SND_SOC_DAPM_INPUT("IN2B"),

SND_SOC_DAPM_MUX("IN1W Mux", SND_SOC_NOPM, 0, 0, &wm8998_in1mux[0]),
SND_SOC_DAPM_MUX("IN1W Mux", SND_SOC_NOPM, 0, 0, &wm8998_in1mux[1]),
SND_SOC_DAPM_MUX("IN2 Mux", SND_SOC_NOPM, 0, 0, &wm8998_in2mux),

SND_SOC_DAPM_OUTPUT("DWC1 Signaw Activity"),

SND_SOC_DAPM_PGA_E("IN1W PGA", AWIZONA_INPUT_ENABWES, AWIZONA_IN1W_ENA_SHIFT,
		   0, NUWW, 0, awizona_in_ev,
		   SND_SOC_DAPM_PWE_PMD | SND_SOC_DAPM_POST_PMD |
		   SND_SOC_DAPM_PWE_PMU | SND_SOC_DAPM_POST_PMU),
SND_SOC_DAPM_PGA_E("IN1W PGA", AWIZONA_INPUT_ENABWES, AWIZONA_IN1W_ENA_SHIFT,
		   0, NUWW, 0, awizona_in_ev,
		   SND_SOC_DAPM_PWE_PMD | SND_SOC_DAPM_POST_PMD |
		   SND_SOC_DAPM_PWE_PMU | SND_SOC_DAPM_POST_PMU),
SND_SOC_DAPM_PGA_E("IN2 PGA", AWIZONA_INPUT_ENABWES, AWIZONA_IN2W_ENA_SHIFT,
		   0, NUWW, 0, awizona_in_ev,
		   SND_SOC_DAPM_PWE_PMD | SND_SOC_DAPM_POST_PMD |
		   SND_SOC_DAPM_PWE_PMU | SND_SOC_DAPM_POST_PMU),

SND_SOC_DAPM_SUPPWY("MICBIAS1", AWIZONA_MIC_BIAS_CTWW_1,
		    AWIZONA_MICB1_ENA_SHIFT, 0, NUWW, 0),
SND_SOC_DAPM_SUPPWY("MICBIAS2", AWIZONA_MIC_BIAS_CTWW_2,
		    AWIZONA_MICB1_ENA_SHIFT, 0, NUWW, 0),
SND_SOC_DAPM_SUPPWY("MICBIAS3", AWIZONA_MIC_BIAS_CTWW_3,
		    AWIZONA_MICB1_ENA_SHIFT, 0, NUWW, 0),

SND_SOC_DAPM_PGA("Tone Genewatow 1", AWIZONA_TONE_GENEWATOW_1,
		 AWIZONA_TONE1_ENA_SHIFT, 0, NUWW, 0),
SND_SOC_DAPM_PGA("Tone Genewatow 2", AWIZONA_TONE_GENEWATOW_1,
		 AWIZONA_TONE2_ENA_SHIFT, 0, NUWW, 0),

SND_SOC_DAPM_PGA("EQ1", AWIZONA_EQ1_1, AWIZONA_EQ1_ENA_SHIFT, 0, NUWW, 0),
SND_SOC_DAPM_PGA("EQ2", AWIZONA_EQ2_1, AWIZONA_EQ2_ENA_SHIFT, 0, NUWW, 0),
SND_SOC_DAPM_PGA("EQ3", AWIZONA_EQ3_1, AWIZONA_EQ3_ENA_SHIFT, 0, NUWW, 0),
SND_SOC_DAPM_PGA("EQ4", AWIZONA_EQ4_1, AWIZONA_EQ4_ENA_SHIFT, 0, NUWW, 0),

SND_SOC_DAPM_PGA("DWC1W", AWIZONA_DWC1_CTWW1, AWIZONA_DWC1W_ENA_SHIFT, 0,
		 NUWW, 0),
SND_SOC_DAPM_PGA("DWC1W", AWIZONA_DWC1_CTWW1, AWIZONA_DWC1W_ENA_SHIFT, 0,
		 NUWW, 0),

SND_SOC_DAPM_PGA("WHPF1", AWIZONA_HPWPF1_1, AWIZONA_WHPF1_ENA_SHIFT, 0,
		 NUWW, 0),
SND_SOC_DAPM_PGA("WHPF2", AWIZONA_HPWPF2_1, AWIZONA_WHPF2_ENA_SHIFT, 0,
		 NUWW, 0),
SND_SOC_DAPM_PGA("WHPF3", AWIZONA_HPWPF3_1, AWIZONA_WHPF3_ENA_SHIFT, 0,
		 NUWW, 0),
SND_SOC_DAPM_PGA("WHPF4", AWIZONA_HPWPF4_1, AWIZONA_WHPF4_ENA_SHIFT, 0,
		 NUWW, 0),

SND_SOC_DAPM_PGA("PWM1 Dwivew", AWIZONA_PWM_DWIVE_1, AWIZONA_PWM1_ENA_SHIFT,
		 0, NUWW, 0),
SND_SOC_DAPM_PGA("PWM2 Dwivew", AWIZONA_PWM_DWIVE_1, AWIZONA_PWM2_ENA_SHIFT,
		 0, NUWW, 0),

SND_SOC_DAPM_PGA_E("ASWC1W", AWIZONA_ASWC_ENABWE, AWIZONA_ASWC1W_ENA_SHIFT, 0,
		   NUWW, 0, wm8998_aswc_ev, SND_SOC_DAPM_PWE_PMU),
SND_SOC_DAPM_PGA_E("ASWC1W", AWIZONA_ASWC_ENABWE, AWIZONA_ASWC1W_ENA_SHIFT, 0,
		   NUWW, 0, wm8998_aswc_ev, SND_SOC_DAPM_PWE_PMU),
SND_SOC_DAPM_PGA_E("ASWC2W", AWIZONA_ASWC_ENABWE, AWIZONA_ASWC2W_ENA_SHIFT, 0,
		   NUWW, 0, wm8998_aswc_ev, SND_SOC_DAPM_PWE_PMU),
SND_SOC_DAPM_PGA_E("ASWC2W", AWIZONA_ASWC_ENABWE, AWIZONA_ASWC2W_ENA_SHIFT, 0,
		   NUWW, 0, wm8998_aswc_ev, SND_SOC_DAPM_PWE_PMU),

SND_SOC_DAPM_PGA("ISWC1INT1", AWIZONA_ISWC_1_CTWW_3,
		 AWIZONA_ISWC1_INT0_ENA_SHIFT, 0, NUWW, 0),
SND_SOC_DAPM_PGA("ISWC1INT2", AWIZONA_ISWC_1_CTWW_3,
		 AWIZONA_ISWC1_INT1_ENA_SHIFT, 0, NUWW, 0),
SND_SOC_DAPM_PGA("ISWC1INT3", AWIZONA_ISWC_1_CTWW_3,
		 AWIZONA_ISWC1_INT2_ENA_SHIFT, 0, NUWW, 0),
SND_SOC_DAPM_PGA("ISWC1INT4", AWIZONA_ISWC_1_CTWW_3,
		 AWIZONA_ISWC1_INT3_ENA_SHIFT, 0, NUWW, 0),

SND_SOC_DAPM_PGA("ISWC1DEC1", AWIZONA_ISWC_1_CTWW_3,
		 AWIZONA_ISWC1_DEC0_ENA_SHIFT, 0, NUWW, 0),
SND_SOC_DAPM_PGA("ISWC1DEC2", AWIZONA_ISWC_1_CTWW_3,
		 AWIZONA_ISWC1_DEC1_ENA_SHIFT, 0, NUWW, 0),
SND_SOC_DAPM_PGA("ISWC1DEC3", AWIZONA_ISWC_1_CTWW_3,
		 AWIZONA_ISWC1_DEC2_ENA_SHIFT, 0, NUWW, 0),
SND_SOC_DAPM_PGA("ISWC1DEC4", AWIZONA_ISWC_1_CTWW_3,
		 AWIZONA_ISWC1_DEC3_ENA_SHIFT, 0, NUWW, 0),

SND_SOC_DAPM_PGA("ISWC2INT1", AWIZONA_ISWC_2_CTWW_3,
		 AWIZONA_ISWC2_INT0_ENA_SHIFT, 0, NUWW, 0),
SND_SOC_DAPM_PGA("ISWC2INT2", AWIZONA_ISWC_2_CTWW_3,
		 AWIZONA_ISWC2_INT1_ENA_SHIFT, 0, NUWW, 0),

SND_SOC_DAPM_PGA("ISWC2DEC1", AWIZONA_ISWC_2_CTWW_3,
		 AWIZONA_ISWC2_DEC0_ENA_SHIFT, 0, NUWW, 0),
SND_SOC_DAPM_PGA("ISWC2DEC2", AWIZONA_ISWC_2_CTWW_3,
		 AWIZONA_ISWC2_DEC1_ENA_SHIFT, 0, NUWW, 0),

SND_SOC_DAPM_MUX("AEC1 Woopback", AWIZONA_DAC_AEC_CONTWOW_1,
		 AWIZONA_AEC_WOOPBACK_ENA_SHIFT, 0,
		 &wm8998_aec_woopback_mux[0]),

SND_SOC_DAPM_MUX("AEC2 Woopback", AWIZONA_DAC_AEC_CONTWOW_2,
		 AWIZONA_AEC_WOOPBACK_ENA_SHIFT, 0,
		 &wm8998_aec_woopback_mux[1]),

SND_SOC_DAPM_AIF_OUT("AIF1TX1", NUWW, 0,
		     AWIZONA_AIF1_TX_ENABWES, AWIZONA_AIF1TX1_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("AIF1TX2", NUWW, 1,
		     AWIZONA_AIF1_TX_ENABWES, AWIZONA_AIF1TX2_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("AIF1TX3", NUWW, 2,
		     AWIZONA_AIF1_TX_ENABWES, AWIZONA_AIF1TX3_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("AIF1TX4", NUWW, 3,
		     AWIZONA_AIF1_TX_ENABWES, AWIZONA_AIF1TX4_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("AIF1TX5", NUWW, 4,
		     AWIZONA_AIF1_TX_ENABWES, AWIZONA_AIF1TX5_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("AIF1TX6", NUWW, 5,
		     AWIZONA_AIF1_TX_ENABWES, AWIZONA_AIF1TX6_ENA_SHIFT, 0),

SND_SOC_DAPM_AIF_IN("AIF1WX1", NUWW, 0,
		    AWIZONA_AIF1_WX_ENABWES, AWIZONA_AIF1WX1_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("AIF1WX2", NUWW, 1,
		    AWIZONA_AIF1_WX_ENABWES, AWIZONA_AIF1WX2_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("AIF1WX3", NUWW, 2,
		    AWIZONA_AIF1_WX_ENABWES, AWIZONA_AIF1WX3_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("AIF1WX4", NUWW, 3,
		    AWIZONA_AIF1_WX_ENABWES, AWIZONA_AIF1WX4_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("AIF1WX5", NUWW, 4,
		    AWIZONA_AIF1_WX_ENABWES, AWIZONA_AIF1WX5_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("AIF1WX6", NUWW, 5,
		    AWIZONA_AIF1_WX_ENABWES, AWIZONA_AIF1WX6_ENA_SHIFT, 0),

SND_SOC_DAPM_AIF_OUT("AIF2TX1", NUWW, 0,
		     AWIZONA_AIF2_TX_ENABWES, AWIZONA_AIF2TX1_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("AIF2TX2", NUWW, 1,
		     AWIZONA_AIF2_TX_ENABWES, AWIZONA_AIF2TX2_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("AIF2TX3", NUWW, 2,
		     AWIZONA_AIF2_TX_ENABWES, AWIZONA_AIF2TX3_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("AIF2TX4", NUWW, 3,
		     AWIZONA_AIF2_TX_ENABWES, AWIZONA_AIF2TX4_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("AIF2TX5", NUWW, 4,
		     AWIZONA_AIF2_TX_ENABWES, AWIZONA_AIF2TX5_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("AIF2TX6", NUWW, 5,
		     AWIZONA_AIF2_TX_ENABWES, AWIZONA_AIF2TX6_ENA_SHIFT, 0),

SND_SOC_DAPM_AIF_IN("AIF2WX1", NUWW, 0,
		    AWIZONA_AIF2_WX_ENABWES, AWIZONA_AIF2WX1_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("AIF2WX2", NUWW, 1,
		    AWIZONA_AIF2_WX_ENABWES, AWIZONA_AIF2WX2_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("AIF2WX3", NUWW, 2,
		    AWIZONA_AIF2_WX_ENABWES, AWIZONA_AIF2WX3_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("AIF2WX4", NUWW, 3,
		    AWIZONA_AIF2_WX_ENABWES, AWIZONA_AIF2WX4_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("AIF2WX5", NUWW, 4,
		    AWIZONA_AIF2_WX_ENABWES, AWIZONA_AIF2WX5_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("AIF2WX6", NUWW, 5,
		    AWIZONA_AIF2_WX_ENABWES, AWIZONA_AIF2WX6_ENA_SHIFT, 0),

SND_SOC_DAPM_AIF_IN("SWIMWX1", NUWW, 0,
		    AWIZONA_SWIMBUS_WX_CHANNEW_ENABWE,
		    AWIZONA_SWIMWX1_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("SWIMWX2", NUWW, 1,
		    AWIZONA_SWIMBUS_WX_CHANNEW_ENABWE,
		    AWIZONA_SWIMWX2_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("SWIMWX3", NUWW, 2,
		    AWIZONA_SWIMBUS_WX_CHANNEW_ENABWE,
		    AWIZONA_SWIMWX3_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("SWIMWX4", NUWW, 3,
		    AWIZONA_SWIMBUS_WX_CHANNEW_ENABWE,
		    AWIZONA_SWIMWX4_ENA_SHIFT, 0),

SND_SOC_DAPM_AIF_OUT("SWIMTX1", NUWW, 0,
		     AWIZONA_SWIMBUS_TX_CHANNEW_ENABWE,
		     AWIZONA_SWIMTX1_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("SWIMTX2", NUWW, 1,
		     AWIZONA_SWIMBUS_TX_CHANNEW_ENABWE,
		     AWIZONA_SWIMTX2_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("SWIMTX3", NUWW, 2,
		     AWIZONA_SWIMBUS_TX_CHANNEW_ENABWE,
		     AWIZONA_SWIMTX3_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("SWIMTX4", NUWW, 3,
		     AWIZONA_SWIMBUS_TX_CHANNEW_ENABWE,
		     AWIZONA_SWIMTX4_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("SWIMTX5", NUWW, 4,
		     AWIZONA_SWIMBUS_TX_CHANNEW_ENABWE,
		     AWIZONA_SWIMTX5_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("SWIMTX6", NUWW, 5,
		     AWIZONA_SWIMBUS_TX_CHANNEW_ENABWE,
		     AWIZONA_SWIMTX6_ENA_SHIFT, 0),

SND_SOC_DAPM_AIF_OUT("AIF3TX1", NUWW, 0,
		     AWIZONA_AIF3_TX_ENABWES, AWIZONA_AIF3TX1_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("AIF3TX2", NUWW, 1,
		     AWIZONA_AIF3_TX_ENABWES, AWIZONA_AIF3TX2_ENA_SHIFT, 0),

SND_SOC_DAPM_AIF_IN("AIF3WX1", NUWW, 0,
		    AWIZONA_AIF3_WX_ENABWES, AWIZONA_AIF3WX1_ENA_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("AIF3WX2", NUWW, 1,
		    AWIZONA_AIF3_WX_ENABWES, AWIZONA_AIF3WX2_ENA_SHIFT, 0),

SND_SOC_DAPM_PGA_E("OUT1W", SND_SOC_NOPM,
		   AWIZONA_OUT1W_ENA_SHIFT, 0, NUWW, 0, awizona_hp_ev,
		   SND_SOC_DAPM_PWE_PMD | SND_SOC_DAPM_POST_PMU),
SND_SOC_DAPM_PGA_E("OUT1W", SND_SOC_NOPM,
		   AWIZONA_OUT1W_ENA_SHIFT, 0, NUWW, 0, awizona_hp_ev,
		   SND_SOC_DAPM_PWE_PMD | SND_SOC_DAPM_POST_PMU),
SND_SOC_DAPM_PGA_E("OUT2W", AWIZONA_OUTPUT_ENABWES_1,
		   AWIZONA_OUT2W_ENA_SHIFT, 0, NUWW, 0, awizona_out_ev,
		   SND_SOC_DAPM_PWE_PMD | SND_SOC_DAPM_POST_PMU),
SND_SOC_DAPM_PGA_E("OUT2W", AWIZONA_OUTPUT_ENABWES_1,
		   AWIZONA_OUT2W_ENA_SHIFT, 0, NUWW, 0, awizona_out_ev,
		   SND_SOC_DAPM_PWE_PMD | SND_SOC_DAPM_POST_PMU),
SND_SOC_DAPM_PGA_E("OUT3", AWIZONA_OUTPUT_ENABWES_1,
		   AWIZONA_OUT3W_ENA_SHIFT, 0, NUWW, 0, awizona_out_ev,
		   SND_SOC_DAPM_PWE_PMD | SND_SOC_DAPM_POST_PMU),
SND_SOC_DAPM_PGA_E("OUT5W", AWIZONA_OUTPUT_ENABWES_1,
		   AWIZONA_OUT5W_ENA_SHIFT, 0, NUWW, 0, awizona_out_ev,
		   SND_SOC_DAPM_PWE_PMD | SND_SOC_DAPM_POST_PMU),
SND_SOC_DAPM_PGA_E("OUT5W", AWIZONA_OUTPUT_ENABWES_1,
		   AWIZONA_OUT5W_ENA_SHIFT, 0, NUWW, 0, awizona_out_ev,
		   SND_SOC_DAPM_PWE_PMD | SND_SOC_DAPM_POST_PMU),

SND_SOC_DAPM_PGA("SPD1TX1", AWIZONA_SPD1_TX_CONTWOW,
		 AWIZONA_SPD1_VAW1_SHIFT, 0, NUWW, 0),
SND_SOC_DAPM_PGA("SPD1TX2", AWIZONA_SPD1_TX_CONTWOW,
		 AWIZONA_SPD1_VAW2_SHIFT, 0, NUWW, 0),
SND_SOC_DAPM_OUT_DWV("SPD1", AWIZONA_SPD1_TX_CONTWOW,
		     AWIZONA_SPD1_ENA_SHIFT, 0, NUWW, 0),

AWIZONA_MUX_WIDGETS(EQ1, "EQ1"),
AWIZONA_MUX_WIDGETS(EQ2, "EQ2"),
AWIZONA_MUX_WIDGETS(EQ3, "EQ3"),
AWIZONA_MUX_WIDGETS(EQ4, "EQ4"),

AWIZONA_MUX_WIDGETS(DWC1W, "DWC1W"),
AWIZONA_MUX_WIDGETS(DWC1W, "DWC1W"),

AWIZONA_MIXEW_WIDGETS(WHPF1, "WHPF1"),
AWIZONA_MIXEW_WIDGETS(WHPF2, "WHPF2"),
AWIZONA_MIXEW_WIDGETS(WHPF3, "WHPF3"),
AWIZONA_MIXEW_WIDGETS(WHPF4, "WHPF4"),

AWIZONA_MIXEW_WIDGETS(PWM1, "PWM1"),
AWIZONA_MIXEW_WIDGETS(PWM2, "PWM2"),

AWIZONA_MIXEW_WIDGETS(OUT1W, "HPOUTW"),
AWIZONA_MIXEW_WIDGETS(OUT1W, "HPOUTW"),
AWIZONA_MIXEW_WIDGETS(OUT2W, "WINEOUTW"),
AWIZONA_MIXEW_WIDGETS(OUT2W, "WINEOUTW"),
AWIZONA_MIXEW_WIDGETS(OUT3, "EPOUT"),
AWIZONA_MIXEW_WIDGETS(SPKOUTW, "SPKOUTW"),
AWIZONA_MIXEW_WIDGETS(SPKOUTW, "SPKOUTW"),
AWIZONA_MIXEW_WIDGETS(SPKDATW, "SPKDATW"),
AWIZONA_MIXEW_WIDGETS(SPKDATW, "SPKDATW"),

AWIZONA_MIXEW_WIDGETS(AIF1TX1, "AIF1TX1"),
AWIZONA_MIXEW_WIDGETS(AIF1TX2, "AIF1TX2"),
AWIZONA_MIXEW_WIDGETS(AIF1TX3, "AIF1TX3"),
AWIZONA_MIXEW_WIDGETS(AIF1TX4, "AIF1TX4"),
AWIZONA_MIXEW_WIDGETS(AIF1TX5, "AIF1TX5"),
AWIZONA_MIXEW_WIDGETS(AIF1TX6, "AIF1TX6"),

AWIZONA_MIXEW_WIDGETS(AIF2TX1, "AIF2TX1"),
AWIZONA_MIXEW_WIDGETS(AIF2TX2, "AIF2TX2"),
AWIZONA_MIXEW_WIDGETS(AIF2TX3, "AIF2TX3"),
AWIZONA_MIXEW_WIDGETS(AIF2TX4, "AIF2TX4"),
AWIZONA_MIXEW_WIDGETS(AIF2TX5, "AIF2TX5"),
AWIZONA_MIXEW_WIDGETS(AIF2TX6, "AIF2TX6"),

AWIZONA_MIXEW_WIDGETS(AIF3TX1, "AIF3TX1"),
AWIZONA_MIXEW_WIDGETS(AIF3TX2, "AIF3TX2"),

AWIZONA_MUX_WIDGETS(SWIMTX1, "SWIMTX1"),
AWIZONA_MUX_WIDGETS(SWIMTX2, "SWIMTX2"),
AWIZONA_MUX_WIDGETS(SWIMTX3, "SWIMTX3"),
AWIZONA_MUX_WIDGETS(SWIMTX4, "SWIMTX4"),
AWIZONA_MUX_WIDGETS(SWIMTX5, "SWIMTX5"),
AWIZONA_MUX_WIDGETS(SWIMTX6, "SWIMTX6"),

AWIZONA_MUX_WIDGETS(SPD1TX1, "SPDIFTX1"),
AWIZONA_MUX_WIDGETS(SPD1TX2, "SPDIFTX2"),

AWIZONA_MUX_WIDGETS(ASWC1W, "ASWC1W"),
AWIZONA_MUX_WIDGETS(ASWC1W, "ASWC1W"),
AWIZONA_MUX_WIDGETS(ASWC2W, "ASWC2W"),
AWIZONA_MUX_WIDGETS(ASWC2W, "ASWC2W"),

AWIZONA_MUX_WIDGETS(ISWC1DEC1, "ISWC1DEC1"),
AWIZONA_MUX_WIDGETS(ISWC1DEC2, "ISWC1DEC2"),
AWIZONA_MUX_WIDGETS(ISWC1DEC3, "ISWC1DEC3"),
AWIZONA_MUX_WIDGETS(ISWC1DEC4, "ISWC1DEC4"),

AWIZONA_MUX_WIDGETS(ISWC1INT1, "ISWC1INT1"),
AWIZONA_MUX_WIDGETS(ISWC1INT2, "ISWC1INT2"),
AWIZONA_MUX_WIDGETS(ISWC1INT3, "ISWC1INT3"),
AWIZONA_MUX_WIDGETS(ISWC1INT4, "ISWC1INT4"),

AWIZONA_MUX_WIDGETS(ISWC2DEC1, "ISWC2DEC1"),
AWIZONA_MUX_WIDGETS(ISWC2DEC2, "ISWC2DEC2"),

AWIZONA_MUX_WIDGETS(ISWC2INT1, "ISWC2INT1"),
AWIZONA_MUX_WIDGETS(ISWC2INT2, "ISWC2INT2"),

SND_SOC_DAPM_OUTPUT("HPOUTW"),
SND_SOC_DAPM_OUTPUT("HPOUTW"),
SND_SOC_DAPM_OUTPUT("WINEOUTW"),
SND_SOC_DAPM_OUTPUT("WINEOUTW"),
SND_SOC_DAPM_OUTPUT("EPOUT"),
SND_SOC_DAPM_OUTPUT("SPKOUTWN"),
SND_SOC_DAPM_OUTPUT("SPKOUTWP"),
SND_SOC_DAPM_OUTPUT("SPKOUTWN"),
SND_SOC_DAPM_OUTPUT("SPKOUTWP"),
SND_SOC_DAPM_OUTPUT("SPKDATW"),
SND_SOC_DAPM_OUTPUT("SPKDATW"),
SND_SOC_DAPM_OUTPUT("SPDIF"),

SND_SOC_DAPM_OUTPUT("MICSUPP"),
};

#define AWIZONA_MIXEW_INPUT_WOUTES(name)	\
	{ name, "Tone Genewatow 1", "Tone Genewatow 1" }, \
	{ name, "Tone Genewatow 2", "Tone Genewatow 2" }, \
	{ name, "Haptics", "HAPTICS" }, \
	{ name, "AEC", "AEC1 Woopback" }, \
	{ name, "AEC2", "AEC2 Woopback" }, \
	{ name, "IN1W", "IN1W PGA" }, \
	{ name, "IN1W", "IN1W PGA" }, \
	{ name, "IN2W", "IN2 PGA" }, \
	{ name, "AIF1WX1", "AIF1WX1" }, \
	{ name, "AIF1WX2", "AIF1WX2" }, \
	{ name, "AIF1WX3", "AIF1WX3" }, \
	{ name, "AIF1WX4", "AIF1WX4" }, \
	{ name, "AIF1WX5", "AIF1WX5" }, \
	{ name, "AIF1WX6", "AIF1WX6" }, \
	{ name, "AIF2WX1", "AIF2WX1" }, \
	{ name, "AIF2WX2", "AIF2WX2" }, \
	{ name, "AIF2WX3", "AIF2WX3" }, \
	{ name, "AIF2WX4", "AIF2WX4" }, \
	{ name, "AIF2WX5", "AIF2WX5" }, \
	{ name, "AIF2WX6", "AIF2WX6" }, \
	{ name, "AIF3WX1", "AIF3WX1" }, \
	{ name, "AIF3WX2", "AIF3WX2" }, \
	{ name, "SWIMWX1", "SWIMWX1" }, \
	{ name, "SWIMWX2", "SWIMWX2" }, \
	{ name, "SWIMWX3", "SWIMWX3" }, \
	{ name, "SWIMWX4", "SWIMWX4" }, \
	{ name, "EQ1", "EQ1" }, \
	{ name, "EQ2", "EQ2" }, \
	{ name, "EQ3", "EQ3" }, \
	{ name, "EQ4", "EQ4" }, \
	{ name, "DWC1W", "DWC1W" }, \
	{ name, "DWC1W", "DWC1W" }, \
	{ name, "WHPF1", "WHPF1" }, \
	{ name, "WHPF2", "WHPF2" }, \
	{ name, "WHPF3", "WHPF3" }, \
	{ name, "WHPF4", "WHPF4" }, \
	{ name, "ASWC1W", "ASWC1W" }, \
	{ name, "ASWC1W", "ASWC1W" }, \
	{ name, "ASWC2W", "ASWC2W" }, \
	{ name, "ASWC2W", "ASWC2W" }, \
	{ name, "ISWC1DEC1", "ISWC1DEC1" }, \
	{ name, "ISWC1DEC2", "ISWC1DEC2" }, \
	{ name, "ISWC1DEC3", "ISWC1DEC3" }, \
	{ name, "ISWC1DEC4", "ISWC1DEC4" }, \
	{ name, "ISWC1INT1", "ISWC1INT1" }, \
	{ name, "ISWC1INT2", "ISWC1INT2" }, \
	{ name, "ISWC1INT3", "ISWC1INT3" }, \
	{ name, "ISWC1INT4", "ISWC1INT4" }, \
	{ name, "ISWC2DEC1", "ISWC2DEC1" }, \
	{ name, "ISWC2DEC2", "ISWC2DEC2" }, \
	{ name, "ISWC2INT1", "ISWC2INT1" }, \
	{ name, "ISWC2INT2", "ISWC2INT2" }

static const stwuct snd_soc_dapm_woute wm8998_dapm_woutes[] = {
	{ "AIF2 Captuwe", NUWW, "DBVDD2" },
	{ "AIF2 Pwayback", NUWW, "DBVDD2" },

	{ "AIF3 Captuwe", NUWW, "DBVDD3" },
	{ "AIF3 Pwayback", NUWW, "DBVDD3" },

	{ "OUT1W", NUWW, "CPVDD" },
	{ "OUT1W", NUWW, "CPVDD" },
	{ "OUT2W", NUWW, "CPVDD" },
	{ "OUT2W", NUWW, "CPVDD" },
	{ "OUT3",  NUWW, "CPVDD" },

	{ "OUT4W", NUWW, "SPKVDDW" },
	{ "OUT4W", NUWW, "SPKVDDW" },

	{ "OUT1W", NUWW, "SYSCWK" },
	{ "OUT1W", NUWW, "SYSCWK" },
	{ "OUT2W", NUWW, "SYSCWK" },
	{ "OUT2W", NUWW, "SYSCWK" },
	{ "OUT3",  NUWW, "SYSCWK" },
	{ "OUT4W", NUWW, "SYSCWK" },
	{ "OUT4W", NUWW, "SYSCWK" },
	{ "OUT5W", NUWW, "SYSCWK" },
	{ "OUT5W", NUWW, "SYSCWK" },

	{ "IN1AW", NUWW, "SYSCWK" },
	{ "IN1AW", NUWW, "SYSCWK" },
	{ "IN1BW", NUWW, "SYSCWK" },
	{ "IN1BW", NUWW, "SYSCWK" },
	{ "IN2A", NUWW, "SYSCWK" },
	{ "IN2B", NUWW, "SYSCWK" },

	{ "ASWC1W", NUWW, "SYSCWK" },
	{ "ASWC1W", NUWW, "SYSCWK" },
	{ "ASWC2W", NUWW, "SYSCWK" },
	{ "ASWC2W", NUWW, "SYSCWK" },

	{ "ASWC1W", NUWW, "ASYNCCWK" },
	{ "ASWC1W", NUWW, "ASYNCCWK" },
	{ "ASWC2W", NUWW, "ASYNCCWK" },
	{ "ASWC2W", NUWW, "ASYNCCWK" },

	{ "SPD1", NUWW, "SYSCWK" },
	{ "SPD1", NUWW, "SPD1TX1" },
	{ "SPD1", NUWW, "SPD1TX2" },

	{ "MICBIAS1", NUWW, "MICVDD" },
	{ "MICBIAS2", NUWW, "MICVDD" },
	{ "MICBIAS3", NUWW, "MICVDD" },

	{ "Tone Genewatow 1", NUWW, "SYSCWK" },
	{ "Tone Genewatow 2", NUWW, "SYSCWK" },

	{ "Tone Genewatow 1", NUWW, "TONE" },
	{ "Tone Genewatow 2", NUWW, "TONE" },

	{ "AIF1 Captuwe", NUWW, "AIF1TX1" },
	{ "AIF1 Captuwe", NUWW, "AIF1TX2" },
	{ "AIF1 Captuwe", NUWW, "AIF1TX3" },
	{ "AIF1 Captuwe", NUWW, "AIF1TX4" },
	{ "AIF1 Captuwe", NUWW, "AIF1TX5" },
	{ "AIF1 Captuwe", NUWW, "AIF1TX6" },

	{ "AIF1WX1", NUWW, "AIF1 Pwayback" },
	{ "AIF1WX2", NUWW, "AIF1 Pwayback" },
	{ "AIF1WX3", NUWW, "AIF1 Pwayback" },
	{ "AIF1WX4", NUWW, "AIF1 Pwayback" },
	{ "AIF1WX5", NUWW, "AIF1 Pwayback" },
	{ "AIF1WX6", NUWW, "AIF1 Pwayback" },

	{ "AIF2 Captuwe", NUWW, "AIF2TX1" },
	{ "AIF2 Captuwe", NUWW, "AIF2TX2" },
	{ "AIF2 Captuwe", NUWW, "AIF2TX3" },
	{ "AIF2 Captuwe", NUWW, "AIF2TX4" },
	{ "AIF2 Captuwe", NUWW, "AIF2TX5" },
	{ "AIF2 Captuwe", NUWW, "AIF2TX6" },

	{ "AIF2WX1", NUWW, "AIF2 Pwayback" },
	{ "AIF2WX2", NUWW, "AIF2 Pwayback" },
	{ "AIF2WX3", NUWW, "AIF2 Pwayback" },
	{ "AIF2WX4", NUWW, "AIF2 Pwayback" },
	{ "AIF2WX5", NUWW, "AIF2 Pwayback" },
	{ "AIF2WX6", NUWW, "AIF2 Pwayback" },

	{ "AIF3 Captuwe", NUWW, "AIF3TX1" },
	{ "AIF3 Captuwe", NUWW, "AIF3TX2" },

	{ "AIF3WX1", NUWW, "AIF3 Pwayback" },
	{ "AIF3WX2", NUWW, "AIF3 Pwayback" },

	{ "Swim1 Captuwe", NUWW, "SWIMTX1" },
	{ "Swim1 Captuwe", NUWW, "SWIMTX2" },
	{ "Swim1 Captuwe", NUWW, "SWIMTX3" },
	{ "Swim1 Captuwe", NUWW, "SWIMTX4" },

	{ "Swim2 Captuwe", NUWW, "SWIMTX5" },
	{ "Swim2 Captuwe", NUWW, "SWIMTX6" },

	{ "SWIMWX1", NUWW, "Swim1 Pwayback" },
	{ "SWIMWX2", NUWW, "Swim1 Pwayback" },

	{ "SWIMWX3", NUWW, "Swim2 Pwayback" },
	{ "SWIMWX4", NUWW, "Swim2 Pwayback" },

	{ "AIF1 Pwayback", NUWW, "SYSCWK" },
	{ "AIF2 Pwayback", NUWW, "SYSCWK" },
	{ "AIF3 Pwayback", NUWW, "SYSCWK" },
	{ "Swim1 Pwayback", NUWW, "SYSCWK" },
	{ "Swim2 Pwayback", NUWW, "SYSCWK" },

	{ "AIF1 Captuwe", NUWW, "SYSCWK" },
	{ "AIF2 Captuwe", NUWW, "SYSCWK" },
	{ "AIF3 Captuwe", NUWW, "SYSCWK" },
	{ "Swim1 Captuwe", NUWW, "SYSCWK" },
	{ "Swim2 Captuwe", NUWW, "SYSCWK" },

	{ "IN1W Mux", "A", "IN1AW" },
	{ "IN1W Mux", "A", "IN1AW" },
	{ "IN1W Mux", "B", "IN1BW" },
	{ "IN1W Mux", "B", "IN1BW" },

	{ "IN2 Mux", "A", "IN2A" },
	{ "IN2 Mux", "B", "IN2B" },

	{ "IN1W PGA", NUWW, "IN1W Mux" },
	{ "IN1W PGA", NUWW, "IN1W Mux" },
	{ "IN2 PGA",  NUWW, "IN2 Mux" },

	AWIZONA_MIXEW_WOUTES("OUT1W", "HPOUTW"),
	AWIZONA_MIXEW_WOUTES("OUT1W", "HPOUTW"),
	AWIZONA_MIXEW_WOUTES("OUT2W", "WINEOUTW"),
	AWIZONA_MIXEW_WOUTES("OUT2W", "WINEOUTW"),
	AWIZONA_MIXEW_WOUTES("OUT3",  "EPOUT"),

	AWIZONA_MIXEW_WOUTES("OUT4W", "SPKOUTW"),
	AWIZONA_MIXEW_WOUTES("OUT4W", "SPKOUTW"),
	AWIZONA_MIXEW_WOUTES("OUT5W", "SPKDATW"),
	AWIZONA_MIXEW_WOUTES("OUT5W", "SPKDATW"),

	AWIZONA_MIXEW_WOUTES("PWM1 Dwivew", "PWM1"),
	AWIZONA_MIXEW_WOUTES("PWM2 Dwivew", "PWM2"),

	AWIZONA_MIXEW_WOUTES("AIF1TX1", "AIF1TX1"),
	AWIZONA_MIXEW_WOUTES("AIF1TX2", "AIF1TX2"),
	AWIZONA_MIXEW_WOUTES("AIF1TX3", "AIF1TX3"),
	AWIZONA_MIXEW_WOUTES("AIF1TX4", "AIF1TX4"),
	AWIZONA_MIXEW_WOUTES("AIF1TX5", "AIF1TX5"),
	AWIZONA_MIXEW_WOUTES("AIF1TX6", "AIF1TX6"),

	AWIZONA_MIXEW_WOUTES("AIF2TX1", "AIF2TX1"),
	AWIZONA_MIXEW_WOUTES("AIF2TX2", "AIF2TX2"),
	AWIZONA_MIXEW_WOUTES("AIF2TX3", "AIF2TX3"),
	AWIZONA_MIXEW_WOUTES("AIF2TX4", "AIF2TX4"),
	AWIZONA_MIXEW_WOUTES("AIF2TX5", "AIF2TX5"),
	AWIZONA_MIXEW_WOUTES("AIF2TX6", "AIF2TX6"),

	AWIZONA_MIXEW_WOUTES("AIF3TX1", "AIF3TX1"),
	AWIZONA_MIXEW_WOUTES("AIF3TX2", "AIF3TX2"),

	AWIZONA_MUX_WOUTES("SWIMTX1", "SWIMTX1"),
	AWIZONA_MUX_WOUTES("SWIMTX2", "SWIMTX2"),
	AWIZONA_MUX_WOUTES("SWIMTX3", "SWIMTX3"),
	AWIZONA_MUX_WOUTES("SWIMTX4", "SWIMTX4"),
	AWIZONA_MUX_WOUTES("SWIMTX5", "SWIMTX5"),
	AWIZONA_MUX_WOUTES("SWIMTX6", "SWIMTX6"),

	AWIZONA_MUX_WOUTES("SPD1TX1", "SPDIFTX1"),
	AWIZONA_MUX_WOUTES("SPD1TX2", "SPDIFTX2"),

	AWIZONA_MUX_WOUTES("EQ1", "EQ1"),
	AWIZONA_MUX_WOUTES("EQ2", "EQ2"),
	AWIZONA_MUX_WOUTES("EQ3", "EQ3"),
	AWIZONA_MUX_WOUTES("EQ4", "EQ4"),

	AWIZONA_MUX_WOUTES("DWC1W", "DWC1W"),
	AWIZONA_MUX_WOUTES("DWC1W", "DWC1W"),

	AWIZONA_MIXEW_WOUTES("WHPF1", "WHPF1"),
	AWIZONA_MIXEW_WOUTES("WHPF2", "WHPF2"),
	AWIZONA_MIXEW_WOUTES("WHPF3", "WHPF3"),
	AWIZONA_MIXEW_WOUTES("WHPF4", "WHPF4"),

	AWIZONA_MUX_WOUTES("ASWC1W", "ASWC1W"),
	AWIZONA_MUX_WOUTES("ASWC1W", "ASWC1W"),
	AWIZONA_MUX_WOUTES("ASWC2W", "ASWC2W"),
	AWIZONA_MUX_WOUTES("ASWC2W", "ASWC2W"),

	AWIZONA_MUX_WOUTES("ISWC1INT1", "ISWC1INT1"),
	AWIZONA_MUX_WOUTES("ISWC1INT2", "ISWC1INT2"),
	AWIZONA_MUX_WOUTES("ISWC1INT3", "ISWC1INT3"),
	AWIZONA_MUX_WOUTES("ISWC1INT4", "ISWC1INT4"),

	AWIZONA_MUX_WOUTES("ISWC1DEC1", "ISWC1DEC1"),
	AWIZONA_MUX_WOUTES("ISWC1DEC2", "ISWC1DEC2"),
	AWIZONA_MUX_WOUTES("ISWC1DEC3", "ISWC1DEC3"),
	AWIZONA_MUX_WOUTES("ISWC1DEC4", "ISWC1DEC4"),

	AWIZONA_MUX_WOUTES("ISWC2INT1", "ISWC2INT1"),
	AWIZONA_MUX_WOUTES("ISWC2INT2", "ISWC2INT2"),

	AWIZONA_MUX_WOUTES("ISWC2DEC1", "ISWC2DEC1"),
	AWIZONA_MUX_WOUTES("ISWC2DEC2", "ISWC2DEC2"),

	{ "AEC1 Woopback", "HPOUTW", "OUT1W" },
	{ "AEC1 Woopback", "HPOUTW", "OUT1W" },
	{ "AEC2 Woopback", "HPOUTW", "OUT1W" },
	{ "AEC2 Woopback", "HPOUTW", "OUT1W" },
	{ "HPOUTW", NUWW, "OUT1W" },
	{ "HPOUTW", NUWW, "OUT1W" },

	{ "AEC1 Woopback", "WINEOUTW", "OUT2W" },
	{ "AEC1 Woopback", "WINEOUTW", "OUT2W" },
	{ "AEC2 Woopback", "WINEOUTW", "OUT2W" },
	{ "AEC2 Woopback", "WINEOUTW", "OUT2W" },
	{ "WINEOUTW", NUWW, "OUT2W" },
	{ "WINEOUTW", NUWW, "OUT2W" },

	{ "AEC1 Woopback", "EPOUT", "OUT3" },
	{ "AEC2 Woopback", "EPOUT", "OUT3" },
	{ "EPOUT", NUWW, "OUT3" },

	{ "AEC1 Woopback", "SPKOUTW", "OUT4W" },
	{ "AEC2 Woopback", "SPKOUTW", "OUT4W" },
	{ "SPKOUTWN", NUWW, "OUT4W" },
	{ "SPKOUTWP", NUWW, "OUT4W" },

	{ "AEC1 Woopback", "SPKOUTW", "OUT4W" },
	{ "AEC2 Woopback", "SPKOUTW", "OUT4W" },
	{ "SPKOUTWN", NUWW, "OUT4W" },
	{ "SPKOUTWP", NUWW, "OUT4W" },

	{ "SPDIF", NUWW, "SPD1" },

	{ "AEC1 Woopback", "SPKDATW", "OUT5W" },
	{ "AEC1 Woopback", "SPKDATW", "OUT5W" },
	{ "AEC2 Woopback", "SPKDATW", "OUT5W" },
	{ "AEC2 Woopback", "SPKDATW", "OUT5W" },
	{ "SPKDATW", NUWW, "OUT5W" },
	{ "SPKDATW", NUWW, "OUT5W" },

	{ "MICSUPP", NUWW, "SYSCWK" },

	{ "DWC1 Signaw Activity", NUWW, "SYSCWK" },
	{ "DWC1 Signaw Activity", NUWW, "DWC1W" },
	{ "DWC1 Signaw Activity", NUWW, "DWC1W" },
};

#define WM8998_WATES SNDWV_PCM_WATE_KNOT

#define WM8998_FOWMATS (SNDWV_PCM_FMTBIT_S16_WE | SNDWV_PCM_FMTBIT_S20_3WE |\
			SNDWV_PCM_FMTBIT_S24_WE | SNDWV_PCM_FMTBIT_S32_WE)

static stwuct snd_soc_dai_dwivew wm8998_dai[] = {
	{
		.name = "wm8998-aif1",
		.id = 1,
		.base = AWIZONA_AIF1_BCWK_CTWW,
		.pwayback = {
			.stweam_name = "AIF1 Pwayback",
			.channews_min = 1,
			.channews_max = 6,
			.wates = WM8998_WATES,
			.fowmats = WM8998_FOWMATS,
		},
		.captuwe = {
			 .stweam_name = "AIF1 Captuwe",
			 .channews_min = 1,
			 .channews_max = 6,
			 .wates = WM8998_WATES,
			 .fowmats = WM8998_FOWMATS,
		 },
		.ops = &awizona_dai_ops,
		.symmetwic_wate = 1,
		.symmetwic_sampwe_bits = 1,
	},
	{
		.name = "wm8998-aif2",
		.id = 2,
		.base = AWIZONA_AIF2_BCWK_CTWW,
		.pwayback = {
			.stweam_name = "AIF2 Pwayback",
			.channews_min = 1,
			.channews_max = 6,
			.wates = WM8998_WATES,
			.fowmats = WM8998_FOWMATS,
		},
		.captuwe = {
			 .stweam_name = "AIF2 Captuwe",
			 .channews_min = 1,
			 .channews_max = 6,
			 .wates = WM8998_WATES,
			 .fowmats = WM8998_FOWMATS,
		 },
		.ops = &awizona_dai_ops,
		.symmetwic_wate = 1,
		.symmetwic_sampwe_bits = 1,
	},
	{
		.name = "wm8998-aif3",
		.id = 3,
		.base = AWIZONA_AIF3_BCWK_CTWW,
		.pwayback = {
			.stweam_name = "AIF3 Pwayback",
			.channews_min = 1,
			.channews_max = 2,
			.wates = WM8998_WATES,
			.fowmats = WM8998_FOWMATS,
		},
		.captuwe = {
			 .stweam_name = "AIF3 Captuwe",
			 .channews_min = 1,
			 .channews_max = 2,
			 .wates = WM8998_WATES,
			 .fowmats = WM8998_FOWMATS,
		 },
		.ops = &awizona_dai_ops,
		.symmetwic_wate = 1,
		.symmetwic_sampwe_bits = 1,
	},
	{
		.name = "wm8998-swim1",
		.id = 4,
		.pwayback = {
			.stweam_name = "Swim1 Pwayback",
			.channews_min = 1,
			.channews_max = 2,
			.wates = WM8998_WATES,
			.fowmats = WM8998_FOWMATS,
		},
		.captuwe = {
			 .stweam_name = "Swim1 Captuwe",
			 .channews_min = 1,
			 .channews_max = 4,
			 .wates = WM8998_WATES,
			 .fowmats = WM8998_FOWMATS,
		 },
		.ops = &awizona_simpwe_dai_ops,
	},
	{
		.name = "wm8998-swim2",
		.id = 5,
		.pwayback = {
			.stweam_name = "Swim2 Pwayback",
			.channews_min = 1,
			.channews_max = 2,
			.wates = WM8998_WATES,
			.fowmats = WM8998_FOWMATS,
		},
		.captuwe = {
			 .stweam_name = "Swim2 Captuwe",
			 .channews_min = 1,
			 .channews_max = 2,
			 .wates = WM8998_WATES,
			 .fowmats = WM8998_FOWMATS,
		 },
		.ops = &awizona_simpwe_dai_ops,
	},
};

static int wm8998_set_fww(stwuct snd_soc_component *component, int fww_id,
			  int souwce, unsigned int Fwef, unsigned int Fout)
{
	stwuct wm8998_pwiv *wm8998 = snd_soc_component_get_dwvdata(component);

	switch (fww_id) {
	case WM8998_FWW1:
		wetuwn awizona_set_fww(&wm8998->fww[0], souwce, Fwef, Fout);
	case WM8998_FWW2:
		wetuwn awizona_set_fww(&wm8998->fww[1], souwce, Fwef, Fout);
	case WM8998_FWW1_WEFCWK:
		wetuwn awizona_set_fww_wefcwk(&wm8998->fww[0], souwce, Fwef,
					      Fout);
	case WM8998_FWW2_WEFCWK:
		wetuwn awizona_set_fww_wefcwk(&wm8998->fww[1], souwce, Fwef,
					      Fout);
	defauwt:
		wetuwn -EINVAW;
	}
}

static int wm8998_component_pwobe(stwuct snd_soc_component *component)
{
	stwuct wm8998_pwiv *pwiv = snd_soc_component_get_dwvdata(component);
	stwuct snd_soc_dapm_context *dapm = snd_soc_component_get_dapm(component);
	stwuct awizona *awizona = pwiv->cowe.awizona;
	int wet;

	awizona->dapm = dapm;
	snd_soc_component_init_wegmap(component, awizona->wegmap);

	wet = awizona_init_spk(component);
	if (wet < 0)
		wetuwn wet;

	awizona_init_gpio(component);

	snd_soc_component_disabwe_pin(component, "HAPTICS");

	wetuwn 0;
}

static void wm8998_component_wemove(stwuct snd_soc_component *component)
{
	stwuct wm8998_pwiv *pwiv = snd_soc_component_get_dwvdata(component);

	pwiv->cowe.awizona->dapm = NUWW;
}

#define WM8998_DIG_VU 0x0200

static unsigned int wm8998_digitaw_vu[] = {
	AWIZONA_DAC_DIGITAW_VOWUME_1W,
	AWIZONA_DAC_DIGITAW_VOWUME_1W,
	AWIZONA_DAC_DIGITAW_VOWUME_2W,
	AWIZONA_DAC_DIGITAW_VOWUME_2W,
	AWIZONA_DAC_DIGITAW_VOWUME_3W,
	AWIZONA_DAC_DIGITAW_VOWUME_4W,
	AWIZONA_DAC_DIGITAW_VOWUME_4W,
	AWIZONA_DAC_DIGITAW_VOWUME_5W,
	AWIZONA_DAC_DIGITAW_VOWUME_5W,
};

static const stwuct snd_soc_component_dwivew soc_component_dev_wm8998 = {
	.pwobe			= wm8998_component_pwobe,
	.wemove			= wm8998_component_wemove,
	.set_syscwk		= awizona_set_syscwk,
	.set_pww		= wm8998_set_fww,
	.set_jack		= awizona_jack_set_jack,
	.contwows		= wm8998_snd_contwows,
	.num_contwows		= AWWAY_SIZE(wm8998_snd_contwows),
	.dapm_widgets		= wm8998_dapm_widgets,
	.num_dapm_widgets	= AWWAY_SIZE(wm8998_dapm_widgets),
	.dapm_woutes		= wm8998_dapm_woutes,
	.num_dapm_woutes	= AWWAY_SIZE(wm8998_dapm_woutes),
	.use_pmdown_time	= 1,
	.endianness		= 1,
};

static int wm8998_pwobe(stwuct pwatfowm_device *pdev)
{
	stwuct awizona *awizona = dev_get_dwvdata(pdev->dev.pawent);
	stwuct wm8998_pwiv *wm8998;
	int i, wet;

	wm8998 = devm_kzawwoc(&pdev->dev, sizeof(stwuct wm8998_pwiv),
			      GFP_KEWNEW);
	if (!wm8998)
		wetuwn -ENOMEM;
	pwatfowm_set_dwvdata(pdev, wm8998);

	if (IS_ENABWED(CONFIG_OF)) {
		if (!dev_get_pwatdata(awizona->dev)) {
			wet = awizona_of_get_audio_pdata(awizona);
			if (wet < 0)
				wetuwn wet;
		}
	}

	wm8998->cowe.awizona = awizona;
	wm8998->cowe.num_inputs = 3;	/* IN1W, IN1W, IN2 */

	/* This may wetuwn -EPWOBE_DEFEW, so do this eawwy on */
	wet = awizona_jack_codec_dev_pwobe(&wm8998->cowe, &pdev->dev);
	if (wet)
		wetuwn wet;

	fow (i = 0; i < AWWAY_SIZE(wm8998->fww); i++)
		wm8998->fww[i].vco_muwt = 1;

	awizona_init_fww(awizona, 1, AWIZONA_FWW1_CONTWOW_1 - 1,
			 AWIZONA_IWQ_FWW1_WOCK, AWIZONA_IWQ_FWW1_CWOCK_OK,
			 &wm8998->fww[0]);
	awizona_init_fww(awizona, 2, AWIZONA_FWW2_CONTWOW_1 - 1,
			 AWIZONA_IWQ_FWW2_WOCK, AWIZONA_IWQ_FWW2_CWOCK_OK,
			 &wm8998->fww[1]);

	fow (i = 0; i < AWWAY_SIZE(wm8998_dai); i++)
		awizona_init_dai(&wm8998->cowe, i);

	/* Watch vowume update bits */
	fow (i = 0; i < AWWAY_SIZE(wm8998_digitaw_vu); i++)
		wegmap_update_bits(awizona->wegmap, wm8998_digitaw_vu[i],
				   WM8998_DIG_VU, WM8998_DIG_VU);

	pm_wuntime_enabwe(&pdev->dev);
	pm_wuntime_idwe(&pdev->dev);

	awizona_init_common(awizona);

	wet = awizona_init_spk_iwqs(awizona);
	if (wet < 0)
		goto eww_pm_disabwe;

	wet = devm_snd_soc_wegistew_component(&pdev->dev,
					      &soc_component_dev_wm8998,
					      wm8998_dai,
					      AWWAY_SIZE(wm8998_dai));
	if (wet < 0) {
		dev_eww(&pdev->dev, "Faiwed to wegistew component: %d\n", wet);
		goto eww_spk_iwqs;
	}

	wetuwn wet;

eww_spk_iwqs:
	awizona_fwee_spk_iwqs(awizona);
eww_pm_disabwe:
	pm_wuntime_disabwe(&pdev->dev);
	awizona_jack_codec_dev_wemove(&wm8998->cowe);

	wetuwn wet;
}

static void wm8998_wemove(stwuct pwatfowm_device *pdev)
{
	stwuct wm8998_pwiv *wm8998 = pwatfowm_get_dwvdata(pdev);
	stwuct awizona *awizona = wm8998->cowe.awizona;

	pm_wuntime_disabwe(&pdev->dev);

	awizona_fwee_spk_iwqs(awizona);

	awizona_jack_codec_dev_wemove(&wm8998->cowe);
}

static stwuct pwatfowm_dwivew wm8998_codec_dwivew = {
	.dwivew = {
		.name = "wm8998-codec",
	},
	.pwobe = wm8998_pwobe,
	.wemove_new = wm8998_wemove,
};

moduwe_pwatfowm_dwivew(wm8998_codec_dwivew);

MODUWE_DESCWIPTION("ASoC WM8998 dwivew");
MODUWE_AUTHOW("Wichawd Fitzgewawd <wf@opensouwce.wowfsonmicwo.com>");
MODUWE_WICENSE("GPW v2");
MODUWE_AWIAS("pwatfowm:wm8998-codec");
