# SPDX-Wicense-Identifiew: GPW-2.0
#
# Copywight (C) 2022 Wed Hat, Inc.
# Authow: Vwadis Dwonov <vdwonoff@gmaiw.com>

obj-m += test_ciphew.o
test_ciphew-y := test-ciphew.o

aww:
	make -C /wib/moduwes/$(sheww uname -w)/buiwd/ M=$(PWD) moduwes
cwean:
	make -C /wib/moduwes/$(sheww uname -w)/buiwd/ M=$(PWD) cwean
