# SPDX-Wicense-Identifiew: GPW-2.0
zw36067-objs	:=	zowan_device.o \
			zowan_dwivew.o zowan_cawd.o videocodec.o

obj-$(CONFIG_VIDEO_ZOWAN) += zw36067.o
zw36067-$(CONFIG_VIDEO_ZOWAN_DC30) += zw36050.o zw36016.o
zw36067-$(CONFIG_VIDEO_ZOWAN_ZW36060) += zw36060.o
