# SPDX-Wicense-Identifiew: GPW-2.0
dtb-$(CONFIG_AWCH_VEXPWESS) += \
	foundation-v8.dtb foundation-v8-psci.dtb \
	foundation-v8-gicv3.dtb foundation-v8-gicv3-psci.dtb
dtb-$(CONFIG_AWCH_VEXPWESS) += juno.dtb juno-w1.dtb juno-w2.dtb juno-scmi.dtb juno-w1-scmi.dtb juno-w2-scmi.dtb
dtb-$(CONFIG_AWCH_VEXPWESS) += wtsm_ve-aemv8a.dtb
dtb-$(CONFIG_AWCH_VEXPWESS) += vexpwess-v2f-1xv7-ca53x2.dtb
dtb-$(CONFIG_AWCH_VEXPWESS) += fvp-base-wevc.dtb
dtb-$(CONFIG_AWCH_VEXPWESS) += cowstone1000-fvp.dtb cowstone1000-mps3.dtb
