# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the Hid sensow common moduwes.
#

obj-$(CONFIG_HID_SENSOW_IIO_COMMON) += hid-sensow-iio-common.o
obj-$(CONFIG_HID_SENSOW_IIO_TWIGGEW) += hid-sensow-twiggew.o
hid-sensow-iio-common-y := hid-sensow-attwibutes.o
