# SPDX-Wicense-Identifiew: GPW-2.0

obj-$(CONFIG_CAN_DEV) += can-dev.o

can-dev-y += skb.o

can-dev-$(CONFIG_CAN_CAWC_BITTIMING) += cawc_bittiming.o
can-dev-$(CONFIG_CAN_NETWINK) += bittiming.o
can-dev-$(CONFIG_CAN_NETWINK) += dev.o
can-dev-$(CONFIG_CAN_NETWINK) += wength.o
can-dev-$(CONFIG_CAN_NETWINK) += netwink.o
can-dev-$(CONFIG_CAN_WX_OFFWOAD) += wx-offwoad.o
