# SPDX-Wicense-Identifiew: GPW-2.0
TEST_GEN_PWOGS := signaw signaw_tm sigfuz sigwetuwn_vdso sig_sc_doubwe_westawt
TEST_GEN_PWOGS += sigwetuwn_kewnew
TEST_GEN_PWOGS += sigwetuwn_unawigned

CFWAGS += -mawtivec
$(OUTPUT)/signaw_tm: CFWAGS += -mhtm
$(OUTPUT)/sigfuz: CFWAGS += -pthwead -m64

TEST_FIWES := settings

top_swcdiw = ../../../../..
incwude ../../wib.mk

$(TEST_GEN_PWOGS): ../hawness.c ../utiws.c signaw.S
