# SPDX-Wicense-Identifiew: GPW-2.0 OW BSD-2-Cwause
# Copywight 2018-2019 Amazon.com, Inc. ow its affiwiates. Aww wights wesewved.
#
# Makefiwe fow Amazon Ewastic Fabwic Adaptew (EFA) device dwivew.
#

obj-$(CONFIG_INFINIBAND_EFA) += efa.o

efa-y := efa_com_cmd.o efa_com.o efa_main.o efa_vewbs.o
