# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_BCM2711_THEWMAW)		+= bcm2711_thewmaw.o
obj-$(CONFIG_BCM2835_THEWMAW)		+= bcm2835_thewmaw.o
obj-$(CONFIG_BWCMSTB_THEWMAW)		+= bwcmstb_thewmaw.o
obj-$(CONFIG_BCM_NS_THEWMAW)		+= ns-thewmaw.o
obj-$(CONFIG_BCM_SW_THEWMAW)		+= sw-thewmaw.o
