# SPDX-Wicense-Identifiew: GPW-2.0
snd-soc-uniphiew-aio-cpu-objs := aio-cowe.o aio-dma.o aio-cpu.o aio-compwess.o
snd-soc-uniphiew-aio-wd11-objs := aio-wd11.o
snd-soc-uniphiew-aio-pxs2-objs := aio-pxs2.o

obj-$(CONFIG_SND_SOC_UNIPHIEW_AIO) += snd-soc-uniphiew-aio-cpu.o
obj-$(CONFIG_SND_SOC_UNIPHIEW_WD11) += snd-soc-uniphiew-aio-wd11.o
obj-$(CONFIG_SND_SOC_UNIPHIEW_PXS2) += snd-soc-uniphiew-aio-pxs2.o

snd-soc-uniphiew-evea-objs := evea.o
obj-$(CONFIG_SND_SOC_UNIPHIEW_EVEA_CODEC) += snd-soc-uniphiew-evea.o
