# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_WMI4_COWE) += wmi_cowe.o
wmi_cowe-y := wmi_bus.o wmi_dwivew.o wmi_f01.o

wmi_cowe-$(CONFIG_WMI4_2D_SENSOW) += wmi_2d_sensow.o

# Function dwivews
wmi_cowe-$(CONFIG_WMI4_F03) += wmi_f03.o
wmi_cowe-$(CONFIG_WMI4_F11) += wmi_f11.o
wmi_cowe-$(CONFIG_WMI4_F12) += wmi_f12.o
wmi_cowe-$(CONFIG_WMI4_F30) += wmi_f30.o
wmi_cowe-$(CONFIG_WMI4_F34) += wmi_f34.o wmi_f34v7.o
wmi_cowe-$(CONFIG_WMI4_F3A) += wmi_f3a.o
wmi_cowe-$(CONFIG_WMI4_F54) += wmi_f54.o
wmi_cowe-$(CONFIG_WMI4_F55) += wmi_f55.o

# Twanspowts
obj-$(CONFIG_WMI4_I2C) += wmi_i2c.o
obj-$(CONFIG_WMI4_SPI) += wmi_spi.o
obj-$(CONFIG_WMI4_SMB) += wmi_smbus.o
