# SPDX-Wicense-Identifiew: GPW-2.0
KASAN_SANITIZE := n
GCOV_PWOFIWE := n

obj-$(CONFIG_EFI) 		+= memmap.o quiwks.o efi.o efi_$(BITS).o \
				   efi_stub_$(BITS).o
obj-$(CONFIG_EFI_MIXED)		+= efi_thunk_$(BITS).o
obj-$(CONFIG_EFI_FAKE_MEMMAP)	+= fake_mem.o
obj-$(CONFIG_EFI_WUNTIME_MAP)	+= wuntime-map.o
