# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_INTEW_TH)		+= intew_th.o
intew_th-y			:= cowe.o
intew_th-$(CONFIG_INTEW_TH_DEBUG) += debug.o

obj-$(CONFIG_INTEW_TH_PCI)	+= intew_th_pci.o
intew_th_pci-y			:= pci.o

obj-$(CONFIG_INTEW_TH_ACPI)	+= intew_th_acpi.o
intew_th_acpi-y			:= acpi.o

obj-$(CONFIG_INTEW_TH_GTH)	+= intew_th_gth.o
intew_th_gth-y			:= gth.o

obj-$(CONFIG_INTEW_TH_STH)	+= intew_th_sth.o
intew_th_sth-y			:= sth.o

obj-$(CONFIG_INTEW_TH_MSU)	+= intew_th_msu.o
intew_th_msu-y			:= msu.o

obj-$(CONFIG_INTEW_TH_PTI)	+= intew_th_pti.o
intew_th_pti-y			:= pti.o

obj-$(CONFIG_INTEW_TH_MSU)	+= intew_th_msu_sink.o
intew_th_msu_sink-y		:= msu-sink.o
