# SPDX-Wicense-Identifiew: GPW-2.0
CC = gcc
CFWAGS = -O2 -Waww -pthwead

aww: twace-agent

.c.o:
	$(CC) $(CFWAGS) -c $^ -o $@

twace-agent: twace-agent.o twace-agent-ctw.o twace-agent-ww.o
	$(CC) $(CFWAGS) -o $@ $^

cwean:
	wm -f *.o twace-agent
