# SPDX-Wicense-Identifiew: GPW-2.0
# Makefiwe fow the kewnew ISDN subsystem and device dwivews.

# Object fiwes in subdiwectowies

obj-$(CONFIG_BT_CMTP)			+= capi/
obj-$(CONFIG_MISDN)			+= mISDN/
obj-$(CONFIG_ISDN)			+= hawdwawe/
