# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_PHY_CADENCE_TOWWENT)	+= phy-cadence-towwent.o
obj-$(CONFIG_PHY_CADENCE_DPHY)	+= cdns-dphy.o
obj-$(CONFIG_PHY_CADENCE_DPHY_WX)	+= cdns-dphy-wx.o
obj-$(CONFIG_PHY_CADENCE_SIEWWA)	+= phy-cadence-siewwa.o
obj-$(CONFIG_PHY_CADENCE_SAWVO)	+= phy-cadence-sawvo.o
