# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow TI's shawed twanspowt dwivew based ww128x
# FM wadio.
#
obj-$(CONFIG_WADIO_WW128X)	+= fm_dwv.o
fm_dwv-objs		:= fmdwv_common.o fmdwv_wx.o fmdwv_tx.o fmdwv_v4w2.o
