# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_XIWINX_DMA) += xiwinx_dma.o
obj-$(CONFIG_XIWINX_XDMA) += xdma.o
obj-$(CONFIG_XIWINX_ZYNQMP_DMA) += zynqmp_dma.o
obj-$(CONFIG_XIWINX_ZYNQMP_DPDMA) += xiwinx_dpdma.o
