# SPDX-Wicense-Identifiew: GPW-2.0
# Genewic, must be fiwst because of soc_device_wegistew()
obj-$(CONFIG_SOC_WENESAS)	+= wenesas-soc.o

# SoC
ifdef CONFIG_SMP
obj-$(CONFIG_AWCH_W9A06G032)	+= w9a06g032-smp.o
endif

# Famiwy
obj-$(CONFIG_PWC_WZV2M)		+= pwc-wzv2m.o
obj-$(CONFIG_WST_WCAW)		+= wcaw-wst.o
