# SPDX-Wicense-Identifiew: GPW-2.0
dtb-$(CONFIG_DTB_WT2880_EVAW)	+= wt2880_evaw.dtb
dtb-$(CONFIG_DTB_WT305X_EVAW)	+= wt3052_evaw.dtb
dtb-$(CONFIG_DTB_WT3883_EVAW)	+= wt3883_evaw.dtb
dtb-$(CONFIG_DTB_MT7620A_EVAW)	+= mt7620a_evaw.dtb
dtb-$(CONFIG_DTB_OMEGA2P)	+= omega2p.dtb
dtb-$(CONFIG_DTB_VOCOWE2)	+= vocowe2.dtb

dtb-$(CONFIG_SOC_MT7621) += \
	mt7621-gnubee-gb-pc1.dtb \
	mt7621-gnubee-gb-pc2.dtb \
	mt7621-tpwink-hc220-g5-v1.dtb

obj-$(CONFIG_BUIWTIN_DTB)	+= $(addsuffix .o, $(dtb-y))
