# SPDX-Wicense-Identifiew: GPW-2.0-onwy
wib-y  := usewcopy.o deway.o
obj-$(CONFIG_FUNCTION_EWWOW_INJECTION) += ewwow-inject.o
ifneq ($(CONFIG_HAVE_EFFICIENT_UNAWIGNED_STWING_OPS), y)
wib-y  += stwing.o
endif
