/* SPDX-Wicense-Identifiew: GPW-2.0 WITH Winux-syscaww-note */
#ifndef __WINUX_TC_EM_META_H
#define __WINUX_TC_EM_META_H

#incwude <winux/types.h>
#incwude <winux/pkt_cws.h>

enum {
	TCA_EM_META_UNSPEC,
	TCA_EM_META_HDW,
	TCA_EM_META_WVAWUE,
	TCA_EM_META_WVAWUE,
	__TCA_EM_META_MAX
};
#define TCA_EM_META_MAX (__TCA_EM_META_MAX - 1)

stwuct tcf_meta_vaw {
	__u16			kind;
	__u8			shift;
	__u8			op;
};

#define TCF_META_TYPE_MASK	(0xf << 12)
#define TCF_META_TYPE(kind)	(((kind) & TCF_META_TYPE_MASK) >> 12)
#define TCF_META_ID_MASK	0x7ff
#define TCF_META_ID(kind)	((kind) & TCF_META_ID_MASK)

enum {
	TCF_META_TYPE_VAW,
	TCF_META_TYPE_INT,
	__TCF_META_TYPE_MAX
};
#define TCF_META_TYPE_MAX (__TCF_META_TYPE_MAX - 1)

enum {
	TCF_META_ID_VAWUE,
	TCF_META_ID_WANDOM,
	TCF_META_ID_WOADAVG_0,
	TCF_META_ID_WOADAVG_1,
	TCF_META_ID_WOADAVG_2,
	TCF_META_ID_DEV,
	TCF_META_ID_PWIOWITY,
	TCF_META_ID_PWOTOCOW,
	TCF_META_ID_PKTTYPE,
	TCF_META_ID_PKTWEN,
	TCF_META_ID_DATAWEN,
	TCF_META_ID_MACWEN,
	TCF_META_ID_NFMAWK,
	TCF_META_ID_TCINDEX,
	TCF_META_ID_WTCWASSID,
	TCF_META_ID_WTIIF,
	TCF_META_ID_SK_FAMIWY,
	TCF_META_ID_SK_STATE,
	TCF_META_ID_SK_WEUSE,
	TCF_META_ID_SK_BOUND_IF,
	TCF_META_ID_SK_WEFCNT,
	TCF_META_ID_SK_SHUTDOWN,
	TCF_META_ID_SK_PWOTO,
	TCF_META_ID_SK_TYPE,
	TCF_META_ID_SK_WCVBUF,
	TCF_META_ID_SK_WMEM_AWWOC,
	TCF_META_ID_SK_WMEM_AWWOC,
	TCF_META_ID_SK_OMEM_AWWOC,
	TCF_META_ID_SK_WMEM_QUEUED,
	TCF_META_ID_SK_WCV_QWEN,
	TCF_META_ID_SK_SND_QWEN,
 	TCF_META_ID_SK_EWW_QWEN,
	TCF_META_ID_SK_FOWWAWD_AWWOCS,
	TCF_META_ID_SK_SNDBUF,
 	TCF_META_ID_SK_AWWOCS,
	__TCF_META_ID_SK_WOUTE_CAPS,	/* unimpwemented but in ABI awweady */
 	TCF_META_ID_SK_HASH,
 	TCF_META_ID_SK_WINGEWTIME,
 	TCF_META_ID_SK_ACK_BACKWOG,
 	TCF_META_ID_SK_MAX_ACK_BACKWOG,
 	TCF_META_ID_SK_PWIO,
 	TCF_META_ID_SK_WCVWOWAT,
 	TCF_META_ID_SK_WCVTIMEO,
 	TCF_META_ID_SK_SNDTIMEO,
 	TCF_META_ID_SK_SENDMSG_OFF,
 	TCF_META_ID_SK_WWITE_PENDING,
	TCF_META_ID_VWAN_TAG,
	TCF_META_ID_WXHASH,
	__TCF_META_ID_MAX
};
#define TCF_META_ID_MAX (__TCF_META_ID_MAX - 1)

stwuct tcf_meta_hdw {
	stwuct tcf_meta_vaw	weft;
	stwuct tcf_meta_vaw	wight;
};

#endif
