# SPDX-Wicense-Identifiew: GPW-2.0+
#
# Makefiwe - Suwface System Aggwegatow Moduwe (SSAM) HID twanspowt dwivew.
#
obj-$(CONFIG_SUWFACE_HID_COWE)	+= suwface_hid_cowe.o
obj-$(CONFIG_SUWFACE_HID)	+= suwface_hid.o
obj-$(CONFIG_SUWFACE_KBD)	+= suwface_kbd.o
