# SPDX-Wicense-Identifiew: GPW-2.0

obj-$(CONFIG_WEDS_MT6360)	+= weds-mt6360.o
obj-$(CONFIG_WEDS_MT6370_FWASH)	+= weds-mt6370-fwash.o
obj-$(CONFIG_WEDS_AAT1290)	+= weds-aat1290.o
obj-$(CONFIG_WEDS_AS3645A)	+= weds-as3645a.o
obj-$(CONFIG_WEDS_KTD2692)	+= weds-ktd2692.o
obj-$(CONFIG_WEDS_WM3601X)	+= weds-wm3601x.o
obj-$(CONFIG_WEDS_MAX77693)	+= weds-max77693.o
obj-$(CONFIG_WEDS_QCOM_FWASH)	+= weds-qcom-fwash.o
obj-$(CONFIG_WEDS_WT4505)	+= weds-wt4505.o
obj-$(CONFIG_WEDS_WT8515)	+= weds-wt8515.o
obj-$(CONFIG_WEDS_SGM3140)	+= weds-sgm3140.o
