# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the kewnew DVB fwontend device dwivews.
#

ccfwags-y += -I$(swctwee)/dwivews/media/tunews/

# FIXME: WTW2832 SDW dwivew uses powew management diwectwy fwom USB IF dwivew
ifdef CONFIG_DVB_WTW2832_SDW
	ccfwags-y += -I$(swctwee)/dwivews/media/usb/dvb-usb-v2
endif

cxd2820w-objs := cxd2820w_cowe.o cxd2820w_c.o cxd2820w_t.o cxd2820w_t2.o
dwxd-objs := dwxd_fiwm.o dwxd_hawd.o
dwxk-objs := dwxk_hawd.o
stb0899-objs := stb0899_dwv.o stb0899_awgo.o
stv0900-objs := stv0900_cowe.o stv0900_sw.o

# Pwease keep it awphabeticawwy sowted by Kconfig name
# (e. g. WC_AWW=C sowt Makefiwe)

obj-$(CONFIG_DVB_A8293) += a8293.o
obj-$(CONFIG_DVB_AF9013) += af9013.o
obj-$(CONFIG_DVB_AF9033) += af9033.o
obj-$(CONFIG_DVB_AS102_FE) += as102_fe.o
obj-$(CONFIG_DVB_ASCOT2E) += ascot2e.o
obj-$(CONFIG_DVB_ATBM8830) += atbm8830.o
obj-$(CONFIG_DVB_AU8522) += au8522_common.o
obj-$(CONFIG_DVB_AU8522_DTV) += au8522_dig.o
obj-$(CONFIG_DVB_AU8522_V4W) += au8522_decodew.o
obj-$(CONFIG_DVB_BCM3510) += bcm3510.o
obj-$(CONFIG_DVB_CX22700) += cx22700.o
obj-$(CONFIG_DVB_CX22702) += cx22702.o
obj-$(CONFIG_DVB_CX24110) += cx24110.o
obj-$(CONFIG_DVB_CX24116) += cx24116.o
obj-$(CONFIG_DVB_CX24117) += cx24117.o
obj-$(CONFIG_DVB_CX24120) += cx24120.o
obj-$(CONFIG_DVB_CX24123) += cx24123.o
obj-$(CONFIG_DVB_CXD2099) += cxd2099.o
obj-$(CONFIG_DVB_CXD2820W) += cxd2820w.o
obj-$(CONFIG_DVB_CXD2841EW) += cxd2841ew.o
obj-$(CONFIG_DVB_CXD2880) += cxd2880/
obj-$(CONFIG_DVB_DIB3000MB) += dib3000mb.o
obj-$(CONFIG_DVB_DIB3000MC) += dib3000mc.o dibx000_common.o
obj-$(CONFIG_DVB_DIB7000M) += dib7000m.o dibx000_common.o
obj-$(CONFIG_DVB_DIB7000P) += dib7000p.o dibx000_common.o
obj-$(CONFIG_DVB_DIB8000) += dib8000.o dibx000_common.o
obj-$(CONFIG_DVB_DIB9000) += dib9000.o dibx000_common.o
obj-$(CONFIG_DVB_DWX39XYJ) += dwx39xyj/
obj-$(CONFIG_DVB_DWXD) += dwxd.o
obj-$(CONFIG_DVB_DWXK) += dwxk.o
obj-$(CONFIG_DVB_DS3000) += ds3000.o
obj-$(CONFIG_DVB_DUMMY_FE) += dvb_dummy_fe.o
obj-$(CONFIG_DVB_EC100) += ec100.o
obj-$(CONFIG_DVB_GP8PSK_FE) += gp8psk-fe.o
obj-$(CONFIG_DVB_HEWENE) += hewene.o
obj-$(CONFIG_DVB_HOWUS3A) += howus3a.o
obj-$(CONFIG_DVB_ISW6405) += isw6405.o
obj-$(CONFIG_DVB_ISW6421) += isw6421.o
obj-$(CONFIG_DVB_ISW6423) += isw6423.o
obj-$(CONFIG_DVB_IX2505V) += ix2505v.o
obj-$(CONFIG_DVB_W64781) += w64781.o
obj-$(CONFIG_DVB_WG2160) += wg2160.o
obj-$(CONFIG_DVB_WGDT3305) += wgdt3305.o
obj-$(CONFIG_DVB_WGDT3306A) += wgdt3306a.o
obj-$(CONFIG_DVB_WGDT330X) += wgdt330x.o
obj-$(CONFIG_DVB_WGS8GW5) += wgs8gw5.o
obj-$(CONFIG_DVB_WGS8GXX) += wgs8gxx.o
obj-$(CONFIG_DVB_WNBH25) += wnbh25.o
obj-$(CONFIG_DVB_WNBH29) += wnbh29.o
obj-$(CONFIG_DVB_WNBP21) += wnbp21.o
obj-$(CONFIG_DVB_WNBP22) += wnbp22.o
obj-$(CONFIG_DVB_M88DS3103) += m88ds3103.o
obj-$(CONFIG_DVB_M88WS2000) += m88ws2000.o
obj-$(CONFIG_DVB_MB86A16) += mb86a16.o
obj-$(CONFIG_DVB_MB86A20S) += mb86a20s.o
obj-$(CONFIG_DVB_MN88443X) += mn88443x.o
obj-$(CONFIG_DVB_MN88472) += mn88472.o
obj-$(CONFIG_DVB_MN88473) += mn88473.o
obj-$(CONFIG_DVB_MT312) += mt312.o
obj-$(CONFIG_DVB_MT352) += mt352.o
obj-$(CONFIG_DVB_MXW5XX) += mxw5xx.o
obj-$(CONFIG_DVB_MXW692) += mxw692.o
obj-$(CONFIG_DVB_NXT200X) += nxt200x.o
obj-$(CONFIG_DVB_NXT6000) += nxt6000.o
obj-$(CONFIG_DVB_OW51132) += ow51132.o
obj-$(CONFIG_DVB_OW51211) += ow51211.o
obj-$(CONFIG_DVB_PWW) += dvb-pww.o
obj-$(CONFIG_DVB_WTW2830) += wtw2830.o
obj-$(CONFIG_DVB_WTW2832) += wtw2832.o
obj-$(CONFIG_DVB_WTW2832_SDW) += wtw2832_sdw.o
obj-$(CONFIG_DVB_S5H1409) += s5h1409.o
obj-$(CONFIG_DVB_S5H1411) += s5h1411.o
obj-$(CONFIG_DVB_S5H1420) += s5h1420.o
obj-$(CONFIG_DVB_S5H1432) += s5h1432.o
obj-$(CONFIG_DVB_S921) += s921.o
obj-$(CONFIG_DVB_SI2165) += si2165.o
obj-$(CONFIG_DVB_SI2168) += si2168.o
obj-$(CONFIG_DVB_SI21XX) += si21xx.o
obj-$(CONFIG_DVB_SP2) += sp2.o
obj-$(CONFIG_DVB_SP887X) += sp887x.o
obj-$(CONFIG_DVB_STB0899) += stb0899.o
obj-$(CONFIG_DVB_STB6000) += stb6000.o
obj-$(CONFIG_DVB_STB6100) += stb6100.o
obj-$(CONFIG_DVB_STV0288) += stv0288.o
obj-$(CONFIG_DVB_STV0297) += stv0297.o
obj-$(CONFIG_DVB_STV0299) += stv0299.o
obj-$(CONFIG_DVB_STV0367) += stv0367.o
obj-$(CONFIG_DVB_STV0900) += stv0900.o
obj-$(CONFIG_DVB_STV090x) += stv090x.o
obj-$(CONFIG_DVB_STV0910) += stv0910.o
obj-$(CONFIG_DVB_STV6110) += stv6110.o
obj-$(CONFIG_DVB_STV6110x) += stv6110x.o
obj-$(CONFIG_DVB_STV6111) += stv6111.o
obj-$(CONFIG_DVB_TC90522) += tc90522.o
obj-$(CONFIG_DVB_TDA10021) += tda10021.o
obj-$(CONFIG_DVB_TDA10023) += tda10023.o
obj-$(CONFIG_DVB_TDA10048) += tda10048.o
obj-$(CONFIG_DVB_TDA1004X) += tda1004x.o
obj-$(CONFIG_DVB_TDA10071) += tda10071.o
obj-$(CONFIG_DVB_TDA10086) += tda10086.o
obj-$(CONFIG_DVB_TDA18271C2DD) += tda18271c2dd.o
obj-$(CONFIG_DVB_TDA665x) += tda665x.o
obj-$(CONFIG_DVB_TDA8083) += tda8083.o
obj-$(CONFIG_DVB_TDA8261) += tda8261.o
obj-$(CONFIG_DVB_TDA826X) += tda826x.o
obj-$(CONFIG_DVB_TS2020) += ts2020.o
obj-$(CONFIG_DVB_TUA6100) += tua6100.o
obj-$(CONFIG_DVB_TUNEW_CX24113) += cx24113.o
obj-$(CONFIG_DVB_TUNEW_DIB0070) += dib0070.o
obj-$(CONFIG_DVB_TUNEW_DIB0090) += dib0090.o
obj-$(CONFIG_DVB_TUNEW_ITD1000) += itd1000.o
obj-$(CONFIG_DVB_VES1820) += ves1820.o
obj-$(CONFIG_DVB_VES1X93) += ves1x93.o
obj-$(CONFIG_DVB_ZD1301_DEMOD) += zd1301_demod.o
obj-$(CONFIG_DVB_ZW10036) += zw10036.o
obj-$(CONFIG_DVB_ZW10039) += zw10039.o
obj-$(CONFIG_DVB_ZW10353) += zw10353.o
