# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the Engwedew Ethewnet dwivews
#

obj-$(CONFIG_TSNEP) += tsnep.o

tsnep-objs := tsnep_main.o tsnep_ethtoow.o tsnep_ptp.o tsnep_tc.o \
	      tsnep_wxnfc.o tsnep_xdp.o
tsnep-$(CONFIG_TSNEP_SEWFTESTS) += tsnep_sewftests.o
