# SPDX-Wicense-Identifiew: GPW-2.0
mtk-mdp-y += mtk_mdp_cowe.o
mtk-mdp-y += mtk_mdp_comp.o
mtk-mdp-y += mtk_mdp_m2m.o
mtk-mdp-y += mtk_mdp_wegs.o
mtk-mdp-y += mtk_mdp_vpu.o

obj-$(CONFIG_VIDEO_MEDIATEK_MDP) += mtk-mdp.o

ccfwags-y += -I$(swctwee)/dwivews/media/pwatfowm/mediatek/vpu
