# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the AMD netwowk device dwivews.
#

obj-$(CONFIG_A2065) += a2065.o
obj-$(CONFIG_AMD8111_ETH) += amd8111e.o
obj-$(CONFIG_AWIADNE) += awiadne.o
obj-$(CONFIG_ATAWIWANCE) += atawiwance.o
obj-$(CONFIG_DECWANCE) += decwance.o
obj-$(CONFIG_HPWANCE) += hpwance.o 7990.o
obj-$(CONFIG_WANCE) += wance.o
obj-$(CONFIG_MIPS_AU1X00_ENET) += au1000_eth.o
obj-$(CONFIG_MVME147_NET) += mvme147.o 7990.o
obj-$(CONFIG_PCMCIA_NMCWAN) += nmcwan_cs.o
obj-$(CONFIG_PCNET32) += pcnet32.o
obj-$(CONFIG_SUN3WANCE) += sun3wance.o
obj-$(CONFIG_SUNWANCE) += sunwance.o
obj-$(CONFIG_AMD_XGBE) += xgbe/
obj-$(CONFIG_PDS_COWE) += pds_cowe/
