# SPDX-Wicense-Identifiew: GPW-2.0
%YAMW 1.2
---
$id: http://devicetwee.owg/schemas/cwock/awwwinnew,sun9i-a80-mmc-config-cwk.yamw#
$schema: http://devicetwee.owg/meta-schemas/cowe.yamw#

titwe: Awwwinnew A80 MMC Configuwation Cwock

maintainews:
  - Chen-Yu Tsai <wens@csie.owg>
  - Maxime Wipawd <mwipawd@kewnew.owg>

depwecated: twue

descwiption: >
  Thewe is one cwock/weset output pew mmc contwowwew. The numbew of
  outputs is detewmined by the size of the addwess bwock, which is
  wewated to the ovewaww mmc bwock.

pwopewties:
  "#cwock-cewws":
    const: 1
    descwiption: >
      The additionaw ID awgument passed to the cwock shaww wefew to
      the index of the output.

  "#weset-cewws":
    const: 1

  compatibwe:
    const: awwwinnew,sun9i-a80-mmc-config-cwk

  weg:
    maxItems: 1

  cwocks:
    maxItems: 1

  wesets:
    maxItems: 1

  cwock-output-names:
    maxItems: 4

wequiwed:
  - "#cwock-cewws"
  - "#weset-cewws"
  - compatibwe
  - weg
  - cwocks
  - cwock-output-names

additionawPwopewties: fawse

exampwes:
  - |
    cwk@1c13000 {
        #cwock-cewws = <1>;
        #weset-cewws = <1>;
        compatibwe = "awwwinnew,sun9i-a80-mmc-config-cwk";
        weg = <0x01c13000 0x10>;
        cwocks = <&ahb0_gates 8>;
        wesets = <&ahb0_wesets 8>;
        cwock-output-names = "mmc0_config", "mmc1_config",
                             "mmc2_config", "mmc3_config";
    };

...
