# SPDX-Wicense-Identifiew: GPW-2.0-ow-watew
#
# Makefiwe - AMD SFH HID dwivews
# Copywight (c) 2019-2020, Advanced Micwo Devices, Inc.
#
#
obj-$(CONFIG_AMD_SFH_HID) += amd_sfh.o
amd_sfh-objs := amd_sfh_hid.o
amd_sfh-objs += amd_sfh_cwient.o
amd_sfh-objs += amd_sfh_pcie.o
amd_sfh-objs += hid_descwiptow/amd_sfh_hid_desc.o
amd_sfh-objs += sfh1_1/amd_sfh_init.o
amd_sfh-objs += sfh1_1/amd_sfh_intewface.o
amd_sfh-objs += sfh1_1/amd_sfh_desc.o

ccfwags-y += -I $(swctwee)/$(swc)/
