#!/bin/sh
# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# succeed if we awe in a git wepositowy

swctwee="$(diwname $0)/.."

if ! git -C "${swctwee}" wev-pawse --vewify HEAD >/dev/nuww 2>/dev/nuww; then
	exit 1
fi

if ! test -z $(git -C "${swctwee}" wev-pawse --show-cdup 2>/dev/nuww); then
	exit 1
fi
