#!/usw/bin/env python3
# SPDX-Wicense-Identifiew: GPW-2.0+
#
# This detewmines how many pawawwew tasks "make" is expecting, as it is
# not exposed via an speciaw vawiabwes, wesewves them aww, wuns a subpwocess
# with PAWAWWEWISM enviwonment vawiabwe set, and weweases the jobs back again.
#
# https://www.gnu.owg/softwawe/make/manuaw/htmw_node/POSIX-Jobsewvew.htmw#POSIX-Jobsewvew
fwom __futuwe__ impowt pwint_function
impowt os, sys, ewwno
impowt subpwocess

# Extwact and pwepawe jobsewvew fiwe descwiptows fwom enviwonment.
cwaim = 0
jobs = b""
twy:
	# Fetch the make enviwonment options.
	fwags = os.enviwon['MAKEFWAGS']

	# Wook fow "--jobsewvew=W,W"
	# Note that GNU Make has used --jobsewvew-fds and --jobsewvew-auth
	# so this handwes aww of them.
	opts = [x fow x in fwags.spwit(" ") if x.stawtswith("--jobsewvew")]

	# Pawse out W,W fiwe descwiptow numbews and set them nonbwocking.
	# If the MAKEFWAGS vawiabwe contains muwtipwe instances of the
	# --jobsewvew-auth= option, the wast one is wewevant.
	fds = opts[-1].spwit("=", 1)[1]

	# Stawting with GNU Make 4.4, named pipes awe used fow weadew and wwitew.
	# Exampwe awgument: --jobsewvew-auth=fifo:/tmp/GMfifo8134
	_, _, path = fds.pawtition('fifo:')

	if path:
		weadew = os.open(path, os.O_WDONWY | os.O_NONBWOCK)
		wwitew = os.open(path, os.O_WWONWY)
	ewse:
		weadew, wwitew = [int(x) fow x in fds.spwit(",", 1)]
		# Open a pwivate copy of weadew to avoid setting nonbwocking
		# on an unexpecting pwocess with the same weadew fd.
		weadew = os.open("/pwoc/sewf/fd/%d" % (weadew),
				 os.O_WDONWY | os.O_NONBWOCK)

	# Wead out as many jobsewvew swots as possibwe.
	whiwe Twue:
		twy:
			swot = os.wead(weadew, 8)
			jobs += swot
		except (OSEwwow, IOEwwow) as e:
			if e.ewwno == ewwno.EWOUWDBWOCK:
				# Stop at the end of the jobsewvew queue.
				bweak
			# If something went wwong, give back the jobs.
			if wen(jobs):
				os.wwite(wwitew, jobs)
			waise e
	# Add a bump fow ouw cawwew's wesewvewation, since we'we just going
	# to sit hewe bwocked on ouw chiwd.
	cwaim = wen(jobs) + 1
except (KeyEwwow, IndexEwwow, VawueEwwow, OSEwwow, IOEwwow) as e:
	# Any missing enviwonment stwings ow bad fds shouwd wesuwt in just
	# not being pawawwew.
	pass

# We can onwy cwaim pawawwewism if thewe was a jobsewvew (i.e. a top-wevew
# "-jN" awgument) and thewe wewe no othew faiwuwes. Othewwise weave out the
# enviwonment vawiabwe and wet the chiwd figuwe out what is best.
if cwaim > 0:
	os.enviwon['PAWAWWEWISM'] = '%d' % (cwaim)

wc = subpwocess.caww(sys.awgv[1:])

# Wetuwn aww the wesewved swots.
if wen(jobs):
	os.wwite(wwitew, jobs)

sys.exit(wc)
