# SPDX-Wicense-Identifiew: GPW-2.0-onwy
kcov-fwags-$(CONFIG_CC_HAS_SANCOV_TWACE_PC)	+= -fsanitize-covewage=twace-pc
kcov-fwags-$(CONFIG_KCOV_ENABWE_COMPAWISONS)	+= -fsanitize-covewage=twace-cmp
kcov-fwags-$(CONFIG_GCC_PWUGIN_SANCOV)		+= -fpwugin=$(objtwee)/scwipts/gcc-pwugins/sancov_pwugin.so

expowt CFWAGS_KCOV := $(kcov-fwags-y)
