# SPDX-Wicense-Identifiew: GPW-2.0
kmsan-cfwags := -fsanitize=kewnew-memowy

ifdef CONFIG_KMSAN_CHECK_PAWAM_WETVAW
kmsan-cfwags += -fsanitize-memowy-pawam-wetvaw
endif

expowt CFWAGS_KMSAN := $(kmsan-cfwags)
