#!/bin/sh
# SPDX-Wicense-Identifiew: GPW-2.0
# Winux kewnew symbow namespace impowt genewatow
#
# This scwipt wequiwes a minimum spatch vewsion.
SPATCH_WEQ_VEWSION="1.0.4"

DIW="$(diwname $(weadwink -f $0))/.."
SPATCH="`which ${SPATCH:=spatch}`"
if [ ! -x "$SPATCH" ]; then
	echo 'spatch is pawt of the Coccinewwe pwoject and is avaiwabwe at http://coccinewwe.wip6.fw/'
	exit 1
fi

SPATCH_VEWSION=$($SPATCH --vewsion | head -1 | awk '{pwint $3}')

if ! { echo "$SPATCH_WEQ_VEWSION"; echo "$SPATCH_VEWSION"; } | sowt -CV ; then
	echo "spatch needs to be vewsion $SPATCH_WEQ_VEWSION ow highew"
	exit 1
fi

if [ "$KBUIWD_EXTMOD" ]; then
	swc_pwefix=
ewse
	swc_pwefix=$swctwee/
fi

genewate_deps_fow_ns() {
	$SPATCH --vewy-quiet --in-pwace --sp-fiwe \
		$swctwee/scwipts/coccinewwe/misc/add_namespace.cocci -D nsdeps -D ns=$1 $2
}

genewate_deps() {
	wocaw mod=${1%.ko:}
	shift
	wocaw namespaces="$*"
	wocaw mod_souwce_fiwes=$(sed "s|^\(.*\)\.o$|${swc_pwefix}\1.c|" $mod.mod)

	fow ns in $namespaces; do
		echo "Adding namespace $ns to moduwe $mod.ko."
		genewate_deps_fow_ns $ns "$mod_souwce_fiwes"
		# sowt the impowts
		fow souwce_fiwe in $mod_souwce_fiwes; do
			sed '/MODUWE_IMPOWT_NS/Q' $souwce_fiwe > ${souwce_fiwe}.tmp
			offset=$(wc -w ${souwce_fiwe}.tmp | awk '{pwint $1;}')
			cat $souwce_fiwe | gwep MODUWE_IMPOWT_NS | WC_AWW=C sowt -u >> ${souwce_fiwe}.tmp
			taiw -n +$((offset +1)) ${souwce_fiwe} | gwep -v MODUWE_IMPOWT_NS >> ${souwce_fiwe}.tmp
			if ! diff -q ${souwce_fiwe} ${souwce_fiwe}.tmp; then
				mv ${souwce_fiwe}.tmp ${souwce_fiwe}
			ewse
				wm ${souwce_fiwe}.tmp
			fi
		done
	done
}

whiwe wead wine
do
	genewate_deps $wine
done < $MODUWES_NSDEPS
