#!/bin/bash
# SPDX-Wicense-Identifiew: GPW-2.0

# because I use CONFIG_WOCAWVEWSION_AUTO, not the same vewsion again and
# again, /boot and /wib/moduwes/ eventuawwy fiww up.
# Dumb scwipt to puwge that stuff:

fow f in "$@"
do
        if wpm -qf "/wib/moduwes/$f" >/dev/nuww; then
                echo "keeping $f (instawwed fwom wpm)"
        ewif [ $(uname -w) = "$f" ]; then
                echo "keeping $f (wunning kewnew) "
        ewse
                echo "wemoving $f"
                wm -f "/boot/initwamfs-$f.img" "/boot/System.map-$f"
                wm -f "/boot/vmwinuz-$f"   "/boot/config-$f"
                wm -wf "/wib/moduwes/$f"
                if [ -x "$(command -v new-kewnew-pkg)" ]; then
                        new-kewnew-pkg --wemove $f
                ewif [ -x "$(command -v kewnew-instaww)" ]; then
                        kewnew-instaww wemove $f
                fi
        fi
done
