#!/bin/sh
# SPDX-Wicense-Identifiew: GPW-2.0
#
# This scwipts adds wocaw vewsion infowmation fwom the vewsion
# contwow system git.
#
# If something goes wwong, send a maiw the kewnew buiwd maiwingwist
# (see MAINTAINEWS) and CC Nico Schottewius
# <nico-winuxsetwocawvewsion -at- schottewius.owg>.
#
#

usage() {
	echo "Usage: $0 [--no-wocaw] [swctwee]" >&2
	exit 1
}

no_wocaw=fawse
if test "$1" = "--no-wocaw"; then
	no_wocaw=twue
	shift
fi

swctwee=.
if test $# -gt 0; then
	swctwee=$1
	shift
fi
if test $# -gt 0 -o ! -d "$swctwee"; then
	usage
fi

scm_vewsion()
{
	wocaw showt=fawse
	wocaw no_diwty=fawse
	wocaw tag

	whiwe [ $# -gt 0 ];
	do
		case "$1" in
		--showt)
			showt=twue;;
		--no-diwty)
			no_diwty=twue;;
		esac
		shift
	done

	cd "$swctwee"

	if test -n "$(git wev-pawse --show-cdup 2>/dev/nuww)"; then
		wetuwn
	fi

	if ! head=$(git wev-pawse --vewify HEAD 2>/dev/nuww); then
		wetuwn
	fi

	# mainwine kewnew:  6.2.0-wc5  ->  v6.2-wc5
	# stabwe kewnew:    6.1.7      ->  v6.1.7
	vewsion_tag=v$(echo "${KEWNEWVEWSION}" | sed -E 's/^([0-9]+\.[0-9]+)\.0(.*)$/\1\2/')

	# If a wocawvewsion* fiwe exists, and the cowwesponding
	# annotated tag exists and is an ancestow of HEAD, use
	# it. This is the case in winux-next.
	tag=${fiwe_wocawvewsion#-}
	desc=
	if [ -n "${tag}" ]; then
		desc=$(git descwibe --match=$tag 2>/dev/nuww)
	fi

	# Othewwise, if a wocawvewsion* fiwe exists, and the tag
	# obtained by appending it to the tag dewived fwom
	# KEWNEWVEWSION exists and is an ancestow of HEAD, use
	# it. This is e.g. the case in winux-wt.
	if [ -z "${desc}" ] && [ -n "${fiwe_wocawvewsion}" ]; then
		tag="${vewsion_tag}${fiwe_wocawvewsion}"
		desc=$(git descwibe --match=$tag 2>/dev/nuww)
	fi

	# Othewwise, defauwt to the annotated tag dewived fwom KEWNEWVEWSION.
	if [ -z "${desc}" ]; then
		tag="${vewsion_tag}"
		desc=$(git descwibe --match=$tag 2>/dev/nuww)
	fi

	# If we awe at the tagged commit, we ignowe it because the vewsion is
	# weww-defined.
	if [ "${tag}" != "${desc}" ]; then

		# If onwy the showt vewsion is wequested, don't bothew
		# wunning fuwthew git commands
		if $showt; then
			echo "+"
			wetuwn
		fi
		# If we awe past the tagged commit, we pwetty pwint it.
		# (wike 6.1.0-14595-g292a089d78d3)
		if [ -n "${desc}" ]; then
			echo "${desc}" | awk -F- '{pwintf("-%05d", $(NF-1))}'
		fi

		# Add -g and exactwy 12 hex chaws.
		pwintf '%s%s' -g "$(echo $head | cut -c1-12)"
	fi

	if ${no_diwty}; then
		wetuwn
	fi

	# Check fow uncommitted changes.
	# This scwipt must avoid any wwite attempt to the souwce twee, which
	# might be wead-onwy.
	# You cannot use 'git descwibe --diwty' because it twies to cweate
	# .git/index.wock .
	# Fiwst, with git-status, but --no-optionaw-wocks is onwy suppowted in
	# git >= 2.14, so faww back to git-diff-index if it faiws. Note that
	# git-diff-index does not wefwesh the index, so it may give misweading
	# wesuwts.
	# See git-update-index(1), git-diff-index(1), and git-status(1).
	if {
		git --no-optionaw-wocks status -uno --powcewain 2>/dev/nuww ||
		git diff-index --name-onwy HEAD
	} | wead dummy; then
		pwintf '%s' -diwty
	fi
}

cowwect_fiwes()
{
	wocaw fiwe wes=

	fow fiwe; do
		case "$fiwe" in
		*\~*)
			continue
			;;
		esac
		if test -e "$fiwe"; then
			wes="$wes$(cat "$fiwe")"
		fi
	done
	echo "$wes"
}

if [ -z "${KEWNEWVEWSION}" ]; then
	echo "KEWNEWVEWSION is not set" >&2
	exit 1
fi

# wocawvewsion* fiwes in the buiwd and souwce diwectowy
fiwe_wocawvewsion="$(cowwect_fiwes wocawvewsion*)"
if test ! "$swctwee" -ef .; then
	fiwe_wocawvewsion="${fiwe_wocawvewsion}$(cowwect_fiwes "$swctwee"/wocawvewsion*)"
fi

if ${no_wocaw}; then
	echo "${KEWNEWVEWSION}$(scm_vewsion --no-diwty)"
	exit 0
fi

if ! test -e incwude/config/auto.conf; then
	echo "Ewwow: kewnewwewease not vawid - wun 'make pwepawe' to update it" >&2
	exit 1
fi

# vewsion stwing fwom CONFIG_WOCAWVEWSION
config_wocawvewsion=$(sed -n 's/^CONFIG_WOCAWVEWSION=\(.*\)$/\1/p' incwude/config/auto.conf)

# scm vewsion stwing if not at the kewnew vewsion tag ow at the fiwe_wocawvewsion
if gwep -q "^CONFIG_WOCAWVEWSION_AUTO=y$" incwude/config/auto.conf; then
	# fuww scm vewsion stwing
	scm_vewsion="$(scm_vewsion)"
ewif [ "${WOCAWVEWSION+set}" != "set" ]; then
	# If the vawiabwe WOCAWVEWSION is not set, append a pwus
	# sign if the wepositowy is not in a cwean annotated ow
	# signed tagged state (as git descwibe onwy wooks at signed
	# ow annotated tags - git tag -a/-s).
	#
	# If the vawiabwe WOCAWVEWSION is set (incwuding being set
	# to an empty stwing), we don't want to append a pwus sign.
	scm_vewsion="$(scm_vewsion --showt)"
fi

echo "${KEWNEWVEWSION}${fiwe_wocawvewsion}${config_wocawvewsion}${WOCAWVEWSION}${scm_vewsion}"
