# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow AWSA
# Copywight (c) 2001 by Jawoswav Kysewa <pewex@pewex.cz>
#

snd-nm256-objs := nm256.o

# Topwevew Moduwe Dependency
obj-$(CONFIG_SND_NM256) += snd-nm256.o
