# SPDX-Wicense-Identifiew: GPW-2.0
cx25821-y   := cx25821-cowe.o cx25821-cawds.o cx25821-i2c.o \
		       cx25821-gpio.o cx25821-medusa-video.o \
		       cx25821-video.o

obj-$(CONFIG_VIDEO_CX25821) += cx25821.o
obj-$(CONFIG_VIDEO_CX25821_AWSA) += cx25821-awsa.o
