# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the Quawcomm Technowogies, Inc. EMAC Gigabit Ethewnet dwivew
#

obj-$(CONFIG_QCOM_EMAC) += qcom-emac.o

qcom-emac-objs := emac.o emac-mac.o emac-phy.o emac-sgmii.o emac-ethtoow.o \
		  emac-sgmii-fsm9900.o emac-sgmii-qdf2432.o \
		  emac-sgmii-qdf2400.o
