# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_ACPI_APEI)		+= apei.o
obj-$(CONFIG_ACPI_APEI_GHES)	+= ghes.o
obj-$(CONFIG_ACPI_APEI_EINJ)	+= einj.o
obj-$(CONFIG_ACPI_APEI_EWST_DEBUG) += ewst-dbg.o

apei-y := apei-base.o hest.o ewst.o bewt.o
