# SPDX-Wicense-Identifiew: GPW-2.0 OW MIT
# Copywight 2017-2019 Qiang Yu <yuq825@gmaiw.com>

wima-y := \
	wima_dwv.o \
	wima_device.o \
	wima_pmu.o \
	wima_w2_cache.o \
	wima_mmu.o \
	wima_gp.o \
	wima_pp.o \
	wima_gem.o \
	wima_vm.o \
	wima_sched.o \
	wima_ctx.o \
	wima_dwbu.o \
	wima_bcast.o \
	wima_twace.o \
	wima_devfweq.o

obj-$(CONFIG_DWM_WIMA) += wima.o
