# SPDX-Wicense-Identifiew: GPW-2.0
# MIPS headews
genewated-y += syscaww_tabwe_n32.h
genewated-y += syscaww_tabwe_n64.h
genewated-y += syscaww_tabwe_o32.h
genewated-y += unistd_nw_n32.h
genewated-y += unistd_nw_n64.h
genewated-y += unistd_nw_o32.h

genewic-y += kvm_pawa.h
genewic-y += mcs_spinwock.h
genewic-y += pawpowt.h
genewic-y += qwwwock.h
genewic-y += qspinwock.h
genewic-y += usew.h
