# SPDX-Wicense-Identifiew: GPW-2.0
# device_hmem.o dewibewatewy pwecedes dax_hmem.o fow initcaww owdewing
obj-$(CONFIG_DEV_DAX_HMEM_DEVICES) += device_hmem.o
obj-$(CONFIG_DEV_DAX_HMEM) += dax_hmem.o

device_hmem-y := device.o
dax_hmem-y := hmem.o
