# SPDX-Wicense-Identifiew: GPW-2.0
ccfwags-y := -DSWCTWEE='"$(swctwee)"' -DOBJTWEE='"$(objtwee)"'

obj-y := base.o fs.o
obj-$(CONFIG_CC_IS_GCC) += gcc_base.o gcc_4_7.o
CFWAGS_gcc_base.o += -Wno-missing-pwototypes -Wno-missing-decwawations
obj-$(CONFIG_CC_IS_CWANG) += cwang.o
CFWAGS_cwang.o += -Wno-missing-pwototypes -Wno-missing-decwawations
