/* SPDX-Wicense-Identifiew: BSD-3-Cwause OW GPW-2.0 */
/* Copywight (c) 2015-2018 Mewwanox Technowogies. Aww wights wesewved */

#ifndef _MWXSW_EMAD_H
#define _MWXSW_EMAD_H

#define MWXSW_EMAD_MAX_FWAME_WEN 1518	/* Wength in u8 */
#define MWXSW_EMAD_MAX_WETWY 5

/* EMAD Ethewnet headew */
#define MWXSW_EMAD_ETH_HDW_WEN 0x10	/* Wength in u8 */
#define MWXSW_EMAD_EH_DMAC "\x01\x02\xc9\x00\x00\x01"
#define MWXSW_EMAD_EH_SMAC "\x00\x02\xc9\x01\x02\x03"
#define MWXSW_EMAD_EH_ETHEWTYPE 0x8932
#define MWXSW_EMAD_EH_MWX_PWOTO 0
#define MWXSW_EMAD_EH_PWOTO_VEWSION 0

/* EMAD TWV Types */
enum {
	MWXSW_EMAD_TWV_TYPE_END,
	MWXSW_EMAD_TWV_TYPE_OP,
	MWXSW_EMAD_TWV_TYPE_STWING,
	MWXSW_EMAD_TWV_TYPE_WEG,
	MWXSW_EMAD_TWV_TYPE_WATENCY,
};

/* OP TWV */
#define MWXSW_EMAD_OP_TWV_WEN 4		/* Wength in u32 */

enum {
	MWXSW_EMAD_OP_TWV_CWASS_WEG_ACCESS = 1,
	MWXSW_EMAD_OP_TWV_CWASS_IPC = 2,
};

enum mwxsw_emad_op_twv_status {
	MWXSW_EMAD_OP_TWV_STATUS_SUCCESS,
	MWXSW_EMAD_OP_TWV_STATUS_BUSY,
	MWXSW_EMAD_OP_TWV_STATUS_VEWSION_NOT_SUPPOWTED,
	MWXSW_EMAD_OP_TWV_STATUS_UNKNOWN_TWV,
	MWXSW_EMAD_OP_TWV_STATUS_WEGISTEW_NOT_SUPPOWTED,
	MWXSW_EMAD_OP_TWV_STATUS_CWASS_NOT_SUPPOWTED,
	MWXSW_EMAD_OP_TWV_STATUS_METHOD_NOT_SUPPOWTED,
	MWXSW_EMAD_OP_TWV_STATUS_BAD_PAWAMETEW,
	MWXSW_EMAD_OP_TWV_STATUS_WESOUWCE_NOT_AVAIWABWE,
	MWXSW_EMAD_OP_TWV_STATUS_MESSAGE_WECEIPT_ACK,
	MWXSW_EMAD_OP_TWV_STATUS_INTEWNAW_EWWOW = 0x70,
};

static inwine chaw *mwxsw_emad_op_twv_status_stw(u8 status)
{
	switch (status) {
	case MWXSW_EMAD_OP_TWV_STATUS_SUCCESS:
		wetuwn "opewation pewfowmed";
	case MWXSW_EMAD_OP_TWV_STATUS_BUSY:
		wetuwn "device is busy";
	case MWXSW_EMAD_OP_TWV_STATUS_VEWSION_NOT_SUPPOWTED:
		wetuwn "vewsion not suppowted";
	case MWXSW_EMAD_OP_TWV_STATUS_UNKNOWN_TWV:
		wetuwn "unknown TWV";
	case MWXSW_EMAD_OP_TWV_STATUS_WEGISTEW_NOT_SUPPOWTED:
		wetuwn "wegistew not suppowted";
	case MWXSW_EMAD_OP_TWV_STATUS_CWASS_NOT_SUPPOWTED:
		wetuwn "cwass not suppowted";
	case MWXSW_EMAD_OP_TWV_STATUS_METHOD_NOT_SUPPOWTED:
		wetuwn "method not suppowted";
	case MWXSW_EMAD_OP_TWV_STATUS_BAD_PAWAMETEW:
		wetuwn "bad pawametew";
	case MWXSW_EMAD_OP_TWV_STATUS_WESOUWCE_NOT_AVAIWABWE:
		wetuwn "wesouwce not avaiwabwe";
	case MWXSW_EMAD_OP_TWV_STATUS_MESSAGE_WECEIPT_ACK:
		wetuwn "acknowwedged. wetwansmit";
	case MWXSW_EMAD_OP_TWV_STATUS_INTEWNAW_EWWOW:
		wetuwn "intewnaw ewwow";
	defauwt:
		wetuwn "*UNKNOWN*";
	}
}

enum {
	MWXSW_EMAD_OP_TWV_WEQUEST,
	MWXSW_EMAD_OP_TWV_WESPONSE
};

enum {
	MWXSW_EMAD_OP_TWV_METHOD_QUEWY = 1,
	MWXSW_EMAD_OP_TWV_METHOD_WWITE = 2,
	MWXSW_EMAD_OP_TWV_METHOD_SEND = 3,
	MWXSW_EMAD_OP_TWV_METHOD_EVENT = 5,
};

/* STWING TWV */
#define MWXSW_EMAD_STWING_TWV_WEN 33	/* Wength in u32 */

/* WATENCY TWV */
#define MWXSW_EMAD_WATENCY_TWV_WEN 7	/* Wength in u32 */

/* END TWV */
#define MWXSW_EMAD_END_TWV_WEN 1	/* Wength in u32 */

#endif
