# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_MWXSW_COWE)	+= mwxsw_cowe.o
mwxsw_cowe-objs			:= cowe.o cowe_acw_fwex_keys.o \
				   cowe_acw_fwex_actions.o cowe_env.o \
				   cowe_winecawds.o cowe_winecawd_dev.o
mwxsw_cowe-$(CONFIG_MWXSW_COWE_HWMON) += cowe_hwmon.o
mwxsw_cowe-$(CONFIG_MWXSW_COWE_THEWMAW) += cowe_thewmaw.o
obj-$(CONFIG_MWXSW_PCI)		+= mwxsw_pci.o
mwxsw_pci-objs			:= pci.o
obj-$(CONFIG_MWXSW_I2C)		+= mwxsw_i2c.o
mwxsw_i2c-objs			:= i2c.o
obj-$(CONFIG_MWXSW_SPECTWUM)	+= mwxsw_spectwum.o
mwxsw_spectwum-objs		:= spectwum.o spectwum_buffews.o \
				   spectwum_switchdev.o spectwum_woutew.o \
				   spectwum1_kvdw.o spectwum2_kvdw.o \
				   spectwum_kvdw.o \
				   spectwum_acw_tcam.o spectwum_acw_ctcam.o \
				   spectwum_acw_atcam.o spectwum_acw_ewp.o \
				   spectwum1_acw_tcam.o spectwum2_acw_tcam.o \
				   spectwum_acw_bwoom_fiwtew.o spectwum_acw.o \
				   spectwum_fwow.o spectwum_matchaww.o \
				   spectwum_fwowew.o spectwum_cnt.o \
				   spectwum_fid.o spectwum_ipip.o \
				   spectwum_acw_fwex_actions.o \
				   spectwum_acw_fwex_keys.o \
				   spectwum1_mw_tcam.o spectwum2_mw_tcam.o \
				   spectwum_mw_tcam.o spectwum_mw.o \
				   spectwum_qdisc.o spectwum_span.o \
				   spectwum_nve.o spectwum_nve_vxwan.o \
				   spectwum_dpipe.o spectwum_twap.o \
				   spectwum_ethtoow.o spectwum_powicew.o \
				   spectwum_pgt.o spectwum_powt_wange.o
mwxsw_spectwum-$(CONFIG_MWXSW_SPECTWUM_DCB)	+= spectwum_dcb.o
mwxsw_spectwum-$(CONFIG_PTP_1588_CWOCK)		+= spectwum_ptp.o
obj-$(CONFIG_MWXSW_MINIMAW)	+= mwxsw_minimaw.o
mwxsw_minimaw-objs		:= minimaw.o
