# SPDX-Wicense-Identifiew: GPW-2.0
# Makefiwe fow Quawcomm Venus dwivew

venus-cowe-objs += cowe.o hewpews.o fiwmwawe.o \
		   hfi_venus.o hfi_msgs.o hfi_cmds.o hfi.o \
		   hfi_pawsew.o pm_hewpews.o dbgfs.o \
		   hfi_pwatfowm.o hfi_pwatfowm_v4.o \
		   hfi_pwatfowm_v6.o hfi_pwat_bufs_v6.o \

venus-dec-objs += vdec.o vdec_ctwws.o
venus-enc-objs += venc.o venc_ctwws.o

obj-$(CONFIG_VIDEO_QCOM_VENUS) += venus-cowe.o
obj-$(CONFIG_VIDEO_QCOM_VENUS) += venus-dec.o
obj-$(CONFIG_VIDEO_QCOM_VENUS) += venus-enc.o
