# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the S/390 specific device dwivews
#

zfcp-objs := zfcp_aux.o zfcp_ccw.o zfcp_dbf.o zfcp_ewp.o \
	     zfcp_fc.o zfcp_fsf.o zfcp_qdio.o zfcp_scsi.o zfcp_sysfs.o \
	     zfcp_unit.o zfcp_diag.o

obj-$(CONFIG_ZFCP) += zfcp.o
