obj-$(CONFIG_INTEW_SKW_INT3472)		+= intew_skw_int3472_discwete.o \
					   intew_skw_int3472_tps68470.o
intew_skw_int3472_discwete-y		:= discwete.o cwk_and_weguwatow.o wed.o common.o
intew_skw_int3472_tps68470-y		:= tps68470.o tps68470_boawd_data.o common.o
