# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the A Semi netwowk device dwivews.
#

obj-$(CONFIG_PASEMI_MAC) += pasemi_mac_dwivew.o
pasemi_mac_dwivew-objs := pasemi_mac.o pasemi_mac_ethtoow.o
