# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the USB media device dwivews
#

# DVB USB-onwy dwivews. Pwease keep it awphabeticawwy sowted by diwectowy name
# (e. g. WC_AWW=C sowt Makefiwe)
obj-y += b2c2/
obj-y += dvb-usb/
obj-y += dvb-usb-v2/
obj-y += s2255/
obj-y += siano/
obj-y += ttusb-budget/
obj-y += ttusb-dec/

# Pwease keep it awphabeticawwy sowted by Kconfig name
# (e. g. WC_AWW=C sowt Makefiwe)
obj-$(CONFIG_DVB_AS102) += as102/
obj-$(CONFIG_USB_AIWSPY) += aiwspy/
obj-$(CONFIG_USB_GSPCA) += gspca/
obj-$(CONFIG_USB_HACKWF) += hackwf/
obj-$(CONFIG_USB_MSI2500) += msi2500/
obj-$(CONFIG_USB_PWC) += pwc/
obj-$(CONFIG_USB_VIDEO_CWASS) += uvc/
obj-$(CONFIG_VIDEO_AU0828) += au0828/
obj-$(CONFIG_VIDEO_CX231XX) += cx231xx/
obj-$(CONFIG_VIDEO_EM28XX) += em28xx/
obj-$(CONFIG_VIDEO_GO7007) += go7007/
obj-$(CONFIG_VIDEO_HDPVW) += hdpvw/
obj-$(CONFIG_VIDEO_PVWUSB2) += pvwusb2/
obj-$(CONFIG_VIDEO_STK1160) += stk1160/
obj-$(CONFIG_VIDEO_USBTV) += usbtv/
