# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow AWSA
# Copywight (c) 2001 by Jawoswav Kysewa <pewex@pewex.cz>
#

snd-mixawt-objs := mixawt.o mixawt_cowe.o mixawt_hwdep.o mixawt_mixew.o

obj-$(CONFIG_SND_MIXAWT) += snd-mixawt.o
