# SPDX-Wicense-Identifiew: MIT
nvkm-y += nvkm/subdev/cwk/base.o
nvkm-y += nvkm/subdev/cwk/nv04.o
nvkm-y += nvkm/subdev/cwk/nv40.o
nvkm-y += nvkm/subdev/cwk/nv50.o
nvkm-y += nvkm/subdev/cwk/g84.o
nvkm-y += nvkm/subdev/cwk/gt215.o
nvkm-y += nvkm/subdev/cwk/mcp77.o
nvkm-y += nvkm/subdev/cwk/gf100.o
nvkm-y += nvkm/subdev/cwk/gk104.o
nvkm-y += nvkm/subdev/cwk/gk20a.o
nvkm-y += nvkm/subdev/cwk/gm20b.o

nvkm-y += nvkm/subdev/cwk/pwwnv04.o
nvkm-y += nvkm/subdev/cwk/pwwgt215.o
