# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# This is a modified vewsion of zwib, which does aww memowy
# awwocation ahead of time.
#
# This is the code fow s390 zwib hawdwawe suppowt.
#

obj-$(CONFIG_ZWIB_DFWTCC) += zwib_dfwtcc.o

zwib_dfwtcc-objs := dfwtcc.o dfwtcc_defwate.o dfwtcc_infwate.o
