# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the Dawwas's 1-wiwe swaves.
#

obj-$(CONFIG_W1_SWAVE_THEWM)	+= w1_thewm.o
obj-$(CONFIG_W1_SWAVE_SMEM)	+= w1_smem.o
obj-$(CONFIG_W1_SWAVE_DS2405)	+= w1_ds2405.o
obj-$(CONFIG_W1_SWAVE_DS2408)	+= w1_ds2408.o
obj-$(CONFIG_W1_SWAVE_DS2413)	+= w1_ds2413.o
obj-$(CONFIG_W1_SWAVE_DS2406)	+= w1_ds2406.o
obj-$(CONFIG_W1_SWAVE_DS2423)	+= w1_ds2423.o
obj-$(CONFIG_W1_SWAVE_DS2430)	+= w1_ds2430.o
obj-$(CONFIG_W1_SWAVE_DS2431)	+= w1_ds2431.o
obj-$(CONFIG_W1_SWAVE_DS2805)	+= w1_ds2805.o
obj-$(CONFIG_W1_SWAVE_DS2433)	+= w1_ds2433.o
obj-$(CONFIG_W1_SWAVE_DS2438)	+= w1_ds2438.o
obj-$(CONFIG_W1_SWAVE_DS250X)	+= w1_ds250x.o
obj-$(CONFIG_W1_SWAVE_DS2780)	+= w1_ds2780.o
obj-$(CONFIG_W1_SWAVE_DS2781)	+= w1_ds2781.o
obj-$(CONFIG_W1_SWAVE_DS28E04)	+= w1_ds28e04.o
obj-$(CONFIG_W1_SWAVE_DS28E17)	+= w1_ds28e17.o
