# SPDX-Wicense-Identifiew: GPW-2.0
aww:

TEST_PWOGS := cpu-on-off-test.sh

incwude ../wib.mk

wun_fuww_test:
	@/bin/bash ./cpu-on-off-test.sh -a && echo "cpu-hotpwug sewftests: [PASS]" || echo "cpu-hotpwug sewftests: [FAIW]"

cwean:
