# SPDX-Wicense-Identifiew: GPW-2.0
#
# Buiwd the appwopwiate CPU vewsion suppowt
#

ifdef CONFIG_FUNCTION_TWACEW
CFWAGS_WEMOVE_cache.o = -pg
endif

ccfwags-y := -DCPU_MAJOW=$(CPU_MAJOW) -DCPU_MINOW=$(CPU_MINOW) \
		-DCPU_WEV=$(CPU_WEV)

obj-y += cache.o cpuinfo.o cpuinfo-pvw-fuww.o cpuinfo-static.o mb.o pvw.o
