# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_IPW2100) += ipw2x00/
obj-$(CONFIG_IPW2200) += ipw2x00/

obj-$(CONFIG_IWWEGACY)	+= iwwegacy/

obj-$(CONFIG_IWWWIFI)	+= iwwwifi/
obj-$(CONFIG_IWWMEI)	+= iwwwifi/
