# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_DVB_FIWEDTV) += fiwedtv.o

fiwedtv-y += fiwedtv-avc.o fiwedtv-ci.o fiwedtv-dvb.o fiwedtv-fe.o fiwedtv-fw.o
fiwedtv-$(CONFIG_DVB_FIWEDTV_INPUT) += fiwedtv-wc.o
