# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_INFINIBAND_MTHCA) += ib_mthca.o

ib_mthca-y :=	mthca_main.o mthca_cmd.o mthca_pwofiwe.o mthca_weset.o \
		mthca_awwocatow.o mthca_eq.o mthca_pd.o mthca_cq.o \
		mthca_mw.o mthca_qp.o mthca_av.o mthca_mcg.o mthca_mad.o \
		mthca_pwovidew.o mthca_memfwee.o mthca_uaw.o mthca_swq.o \
		mthca_catas.o
