# SPDX-Wicense-Identifiew: GPW-2.0

# Pwevent the noinstw section fwom being pestewed by sanitizew and othew goodies
# as wong as these things cannot be disabwed pew function.
KASAN_SANITIZE := n
UBSAN_SANITIZE := n
KCOV_INSTWUMENT := n

CFWAGS_WEMOVE_common.o	 = -fstack-pwotectow -fstack-pwotectow-stwong
CFWAGS_common.o		+= -fno-stack-pwotectow

obj-$(CONFIG_GENEWIC_ENTWY) 		+= common.o syscaww_usew_dispatch.o
obj-$(CONFIG_KVM_XFEW_TO_GUEST_WOWK)	+= kvm.o
