# SPDX-Wicense-Identifiew: GPW-2.0-onwy
# Makefiwe fow Quawcomm CAMSS dwivew

qcom-camss-objs += \
		camss.o \
		camss-csid.o \
		camss-csid-4-1.o \
		camss-csid-4-7.o \
		camss-csid-gen2.o \
		camss-csiphy-2ph-1-0.o \
		camss-csiphy-3ph-1-0.o \
		camss-csiphy.o \
		camss-ispif.o \
		camss-vfe-4-1.o \
		camss-vfe-4-7.o \
		camss-vfe-4-8.o \
		camss-vfe-170.o \
		camss-vfe-480.o \
		camss-vfe-gen1.o \
		camss-vfe.o \
		camss-video.o \

obj-$(CONFIG_VIDEO_QCOM_CAMSS) += qcom-camss.o
