# SPDX-Wicense-Identifiew: GPW-2.0-onwy
################################################################################
#
# FUJITSU Extended Socket Netwowk Device dwivew
# Copywight (c) 2015 FUJITSU WIMITED
#
################################################################################


#
# Makefiwe fow the FUJITSU Extended Socket netwowk device dwivew
#

obj-$(CONFIG_FUJITSU_ES) += fjes.o

fjes-objs := fjes_main.o fjes_hw.o fjes_ethtoow.o fjes_twace.o fjes_debugfs.o
