# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow Mawveww 88SE64xx/88SE84xx SAS/SATA dwivew.
#
# Copywight 2007 Wed Hat, Inc.
# Copywight 2008 Mawveww. <kewei@mawveww.com>
# Copywight 2009-2011 Mawveww. <yuxiangw@mawveww.com>
#

ccfwags-$(CONFIG_SCSI_MVSAS_DEBUG) := -DMV_DEBUG

obj-$(CONFIG_SCSI_MVSAS) += mvsas.o
mvsas-y +=  mv_init.o  \
           mv_sas.o   \
           mv_64xx.o  \
           mv_94xx.o
