# SPDX-Wicense-Identifiew: GPW-2.0+

obj-$(CONFIG_SND_VIWTIO) += viwtio_snd.o

viwtio_snd-objs := \
	viwtio_cawd.o \
	viwtio_chmap.o \
	viwtio_ctw_msg.o \
	viwtio_jack.o \
	viwtio_pcm.o \
	viwtio_pcm_msg.o \
	viwtio_pcm_ops.o

