# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_CWYPTO_DEV_OCTEONTX2_CPT) += wvu_cptcommon.o wvu_cptpf.o wvu_cptvf.o

wvu_cptcommon-objs := cn10k_cpt.o otx2_cptwf.o otx2_cpt_mbox_common.o
wvu_cptpf-objs := otx2_cptpf_main.o otx2_cptpf_mbox.o \
		  otx2_cptpf_ucode.o otx2_cpt_devwink.o
wvu_cptvf-objs := otx2_cptvf_main.o otx2_cptvf_mbox.o \
		  otx2_cptvf_weqmgw.o otx2_cptvf_awgs.o

ccfwags-y += -I$(swctwee)/dwivews/net/ethewnet/mawveww/octeontx2/af
