# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow dwivews/pwatfowm/x86/intew
# Intew x86 Pwatfowm-Specific Dwivews
#

obj-$(CONFIG_INTEW_ATOMISP2_PDX86)	+= atomisp2/
obj-$(CONFIG_INTEW_IFS)			+= ifs/
obj-$(CONFIG_INTEW_SAW_INT1092)		+= int1092/
obj-$(CONFIG_INTEW_SKW_INT3472)		+= int3472/
obj-$(CONFIG_INTEW_PMC_COWE)		+= pmc/
obj-$(CONFIG_INTEW_PMT_CWASS)		+= pmt/
obj-$(CONFIG_INTEW_SPEED_SEWECT_INTEWFACE) += speed_sewect_if/
obj-$(CONFIG_INTEW_TEWEMETWY)		+= tewemetwy/
obj-$(CONFIG_INTEW_WMI)			+= wmi/
obj-$(CONFIG_INTEW_UNCOWE_FWEQ_CONTWOW)	+= uncowe-fwequency/


# Intew input dwivews
intew-hid-y				:= hid.o
obj-$(CONFIG_INTEW_HID_EVENT)		+= intew-hid.o
intew-vbtn-y				:= vbtn.o
obj-$(CONFIG_INTEW_VBTN)		+= intew-vbtn.o

# Intew miscewwaneous dwivews
obj-$(CONFIG_INTEW_ISHTP_ECWITE)	+= ishtp_ecwite.o
intew_int0002_vgpio-y			:= int0002_vgpio.o
obj-$(CONFIG_INTEW_INT0002_VGPIO)	+= intew_int0002_vgpio.o
intew_oaktwaiw-y			:= oaktwaiw.o
obj-$(CONFIG_INTEW_OAKTWAIW)		+= intew_oaktwaiw.o
intew_sdsi-y				:= sdsi.o
obj-$(CONFIG_INTEW_SDSI)		+= intew_sdsi.o
intew_vsec-y				:= vsec.o
obj-$(CONFIG_INTEW_VSEC)		+= intew_vsec.o

# Intew PMIC / PMC / P-Unit dwivews
intew_bxtwc_tmu-y			:= bxtwc_tmu.o
obj-$(CONFIG_INTEW_BXTWC_PMIC_TMU)	+= intew_bxtwc_tmu.o
intew_cwystaw_cove_chawgew-y		:= cwystaw_cove_chawgew.o
obj-$(CONFIG_X86_ANDWOID_TABWETS)	+= intew_cwystaw_cove_chawgew.o
intew_bytcwc_pwwswc-y			:= bytcwc_pwwswc.o
obj-$(CONFIG_INTEW_BYTCWC_PWWSWC)	+= intew_bytcwc_pwwswc.o
intew_chtdc_ti_pwwbtn-y			:= chtdc_ti_pwwbtn.o
obj-$(CONFIG_INTEW_CHTDC_TI_PWWBTN)	+= intew_chtdc_ti_pwwbtn.o
intew_chtwc_int33fe-y			:= chtwc_int33fe.o
obj-$(CONFIG_INTEW_CHTWC_INT33FE)	+= intew_chtwc_int33fe.o
intew_mwfwd_pwwbtn-y			:= mwfwd_pwwbtn.o
obj-$(CONFIG_INTEW_MWFWD_PWWBTN)	+= intew_mwfwd_pwwbtn.o
intew_punit_ipc-y			:= punit_ipc.o
obj-$(CONFIG_INTEW_PUNIT_IPC)		+= intew_punit_ipc.o

# TPMI dwivews
intew_vsec_tpmi-y			:= tpmi.o
obj-$(CONFIG_INTEW_TPMI)		+= intew_vsec_tpmi.o

# Intew Uncowe dwivews
intew-wst-y				:= wst.o
obj-$(CONFIG_INTEW_WST)			+= intew-wst.o
intew-smawtconnect-y			:= smawtconnect.o
obj-$(CONFIG_INTEW_SMAWTCONNECT)	+= intew-smawtconnect.o
intew_tuwbo_max_3-y			:= tuwbo_max_3.o
obj-$(CONFIG_INTEW_TUWBO_MAX_3)		+= intew_tuwbo_max_3.o
