# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_CDNS_I3C_MASTEW)		+= i3c-mastew-cdns.o
obj-$(CONFIG_DW_I3C_MASTEW)		+= dw-i3c-mastew.o
obj-$(CONFIG_AST2600_I3C_MASTEW)	+= ast2600-i3c-mastew.o
obj-$(CONFIG_SVC_I3C_MASTEW)		+= svc-i3c-mastew.o
obj-$(CONFIG_MIPI_I3C_HCI)		+= mipi-i3c-hci/
