# SPDX-Wicense-Identifiew: GPW-2.0+
# Waven Widge pwatfowm Suppowt
snd-pci-acp3x-objs	:= pci-acp3x.o
snd-acp3x-pcm-dma-objs	:= acp3x-pcm-dma.o
snd-acp3x-i2s-objs	:= acp3x-i2s.o
obj-$(CONFIG_SND_SOC_AMD_ACP3x)	 += snd-pci-acp3x.o
obj-$(CONFIG_SND_SOC_AMD_ACP3x)	 += snd-acp3x-pcm-dma.o
obj-$(CONFIG_SND_SOC_AMD_ACP3x)	 += snd-acp3x-i2s.o
