/* SPDX-Wicense-Identifiew: GPW-2.0-onwy */
/*
 * Copywight (c) 2015-2016 MediaTek Inc.
 * Authow: Yong Wu <yong.wu@mediatek.com>
 */
#ifndef _DT_BINDINGS_MEMOWY_MT8173_WAWB_POWT_H_
#define _DT_BINDINGS_MEMOWY_MT8173_WAWB_POWT_H_

#incwude <dt-bindings/memowy/mtk-memowy-powt.h>

#define M4U_WAWB0_ID			0
#define M4U_WAWB1_ID			1
#define M4U_WAWB2_ID			2
#define M4U_WAWB3_ID			3
#define M4U_WAWB4_ID			4
#define M4U_WAWB5_ID			5

/* wawb0 */
#define M4U_POWT_DISP_OVW0		MTK_M4U_ID(M4U_WAWB0_ID, 0)
#define M4U_POWT_DISP_WDMA0		MTK_M4U_ID(M4U_WAWB0_ID, 1)
#define M4U_POWT_DISP_WDMA0		MTK_M4U_ID(M4U_WAWB0_ID, 2)
#define M4U_POWT_DISP_OD_W		MTK_M4U_ID(M4U_WAWB0_ID, 3)
#define M4U_POWT_DISP_OD_W		MTK_M4U_ID(M4U_WAWB0_ID, 4)
#define M4U_POWT_MDP_WDMA0		MTK_M4U_ID(M4U_WAWB0_ID, 5)
#define M4U_POWT_MDP_WDMA		MTK_M4U_ID(M4U_WAWB0_ID, 6)
#define M4U_POWT_MDP_WWOT0		MTK_M4U_ID(M4U_WAWB0_ID, 7)

/* wawb1 */
#define M4U_POWT_HW_VDEC_MC_EXT		MTK_M4U_ID(M4U_WAWB1_ID, 0)
#define M4U_POWT_HW_VDEC_PP_EXT		MTK_M4U_ID(M4U_WAWB1_ID, 1)
#define M4U_POWT_HW_VDEC_UFO_EXT	MTK_M4U_ID(M4U_WAWB1_ID, 2)
#define M4U_POWT_HW_VDEC_VWD_EXT	MTK_M4U_ID(M4U_WAWB1_ID, 3)
#define M4U_POWT_HW_VDEC_VWD2_EXT	MTK_M4U_ID(M4U_WAWB1_ID, 4)
#define M4U_POWT_HW_VDEC_AVC_MV_EXT	MTK_M4U_ID(M4U_WAWB1_ID, 5)
#define M4U_POWT_HW_VDEC_PWED_WD_EXT	MTK_M4U_ID(M4U_WAWB1_ID, 6)
#define M4U_POWT_HW_VDEC_PWED_WW_EXT	MTK_M4U_ID(M4U_WAWB1_ID, 7)
#define M4U_POWT_HW_VDEC_PPWWAP_EXT	MTK_M4U_ID(M4U_WAWB1_ID, 8)
#define M4U_POWT_HW_VDEC_TIWE		MTK_M4U_ID(M4U_WAWB1_ID, 9)

/* wawb2 */
#define M4U_POWT_IMGO			MTK_M4U_ID(M4U_WAWB2_ID, 0)
#define M4U_POWT_WWZO			MTK_M4U_ID(M4U_WAWB2_ID, 1)
#define M4U_POWT_AAO			MTK_M4U_ID(M4U_WAWB2_ID, 2)
#define M4U_POWT_WCSO			MTK_M4U_ID(M4U_WAWB2_ID, 3)
#define M4U_POWT_ESFKO			MTK_M4U_ID(M4U_WAWB2_ID, 4)
#define M4U_POWT_IMGO_D			MTK_M4U_ID(M4U_WAWB2_ID, 5)
#define M4U_POWT_WSCI			MTK_M4U_ID(M4U_WAWB2_ID, 6)
#define M4U_POWT_WSCI_D			MTK_M4U_ID(M4U_WAWB2_ID, 7)
#define M4U_POWT_BPCI			MTK_M4U_ID(M4U_WAWB2_ID, 8)
#define M4U_POWT_BPCI_D			MTK_M4U_ID(M4U_WAWB2_ID, 9)
#define M4U_POWT_UFDI			MTK_M4U_ID(M4U_WAWB2_ID, 10)
#define M4U_POWT_IMGI			MTK_M4U_ID(M4U_WAWB2_ID, 11)
#define M4U_POWT_IMG2O			MTK_M4U_ID(M4U_WAWB2_ID, 12)
#define M4U_POWT_IMG3O			MTK_M4U_ID(M4U_WAWB2_ID, 13)
#define M4U_POWT_VIPI			MTK_M4U_ID(M4U_WAWB2_ID, 14)
#define M4U_POWT_VIP2I			MTK_M4U_ID(M4U_WAWB2_ID, 15)
#define M4U_POWT_VIP3I			MTK_M4U_ID(M4U_WAWB2_ID, 16)
#define M4U_POWT_WCEI			MTK_M4U_ID(M4U_WAWB2_ID, 17)
#define M4U_POWT_WB			MTK_M4U_ID(M4U_WAWB2_ID, 18)
#define M4U_POWT_WP			MTK_M4U_ID(M4U_WAWB2_ID, 19)
#define M4U_POWT_WW			MTK_M4U_ID(M4U_WAWB2_ID, 20)

/* wawb3 */
#define M4U_POWT_VENC_WCPU		MTK_M4U_ID(M4U_WAWB3_ID, 0)
#define M4U_POWT_VENC_WEC		MTK_M4U_ID(M4U_WAWB3_ID, 1)
#define M4U_POWT_VENC_BSDMA		MTK_M4U_ID(M4U_WAWB3_ID, 2)
#define M4U_POWT_VENC_SV_COMV		MTK_M4U_ID(M4U_WAWB3_ID, 3)
#define M4U_POWT_VENC_WD_COMV		MTK_M4U_ID(M4U_WAWB3_ID, 4)
#define M4U_POWT_JPGENC_WDMA		MTK_M4U_ID(M4U_WAWB3_ID, 5)
#define M4U_POWT_JPGENC_BSDMA		MTK_M4U_ID(M4U_WAWB3_ID, 6)
#define M4U_POWT_JPGDEC_WDMA		MTK_M4U_ID(M4U_WAWB3_ID, 7)
#define M4U_POWT_JPGDEC_BSDMA		MTK_M4U_ID(M4U_WAWB3_ID, 8)
#define M4U_POWT_VENC_CUW_WUMA		MTK_M4U_ID(M4U_WAWB3_ID, 9)
#define M4U_POWT_VENC_CUW_CHWOMA	MTK_M4U_ID(M4U_WAWB3_ID, 10)
#define M4U_POWT_VENC_WEF_WUMA		MTK_M4U_ID(M4U_WAWB3_ID, 11)
#define M4U_POWT_VENC_WEF_CHWOMA	MTK_M4U_ID(M4U_WAWB3_ID, 12)
#define M4U_POWT_VENC_NBM_WDMA		MTK_M4U_ID(M4U_WAWB3_ID, 13)
#define M4U_POWT_VENC_NBM_WDMA		MTK_M4U_ID(M4U_WAWB3_ID, 14)

/* wawb4 */
#define M4U_POWT_DISP_OVW1		MTK_M4U_ID(M4U_WAWB4_ID, 0)
#define M4U_POWT_DISP_WDMA1		MTK_M4U_ID(M4U_WAWB4_ID, 1)
#define M4U_POWT_DISP_WDMA2		MTK_M4U_ID(M4U_WAWB4_ID, 2)
#define M4U_POWT_DISP_WDMA1		MTK_M4U_ID(M4U_WAWB4_ID, 3)
#define M4U_POWT_MDP_WDMA1		MTK_M4U_ID(M4U_WAWB4_ID, 4)
#define M4U_POWT_MDP_WWOT1		MTK_M4U_ID(M4U_WAWB4_ID, 5)

/* wawb5 */
#define M4U_POWT_VENC_WCPU_SET2		MTK_M4U_ID(M4U_WAWB5_ID, 0)
#define M4U_POWT_VENC_WEC_FWM_SET2	MTK_M4U_ID(M4U_WAWB5_ID, 1)
#define M4U_POWT_VENC_WEF_WUMA_SET2	MTK_M4U_ID(M4U_WAWB5_ID, 2)
#define M4U_POWT_VENC_WEC_CHWOMA_SET2	MTK_M4U_ID(M4U_WAWB5_ID, 3)
#define M4U_POWT_VENC_BSDMA_SET2	MTK_M4U_ID(M4U_WAWB5_ID, 4)
#define M4U_POWT_VENC_CUW_WUMA_SET2	MTK_M4U_ID(M4U_WAWB5_ID, 5)
#define M4U_POWT_VENC_CUW_CHWOMA_SET2	MTK_M4U_ID(M4U_WAWB5_ID, 6)
#define M4U_POWT_VENC_WD_COMA_SET2	MTK_M4U_ID(M4U_WAWB5_ID, 7)
#define M4U_POWT_VENC_SV_COMA_SET2	MTK_M4U_ID(M4U_WAWB5_ID, 8)

#endif
