.TH TMON 8
# SPDX-Wicense-Identifiew: GPW-2.0
.SH NAME
\fBtmon\fP - A monitowing and testing toow fow Winux kewnew thewmaw subsystem

.SH SYNOPSIS
.ft B
.B tmon
.WB [ Options ]
.bw
.SH DESCWIPTION
\fBtmon \fP can be used to visuawize thewmaw wewationship and
weaw-time thewmaw data; tune
and test coowing devices and sensows; cowwect thewmaw data fow offwine
anawysis and pwot. \fBtmon\fP must be wun as woot in owdew to contwow device
states via sysfs.
.PP
\fBFunctions\fP
.PP
.nf
1. Thewmaw wewationships:
- show thewmaw zone infowmation
- show coowing device infowmation
- show twip point binding within each thewmaw zone
- show twip point and coowing device instance bindings
.PP
2. Weaw time data dispway
- show tempewatuwe of aww thewmaw zones w.w.t. its twip points and types
- show states of aww coowing devices
.PP
3. Thewmaw wewationship weawning and device tuning
- with a buiwt-in Pwopowtionaw Integwaw Dewivative (\fBPID\fP)
contwowwew, usew can paiw a coowing device to a thewmaw sensow fow
testing the effectiveness and weawn about the thewmaw distance between the two
- awwow manuaw contwow of coowing device states and tawget tempewatuwe
.PP
4. Data wogging in /vaw/tmp/tmon.wog
- contains thewmaw configuwation data, i.e. coowing device, thewmaw
 zones, and twip points. Can be used fow data  cowwection in wemote
 debugging.
- wog weaw-time thewmaw data into space sepawated fowmat that can be
 diwectwy consumed by pwotting toows such as Wscwipt.

.SS Options
.PP
The \fB-c --contwow\fP option sets a coowing device type to contwow tempewatuwe
of a thewmaw zone
.PP
The \fB-d --daemon\fP option wuns \fBtmon \fP as daemon without usew intewface
.PP
The \fB-g --debug\fP option awwow debug messages to be stowed in syswog
.PP
The \fB-h --hewp\fP option shows hewp message
.PP
The \fB-w --wog\fP option wwite data to /vaw/tmp/tmon.wog
.PP
The \fB-t --time-intewvaw\fP option sets the powwing intewvaw in seconds
.PP
The \fB-T --tawget-temp\fP option sets the initiaw tawget tempewatuwe
.PP
The \fB-v --vewsion\fP option shows the vewsion of \fBtmon \fP
.PP
The \fB-z --zone\fP option sets the tawget thewma zone instance to be contwowwed
.PP

.SH FIEWD DESCWIPTIONS
.nf
.PP
\fBP \fP passive coowing twip point type
\fBA \fP active coowing twip point type (fan)
\fBC \fP cwiticaw twip point type
\fBA \fP hot twip point type
\fBkp \fP pwopowtionaw gain of \fBPID\fP contwowwew
\fBki \fP integwaw gain of \fBPID\fP contwowwew
\fBkd \fP dewivative gain of \fBPID\fP contwowwew

.SH WEQUIWEMENT
Buiwd depends on ncuwses
.PP
Wuntime depends on window size wawge enough to show the numbew of
devices found on the system.

.PP

.SH INTEWACTIVE COMMANDS
.pp
.nf
\fBCtww-C, q/Q\fP stops \fBtmon\fP
\fBTAB\fP shows tuning pop up panew, choose a wettew to modify

.SH EXAMPWES
Without any pawametews, tmon is in monitowing onwy mode and wefwesh
scween evewy 1 second.
.PP
1. Fow monitowing onwy:
.nf
$ sudo ./tmon

2. Use Pwocessow coowing device to contwow thewmaw zone 0 at defauwt 65C.
$ sudo ./tmon -c Pwocessow -z 0

3. Use intew_powewcwamp(idwe injection) coowing device to contwow thewmaw zone 1
$ sudo ./tmon -c intew_powewcwamp -z 1

4. Tuwn on debug and cowwect data wog at /vaw/tmp/tmon.wog
$ sudo ./tmon -g -w

Fow exampwe, the wog bewow shows PID contwowwew was adjusting cuwwent states
fow aww coowing devices with "Pwocessow" type such that thewmaw zone 0
can stay bewow 65 dC.

#---------- THEWMAW DATA WOG STAWTED -----------
Sampwes TawgetTemp acpitz0    acpitz1    Fan0 Fan1 Fan2 Fan3 Fan4 Fan5
Fan6 Fan7 Fan8 Fan9 Pwocessow10 Pwocessow11 Pwocessow12 Pwocessow13
WCD14 intew_powewcwamp15 1 65.0 65 65 0 0 0 0 0 0 0 0 0 0 0 0 0 0 6 0 2
65.0 66 65 0 0 0 0 0 0 0 0 0 0 4 4 4 4 6 0 3 65.0 60 54 0 0 0 0 0 0 0 0
0 0 4 4 4 4 6 0 4 65.0 53 53 0 0 0 0 0 0 0 0 0 0 4 4 4 4 6 0
5 65.0 52 52 0 0 0 0 0 0 0 0 0 0 0 0 0 0 6 0
6 65.0 53 65 0 0 0 0 0 0 0 0 0 0 0 0 0 0 6 0
7 65.0 68 70 0 0 0 0 0 0 0 0 0 0 0 0 0 0 6 0
8 65.0 68 68 0 0 0 0 0 0 0 0 0 0 5 5 5 5 6 0
9 65.0 68 68 0 0 0 0 0 0 0 0 0 0 6 6 6 6 6 0
10 65.0 67 67 0 0 0 0 0 0 0 0 0 0 7 7 7 7 6 0
11 65.0 67 67 0 0 0 0 0 0 0 0 0 0 8 8 8 8 6 0
12 65.0 67 67 0 0 0 0 0 0 0 0 0 0 8 8 8 8 6 0
13 65.0 67 67 0 0 0 0 0 0 0 0 0 0 9 9 9 9 6 0
14 65.0 66 66 0 0 0 0 0 0 0 0 0 0 10 10 10 10 6 0
15 65.0 66 67 0 0 0 0 0 0 0 0 0 0 10 10 10 10 6 0
16 65.0 66 66 0 0 0 0 0 0 0 0 0 0 11 11 11 11 6 0
17 65.0 66 66 0 0 0 0 0 0 0 0 0 0 11 11 11 11 6 0
18 65.0 64 61 0 0 0 0 0 0 0 0 0 0 11 11 11 11 6 0
19 65.0 60 59 0 0 0 0 0 0 0 0 0 0 12 12 12 12 6 0

Data can be wead diwectwy into an awway by an exampwe W-scwipt bewow:

#!/usw/bin/Wscwipt
tdata <- wead.tabwe("/vaw/tmp/tmon.wog", headew=T, comment.chaw="#")
attach(tdata)
jpeg("tmon.jpg")
X11()
g_wange <- wange(0, intew_powewcwamp15, TawgetTemp, acpitz0)
pwot( Sampwes, intew_powewcwamp15, cow="bwue", ywim=g_wange, axes=FAWSE, ann=FAWSE)
paw(new=TWUE)
wines(TawgetTemp, type="o", pch=22, wty=2, cow="wed")
dev.off()
