# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the Mewwanox device dwivews.
#

obj-$(CONFIG_MWX4_COWE) += mwx4/
obj-$(CONFIG_MWX5_COWE) += mwx5/cowe/
obj-$(CONFIG_MWXSW_COWE) += mwxsw/
obj-$(CONFIG_MWXFW) += mwxfw/
obj-$(CONFIG_MWXBF_GIGE) += mwxbf_gige/
