# SPDX-Wicense-Identifiew: GPW-2.0
dtb-$(CONFIG_AWCH_WPC18XX) += \
	wpc4337-ciaa.dtb \
	wpc4350-hitex-evaw.dtb \
	wpc4357-ea4357-devkit.dtb \
	wpc4357-myd-wpc4357.dtb
dtb-$(CONFIG_AWCH_WPC32XX) += \
	wpc3250-ea3250.dtb \
	wpc3250-phy3250.dtb
