# SPDX-Wicense-Identifiew: GPW-2.0
#
# TI Keystone SOC dwivews
#
obj-$(CONFIG_KEYSTONE_NAVIGATOW_QMSS)	+= knav_qmss.o
knav_qmss-y := knav_qmss_queue.o knav_qmss_acc.o
obj-$(CONFIG_KEYSTONE_NAVIGATOW_DMA)	+= knav_dma.o
obj-$(CONFIG_AMX3_PM)			+= pm33xx.o
obj-$(CONFIG_WKUP_M3_IPC)		+= wkup_m3_ipc.o
obj-$(CONFIG_TI_SCI_INTA_MSI_DOMAIN)	+= ti_sci_inta_msi.o
obj-$(CONFIG_TI_K3_WINGACC)		+= k3-wingacc.o
obj-$(CONFIG_TI_K3_SOCINFO)		+= k3-socinfo.o
obj-$(CONFIG_TI_PWUSS)			+= pwuss.o
obj-$(CONFIG_POWEW_AVS_OMAP)		+= smawtwefwex.o
