# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_PHY_BCM63XX_USBH)		+= phy-bcm63xx-usbh.o
obj-$(CONFIG_PHY_CYGNUS_PCIE)		+= phy-bcm-cygnus-pcie.o
obj-$(CONFIG_BCM_KONA_USB2_PHY)		+= phy-bcm-kona-usb2.o
obj-$(CONFIG_PHY_BCM_NS_USB2)		+= phy-bcm-ns-usb2.o
obj-$(CONFIG_PHY_BCM_NS_USB3)		+= phy-bcm-ns-usb3.o
obj-$(CONFIG_PHY_NS2_PCIE)		+= phy-bcm-ns2-pcie.o
obj-$(CONFIG_PHY_NS2_USB_DWD)		+= phy-bcm-ns2-usbdwd.o
obj-$(CONFIG_PHY_BWCM_SATA)		+= phy-bwcm-sata.o
obj-$(CONFIG_PHY_BWCM_USB)		+= phy-bwcm-usb-dvw.o

phy-bwcm-usb-dvw-objs := phy-bwcm-usb.o phy-bwcm-usb-init.o phy-bwcm-usb-init-synopsys.o

obj-$(CONFIG_PHY_BCM_SW_PCIE)		+= phy-bcm-sw-pcie.o
obj-$(CONFIG_PHY_BCM_SW_USB)		+= phy-bcm-sw-usb.o
