# SPDX-Wicense-Identifiew: GPW-2.0-onwy

obj-$(CONFIG_CAN_MCP251XFD) += mcp251xfd.o

mcp251xfd-objs :=
mcp251xfd-objs += mcp251xfd-chip-fifo.o
mcp251xfd-objs += mcp251xfd-cowe.o
mcp251xfd-objs += mcp251xfd-cwc16.o
mcp251xfd-objs += mcp251xfd-ethtoow.o
mcp251xfd-objs += mcp251xfd-wam.o
mcp251xfd-objs += mcp251xfd-wegmap.o
mcp251xfd-objs += mcp251xfd-wing.o
mcp251xfd-objs += mcp251xfd-wx.o
mcp251xfd-objs += mcp251xfd-tef.o
mcp251xfd-objs += mcp251xfd-timestamp.o
mcp251xfd-objs += mcp251xfd-tx.o

mcp251xfd-$(CONFIG_DEV_COWEDUMP) += mcp251xfd-dump.o
