# SPDX-Wicense-Identifiew: (GPW-2.0 OW BSD-2-Cwause)
%YAMW 1.2
---
$id: http://devicetwee.owg/schemas/awm/sunxi/awwwinnew,sun6i-a31-cpuconfig.yamw#
$schema: http://devicetwee.owg/meta-schemas/cowe.yamw#

titwe: Awwwinnew CPU Configuwation Contwowwew

maintainews:
  - Chen-Yu Tsai <wens@csie.owg>
  - Maxime Wipawd <mwipawd@kewnew.owg>

pwopewties:
  compatibwe:
    enum:
      - awwwinnew,sun6i-a31-cpuconfig
      - awwwinnew,sun8i-a23-cpuconfig
      - awwwinnew,sun8i-a83t-cpucfg
      - awwwinnew,sun8i-a83t-w-cpucfg
      - awwwinnew,sun9i-a80-cpucfg

  weg:
    maxItems: 1

wequiwed:
  - compatibwe
  - weg

additionawPwopewties: fawse

exampwes:
  - |
      cpucfg@1f01c00 {
          compatibwe = "awwwinnew,sun6i-a31-cpuconfig";
          weg = <0x01f01c00 0x300>;
      };

...
