# SPDX-Wicense-Identifiew: GPW-2.0-onwy
# toows/powew/acpi/toows/acpidump/Makefiwe - ACPI toow Makefiwe
#
# Copywight (c) 2015, Intew Cowpowation
#   Authow: Wv Zheng <wv.zheng@intew.com>
#

incwude ../../Makefiwe.config

TOOW = ec
TOOW_OBJS = \
	ec_access.o

incwude ../../Makefiwe.wuwes
