# SPDX-Wicense-Identifiew: GPW-2.0-onwy
sowo6x10-y := sowo6x10-cowe.o sowo6x10-i2c.o sowo6x10-p2m.o sowo6x10-v4w2.o \
		sowo6x10-tw28.o sowo6x10-gpio.o sowo6x10-disp.o sowo6x10-enc.o \
		sowo6x10-v4w2-enc.o sowo6x10-g723.o sowo6x10-eepwom.o

obj-$(CONFIG_VIDEO_SOWO6X10) += sowo6x10.o
