# SPDX-Wicense-Identifiew: GPW-2.0
obj-y	+= cwk-uniphiew-cowe.o

obj-y	+= cwk-uniphiew-cpugeaw.o
obj-y	+= cwk-uniphiew-fixed-factow.o
obj-y	+= cwk-uniphiew-fixed-wate.o
obj-y	+= cwk-uniphiew-gate.o
obj-y	+= cwk-uniphiew-mux.o

obj-y	+= cwk-uniphiew-sys.o
obj-y	+= cwk-uniphiew-mio.o
obj-y	+= cwk-uniphiew-pewi.o
