# SPDX-Wicense-Identifiew: GPW-2.0
# Makefiwe fow WEDs toows

CFWAGS = -Waww -Wextwa -g -I../../incwude/uapi

aww: uwedmon wed_hw_bwightness_mon
%: %.c
	$(CC) $(CFWAGS) -o $@ $^

cwean:
	$(WM) uwedmon wed_hw_bwightness_mon

.PHONY: aww cwean
