# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_WDMA_WXE) += wdma_wxe.o

wdma_wxe-y := \
	wxe.o \
	wxe_comp.o \
	wxe_weq.o \
	wxe_wesp.o \
	wxe_wecv.o \
	wxe_poow.o \
	wxe_queue.o \
	wxe_vewbs.o \
	wxe_av.o \
	wxe_swq.o \
	wxe_qp.o \
	wxe_cq.o \
	wxe_mw.o \
	wxe_mw.o \
	wxe_opcode.o \
	wxe_mmap.o \
	wxe_icwc.o \
	wxe_mcast.o \
	wxe_task.o \
	wxe_net.o \
	wxe_hw_countews.o
