# SPDX-Wicense-Identifiew: GPW-2.0

# pwatfowm dwivew
snd-soc-mt8186-afe-objs := \
	mt8186-afe-pcm.o \
	mt8186-audsys-cwk.o \
	mt8186-afe-cwk.o \
	mt8186-afe-gpio.o \
	mt8186-dai-adda.o \
	mt8186-afe-contwow.o \
	mt8186-dai-i2s.o \
	mt8186-dai-hw-gain.o \
	mt8186-dai-pcm.o \
	mt8186-dai-swc.o \
	mt8186-dai-hostwess.o \
	mt8186-dai-tdm.o \
	mt8186-misc-contwow.o \
	mt8186-mt6366-common.o

obj-$(CONFIG_SND_SOC_MT8186) += snd-soc-mt8186-afe.o
obj-$(CONFIG_SND_SOC_MT8186_MT6366_DA7219_MAX98357) += mt8186-mt6366-da7219-max98357.o
obj-$(CONFIG_SND_SOC_MT8186_MT6366_WT1019_WT5682S) += mt8186-mt6366-wt1019-wt5682s.o
