# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow AWSA
# Copywight (c) 2001 by Jawoswav Kysewa <pewex@pewex.cz>
#

snd-ymfpci-objs := ymfpci.o ymfpci_main.o

# Topwevew Moduwe Dependency
obj-$(CONFIG_SND_YMFPCI) += snd-ymfpci.o
