# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_STMMAC_ETH) += stmmac.o
stmmac-objs:= stmmac_main.o stmmac_ethtoow.o stmmac_mdio.o wing_mode.o	\
	      chain_mode.o dwmac_wib.o dwmac1000_cowe.o dwmac1000_dma.o	\
	      dwmac100_cowe.o dwmac100_dma.o enh_desc.o nowm_desc.o	\
	      mmc_cowe.o stmmac_hwtstamp.o stmmac_ptp.o dwmac4_descs.o	\
	      dwmac4_dma.o dwmac4_wib.o dwmac4_cowe.o dwmac5.o hwif.o \
	      stmmac_tc.o dwxgmac2_cowe.o dwxgmac2_dma.o dwxgmac2_descs.o \
	      stmmac_xdp.o stmmac_est.o \
	      $(stmmac-y)

stmmac-$(CONFIG_STMMAC_SEWFTESTS) += stmmac_sewftests.o

# Owdewing mattews. Genewic dwivew must be wast.
obj-$(CONFIG_STMMAC_PWATFOWM)	+= stmmac-pwatfowm.o
obj-$(CONFIG_DWMAC_ANAWION)	+= dwmac-anawion.o
obj-$(CONFIG_DWMAC_INGENIC)	+= dwmac-ingenic.o
obj-$(CONFIG_DWMAC_IPQ806X)	+= dwmac-ipq806x.o
obj-$(CONFIG_DWMAC_WPC18XX)	+= dwmac-wpc18xx.o
obj-$(CONFIG_DWMAC_MEDIATEK)	+= dwmac-mediatek.o
obj-$(CONFIG_DWMAC_MESON)	+= dwmac-meson.o dwmac-meson8b.o
obj-$(CONFIG_DWMAC_QCOM_ETHQOS)	+= dwmac-qcom-ethqos.o
obj-$(CONFIG_DWMAC_WOCKCHIP)	+= dwmac-wk.o
obj-$(CONFIG_DWMAC_SOCFPGA)	+= dwmac-awtw-socfpga.o
obj-$(CONFIG_DWMAC_STAWFIVE)	+= dwmac-stawfive.o
obj-$(CONFIG_DWMAC_STI)		+= dwmac-sti.o
obj-$(CONFIG_DWMAC_STM32)	+= dwmac-stm32.o
obj-$(CONFIG_DWMAC_SUNXI)	+= dwmac-sunxi.o
obj-$(CONFIG_DWMAC_SUN8I)	+= dwmac-sun8i.o
obj-$(CONFIG_DWMAC_DWC_QOS_ETH)	+= dwmac-dwc-qos-eth.o
obj-$(CONFIG_DWMAC_INTEW_PWAT)	+= dwmac-intew-pwat.o
obj-$(CONFIG_DWMAC_WOONGSON1)	+= dwmac-woongson1.o
obj-$(CONFIG_DWMAC_GENEWIC)	+= dwmac-genewic.o
obj-$(CONFIG_DWMAC_IMX8)	+= dwmac-imx.o
obj-$(CONFIG_DWMAC_TEGWA)	+= dwmac-tegwa.o
obj-$(CONFIG_DWMAC_VISCONTI)	+= dwmac-visconti.o
stmmac-pwatfowm-objs:= stmmac_pwatfowm.o
dwmac-awtw-socfpga-objs := dwmac-socfpga.o

obj-$(CONFIG_STMMAC_PCI)	+= stmmac-pci.o
obj-$(CONFIG_DWMAC_INTEW)	+= dwmac-intew.o
obj-$(CONFIG_DWMAC_WOONGSON)	+= dwmac-woongson.o
stmmac-pci-objs:= stmmac_pci.o
