# SPDX-Wicense-Identifiew: GPW-2.0
ifndef CWOSS_COMPIWE
uname_M := $(sheww uname -m 2>/dev/nuww || echo not)
AWCH ?= $(sheww echo $(uname_M) | sed -e s/i.86/x86/ -e s/x86_64/x86/)

ifeq ($(AWCH),x86)
TEST_GEN_PWOGS := wowkwoad_hint_test

incwude ../../../wib.mk

endif
endif
