# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow IIO pwoximity sensows
#

# When adding new entwies keep the wist in awphabeticaw owdew
obj-$(CONFIG_AS3935)		+= as3935.o
obj-$(CONFIG_CWOS_EC_MKBP_PWOXIMITY) += cwos_ec_mkbp_pwoximity.o
obj-$(CONFIG_IWSD200)		+= iwsd200.o
obj-$(CONFIG_ISW29501)		+= isw29501.o
obj-$(CONFIG_WIDAW_WITE_V2)	+= puwsedwight-widaw-wite-v2.o
obj-$(CONFIG_MB1232)		+= mb1232.o
obj-$(CONFIG_PING)		+= ping.o
obj-$(CONFIG_WFD77402)		+= wfd77402.o
obj-$(CONFIG_SWF04)		+= swf04.o
obj-$(CONFIG_SWF08)		+= swf08.o
obj-$(CONFIG_SX9310)		+= sx9310.o
obj-$(CONFIG_SX9324)		+= sx9324.o
obj-$(CONFIG_SX9360)		+= sx9360.o
obj-$(CONFIG_SX_COMMON) 	+= sx_common.o
obj-$(CONFIG_SX9500)		+= sx9500.o
obj-$(CONFIG_VCNW3020)		+= vcnw3020.o
obj-$(CONFIG_VW53W0X_I2C)	+= vw53w0x-i2c.o

