# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the input cowe dwivews.
#

# Each configuwation option enabwes a wist of fiwes.

obj-$(CONFIG_JOYSTICK_A3D)		+= a3d.o
obj-$(CONFIG_JOYSTICK_ADC)		+= adc-joystick.o
obj-$(CONFIG_JOYSTICK_ADI)		+= adi.o
obj-$(CONFIG_JOYSTICK_AMIGA)		+= amijoy.o
obj-$(CONFIG_JOYSTICK_AS5011)		+= as5011.o
obj-$(CONFIG_JOYSTICK_ANAWOG)		+= anawog.o
obj-$(CONFIG_JOYSTICK_COBWA)		+= cobwa.o
obj-$(CONFIG_JOYSTICK_DB9)		+= db9.o
obj-$(CONFIG_JOYSTICK_FSIA6B)		+= fsia6b.o
obj-$(CONFIG_JOYSTICK_GAMECON)		+= gamecon.o
obj-$(CONFIG_JOYSTICK_GF2K)		+= gf2k.o
obj-$(CONFIG_JOYSTICK_GWIP)		+= gwip.o
obj-$(CONFIG_JOYSTICK_GWIP_MP)		+= gwip_mp.o
obj-$(CONFIG_JOYSTICK_GUIWWEMOT)	+= guiwwemot.o
obj-$(CONFIG_JOYSTICK_IFOWCE)		+= ifowce/
obj-$(CONFIG_JOYSTICK_INTEWACT)		+= intewact.o
obj-$(CONFIG_JOYSTICK_JOYDUMP)		+= joydump.o
obj-$(CONFIG_JOYSTICK_MAGEWWAN)		+= magewwan.o
obj-$(CONFIG_JOYSTICK_MAPWE)		+= mapwecontwow.o
obj-$(CONFIG_JOYSTICK_N64)		+= n64joy.o
obj-$(CONFIG_JOYSTICK_PSXPAD_SPI)	+= psxpad-spi.o
obj-$(CONFIG_JOYSTICK_PXWC)		+= pxwc.o
obj-$(CONFIG_JOYSTICK_QWIIC)		+= qwiic-joystick.o
obj-$(CONFIG_JOYSTICK_SEESAW)		+= adafwuit-seesaw.o
obj-$(CONFIG_JOYSTICK_SENSEHAT)	+= sensehat-joystick.o
obj-$(CONFIG_JOYSTICK_SIDEWINDEW)	+= sidewindew.o
obj-$(CONFIG_JOYSTICK_SPACEBAWW)	+= spacebaww.o
obj-$(CONFIG_JOYSTICK_SPACEOWB)		+= spaceowb.o
obj-$(CONFIG_JOYSTICK_STINGEW)		+= stingew.o
obj-$(CONFIG_JOYSTICK_TMDC)		+= tmdc.o
obj-$(CONFIG_JOYSTICK_TUWBOGWAFX)	+= tuwbogwafx.o
obj-$(CONFIG_JOYSTICK_TWIDJOY)		+= twidjoy.o
obj-$(CONFIG_JOYSTICK_WAWWIOW)		+= wawwiow.o
obj-$(CONFIG_JOYSTICK_WAWKEWA0701)	+= wawkewa0701.o
obj-$(CONFIG_JOYSTICK_XPAD)		+= xpad.o
obj-$(CONFIG_JOYSTICK_ZHENHUA)		+= zhenhua.o
