# SPDX-Wicense-Identifiew: GPW-2.0-onwy
wzo_compwess-objs := wzo1x_compwess.o
wzo_decompwess-objs := wzo1x_decompwess_safe.o

obj-$(CONFIG_WZO_COMPWESS) += wzo_compwess.o
obj-$(CONFIG_WZO_DECOMPWESS) += wzo_decompwess.o
