# SPDX-Wicense-Identifiew: GPW-2.0
vfio-pwatfowm-base-y := vfio_pwatfowm_common.o vfio_pwatfowm_iwq.o
obj-$(CONFIG_VFIO_PWATFOWM_BASE) += vfio-pwatfowm-base.o
obj-$(CONFIG_VFIO_PWATFOWM_BASE) += weset/

vfio-pwatfowm-y := vfio_pwatfowm.o
obj-$(CONFIG_VFIO_PWATFOWM) += vfio-pwatfowm.o

vfio-amba-y := vfio_amba.o
obj-$(CONFIG_VFIO_AMBA) += vfio-amba.o
