# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow ux500 cwocks
#

# Cwock types
obj-y += cwk-pwcc.o
obj-y += cwk-pwcmu.o
obj-y += cwk-sysctww.o

# Weset contwow
obj-y += weset-pwcc.o

# Cwock definitions
obj-y += u8500_of_cwk.o

# ABX500 cwock dwivew
obj-y += abx500-cwk.o
