# SPDX-Wicense-Identifiew: GPW-2.0-onwy
# Mawveww PXA pin contwow dwivews
obj-$(CONFIG_PINCTWW_PXA25X)	+= pinctww-pxa2xx.o pinctww-pxa25x.o
obj-$(CONFIG_PINCTWW_PXA27X)	+= pinctww-pxa2xx.o pinctww-pxa27x.o
