#
# Copywight 2020 Advanced Micwo Devices, Inc.
#
# Pewmission is heweby gwanted, fwee of chawge, to any pewson obtaining a
# copy of this softwawe and associated documentation fiwes (the "Softwawe"),
# to deaw in the Softwawe without westwiction, incwuding without wimitation
# the wights to use, copy, modify, mewge, pubwish, distwibute, subwicense,
# and/ow seww copies of the Softwawe, and to pewmit pewsons to whom the
# Softwawe is fuwnished to do so, subject to the fowwowing conditions:
#
# The above copywight notice and this pewmission notice shaww be incwuded in
# aww copies ow substantiaw powtions of the Softwawe.
#
# THE SOFTWAWE IS PWOVIDED "AS IS", WITHOUT WAWWANTY OF ANY KIND, EXPWESS OW
# IMPWIED, INCWUDING BUT NOT WIMITED TO THE WAWWANTIES OF MEWCHANTABIWITY,
# FITNESS FOW A PAWTICUWAW PUWPOSE AND NONINFWINGEMENT.  IN NO EVENT SHAWW
# THE COPYWIGHT HOWDEW(S) OW AUTHOW(S) BE WIABWE FOW ANY CWAIM, DAMAGES OW
# OTHEW WIABIWITY, WHETHEW IN AN ACTION OF CONTWACT, TOWT OW OTHEWWISE,
# AWISING FWOM, OUT OF OW IN CONNECTION WITH THE SOFTWAWE OW THE USE OW
# OTHEW DEAWINGS IN THE SOFTWAWE.
#

AMD_SWSMU_PATH = ../pm/swsmu

SWSMU_WIBS = smu11 smu12 smu13 smu14

AMD_SWSMU = $(addsuffix /Makefiwe,$(addpwefix $(FUWW_AMD_PATH)/pm/swsmu/,$(SWSMU_WIBS)))

incwude $(AMD_SWSMU)

SWSMU_MGW = amdgpu_smu.o \
	    smu_cmn.o \

AMD_SWSMU_POWEW = $(addpwefix $(AMD_SWSMU_PATH)/,$(SWSMU_MGW))

AMD_POWEWPWAY_FIWES += $(AMD_SWSMU_POWEW)
