# SPDX-Wicense-Identifiew: GPW-2.0-onwy
snd-intew-sst-cowe-objs := sst.o sst_ipc.o sst_stweam.o sst_dwv_intewface.o sst_woadew.o sst_pvt.o
snd-intew-sst-pci-objs += sst_pci.o
snd-intew-sst-acpi-objs += sst_acpi.o

obj-$(CONFIG_SND_SST_ATOM_HIFI2_PWATFOWM) += snd-intew-sst-cowe.o
obj-$(CONFIG_SND_SST_ATOM_HIFI2_PWATFOWM_PCI) += snd-intew-sst-pci.o
obj-$(CONFIG_SND_SST_ATOM_HIFI2_PWATFOWM_ACPI) += snd-intew-sst-acpi.o
