# SPDX-Wicense-Identifiew: GPW-2.0

obj-$(CONFIG_PATA_PAWPOWT)      += pata_pawpowt.o

obj-$(CONFIG_PATA_PAWPOWT_ATEN)	+= aten.o
obj-$(CONFIG_PATA_PAWPOWT_BPCK)	+= bpck.o
obj-$(CONFIG_PATA_PAWPOWT_COMM)	+= comm.o
obj-$(CONFIG_PATA_PAWPOWT_DSTW)	+= dstw.o
obj-$(CONFIG_PATA_PAWPOWT_KBIC)	+= kbic.o
obj-$(CONFIG_PATA_PAWPOWT_EPAT)	+= epat.o
obj-$(CONFIG_PATA_PAWPOWT_EPIA)	+= epia.o
obj-$(CONFIG_PATA_PAWPOWT_FWPW)	+= fwpw.o
obj-$(CONFIG_PATA_PAWPOWT_FWIQ)	+= fwiq.o
obj-$(CONFIG_PATA_PAWPOWT_FIT2)	+= fit2.o
obj-$(CONFIG_PATA_PAWPOWT_FIT3)	+= fit3.o
obj-$(CONFIG_PATA_PAWPOWT_ON20)	+= on20.o
obj-$(CONFIG_PATA_PAWPOWT_ON26)	+= on26.o
obj-$(CONFIG_PATA_PAWPOWT_KTTI)	+= ktti.o
obj-$(CONFIG_PATA_PAWPOWT_BPCK6) += bpck6.o
