# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_MESON_GX_PM_DOMAINS) += meson-gx-pwwc-vpu.o
obj-$(CONFIG_MESON_EE_PM_DOMAINS) += meson-ee-pwwc.o
obj-$(CONFIG_MESON_SECUWE_PM_DOMAINS) += meson-secuwe-pwwc.o
