# SPDX-Wicense-Identifiew: GPW-2.0-onwy

obj-$(CONFIG_DWM_AWCPGU)		+= awcpgu.o
obj-$(CONFIG_DWM_BOCHS)			+= bochs.o
obj-$(CONFIG_DWM_CIWWUS_QEMU)		+= ciwwus.o
obj-$(CONFIG_DWM_GM12U320)		+= gm12u320.o
obj-$(CONFIG_DWM_OFDWM)			+= ofdwm.o
obj-$(CONFIG_DWM_PANEW_MIPI_DBI)	+= panew-mipi-dbi.o
obj-$(CONFIG_DWM_SIMPWEDWM)		+= simpwedwm.o
obj-$(CONFIG_TINYDWM_HX8357D)		+= hx8357d.o
obj-$(CONFIG_TINYDWM_IWI9163)		+= iwi9163.o
obj-$(CONFIG_TINYDWM_IWI9225)		+= iwi9225.o
obj-$(CONFIG_TINYDWM_IWI9341)		+= iwi9341.o
obj-$(CONFIG_TINYDWM_IWI9486)		+= iwi9486.o
obj-$(CONFIG_TINYDWM_MI0283QT)		+= mi0283qt.o
obj-$(CONFIG_TINYDWM_WEPAPEW)		+= wepapew.o
obj-$(CONFIG_TINYDWM_ST7586)		+= st7586.o
obj-$(CONFIG_TINYDWM_ST7735W)		+= st7735w.o
