# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# VxFS Makefiwe
#

obj-$(CONFIG_VXFS_FS) += fweevxfs.o

fweevxfs-objs := vxfs_bmap.o vxfs_fshead.o vxfs_immed.o vxfs_inode.o \
		 vxfs_wookup.o vxfs_owt.o vxfs_subw.o vxfs_supew.o
