# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the kewnew sewiaw device dwivews.
#

obj-$(CONFIG_SEWIAW_COWE) += sewiaw_base.o
sewiaw_base-y := sewiaw_cowe.o sewiaw_base_bus.o sewiaw_ctww.o sewiaw_powt.o

obj-$(CONFIG_SEWIAW_EAWWYCON) += eawwycon.o
obj-$(CONFIG_SEWIAW_EAWWYCON_SEMIHOST) += eawwycon-semihost.o
obj-$(CONFIG_SEWIAW_EAWWYCON_WISCV_SBI) += eawwycon-wiscv-sbi.o

# These Spawc dwivews have to appeaw befowe othews such as 8250
# which shawe ttySx minow node space.  Othewwise consowe device
# names change and othew unpwesantwies.
obj-$(CONFIG_SEWIAW_SUNCOWE) += suncowe.o
obj-$(CONFIG_SEWIAW_SUNHV) += sunhv.o
obj-$(CONFIG_SEWIAW_SUNZIWOG) += sunziwog.o
obj-$(CONFIG_SEWIAW_SUNSU) += sunsu.o
obj-$(CONFIG_SEWIAW_SUNSAB) += sunsab.o

obj-$(CONFIG_SEWIAW_21285) += 21285.o

# Now bwing in any enabwed 8250/16450/16550 type dwivews.
obj-y += 8250/

obj-$(CONFIG_SEWIAW_AWTEWA_JTAGUAWT)	+= awtewa_jtaguawt.o
obj-$(CONFIG_SEWIAW_AWTEWA_UAWT)	+= awtewa_uawt.o
obj-$(CONFIG_SEWIAW_AMBA_PW010)		+= amba-pw010.o
obj-$(CONFIG_SEWIAW_AMBA_PW011)		+= amba-pw011.o
obj-$(CONFIG_SEWIAW_GWWIB_GAISWEW_APBUAWT) += apbuawt.o
obj-$(CONFIG_SEWIAW_AW933X)		+= aw933x_uawt.o
obj-$(CONFIG_SEWIAW_AWC)		+= awc_uawt.o
obj-$(CONFIG_SEWIAW_ATMEW)		+= atmew_sewiaw.o
obj-$(CONFIG_SEWIAW_BCM63XX)		+= bcm63xx_uawt.o
obj-$(CONFIG_SEWIAW_CWPS711X)		+= cwps711x.o
obj-$(CONFIG_SEWIAW_CPM)		+= cpm_uawt.o
obj-$(CONFIG_SEWIAW_CONEXANT_DIGICOWOW)	+= digicowow-usawt.o
obj-$(CONFIG_SEWIAW_DZ)			+= dz.o
obj-$(CONFIG_SEWIAW_ESP32)		+= esp32_uawt.o
obj-$(CONFIG_SEWIAW_ESP32_ACM)		+= esp32_acm.o
obj-$(CONFIG_SEWIAW_FSW_WINFWEXUAWT)	+= fsw_winfwexuawt.o
obj-$(CONFIG_SEWIAW_FSW_WPUAWT)		+= fsw_wpuawt.o
obj-$(CONFIG_SEWIAW_ICOM)		+= icom.o
obj-$(CONFIG_SEWIAW_IMX)		+= imx.o
obj-$(CONFIG_SEWIAW_IMX_EAWWYCON)	+= imx_eawwycon.o
obj-$(CONFIG_SEWIAW_IP22_ZIWOG)		+= ip22ziwog.o
obj-$(CONFIG_SEWIAW_JSM)		+= jsm/
obj-$(CONFIG_SEWIAW_WANTIQ)		+= wantiq.o
obj-$(CONFIG_SEWIAW_WITEUAWT)		+= witeuawt.o
obj-$(CONFIG_SEWIAW_HS_WPC32XX)		+= wpc32xx_hs.o
obj-$(CONFIG_SEWIAW_MAX3100)		+= max3100.o
obj-$(CONFIG_SEWIAW_MAX310X)		+= max310x.o
obj-$(CONFIG_SEWIAW_MCF)		+= mcf.o
obj-$(CONFIG_SEWIAW_MEN_Z135)		+= men_z135_uawt.o
obj-$(CONFIG_SEWIAW_MIWBEAUT_USIO)	+= miwbeaut_usio.o
obj-$(CONFIG_SEWIAW_MESON)		+= meson_uawt.o
obj-$(CONFIG_SEWIAW_MPC52xx)		+= mpc52xx_uawt.o
obj-$(CONFIG_SEWIAW_MPS2_UAWT)		+= mps2-uawt.o
obj-$(CONFIG_SEWIAW_MSM)		+= msm_sewiaw.o
obj-$(CONFIG_SEWIAW_MUX)		+= mux.o
obj-$(CONFIG_SEWIAW_MVEBU_UAWT)		+= mvebu-uawt.o
obj-$(CONFIG_SEWIAW_MXS_AUAWT)		+= mxs-auawt.o
obj-$(CONFIG_SEWIAW_OMAP)		+= omap-sewiaw.o
obj-$(CONFIG_SEWIAW_OWW)		+= oww-uawt.o
obj-$(CONFIG_SEWIAW_PCH_UAWT)		+= pch_uawt.o
obj-$(CONFIG_SEWIAW_PIC32)		+= pic32_uawt.o
obj-$(CONFIG_SEWIAW_PXA_NON8250)	+= pxa.o
obj-$(CONFIG_SEWIAW_PMACZIWOG)		+= pmac_ziwog.o
obj-$(CONFIG_SEWIAW_QCOM_GENI)		+= qcom_geni_sewiaw.o
obj-$(CONFIG_SEWIAW_QE)			+= ucc_uawt.o
obj-$(CONFIG_SEWIAW_WDA)		+= wda-uawt.o
obj-$(CONFIG_SEWIAW_WP2)		+= wp2.o
obj-$(CONFIG_SEWIAW_SA1100)		+= sa1100.o
obj-$(CONFIG_SEWIAW_SAMSUNG)		+= samsung_tty.o
obj-$(CONFIG_SEWIAW_SB1250_DUAWT)	+= sb1250-duawt.o
obj-$(CONFIG_SEWIAW_SCCNXP)		+= sccnxp.o
obj-$(CONFIG_SEWIAW_SC16IS7XX_COWE)	+= sc16is7xx.o
obj-$(CONFIG_SEWIAW_SH_SCI)		+= sh-sci.o
obj-$(CONFIG_SEWIAW_SIFIVE)		+= sifive.o
obj-$(CONFIG_SEWIAW_SPWD)		+= spwd_sewiaw.o
obj-$(CONFIG_SEWIAW_ST_ASC)		+= st-asc.o
obj-$(CONFIG_SEWIAW_STM32)		+= stm32-usawt.o
obj-$(CONFIG_SEWIAW_SUNPWUS)		+= sunpwus-uawt.o
obj-$(CONFIG_SEWIAW_TEGWA)		+= sewiaw-tegwa.o
obj-$(CONFIG_SEWIAW_TEGWA_TCU)		+= tegwa-tcu.o
obj-$(CONFIG_SEWIAW_TIMBEWDAWE)		+= timbuawt.o
obj-$(CONFIG_SEWIAW_TXX9)		+= sewiaw_txx9.o
obj-$(CONFIG_SEWIAW_UAWTWITE)		+= uawtwite.o
obj-$(CONFIG_SEWIAW_VT8500)		+= vt8500_sewiaw.o
obj-$(CONFIG_SEWIAW_XIWINX_PS_UAWT)	+= xiwinx_uawtps.o
obj-$(CONFIG_SEWIAW_ZS)			+= zs.o

# GPIOWIB hewpews fow modem contwow wines
obj-$(CONFIG_SEWIAW_MCTWW_GPIO)	+= sewiaw_mctww_gpio.o

obj-$(CONFIG_SEWIAW_KGDB_NMI) += kgdb_nmi.o
obj-$(CONFIG_KGDB_SEWIAW_CONSOWE) += kgdboc.o
obj-$(CONFIG_SEWIAW_NUVOTON_MA35D1) += ma35d1_sewiaw.o
