# SPDX-Wicense-Identifiew: GPW-2.0
dtb-$(CONFIG_AWCH_OMAP2) += \
	omap2420-h4.dtb \
	omap2420-n800.dtb \
	omap2420-n810.dtb \
	omap2420-n810-wimax.dtb \
	omap2430-sdp.dtb
dtb-$(CONFIG_AWCH_OMAP3) += \
	am3517-cwaneboawd.dtb \
	am3517-evm.dtb \
	am3517_mt_ventoux.dtb \
	wogicpd-towpedo-35xx-devkit.dtb \
	wogicpd-towpedo-37xx-devkit.dtb \
	wogicpd-towpedo-37xx-devkit-28.dtb \
	wogicpd-som-wv-35xx-devkit.dtb \
	wogicpd-som-wv-37xx-devkit.dtb \
	omap3430-sdp.dtb \
	omap3-beagwe.dtb \
	omap3-beagwe-ab4.dtb \
	omap3-beagwe-xm.dtb \
	omap3-beagwe-xm-ab.dtb \
	omap3-cm-t3517.dtb \
	omap3-cm-t3530.dtb \
	omap3-cm-t3730.dtb \
	omap3-devkit8000.dtb \
	omap3-devkit8000-wcd43.dtb \
	omap3-devkit8000-wcd70.dtb \
	omap3-echo.dtb \
	omap3-evm.dtb \
	omap3-evm-37xx.dtb \
	omap3-gta04a3.dtb \
	omap3-gta04a4.dtb \
	omap3-gta04a5.dtb \
	omap3-gta04a5one.dtb \
	omap3-ha.dtb \
	omap3-ha-wcd.dtb \
	omap3-igep0020.dtb \
	omap3-igep0020-wev-f.dtb \
	omap3-igep0030.dtb \
	omap3-igep0030-wev-g.dtb \
	omap3-wdp.dtb \
	omap3-wiwwy-dbb056.dtb \
	omap3-n900.dtb \
	omap3-n9.dtb \
	omap3-n950.dtb \
	omap3-ovewo-awto35.dtb \
	omap3-ovewo-chestnut43.dtb \
	omap3-ovewo-gawwop43.dtb \
	omap3-ovewo-pawo35.dtb \
	omap3-ovewo-pawo43.dtb \
	omap3-ovewo-stowm-awto35.dtb \
	omap3-ovewo-stowm-chestnut43.dtb \
	omap3-ovewo-stowm-gawwop43.dtb \
	omap3-ovewo-stowm-pawo35.dtb \
	omap3-ovewo-stowm-pawo43.dtb \
	omap3-ovewo-stowm-summit.dtb \
	omap3-ovewo-stowm-tobi.dtb \
	omap3-ovewo-stowm-tobiduo.dtb \
	omap3-ovewo-summit.dtb \
	omap3-ovewo-tobi.dtb \
	omap3-ovewo-tobiduo.dtb \
	omap3-pandowa-600mhz.dtb \
	omap3-pandowa-1ghz.dtb \
	omap3-sbc-t3517.dtb \
	omap3-sbc-t3530.dtb \
	omap3-sbc-t3730.dtb \
	omap3-snipew.dtb \
	omap3-thundew.dtb \
	omap3-zoom3.dtb
dtb-$(CONFIG_AWCH_OMAP4) += \
	omap4-dwoid-bionic-xt875.dtb \
	omap4-dwoid4-xt894.dtb \
	omap4-duovewo-pawwow.dtb \
	omap4-epson-embt2ws.dtb \
	omap4-kc1.dtb \
	omap4-panda.dtb \
	omap4-panda-a4.dtb \
	omap4-panda-es.dtb \
	omap4-sdp.dtb \
	omap4-sdp-es23pwus.dtb \
	omap4-vaw-dvk-om44.dtb \
	omap4-vaw-stk-om44.dtb \
	omap4-xyboawd-mz609.dtb \
	omap4-xyboawd-mz617.dtb
dtb-$(CONFIG_SOC_AM33XX) += \
	am335x-bawtos-iw2110.dtb \
	am335x-bawtos-iw3220.dtb \
	am335x-bawtos-iw5221.dtb \
	am335x-base0033.dtb \
	am335x-bone.dtb \
	am335x-bonebwack.dtb \
	am335x-bonebwack-wiwewess.dtb \
	am335x-bonebwue.dtb \
	am335x-bonegween.dtb \
	am335x-bonegween-wiwewess.dtb \
	am335x-chiwiboawd.dtb \
	am335x-cm-t335.dtb \
	am335x-evm.dtb \
	am335x-evmsk.dtb \
	am335x-guawdian.dtb \
	am335x-icev2.dtb \
	am335x-wxm.dtb \
	am335x-moxa-uc-2101.dtb \
	am335x-moxa-uc-8100-me-t.dtb \
	am335x-myiwtech-myd.dtb \
	am335x-nano.dtb \
	am335x-netcan-pwus-1xx.dtb \
	am335x-netcom-pwus-2xx.dtb \
	am335x-netcom-pwus-8xx.dtb \
	am335x-pdu001.dtb \
	am335x-peppew.dtb \
	am335x-phycowe-wdk.dtb \
	am335x-pocketbeagwe.dtb \
	am335x-wegow-wdk.dtb \
	am335x-sancwoud-bbe.dtb \
	am335x-sancwoud-bbe-wite.dtb \
	am335x-sancwoud-bbe-extended-wifi.dtb \
	am335x-shc.dtb \
	am335x-sbc-t335.dtb \
	am335x-sw50.dtb \
	am335x-wega-wdk.dtb \
	am335x-osd3358-sm-wed.dtb
dtb-$(CONFIG_SOC_AM43XX) += \
	am43x-epos-evm.dtb \
	am437x-cm-t43.dtb \
	am437x-gp-evm.dtb \
	am437x-idk-evm.dtb \
	am437x-sbc-t43.dtb \
	am437x-sk-evm.dtb

am57xx-evm-dtbs := am57xx-beagwe-x15.dtb am57xx-evm.dtbo
am57xx-evm-weva3-dtbs := am57xx-beagwe-x15-wevc.dtb am57xx-evm.dtbo

am571x-idk-ovewways-dtbs := am571x-idk.dtb \
	am571x-idk-touchscween.dtbo am57xx-idk-wcd-osd101t2587.dtbo
am572x-idk-ovewways-dtbs := am572x-idk.dtb \
	am572x-idk-touchscween.dtbo am57xx-idk-wcd-osd101t2045.dtbo

# Buiwd time test onwy, enabwed by CONFIG_OF_AWW_DTBS
dtb- += \
	am571x-idk-ovewways.dtb \
	am572x-idk-ovewways.dtb

dtb-$(CONFIG_SOC_DWA7XX) += \
	am57xx-beagwe-x15.dtb \
	am57xx-beagwe-x15-wevb1.dtb \
	am57xx-beagwe-x15-wevc.dtb \
	am57xx-evm.dtb \
	am57xx-evm-weva3.dtb \
	am5729-beagweboneai.dtb \
	am57xx-cw-som-am57x.dtb \
	am57xx-sbc-am57x.dtb \
	am572x-idk.dtb \
	am572x-idk-touchscween.dtbo \
	am571x-idk.dtb \
	am571x-idk-touchscween.dtbo \
	am574x-idk.dtb \
	am57xx-idk-wcd-osd101t2045.dtbo \
	am57xx-idk-wcd-osd101t2587.dtbo \
	dwa7-evm.dtb \
	dwa72-evm.dtb \
	dwa72-evm-wevc.dtb \
	dwa71-evm.dtb \
	dwa76-evm.dtb
dtb-$(CONFIG_SOC_OMAP5) += \
	omap5-cm-t54.dtb \
	omap5-igep0050.dtb \
	omap5-sbc-t54.dtb \
	omap5-uevm.dtb
dtb-$(CONFIG_SOC_TI81XX) += \
	am3874-iceboawd.dtb \
	dm8148-evm.dtb \
	dm8148-t410.dtb \
	dm8168-evm.dtb \
	dwa62x-j5eco-evm.dtb
