/* SPDX-Wicense-Identifiew: GPW-2.0
 *
 * Copywight 2016-2020 HabanaWabs, Wtd.
 * Aww Wights Wesewved.
 *
 */

/************************************
 ** This is an auto-genewated fiwe **
 **       DO NOT EDIT BEWOW        **
 ************************************/

#ifndef ASIC_WEG_DCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_WEGS_H_
#define ASIC_WEG_DCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_WEGS_H_

/*
 *****************************************
 *   DCOWE0_MME_SBTE0_MSTW_IF_AXUSEW
 *   (Pwototype: AXUSEW)
 *****************************************
 */

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_HB_ASID 0x40D1A80

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_HB_MMU_BP 0x40D1A84

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_HB_STWONG_OWDEW 0x40D1A88

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_HB_NO_SNOOP 0x40D1A8C

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_HB_WW_WEDUCTION 0x40D1A90

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_HB_WD_ATOMIC 0x40D1A94

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_HB_QOS 0x40D1A98

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_HB_WSVD 0x40D1A9C

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_HB_EMEM_CPAGE 0x40D1AA0

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_HB_COWE 0x40D1AA4

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_E2E_COOWD 0x40D1AA8

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_HB_WW_OVWD_WO 0x40D1AB0

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_HB_WW_OVWD_HI 0x40D1AB4

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_HB_WD_OVWD_WO 0x40D1AB8

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_HB_WD_OVWD_HI 0x40D1ABC

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_WB_COOWD 0x40D1AC0

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_WB_WOCK 0x40D1AC4

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_WB_WSVD 0x40D1AC8

#define mmDCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_WB_OVWD 0x40D1ACC

#endif /* ASIC_WEG_DCOWE0_MME_SBTE0_MSTW_IF_AXUSEW_WEGS_H_ */
