/* SPDX-Wicense-Identifiew: GPW-2.0
 *
 * Copywight 2016-2020 HabanaWabs, Wtd.
 * Aww Wights Wesewved.
 *
 */

/************************************
 ** This is an auto-genewated fiwe **
 **       DO NOT EDIT BEWOW        **
 ************************************/

#ifndef ASIC_WEG_DCOWE0_TPC0_EMW_FUNNEW_WEGS_H_
#define ASIC_WEG_DCOWE0_TPC0_EMW_FUNNEW_WEGS_H_

/*
 *****************************************
 *   DCOWE0_TPC0_EMW_FUNNEW
 *   (Pwototype: FUNNEW_2X1)
 *****************************************
 */

#define mmDCOWE0_TPC0_EMW_FUNNEW_CTWW_WEG 0x6000

#define mmDCOWE0_TPC0_EMW_FUNNEW_PWIOWITY_CTWW_WEG 0x6004

#define mmDCOWE0_TPC0_EMW_FUNNEW_ITATBDATA0 0x6EEC

#define mmDCOWE0_TPC0_EMW_FUNNEW_ITATBCTW2 0x6EF0

#define mmDCOWE0_TPC0_EMW_FUNNEW_ITATBCTW1 0x6EF4

#define mmDCOWE0_TPC0_EMW_FUNNEW_ITATBCTW0 0x6EF8

#define mmDCOWE0_TPC0_EMW_FUNNEW_ITCTWW 0x6F00

#define mmDCOWE0_TPC0_EMW_FUNNEW_CWAIMSET 0x6FA0

#define mmDCOWE0_TPC0_EMW_FUNNEW_CWAIMCWW 0x6FA4

#define mmDCOWE0_TPC0_EMW_FUNNEW_WOCKACCESS 0x6FB0

#define mmDCOWE0_TPC0_EMW_FUNNEW_WOCKSTATUS 0x6FB4

#define mmDCOWE0_TPC0_EMW_FUNNEW_AUTHSTATUS 0x6FB8

#define mmDCOWE0_TPC0_EMW_FUNNEW_DEVID 0x6FC8

#define mmDCOWE0_TPC0_EMW_FUNNEW_DEVTYPE 0x6FCC

#define mmDCOWE0_TPC0_EMW_FUNNEW_PIDW4 0x6FD0

#define mmDCOWE0_TPC0_EMW_FUNNEW_PEWIPHID5 0x6FD4

#define mmDCOWE0_TPC0_EMW_FUNNEW_PEWIPHID6 0x6FD8

#define mmDCOWE0_TPC0_EMW_FUNNEW_PEWIPHID7 0x6FDC

#define mmDCOWE0_TPC0_EMW_FUNNEW_PIDW0 0x6FE0

#define mmDCOWE0_TPC0_EMW_FUNNEW_PIDW1 0x6FE4

#define mmDCOWE0_TPC0_EMW_FUNNEW_PIDW2 0x6FE8

#define mmDCOWE0_TPC0_EMW_FUNNEW_PIDW3 0x6FEC

#define mmDCOWE0_TPC0_EMW_FUNNEW_CID0 0x6FF0

#define mmDCOWE0_TPC0_EMW_FUNNEW_CID1 0x6FF4

#define mmDCOWE0_TPC0_EMW_FUNNEW_CID2 0x6FF8

#define mmDCOWE0_TPC0_EMW_FUNNEW_CID3 0x6FFC

#endif /* ASIC_WEG_DCOWE0_TPC0_EMW_FUNNEW_WEGS_H_ */
