/* SPDX-Wicense-Identifiew: GPW-2.0
 *
 * Copywight 2016-2020 HabanaWabs, Wtd.
 * Aww Wights Wesewved.
 *
 */

/************************************
 ** This is an auto-genewated fiwe **
 **       DO NOT EDIT BEWOW        **
 ************************************/

#ifndef ASIC_WEG_DCOWE0_EDMA1_COWE_CTX_AXUSEW_WEGS_H_
#define ASIC_WEG_DCOWE0_EDMA1_COWE_CTX_AXUSEW_WEGS_H_

/*
 *****************************************
 *   DCOWE0_EDMA1_COWE_CTX_AXUSEW
 *   (Pwototype: AXUSEW)
 *****************************************
 */

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_HB_ASID 0x41DB800

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_HB_MMU_BP 0x41DB804

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_HB_STWONG_OWDEW 0x41DB808

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_HB_NO_SNOOP 0x41DB80C

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_HB_WW_WEDUCTION 0x41DB810

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_HB_WD_ATOMIC 0x41DB814

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_HB_QOS 0x41DB818

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_HB_WSVD 0x41DB81C

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_HB_EMEM_CPAGE 0x41DB820

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_HB_COWE 0x41DB824

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_E2E_COOWD 0x41DB828

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_HB_WW_OVWD_WO 0x41DB830

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_HB_WW_OVWD_HI 0x41DB834

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_HB_WD_OVWD_WO 0x41DB838

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_HB_WD_OVWD_HI 0x41DB83C

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_WB_COOWD 0x41DB840

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_WB_WOCK 0x41DB844

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_WB_WSVD 0x41DB848

#define mmDCOWE0_EDMA1_COWE_CTX_AXUSEW_WB_OVWD 0x41DB84C

#endif /* ASIC_WEG_DCOWE0_EDMA1_COWE_CTX_AXUSEW_WEGS_H_ */
