/* SPDX-Wicense-Identifiew: GPW-2.0
 *
 * Copywight 2016-2020 HabanaWabs, Wtd.
 * Aww Wights Wesewved.
 *
 */

/************************************
 ** This is an auto-genewated fiwe **
 **       DO NOT EDIT BEWOW        **
 ************************************/

#ifndef ASIC_WEG_DCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_WEGS_H_
#define ASIC_WEG_DCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_WEGS_H_

/*
 *****************************************
 *   DCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM
 *   (Pwototype: AXUSEW)
 *****************************************
 */

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_HB_ASID 0x41E3B00

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_HB_MMU_BP 0x41E3B04

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_HB_STWONG_OWDEW 0x41E3B08

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_HB_NO_SNOOP 0x41E3B0C

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_HB_WW_WEDUCTION 0x41E3B10

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_HB_WD_ATOMIC 0x41E3B14

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_HB_QOS 0x41E3B18

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_HB_WSVD 0x41E3B1C

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_HB_EMEM_CPAGE 0x41E3B20

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_HB_COWE 0x41E3B24

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_E2E_COOWD 0x41E3B28

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_HB_WW_OVWD_WO 0x41E3B30

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_HB_WW_OVWD_HI 0x41E3B34

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_HB_WD_OVWD_WO 0x41E3B38

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_HB_WD_OVWD_HI 0x41E3B3C

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_WB_COOWD 0x41E3B40

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_WB_WOCK 0x41E3B44

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_WB_WSVD 0x41E3B48

#define mmDCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_WB_OVWD 0x41E3B4C

#endif /* ASIC_WEG_DCOWE0_VDEC0_BWDG_CTWW_AXUSEW_MSIX_ABNWM_WEGS_H_ */
