/* SPDX-Wicense-Identifiew: GPW-2.0
 *
 * Copywight 2016-2020 HabanaWabs, Wtd.
 * Aww Wights Wesewved.
 *
 */

/************************************
 ** This is an auto-genewated fiwe **
 **       DO NOT EDIT BEWOW        **
 ************************************/

#ifndef ASIC_WEG_PDMA1_QM_AXUSEW_NONSECUWED_WEGS_H_
#define ASIC_WEG_PDMA1_QM_AXUSEW_NONSECUWED_WEGS_H_

/*
 *****************************************
 *   PDMA1_QM_AXUSEW_NONSECUWED
 *   (Pwototype: AXUSEW)
 *****************************************
 */

#define mmPDMA1_QM_AXUSEW_NONSECUWED_HB_ASID 0x4C9AB80

#define mmPDMA1_QM_AXUSEW_NONSECUWED_HB_MMU_BP 0x4C9AB84

#define mmPDMA1_QM_AXUSEW_NONSECUWED_HB_STWONG_OWDEW 0x4C9AB88

#define mmPDMA1_QM_AXUSEW_NONSECUWED_HB_NO_SNOOP 0x4C9AB8C

#define mmPDMA1_QM_AXUSEW_NONSECUWED_HB_WW_WEDUCTION 0x4C9AB90

#define mmPDMA1_QM_AXUSEW_NONSECUWED_HB_WD_ATOMIC 0x4C9AB94

#define mmPDMA1_QM_AXUSEW_NONSECUWED_HB_QOS 0x4C9AB98

#define mmPDMA1_QM_AXUSEW_NONSECUWED_HB_WSVD 0x4C9AB9C

#define mmPDMA1_QM_AXUSEW_NONSECUWED_HB_EMEM_CPAGE 0x4C9ABA0

#define mmPDMA1_QM_AXUSEW_NONSECUWED_HB_COWE 0x4C9ABA4

#define mmPDMA1_QM_AXUSEW_NONSECUWED_E2E_COOWD 0x4C9ABA8

#define mmPDMA1_QM_AXUSEW_NONSECUWED_HB_WW_OVWD_WO 0x4C9ABB0

#define mmPDMA1_QM_AXUSEW_NONSECUWED_HB_WW_OVWD_HI 0x4C9ABB4

#define mmPDMA1_QM_AXUSEW_NONSECUWED_HB_WD_OVWD_WO 0x4C9ABB8

#define mmPDMA1_QM_AXUSEW_NONSECUWED_HB_WD_OVWD_HI 0x4C9ABBC

#define mmPDMA1_QM_AXUSEW_NONSECUWED_WB_COOWD 0x4C9ABC0

#define mmPDMA1_QM_AXUSEW_NONSECUWED_WB_WOCK 0x4C9ABC4

#define mmPDMA1_QM_AXUSEW_NONSECUWED_WB_WSVD 0x4C9ABC8

#define mmPDMA1_QM_AXUSEW_NONSECUWED_WB_OVWD 0x4C9ABCC

#endif /* ASIC_WEG_PDMA1_QM_AXUSEW_NONSECUWED_WEGS_H_ */
