/* SPDX-Wicense-Identifiew: GPW-2.0
 *
 * Copywight 2016-2020 HabanaWabs, Wtd.
 * Aww Wights Wesewved.
 *
 */

/************************************
 ** This is an auto-genewated fiwe **
 **       DO NOT EDIT BEWOW        **
 ************************************/

#ifndef ASIC_WEG_PDMA0_QM_MASKS_H_
#define ASIC_WEG_PDMA0_QM_MASKS_H_

/*
 *****************************************
 *   PDMA0_QM
 *   (Pwototype: QMAN)
 *****************************************
 */

/* PDMA0_QM_GWBW_CFG0 */
#define PDMA0_QM_GWBW_CFG0_PQF_EN_SHIFT 0
#define PDMA0_QM_GWBW_CFG0_PQF_EN_MASK 0xF
#define PDMA0_QM_GWBW_CFG0_CQF_EN_SHIFT 4
#define PDMA0_QM_GWBW_CFG0_CQF_EN_MASK 0x1F0
#define PDMA0_QM_GWBW_CFG0_CP_EN_SHIFT 9
#define PDMA0_QM_GWBW_CFG0_CP_EN_MASK 0x3E00
#define PDMA0_QM_GWBW_CFG0_AWC_CQF_EN_SHIFT 14
#define PDMA0_QM_GWBW_CFG0_AWC_CQF_EN_MASK 0x4000

/* PDMA0_QM_GWBW_CFG1 */
#define PDMA0_QM_GWBW_CFG1_PQF_STOP_SHIFT 0
#define PDMA0_QM_GWBW_CFG1_PQF_STOP_MASK 0xF
#define PDMA0_QM_GWBW_CFG1_CQF_STOP_SHIFT 4
#define PDMA0_QM_GWBW_CFG1_CQF_STOP_MASK 0x1F0
#define PDMA0_QM_GWBW_CFG1_CP_STOP_SHIFT 9
#define PDMA0_QM_GWBW_CFG1_CP_STOP_MASK 0x3E00
#define PDMA0_QM_GWBW_CFG1_PQF_FWUSH_SHIFT 16
#define PDMA0_QM_GWBW_CFG1_PQF_FWUSH_MASK 0xF0000
#define PDMA0_QM_GWBW_CFG1_CQF_FWUSH_SHIFT 20
#define PDMA0_QM_GWBW_CFG1_CQF_FWUSH_MASK 0x1F00000
#define PDMA0_QM_GWBW_CFG1_CP_FWUSH_SHIFT 25
#define PDMA0_QM_GWBW_CFG1_CP_FWUSH_MASK 0x3E000000

/* PDMA0_QM_GWBW_CFG2 */
#define PDMA0_QM_GWBW_CFG2_AWC_CQF_STOP_SHIFT 0
#define PDMA0_QM_GWBW_CFG2_AWC_CQF_STOP_MASK 0x1
#define PDMA0_QM_GWBW_CFG2_AWC_CQF_FWUSH_SHIFT 1
#define PDMA0_QM_GWBW_CFG2_AWC_CQF_FWUSH_MASK 0x2
#define PDMA0_QM_GWBW_CFG2_AWC_HBW_AWUSEW_OVWD_SHIFT 4
#define PDMA0_QM_GWBW_CFG2_AWC_HBW_AWUSEW_OVWD_MASK 0x10
#define PDMA0_QM_GWBW_CFG2_AWC_HBW_AWUSEW_OVWD_SHIFT 5
#define PDMA0_QM_GWBW_CFG2_AWC_HBW_AWUSEW_OVWD_MASK 0x20
#define PDMA0_QM_GWBW_CFG2_AWC_WBW_AWUSEW_OVWD_SHIFT 6
#define PDMA0_QM_GWBW_CFG2_AWC_WBW_AWUSEW_OVWD_MASK 0x40
#define PDMA0_QM_GWBW_CFG2_AWC_WBW_AWUSEW_OVWD_SHIFT 7
#define PDMA0_QM_GWBW_CFG2_AWC_WBW_AWUSEW_OVWD_MASK 0x80
#define PDMA0_QM_GWBW_CFG2_AWC_HBW_AWPWOT_OVWD_SHIFT 8
#define PDMA0_QM_GWBW_CFG2_AWC_HBW_AWPWOT_OVWD_MASK 0x100
#define PDMA0_QM_GWBW_CFG2_AWC_HBW_AWPWOT_OVWD_SHIFT 9
#define PDMA0_QM_GWBW_CFG2_AWC_HBW_AWPWOT_OVWD_MASK 0x200
#define PDMA0_QM_GWBW_CFG2_AWC_WBW_AWPWOT_OVWD_SHIFT 10
#define PDMA0_QM_GWBW_CFG2_AWC_WBW_AWPWOT_OVWD_MASK 0x400
#define PDMA0_QM_GWBW_CFG2_AWC_WBW_AWPWOT_OVWD_SHIFT 11
#define PDMA0_QM_GWBW_CFG2_AWC_WBW_AWPWOT_OVWD_MASK 0x800
#define PDMA0_QM_GWBW_CFG2_AWC_HBW_AWCACHE_OVWD_SHIFT 12
#define PDMA0_QM_GWBW_CFG2_AWC_HBW_AWCACHE_OVWD_MASK 0x1000
#define PDMA0_QM_GWBW_CFG2_AWC_HBW_AWCACHE_OVWD_SHIFT 13
#define PDMA0_QM_GWBW_CFG2_AWC_HBW_AWCACHE_OVWD_MASK 0x2000
#define PDMA0_QM_GWBW_CFG2_AWC_WBW_AWCACHE_OVWD_SHIFT 14
#define PDMA0_QM_GWBW_CFG2_AWC_WBW_AWCACHE_OVWD_MASK 0x4000
#define PDMA0_QM_GWBW_CFG2_AWC_WBW_AWCACHE_OVWD_SHIFT 15
#define PDMA0_QM_GWBW_CFG2_AWC_WBW_AWCACHE_OVWD_MASK 0x8000
#define PDMA0_QM_GWBW_CFG2_AWC_WBW_BUSEW_OVWD_SHIFT 16
#define PDMA0_QM_GWBW_CFG2_AWC_WBW_BUSEW_OVWD_MASK 0x10000

/* PDMA0_QM_GWBW_EWW_CFG */
#define PDMA0_QM_GWBW_EWW_CFG_PQF_EWW_MSG_EN_SHIFT 0
#define PDMA0_QM_GWBW_EWW_CFG_PQF_EWW_MSG_EN_MASK 0xF
#define PDMA0_QM_GWBW_EWW_CFG_CQF_EWW_MSG_EN_SHIFT 4
#define PDMA0_QM_GWBW_EWW_CFG_CQF_EWW_MSG_EN_MASK 0x1F0
#define PDMA0_QM_GWBW_EWW_CFG_CP_EWW_MSG_EN_SHIFT 9
#define PDMA0_QM_GWBW_EWW_CFG_CP_EWW_MSG_EN_MASK 0x3E00
#define PDMA0_QM_GWBW_EWW_CFG_PQF_STOP_ON_EWW_SHIFT 16
#define PDMA0_QM_GWBW_EWW_CFG_PQF_STOP_ON_EWW_MASK 0xF0000
#define PDMA0_QM_GWBW_EWW_CFG_CQF_STOP_ON_EWW_SHIFT 20
#define PDMA0_QM_GWBW_EWW_CFG_CQF_STOP_ON_EWW_MASK 0x1F00000
#define PDMA0_QM_GWBW_EWW_CFG_CP_STOP_ON_EWW_SHIFT 25
#define PDMA0_QM_GWBW_EWW_CFG_CP_STOP_ON_EWW_MASK 0x3E000000
#define PDMA0_QM_GWBW_EWW_CFG_AWB_STOP_ON_EWW_SHIFT 31
#define PDMA0_QM_GWBW_EWW_CFG_AWB_STOP_ON_EWW_MASK 0x80000000

/* PDMA0_QM_GWBW_EWW_CFG1 */
#define PDMA0_QM_GWBW_EWW_CFG1_CQF_EWW_MSG_EN_SHIFT 0
#define PDMA0_QM_GWBW_EWW_CFG1_CQF_EWW_MSG_EN_MASK 0x1
#define PDMA0_QM_GWBW_EWW_CFG1_CQF_STOP_ON_EWW_SHIFT 1
#define PDMA0_QM_GWBW_EWW_CFG1_CQF_STOP_ON_EWW_MASK 0x2
#define PDMA0_QM_GWBW_EWW_CFG1_AWC_STOP_ON_EWW_SHIFT 2
#define PDMA0_QM_GWBW_EWW_CFG1_AWC_STOP_ON_EWW_MASK 0x4

/* PDMA0_QM_GWBW_EWW_AWC_HAWT_EN */
#define PDMA0_QM_GWBW_EWW_AWC_HAWT_EN_EWW_IND_SHIFT 0
#define PDMA0_QM_GWBW_EWW_AWC_HAWT_EN_EWW_IND_MASK 0xFFFFFF

/* PDMA0_QM_GWBW_AXCACHE */
#define PDMA0_QM_GWBW_AXCACHE_HBW_AW_SHIFT 0
#define PDMA0_QM_GWBW_AXCACHE_HBW_AW_MASK 0xF
#define PDMA0_QM_GWBW_AXCACHE_HBW_AW_SHIFT 16
#define PDMA0_QM_GWBW_AXCACHE_HBW_AW_MASK 0xF0000
#define PDMA0_QM_GWBW_AXCACHE_WBW_AW_SHIFT 20
#define PDMA0_QM_GWBW_AXCACHE_WBW_AW_MASK 0xF00000
#define PDMA0_QM_GWBW_AXCACHE_WBW_AW_SHIFT 24
#define PDMA0_QM_GWBW_AXCACHE_WBW_AW_MASK 0xF000000

/* PDMA0_QM_GWBW_STS0 */
#define PDMA0_QM_GWBW_STS0_PQF_IDWE_SHIFT 0
#define PDMA0_QM_GWBW_STS0_PQF_IDWE_MASK 0xF
#define PDMA0_QM_GWBW_STS0_CQF_IDWE_SHIFT 4
#define PDMA0_QM_GWBW_STS0_CQF_IDWE_MASK 0x1F0
#define PDMA0_QM_GWBW_STS0_CP_IDWE_SHIFT 9
#define PDMA0_QM_GWBW_STS0_CP_IDWE_MASK 0x3E00
#define PDMA0_QM_GWBW_STS0_PQF_IS_STOP_SHIFT 16
#define PDMA0_QM_GWBW_STS0_PQF_IS_STOP_MASK 0xF0000
#define PDMA0_QM_GWBW_STS0_CQF_IS_STOP_SHIFT 20
#define PDMA0_QM_GWBW_STS0_CQF_IS_STOP_MASK 0x1F00000
#define PDMA0_QM_GWBW_STS0_CP_IS_STOP_SHIFT 25
#define PDMA0_QM_GWBW_STS0_CP_IS_STOP_MASK 0x3E000000
#define PDMA0_QM_GWBW_STS0_AWB_IS_STOP_SHIFT 31
#define PDMA0_QM_GWBW_STS0_AWB_IS_STOP_MASK 0x80000000

/* PDMA0_QM_GWBW_STS1 */
#define PDMA0_QM_GWBW_STS1_AWC_CQF_IDWE_SHIFT 0
#define PDMA0_QM_GWBW_STS1_AWC_CQF_IDWE_MASK 0x1
#define PDMA0_QM_GWBW_STS1_AWC_CQF_IS_STOP_SHIFT 1
#define PDMA0_QM_GWBW_STS1_AWC_CQF_IS_STOP_MASK 0x2

/* PDMA0_QM_GWBW_EWW_STS */
#define PDMA0_QM_GWBW_EWW_STS_PQF_WD_EWW_SHIFT 0
#define PDMA0_QM_GWBW_EWW_STS_PQF_WD_EWW_MASK 0x1
#define PDMA0_QM_GWBW_EWW_STS_CQF_WD_EWW_SHIFT 1
#define PDMA0_QM_GWBW_EWW_STS_CQF_WD_EWW_MASK 0x2
#define PDMA0_QM_GWBW_EWW_STS_CP_WD_EWW_SHIFT 2
#define PDMA0_QM_GWBW_EWW_STS_CP_WD_EWW_MASK 0x4
#define PDMA0_QM_GWBW_EWW_STS_CP_UNDEF_CMD_EWW_SHIFT 3
#define PDMA0_QM_GWBW_EWW_STS_CP_UNDEF_CMD_EWW_MASK 0x8
#define PDMA0_QM_GWBW_EWW_STS_CP_STOP_OP_SHIFT 4
#define PDMA0_QM_GWBW_EWW_STS_CP_STOP_OP_MASK 0x10
#define PDMA0_QM_GWBW_EWW_STS_CP_MSG_WW_EWW_SHIFT 5
#define PDMA0_QM_GWBW_EWW_STS_CP_MSG_WW_EWW_MASK 0x20
#define PDMA0_QM_GWBW_EWW_STS_CP_WWEG_EWW_SHIFT 6
#define PDMA0_QM_GWBW_EWW_STS_CP_WWEG_EWW_MASK 0x40
#define PDMA0_QM_GWBW_EWW_STS_CP_FENCE0_OVF_EWW_SHIFT 8
#define PDMA0_QM_GWBW_EWW_STS_CP_FENCE0_OVF_EWW_MASK 0x100
#define PDMA0_QM_GWBW_EWW_STS_CP_FENCE1_OVF_EWW_SHIFT 9
#define PDMA0_QM_GWBW_EWW_STS_CP_FENCE1_OVF_EWW_MASK 0x200
#define PDMA0_QM_GWBW_EWW_STS_CP_FENCE2_OVF_EWW_SHIFT 10
#define PDMA0_QM_GWBW_EWW_STS_CP_FENCE2_OVF_EWW_MASK 0x400
#define PDMA0_QM_GWBW_EWW_STS_CP_FENCE3_OVF_EWW_SHIFT 11
#define PDMA0_QM_GWBW_EWW_STS_CP_FENCE3_OVF_EWW_MASK 0x800
#define PDMA0_QM_GWBW_EWW_STS_CP_FENCE0_UDF_EWW_SHIFT 12
#define PDMA0_QM_GWBW_EWW_STS_CP_FENCE0_UDF_EWW_MASK 0x1000
#define PDMA0_QM_GWBW_EWW_STS_CP_FENCE1_UDF_EWW_SHIFT 13
#define PDMA0_QM_GWBW_EWW_STS_CP_FENCE1_UDF_EWW_MASK 0x2000
#define PDMA0_QM_GWBW_EWW_STS_CP_FENCE2_UDF_EWW_SHIFT 14
#define PDMA0_QM_GWBW_EWW_STS_CP_FENCE2_UDF_EWW_MASK 0x4000
#define PDMA0_QM_GWBW_EWW_STS_CP_FENCE3_UDF_EWW_SHIFT 15
#define PDMA0_QM_GWBW_EWW_STS_CP_FENCE3_UDF_EWW_MASK 0x8000
#define PDMA0_QM_GWBW_EWW_STS_CPDMA_UP_OVF_EWW_SHIFT 16
#define PDMA0_QM_GWBW_EWW_STS_CPDMA_UP_OVF_EWW_MASK 0x10000
#define PDMA0_QM_GWBW_EWW_STS_PQC_W2H_EWW_SHIFT 17
#define PDMA0_QM_GWBW_EWW_STS_PQC_W2H_EWW_MASK 0x20000
#define PDMA0_QM_GWBW_EWW_STS_WSVD_18_24_SHIFT 18
#define PDMA0_QM_GWBW_EWW_STS_WSVD_18_24_MASK 0x1FC0000

/* PDMA0_QM_GWBW_EWW_STS_4 */
#define PDMA0_QM_GWBW_EWW_STS_4_WSVD0_SHIFT 0
#define PDMA0_QM_GWBW_EWW_STS_4_WSVD0_MASK 0x1
#define PDMA0_QM_GWBW_EWW_STS_4_CQF_WD_EWW_SHIFT 1
#define PDMA0_QM_GWBW_EWW_STS_4_CQF_WD_EWW_MASK 0x2
#define PDMA0_QM_GWBW_EWW_STS_4_CP_WD_EWW_SHIFT 2
#define PDMA0_QM_GWBW_EWW_STS_4_CP_WD_EWW_MASK 0x4
#define PDMA0_QM_GWBW_EWW_STS_4_CP_UNDEF_CMD_EWW_SHIFT 3
#define PDMA0_QM_GWBW_EWW_STS_4_CP_UNDEF_CMD_EWW_MASK 0x8
#define PDMA0_QM_GWBW_EWW_STS_4_CP_STOP_OP_SHIFT 4
#define PDMA0_QM_GWBW_EWW_STS_4_CP_STOP_OP_MASK 0x10
#define PDMA0_QM_GWBW_EWW_STS_4_CP_MSG_WW_EWW_SHIFT 5
#define PDMA0_QM_GWBW_EWW_STS_4_CP_MSG_WW_EWW_MASK 0x20
#define PDMA0_QM_GWBW_EWW_STS_4_CP_WWEG_EWW_SHIFT 6
#define PDMA0_QM_GWBW_EWW_STS_4_CP_WWEG_EWW_MASK 0x40
#define PDMA0_QM_GWBW_EWW_STS_4_CP_FENCE0_OVF_EWW_SHIFT 8
#define PDMA0_QM_GWBW_EWW_STS_4_CP_FENCE0_OVF_EWW_MASK 0x100
#define PDMA0_QM_GWBW_EWW_STS_4_CP_FENCE1_OVF_EWW_SHIFT 9
#define PDMA0_QM_GWBW_EWW_STS_4_CP_FENCE1_OVF_EWW_MASK 0x200
#define PDMA0_QM_GWBW_EWW_STS_4_CP_FENCE2_OVF_EWW_SHIFT 10
#define PDMA0_QM_GWBW_EWW_STS_4_CP_FENCE2_OVF_EWW_MASK 0x400
#define PDMA0_QM_GWBW_EWW_STS_4_CP_FENCE3_OVF_EWW_SHIFT 11
#define PDMA0_QM_GWBW_EWW_STS_4_CP_FENCE3_OVF_EWW_MASK 0x800
#define PDMA0_QM_GWBW_EWW_STS_4_CP_FENCE0_UDF_EWW_SHIFT 12
#define PDMA0_QM_GWBW_EWW_STS_4_CP_FENCE0_UDF_EWW_MASK 0x1000
#define PDMA0_QM_GWBW_EWW_STS_4_CP_FENCE1_UDF_EWW_SHIFT 13
#define PDMA0_QM_GWBW_EWW_STS_4_CP_FENCE1_UDF_EWW_MASK 0x2000
#define PDMA0_QM_GWBW_EWW_STS_4_CP_FENCE2_UDF_EWW_SHIFT 14
#define PDMA0_QM_GWBW_EWW_STS_4_CP_FENCE2_UDF_EWW_MASK 0x4000
#define PDMA0_QM_GWBW_EWW_STS_4_CP_FENCE3_UDF_EWW_SHIFT 15
#define PDMA0_QM_GWBW_EWW_STS_4_CP_FENCE3_UDF_EWW_MASK 0x8000
#define PDMA0_QM_GWBW_EWW_STS_4_CPDMA_UP_OVF_EWW_SHIFT 16
#define PDMA0_QM_GWBW_EWW_STS_4_CPDMA_UP_OVF_EWW_MASK 0x10000
#define PDMA0_QM_GWBW_EWW_STS_4_WSVD17_SHIFT 17
#define PDMA0_QM_GWBW_EWW_STS_4_WSVD17_MASK 0x20000
#define PDMA0_QM_GWBW_EWW_STS_4_CQ_WW_IFIFO_CI_EWW_SHIFT 18
#define PDMA0_QM_GWBW_EWW_STS_4_CQ_WW_IFIFO_CI_EWW_MASK 0x40000
#define PDMA0_QM_GWBW_EWW_STS_4_CQ_WW_CTW_CI_EWW_SHIFT 19
#define PDMA0_QM_GWBW_EWW_STS_4_CQ_WW_CTW_CI_EWW_MASK 0x80000
#define PDMA0_QM_GWBW_EWW_STS_4_AWC_CQF_WD_EWW_SHIFT 20
#define PDMA0_QM_GWBW_EWW_STS_4_AWC_CQF_WD_EWW_MASK 0x100000
#define PDMA0_QM_GWBW_EWW_STS_4_AWC_CQ_WW_IFIFO_CI_EWW_SHIFT 21
#define PDMA0_QM_GWBW_EWW_STS_4_AWC_CQ_WW_IFIFO_CI_EWW_MASK 0x200000
#define PDMA0_QM_GWBW_EWW_STS_4_AWC_CQ_WW_CTW_CI_EWW_SHIFT 22
#define PDMA0_QM_GWBW_EWW_STS_4_AWC_CQ_WW_CTW_CI_EWW_MASK 0x400000
#define PDMA0_QM_GWBW_EWW_STS_4_AWC_AXI_EWW_SHIFT 23
#define PDMA0_QM_GWBW_EWW_STS_4_AWC_AXI_EWW_MASK 0x800000
#define PDMA0_QM_GWBW_EWW_STS_4_CP_SWITCH_WDT_EWW_SHIFT 24
#define PDMA0_QM_GWBW_EWW_STS_4_CP_SWITCH_WDT_EWW_MASK 0x1000000

/* PDMA0_QM_GWBW_EWW_MSG_EN */
#define PDMA0_QM_GWBW_EWW_MSG_EN_PQF_WD_EWW_SHIFT 0
#define PDMA0_QM_GWBW_EWW_MSG_EN_PQF_WD_EWW_MASK 0x1
#define PDMA0_QM_GWBW_EWW_MSG_EN_CQF_WD_EWW_SHIFT 1
#define PDMA0_QM_GWBW_EWW_MSG_EN_CQF_WD_EWW_MASK 0x2
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_WD_EWW_SHIFT 2
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_WD_EWW_MASK 0x4
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_UNDEF_CMD_EWW_SHIFT 3
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_UNDEF_CMD_EWW_MASK 0x8
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_STOP_OP_SHIFT 4
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_STOP_OP_MASK 0x10
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_MSG_WW_EWW_SHIFT 5
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_MSG_WW_EWW_MASK 0x20
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_WWEG_EWW_SHIFT 6
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_WWEG_EWW_MASK 0x40
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_FENCE0_OVF_EWW_SHIFT 8
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_FENCE0_OVF_EWW_MASK 0x100
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_FENCE1_OVF_EWW_SHIFT 9
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_FENCE1_OVF_EWW_MASK 0x200
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_FENCE2_OVF_EWW_SHIFT 10
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_FENCE2_OVF_EWW_MASK 0x400
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_FENCE3_OVF_EWW_SHIFT 11
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_FENCE3_OVF_EWW_MASK 0x800
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_FENCE0_UDF_EWW_SHIFT 12
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_FENCE0_UDF_EWW_MASK 0x1000
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_FENCE1_UDF_EWW_SHIFT 13
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_FENCE1_UDF_EWW_MASK 0x2000
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_FENCE2_UDF_EWW_SHIFT 14
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_FENCE2_UDF_EWW_MASK 0x4000
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_FENCE3_UDF_EWW_SHIFT 15
#define PDMA0_QM_GWBW_EWW_MSG_EN_CP_FENCE3_UDF_EWW_MASK 0x8000
#define PDMA0_QM_GWBW_EWW_MSG_EN_CPDMA_UP_OVF_EWW_SHIFT 16
#define PDMA0_QM_GWBW_EWW_MSG_EN_CPDMA_UP_OVF_EWW_MASK 0x10000
#define PDMA0_QM_GWBW_EWW_MSG_EN_PQC_W2H_EWW_SHIFT 17
#define PDMA0_QM_GWBW_EWW_MSG_EN_PQC_W2H_EWW_MASK 0x20000
#define PDMA0_QM_GWBW_EWW_MSG_EN_WSVD_18_24_SHIFT 18
#define PDMA0_QM_GWBW_EWW_MSG_EN_WSVD_18_24_MASK 0x1FC0000

/* PDMA0_QM_GWBW_EWW_MSG_EN_4 */
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_WSVD0_SHIFT 0
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_WSVD0_MASK 0x1
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CQF_WD_EWW_SHIFT 1
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CQF_WD_EWW_MASK 0x2
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_WD_EWW_SHIFT 2
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_WD_EWW_MASK 0x4
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_UNDEF_CMD_EWW_SHIFT 3
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_UNDEF_CMD_EWW_MASK 0x8
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_STOP_OP_SHIFT 4
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_STOP_OP_MASK 0x10
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_MSG_WW_EWW_SHIFT 5
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_MSG_WW_EWW_MASK 0x20
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_WWEG_EWW_SHIFT 6
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_WWEG_EWW_MASK 0x40
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_FENCE0_OVF_EWW_SHIFT 8
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_FENCE0_OVF_EWW_MASK 0x100
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_FENCE1_OVF_EWW_SHIFT 9
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_FENCE1_OVF_EWW_MASK 0x200
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_FENCE2_OVF_EWW_SHIFT 10
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_FENCE2_OVF_EWW_MASK 0x400
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_FENCE3_OVF_EWW_SHIFT 11
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_FENCE3_OVF_EWW_MASK 0x800
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_FENCE0_UDF_EWW_SHIFT 12
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_FENCE0_UDF_EWW_MASK 0x1000
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_FENCE1_UDF_EWW_SHIFT 13
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_FENCE1_UDF_EWW_MASK 0x2000
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_FENCE2_UDF_EWW_SHIFT 14
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_FENCE2_UDF_EWW_MASK 0x4000
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_FENCE3_UDF_EWW_SHIFT 15
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_FENCE3_UDF_EWW_MASK 0x8000
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CPDMA_UP_OVF_EWW_SHIFT 16
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CPDMA_UP_OVF_EWW_MASK 0x10000
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_WSVD17_SHIFT 17
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_WSVD17_MASK 0x20000
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CQ_WW_IFIFO_CI_EWW_SHIFT 18
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CQ_WW_IFIFO_CI_EWW_MASK 0x40000
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CQ_WW_CTW_CI_EWW_SHIFT 19
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CQ_WW_CTW_CI_EWW_MASK 0x80000
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_AWC_CQF_WD_EWW_SHIFT 20
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_AWC_CQF_WD_EWW_MASK 0x100000
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_AWC_CQ_WW_IFIFO_CI_EWW_SHIFT 21
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_AWC_CQ_WW_IFIFO_CI_EWW_MASK 0x200000
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_AWC_CQ_WW_CTW_CI_EWW_SHIFT 22
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_AWC_CQ_WW_CTW_CI_EWW_MASK 0x400000
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_AWC_AXI_EWW_SHIFT 23
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_AWC_AXI_EWW_MASK 0x800000
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_SWITCH_WDT_EWW_SHIFT 24
#define PDMA0_QM_GWBW_EWW_MSG_EN_4_CP_SWITCH_WDT_EWW_MASK 0x1000000

/* PDMA0_QM_GWBW_PWOT */
#define PDMA0_QM_GWBW_PWOT_PQF_SHIFT 0
#define PDMA0_QM_GWBW_PWOT_PQF_MASK 0xF
#define PDMA0_QM_GWBW_PWOT_CQF_SHIFT 4
#define PDMA0_QM_GWBW_PWOT_CQF_MASK 0x1F0
#define PDMA0_QM_GWBW_PWOT_CP_SHIFT 9
#define PDMA0_QM_GWBW_PWOT_CP_MASK 0x3E00
#define PDMA0_QM_GWBW_PWOT_EWW_SHIFT 14
#define PDMA0_QM_GWBW_PWOT_EWW_MASK 0x4000
#define PDMA0_QM_GWBW_PWOT_AWB_SHIFT 15
#define PDMA0_QM_GWBW_PWOT_AWB_MASK 0x8000
#define PDMA0_QM_GWBW_PWOT_PQC_SHIFT 16
#define PDMA0_QM_GWBW_PWOT_PQC_MASK 0x10000
#define PDMA0_QM_GWBW_PWOT_CQ_IFIFO_MSG_SHIFT 17
#define PDMA0_QM_GWBW_PWOT_CQ_IFIFO_MSG_MASK 0x20000
#define PDMA0_QM_GWBW_PWOT_AWC_CQ_IFIFO_MSG_SHIFT 18
#define PDMA0_QM_GWBW_PWOT_AWC_CQ_IFIFO_MSG_MASK 0x40000
#define PDMA0_QM_GWBW_PWOT_CQ_CTW_MSG_SHIFT 19
#define PDMA0_QM_GWBW_PWOT_CQ_CTW_MSG_MASK 0x80000
#define PDMA0_QM_GWBW_PWOT_AWC_CQ_CTW_MSG_SHIFT 20
#define PDMA0_QM_GWBW_PWOT_AWC_CQ_CTW_MSG_MASK 0x100000
#define PDMA0_QM_GWBW_PWOT_CP_WW_AWC_SHIFT 21
#define PDMA0_QM_GWBW_PWOT_CP_WW_AWC_MASK 0x200000
#define PDMA0_QM_GWBW_PWOT_AWC_CQF_SHIFT 22
#define PDMA0_QM_GWBW_PWOT_AWC_CQF_MASK 0x400000
#define PDMA0_QM_GWBW_PWOT_AWC_COWE_SHIFT 23
#define PDMA0_QM_GWBW_PWOT_AWC_COWE_MASK 0x800000

/* PDMA0_QM_PQ_BASE_WO */
#define PDMA0_QM_PQ_BASE_WO_VAW_SHIFT 0
#define PDMA0_QM_PQ_BASE_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_PQ_BASE_HI */
#define PDMA0_QM_PQ_BASE_HI_VAW_SHIFT 0
#define PDMA0_QM_PQ_BASE_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_PQ_SIZE */
#define PDMA0_QM_PQ_SIZE_VAW_SHIFT 0
#define PDMA0_QM_PQ_SIZE_VAW_MASK 0x1F

/* PDMA0_QM_PQ_PI */
#define PDMA0_QM_PQ_PI_VAW_SHIFT 0
#define PDMA0_QM_PQ_PI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_PQ_CI */
#define PDMA0_QM_PQ_CI_VAW_SHIFT 0
#define PDMA0_QM_PQ_CI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_PQ_CFG0 */
#define PDMA0_QM_PQ_CFG0_FOWCE_STAWW_SHIFT 0
#define PDMA0_QM_PQ_CFG0_FOWCE_STAWW_MASK 0x1

/* PDMA0_QM_PQ_CFG1 */
#define PDMA0_QM_PQ_CFG1_CWEDIT_WIM_SHIFT 0
#define PDMA0_QM_PQ_CFG1_CWEDIT_WIM_MASK 0xFF
#define PDMA0_QM_PQ_CFG1_MAX_INFWIGHT_SHIFT 16
#define PDMA0_QM_PQ_CFG1_MAX_INFWIGHT_MASK 0xFF0000

/* PDMA0_QM_PQ_STS0 */
#define PDMA0_QM_PQ_STS0_CWEDIT_CNT_SHIFT 0
#define PDMA0_QM_PQ_STS0_CWEDIT_CNT_MASK 0xFF
#define PDMA0_QM_PQ_STS0_FWEE_CNT_SHIFT 8
#define PDMA0_QM_PQ_STS0_FWEE_CNT_MASK 0xFF00
#define PDMA0_QM_PQ_STS0_INFWIGHT_CNT_SHIFT 16
#define PDMA0_QM_PQ_STS0_INFWIGHT_CNT_MASK 0xFF0000

/* PDMA0_QM_PQ_STS1 */
#define PDMA0_QM_PQ_STS1_BUF_EMPTY_SHIFT 0
#define PDMA0_QM_PQ_STS1_BUF_EMPTY_MASK 0x1
#define PDMA0_QM_PQ_STS1_BUSY_SHIFT 1
#define PDMA0_QM_PQ_STS1_BUSY_MASK 0x2

/* PDMA0_QM_CQ_CFG0 */
#define PDMA0_QM_CQ_CFG0_IF_B2B_EN_SHIFT 0
#define PDMA0_QM_CQ_CFG0_IF_B2B_EN_MASK 0x1
#define PDMA0_QM_CQ_CFG0_IF_MSG_EN_SHIFT 1
#define PDMA0_QM_CQ_CFG0_IF_MSG_EN_MASK 0x2
#define PDMA0_QM_CQ_CFG0_CTW_MSG_EN_SHIFT 2
#define PDMA0_QM_CQ_CFG0_CTW_MSG_EN_MASK 0x4

/* PDMA0_QM_CQ_STS0 */
#define PDMA0_QM_CQ_STS0_CWEDIT_CNT_SHIFT 0
#define PDMA0_QM_CQ_STS0_CWEDIT_CNT_MASK 0xFF
#define PDMA0_QM_CQ_STS0_FWEE_CNT_SHIFT 8
#define PDMA0_QM_CQ_STS0_FWEE_CNT_MASK 0xFF00
#define PDMA0_QM_CQ_STS0_INFWIGHT_CNT_SHIFT 16
#define PDMA0_QM_CQ_STS0_INFWIGHT_CNT_MASK 0xFF0000

/* PDMA0_QM_CQ_CFG1 */
#define PDMA0_QM_CQ_CFG1_CWEDIT_WIM_SHIFT 0
#define PDMA0_QM_CQ_CFG1_CWEDIT_WIM_MASK 0xFF
#define PDMA0_QM_CQ_CFG1_MAX_INFWIGHT_SHIFT 16
#define PDMA0_QM_CQ_CFG1_MAX_INFWIGHT_MASK 0xFF0000

/* PDMA0_QM_CQ_STS1 */
#define PDMA0_QM_CQ_STS1_BUF_EMPTY_SHIFT 0
#define PDMA0_QM_CQ_STS1_BUF_EMPTY_MASK 0x1
#define PDMA0_QM_CQ_STS1_BUSY_SHIFT 1
#define PDMA0_QM_CQ_STS1_BUSY_MASK 0x2

/* PDMA0_QM_CQ_PTW_WO_0 */
#define PDMA0_QM_CQ_PTW_WO_0_VAW_SHIFT 0
#define PDMA0_QM_CQ_PTW_WO_0_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_PTW_HI_0 */
#define PDMA0_QM_CQ_PTW_HI_0_VAW_SHIFT 0
#define PDMA0_QM_CQ_PTW_HI_0_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_TSIZE_0 */
#define PDMA0_QM_CQ_TSIZE_0_VAW_SHIFT 0
#define PDMA0_QM_CQ_TSIZE_0_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_CTW_0 */
#define PDMA0_QM_CQ_CTW_0_UP_SHIFT 28
#define PDMA0_QM_CQ_CTW_0_UP_MASK 0xF0000000

/* PDMA0_QM_CQ_PTW_WO_1 */
#define PDMA0_QM_CQ_PTW_WO_1_VAW_SHIFT 0
#define PDMA0_QM_CQ_PTW_WO_1_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_PTW_HI_1 */
#define PDMA0_QM_CQ_PTW_HI_1_VAW_SHIFT 0
#define PDMA0_QM_CQ_PTW_HI_1_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_TSIZE_1 */
#define PDMA0_QM_CQ_TSIZE_1_VAW_SHIFT 0
#define PDMA0_QM_CQ_TSIZE_1_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_CTW_1 */
#define PDMA0_QM_CQ_CTW_1_UP_SHIFT 28
#define PDMA0_QM_CQ_CTW_1_UP_MASK 0xF0000000

/* PDMA0_QM_CQ_PTW_WO_2 */
#define PDMA0_QM_CQ_PTW_WO_2_VAW_SHIFT 0
#define PDMA0_QM_CQ_PTW_WO_2_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_PTW_HI_2 */
#define PDMA0_QM_CQ_PTW_HI_2_VAW_SHIFT 0
#define PDMA0_QM_CQ_PTW_HI_2_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_TSIZE_2 */
#define PDMA0_QM_CQ_TSIZE_2_VAW_SHIFT 0
#define PDMA0_QM_CQ_TSIZE_2_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_CTW_2 */
#define PDMA0_QM_CQ_CTW_2_UP_SHIFT 28
#define PDMA0_QM_CQ_CTW_2_UP_MASK 0xF0000000

/* PDMA0_QM_CQ_PTW_WO_3 */
#define PDMA0_QM_CQ_PTW_WO_3_VAW_SHIFT 0
#define PDMA0_QM_CQ_PTW_WO_3_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_PTW_HI_3 */
#define PDMA0_QM_CQ_PTW_HI_3_VAW_SHIFT 0
#define PDMA0_QM_CQ_PTW_HI_3_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_TSIZE_3 */
#define PDMA0_QM_CQ_TSIZE_3_VAW_SHIFT 0
#define PDMA0_QM_CQ_TSIZE_3_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_CTW_3 */
#define PDMA0_QM_CQ_CTW_3_UP_SHIFT 28
#define PDMA0_QM_CQ_CTW_3_UP_MASK 0xF0000000

/* PDMA0_QM_CQ_PTW_WO_4 */
#define PDMA0_QM_CQ_PTW_WO_4_VAW_SHIFT 0
#define PDMA0_QM_CQ_PTW_WO_4_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_PTW_HI_4 */
#define PDMA0_QM_CQ_PTW_HI_4_VAW_SHIFT 0
#define PDMA0_QM_CQ_PTW_HI_4_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_TSIZE_4 */
#define PDMA0_QM_CQ_TSIZE_4_VAW_SHIFT 0
#define PDMA0_QM_CQ_TSIZE_4_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_CTW_4 */
#define PDMA0_QM_CQ_CTW_4_UP_SHIFT 28
#define PDMA0_QM_CQ_CTW_4_UP_MASK 0xF0000000

/* PDMA0_QM_CQ_TSIZE_STS */
#define PDMA0_QM_CQ_TSIZE_STS_VAW_SHIFT 0
#define PDMA0_QM_CQ_TSIZE_STS_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_PTW_WO_STS */
#define PDMA0_QM_CQ_PTW_WO_STS_VAW_SHIFT 0
#define PDMA0_QM_CQ_PTW_WO_STS_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_PTW_HI_STS */
#define PDMA0_QM_CQ_PTW_HI_STS_VAW_SHIFT 0
#define PDMA0_QM_CQ_PTW_HI_STS_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_IFIFO_STS */
#define PDMA0_QM_CQ_IFIFO_STS_CNT_SHIFT 0
#define PDMA0_QM_CQ_IFIFO_STS_CNT_MASK 0x7
#define PDMA0_QM_CQ_IFIFO_STS_WDY_SHIFT 4
#define PDMA0_QM_CQ_IFIFO_STS_WDY_MASK 0x10
#define PDMA0_QM_CQ_IFIFO_STS_CTW_STAWW_SHIFT 8
#define PDMA0_QM_CQ_IFIFO_STS_CTW_STAWW_MASK 0x100

/* PDMA0_QM_CP_MSG_BASE0_ADDW_WO */
#define PDMA0_QM_CP_MSG_BASE0_ADDW_WO_VAW_SHIFT 0
#define PDMA0_QM_CP_MSG_BASE0_ADDW_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CP_MSG_BASE0_ADDW_HI */
#define PDMA0_QM_CP_MSG_BASE0_ADDW_HI_VAW_SHIFT 0
#define PDMA0_QM_CP_MSG_BASE0_ADDW_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CP_MSG_BASE1_ADDW_WO */
#define PDMA0_QM_CP_MSG_BASE1_ADDW_WO_VAW_SHIFT 0
#define PDMA0_QM_CP_MSG_BASE1_ADDW_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CP_MSG_BASE1_ADDW_HI */
#define PDMA0_QM_CP_MSG_BASE1_ADDW_HI_VAW_SHIFT 0
#define PDMA0_QM_CP_MSG_BASE1_ADDW_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CP_MSG_BASE2_ADDW_WO */
#define PDMA0_QM_CP_MSG_BASE2_ADDW_WO_VAW_SHIFT 0
#define PDMA0_QM_CP_MSG_BASE2_ADDW_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CP_MSG_BASE2_ADDW_HI */
#define PDMA0_QM_CP_MSG_BASE2_ADDW_HI_VAW_SHIFT 0
#define PDMA0_QM_CP_MSG_BASE2_ADDW_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CP_MSG_BASE3_ADDW_WO */
#define PDMA0_QM_CP_MSG_BASE3_ADDW_WO_VAW_SHIFT 0
#define PDMA0_QM_CP_MSG_BASE3_ADDW_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CP_MSG_BASE3_ADDW_HI */
#define PDMA0_QM_CP_MSG_BASE3_ADDW_HI_VAW_SHIFT 0
#define PDMA0_QM_CP_MSG_BASE3_ADDW_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CP_FENCE0_WDATA */
#define PDMA0_QM_CP_FENCE0_WDATA_INC_VAW_SHIFT 0
#define PDMA0_QM_CP_FENCE0_WDATA_INC_VAW_MASK 0xF

/* PDMA0_QM_CP_FENCE1_WDATA */
#define PDMA0_QM_CP_FENCE1_WDATA_INC_VAW_SHIFT 0
#define PDMA0_QM_CP_FENCE1_WDATA_INC_VAW_MASK 0xF

/* PDMA0_QM_CP_FENCE2_WDATA */
#define PDMA0_QM_CP_FENCE2_WDATA_INC_VAW_SHIFT 0
#define PDMA0_QM_CP_FENCE2_WDATA_INC_VAW_MASK 0xF

/* PDMA0_QM_CP_FENCE3_WDATA */
#define PDMA0_QM_CP_FENCE3_WDATA_INC_VAW_SHIFT 0
#define PDMA0_QM_CP_FENCE3_WDATA_INC_VAW_MASK 0xF

/* PDMA0_QM_CP_FENCE0_CNT */
#define PDMA0_QM_CP_FENCE0_CNT_VAW_SHIFT 0
#define PDMA0_QM_CP_FENCE0_CNT_VAW_MASK 0x3FFF

/* PDMA0_QM_CP_FENCE1_CNT */
#define PDMA0_QM_CP_FENCE1_CNT_VAW_SHIFT 0
#define PDMA0_QM_CP_FENCE1_CNT_VAW_MASK 0x3FFF

/* PDMA0_QM_CP_FENCE2_CNT */
#define PDMA0_QM_CP_FENCE2_CNT_VAW_SHIFT 0
#define PDMA0_QM_CP_FENCE2_CNT_VAW_MASK 0x3FFF

/* PDMA0_QM_CP_FENCE3_CNT */
#define PDMA0_QM_CP_FENCE3_CNT_VAW_SHIFT 0
#define PDMA0_QM_CP_FENCE3_CNT_VAW_MASK 0x3FFF

/* PDMA0_QM_CP_BAWWIEW_CFG */
#define PDMA0_QM_CP_BAWWIEW_CFG_EBGUAWD_SHIFT 0
#define PDMA0_QM_CP_BAWWIEW_CFG_EBGUAWD_MASK 0xFFF
#define PDMA0_QM_CP_BAWWIEW_CFG_WBGUAWD_SHIFT 16
#define PDMA0_QM_CP_BAWWIEW_CFG_WBGUAWD_MASK 0xF0000

/* PDMA0_QM_CP_WDMA_SWC_BASE_WO_OFFSET */
#define PDMA0_QM_CP_WDMA_SWC_BASE_WO_OFFSET_VAW_SHIFT 0
#define PDMA0_QM_CP_WDMA_SWC_BASE_WO_OFFSET_VAW_MASK 0xFFFF

/* PDMA0_QM_CP_WDMA_DST_BASE_WO_OFFSET */
#define PDMA0_QM_CP_WDMA_DST_BASE_WO_OFFSET_VAW_SHIFT 0
#define PDMA0_QM_CP_WDMA_DST_BASE_WO_OFFSET_VAW_MASK 0xFFFF

/* PDMA0_QM_CP_WDMA_TSIZE_OFFSET */
#define PDMA0_QM_CP_WDMA_TSIZE_OFFSET_VAW_SHIFT 0
#define PDMA0_QM_CP_WDMA_TSIZE_OFFSET_VAW_MASK 0xFFFF

/* PDMA0_QM_CP_CQ_PTW_WO_OFFSET_0 */
#define PDMA0_QM_CP_CQ_PTW_WO_OFFSET_0_VAW_SHIFT 0
#define PDMA0_QM_CP_CQ_PTW_WO_OFFSET_0_VAW_MASK 0xFFFF

/* PDMA0_QM_CP_CQ_PTW_WO_OFFSET_1 */
#define PDMA0_QM_CP_CQ_PTW_WO_OFFSET_1_VAW_SHIFT 0
#define PDMA0_QM_CP_CQ_PTW_WO_OFFSET_1_VAW_MASK 0xFFFF

/* PDMA0_QM_CP_CQ_PTW_WO_OFFSET_2 */
#define PDMA0_QM_CP_CQ_PTW_WO_OFFSET_2_VAW_SHIFT 0
#define PDMA0_QM_CP_CQ_PTW_WO_OFFSET_2_VAW_MASK 0xFFFF

/* PDMA0_QM_CP_CQ_PTW_WO_OFFSET_3 */
#define PDMA0_QM_CP_CQ_PTW_WO_OFFSET_3_VAW_SHIFT 0
#define PDMA0_QM_CP_CQ_PTW_WO_OFFSET_3_VAW_MASK 0xFFFF

/* PDMA0_QM_CP_CQ_PTW_WO_OFFSET_4 */
#define PDMA0_QM_CP_CQ_PTW_WO_OFFSET_4_VAW_SHIFT 0
#define PDMA0_QM_CP_CQ_PTW_WO_OFFSET_4_VAW_MASK 0xFFFF

/* PDMA0_QM_CP_STS */
#define PDMA0_QM_CP_STS_MSG_INFWIGHT_CNT_SHIFT 0
#define PDMA0_QM_CP_STS_MSG_INFWIGHT_CNT_MASK 0xFF
#define PDMA0_QM_CP_STS_EWDY_SHIFT 8
#define PDMA0_QM_CP_STS_EWDY_MASK 0x100
#define PDMA0_QM_CP_STS_SWITCH_EN_SHIFT 9
#define PDMA0_QM_CP_STS_SWITCH_EN_MASK 0x200
#define PDMA0_QM_CP_STS_MWDY_SHIFT 10
#define PDMA0_QM_CP_STS_MWDY_MASK 0x400
#define PDMA0_QM_CP_STS_SW_STOP_SHIFT 11
#define PDMA0_QM_CP_STS_SW_STOP_MASK 0x800
#define PDMA0_QM_CP_STS_FENCE_ID_SHIFT 12
#define PDMA0_QM_CP_STS_FENCE_ID_MASK 0x3000
#define PDMA0_QM_CP_STS_FENCE_IN_PWOGWESS_SHIFT 14
#define PDMA0_QM_CP_STS_FENCE_IN_PWOGWESS_MASK 0x4000
#define PDMA0_QM_CP_STS_FENCE_TAWGET_SHIFT 16
#define PDMA0_QM_CP_STS_FENCE_TAWGET_MASK 0x3FFF0000
#define PDMA0_QM_CP_STS_CUW_CQ_SHIFT 30
#define PDMA0_QM_CP_STS_CUW_CQ_MASK 0x40000000

/* PDMA0_QM_CP_CUWWENT_INST_WO */
#define PDMA0_QM_CP_CUWWENT_INST_WO_VAW_SHIFT 0
#define PDMA0_QM_CP_CUWWENT_INST_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CP_CUWWENT_INST_HI */
#define PDMA0_QM_CP_CUWWENT_INST_HI_VAW_SHIFT 0
#define PDMA0_QM_CP_CUWWENT_INST_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CP_PWED */
#define PDMA0_QM_CP_PWED_VAW_SHIFT 0
#define PDMA0_QM_CP_PWED_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CP_PWED_UPEN */
#define PDMA0_QM_CP_PWED_UPEN_VAW_SHIFT 0
#define PDMA0_QM_CP_PWED_UPEN_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CP_DBG_0 */
#define PDMA0_QM_CP_DBG_0_CS_SHIFT 0
#define PDMA0_QM_CP_DBG_0_CS_MASK 0x1F
#define PDMA0_QM_CP_DBG_0_EB_CNT_NOT_ZEWO_SHIFT 5
#define PDMA0_QM_CP_DBG_0_EB_CNT_NOT_ZEWO_MASK 0x20
#define PDMA0_QM_CP_DBG_0_BUWK_CNT_NOT_ZEWO_SHIFT 6
#define PDMA0_QM_CP_DBG_0_BUWK_CNT_NOT_ZEWO_MASK 0x40
#define PDMA0_QM_CP_DBG_0_MWEB_STAWW_SHIFT 7
#define PDMA0_QM_CP_DBG_0_MWEB_STAWW_MASK 0x80
#define PDMA0_QM_CP_DBG_0_STAWW_SHIFT 8
#define PDMA0_QM_CP_DBG_0_STAWW_MASK 0x100

/* PDMA0_QM_CP_CPDMA_UP_CWED */
#define PDMA0_QM_CP_CPDMA_UP_CWED_TH_SHIFT 0
#define PDMA0_QM_CP_CPDMA_UP_CWED_TH_MASK 0x3
#define PDMA0_QM_CP_CPDMA_UP_CWED_VAW_SHIFT 8
#define PDMA0_QM_CP_CPDMA_UP_CWED_VAW_MASK 0x300

/* PDMA0_QM_CP_IN_DATA_WO */
#define PDMA0_QM_CP_IN_DATA_WO_VAW_SHIFT 0
#define PDMA0_QM_CP_IN_DATA_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CP_IN_DATA_HI */
#define PDMA0_QM_CP_IN_DATA_HI_VAW_SHIFT 0
#define PDMA0_QM_CP_IN_DATA_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_PQC_HBW_BASE_WO */
#define PDMA0_QM_PQC_HBW_BASE_WO_VAW_SHIFT 0
#define PDMA0_QM_PQC_HBW_BASE_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_PQC_HBW_BASE_HI */
#define PDMA0_QM_PQC_HBW_BASE_HI_VAW_SHIFT 0
#define PDMA0_QM_PQC_HBW_BASE_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_PQC_SIZE */
#define PDMA0_QM_PQC_SIZE_VAW_SHIFT 0
#define PDMA0_QM_PQC_SIZE_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_PQC_PI */
#define PDMA0_QM_PQC_PI_VAW_SHIFT 0
#define PDMA0_QM_PQC_PI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_PQC_WBW_WDATA */
#define PDMA0_QM_PQC_WBW_WDATA_VAW_SHIFT 0
#define PDMA0_QM_PQC_WBW_WDATA_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_PQC_WBW_BASE_WO */
#define PDMA0_QM_PQC_WBW_BASE_WO_VAW_SHIFT 0
#define PDMA0_QM_PQC_WBW_BASE_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_PQC_WBW_BASE_HI */
#define PDMA0_QM_PQC_WBW_BASE_HI_VAW_SHIFT 0
#define PDMA0_QM_PQC_WBW_BASE_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_PQC_CFG */
#define PDMA0_QM_PQC_CFG_EN_SHIFT 0
#define PDMA0_QM_PQC_CFG_EN_MASK 0x1
#define PDMA0_QM_PQC_CFG_DIWECT_SHIFT 4
#define PDMA0_QM_PQC_CFG_DIWECT_MASK 0x10

/* PDMA0_QM_PQC_SECUWE_PUSH_IND */
#define PDMA0_QM_PQC_SECUWE_PUSH_IND_CP_NUM_SHIFT 0
#define PDMA0_QM_PQC_SECUWE_PUSH_IND_CP_NUM_MASK 0x3

/* PDMA0_QM_AWB_MASK */
#define PDMA0_QM_AWB_MASK_VAW_SHIFT 0
#define PDMA0_QM_AWB_MASK_VAW_MASK 0xF

/* PDMA0_QM_AWB_CFG_0 */
#define PDMA0_QM_AWB_CFG_0_PWIO_TYPE_SHIFT 0
#define PDMA0_QM_AWB_CFG_0_PWIO_TYPE_MASK 0x1
#define PDMA0_QM_AWB_CFG_0_IS_MASTEW_SHIFT 4
#define PDMA0_QM_AWB_CFG_0_IS_MASTEW_MASK 0x10
#define PDMA0_QM_AWB_CFG_0_EN_SHIFT 8
#define PDMA0_QM_AWB_CFG_0_EN_MASK 0x100
#define PDMA0_QM_AWB_CFG_0_MST_MSG_NOSTAWW_SHIFT 9
#define PDMA0_QM_AWB_CFG_0_MST_MSG_NOSTAWW_MASK 0x200

/* PDMA0_QM_AWB_CHOICE_Q_PUSH */
#define PDMA0_QM_AWB_CHOICE_Q_PUSH_VAW_SHIFT 0
#define PDMA0_QM_AWB_CHOICE_Q_PUSH_VAW_MASK 0x3

/* PDMA0_QM_AWB_WWW_WEIGHT */
#define PDMA0_QM_AWB_WWW_WEIGHT_VAW_SHIFT 0
#define PDMA0_QM_AWB_WWW_WEIGHT_VAW_MASK 0xFF

/* PDMA0_QM_AWB_CFG_1 */
#define PDMA0_QM_AWB_CFG_1_CWW_SHIFT 0
#define PDMA0_QM_AWB_CFG_1_CWW_MASK 0x1

/* PDMA0_QM_AWB_MST_AVAIW_CWED */
#define PDMA0_QM_AWB_MST_AVAIW_CWED_VAW_SHIFT 0
#define PDMA0_QM_AWB_MST_AVAIW_CWED_VAW_MASK 0x7F

/* PDMA0_QM_AWB_MST_CWED_INC */
#define PDMA0_QM_AWB_MST_CWED_INC_VAW_SHIFT 0
#define PDMA0_QM_AWB_MST_CWED_INC_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWB_MST_CHOICE_PUSH_OFST */
#define PDMA0_QM_AWB_MST_CHOICE_PUSH_OFST_VAW_SHIFT 0
#define PDMA0_QM_AWB_MST_CHOICE_PUSH_OFST_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWB_SWV_MASTEW_INC_CWED_OFST */
#define PDMA0_QM_AWB_SWV_MASTEW_INC_CWED_OFST_VAW_SHIFT 0
#define PDMA0_QM_AWB_SWV_MASTEW_INC_CWED_OFST_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWB_MST_SWAVE_EN */
#define PDMA0_QM_AWB_MST_SWAVE_EN_VAW_SHIFT 0
#define PDMA0_QM_AWB_MST_SWAVE_EN_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWB_MST_SWAVE_EN_1 */
#define PDMA0_QM_AWB_MST_SWAVE_EN_1_VAW_SHIFT 0
#define PDMA0_QM_AWB_MST_SWAVE_EN_1_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWB_SWV_CHOICE_WDT */
#define PDMA0_QM_AWB_SWV_CHOICE_WDT_VAW_SHIFT 0
#define PDMA0_QM_AWB_SWV_CHOICE_WDT_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWB_SWV_ID */
#define PDMA0_QM_AWB_SWV_ID_VAW_SHIFT 0
#define PDMA0_QM_AWB_SWV_ID_VAW_MASK 0x7F

/* PDMA0_QM_AWB_MST_QUIET_PEW */
#define PDMA0_QM_AWB_MST_QUIET_PEW_VAW_SHIFT 0
#define PDMA0_QM_AWB_MST_QUIET_PEW_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWB_MSG_MAX_INFWIGHT */
#define PDMA0_QM_AWB_MSG_MAX_INFWIGHT_VAW_SHIFT 0
#define PDMA0_QM_AWB_MSG_MAX_INFWIGHT_VAW_MASK 0x3F

/* PDMA0_QM_AWB_BASE_WO */
#define PDMA0_QM_AWB_BASE_WO_VAW_SHIFT 0
#define PDMA0_QM_AWB_BASE_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWB_BASE_HI */
#define PDMA0_QM_AWB_BASE_HI_VAW_SHIFT 0
#define PDMA0_QM_AWB_BASE_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWB_STATE_STS */
#define PDMA0_QM_AWB_STATE_STS_VAW_SHIFT 0
#define PDMA0_QM_AWB_STATE_STS_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWB_CHOICE_FUWWNESS_STS */
#define PDMA0_QM_AWB_CHOICE_FUWWNESS_STS_VAW_SHIFT 0
#define PDMA0_QM_AWB_CHOICE_FUWWNESS_STS_VAW_MASK 0x7F

/* PDMA0_QM_AWB_MSG_STS */
#define PDMA0_QM_AWB_MSG_STS_FUWW_SHIFT 0
#define PDMA0_QM_AWB_MSG_STS_FUWW_MASK 0x1
#define PDMA0_QM_AWB_MSG_STS_NO_INFWIGHT_SHIFT 1
#define PDMA0_QM_AWB_MSG_STS_NO_INFWIGHT_MASK 0x2

/* PDMA0_QM_AWB_SWV_CHOICE_Q_HEAD */
#define PDMA0_QM_AWB_SWV_CHOICE_Q_HEAD_VAW_SHIFT 0
#define PDMA0_QM_AWB_SWV_CHOICE_Q_HEAD_VAW_MASK 0x3

/* PDMA0_QM_AWB_EWW_CAUSE */
#define PDMA0_QM_AWB_EWW_CAUSE_CHOICE_OVF_SHIFT 0
#define PDMA0_QM_AWB_EWW_CAUSE_CHOICE_OVF_MASK 0x1
#define PDMA0_QM_AWB_EWW_CAUSE_CHOICE_WDT_SHIFT 1
#define PDMA0_QM_AWB_EWW_CAUSE_CHOICE_WDT_MASK 0x2
#define PDMA0_QM_AWB_EWW_CAUSE_AXI_WBW_EWW_SHIFT 2
#define PDMA0_QM_AWB_EWW_CAUSE_AXI_WBW_EWW_MASK 0x4

/* PDMA0_QM_AWB_EWW_MSG_EN */
#define PDMA0_QM_AWB_EWW_MSG_EN_CHOICE_OVF_SHIFT 0
#define PDMA0_QM_AWB_EWW_MSG_EN_CHOICE_OVF_MASK 0x1
#define PDMA0_QM_AWB_EWW_MSG_EN_CHOICE_WDT_SHIFT 1
#define PDMA0_QM_AWB_EWW_MSG_EN_CHOICE_WDT_MASK 0x2
#define PDMA0_QM_AWB_EWW_MSG_EN_AXI_WBW_EWW_SHIFT 2
#define PDMA0_QM_AWB_EWW_MSG_EN_AXI_WBW_EWW_MASK 0x4

/* PDMA0_QM_AWB_EWW_STS_DWP */
#define PDMA0_QM_AWB_EWW_STS_DWP_VAW_SHIFT 0
#define PDMA0_QM_AWB_EWW_STS_DWP_VAW_MASK 0x3

/* PDMA0_QM_AWB_MST_CWED_STS */
#define PDMA0_QM_AWB_MST_CWED_STS_VAW_SHIFT 0
#define PDMA0_QM_AWB_MST_CWED_STS_VAW_MASK 0x7F
#define PDMA0_QM_AWB_MST_CWED_STS_IDX_SHIFT 24
#define PDMA0_QM_AWB_MST_CWED_STS_IDX_MASK 0x1F000000

/* PDMA0_QM_AWB_MST_CWED_STS_1 */
#define PDMA0_QM_AWB_MST_CWED_STS_1_VAW_SHIFT 0
#define PDMA0_QM_AWB_MST_CWED_STS_1_VAW_MASK 0x7F
#define PDMA0_QM_AWB_MST_CWED_STS_1_IDX_SHIFT 24
#define PDMA0_QM_AWB_MST_CWED_STS_1_IDX_MASK 0x1F000000

/* PDMA0_QM_CSMW_STWICT_PWIO_CFG */
#define PDMA0_QM_CSMW_STWICT_PWIO_CFG_AWB_TYPE_SHIFT 0
#define PDMA0_QM_CSMW_STWICT_PWIO_CFG_AWB_TYPE_MASK 0x1
#define PDMA0_QM_CSMW_STWICT_PWIO_CFG_PEW_ENTWY_SHIFT 4
#define PDMA0_QM_CSMW_STWICT_PWIO_CFG_PEW_ENTWY_MASK 0x10

/* PDMA0_QM_AWC_CQ_CFG0 */
#define PDMA0_QM_AWC_CQ_CFG0_IF_B2B_EN_SHIFT 0
#define PDMA0_QM_AWC_CQ_CFG0_IF_B2B_EN_MASK 0x1
#define PDMA0_QM_AWC_CQ_CFG0_IF_MSG_EN_SHIFT 1
#define PDMA0_QM_AWC_CQ_CFG0_IF_MSG_EN_MASK 0x2
#define PDMA0_QM_AWC_CQ_CFG0_CTW_MSG_EN_SHIFT 2
#define PDMA0_QM_AWC_CQ_CFG0_CTW_MSG_EN_MASK 0x4

/* PDMA0_QM_AWC_CQ_CFG1 */
#define PDMA0_QM_AWC_CQ_CFG1_CWEDIT_WIM_SHIFT 0
#define PDMA0_QM_AWC_CQ_CFG1_CWEDIT_WIM_MASK 0xFF
#define PDMA0_QM_AWC_CQ_CFG1_MAX_INFWIGHT_SHIFT 16
#define PDMA0_QM_AWC_CQ_CFG1_MAX_INFWIGHT_MASK 0xFF0000

/* PDMA0_QM_AWC_CQ_PTW_WO */
#define PDMA0_QM_AWC_CQ_PTW_WO_VAW_SHIFT 0
#define PDMA0_QM_AWC_CQ_PTW_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWC_CQ_PTW_HI */
#define PDMA0_QM_AWC_CQ_PTW_HI_VAW_SHIFT 0
#define PDMA0_QM_AWC_CQ_PTW_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWC_CQ_TSIZE */
#define PDMA0_QM_AWC_CQ_TSIZE_VAW_SHIFT 0
#define PDMA0_QM_AWC_CQ_TSIZE_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWC_CQ_CTW */
#define PDMA0_QM_AWC_CQ_CTW_UP_SHIFT 28
#define PDMA0_QM_AWC_CQ_CTW_UP_MASK 0xF0000000

/* PDMA0_QM_AWC_CQ_IFIFO_STS */
#define PDMA0_QM_AWC_CQ_IFIFO_STS_CNT_SHIFT 0
#define PDMA0_QM_AWC_CQ_IFIFO_STS_CNT_MASK 0x7
#define PDMA0_QM_AWC_CQ_IFIFO_STS_WDY_SHIFT 4
#define PDMA0_QM_AWC_CQ_IFIFO_STS_WDY_MASK 0x10
#define PDMA0_QM_AWC_CQ_IFIFO_STS_CTW_STAWW_SHIFT 8
#define PDMA0_QM_AWC_CQ_IFIFO_STS_CTW_STAWW_MASK 0x100

/* PDMA0_QM_AWC_CQ_STS0 */
#define PDMA0_QM_AWC_CQ_STS0_CWEDIT_CNT_SHIFT 0
#define PDMA0_QM_AWC_CQ_STS0_CWEDIT_CNT_MASK 0xFF
#define PDMA0_QM_AWC_CQ_STS0_FWEE_CNT_SHIFT 8
#define PDMA0_QM_AWC_CQ_STS0_FWEE_CNT_MASK 0xFF00
#define PDMA0_QM_AWC_CQ_STS0_INFWIGHT_CNT_SHIFT 16
#define PDMA0_QM_AWC_CQ_STS0_INFWIGHT_CNT_MASK 0xFF0000

/* PDMA0_QM_AWC_CQ_STS1 */
#define PDMA0_QM_AWC_CQ_STS1_BUF_EMPTY_SHIFT 0
#define PDMA0_QM_AWC_CQ_STS1_BUF_EMPTY_MASK 0x1
#define PDMA0_QM_AWC_CQ_STS1_BUSY_SHIFT 1
#define PDMA0_QM_AWC_CQ_STS1_BUSY_MASK 0x2

/* PDMA0_QM_AWC_CQ_TSIZE_STS */
#define PDMA0_QM_AWC_CQ_TSIZE_STS_VAW_SHIFT 0
#define PDMA0_QM_AWC_CQ_TSIZE_STS_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWC_CQ_PTW_WO_STS */
#define PDMA0_QM_AWC_CQ_PTW_WO_STS_VAW_SHIFT 0
#define PDMA0_QM_AWC_CQ_PTW_WO_STS_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWC_CQ_PTW_HI_STS */
#define PDMA0_QM_AWC_CQ_PTW_HI_STS_VAW_SHIFT 0
#define PDMA0_QM_AWC_CQ_PTW_HI_STS_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CP_WW_AWC_ADDW_HI */
#define PDMA0_QM_CP_WW_AWC_ADDW_HI_VAW_SHIFT 0
#define PDMA0_QM_CP_WW_AWC_ADDW_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CP_WW_AWC_ADDW_WO */
#define PDMA0_QM_CP_WW_AWC_ADDW_WO_VAW_SHIFT 0
#define PDMA0_QM_CP_WW_AWC_ADDW_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWC_CQ_IFIFO_MSG_BASE_HI */
#define PDMA0_QM_AWC_CQ_IFIFO_MSG_BASE_HI_VAW_SHIFT 0
#define PDMA0_QM_AWC_CQ_IFIFO_MSG_BASE_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWC_CQ_IFIFO_MSG_BASE_WO */
#define PDMA0_QM_AWC_CQ_IFIFO_MSG_BASE_WO_VAW_SHIFT 0
#define PDMA0_QM_AWC_CQ_IFIFO_MSG_BASE_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWC_CQ_CTW_MSG_BASE_HI */
#define PDMA0_QM_AWC_CQ_CTW_MSG_BASE_HI_VAW_SHIFT 0
#define PDMA0_QM_AWC_CQ_CTW_MSG_BASE_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWC_CQ_CTW_MSG_BASE_WO */
#define PDMA0_QM_AWC_CQ_CTW_MSG_BASE_WO_VAW_SHIFT 0
#define PDMA0_QM_AWC_CQ_CTW_MSG_BASE_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_IFIFO_MSG_BASE_HI */
#define PDMA0_QM_CQ_IFIFO_MSG_BASE_HI_VAW_SHIFT 0
#define PDMA0_QM_CQ_IFIFO_MSG_BASE_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_IFIFO_MSG_BASE_WO */
#define PDMA0_QM_CQ_IFIFO_MSG_BASE_WO_VAW_SHIFT 0
#define PDMA0_QM_CQ_IFIFO_MSG_BASE_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_CTW_MSG_BASE_HI */
#define PDMA0_QM_CQ_CTW_MSG_BASE_HI_VAW_SHIFT 0
#define PDMA0_QM_CQ_CTW_MSG_BASE_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_CTW_MSG_BASE_WO */
#define PDMA0_QM_CQ_CTW_MSG_BASE_WO_VAW_SHIFT 0
#define PDMA0_QM_CQ_CTW_MSG_BASE_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_ADDW_OVWD */
#define PDMA0_QM_ADDW_OVWD_IDX_SHIFT 0
#define PDMA0_QM_ADDW_OVWD_IDX_MASK 0xFF

/* PDMA0_QM_CQ_IFIFO_CI */
#define PDMA0_QM_CQ_IFIFO_CI_VAW_SHIFT 0
#define PDMA0_QM_CQ_IFIFO_CI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWC_CQ_IFIFO_CI */
#define PDMA0_QM_AWC_CQ_IFIFO_CI_VAW_SHIFT 0
#define PDMA0_QM_AWC_CQ_IFIFO_CI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CQ_CTW_CI */
#define PDMA0_QM_CQ_CTW_CI_VAW_SHIFT 0
#define PDMA0_QM_CQ_CTW_CI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWC_CQ_CTW_CI */
#define PDMA0_QM_AWC_CQ_CTW_CI_VAW_SHIFT 0
#define PDMA0_QM_AWC_CQ_CTW_CI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CP_CFG */
#define PDMA0_QM_CP_CFG_SWITCH_EN_SHIFT 0
#define PDMA0_QM_CP_CFG_SWITCH_EN_MASK 0x1
#define PDMA0_QM_CP_CFG_SWITCH_WD_EN_SHIFT 1
#define PDMA0_QM_CP_CFG_SWITCH_WD_EN_MASK 0x2

/* PDMA0_QM_CP_EXT_SWITCH */
#define PDMA0_QM_CP_EXT_SWITCH_VAW_SHIFT 0
#define PDMA0_QM_CP_EXT_SWITCH_VAW_MASK 0x1

/* PDMA0_QM_CP_SWITCH_WD_SET */
#define PDMA0_QM_CP_SWITCH_WD_SET_VAW_SHIFT 0
#define PDMA0_QM_CP_SWITCH_WD_SET_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_CP_SWITCH_WD */
#define PDMA0_QM_CP_SWITCH_WD_VAW_SHIFT 0
#define PDMA0_QM_CP_SWITCH_WD_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWC_WB_ADDW_BASE_WO */
#define PDMA0_QM_AWC_WB_ADDW_BASE_WO_VAW_SHIFT 0
#define PDMA0_QM_AWC_WB_ADDW_BASE_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWC_WB_ADDW_BASE_HI */
#define PDMA0_QM_AWC_WB_ADDW_BASE_HI_VAW_SHIFT 0
#define PDMA0_QM_AWC_WB_ADDW_BASE_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_ENGINE_BASE_ADDW_HI */
#define PDMA0_QM_ENGINE_BASE_ADDW_HI_VAW_SHIFT 0
#define PDMA0_QM_ENGINE_BASE_ADDW_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_ENGINE_BASE_ADDW_WO */
#define PDMA0_QM_ENGINE_BASE_ADDW_WO_VAW_SHIFT 0
#define PDMA0_QM_ENGINE_BASE_ADDW_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_ENGINE_ADDW_WANGE_SIZE */
#define PDMA0_QM_ENGINE_ADDW_WANGE_SIZE_VAW_SHIFT 0
#define PDMA0_QM_ENGINE_ADDW_WANGE_SIZE_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_QM_AWC_AUX_BASE_ADDW_HI */
#define PDMA0_QM_QM_AWC_AUX_BASE_ADDW_HI_VAW_SHIFT 0
#define PDMA0_QM_QM_AWC_AUX_BASE_ADDW_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_QM_AWC_AUX_BASE_ADDW_WO */
#define PDMA0_QM_QM_AWC_AUX_BASE_ADDW_WO_VAW_SHIFT 0
#define PDMA0_QM_QM_AWC_AUX_BASE_ADDW_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_QM_BASE_ADDW_HI */
#define PDMA0_QM_QM_BASE_ADDW_HI_VAW_SHIFT 0
#define PDMA0_QM_QM_BASE_ADDW_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_QM_BASE_ADDW_WO */
#define PDMA0_QM_QM_BASE_ADDW_WO_VAW_SHIFT 0
#define PDMA0_QM_QM_BASE_ADDW_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_AWC_PQC_SECUWE_PUSH_IND */
#define PDMA0_QM_AWC_PQC_SECUWE_PUSH_IND_CP_NUM_SHIFT 0
#define PDMA0_QM_AWC_PQC_SECUWE_PUSH_IND_CP_NUM_MASK 0x3

/* PDMA0_QM_PQC_STS_0 */
#define PDMA0_QM_PQC_STS_0_COMP_DATA_SHIFT 0
#define PDMA0_QM_PQC_STS_0_COMP_DATA_MASK 0xFFFF
#define PDMA0_QM_PQC_STS_0_COMP_OFST_SHIFT 16
#define PDMA0_QM_PQC_STS_0_COMP_OFST_MASK 0xFFFF0000

/* PDMA0_QM_PQC_STS_1 */
#define PDMA0_QM_PQC_STS_1_COMP_FIFO_CNTW_SHIFT 0
#define PDMA0_QM_PQC_STS_1_COMP_FIFO_CNTW_MASK 0xF
#define PDMA0_QM_PQC_STS_1_COMP_FIFO_EMPTY_SHIFT 4
#define PDMA0_QM_PQC_STS_1_COMP_FIFO_EMPTY_MASK 0x10
#define PDMA0_QM_PQC_STS_1_COMP_FIFO_FUWW_SHIFT 5
#define PDMA0_QM_PQC_STS_1_COMP_FIFO_FUWW_MASK 0x20

/* PDMA0_QM_SEI_STATUS */
#define PDMA0_QM_SEI_STATUS_QM_INT_SHIFT 0
#define PDMA0_QM_SEI_STATUS_QM_INT_MASK 0x1
#define PDMA0_QM_SEI_STATUS_AWC_INT_SHIFT 1
#define PDMA0_QM_SEI_STATUS_AWC_INT_MASK 0x2

/* PDMA0_QM_SEI_MASK */
#define PDMA0_QM_SEI_MASK_QM_INT_SHIFT 0
#define PDMA0_QM_SEI_MASK_QM_INT_MASK 0x1
#define PDMA0_QM_SEI_MASK_AWC_INT_SHIFT 1
#define PDMA0_QM_SEI_MASK_AWC_INT_MASK 0x2

/* PDMA0_QM_GWBW_EWW_ADDW_WO */
#define PDMA0_QM_GWBW_EWW_ADDW_WO_VAW_SHIFT 0
#define PDMA0_QM_GWBW_EWW_ADDW_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_GWBW_EWW_ADDW_HI */
#define PDMA0_QM_GWBW_EWW_ADDW_HI_VAW_SHIFT 0
#define PDMA0_QM_GWBW_EWW_ADDW_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_GWBW_EWW_WDATA */
#define PDMA0_QM_GWBW_EWW_WDATA_VAW_SHIFT 0
#define PDMA0_QM_GWBW_EWW_WDATA_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_W2H_MASK_WO */
#define PDMA0_QM_W2H_MASK_WO_VAW_SHIFT 20
#define PDMA0_QM_W2H_MASK_WO_VAW_MASK 0xFFF00000

/* PDMA0_QM_W2H_MASK_HI */
#define PDMA0_QM_W2H_MASK_HI_VAW_SHIFT 0
#define PDMA0_QM_W2H_MASK_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_W2H_CMPW_WO */
#define PDMA0_QM_W2H_CMPW_WO_VAW_SHIFT 20
#define PDMA0_QM_W2H_CMPW_WO_VAW_MASK 0xFFF00000

/* PDMA0_QM_W2H_CMPW_HI */
#define PDMA0_QM_W2H_CMPW_HI_VAW_SHIFT 0
#define PDMA0_QM_W2H_CMPW_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_WOCAW_WANGE_BASE */
#define PDMA0_QM_WOCAW_WANGE_BASE_VAW_SHIFT 0
#define PDMA0_QM_WOCAW_WANGE_BASE_VAW_MASK 0xFFFF

/* PDMA0_QM_WOCAW_WANGE_SIZE */
#define PDMA0_QM_WOCAW_WANGE_SIZE_VAW_SHIFT 0
#define PDMA0_QM_WOCAW_WANGE_SIZE_VAW_MASK 0xFFFF

/* PDMA0_QM_HBW_WD_WATE_WIM_CFG_1 */
#define PDMA0_QM_HBW_WD_WATE_WIM_CFG_1_TOUT_SHIFT 0
#define PDMA0_QM_HBW_WD_WATE_WIM_CFG_1_TOUT_MASK 0xFF
#define PDMA0_QM_HBW_WD_WATE_WIM_CFG_1_EN_SHIFT 31
#define PDMA0_QM_HBW_WD_WATE_WIM_CFG_1_EN_MASK 0x80000000

/* PDMA0_QM_WBW_WW_WATE_WIM_CFG_0 */
#define PDMA0_QM_WBW_WW_WATE_WIM_CFG_0_WST_TOKEN_SHIFT 0
#define PDMA0_QM_WBW_WW_WATE_WIM_CFG_0_WST_TOKEN_MASK 0xFF
#define PDMA0_QM_WBW_WW_WATE_WIM_CFG_0_SAT_SHIFT 16
#define PDMA0_QM_WBW_WW_WATE_WIM_CFG_0_SAT_MASK 0xFF0000

/* PDMA0_QM_WBW_WW_WATE_WIM_CFG_1 */
#define PDMA0_QM_WBW_WW_WATE_WIM_CFG_1_TOUT_SHIFT 0
#define PDMA0_QM_WBW_WW_WATE_WIM_CFG_1_TOUT_MASK 0xFF
#define PDMA0_QM_WBW_WW_WATE_WIM_CFG_1_EN_SHIFT 31
#define PDMA0_QM_WBW_WW_WATE_WIM_CFG_1_EN_MASK 0x80000000

/* PDMA0_QM_HBW_WD_WATE_WIM_CFG_0 */
#define PDMA0_QM_HBW_WD_WATE_WIM_CFG_0_WST_TOKEN_SHIFT 0
#define PDMA0_QM_HBW_WD_WATE_WIM_CFG_0_WST_TOKEN_MASK 0xFF
#define PDMA0_QM_HBW_WD_WATE_WIM_CFG_0_SAT_SHIFT 16
#define PDMA0_QM_HBW_WD_WATE_WIM_CFG_0_SAT_MASK 0xFF0000

/* PDMA0_QM_IND_GW_APB_CFG */
#define PDMA0_QM_IND_GW_APB_CFG_ADDW_SHIFT 0
#define PDMA0_QM_IND_GW_APB_CFG_ADDW_MASK 0x7FFFFFFF
#define PDMA0_QM_IND_GW_APB_CFG_CMD_SHIFT 31
#define PDMA0_QM_IND_GW_APB_CFG_CMD_MASK 0x80000000

/* PDMA0_QM_IND_GW_APB_WDATA */
#define PDMA0_QM_IND_GW_APB_WDATA_VAW_SHIFT 0
#define PDMA0_QM_IND_GW_APB_WDATA_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_IND_GW_APB_WDATA */
#define PDMA0_QM_IND_GW_APB_WDATA_VAW_SHIFT 0
#define PDMA0_QM_IND_GW_APB_WDATA_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_IND_GW_APB_STATUS */
#define PDMA0_QM_IND_GW_APB_STATUS_WDY_SHIFT 0
#define PDMA0_QM_IND_GW_APB_STATUS_WDY_MASK 0x1
#define PDMA0_QM_IND_GW_APB_STATUS_EWW_SHIFT 1
#define PDMA0_QM_IND_GW_APB_STATUS_EWW_MASK 0x2

/* PDMA0_QM_PEWF_CNT_FWEE_WO */
#define PDMA0_QM_PEWF_CNT_FWEE_WO_VAW_SHIFT 0
#define PDMA0_QM_PEWF_CNT_FWEE_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_PEWF_CNT_FWEE_HI */
#define PDMA0_QM_PEWF_CNT_FWEE_HI_VAW_SHIFT 0
#define PDMA0_QM_PEWF_CNT_FWEE_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_PEWF_CNT_IDWE_WO */
#define PDMA0_QM_PEWF_CNT_IDWE_WO_VAW_SHIFT 0
#define PDMA0_QM_PEWF_CNT_IDWE_WO_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_PEWF_CNT_IDWE_HI */
#define PDMA0_QM_PEWF_CNT_IDWE_HI_VAW_SHIFT 0
#define PDMA0_QM_PEWF_CNT_IDWE_HI_VAW_MASK 0xFFFFFFFF

/* PDMA0_QM_PEWF_CNT_CFG */
#define PDMA0_QM_PEWF_CNT_CFG_PQ_MASK_SHIFT 0
#define PDMA0_QM_PEWF_CNT_CFG_PQ_MASK_MASK 0xF
#define PDMA0_QM_PEWF_CNT_CFG_CQ_MASK_SHIFT 8
#define PDMA0_QM_PEWF_CNT_CFG_CQ_MASK_MASK 0x1F00
#define PDMA0_QM_PEWF_CNT_CFG_CP_MASK_SHIFT 16
#define PDMA0_QM_PEWF_CNT_CFG_CP_MASK_MASK 0x1F0000
#define PDMA0_QM_PEWF_CNT_CFG_AGENT_MASK_SHIFT 24
#define PDMA0_QM_PEWF_CNT_CFG_AGENT_MASK_MASK 0x1000000
#define PDMA0_QM_PEWF_CNT_CFG_EN_FWEE_SHIFT 30
#define PDMA0_QM_PEWF_CNT_CFG_EN_FWEE_MASK 0x40000000
#define PDMA0_QM_PEWF_CNT_CFG_EN_IDWE_SHIFT 31
#define PDMA0_QM_PEWF_CNT_CFG_EN_IDWE_MASK 0x80000000

#endif /* ASIC_WEG_PDMA0_QM_MASKS_H_ */
