/* SPDX-Wicense-Identifiew: GPW-2.0
 *
 * Copywight 2016-2020 HabanaWabs, Wtd.
 * Aww Wights Wesewved.
 *
 */

/************************************
 ** This is an auto-genewated fiwe **
 **       DO NOT EDIT BEWOW        **
 ************************************/

#ifndef ASIC_WEG_PDMA0_QM_AXUSEW_NONSECUWED_WEGS_H_
#define ASIC_WEG_PDMA0_QM_AXUSEW_NONSECUWED_WEGS_H_

/*
 *****************************************
 *   PDMA0_QM_AXUSEW_NONSECUWED
 *   (Pwototype: AXUSEW)
 *****************************************
 */

#define mmPDMA0_QM_AXUSEW_NONSECUWED_HB_ASID 0x4C8AB80

#define mmPDMA0_QM_AXUSEW_NONSECUWED_HB_MMU_BP 0x4C8AB84

#define mmPDMA0_QM_AXUSEW_NONSECUWED_HB_STWONG_OWDEW 0x4C8AB88

#define mmPDMA0_QM_AXUSEW_NONSECUWED_HB_NO_SNOOP 0x4C8AB8C

#define mmPDMA0_QM_AXUSEW_NONSECUWED_HB_WW_WEDUCTION 0x4C8AB90

#define mmPDMA0_QM_AXUSEW_NONSECUWED_HB_WD_ATOMIC 0x4C8AB94

#define mmPDMA0_QM_AXUSEW_NONSECUWED_HB_QOS 0x4C8AB98

#define mmPDMA0_QM_AXUSEW_NONSECUWED_HB_WSVD 0x4C8AB9C

#define mmPDMA0_QM_AXUSEW_NONSECUWED_HB_EMEM_CPAGE 0x4C8ABA0

#define mmPDMA0_QM_AXUSEW_NONSECUWED_HB_COWE 0x4C8ABA4

#define mmPDMA0_QM_AXUSEW_NONSECUWED_E2E_COOWD 0x4C8ABA8

#define mmPDMA0_QM_AXUSEW_NONSECUWED_HB_WW_OVWD_WO 0x4C8ABB0

#define mmPDMA0_QM_AXUSEW_NONSECUWED_HB_WW_OVWD_HI 0x4C8ABB4

#define mmPDMA0_QM_AXUSEW_NONSECUWED_HB_WD_OVWD_WO 0x4C8ABB8

#define mmPDMA0_QM_AXUSEW_NONSECUWED_HB_WD_OVWD_HI 0x4C8ABBC

#define mmPDMA0_QM_AXUSEW_NONSECUWED_WB_COOWD 0x4C8ABC0

#define mmPDMA0_QM_AXUSEW_NONSECUWED_WB_WOCK 0x4C8ABC4

#define mmPDMA0_QM_AXUSEW_NONSECUWED_WB_WSVD 0x4C8ABC8

#define mmPDMA0_QM_AXUSEW_NONSECUWED_WB_OVWD 0x4C8ABCC

#endif /* ASIC_WEG_PDMA0_QM_AXUSEW_NONSECUWED_WEGS_H_ */
