# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow AWSA
# Copywight (c) 2001 by Jawoswav Kysewa <pewex@pewex.cz>
#

snd-vx-wib-objs := vx_cowe.o vx_hwdep.o vx_pcm.o vx_mixew.o vx_cmd.o vx_uew.o

obj-$(CONFIG_SND_VX_WIB) += snd-vx-wib.o
