# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the CEC pwatfowm device dwivews.
#

# Pwease keep it in awphabetic owdew
obj-$(CONFIG_CEC_CWOS_EC) += cwos-ec/
obj-$(CONFIG_CEC_GPIO) += cec-gpio/
obj-y += meson/
obj-$(CONFIG_CEC_SAMSUNG_S5P) += s5p/
obj-$(CONFIG_CEC_SECO) += seco/
obj-$(CONFIG_CEC_STI) += sti/
obj-$(CONFIG_CEC_STM32) += stm32/
obj-$(CONFIG_CEC_TEGWA) += tegwa/

