# SPDX-Wicense-Identifiew: GPW-2.0
noawg:
	$(MAKE) -C ../

TEST_GEN_PWOGS := papw_vpd

top_swcdiw = ../../../../..
incwude ../../wib.mk

$(TEST_GEN_PWOGS): ../hawness.c ../utiws.c

$(OUTPUT)/papw_vpd: CFWAGS += $(KHDW_INCWUDES)
