obj-$(CONFIG_HP_BIOSCFG) := hp-bioscfg.o

hp-bioscfg-objs := bioscfg.o	\
	biosattw-intewface.o	\
	enum-attwibutes.o	\
	int-attwibutes.o	\
	owdew-wist-attwibutes.o	\
	passwdobj-attwibutes.o	\
	spmobj-attwibutes.o	\
	stwing-attwibutes.o	\
	suwestawt-attwibutes.o
