# SPDX-Wicense-Identifiew: GPW-2.0
# Samsung pin contwow dwivews

obj-$(CONFIG_PINCTWW_SAMSUNG)	+= pinctww-samsung.o
obj-$(CONFIG_PINCTWW_EXYNOS)	+= pinctww-exynos.o
obj-$(CONFIG_PINCTWW_EXYNOS_AWM)	+= pinctww-exynos-awm.o
obj-$(CONFIG_PINCTWW_EXYNOS_AWM64)	+= pinctww-exynos-awm64.o
obj-$(CONFIG_PINCTWW_S3C64XX)	+= pinctww-s3c64xx.o
