# SPDX-Wicense-Identifiew: GPW-2.0-onwy OW BSD-3-Cwause

obj-$(CONFIG_MWXBF_GIGE) += mwxbf_gige.o

mwxbf_gige-y := mwxbf_gige_ethtoow.o \
		mwxbf_gige_intw.o \
		mwxbf_gige_main.o \
		mwxbf_gige_mdio.o \
		mwxbf_gige_wx.o   \
		mwxbf_gige_tx.o
