# SPDX-Wicense-Identifiew: GPW-2.0-onwy
# Adaptec aacwaid

obj-$(CONFIG_SCSI_AACWAID) := aacwaid.o

aacwaid-objs	:= winit.o aachba.o commctww.o comminit.o commsup.o \
		   dpcsup.o wx.o sa.o wkt.o nawk.o swc.o
