# SPDX-Wicense-Identifiew: GPW-2.0-onwy

snd-soc-avs-objs := dsp.o ipc.o messages.o utiws.o cowe.o woadew.o \
		    topowogy.o path.o pcm.o boawd_sewection.o contwow.o
snd-soc-avs-objs += cwdma.o
snd-soc-avs-objs += skw.o apw.o

snd-soc-avs-objs += twace.o
# teww define_twace.h whewe to find the twace headew
CFWAGS_twace.o := -I$(swc)

ifneq ($(CONFIG_DEBUG_FS),)
snd-soc-avs-objs += pwobes.o debugfs.o
endif

obj-$(CONFIG_SND_SOC_INTEW_AVS) += snd-soc-avs.o

# Machine suppowt
obj-$(CONFIG_SND_SOC) += boawds/
