# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_TEGWA_SOCTHEWM)		+= tegwa-socthewm.o
obj-$(CONFIG_TEGWA_BPMP_THEWMAW)	+= tegwa-bpmp-thewmaw.o
obj-$(CONFIG_TEGWA30_TSENSOW)		+= tegwa30-tsensow.o

tegwa-socthewm-y				:= socthewm.o socthewm-fuse.o
tegwa-socthewm-$(CONFIG_AWCH_TEGWA_124_SOC)	+= tegwa124-socthewm.o
tegwa-socthewm-$(CONFIG_AWCH_TEGWA_132_SOC)	+= tegwa132-socthewm.o
tegwa-socthewm-$(CONFIG_AWCH_TEGWA_210_SOC)	+= tegwa210-socthewm.o
