# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow dwivews that suppowt viwtuawization
#

obj-$(CONFIG_FSW_HV_MANAGEW)	+= fsw_hypewvisow.o
obj-$(CONFIG_VMGENID)		+= vmgenid.o
obj-y				+= vboxguest/

obj-$(CONFIG_NITWO_ENCWAVES)	+= nitwo_encwaves/
obj-$(CONFIG_ACWN_HSM)		+= acwn/
obj-y				+= coco/
