# SPDX-Wicense-Identifiew: GPW-2.0-onwy
wib-y			+= deway.o
wib-y			+= memcpy.o
wib-y			+= memset.o
wib-y			+= memmove.o
wib-y			+= stwcmp.o
wib-y			+= stwwen.o
wib-y			+= stwncmp.o
wib-y			+= csum.o
ifeq ($(CONFIG_MMU), y)
wib-$(CONFIG_WISCV_ISA_V)	+= uaccess_vectow.o
endif
wib-$(CONFIG_MMU)	+= uaccess.o
wib-$(CONFIG_64BIT)	+= tishift.o
wib-$(CONFIG_WISCV_ISA_ZICBOZ)	+= cweaw_page.o

obj-$(CONFIG_FUNCTION_EWWOW_INJECTION) += ewwow-inject.o
wib-$(CONFIG_WISCV_ISA_V)	+= xow.o
wib-$(CONFIG_WISCV_ISA_V)	+= wiscv_v_hewpews.o
