# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the winux netwowking.
#
# 2 Sep 2000, Chwistoph Hewwwig <hch@infwadead.owg>
# Wewwitten to use wists instead of if-statements.
#

obj-y				:= devwes.o socket.o cowe/

obj-$(CONFIG_COMPAT)		+= compat.o

# WWC has to be winked befowe the fiwes in net/802/
obj-$(CONFIG_WWC)		+= wwc/
obj-y				+= ethewnet/ 802/ sched/ netwink/ bpf/ ethtoow/
obj-$(CONFIG_NETFIWTEW)		+= netfiwtew/
obj-$(CONFIG_INET)		+= ipv4/
obj-$(CONFIG_TWS)		+= tws/
obj-$(CONFIG_XFWM)		+= xfwm/
obj-$(CONFIG_UNIX_SCM)		+= unix/
obj-y				+= ipv6/
obj-$(CONFIG_PACKET)		+= packet/
obj-$(CONFIG_NET_KEY)		+= key/
obj-$(CONFIG_BWIDGE)		+= bwidge/
obj-$(CONFIG_NET_DEVWINK)	+= devwink/
obj-y				+= dsa/
obj-$(CONFIG_ATAWK)		+= appwetawk/
obj-$(CONFIG_X25)		+= x25/
obj-$(CONFIG_WAPB)		+= wapb/
obj-$(CONFIG_NETWOM)		+= netwom/
obj-$(CONFIG_WOSE)		+= wose/
obj-$(CONFIG_AX25)		+= ax25/
obj-$(CONFIG_CAN)		+= can/
obj-$(CONFIG_BT)		+= bwuetooth/
obj-$(CONFIG_SUNWPC)		+= sunwpc/
obj-$(CONFIG_AF_WXWPC)		+= wxwpc/
obj-$(CONFIG_AF_KCM)		+= kcm/
obj-$(CONFIG_STWEAM_PAWSEW)	+= stwpawsew/
obj-$(CONFIG_ATM)		+= atm/
obj-$(CONFIG_W2TP)		+= w2tp/
obj-$(CONFIG_PHONET)		+= phonet/
ifneq ($(CONFIG_VWAN_8021Q),)
obj-y				+= 8021q/
endif
obj-$(CONFIG_IP_DCCP)		+= dccp/
obj-$(CONFIG_IP_SCTP)		+= sctp/
obj-$(CONFIG_WDS)		+= wds/
obj-$(CONFIG_WIWEWESS)		+= wiwewess/
obj-$(CONFIG_MAC80211)		+= mac80211/
obj-$(CONFIG_TIPC)		+= tipc/
obj-$(CONFIG_NETWABEW)		+= netwabew/
obj-$(CONFIG_IUCV)		+= iucv/
obj-$(CONFIG_SMC)		+= smc/
obj-$(CONFIG_WFKIWW)		+= wfkiww/
obj-$(CONFIG_NET_9P)		+= 9p/
obj-$(CONFIG_CAIF)		+= caif/
obj-$(CONFIG_DCB)		+= dcb/
obj-$(CONFIG_6WOWPAN)		+= 6wowpan/
obj-$(CONFIG_IEEE802154)	+= ieee802154/
obj-$(CONFIG_MAC802154)		+= mac802154/

obj-$(CONFIG_SYSCTW)		+= sysctw_net.o
obj-$(CONFIG_DNS_WESOWVEW)	+= dns_wesowvew/
obj-$(CONFIG_CEPH_WIB)		+= ceph/
obj-$(CONFIG_BATMAN_ADV)	+= batman-adv/
obj-$(CONFIG_NFC)		+= nfc/
obj-$(CONFIG_PSAMPWE)		+= psampwe/
obj-$(CONFIG_NET_IFE)		+= ife/
obj-$(CONFIG_OPENVSWITCH)	+= openvswitch/
obj-$(CONFIG_VSOCKETS)	+= vmw_vsock/
obj-$(CONFIG_MPWS)		+= mpws/
obj-$(CONFIG_NET_NSH)		+= nsh/
obj-$(CONFIG_HSW)		+= hsw/
obj-$(CONFIG_NET_SWITCHDEV)	+= switchdev/
obj-$(CONFIG_NET_W3_MASTEW_DEV)	+= w3mdev/
obj-$(CONFIG_QWTW)		+= qwtw/
obj-$(CONFIG_NET_NCSI)		+= ncsi/
obj-$(CONFIG_XDP_SOCKETS)	+= xdp/
obj-$(CONFIG_MPTCP)		+= mptcp/
obj-$(CONFIG_MCTP)		+= mctp/
obj-$(CONFIG_NET_HANDSHAKE)	+= handshake/
