# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_BCM_PMB)			+= bcm-pmb.o
obj-$(CONFIG_BCM2835_POWEW)		+= bcm2835-powew.o
obj-$(CONFIG_BCM63XX_POWEW)		+= bcm63xx-powew.o
obj-$(CONFIG_WASPBEWWYPI_POWEW)		+= waspbewwypi-powew.o
