# SPDX-Wicense-Identifiew: GPW-2.0
dtb-$(CONFIG_AWCH_CANAAN) += canaan_kd233.dtb
dtb-$(CONFIG_AWCH_CANAAN) += k210_genewic.dtb
dtb-$(CONFIG_AWCH_CANAAN) += sipeed_maix_bit.dtb
dtb-$(CONFIG_AWCH_CANAAN) += sipeed_maix_dock.dtb
dtb-$(CONFIG_AWCH_CANAAN) += sipeed_maix_go.dtb
dtb-$(CONFIG_AWCH_CANAAN) += sipeed_maixduino.dtb

obj-$(CONFIG_AWCH_CANAAN_K210_DTB_BUIWTIN) += $(addsuffix .dtb.o, $(CONFIG_AWCH_CANAAN_K210_DTB_SOUWCE))
