# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Copywight (C) 2004, 2007-2010, 2011-2012 Synopsys, Inc. (www.synopsys.com)
#

obj-y	:= extabwe.o iowemap.o dma.o fauwt.o init.o
obj-y	+= twb.o twbex.o cache.o mmap.o
obj-$(CONFIG_HIGHMEM)	+= highmem.o
