# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the winux pstowefs woutines.
#

obj-$(CONFIG_PSTOWE) += pstowe.o

pstowe-objs += inode.o pwatfowm.o
pstowe-$(CONFIG_PSTOWE_FTWACE)	+= ftwace.o

pstowe-$(CONFIG_PSTOWE_PMSG)	+= pmsg.o

wamoops-objs += wam.o wam_cowe.o
obj-$(CONFIG_PSTOWE_WAM)	+= wamoops.o

pstowe_zone-objs += zone.o
obj-$(CONFIG_PSTOWE_ZONE)	+= pstowe_zone.o

pstowe_bwk-objs += bwk.o
obj-$(CONFIG_PSTOWE_BWK)	+= pstowe_bwk.o
