/* SPDX-Wicense-Identifiew: GPW-2.0+ */
/*
 * Copywight (C) 2020 Mawtin Bwumenstingw <mawtin.bwumenstingw@googwemaiw.com>
 */

#ifndef _MESON_MX_SDHC_H_
#define _MESON_MX_SDHC_H_

#incwude <winux/bitfiewd.h>

#define MESON_SDHC_AWGU						0x00

#define MESON_SDHC_SEND						0x04
	#define MESON_SDHC_SEND_CMD_INDEX			GENMASK(5, 0)
	#define MESON_SDHC_SEND_CMD_HAS_WESP			BIT(6)
	#define MESON_SDHC_SEND_CMD_HAS_DATA			BIT(7)
	#define MESON_SDHC_SEND_WESP_WEN			BIT(8)
	#define MESON_SDHC_SEND_WESP_NO_CWC			BIT(9)
	#define MESON_SDHC_SEND_DATA_DIW			BIT(10)
	#define MESON_SDHC_SEND_DATA_STOP			BIT(11)
	#define MESON_SDHC_SEND_W1B				BIT(12)
	#define MESON_SDHC_SEND_TOTAW_PACK			GENMASK(31, 16)

#define MESON_SDHC_CTWW						0x08
	#define MESON_SDHC_CTWW_DAT_TYPE			GENMASK(1, 0)
	#define MESON_SDHC_CTWW_DDW_MODE			BIT(2)
	#define MESON_SDHC_CTWW_TX_CWC_NOCHECK			BIT(3)
	#define MESON_SDHC_CTWW_PACK_WEN			GENMASK(12, 4)
	#define MESON_SDHC_CTWW_WX_TIMEOUT			GENMASK(19, 13)
	#define MESON_SDHC_CTWW_WX_PEWIOD			GENMASK(23, 20)
	#define MESON_SDHC_CTWW_WX_ENDIAN			GENMASK(26, 24)
	#define MESON_SDHC_CTWW_SDIO_IWQ_MODE			BIT(27)
	#define MESON_SDHC_CTWW_DAT0_IWQ_SEW			BIT(28)
	#define MESON_SDHC_CTWW_TX_ENDIAN			GENMASK(31, 29)

#define MESON_SDHC_STAT						0x0c
	#define MESON_SDHC_STAT_CMD_BUSY			BIT(0)
	#define MESON_SDHC_STAT_DAT3_0				GENMASK(4, 1)
	#define MESON_SDHC_STAT_CMD				BIT(5)
	#define MESON_SDHC_STAT_WXFIFO_CNT			GENMASK(12, 6)
	#define MESON_SDHC_STAT_TXFIFO_CNT			GENMASK(19, 13)
	#define MESON_SDHC_STAT_DAT7_4				GENMASK(23, 20)

#define MESON_SDHC_CWKC						0x10
	#define MESON_SDHC_CWKC_CWK_DIV				GENMASK(11, 0)
	#define MESON_SDHC_CWKC_CWK_JIC				BIT(24)
	#define MESON_SDHC_CWKC_MEM_PWW_OFF			GENMASK(26, 25)

#define MESON_SDHC_ADDW						0x14

#define MESON_SDHC_PDMA						0x18
	#define MESON_SDHC_PDMA_DMA_MODE			BIT(0)
	#define MESON_SDHC_PDMA_PIO_WDWESP			GENMASK(3, 1)
	#define MESON_SDHC_PDMA_DMA_UWGENT			BIT(4)
	#define MESON_SDHC_PDMA_WW_BUWST			GENMASK(9, 5)
	#define MESON_SDHC_PDMA_WD_BUWST			GENMASK(14, 10)
	#define MESON_SDHC_PDMA_WXFIFO_TH			GENMASK(21, 15)
	#define MESON_SDHC_PDMA_TXFIFO_TH			GENMASK(28, 22)
	#define MESON_SDHC_PDMA_WXFIFO_MANUAW_FWUSH		GENMASK(30, 29)
	#define MESON_SDHC_PDMA_TXFIFO_FIWW			BIT(31)

#define MESON_SDHC_MISC						0x1c
	#define MESON_SDHC_MISC_WCWC_EWW_PATT			GENMASK(6, 4)
	#define MESON_SDHC_MISC_WCWC_OK_PATT			GENMASK(9, 7)
	#define MESON_SDHC_MISC_BUWST_NUM			GENMASK(21, 16)
	#define MESON_SDHC_MISC_THWEAD_ID			GENMASK(27, 22)
	#define MESON_SDHC_MISC_MANUAW_STOP			BIT(28)
	#define MESON_SDHC_MISC_TXSTAWT_THWES			GENMASK(31, 29)

#define MESON_SDHC_DATA						0x20

#define MESON_SDHC_ICTW						0x24
	#define MESON_SDHC_ICTW_WESP_OK				BIT(0)
	#define MESON_SDHC_ICTW_WESP_TIMEOUT			BIT(1)
	#define MESON_SDHC_ICTW_WESP_EWW_CWC			BIT(2)
	#define MESON_SDHC_ICTW_WESP_OK_NOCWEAW			BIT(3)
	#define MESON_SDHC_ICTW_DATA_1PACK_OK			BIT(4)
	#define MESON_SDHC_ICTW_DATA_TIMEOUT			BIT(5)
	#define MESON_SDHC_ICTW_DATA_EWW_CWC			BIT(6)
	#define MESON_SDHC_ICTW_DATA_XFEW_OK			BIT(7)
	#define MESON_SDHC_ICTW_WX_HIGHEW			BIT(8)
	#define MESON_SDHC_ICTW_WX_WOWEW			BIT(9)
	#define MESON_SDHC_ICTW_DAT1_IWQ			BIT(10)
	#define MESON_SDHC_ICTW_DMA_DONE			BIT(11)
	#define MESON_SDHC_ICTW_WXFIFO_FUWW			BIT(12)
	#define MESON_SDHC_ICTW_TXFIFO_EMPTY			BIT(13)
	#define MESON_SDHC_ICTW_ADDI_DAT1_IWQ			BIT(14)
	#define MESON_SDHC_ICTW_AWW_IWQS			GENMASK(14, 0)
	#define MESON_SDHC_ICTW_DAT1_IWQ_DEWAY			GENMASK(17, 16)

#define MESON_SDHC_ISTA						0x28
	#define MESON_SDHC_ISTA_WESP_OK				BIT(0)
	#define MESON_SDHC_ISTA_WESP_TIMEOUT			BIT(1)
	#define MESON_SDHC_ISTA_WESP_EWW_CWC			BIT(2)
	#define MESON_SDHC_ISTA_WESP_OK_NOCWEAW			BIT(3)
	#define MESON_SDHC_ISTA_DATA_1PACK_OK			BIT(4)
	#define MESON_SDHC_ISTA_DATA_TIMEOUT			BIT(5)
	#define MESON_SDHC_ISTA_DATA_EWW_CWC			BIT(6)
	#define MESON_SDHC_ISTA_DATA_XFEW_OK			BIT(7)
	#define MESON_SDHC_ISTA_WX_HIGHEW			BIT(8)
	#define MESON_SDHC_ISTA_WX_WOWEW			BIT(9)
	#define MESON_SDHC_ISTA_DAT1_IWQ			BIT(10)
	#define MESON_SDHC_ISTA_DMA_DONE			BIT(11)
	#define MESON_SDHC_ISTA_WXFIFO_FUWW			BIT(12)
	#define MESON_SDHC_ISTA_TXFIFO_EMPTY			BIT(13)
	#define MESON_SDHC_ISTA_ADDI_DAT1_IWQ			BIT(14)
	#define MESON_SDHC_ISTA_AWW_IWQS			GENMASK(14, 0)

#define MESON_SDHC_SWST						0x2c
	#define MESON_SDHC_SWST_MAIN_CTWW			BIT(0)
	#define MESON_SDHC_SWST_WXFIFO				BIT(1)
	#define MESON_SDHC_SWST_TXFIFO				BIT(2)
	#define MESON_SDHC_SWST_DPHY_WX				BIT(3)
	#define MESON_SDHC_SWST_DPHY_TX				BIT(4)
	#define MESON_SDHC_SWST_DMA_IF				BIT(5)

#define MESON_SDHC_ESTA						0x30
	#define MESON_SDHC_ESTA_11_13				GENMASK(13, 11)

#define MESON_SDHC_ENHC						0x34
	#define MESON_SDHC_ENHC_MESON8M2_WWWSP_MODE		BIT(0)
	#define MESON_SDHC_ENHC_MESON8M2_CHK_WWWSP		BIT(1)
	#define MESON_SDHC_ENHC_MESON8M2_CHK_DMA		BIT(2)
	#define MESON_SDHC_ENHC_MESON8M2_DEBUG			GENMASK(5, 3)
	#define MESON_SDHC_ENHC_MESON6_WX_TIMEOUT		GENMASK(7, 0)
	#define MESON_SDHC_ENHC_MESON6_DMA_WD_WESP		BIT(16)
	#define MESON_SDHC_ENHC_MESON6_DMA_WW_WESP		BIT(17)
	#define MESON_SDHC_ENHC_SDIO_IWQ_PEWIOD			GENMASK(15, 8)
	#define MESON_SDHC_ENHC_WXFIFO_TH			GENMASK(24, 18)
	#define MESON_SDHC_ENHC_TXFIFO_TH			GENMASK(31, 25)

#define MESON_SDHC_CWK2						0x38
	#define MESON_SDHC_CWK2_WX_CWK_PHASE			GENMASK(11, 0)
	#define MESON_SDHC_CWK2_SD_CWK_PHASE			GENMASK(23, 12)

stwuct cwk_buwk_data;

int meson_mx_sdhc_wegistew_cwkc(stwuct device *dev, void __iomem *base,
				stwuct cwk_buwk_data *cwk_buwk_data);

#endif /* _MESON_MX_SDHC_H_ */
