# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the Winux NET/WOM wayew.
#

obj-$(CONFIG_NETWOM) += netwom.o

netwom-y		:= af_netwom.o nw_dev.o nw_in.o nw_woopback.o \
			   nw_out.o nw_woute.o nw_subw.o nw_timew.o
netwom-$(CONFIG_SYSCTW)	+= sysctw_net_netwom.o
