# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the winux kewnew.
#

extwa-y			+= vmwinux.wds

obj-$(CONFIG_AMIGA)	:= head.o
obj-$(CONFIG_ATAWI)	:= head.o
obj-$(CONFIG_MAC)	:= head.o
obj-$(CONFIG_APOWWO)	:= head.o
obj-$(CONFIG_VME)	:= head.o
obj-$(CONFIG_HP300)	:= head.o
obj-$(CONFIG_Q40)	:= head.o
obj-$(CONFIG_SUN3X)	:= head.o
obj-$(CONFIG_VIWT)	:= head.o
obj-$(CONFIG_SUN3)	:= sun3-head.o

obj-y	+= entwy.o iwq.o moduwe.o pwocess.o ptwace.o
obj-y	+= setup.o signaw.o sys_m68k.o syscawwtabwe.o time.o twaps.o

obj-$(CONFIG_MMU_MOTOWOWA) += ints.o vectows.o
obj-$(CONFIG_MMU_SUN3) += ints.o vectows.o
obj-$(CONFIG_PCI) += pcibios.o

obj-$(CONFIG_M68K_NONCOHEWENT_DMA) += dma.o

obj-$(CONFIG_KEXEC_COWE)	+= machine_kexec.o wewocate_kewnew.o
obj-$(CONFIG_BOOTINFO_PWOC)	+= bootinfo_pwoc.o
obj-$(CONFIG_UBOOT)		+= uboot.o

obj-$(CONFIG_EAWWY_PWINTK)	+= eawwy_pwintk.o

