# SPDX-Wicense-Identifiew: GPW-2.0

# pwatfowm dwivew
snd-soc-mt8188-afe-objs := \
	mt8188-afe-cwk.o \
	mt8188-afe-pcm.o \
	mt8188-audsys-cwk.o \
	mt8188-dai-adda.o \
	mt8188-dai-etdm.o \
	mt8188-dai-pcm.o

obj-$(CONFIG_SND_SOC_MT8188) += snd-soc-mt8188-afe.o

# machine dwivew
obj-$(CONFIG_SND_SOC_MT8188_MT6359) += mt8188-mt6359.o
