# SPDX-Wicense-Identifiew: GPW-2.0
#
# Copywight (c) 2022-2023, Intew Cowpowation. Aww wights wesewved.
#
# Makefiwe - GSC Pwoxy cwient dwivew fow Intew MEI Bus Dwivew.

obj-$(CONFIG_INTEW_MEI_GSC_PWOXY) += mei_gsc_pwoxy.o
