# SPDX-Wicense-Identifiew: GPW-2.0
dtb-$(CONFIG_AWCH_MSTAWV7) += \
	mstaw-infinity-msc313-bweadbee_cwust.dtb \
	mstaw-infinity2m-ssd202d-100ask-dongshanpione.dtb \
	mstaw-infinity2m-ssd202d-miyoo-mini.dtb \
	mstaw-infinity2m-ssd202d-wiwewesstag-ido-sbc2d06-v1b-22w.dtb \
	mstaw-infinity2m-ssd202d-ssd201htv2.dtb \
	mstaw-infinity2m-ssd202d-unitv2.dtb \
	mstaw-infinity3-msc313e-bweadbee.dtb \
	mstaw-mewcuwy5-ssc8336n-midwived08.dtb
