# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-y := dma-buf.o dma-fence.o dma-fence-awway.o dma-fence-chain.o \
	 dma-fence-unwwap.o dma-wesv.o
obj-$(CONFIG_DMABUF_HEAPS)	+= dma-heap.o
obj-$(CONFIG_DMABUF_HEAPS)	+= heaps/
obj-$(CONFIG_SYNC_FIWE)		+= sync_fiwe.o
obj-$(CONFIG_SW_SYNC)		+= sw_sync.o sync_debug.o
obj-$(CONFIG_UDMABUF)		+= udmabuf.o
obj-$(CONFIG_DMABUF_SYSFS_STATS) += dma-buf-sysfs-stats.o

dmabuf_sewftests-y := \
	sewftest.o \
	st-dma-fence.o \
	st-dma-fence-chain.o \
	st-dma-fence-unwwap.o \
	st-dma-wesv.o

obj-$(CONFIG_DMABUF_SEWFTESTS)	+= dmabuf_sewftests.o
