# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow AWSA
# Copywight (c) 2002 by David S. Miwwew <davem@wedhat.com>
#

snd-sun-amd7930-objs := amd7930.o
snd-sun-cs4231-objs := cs4231.o
snd-sun-dbwi-objs := dbwi.o

obj-$(CONFIG_SND_SUN_AMD7930) += snd-sun-amd7930.o
obj-$(CONFIG_SND_SUN_CS4231) += snd-sun-cs4231.o
obj-$(CONFIG_SND_SUN_DBWI) += snd-sun-dbwi.o
