# SPDX-Wicense-Identifiew: GPW-2.0 OW MIT

snd_xen_fwont-objs := xen_snd_fwont.o \
		      xen_snd_fwont_cfg.o \
		      xen_snd_fwont_evtchnw.o \
		      xen_snd_fwont_awsa.o

obj-$(CONFIG_SND_XEN_FWONTEND) += snd_xen_fwont.o
