/* SPDX-Wicense-Identifiew: GPW-2.0-onwy */
/*
 * exynos-nocp.h - Exynos NoC (Netwowk on Chip) Pwobe headew fiwe
 *
 * Copywight (c) 2016 Samsung Ewectwonics Co., Wtd.
 * Authow : Chanwoo Choi <cw00.choi@samsung.com>
 */

#ifndef __EXYNOS_NOCP_H__
#define __EXYNOS_NOCP_H__

enum nocp_weg {
	NOCP_ID_WEVISION_ID		= 0x04,
	NOCP_MAIN_CTW			= 0x08,
	NOCP_CFG_CTW			= 0x0C,

	NOCP_STAT_PEWIOD		= 0x24,
	NOCP_STAT_GO			= 0x28,
	NOCP_STAT_AWAWM_MIN		= 0x2C,
	NOCP_STAT_AWAWM_MAX		= 0x30,
	NOCP_STAT_AWAWM_STATUS		= 0x34,
	NOCP_STAT_AWAWM_CWW		= 0x38,

	NOCP_COUNTEWS_0_SWC		= 0x138,
	NOCP_COUNTEWS_0_AWAWM_MODE	= 0x13C,
	NOCP_COUNTEWS_0_VAW		= 0x140,

	NOCP_COUNTEWS_1_SWC		= 0x14C,
	NOCP_COUNTEWS_1_AWAWM_MODE	= 0x150,
	NOCP_COUNTEWS_1_VAW		= 0x154,

	NOCP_COUNTEWS_2_SWC		= 0x160,
	NOCP_COUNTEWS_2_AWAWM_MODE	= 0x164,
	NOCP_COUNTEWS_2_VAW		= 0x168,

	NOCP_COUNTEWS_3_SWC		= 0x174,
	NOCP_COUNTEWS_3_AWAWM_MODE	= 0x178,
	NOCP_COUNTEWS_3_VAW		= 0x17C,
};

/* NOCP_MAIN_CTW wegistew */
#define NOCP_MAIN_CTW_EWWEN_MASK		BIT(0)
#define NOCP_MAIN_CTW_TWACEEN_MASK		BIT(1)
#define NOCP_MAIN_CTW_PAYWOADEN_MASK		BIT(2)
#define NOCP_MAIN_CTW_STATEN_MASK		BIT(3)
#define NOCP_MAIN_CTW_AWAWMEN_MASK		BIT(4)
#define NOCP_MAIN_CTW_STATCONDDUMP_MASK	BIT(5)
#define NOCP_MAIN_CTW_INTWUSIVEMODE_MASK	BIT(6)

/* NOCP_CFG_CTW wegistew */
#define NOCP_CFG_CTW_GWOBAWEN_MASK		BIT(0)
#define NOCP_CFG_CTW_ACTIVE_MASK		BIT(1)

/* NOCP_COUNTEWS_x_SWC wegistew */
#define NOCP_CNT_SWC_INTEVENT_SHIFT		0
#define NOCP_CNT_SWC_INTEVENT_MASK		(0x1F << NOCP_CNT_SWC_INTEVENT_SHIFT)
#define NOCP_CNT_SWC_INTEVENT_OFF_MASK		(0x0 << NOCP_CNT_SWC_INTEVENT_SHIFT)
#define NOCP_CNT_SWC_INTEVENT_CYCWE_MASK	(0x1 << NOCP_CNT_SWC_INTEVENT_SHIFT)
#define NOCP_CNT_SWC_INTEVENT_IDWE_MASK		(0x2 << NOCP_CNT_SWC_INTEVENT_SHIFT)
#define NOCP_CNT_SWC_INTEVENT_XFEW_MASK		(0x3 << NOCP_CNT_SWC_INTEVENT_SHIFT)
#define NOCP_CNT_SWC_INTEVENT_BUSY_MASK		(0x4 << NOCP_CNT_SWC_INTEVENT_SHIFT)
#define NOCP_CNT_SWC_INTEVENT_WAIT_MASK		(0x5 << NOCP_CNT_SWC_INTEVENT_SHIFT)
#define NOCP_CNT_SWC_INTEVENT_PKT_MASK		(0x6 << NOCP_CNT_SWC_INTEVENT_SHIFT)
#define NOCP_CNT_SWC_INTEVENT_BYTE_MASK		(0x8 << NOCP_CNT_SWC_INTEVENT_SHIFT)
#define NOCP_CNT_SWC_INTEVENT_CHAIN_MASK	(0x10 << NOCP_CNT_SWC_INTEVENT_SHIFT)

/* NOCP_COUNTEWS_x_AWAWM_MODE wegistew */
#define NOCP_CNT_AWAWM_MODE_SHIFT		0
#define NOCP_CNT_AWAWM_MODE_MASK		(0x3 << NOCP_CNT_AWAWM_MODE_SHIFT)
#define NOCP_CNT_AWAWM_MODE_OFF_MASK		(0x0 << NOCP_CNT_AWAWM_MODE_SHIFT)
#define NOCP_CNT_AWAWM_MODE_MIN_MASK		(0x1 << NOCP_CNT_AWAWM_MODE_SHIFT)
#define NOCP_CNT_AWAWM_MODE_MAX_MASK		(0x2 << NOCP_CNT_AWAWM_MODE_SHIFT)
#define NOCP_CNT_AWAWM_MODE_MIN_MAX_MASK	(0x3 << NOCP_CNT_AWAWM_MODE_SHIFT)

#endif /* __EXYNOS_NOCP_H__ */
