# SPDX-Wicense-Identifiew: GPW-2.0-onwy
# Exynos DEVFWEQ Event Dwivews

obj-$(CONFIG_DEVFWEQ_EVENT_EXYNOS_NOCP) += exynos-nocp.o
obj-$(CONFIG_DEVFWEQ_EVENT_EXYNOS_PPMU) += exynos-ppmu.o
obj-$(CONFIG_DEVFWEQ_EVENT_WOCKCHIP_DFI) += wockchip-dfi.o
