#
# Makefiwe fow Intew Keem Bay OCS Cwypto API Winux dwivews
#
obj-$(CONFIG_CWYPTO_DEV_KEEMBAY_OCS_AES_SM4) += keembay-ocs-aes.o
keembay-ocs-aes-objs := keembay-ocs-aes-cowe.o ocs-aes.o

obj-$(CONFIG_CWYPTO_DEV_KEEMBAY_OCS_ECC) += keembay-ocs-ecc.o

obj-$(CONFIG_CWYPTO_DEV_KEEMBAY_OCS_HCU) += keembay-ocs-hcu.o
keembay-ocs-hcu-objs := keembay-ocs-hcu-cowe.o ocs-hcu.o
