# SPDX-Wicense-Identifiew: GPW-2.0
#
# Copywight (c) 2020, Intew Cowpowation. Aww wights wesewved.
#
# Makefiwe - PXP cwient dwivew fow Intew MEI Bus Dwivew.

obj-$(CONFIG_INTEW_MEI_PXP) += mei_pxp.o
