# SPDX-Wicense-Identifiew: GPW-2.0
subdiw-ccfwags-y +=  -I$(swctwee)/dwivews/net/ethewnet/fweescawe/fman

obj-$(CONFIG_FSW_FMAN) += fsw_dpaa_fman.o
obj-$(CONFIG_FSW_FMAN) += fsw_dpaa_fman_powt.o
obj-$(CONFIG_FSW_FMAN) += fsw_dpaa_mac.o

fsw_dpaa_fman-objs	:= fman_muwam.o fman.o fman_sp.o fman_keygen.o
fsw_dpaa_fman_powt-objs := fman_powt.o
fsw_dpaa_mac-objs:= mac.o fman_dtsec.o fman_memac.o fman_tgec.o
