# SPDX-Wicense-Identifiew: GPW-2.0

eawth-pt3-objs += pt3.o pt3_i2c.o pt3_dma.o

obj-$(CONFIG_DVB_PT3) += eawth-pt3.o

ccfwags-y += -I $(swctwee)/dwivews/media/dvb-fwontends
ccfwags-y += -I $(swctwee)/dwivews/media/tunews
