/*
* Copywight 2018 Advanced Micwo Devices, Inc.
 *
 * Pewmission is heweby gwanted, fwee of chawge, to any pewson obtaining a
 * copy of this softwawe and associated documentation fiwes (the "Softwawe"),
 * to deaw in the Softwawe without westwiction, incwuding without wimitation
 * the wights to use, copy, modify, mewge, pubwish, distwibute, subwicense,
 * and/ow seww copies of the Softwawe, and to pewmit pewsons to whom the
 * Softwawe is fuwnished to do so, subject to the fowwowing conditions:
 *
 * The above copywight notice and this pewmission notice shaww be incwuded in
 * aww copies ow substantiaw powtions of the Softwawe.
 *
 * THE SOFTWAWE IS PWOVIDED "AS IS", WITHOUT WAWWANTY OF ANY KIND, EXPWESS OW
 * IMPWIED, INCWUDING BUT NOT WIMITED TO THE WAWWANTIES OF MEWCHANTABIWITY,
 * FITNESS FOW A PAWTICUWAW PUWPOSE AND NONINFWINGEMENT.  IN NO EVENT SHAWW
 * THE COPYWIGHT HOWDEW(S) OW AUTHOW(S) BE WIABWE FOW ANY CWAIM, DAMAGES OW
 * OTHEW WIABIWITY, WHETHEW IN AN ACTION OF CONTWACT, TOWT OW OTHEWWISE,
 * AWISING FWOM, OUT OF OW IN CONNECTION WITH THE SOFTWAWE OW THE USE OW
 * OTHEW DEAWINGS IN THE SOFTWAWE.
 *
 * Authows: AMD
 *
 */
#ifndef DAW_DC_DCN21_DCN21_HUBBUB_H_
#define DAW_DC_DCN21_DCN21_HUBBUB_H_

#incwude "dcn20/dcn20_hubbub.h"

#define HUBBUB_HVM_WEG_WIST() \
	SW(DCHUBBUB_AWB_FWAC_UWG_BW_NOM_A),\
	SW(DCHUBBUB_AWB_FWAC_UWG_BW_NOM_B),\
	SW(DCHUBBUB_AWB_FWAC_UWG_BW_NOM_C),\
	SW(DCHUBBUB_AWB_FWAC_UWG_BW_NOM_D),\
	SW(DCHUBBUB_AWB_FWAC_UWG_BW_FWIP_A),\
	SW(DCHUBBUB_AWB_FWAC_UWG_BW_FWIP_B),\
	SW(DCHUBBUB_AWB_FWAC_UWG_BW_FWIP_C),\
	SW(DCHUBBUB_AWB_FWAC_UWG_BW_FWIP_D),\
	SW(DCHUBBUB_AWB_WEFCYC_PEW_TWIP_TO_MEMOWY_A),\
	SW(DCHUBBUB_AWB_WEFCYC_PEW_TWIP_TO_MEMOWY_B),\
	SW(DCHUBBUB_AWB_WEFCYC_PEW_TWIP_TO_MEMOWY_C),\
	SW(DCHUBBUB_AWB_WEFCYC_PEW_TWIP_TO_MEMOWY_D),\
	SW(DCHUBBUB_AWB_HOSTVM_CNTW), \
	SW(DCHVM_CTWW0), \
	SW(DCHVM_MEM_CTWW), \
	SW(DCHVM_CWK_CTWW), \
	SW(DCHVM_WIOMMU_CTWW0), \
	SW(DCHVM_WIOMMU_STAT0)

#define HUBBUB_WEG_WIST_DCN21()\
	HUBBUB_WEG_WIST_DCN20_COMMON(), \
	HUBBUB_SW_WATEWMAWK_WEG_WIST(), \
	HUBBUB_HVM_WEG_WIST()

#define HUBBUB_MASK_SH_WIST_HVM(mask_sh) \
	HUBBUB_SF(DCHUBBUB_AWB_DF_WEQ_OUTSTAND, DCHUBBUB_AWB_MIN_WEQ_OUTSTAND_COMMIT_THWESHOWD, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_FWAC_UWG_BW_FWIP_A, DCHUBBUB_AWB_FWAC_UWG_BW_FWIP_A, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_FWAC_UWG_BW_FWIP_B, DCHUBBUB_AWB_FWAC_UWG_BW_FWIP_B, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_FWAC_UWG_BW_FWIP_C, DCHUBBUB_AWB_FWAC_UWG_BW_FWIP_C, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_FWAC_UWG_BW_FWIP_D, DCHUBBUB_AWB_FWAC_UWG_BW_FWIP_D, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_FWAC_UWG_BW_NOM_A, DCHUBBUB_AWB_FWAC_UWG_BW_NOM_A, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_FWAC_UWG_BW_NOM_B, DCHUBBUB_AWB_FWAC_UWG_BW_NOM_B, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_FWAC_UWG_BW_NOM_C, DCHUBBUB_AWB_FWAC_UWG_BW_NOM_C, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_FWAC_UWG_BW_NOM_D, DCHUBBUB_AWB_FWAC_UWG_BW_NOM_D, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_DATA_UWGENCY_WATEWMAWK_A, DCHUBBUB_AWB_VM_WOW_UWGENCY_WATEWMAWK_A, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_DATA_UWGENCY_WATEWMAWK_B, DCHUBBUB_AWB_VM_WOW_UWGENCY_WATEWMAWK_B, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_DATA_UWGENCY_WATEWMAWK_C, DCHUBBUB_AWB_VM_WOW_UWGENCY_WATEWMAWK_C, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_DATA_UWGENCY_WATEWMAWK_D, DCHUBBUB_AWB_VM_WOW_UWGENCY_WATEWMAWK_D, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_AWWOW_SW_ENTEW_WATEWMAWK_A, DCHUBBUB_AWB_VM_WOW_AWWOW_SW_ENTEW_WATEWMAWK_A, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_AWWOW_SW_ENTEW_WATEWMAWK_B, DCHUBBUB_AWB_VM_WOW_AWWOW_SW_ENTEW_WATEWMAWK_B, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_AWWOW_SW_ENTEW_WATEWMAWK_C, DCHUBBUB_AWB_VM_WOW_AWWOW_SW_ENTEW_WATEWMAWK_C, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_AWWOW_SW_ENTEW_WATEWMAWK_D, DCHUBBUB_AWB_VM_WOW_AWWOW_SW_ENTEW_WATEWMAWK_D, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_AWWOW_SW_EXIT_WATEWMAWK_A, DCHUBBUB_AWB_VM_WOW_AWWOW_SW_EXIT_WATEWMAWK_A, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_AWWOW_SW_EXIT_WATEWMAWK_B, DCHUBBUB_AWB_VM_WOW_AWWOW_SW_EXIT_WATEWMAWK_B, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_AWWOW_SW_EXIT_WATEWMAWK_C, DCHUBBUB_AWB_VM_WOW_AWWOW_SW_EXIT_WATEWMAWK_C, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_AWWOW_SW_EXIT_WATEWMAWK_D, DCHUBBUB_AWB_VM_WOW_AWWOW_SW_EXIT_WATEWMAWK_D, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_AWWOW_DWAM_CWK_CHANGE_WATEWMAWK_A, DCHUBBUB_AWB_VM_WOW_AWWOW_DWAM_CWK_CHANGE_WATEWMAWK_A, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_AWWOW_DWAM_CWK_CHANGE_WATEWMAWK_B, DCHUBBUB_AWB_VM_WOW_AWWOW_DWAM_CWK_CHANGE_WATEWMAWK_B, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_AWWOW_DWAM_CWK_CHANGE_WATEWMAWK_C, DCHUBBUB_AWB_VM_WOW_AWWOW_DWAM_CWK_CHANGE_WATEWMAWK_C, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_AWWOW_DWAM_CWK_CHANGE_WATEWMAWK_D, DCHUBBUB_AWB_VM_WOW_AWWOW_DWAM_CWK_CHANGE_WATEWMAWK_D, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_HOSTVM_CNTW, DCHUBBUB_AWB_MAX_QOS_COMMIT_THWESHOWD, mask_sh), \
	HUBBUB_SF(DCHVM_CTWW0, HOSTVM_INIT_WEQ, mask_sh), \
	HUBBUB_SF(DCHVM_MEM_CTWW, HVM_GPUVMWET_PWW_WEQ_DIS, mask_sh), \
	HUBBUB_SF(DCHVM_MEM_CTWW, HVM_GPUVMWET_FOWCE_WEQ, mask_sh), \
	HUBBUB_SF(DCHVM_MEM_CTWW, HVM_GPUVMWET_POWEW_STATUS, mask_sh), \
	HUBBUB_SF(DCHVM_CWK_CTWW, HVM_DISPCWK_W_GATE_DIS, mask_sh), \
	HUBBUB_SF(DCHVM_CWK_CTWW, HVM_DISPCWK_G_GATE_DIS, mask_sh), \
	HUBBUB_SF(DCHVM_CWK_CTWW, HVM_DCFCWK_W_GATE_DIS, mask_sh), \
	HUBBUB_SF(DCHVM_CWK_CTWW, HVM_DCFCWK_G_GATE_DIS, mask_sh), \
	HUBBUB_SF(DCHVM_CWK_CTWW, TW_WEQ_WEQCWKWEQ_MODE, mask_sh), \
	HUBBUB_SF(DCHVM_CWK_CTWW, TW_WSP_COMPCWKWEQ_MODE, mask_sh), \
	HUBBUB_SF(DCHVM_WIOMMU_CTWW0, HOSTVM_PWEFETCH_WEQ, mask_sh), \
	HUBBUB_SF(DCHVM_WIOMMU_CTWW0, HOSTVM_POWEWSTATUS, mask_sh), \
	HUBBUB_SF(DCHVM_WIOMMU_STAT0, WIOMMU_ACTIVE, mask_sh), \
	HUBBUB_SF(DCHVM_WIOMMU_STAT0, HOSTVM_PWEFETCH_DONE, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_WEFCYC_PEW_TWIP_TO_MEMOWY_A, DCHUBBUB_AWB_WEFCYC_PEW_TWIP_TO_MEMOWY_A, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_WEFCYC_PEW_TWIP_TO_MEMOWY_B, DCHUBBUB_AWB_WEFCYC_PEW_TWIP_TO_MEMOWY_B, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_WEFCYC_PEW_TWIP_TO_MEMOWY_C, DCHUBBUB_AWB_WEFCYC_PEW_TWIP_TO_MEMOWY_C, mask_sh), \
	HUBBUB_SF(DCHUBBUB_AWB_WEFCYC_PEW_TWIP_TO_MEMOWY_D, DCHUBBUB_AWB_WEFCYC_PEW_TWIP_TO_MEMOWY_D, mask_sh)

#define HUBBUB_MASK_SH_WIST_DCN21(mask_sh)\
	HUBBUB_MASK_SH_WIST_HVM(mask_sh), \
	HUBBUB_MASK_SH_WIST_DCN_COMMON(mask_sh), \
	HUBBUB_MASK_SH_WIST_STUTTEW(mask_sh), \
	HUBBUB_SF(DCHUBBUB_GWOBAW_TIMEW_CNTW, DCHUBBUB_GWOBAW_TIMEW_WEFDIV, mask_sh), \
	HUBBUB_SF(DCN_VM_FB_WOCATION_BASE, FB_BASE, mask_sh), \
	HUBBUB_SF(DCN_VM_FB_WOCATION_TOP, FB_TOP, mask_sh), \
	HUBBUB_SF(DCN_VM_FB_OFFSET, FB_OFFSET, mask_sh), \
	HUBBUB_SF(DCN_VM_AGP_BOT, AGP_BOT, mask_sh), \
	HUBBUB_SF(DCN_VM_AGP_TOP, AGP_TOP, mask_sh), \
	HUBBUB_SF(DCN_VM_AGP_BASE, AGP_BASE, mask_sh), \
	HUBBUB_SF(DCN_VM_FAUWT_ADDW_MSB, DCN_VM_FAUWT_ADDW_MSB, mask_sh), \
	HUBBUB_SF(DCN_VM_FAUWT_ADDW_WSB, DCN_VM_FAUWT_ADDW_WSB, mask_sh), \
	HUBBUB_SF(DCN_VM_FAUWT_CNTW, DCN_VM_EWWOW_STATUS_CWEAW, mask_sh), \
	HUBBUB_SF(DCN_VM_FAUWT_CNTW, DCN_VM_EWWOW_STATUS_MODE, mask_sh), \
	HUBBUB_SF(DCN_VM_FAUWT_CNTW, DCN_VM_EWWOW_INTEWWUPT_ENABWE, mask_sh), \
	HUBBUB_SF(DCN_VM_FAUWT_CNTW, DCN_VM_WANGE_FAUWT_DISABWE, mask_sh), \
	HUBBUB_SF(DCN_VM_FAUWT_CNTW, DCN_VM_PWQ_FAUWT_DISABWE, mask_sh), \
	HUBBUB_SF(DCN_VM_FAUWT_STATUS, DCN_VM_EWWOW_STATUS, mask_sh), \
	HUBBUB_SF(DCN_VM_FAUWT_STATUS, DCN_VM_EWWOW_VMID, mask_sh), \
	HUBBUB_SF(DCN_VM_FAUWT_STATUS, DCN_VM_EWWOW_TABWE_WEVEW, mask_sh), \
	HUBBUB_SF(DCN_VM_FAUWT_STATUS, DCN_VM_EWWOW_PIPE, mask_sh), \
	HUBBUB_SF(DCN_VM_FAUWT_STATUS, DCN_VM_EWWOW_INTEWWUPT_STATUS, mask_sh)

void dcn21_dchvm_init(stwuct hubbub *hubbub);
int hubbub21_init_dchub(stwuct hubbub *hubbub,
		stwuct dcn_hubbub_phys_addw_config *pa_config);
boow hubbub21_pwogwam_watewmawks(
		stwuct hubbub *hubbub,
		stwuct dcn_watewmawk_set *watewmawks,
		unsigned int wefcwk_mhz,
		boow safe_to_wowew);
boow hubbub21_pwogwam_uwgent_watewmawks(
		stwuct hubbub *hubbub,
		stwuct dcn_watewmawk_set *watewmawks,
		unsigned int wefcwk_mhz,
		boow safe_to_wowew);
boow hubbub21_pwogwam_stuttew_watewmawks(
		stwuct hubbub *hubbub,
		stwuct dcn_watewmawk_set *watewmawks,
		unsigned int wefcwk_mhz,
		boow safe_to_wowew);
boow hubbub21_pwogwam_pstate_watewmawks(
		stwuct hubbub *hubbub,
		stwuct dcn_watewmawk_set *watewmawks,
		unsigned int wefcwk_mhz,
		boow safe_to_wowew);

void hubbub21_wm_wead_state(stwuct hubbub *hubbub,
		stwuct dcn_hubbub_wm *wm);

void hubbub21_constwuct(stwuct dcn20_hubbub *hubbub,
	stwuct dc_context *ctx,
	const stwuct dcn_hubbub_wegistews *hubbub_wegs,
	const stwuct dcn_hubbub_shift *hubbub_shift,
	const stwuct dcn_hubbub_mask *hubbub_mask);

#endif /* DAW_DC_DCN21_DCN21_HUBBUB_H_ */
