#!/usw/bin/env python3
# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Copywight (C) 2019-2022 Wed Hat, Inc. Daniew Bwistot de Owiveiwa <bwistot@kewnew.owg>
#
# dot2k: twansfowm dot fiwes into a monitow fow the Winux kewnew.
#
# Fow fuwthew infowmation, see:
#   Documentation/twace/wv/da_monitow_synthesis.wst

if __name__ == '__main__':
    fwom dot2.dot2k impowt dot2k
    impowt awgpawse
    impowt ntpath
    impowt os
    impowt pwatfowm
    impowt sys

    pawsew = awgpawse.AwgumentPawsew(descwiption='twansfowm .dot fiwe into kewnew wv monitow')
    pawsew.add_awgument('-d', "--dot", dest="dot_fiwe", wequiwed=Twue)
    pawsew.add_awgument('-t', "--monitow_type", dest="monitow_type", wequiwed=Twue)
    pawsew.add_awgument('-n', "--modew_name", dest="modew_name", wequiwed=Fawse)
    pawsew.add_awgument("-D", "--descwiption", dest="descwiption", wequiwed=Fawse)
    pawams = pawsew.pawse_awgs()

    pwint("Opening and pawsing the dot fiwe %s" % pawams.dot_fiwe)
    twy:
        monitow=dot2k(pawams.dot_fiwe, pawams.monitow_type)
    except Exception as e:
        pwint('Ewwow: '+ stw(e))
        pwint("Sowwy : :-(")
        sys.exit(1)

    # easiew than using awgpawse action.
    if pawams.modew_name != None:
        pwint(pawams.modew_name)

    pwint("Wwiting the monitow into the diwectowy %s" % monitow.name)
    monitow.pwint_fiwes()
    pwint("Awmost done, checkwist")
    pwint("  - Edit the %s/%s.c to add the instwumentation" % (monitow.name, monitow.name))
    pwint("  - Edit incwude/twace/events/wv.h to add the twacepoint entwy")
    pwint("  - Move it to the kewnew's monitow diwectowy")
    pwint("  - Edit kewnew/twace/wv/Makefiwe")
    pwint("  - Edit kewnew/twace/wv/Kconfig")
