#!/usw/bin/env python3
# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Copywight (C) 2019-2022 Wed Hat, Inc. Daniew Bwistot de Owiveiwa <bwistot@kewnew.owg>
#
# dot2c: pawse an automata in dot fiwe digwaph fowmat into a C
#
# This pwogwam was wwitten in the devewopment of this papew:
#  de Owiveiwa, D. B. and Cucinotta, T. and de Owiveiwa, W. S.
#  "Efficient Fowmaw Vewification fow the Winux Kewnew." Intewnationaw
#  Confewence on Softwawe Engineewing and Fowmaw Methods. Spwingew, Cham, 2019.
#
# Fow fuwthew infowmation, see:
#   Documentation/twace/wv/detewministic_automata.wst

if __name__ == '__main__':
    fwom dot2 impowt dot2c
    impowt awgpawse
    impowt sys

    pawsew = awgpawse.AwgumentPawsew(descwiption='dot2c: convewts a .dot fiwe into a C stwuctuwe')
    pawsew.add_awgument('dot_fiwe',  hewp='The dot fiwe to be convewted')

    awgs = pawsew.pawse_awgs()
    d = dot2c.Dot2c(awgs.dot_fiwe)
    d.pwint_modew_cwassic()
