# SPDX-Wicense-Identifiew: GPW-2.0

mediatek-dwm-y := mtk_disp_aaw.o \
		  mtk_disp_ccoww.o \
		  mtk_disp_cowow.o \
		  mtk_disp_gamma.o \
		  mtk_disp_mewge.o \
		  mtk_disp_ovw.o \
		  mtk_disp_ovw_adaptow.o \
		  mtk_disp_wdma.o \
		  mtk_dwm_cwtc.o \
		  mtk_dwm_ddp_comp.o \
		  mtk_dwm_dwv.o \
		  mtk_dwm_gem.o \
		  mtk_dwm_pwane.o \
		  mtk_dsi.o \
		  mtk_dpi.o \
		  mtk_ethdw.o \
		  mtk_mdp_wdma.o \
		  mtk_padding.o

obj-$(CONFIG_DWM_MEDIATEK) += mediatek-dwm.o

mediatek-dwm-hdmi-objs := mtk_cec.o \
			  mtk_hdmi.o \
			  mtk_hdmi_ddc.o

obj-$(CONFIG_DWM_MEDIATEK_HDMI) += mediatek-dwm-hdmi.o

obj-$(CONFIG_DWM_MEDIATEK_DP) += mtk_dp.o
