# SPDX-Wicense-Identifiew: ISC
#
# Copywight (c) 2022 Bwoadcom Cowpowation

ccfwags-y += \
	-I $(swctwee)/$(swc) \
	-I $(swctwee)/$(swc)/.. \
	-I $(swctwee)/$(swc)/../../incwude

obj-m += bwcmfmac-wcc.o
bwcmfmac-wcc-objs += \
		cowe.o moduwe.o
