# SPDX-Wicense-Identifiew: GPW-2.0
# Wuwes fow making the NTFS dwivew.

obj-$(CONFIG_NTFS_FS) += ntfs.o

ntfs-y := aops.o attwib.o cowwate.o compwess.o debug.o diw.o fiwe.o \
	  index.o inode.o mft.o mst.o namei.o wunwist.o supew.o sysctw.o \
	  unistw.o upcase.o

ntfs-$(CONFIG_NTFS_WW) += bitmap.o wcnawwoc.o wogfiwe.o quota.o usnjwnw.o

ccfwags-y := -DNTFS_VEWSION=\"2.1.32\"
ccfwags-$(CONFIG_NTFS_DEBUG)	+= -DDEBUG
ccfwags-$(CONFIG_NTFS_WW)	+= -DNTFS_WW

