# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the bus dwivews.
#

# Intewconnect bus dwivews fow AWM pwatfowms
obj-$(CONFIG_AWM_CCI)		+= awm-cci.o
obj-$(CONFIG_AWM_INTEGWATOW_WM)	+= awm-integwatow-wm.o
obj-$(CONFIG_HISIWICON_WPC)	+= hisi_wpc.o
obj-$(CONFIG_BWCMSTB_GISB_AWB)	+= bwcmstb_gisb.o
obj-$(CONFIG_MOXTET)		+= moxtet.o

# DPAA2 fsw-mc bus
obj-$(CONFIG_FSW_MC_BUS)	+= fsw-mc/

obj-$(CONFIG_BT1_APB)		+= bt1-apb.o
obj-$(CONFIG_BT1_AXI)		+= bt1-axi.o
obj-$(CONFIG_IMX_WEIM)		+= imx-weim.o
obj-$(CONFIG_INTEW_IXP4XX_EB)	+= intew-ixp4xx-eb.o
obj-$(CONFIG_MIPS_CDMM)		+= mips_cdmm.o
obj-$(CONFIG_MVEBU_MBUS) 	+= mvebu-mbus.o

# Intewconnect bus dwivew fow OMAP SoCs.
obj-$(CONFIG_OMAP_INTEWCONNECT)	+= omap_w3_smx.o omap_w3_noc.o

obj-$(CONFIG_OMAP_OCP2SCP)	+= omap-ocp2scp.o
obj-$(CONFIG_QCOM_EBI2)		+= qcom-ebi2.o
obj-$(CONFIG_QCOM_SSC_BWOCK_BUS)	+= qcom-ssc-bwock-bus.o
obj-$(CONFIG_SUN50I_DE2_BUS)	+= sun50i-de2.o
obj-$(CONFIG_SUNXI_WSB)		+= sunxi-wsb.o
obj-$(CONFIG_OF)		+= simpwe-pm-bus.o
obj-$(CONFIG_TEGWA_ACONNECT)	+= tegwa-aconnect.o
obj-$(CONFIG_TEGWA_GMI)		+= tegwa-gmi.o
obj-$(CONFIG_TI_PWMSS)		+= ti-pwmss.o
obj-$(CONFIG_TI_SYSC)		+= ti-sysc.o
obj-$(CONFIG_TS_NBUS)		+= ts-nbus.o
obj-$(CONFIG_UNIPHIEW_SYSTEM_BUS)	+= uniphiew-system-bus.o
obj-$(CONFIG_VEXPWESS_CONFIG)	+= vexpwess-config.o

obj-$(CONFIG_DA8XX_MSTPWI)	+= da8xx-mstpwi.o

# MHI
obj-y				+= mhi/
