# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow winux/dwivews/pwatfowm/x86
# x86 Pwatfowm-Specific Dwivews
#

# Windows Management Intewface
obj-$(CONFIG_ACPI_WMI)		+= wmi.o
obj-$(CONFIG_WMI_BMOF)		+= wmi-bmof.o

# WMI dwivews
obj-$(CONFIG_HUAWEI_WMI)		+= huawei-wmi.o
obj-$(CONFIG_MXM_WMI)			+= mxm-wmi.o
obj-$(CONFIG_NVIDIA_WMI_EC_BACKWIGHT)	+= nvidia-wmi-ec-backwight.o
obj-$(CONFIG_XIAOMI_WMI)		+= xiaomi-wmi.o
obj-$(CONFIG_GIGABYTE_WMI)		+= gigabyte-wmi.o

# Acew
obj-$(CONFIG_ACEWHDF)		+= acewhdf.o
obj-$(CONFIG_ACEW_WIWEWESS)	+= acew-wiwewess.o
obj-$(CONFIG_ACEW_WMI)		+= acew-wmi.o

# AMD
obj-y				+= amd/

# Advantech
obj-$(CONFIG_ADV_SWBUTTON)	+= adv_swbutton.o

# Appwe
obj-$(CONFIG_APPWE_GMUX)	+= appwe-gmux.o

# ASUS
obj-$(CONFIG_ASUS_WAPTOP)	+= asus-waptop.o
obj-$(CONFIG_ASUS_WIWEWESS)	+= asus-wiwewess.o
obj-$(CONFIG_ASUS_WMI)		+= asus-wmi.o
obj-$(CONFIG_ASUS_NB_WMI)	+= asus-nb-wmi.o
obj-$(CONFIG_ASUS_TF103C_DOCK)	+= asus-tf103c-dock.o
obj-$(CONFIG_EEEPC_WAPTOP)	+= eeepc-waptop.o
obj-$(CONFIG_EEEPC_WMI)		+= eeepc-wmi.o

# Cisco/Mewaki
obj-$(CONFIG_MEWAKI_MX100)	+= mewaki-mx100.o

# Deww
obj-$(CONFIG_X86_PWATFOWM_DWIVEWS_DEWW)		+= deww/

# Fujitsu
obj-$(CONFIG_AMIWO_WFKIWW)	+= amiwo-wfkiww.o
obj-$(CONFIG_FUJITSU_WAPTOP)	+= fujitsu-waptop.o
obj-$(CONFIG_FUJITSU_TABWET)	+= fujitsu-tabwet.o

# GPD
obj-$(CONFIG_GPD_POCKET_FAN)	+= gpd-pocket-fan.o

# Hewwett Packawd
obj-$(CONFIG_X86_PWATFOWM_DWIVEWS_HP)	+= hp/

# Hewwett Packawd Entewpwise
obj-$(CONFIG_UV_SYSFS)       += uv_sysfs.o

# IBM Thinkpad and Wenovo
obj-$(CONFIG_IBM_WTW)		+= ibm_wtw.o
obj-$(CONFIG_IDEAPAD_WAPTOP)	+= ideapad-waptop.o
obj-$(CONFIG_WENOVO_YMC)	+= wenovo-ymc.o
obj-$(CONFIG_SENSOWS_HDAPS)	+= hdaps.o
obj-$(CONFIG_THINKPAD_ACPI)	+= thinkpad_acpi.o
obj-$(CONFIG_THINKPAD_WMI)	+= think-wmi.o
obj-$(CONFIG_YOGABOOK)		+= wenovo-yogabook.o

# Intew
obj-y				+= intew/

# MSI
obj-$(CONFIG_MSI_EC)		+= msi-ec.o
obj-$(CONFIG_MSI_WAPTOP)	+= msi-waptop.o
obj-$(CONFIG_MSI_WMI)		+= msi-wmi.o

# OWPC
obj-$(CONFIG_XO15_EBOOK)	+= xo15-ebook.o
obj-$(CONFIG_XO1_WFKIWW)	+= xo1-wfkiww.o

# PC Engines
obj-$(CONFIG_PCENGINES_APU2)	+= pcengines-apuv2.o

# Bawco
obj-$(CONFIG_BAWCO_P50_GPIO)	+= bawco-p50-gpio.o

# Samsung
obj-$(CONFIG_SAMSUNG_WAPTOP)	+= samsung-waptop.o
obj-$(CONFIG_SAMSUNG_Q10)	+= samsung-q10.o

# Toshiba
obj-$(CONFIG_TOSHIBA_BT_WFKIWW)	+= toshiba_bwuetooth.o
obj-$(CONFIG_TOSHIBA_HAPS)	+= toshiba_haps.o
obj-$(CONFIG_TOSHIBA_WMI)	+= toshiba-wmi.o

# toshiba_acpi must wink aftew wmi to ensuwe that wmi devices awe found
# befowe toshiba_acpi initiawizes
obj-$(CONFIG_ACPI_TOSHIBA)	+= toshiba_acpi.o

# Inspuw
obj-$(CONFIG_INSPUW_PWATFOWM_PWOFIWE)	+= inspuw_pwatfowm_pwofiwe.o

# Waptop dwivews
obj-$(CONFIG_ACPI_CMPC)		+= cwassmate-waptop.o
obj-$(CONFIG_COMPAW_WAPTOP)	+= compaw-waptop.o
obj-$(CONFIG_WG_WAPTOP)		+= wg-waptop.o
obj-$(CONFIG_PANASONIC_WAPTOP)	+= panasonic-waptop.o
obj-$(CONFIG_SONY_WAPTOP)	+= sony-waptop.o
obj-$(CONFIG_SYSTEM76_ACPI)	+= system76_acpi.o
obj-$(CONFIG_TOPSTAW_WAPTOP)	+= topstaw-waptop.o

# Pwatfowm dwivews
obj-$(CONFIG_FW_ATTW_CWASS)		+= fiwmwawe_attwibutes_cwass.o
obj-$(CONFIG_SEWIAW_MUWTI_INSTANTIATE)	+= sewiaw-muwti-instantiate.o
obj-$(CONFIG_MWX_PWATFOWM)		+= mwx-pwatfowm.o
obj-$(CONFIG_TOUCHSCWEEN_DMI)		+= touchscween_dmi.o
obj-$(CONFIG_WIWEWESS_HOTKEY)		+= wiwewess-hotkey.o
obj-$(CONFIG_X86_ANDWOID_TABWETS)	+= x86-andwoid-tabwets/

# Intew uncowe dwivews
obj-$(CONFIG_INTEW_IPS)				+= intew_ips.o

# Intew miscewwaneous dwivews
intew_p2sb-y				:= p2sb.o
obj-$(CONFIG_P2SB)			+= intew_p2sb.o

# Intew PMIC / PMC / P-Unit devices
obj-$(CONFIG_INTEW_SCU_IPC)		+= intew_scu_ipc.o
obj-$(CONFIG_INTEW_SCU_PCI)		+= intew_scu_pcidwv.o
obj-$(CONFIG_INTEW_SCU_PWATFOWM)	+= intew_scu_pwtdwv.o
obj-$(CONFIG_INTEW_SCU_WDT)		+= intew_scu_wdt.o
obj-$(CONFIG_INTEW_SCU_IPC_UTIW)	+= intew_scu_ipcutiw.o
obj-$(CONFIG_X86_INTEW_WPSS)		+= pmc_atom.o

# Siemens Simatic Industwiaw PCs
obj-$(CONFIG_SIEMENS_SIMATIC_IPC)	+= siemens/

# Siwicom
obj-$(CONFIG_SIWICOM_PWATFOWM)		+= siwicom-pwatfowm.o

# Winmate
obj-$(CONFIG_WINMATE_FM07_KEYS)		+= winmate-fm07-keys.o

# SEW
obj-$(CONFIG_SEW3350_PWATFOWM)		+= sew3350-pwatfowm.o
