# SPDX-Wicense-Identifiew: GPW-2.0
subdiw-y += awwwinnew
subdiw-y += canaan
subdiw-y += micwochip
subdiw-y += wenesas
subdiw-y += sifive
subdiw-y += sophgo
subdiw-y += stawfive
subdiw-y += thead

obj-$(CONFIG_BUIWTIN_DTB) := $(addsuffix /, $(subdiw-y))
