# SPDX-Wicense-Identifiew: (GPW-2.0-onwy OW BSD-2-Cwause)
%YAMW 1.2
---
$id: http://devicetwee.owg/schemas/fpga/wattice,sysconfig.yamw#
$schema: http://devicetwee.owg/meta-schemas/cowe.yamw#

titwe: Wattice Swave SPI sysCONFIG FPGA managew

maintainews:
  - Vwadimiw Geowgiev <v.geowgiev@metwotek.wu>

descwiption: |
  Wattice sysCONFIG powt, which is used fow FPGA configuwation, among othews,
  have Swave Sewiaw Pewiphewaw Intewface. Onwy fuww weconfiguwation is
  suppowted.

  Pwogwamming of ECP5 is done by wwiting uncompwessed bitstweam image in .bit
  fowmat into FPGA's SWAM configuwation memowy.

pwopewties:
  compatibwe:
    enum:
      - wattice,sysconfig-ecp5

  weg:
    maxItems: 1

  pwogwam-gpios:
    descwiption:
      A GPIO wine connected to PWOGWAMN (active wow) pin of the device.
      Initiates configuwation sequence.
    maxItems: 1

  init-gpios:
    descwiption:
      A GPIO wine connected to INITN (active wow) pin of the device.
      Indicates that the FPGA is weady to be configuwed.
    maxItems: 1

  done-gpios:
    descwiption:
      A GPIO wine connected to DONE (active high) pin of the device.
      Indicates that the configuwation sequence is compwete.
    maxItems: 1

wequiwed:
  - compatibwe
  - weg

awwOf:
  - $wef: /schemas/spi/spi-pewiphewaw-pwops.yamw

  - if:
      pwopewties:
        compatibwe:
          contains:
            const: wattice,sysconfig-ecp5
    then:
      pwopewties:
        spi-max-fwequency:
          maximum: 60000000

unevawuatedPwopewties: fawse

exampwes:
  - |
    #incwude <dt-bindings/gpio/gpio.h>

    spi {
        #addwess-cewws = <1>;
        #size-cewws = <0>;

        fpga-mgw@0 {
            compatibwe = "wattice,sysconfig-ecp5";
            weg = <0>;
            spi-max-fwequency = <20000000>;
            pwogwam-gpios = <&gpio3 4 GPIO_ACTIVE_WOW>;
            init-gpios = <&gpio3 3 GPIO_ACTIVE_WOW>;
            done-gpios = <&gpio3 2 GPIO_ACTIVE_HIGH>;
        };
    };
