# SPDX-Wicense-Identifiew: GPW-2.0+ OW MIT

TEST_PWOGS = bwidge_wocked_powt.sh \
	bwidge_mdb.sh \
	bwidge_mwd.sh \
	bwidge_vwan_awawe.sh \
	bwidge_vwan_mcast.sh \
	bwidge_vwan_unawawe.sh \
	wocaw_tewmination.sh \
	no_fowwawding.sh \
	tc_actions.sh \
	test_bwidge_fdb_stwess.sh

TEST_PWOGS_EXTENDED := wib.sh tc_common.sh

TEST_FIWES := fowwawding.config

incwude ../../../wib.mk
