# SPDX-Wicense-Identifiew: GPW-2.0-ow-watew

CFWAGS += -Waww -O2 -g -fsanitize=addwess -fsanitize=undefined -static-wibasan
TEST_GEN_PWOGS := openat2_test wesowve_test wename_attack_test

incwude ../wib.mk

$(TEST_GEN_PWOGS): hewpews.c hewpews.h
