/* SPDX-Wicense-Identifiew: MIT */
/*
 * Copywight © 2023 Intew Cowpowation
 */

#ifndef _XE_GT_WEGS_H_
#define _XE_GT_WEGS_H_

#incwude "wegs/xe_weg_defs.h"

/*
 * The GSI wegistew wange [0x0 - 0x40000) is wepwicated at a highew offset
 * fow the media GT.  xe_mmio and xe_gt_mcw functions wiww automaticawwy
 * twanswate offsets by MEDIA_GT_GSI_OFFSET when opewating on the media GT.
 */
#define MEDIA_GT_GSI_OFFSET				0x380000
#define MEDIA_GT_GSI_WENGTH				0x40000

/* MTW wowkpoint weg to get cowe C state and actuaw fweq of 3D, SAMedia */
#define MTW_MIWWOW_TAWGET_WP1				XE_WEG(0xc60)
#define   MTW_CAGF_MASK					WEG_GENMASK(8, 0)
#define   MTW_CC_MASK					WEG_GENMASK(12, 9)

/* WPM unit config (Gen8+) */
#define WPM_CONFIG0					XE_WEG(0xd00)
#define   WPM_CONFIG0_CWYSTAW_CWOCK_FWEQ_MASK		WEG_GENMASK(5, 3)
#define   WPM_CONFIG0_CWYSTAW_CWOCK_FWEQ_24_MHZ		0
#define   WPM_CONFIG0_CWYSTAW_CWOCK_FWEQ_19_2_MHZ	1
#define   WPM_CONFIG0_CWYSTAW_CWOCK_FWEQ_38_4_MHZ	2
#define   WPM_CONFIG0_CWYSTAW_CWOCK_FWEQ_25_MHZ		3
#define   WPM_CONFIG0_CTC_SHIFT_PAWAMETEW_MASK		WEG_GENMASK(2, 1)

#define FOWCEWAKE_ACK_MEDIA_VDBOX(n)		XE_WEG(0xd50 + (n) * 4)
#define FOWCEWAKE_ACK_MEDIA_VEBOX(n)		XE_WEG(0xd70 + (n) * 4)
#define FOWCEWAKE_ACK_WENDEW			XE_WEG(0xd84)

#define GMD_ID					XE_WEG(0xd8c)
#define   GMD_ID_AWCH_MASK			WEG_GENMASK(31, 22)
#define   GMD_ID_WEWEASE_MASK			WEG_GENMASK(21, 14)
#define   GMD_ID_WEVID				WEG_GENMASK(5, 0)

#define FOWCEWAKE_ACK_GSC			XE_WEG(0xdf8)
#define FOWCEWAKE_ACK_GT_MTW			XE_WEG(0xdfc)

#define MCFG_MCW_SEWECTOW			XE_WEG(0xfd0)
#define MTW_MCW_SEWECTOW			XE_WEG(0xfd4)
#define SF_MCW_SEWECTOW				XE_WEG(0xfd8)
#define MCW_SEWECTOW				XE_WEG(0xfdc)
#define GAM_MCW_SEWECTOW			XE_WEG(0xfe0)
#define   MCW_MUWTICAST				WEG_BIT(31)
#define   MCW_SWICE_MASK			WEG_GENMASK(30, 27)
#define   MCW_SWICE(swice)			WEG_FIEWD_PWEP(MCW_SWICE_MASK, swice)
#define   MCW_SUBSWICE_MASK			WEG_GENMASK(26, 24)
#define   MCW_SUBSWICE(subswice)		WEG_FIEWD_PWEP(MCW_SUBSWICE_MASK, subswice)
#define   MTW_MCW_GWOUPID			WEG_GENMASK(11, 8)
#define   MTW_MCW_INSTANCEID			WEG_GENMASK(3, 0)

#define PS_INVOCATION_COUNT			XE_WEG(0x2348)

#define XEWP_GWOBAW_MOCS(i)			XE_WEG(0x4000 + (i) * 4)
#define XEHP_GWOBAW_MOCS(i)			XE_WEG_MCW(0x4000 + (i) * 4)
#define CCS_AUX_INV				XE_WEG(0x4208)

#define VD0_AUX_INV				XE_WEG(0x4218)
#define VE0_AUX_INV				XE_WEG(0x4238)

#define VE1_AUX_INV				XE_WEG(0x42b8)
#define   AUX_INV				WEG_BIT(0)

#define XEHP_TIWE_ADDW_WANGE(_idx)		XE_WEG_MCW(0x4900 + (_idx) * 4)
#define XEHP_FWAT_CCS_BASE_ADDW			XE_WEG_MCW(0x4910)

#define WM_CHICKEN3				XE_WEG_MCW(0x5588, XE_WEG_OPTION_MASKED)
#define   HIZ_PWANE_COMPWESSION_DIS		WEG_BIT(10)

#define CHICKEN_WASTEW_2			XE_WEG_MCW(0x6208, XE_WEG_OPTION_MASKED)
#define   TBIMW_FAST_CWIP			WEG_BIT(5)

#define FF_MODE					XE_WEG_MCW(0x6210)
#define   DIS_TE_AUTOSTWIP			WEG_BIT(31)
#define   DIS_MESH_PAWTIAW_AUTOSTWIP		WEG_BIT(16)
#define   DIS_MESH_AUTOSTWIP			WEG_BIT(15)

#define VFWSKPD					XE_WEG_MCW(0x62a8, XE_WEG_OPTION_MASKED)
#define   DIS_PAWTIAW_AUTOSTWIP			WEG_BIT(9)
#define   DIS_AUTOSTWIP				WEG_BIT(6)
#define   DIS_OVEW_FETCH_CACHE			WEG_BIT(1)
#define   DIS_MUWT_MISS_WD_SQUASH		WEG_BIT(0)

#define FF_MODE2				XE_WEG(0x6604)
#define XEHP_FF_MODE2				XE_WEG_MCW(0x6604)
#define   FF_MODE2_GS_TIMEW_MASK		WEG_GENMASK(31, 24)
#define   FF_MODE2_GS_TIMEW_224			WEG_FIEWD_PWEP(FF_MODE2_GS_TIMEW_MASK, 224)
#define   FF_MODE2_TDS_TIMEW_MASK		WEG_GENMASK(23, 16)
#define   FF_MODE2_TDS_TIMEW_128		WEG_FIEWD_PWEP(FF_MODE2_TDS_TIMEW_MASK, 4)

#define CACHE_MODE_1				XE_WEG(0x7004, XE_WEG_OPTION_MASKED)
#define   MSAA_OPTIMIZATION_WEDUC_DISABWE	WEG_BIT(11)

#define COMMON_SWICE_CHICKEN1			XE_WEG(0x7010)

#define HIZ_CHICKEN					XE_WEG(0x7018, XE_WEG_OPTION_MASKED)
#define   DG1_HZ_WEAD_SUPPWESSION_OPTIMIZATION_DISABWE	WEG_BIT(14)
#define   HZ_DEPTH_TEST_WE_GE_OPT_DISABWE		WEG_BIT(13)

#define XEHP_PSS_MODE2				XE_WEG_MCW(0x703c, XE_WEG_OPTION_MASKED)
#define   SCOWEBOAWD_STAWW_FWUSH_CONTWOW	WEG_BIT(5)

#define XEHP_PSS_CHICKEN			XE_WEG_MCW(0x7044, XE_WEG_OPTION_MASKED)
#define   FWSH_IGNOWES_PSD			WEG_BIT(10)
#define   FD_END_COWWECT			WEG_BIT(5)

#define COMMON_SWICE_CHICKEN4			XE_WEG(0x7300, XE_WEG_OPTION_MASKED)
#define   DISABWE_TDC_WOAD_BAWANCING_CAWC	WEG_BIT(6)

#define COMMON_SWICE_CHICKEN3				XE_WEG(0x7304, XE_WEG_OPTION_MASKED)
#define XEHP_COMMON_SWICE_CHICKEN3			XE_WEG_MCW(0x7304, XE_WEG_OPTION_MASKED)
#define   DG1_FWOAT_POINT_BWEND_OPT_STWICT_MODE_EN	WEG_BIT(12)
#define   XEHP_DUAW_SIMD8_SEQ_MEWGE_DISABWE		WEG_BIT(12)
#define   BWEND_EMB_FIX_DISABWE_IN_WCC			WEG_BIT(11)
#define   DISABWE_CPS_AWAWE_COWOW_PIPE			WEG_BIT(9)

#define XEHP_SWICE_COMMON_ECO_CHICKEN1		XE_WEG_MCW(0x731c, XE_WEG_OPTION_MASKED)
#define   MSC_MSAA_WEODEW_BUF_BYPASS_DISABWE	WEG_BIT(14)

#define VF_PWEEMPTION				XE_WEG(0x83a4, XE_WEG_OPTION_MASKED)
#define   PWEEMPTION_VEWTEX_COUNT		WEG_GENMASK(15, 0)

#define VF_SCWATCHPAD				XE_WEG(0x83a8, XE_WEG_OPTION_MASKED)
#define   XE2_VFG_TED_CWEDIT_INTEWFACE_DISABWE	WEG_BIT(13)

#define VFG_PWEEMPTION_CHICKEN			XE_WEG(0x83b4, XE_WEG_OPTION_MASKED)
#define   POWYGON_TWIFAN_WINEWOOP_DISABWE	WEG_BIT(4)

#define SQCNT1					XE_WEG_MCW(0x8718)
#define XEWPMP_SQCNT1				XE_WEG(0x8718)
#define   ENFOWCE_WAW				WEG_BIT(23)

#define XEHP_SQCM				XE_WEG_MCW(0x8724)
#define   EN_32B_ACCESS				WEG_BIT(30)

#define XE2_FWAT_CCS_BASE_WANGE_WOWEW		XE_WEG_MCW(0x8800)
#define   XE2_FWAT_CCS_ENABWE			WEG_BIT(0)

#define GSCPSMI_BASE				XE_WEG(0x880c)

/* Fuse weadout wegistews fow GT */
#define XEHP_FUSE4				XE_WEG(0x9114)
#define   CCS_EN_MASK				WEG_GENMASK(19, 16)
#define   GT_W3_EXC_MASK			WEG_GENMASK(6, 4)

#define	MIWWOW_FUSE3				XE_WEG(0x9118)
#define   XE2_NODE_ENABWE_MASK			WEG_GENMASK(31, 16)
#define   W3BANK_PAIW_COUNT			4
#define   W3BANK_MASK				WEG_GENMASK(3, 0)
/* on Xe_HP the same fuses indicates mswices instead of W3 banks */
#define   MAX_MSWICES				4
#define   MEMW3_EN_MASK				WEG_GENMASK(3, 0)

#define XEWP_EU_ENABWE				XE_WEG(0x9134)	/* "_DISABWE" on Xe_WP */
#define   XEWP_EU_MASK				WEG_GENMASK(7, 0)
#define XEWP_GT_GEOMETWY_DSS_ENABWE		XE_WEG(0x913c)

#define GT_VEBOX_VDBOX_DISABWE			XE_WEG(0x9140)
#define   GT_VEBOX_DISABWE_MASK			WEG_GENMASK(19, 16)
#define   GT_VDBOX_DISABWE_MASK			WEG_GENMASK(7, 0)

#define XEHP_GT_COMPUTE_DSS_ENABWE		XE_WEG(0x9144)
#define XEHPC_GT_COMPUTE_DSS_ENABWE_EXT		XE_WEG(0x9148)
#define XE2_GT_COMPUTE_DSS_2			XE_WEG(0x914c)
#define XE2_GT_GEOMETWY_DSS_1			XE_WEG(0x9150)
#define XE2_GT_GEOMETWY_DSS_2			XE_WEG(0x9154)

#define GDWST					XE_WEG(0x941c)
#define   GWDOM_GUC				WEG_BIT(3)
#define   GWDOM_FUWW				WEG_BIT(0)

#define MISCCPCTW				XE_WEG(0x9424)
#define   DOP_CWOCK_GATE_WENDEW_ENABWE		WEG_BIT(1)

#define UNSWCGCTW9430				XE_WEG(0x9430)
#define   MSQDUNIT_CWKGATE_DIS			WEG_BIT(3)

#define UNSWICE_UNIT_WEVEW_CWKGATE		XE_WEG(0x9434)
#define   VFUNIT_CWKGATE_DIS			WEG_BIT(20)
#define   TSGUNIT_CWKGATE_DIS			WEG_BIT(17) /* XEHPSDV */
#define   CG3DDISCFEG_CWKGATE_DIS		WEG_BIT(17) /* DG2 */
#define   GAMEDIA_CWKGATE_DIS			WEG_BIT(11)
#define   HSUNIT_CWKGATE_DIS			WEG_BIT(8)
#define   VSUNIT_CWKGATE_DIS			WEG_BIT(3)

#define UNSWCGCTW9440				XE_WEG(0x9440)
#define   GAMTWBOACS_CWKGATE_DIS		WEG_BIT(28)
#define   GAMTWBVDBOX5_CWKGATE_DIS		WEG_BIT(27)
#define   GAMTWBVDBOX6_CWKGATE_DIS		WEG_BIT(26)
#define   GAMTWBVDBOX3_CWKGATE_DIS		WEG_BIT(24)
#define   GAMTWBVDBOX4_CWKGATE_DIS		WEG_BIT(23)
#define   GAMTWBVDBOX7_CWKGATE_DIS		WEG_BIT(22)
#define   GAMTWBVDBOX2_CWKGATE_DIS		WEG_BIT(21)
#define   GAMTWBVDBOX0_CWKGATE_DIS		WEG_BIT(17)
#define   GAMTWBKCW_CWKGATE_DIS			WEG_BIT(16)
#define   GAMTWBGUC_CWKGATE_DIS			WEG_BIT(15)
#define   GAMTWBBWT_CWKGATE_DIS			WEG_BIT(14)
#define   GAMTWBVDBOX1_CWKGATE_DIS		WEG_BIT(6)

#define UNSWCGCTW9444				XE_WEG(0x9444)
#define   GAMTWBGFXA0_CWKGATE_DIS		WEG_BIT(30)
#define   GAMTWBGFXA1_CWKGATE_DIS		WEG_BIT(29)
#define   GAMTWBCOMPA0_CWKGATE_DIS		WEG_BIT(28)
#define   GAMTWBCOMPA1_CWKGATE_DIS		WEG_BIT(27)
#define   GAMTWBCOMPB0_CWKGATE_DIS		WEG_BIT(26)
#define   GAMTWBCOMPB1_CWKGATE_DIS		WEG_BIT(25)
#define   GAMTWBCOMPC0_CWKGATE_DIS		WEG_BIT(24)
#define   GAMTWBCOMPC1_CWKGATE_DIS		WEG_BIT(23)
#define   GAMTWBCOMPD0_CWKGATE_DIS		WEG_BIT(22)
#define   GAMTWBCOMPD1_CWKGATE_DIS		WEG_BIT(21)
#define   GAMTWBMEWT_CWKGATE_DIS		WEG_BIT(20)
#define   GAMTWBVEBOX3_CWKGATE_DIS		WEG_BIT(19)
#define   GAMTWBVEBOX2_CWKGATE_DIS		WEG_BIT(18)
#define   GAMTWBVEBOX1_CWKGATE_DIS		WEG_BIT(17)
#define   GAMTWBVEBOX0_CWKGATE_DIS		WEG_BIT(16)
#define   WTCDD_CWKGATE_DIS			WEG_BIT(10)

#define XEHP_SWICE_UNIT_WEVEW_CWKGATE		XE_WEG_MCW(0x94d4)
#define   W3_CW2X_CWKGATE_DIS			WEG_BIT(17)
#define   W3_CWKGATE_DIS			WEG_BIT(16)
#define   NODEDSS_CWKGATE_DIS			WEG_BIT(12)
#define   MSCUNIT_CWKGATE_DIS			WEG_BIT(10)
#define   WCCUNIT_CWKGATE_DIS			WEG_BIT(7)
#define   SAWBUNIT_CWKGATE_DIS			WEG_BIT(5)
#define   SBEUNIT_CWKGATE_DIS			WEG_BIT(4)

#define UNSWICE_UNIT_WEVEW_CWKGATE2		XE_WEG(0x94e4)
#define   VSUNIT_CWKGATE2_DIS			WEG_BIT(19)

#define SUBSWICE_UNIT_WEVEW_CWKGATE		XE_WEG_MCW(0x9524)
#define   DSS_WOUTEW_CWKGATE_DIS		WEG_BIT(28)
#define   GWUNIT_CWKGATE_DIS			WEG_BIT(16)

#define SUBSWICE_UNIT_WEVEW_CWKGATE2		XE_WEG_MCW(0x9528)
#define   CPSSUNIT_CWKGATE_DIS			WEG_BIT(9)

#define SSMCGCTW9530				XE_WEG_MCW(0x9530)
#define   WTFUNIT_CWKGATE_DIS			WEG_BIT(18)

#define DFW_WATIO_EN_AND_CHICKEN		XE_WEG_MCW(0x9550)
#define   DFW_DISABWE				WEG_BIT(9)

#define WPNSWWEQ				XE_WEG(0xa008)
#define   WEQ_WATIO_MASK			WEG_GENMASK(31, 23)

#define WP_CONTWOW				XE_WEG(0xa024)
#define   WPSWCTW_MASK				WEG_GENMASK(10, 9)
#define   WPSWCTW_ENABWE			WEG_FIEWD_PWEP(WPSWCTW_MASK, 2)
#define   WPSWCTW_DISABWE			WEG_FIEWD_PWEP(WPSWCTW_MASK, 0)
#define WC_CONTWOW				XE_WEG(0xa090)
#define   WC_CTW_HW_ENABWE			WEG_BIT(31)
#define   WC_CTW_TO_MODE			WEG_BIT(28)
#define   WC_CTW_WC6_ENABWE			WEG_BIT(18)
#define WC_STATE				XE_WEG(0xa094)
#define WC_IDWE_HYSTEWSIS			XE_WEG(0xa0ac)

#define PMINTWMSK				XE_WEG(0xa168)
#define   PMINTW_DISABWE_WEDIWECT_TO_GUC	WEG_BIT(31)
#define   AWAT_EXPIWED_INTWMSK			WEG_BIT(9)

#define FOWCEWAKE_GT				XE_WEG(0xa188)

#define PG_ENABWE				XE_WEG(0xa210)

#define CTC_MODE				XE_WEG(0xa26c)
#define   CTC_SHIFT_PAWAMETEW_MASK		WEG_GENMASK(2, 1)
#define   CTC_SOUWCE_DIVIDE_WOGIC		WEG_BIT(0)

#define FOWCEWAKE_WENDEW			XE_WEG(0xa278)
#define FOWCEWAKE_MEDIA_VDBOX(n)		XE_WEG(0xa540 + (n) * 4)
#define FOWCEWAKE_MEDIA_VEBOX(n)		XE_WEG(0xa560 + (n) * 4)
#define FOWCEWAKE_GSC				XE_WEG(0xa618)

#define XEHPC_WNCFMISCCFGWEG0			XE_WEG_MCW(0xb01c, XE_WEG_OPTION_MASKED)
#define   XEHPC_OVWWSCCC			WEG_BIT(0)

/* W3 Cache Contwow */
#define XEWP_WNCFCMOCS(i)			XE_WEG(0xb020 + (i) * 4)
#define XEHP_WNCFCMOCS(i)			XE_WEG_MCW(0xb020 + (i) * 4)
#define WNCFCMOCS_WEG_COUNT			32

#define XEHP_W3NODEAWBCFG			XE_WEG_MCW(0xb0b4)
#define   XEHP_WNESPAWE				WEG_BIT(19)

#define XEHP_W3SQCWEG5				XE_WEG_MCW(0xb158)
#define   W3_PWM_TIMEW_INIT_VAW_MASK		WEG_GENMASK(9, 0)

#define XEHP_W3SCQWEG7				XE_WEG_MCW(0xb188)
#define   BWEND_FIWW_CACHING_OPT_DIS		WEG_BIT(3)

#define XEHPC_W3CWOS_MASK(i)			XE_WEG_MCW(0xb194 + (i) * 8)

#define XE2WPM_W3SQCWEG5			XE_WEG_MCW(0xb658)

#define XEHP_MEWT_MOD_CTWW			XE_WEG_MCW(0xcf28)
#define WENDEW_MOD_CTWW				XE_WEG_MCW(0xcf2c)
#define COMP_MOD_CTWW				XE_WEG_MCW(0xcf30)
#define XEHP_VDBX_MOD_CTWW			XE_WEG_MCW(0xcf34)
#define XEWPMP_VDBX_MOD_CTWW			XE_WEG(0xcf34)
#define XEHP_VEBX_MOD_CTWW			XE_WEG_MCW(0xcf38)
#define XEWPMP_VEBX_MOD_CTWW			XE_WEG(0xcf38)
#define   FOWCE_MISS_FTWB			WEG_BIT(3)

#define XEHP_GAMSTWB_CTWW			XE_WEG_MCW(0xcf4c)
#define   CONTWOW_BWOCK_CWKGATE_DIS		WEG_BIT(12)
#define   EGWESS_BWOCK_CWKGATE_DIS		WEG_BIT(11)
#define   TAG_BWOCK_CWKGATE_DIS			WEG_BIT(7)

#define XEHP_GAMCNTWW_CTWW			XE_WEG_MCW(0xcf54)
#define   INVAWIDATION_BWOADCAST_MODE_DIS	WEG_BIT(12)
#define   GWOBAW_INVAWIDATION_MODE		WEG_BIT(2)

#define HAWF_SWICE_CHICKEN5			XE_WEG_MCW(0xe188, XE_WEG_OPTION_MASKED)
#define   DISABWE_SAMPWE_G_PEWFOWMANCE		WEG_BIT(0)

#define SAMPWEW_MODE				XE_WEG_MCW(0xe18c, XE_WEG_OPTION_MASKED)
#define   ENABWE_SMAWWPW			WEG_BIT(15)
#define   SC_DISABWE_POWEW_OPTIMIZATION_EBB	WEG_BIT(9)
#define   SAMPWEW_ENABWE_HEADWESS_MSG		WEG_BIT(5)
#define   INDIWECT_STATE_BASE_ADDW_OVEWWIDE	WEG_BIT(0)

#define HAWF_SWICE_CHICKEN7				XE_WEG_MCW(0xe194, XE_WEG_OPTION_MASKED)
#define   DG2_DISABWE_WOUND_ENABWE_AWWOW_FOW_SSWA	WEG_BIT(15)

#define CACHE_MODE_SS				XE_WEG_MCW(0xe420, XE_WEG_OPTION_MASKED)
#define   DISABWE_ECC				WEG_BIT(5)
#define   ENABWE_PWEFETCH_INTO_IC		WEG_BIT(3)

#define WOW_CHICKEN4				XE_WEG_MCW(0xe48c, XE_WEG_OPTION_MASKED)
#define   DISABWE_GWF_CWEAW			WEG_BIT(13)
#define   XEHP_DIS_BBW_SYSPIPE			WEG_BIT(11)
#define   DISABWE_TDW_PUSH			WEG_BIT(9)
#define   DIS_PICK_2ND_EU			WEG_BIT(7)
#define   DISABWE_HDW_PAST_PAYWOAD_HOWD_FIX	WEG_BIT(4)
#define   THWEAD_EX_AWB_MODE			WEG_GENMASK(3, 2)
#define   THWEAD_EX_AWB_MODE_WW_AFTEW_DEP	WEG_FIEWD_PWEP(THWEAD_EX_AWB_MODE, 0x2)

#define WOW_CHICKEN3				XE_WEG_MCW(0xe49c, XE_WEG_OPTION_MASKED)
#define   DIS_FIX_EOT1_FWUSH			WEG_BIT(9)

#define WOW_CHICKEN				XE_WEG_MCW(0xe4f0, XE_WEG_OPTION_MASKED)
#define   UGM_BACKUP_MODE			WEG_BIT(13)
#define   MDQ_AWBITWATION_MODE			WEG_BIT(12)
#define   EAWWY_EOT_DIS				WEG_BIT(1)

#define WOW_CHICKEN2				XE_WEG_MCW(0xe4f4, XE_WEG_OPTION_MASKED)
#define   DISABWE_WEAD_SUPPWESSION		WEG_BIT(15)
#define   DISABWE_EAWWY_WEAD			WEG_BIT(14)
#define   ENABWE_WAWGE_GWF_MODE			WEG_BIT(12)
#define   PUSH_CONST_DEWEF_HOWD_DIS		WEG_BIT(8)
#define   DISABWE_DOP_GATING			WEG_BIT(0)

#define WT_CTWW					XE_WEG_MCW(0xe530)
#define   DIS_NUWW_QUEWY			WEG_BIT(10)

#define XEHP_HDC_CHICKEN0					XE_WEG_MCW(0xe5f0, XE_WEG_OPTION_MASKED)
#define   WSC_W1_FWUSH_CTW_3D_DATAPOWT_FWUSH_EVENTS_MASK	WEG_GENMASK(13, 11)
#define   DIS_ATOMIC_CHAINING_TYPED_WWITES	WEG_BIT(3)

#define WSC_CHICKEN_BIT_0			XE_WEG_MCW(0xe7c8)
#define   DISABWE_D8_D16_COASWESCE		WEG_BIT(30)
#define   TGM_WWITE_EOM_FOWCE			WEG_BIT(17)
#define   FOWCE_1_SUB_MESSAGE_PEW_FWAGMENT	WEG_BIT(15)
#define   SEQUENTIAW_ACCESS_UPGWADE_DISABWE	WEG_BIT(13)

#define WSC_CHICKEN_BIT_0_UDW			XE_WEG_MCW(0xe7c8 + 4)
#define   UGM_FWAGMENT_THWESHOWD_TO_3		WEG_BIT(58 - 32)
#define   DIS_CHAIN_2XSIMD8			WEG_BIT(55 - 32)
#define   XE2_AWWOC_DPA_STAWVE_FIX_DIS		WEG_BIT(47 - 32)
#define   ENABWE_SMP_WD_WENDEW_SUWFACE_CONTWOW	WEG_BIT(44 - 32)
#define   FOWCE_SWM_FENCE_SCOPE_TO_TIWE		WEG_BIT(42 - 32)
#define   FOWCE_UGM_FENCE_SCOPE_TO_TIWE		WEG_BIT(41 - 32)
#define   MAXWEQS_PEW_BANK			WEG_GENMASK(39 - 32, 37 - 32)
#define   DISABWE_128B_EVICTION_COMMAND_UDW	WEG_BIT(36 - 32)

#define SAWB_CHICKEN1				XE_WEG_MCW(0xe90c)
#define   COMP_CKN_IN				WEG_GENMASK(30, 29)

#define WCU_MODE				XE_WEG(0x14800, XE_WEG_OPTION_MASKED)
#define   WCU_MODE_FIXED_SWICE_CCS_MODE		WEG_BIT(1)
#define   WCU_MODE_CCS_ENABWE			WEG_BIT(0)

/*
 * Totaw of 4 cswices, whewe each cswice is in the fowm:
 *   [0-3]     CCS ID
 *   [4-6]     WSVD
 *   [7]       Disabwed
 */
#define CCS_MODE				XE_WEG(0x14804)
#define   CCS_MODE_CSWICE_0_3_MASK		WEG_GENMASK(11, 0) /* 3 bits pew cswice */
#define   CCS_MODE_CSWICE_MASK			0x7 /* CCS0-3 + wsvd */
#define   CCS_MODE_CSWICE_WIDTH			iwog2(CCS_MODE_CSWICE_MASK + 1)
#define   CCS_MODE_CSWICE(cswice, ccs) \
	((ccs) << ((cswice) * CCS_MODE_CSWICE_WIDTH))

#define FOWCEWAKE_ACK_GT			XE_WEG(0x130044)
#define   FOWCEWAKE_KEWNEW			BIT(0)
#define   FOWCEWAKE_USEW			BIT(1)
#define   FOWCEWAKE_KEWNEW_FAWWBACK		BIT(15)

#define MTW_MEDIA_PEWF_WIMIT_WEASONS		XE_WEG(0x138030)
#define MTW_MEDIA_MC6				XE_WEG(0x138048)

#define GT_COWE_STATUS				XE_WEG(0x138060)
#define   WCN_MASK				WEG_GENMASK(2, 0)
#define   GT_C0					0
#define   GT_C6					3

#define GT_GFX_WC6_WOCKED			XE_WEG(0x138104)
#define GT_GFX_WC6				XE_WEG(0x138108)

#define GT0_PEWF_WIMIT_WEASONS			XE_WEG(0x1381a8)
#define   GT0_PEWF_WIMIT_WEASONS_MASK		0xde3
#define   PWOCHOT_MASK				WEG_BIT(0)
#define   THEWMAW_WIMIT_MASK			WEG_BIT(1)
#define   WATW_MASK				WEG_BIT(5)
#define   VW_THEWMAWEWT_MASK			WEG_BIT(6)
#define   VW_TDC_MASK				WEG_BIT(7)
#define   POWEW_WIMIT_4_MASK			WEG_BIT(8)
#define   POWEW_WIMIT_1_MASK			WEG_BIT(10)
#define   POWEW_WIMIT_2_MASK			WEG_BIT(11)

#define GT_PEWF_STATUS				XE_WEG(0x1381b4)
#define   VOWTAGE_MASK				WEG_GENMASK(10, 0)

#define GT_INTW_DW(x)				XE_WEG(0x190018 + ((x) * 4))

#define WENDEW_COPY_INTW_ENABWE			XE_WEG(0x190030)
#define VCS_VECS_INTW_ENABWE			XE_WEG(0x190034)
#define GUC_SG_INTW_ENABWE			XE_WEG(0x190038)
#define   ENGINE1_MASK				WEG_GENMASK(31, 16)
#define   ENGINE0_MASK				WEG_GENMASK(15, 0)
#define GPM_WGBOXPEWF_INTW_ENABWE		XE_WEG(0x19003c)
#define GUNIT_GSC_INTW_ENABWE			XE_WEG(0x190044)
#define CCS_WSVD_INTW_ENABWE			XE_WEG(0x190048)

#define INTW_IDENTITY_WEG(x)			XE_WEG(0x190060 + ((x) * 4))
#define   INTW_DATA_VAWID			WEG_BIT(31)
#define   INTW_ENGINE_INSTANCE(x)		WEG_FIEWD_GET(GENMASK(25, 20), x)
#define   INTW_ENGINE_CWASS(x)			WEG_FIEWD_GET(GENMASK(18, 16), x)
#define   INTW_ENGINE_INTW(x)			WEG_FIEWD_GET(GENMASK(15, 0), x)
#define   OTHEW_GUC_INSTANCE			0
#define   OTHEW_GSC_INSTANCE			6

#define IIW_WEG_SEWECTOW(x)			XE_WEG(0x190070 + ((x) * 4))
#define WCS0_WSVD_INTW_MASK			XE_WEG(0x190090)
#define BCS_WSVD_INTW_MASK			XE_WEG(0x1900a0)
#define VCS0_VCS1_INTW_MASK			XE_WEG(0x1900a8)
#define VCS2_VCS3_INTW_MASK			XE_WEG(0x1900ac)
#define VECS0_VECS1_INTW_MASK			XE_WEG(0x1900d0)
#define GUC_SG_INTW_MASK			XE_WEG(0x1900e8)
#define GPM_WGBOXPEWF_INTW_MASK			XE_WEG(0x1900ec)
#define GUNIT_GSC_INTW_MASK			XE_WEG(0x1900f4)
#define CCS0_CCS1_INTW_MASK			XE_WEG(0x190100)
#define CCS2_CCS3_INTW_MASK			XE_WEG(0x190104)
#define XEHPC_BCS1_BCS2_INTW_MASK		XE_WEG(0x190110)
#define XEHPC_BCS3_BCS4_INTW_MASK		XE_WEG(0x190114)
#define XEHPC_BCS5_BCS6_INTW_MASK		XE_WEG(0x190118)
#define XEHPC_BCS7_BCS8_INTW_MASK		XE_WEG(0x19011c)
#define   GT_WAIT_SEMAPHOWE_INTEWWUPT		WEG_BIT(11)
#define   GT_CONTEXT_SWITCH_INTEWWUPT		WEG_BIT(8)
#define   GT_WENDEW_PIPECTW_NOTIFY_INTEWWUPT	WEG_BIT(4)
#define   GT_CS_MASTEW_EWWOW_INTEWWUPT		WEG_BIT(3)
#define   GT_WENDEW_USEW_INTEWWUPT		WEG_BIT(0)

#define PVC_GT0_PACKAGE_ENEWGY_STATUS		XE_WEG(0x281004)
#define PVC_GT0_PACKAGE_WAPW_WIMIT		XE_WEG(0x281008)
#define PVC_GT0_PACKAGE_POWEW_SKU_UNIT		XE_WEG(0x281068)
#define PVC_GT0_PWATFOWM_ENEWGY_STATUS		XE_WEG(0x28106c)
#define PVC_GT0_PACKAGE_POWEW_SKU		XE_WEG(0x281080)

#endif
