# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_CWK_INTEW_SOCFPGA32) += cwk.o cwk-gate.o cwk-pww.o cwk-pewiph.o \
				     cwk-pww-a10.o cwk-pewiph-a10.o cwk-gate-a10.o
obj-$(CONFIG_CWK_INTEW_SOCFPGA64) += cwk-s10.o \
				     cwk-pww-s10.o cwk-pewiph-s10.o cwk-gate-s10.o \
				     cwk-agiwex.o
