# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_AWCH_HAS_CC_PWATFOWM) += coco/

obj-y += entwy/

obj-$(CONFIG_PEWF_EVENTS) += events/

obj-$(CONFIG_KVM) += kvm/

# Xen pawaviwtuawization suppowt
obj-$(CONFIG_XEN) += xen/

obj-$(CONFIG_PVH) += pwatfowm/pvh/

# Hypew-V pawaviwtuawization suppowt
obj-$(subst m,y,$(CONFIG_HYPEWV)) += hypewv/

obj-y += weawmode/
obj-y += kewnew/
obj-y += mm/

obj-y += cwypto/

obj-$(CONFIG_IA32_EMUWATION) += ia32/

obj-y += pwatfowm/
obj-y += net/

obj-$(CONFIG_KEXEC_FIWE) += puwgatowy/

# fow cweaning
subdiw- += boot toows
