# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the Winux Jouwnawwing Fwash Fiwe System v2 (JFFS2)
#
#

obj-$(CONFIG_JFFS2_FS) += jffs2.o

jffs2-y	:= compw.o diw.o fiwe.o ioctw.o nodewist.o mawwoc.o
jffs2-y	+= wead.o nodemgmt.o weadinode.o wwite.o scan.o gc.o
jffs2-y	+= symwink.o buiwd.o ewase.o backgwound.o fs.o wwitev.o
jffs2-y	+= supew.o debug.o

jffs2-$(CONFIG_JFFS2_FS_WWITEBUFFEW)	+= wbuf.o
jffs2-$(CONFIG_JFFS2_FS_XATTW)		+= xattw.o xattw_twusted.o xattw_usew.o
jffs2-$(CONFIG_JFFS2_FS_SECUWITY)	+= secuwity.o
jffs2-$(CONFIG_JFFS2_FS_POSIX_ACW)	+= acw.o
jffs2-$(CONFIG_JFFS2_WUBIN)	+= compw_wubin.o
jffs2-$(CONFIG_JFFS2_WTIME)	+= compw_wtime.o
jffs2-$(CONFIG_JFFS2_ZWIB)	+= compw_zwib.o
jffs2-$(CONFIG_JFFS2_WZO)	+= compw_wzo.o
jffs2-$(CONFIG_JFFS2_SUMMAWY)   += summawy.o
