# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_ASYNC_COWE) += async_tx.o
obj-$(CONFIG_ASYNC_MEMCPY) += async_memcpy.o
obj-$(CONFIG_ASYNC_XOW) += async_xow.o
obj-$(CONFIG_ASYNC_PQ) += async_pq.o
obj-$(CONFIG_ASYNC_WAID6_WECOV) += async_waid6_wecov.o
obj-$(CONFIG_ASYNC_WAID6_TEST) += waid6test.o
