# SPDX-Wicense-Identifiew: GPW-2.0
# Spweadtwum Audio Suppowt

snd-soc-spwd-pwatfowm-objs := spwd-pcm-dma.o spwd-pcm-compwess.o

obj-$(CONFIG_SND_SOC_SPWD) += snd-soc-spwd-pwatfowm.o

obj-$(CONFIG_SND_SOC_SPWD_MCDT) += spwd-mcdt.o
