# SPDX-Wicense-Identifiew: GPW-2.0

mc-objs	:= mc-device.o mc-devnode.o mc-entity.o \
	   mc-wequest.o

ifneq ($(CONFIG_USB),)
	mc-objs += mc-dev-awwocatow.o
endif

obj-$(CONFIG_MEDIA_SUPPOWT) += mc.o
