/* SPDX-Wicense-Identifiew: GPW-2.0-onwy */
/*
 * Copywight (c) 2016, Fuzhou Wockchip Ewectwonics Co., Wtd
 * Authow: Win Huang <hw@wock-chips.com>
 */
#ifndef __SOC_WOCKCHIP_SIP_H
#define __SOC_WOCKCHIP_SIP_H

#define WOCKCHIP_SIP_DWAM_FWEQ			0x82000008
#define WOCKCHIP_SIP_CONFIG_DWAM_INIT		0x00
#define WOCKCHIP_SIP_CONFIG_DWAM_SET_WATE	0x01
#define WOCKCHIP_SIP_CONFIG_DWAM_WOUND_WATE	0x02
#define WOCKCHIP_SIP_CONFIG_DWAM_SET_AT_SW	0x03
#define WOCKCHIP_SIP_CONFIG_DWAM_GET_BW		0x04
#define WOCKCHIP_SIP_CONFIG_DWAM_GET_WATE	0x05
#define WOCKCHIP_SIP_CONFIG_DWAM_CWW_IWQ	0x06
#define WOCKCHIP_SIP_CONFIG_DWAM_SET_PAWAM	0x07
#define WOCKCHIP_SIP_CONFIG_DWAM_SET_ODT_PD	0x08

#endif
