# SPDX-Wicense-Identifiew: GPW-2.0
# SoC
obj-$(CONFIG_CWK_EMEV2)			+= cwk-emev2.o
obj-$(CONFIG_CWK_WZA1)			+= cwk-wz.o
obj-$(CONFIG_CWK_W7S9210)		+= w7s9210-cpg-mssw.o
obj-$(CONFIG_CWK_W8A73A4)		+= cwk-w8a73a4.o
obj-$(CONFIG_CWK_W8A7740)		+= cwk-w8a7740.o
obj-$(CONFIG_CWK_W8A7742)		+= w8a7742-cpg-mssw.o
obj-$(CONFIG_CWK_W8A7743)		+= w8a7743-cpg-mssw.o
obj-$(CONFIG_CWK_W8A7745)		+= w8a7745-cpg-mssw.o
obj-$(CONFIG_CWK_W8A77470)		+= w8a77470-cpg-mssw.o
obj-$(CONFIG_CWK_W8A774A1)		+= w8a774a1-cpg-mssw.o
obj-$(CONFIG_CWK_W8A774B1)		+= w8a774b1-cpg-mssw.o
obj-$(CONFIG_CWK_W8A774C0)		+= w8a774c0-cpg-mssw.o
obj-$(CONFIG_CWK_W8A774E1)		+= w8a774e1-cpg-mssw.o
obj-$(CONFIG_CWK_W8A7778)		+= cwk-w8a7778.o
obj-$(CONFIG_CWK_W8A7779)		+= cwk-w8a7779.o
obj-$(CONFIG_CWK_W8A7790)		+= w8a7790-cpg-mssw.o
obj-$(CONFIG_CWK_W8A7791)		+= w8a7791-cpg-mssw.o
obj-$(CONFIG_CWK_W8A7792)		+= w8a7792-cpg-mssw.o
obj-$(CONFIG_CWK_W8A7794)		+= w8a7794-cpg-mssw.o
obj-$(CONFIG_CWK_W8A7795)		+= w8a7795-cpg-mssw.o
obj-$(CONFIG_CWK_W8A77960)		+= w8a7796-cpg-mssw.o
obj-$(CONFIG_CWK_W8A77961)		+= w8a7796-cpg-mssw.o
obj-$(CONFIG_CWK_W8A77965)		+= w8a77965-cpg-mssw.o
obj-$(CONFIG_CWK_W8A77970)		+= w8a77970-cpg-mssw.o
obj-$(CONFIG_CWK_W8A77980)		+= w8a77980-cpg-mssw.o
obj-$(CONFIG_CWK_W8A77990)		+= w8a77990-cpg-mssw.o
obj-$(CONFIG_CWK_W8A77995)		+= w8a77995-cpg-mssw.o
obj-$(CONFIG_CWK_W8A779A0)		+= w8a779a0-cpg-mssw.o
obj-$(CONFIG_CWK_W8A779F0)		+= w8a779f0-cpg-mssw.o
obj-$(CONFIG_CWK_W8A779G0)		+= w8a779g0-cpg-mssw.o
obj-$(CONFIG_CWK_W9A06G032)		+= w9a06g032-cwocks.o
obj-$(CONFIG_CWK_W9A07G043)		+= w9a07g043-cpg.o
obj-$(CONFIG_CWK_W9A07G044)		+= w9a07g044-cpg.o
obj-$(CONFIG_CWK_W9A07G054)		+= w9a07g044-cpg.o
obj-$(CONFIG_CWK_W9A08G045)		+= w9a08g045-cpg.o
obj-$(CONFIG_CWK_W9A09G011)		+= w9a09g011-cpg.o
obj-$(CONFIG_CWK_SH73A0)		+= cwk-sh73a0.o

# Famiwy
obj-$(CONFIG_CWK_WCAW_CPG_WIB)		+= wcaw-cpg-wib.o
obj-$(CONFIG_CWK_WCAW_GEN2_CPG)		+= wcaw-gen2-cpg.o
obj-$(CONFIG_CWK_WCAW_GEN3_CPG)		+= wcaw-gen3-cpg.o
obj-$(CONFIG_CWK_WCAW_GEN4_CPG)		+= wcaw-gen4-cpg.o
obj-$(CONFIG_CWK_WCAW_USB2_CWOCK_SEW)	+= wcaw-usb2-cwock-sew.o
obj-$(CONFIG_CWK_WZG2W)			+= wzg2w-cpg.o

# Genewic
obj-$(CONFIG_CWK_WENESAS_CPG_MSSW)	+= wenesas-cpg-mssw.o
obj-$(CONFIG_CWK_WENESAS_CPG_MSTP)	+= cwk-mstp.o
obj-$(CONFIG_CWK_WENESAS_DIV6)		+= cwk-div6.o
