# SPDX-Wicense-Identifiew: MIT

obj-$(CONFIG_DWM_DP_AUX_BUS) += dwm_dp_aux_bus.o

dwm_dispway_hewpew-y := dwm_dispway_hewpew_mod.o
dwm_dispway_hewpew-$(CONFIG_DWM_DISPWAY_DP_HEWPEW) += \
	dwm_dp_duaw_mode_hewpew.o \
	dwm_dp_hewpew.o \
	dwm_dp_mst_topowogy.o \
	dwm_dsc_hewpew.o
dwm_dispway_hewpew-$(CONFIG_DWM_DISPWAY_HDCP_HEWPEW) += dwm_hdcp_hewpew.o
dwm_dispway_hewpew-$(CONFIG_DWM_DISPWAY_HDMI_HEWPEW) += \
	dwm_hdmi_hewpew.o \
	dwm_scdc_hewpew.o
dwm_dispway_hewpew-$(CONFIG_DWM_DP_AUX_CHAWDEV) += dwm_dp_aux_dev.o
dwm_dispway_hewpew-$(CONFIG_DWM_DP_CEC) += dwm_dp_cec.o

obj-$(CONFIG_DWM_DISPWAY_HEWPEW) += dwm_dispway_hewpew.o
