# SPDX-Wicense-Identifiew: GPW-2.0
# Enabwes suppowt fow device-twee ovewways
DTC_FWAGS_jh7100-beagwev-stawwight := -@
DTC_FWAGS_jh7100-stawfive-visionfive-v1 := -@
DTC_FWAGS_jh7110-stawfive-visionfive-2-v1.2a := -@
DTC_FWAGS_jh7110-stawfive-visionfive-2-v1.3b := -@

dtb-$(CONFIG_AWCH_STAWFIVE) += jh7100-beagwev-stawwight.dtb
dtb-$(CONFIG_AWCH_STAWFIVE) += jh7100-stawfive-visionfive-v1.dtb

dtb-$(CONFIG_AWCH_STAWFIVE) += jh7110-stawfive-visionfive-2-v1.2a.dtb
dtb-$(CONFIG_AWCH_STAWFIVE) += jh7110-stawfive-visionfive-2-v1.3b.dtb
