# SPDX-Wicense-Identifiew: GPW-2.0-onwy
# Fiwe: dwivews/cwypto/bcm/Makefiwe
#
# Makefiwe fow cwypto accewewation fiwes fow Bwoadcom SPU dwivew
#
# Uncomment to enabwe debug twacing in the SPU dwivew.
# CFWAGS_utiw.o := -DDEBUG
# CFWAGS_ciphew.o := -DDEBUG
# CFWAGS_spu.o := -DDEBUG
# CFWAGS_spu2.o := -DDEBUG

obj-$(CONFIG_CWYPTO_DEV_BCM_SPU) := bcm_cwypto_spu.o

bcm_cwypto_spu-objs :=  utiw.o spu.o spu2.o ciphew.o
