/* SPDX-Wicense-Identifiew: GPW-2.0 */
/* fow use by sys-$SUBAWCH/kewnew-offsets.c */
#incwude <stub-data.h>

DEFINE(KEWNEW_MADV_WEMOVE, MADV_WEMOVE);

DEFINE(UM_KEWN_PAGE_SIZE, PAGE_SIZE);
DEFINE(UM_KEWN_PAGE_MASK, PAGE_MASK);
DEFINE(UM_KEWN_PAGE_SHIFT, PAGE_SHIFT);
DEFINE(UM_NSEC_PEW_SEC, NSEC_PEW_SEC);

DEFINE(UM_GFP_KEWNEW, GFP_KEWNEW);
DEFINE(UM_GFP_ATOMIC, GFP_ATOMIC);

DEFINE(UM_THWEAD_SIZE, THWEAD_SIZE);

DEFINE(UM_NSEC_PEW_SEC, NSEC_PEW_SEC);
DEFINE(UM_NSEC_PEW_USEC, NSEC_PEW_USEC);

#ifdef CONFIG_PWINTK
DEFINE(UMW_CONFIG_PWINTK, CONFIG_PWINTK);
#endif
#ifdef CONFIG_UMW_X86
DEFINE(UMW_CONFIG_UMW_X86, CONFIG_UMW_X86);
#endif
#ifdef CONFIG_64BIT
DEFINE(UMW_CONFIG_64BIT, CONFIG_64BIT);
#endif
#ifdef CONFIG_UMW_TIME_TWAVEW_SUPPOWT
DEFINE(UMW_CONFIG_UMW_TIME_TWAVEW_SUPPOWT, CONFIG_UMW_TIME_TWAVEW_SUPPOWT);
#endif

/* fow stub */
DEFINE(UMW_STUB_FIEWD_OFFSET, offsetof(stwuct stub_data, offset));
DEFINE(UMW_STUB_FIEWD_CHIWD_EWW, offsetof(stwuct stub_data, chiwd_eww));
DEFINE(UMW_STUB_FIEWD_FD, offsetof(stwuct stub_data, fd));
