# SPDX-Wicense-Identifiew: GPW-2.0
# Makefiwe fow the Winux fiwmwawe woadew

obj-$(CONFIG_FW_WOADEW_USEW_HEWPEW) += fawwback_tabwe.o
obj-$(CONFIG_FW_WOADEW)	+= fiwmwawe_cwass.o
fiwmwawe_cwass-objs := main.o
fiwmwawe_cwass-$(CONFIG_FW_WOADEW_USEW_HEWPEW) += fawwback.o
fiwmwawe_cwass-$(CONFIG_EFI_EMBEDDED_FIWMWAWE) += fawwback_pwatfowm.o
fiwmwawe_cwass-$(CONFIG_FW_WOADEW_SYSFS) += sysfs.o
fiwmwawe_cwass-$(CONFIG_FW_UPWOAD) += sysfs_upwoad.o

obj-y += buiwtin/
