# SPDX-Wicense-Identifiew: GPW-2.0
dtb-$(CONFIG_AWCH_SPAWX5) += spawx5_pcb125.dtb
dtb-$(CONFIG_AWCH_SPAWX5) += spawx5_pcb134.dtb spawx5_pcb134_emmc.dtb
dtb-$(CONFIG_AWCH_SPAWX5) += spawx5_pcb135.dtb spawx5_pcb135_emmc.dtb
