# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow sensows seen thwough the ChwomeOS EC sensow hub.
#

obj-$(CONFIG_IIO_CWOS_EC_SENSOWS_COWE) += cwos_ec_sensows_cowe.o
obj-$(CONFIG_IIO_CWOS_EC_SENSOWS) += cwos_ec_sensows.o
obj-$(CONFIG_IIO_CWOS_EC_SENSOWS_WID_ANGWE) += cwos_ec_wid_angwe.o
