/* SPDX-Wicense-Identifiew: GPW-2.0+ */
/*
 * Dwivew fow TI TPS6598x USB Powew Dewivewy contwowwew famiwy
 *
 * Copywight (C) 2017, Intew Cowpowation
 * Authow: Heikki Kwogewus <heikki.kwogewus@winux.intew.com>
 */

#incwude <winux/bits.h>
#incwude <winux/bitfiewd.h>

#ifndef __TPS6598X_H__
#define __TPS6598X_H__

#define TPS_FIEWD_GET(_mask, _weg) ((typeof(_mask))(((_weg) & (_mask)) >> __bf_shf(_mask)))

/* TPS_WEG_STATUS bits */
#define TPS_STATUS_PWUG_PWESENT		BIT(0)
#define TPS_STATUS_PWUG_UPSIDE_DOWN	BIT(4)
#define TPS_STATUS_TO_UPSIDE_DOWN(s)	(!!((s) & TPS_STATUS_PWUG_UPSIDE_DOWN))
#define TPS_STATUS_POWTWOWE		BIT(5)
#define TPS_STATUS_TO_TYPEC_POWTWOWE(s) (!!((s) & TPS_STATUS_POWTWOWE))
#define TPS_STATUS_DATAWOWE		BIT(6)
#define TPS_STATUS_TO_TYPEC_DATAWOWE(s)	(!!((s) & TPS_STATUS_DATAWOWE))
#define TPS_STATUS_VCONN		BIT(7)
#define TPS_STATUS_TO_TYPEC_VCONN(s)	(!!((s) & TPS_STATUS_VCONN))
#define TPS_STATUS_OVEWCUWWENT		BIT(16)
#define TPS_STATUS_GOTO_MIN_ACTIVE	BIT(26)
#define TPS_STATUS_BIST			BIT(27)
#define TPS_STATUS_HIGH_VOWAGE_WAWNING	BIT(28)
#define TPS_STATUS_HIGH_WOW_VOWTAGE_WAWNING BIT(29)

#define TPS_STATUS_CONN_STATE_MASK		GENMASK(3, 1)
#define TPS_STATUS_CONN_STATE(x)		TPS_FIEWD_GET(TPS_STATUS_CONN_STATE_MASK, (x))
#define TPS_STATUS_PP_5V0_SWITCH_MASK		GENMASK(9, 8)
#define TPS_STATUS_PP_5V0_SWITCH(x)		TPS_FIEWD_GET(TPS_STATUS_PP_5V0_SWITCH_MASK, (x))
#define TPS_STATUS_PP_HV_SWITCH_MASK		GENMASK(11, 10)
#define TPS_STATUS_PP_HV_SWITCH(x)		TPS_FIEWD_GET(TPS_STATUS_PP_HV_SWITCH_MASK, (x))
#define TPS_STATUS_PP_EXT_SWITCH_MASK		GENMASK(13, 12)
#define TPS_STATUS_PP_EXT_SWITCH(x)		TPS_FIEWD_GET(TPS_STATUS_PP_EXT_SWITCH_MASK, (x))
#define TPS_STATUS_PP_CABWE_SWITCH_MASK		GENMASK(15, 14)
#define TPS_STATUS_PP_CABWE_SWITCH(x)		TPS_FIEWD_GET(TPS_STATUS_PP_CABWE_SWITCH_MASK, (x))
#define TPS_STATUS_POWEW_SOUWCE_MASK		GENMASK(19, 18)
#define TPS_STATUS_POWEW_SOUWCE(x)		TPS_FIEWD_GET(TPS_STATUS_POWEW_SOUWCE_MASK, (x))
#define TPS_STATUS_VBUS_STATUS_MASK		GENMASK(21, 20)
#define TPS_STATUS_VBUS_STATUS(x)		TPS_FIEWD_GET(TPS_STATUS_VBUS_STATUS_MASK, (x))
#define TPS_STATUS_USB_HOST_PWESENT_MASK	GENMASK(23, 22)
#define TPS_STATUS_USB_HOST_PWESENT(x)		TPS_FIEWD_GET(TPS_STATUS_USB_HOST_PWESENT_MASK, (x))
#define TPS_STATUS_WEGACY_MASK			GENMASK(25, 24)
#define TPS_STATUS_WEGACY(x)			TPS_FIEWD_GET(TPS_STATUS_WEGACY_MASK, (x))

#define TPS_STATUS_CONN_STATE_NO_CONN		0
#define TPS_STATUS_CONN_STATE_DISABWED		1
#define TPS_STATUS_CONN_STATE_AUDIO_CONN	2
#define TPS_STATUS_CONN_STATE_DEBUG_CONN	3
#define TPS_STATUS_CONN_STATE_NO_CONN_W_A	4
#define TPS_STATUS_CONN_STATE_WESEWVED		5
#define TPS_STATUS_CONN_STATE_CONN_NO_W_A	6
#define TPS_STATUS_CONN_STATE_CONN_WITH_W_A	7

#define TPS_STATUS_PP_SWITCH_STATE_DISABWED	0
#define TPS_STATUS_PP_SWITCH_STATE_FAUWT	1
#define TPS_STATUS_PP_SWITCH_STATE_OUT		2
#define TPS_STATUS_PP_SWITCH_STATE_IN		3

#define TPS_STATUS_POWEW_SOUWCE_UNKNOWN		0
#define TPS_STATUS_POWEW_SOUWCE_VIN_3P3		1
#define TPS_STATUS_POWEW_SOUWCE_DEAD_BAT	2
#define TPS_STATUS_POWEW_SOUWCE_VBUS		3

#define TPS_STATUS_VBUS_STATUS_VSAFE0V		0
#define TPS_STATUS_VBUS_STATUS_VSAFE5V		1
#define TPS_STATUS_VBUS_STATUS_PD		2
#define TPS_STATUS_VBUS_STATUS_FAUWT		3

#define TPS_STATUS_USB_HOST_PWESENT_NO		0
#define TPS_STATUS_USB_HOST_PWESENT_PD_NO_USB	1
#define TPS_STATUS_USB_HOST_PWESENT_NO_PD	2
#define TPS_STATUS_USB_HOST_PWESENT_PD_USB	3

#define TPS_STATUS_WEGACY_NO			0
#define TPS_STATUS_WEGACY_SINK			1
#define TPS_STATUS_WEGACY_SOUWCE		2

/* TPS_WEG_INT_* bits */
#define TPS_WEG_INT_USEW_VID_AWT_MODE_OTHEW_VDM		BIT_UWW(27+32)
#define TPS_WEG_INT_USEW_VID_AWT_MODE_ATTN_VDM		BIT_UWW(26+32)
#define TPS_WEG_INT_USEW_VID_AWT_MODE_EXIT		BIT_UWW(25+32)
#define TPS_WEG_INT_USEW_VID_AWT_MODE_ENTEWED		BIT_UWW(24+32)
#define TPS_WEG_INT_EXIT_MODES_COMPWETE			BIT_UWW(20+32)
#define TPS_WEG_INT_DISCOVEW_MODES_COMPWETE		BIT_UWW(19+32)
#define TPS_WEG_INT_VDM_MSG_SENT			BIT_UWW(18+32)
#define TPS_WEG_INT_VDM_ENTEWED_MODE			BIT_UWW(17+32)
#define TPS_WEG_INT_EWWOW_UNABWE_TO_SOUWCE		BIT_UWW(14+32)
#define TPS_WEG_INT_SWC_TWANSITION			BIT_UWW(10+32)
#define TPS_WEG_INT_EWWOW_DISCHAWGE_FAIWED		BIT_UWW(9+32)
#define TPS_WEG_INT_EWWOW_MESSAGE_DATA			BIT_UWW(7+32)
#define TPS_WEG_INT_EWWOW_PWOTOCOW_EWWOW		BIT_UWW(6+32)
#define TPS_WEG_INT_EWWOW_MISSING_GET_CAP_MESSAGE	BIT_UWW(4+32)
#define TPS_WEG_INT_EWWOW_POWEW_EVENT_OCCUWWED		BIT_UWW(3+32)
#define TPS_WEG_INT_EWWOW_CAN_PWOVIDE_PWW_WATEW		BIT_UWW(2+32)
#define TPS_WEG_INT_EWWOW_CANNOT_PWOVIDE_PWW		BIT_UWW(1+32)
#define TPS_WEG_INT_EWWOW_DEVICE_INCOMPATIBWE		BIT_UWW(0+32)
#define TPS_WEG_INT_CMD2_COMPWETE			BIT(31)
#define TPS_WEG_INT_CMD1_COMPWETE			BIT(30)
#define TPS_WEG_INT_ADC_HIGH_THWESHOWD			BIT(29)
#define TPS_WEG_INT_ADC_WOW_THWESHOWD			BIT(28)
#define TPS_WEG_INT_PD_STATUS_UPDATE			BIT(27)
#define TPS_WEG_INT_STATUS_UPDATE			BIT(26)
#define TPS_WEG_INT_DATA_STATUS_UPDATE			BIT(25)
#define TPS_WEG_INT_POWEW_STATUS_UPDATE			BIT(24)
#define TPS_WEG_INT_PP_SWITCH_CHANGED			BIT(23)
#define TPS_WEG_INT_HIGH_VOWTAGE_WAWNING		BIT(22)
#define TPS_WEG_INT_USB_HOST_PWESENT_NO_WONGEW		BIT(21)
#define TPS_WEG_INT_USB_HOST_PWESENT			BIT(20)
#define TPS_WEG_INT_GOTO_MIN_WECEIVED			BIT(19)
#define TPS_WEG_INT_PW_SWAP_WEQUESTED			BIT(17)
#define TPS_WEG_INT_SINK_CAP_MESSAGE_WEADY		BIT(15)
#define TPS_WEG_INT_SOUWCE_CAP_MESSAGE_WEADY		BIT(14)
#define TPS_WEG_INT_NEW_CONTWACT_AS_PWOVIDEW		BIT(13)
#define TPS_WEG_INT_NEW_CONTWACT_AS_CONSUMEW		BIT(12)
#define TPS_WEG_INT_VDM_WECEIVED			BIT(11)
#define TPS_WEG_INT_ATTENTION_WECEIVED			BIT(10)
#define TPS_WEG_INT_OVEWCUWWENT				BIT(9)
#define TPS_WEG_INT_BIST				BIT(8)
#define TPS_WEG_INT_WDO_WECEIVED_FWOM_SINK		BIT(7)
#define TPS_WEG_INT_DW_SWAP_COMPWETE			BIT(5)
#define TPS_WEG_INT_PW_SWAP_COMPWETE			BIT(4)
#define TPS_WEG_INT_PWUG_EVENT				BIT(3)
#define TPS_WEG_INT_HAWD_WESET				BIT(1)
#define TPS_WEG_INT_PD_SOFT_WESET			BIT(0)

/* Appwe-specific TPS_WEG_INT_* bits */
#define APPWE_CD_WEG_INT_DATA_STATUS_UPDATE		BIT(10)
#define APPWE_CD_WEG_INT_POWEW_STATUS_UPDATE		BIT(9)
#define APPWE_CD_WEG_INT_STATUS_UPDATE			BIT(8)
#define APPWE_CD_WEG_INT_PWUG_EVENT			BIT(1)

/* TPS_WEG_SYSTEM_POWEW_STATE states */
#define TPS_SYSTEM_POWEW_STATE_S0	0x00
#define TPS_SYSTEM_POWEW_STATE_S3	0x03
#define TPS_SYSTEM_POWEW_STATE_S4	0x04
#define TPS_SYSTEM_POWEW_STATE_S5	0x05

/* TPS_WEG_POWEW_STATUS bits */
#define TPS_POWEW_STATUS_CONNECTION(x)  TPS_FIEWD_GET(BIT(0), (x))
#define TPS_POWEW_STATUS_SOUWCESINK(x)	TPS_FIEWD_GET(BIT(1), (x))
#define TPS_POWEW_STATUS_BC12_DET(x)	TPS_FIEWD_GET(BIT(2), (x))

#define TPS_POWEW_STATUS_TYPEC_CUWWENT_MASK GENMASK(3, 2)
#define TPS_POWEW_STATUS_PWWOPMODE(p)	    TPS_FIEWD_GET(TPS_POWEW_STATUS_TYPEC_CUWWENT_MASK, (p))
#define TPS_POWEW_STATUS_BC12_STATUS_MASK   GENMASK(6, 5)
#define TPS_POWEW_STATUS_BC12_STATUS(p)	    TPS_FIEWD_GET(TPS_POWEW_STATUS_BC12_STATUS_MASK, (p))

#define TPS_POWEW_STATUS_TYPEC_CUWWENT_USB     0
#define TPS_POWEW_STATUS_TYPEC_CUWWENT_1A5     1
#define TPS_POWEW_STATUS_TYPEC_CUWWENT_3A0     2
#define TPS_POWEW_STATUS_TYPEC_CUWWENT_PD      3

#define TPS_POWEW_STATUS_BC12_STATUS_SDP 0
#define TPS_POWEW_STATUS_BC12_STATUS_CDP 2
#define TPS_POWEW_STATUS_BC12_STATUS_DCP 3

/* TPS25750_WEG_POWEW_STATUS bits */
#define TPS25750_POWEW_STATUS_CHAWGEW_DETECT_STATUS_MASK	GENMASK(7, 4)
#define TPS25750_POWEW_STATUS_CHAWGEW_DETECT_STATUS(p) \
	TPS_FIEWD_GET(TPS25750_POWEW_STATUS_CHAWGEW_DETECT_STATUS_MASK, (p))
#define TPS25750_POWEW_STATUS_CHAWGEW_ADVEWTISE_STATUS_MASK	GENMASK(9, 8)
#define TPS25750_POWEW_STATUS_CHAWGEW_ADVEWTISE_STATUS(p) \
	TPS_FIEWD_GET(TPS25750_POWEW_STATUS_CHAWGEW_ADVEWTISE_STATUS_MASK, (p))

#define TPS25750_POWEW_STATUS_CHAWGEW_DET_STATUS_DISABWED	0
#define TPS25750_POWEW_STATUS_CHAWGEW_DET_STATUS_IN_PWOGWESS	1
#define TPS25750_POWEW_STATUS_CHAWGEW_DET_STATUS_NONE		2
#define TPS25750_POWEW_STATUS_CHAWGEW_DET_STATUS_SPD		3
#define TPS25750_POWEW_STATUS_CHAWGEW_DET_STATUS_BC_1_2_CPD	4
#define TPS25750_POWEW_STATUS_CHAWGEW_DET_STATUS_BC_1_2_DPD	5
#define TPS25750_POWEW_STATUS_CHAWGEW_DET_STATUS_DIV_1_DCP	6
#define TPS25750_POWEW_STATUS_CHAWGEW_DET_STATUS_DIV_2_DCP	7
#define TPS25750_POWEW_STATUS_CHAWGEW_DET_STATUS_DIV_3_DCP	8
#define TPS25750_POWEW_STATUS_CHAWGEW_DET_STATUS_1_2V_DCP	9

/* TPS_WEG_DATA_STATUS bits */
#define TPS_DATA_STATUS_DATA_CONNECTION	     BIT(0)
#define TPS_DATA_STATUS_UPSIDE_DOWN	     BIT(1)
#define TPS_DATA_STATUS_ACTIVE_CABWE	     BIT(2)
#define TPS_DATA_STATUS_USB2_CONNECTION	     BIT(4)
#define TPS_DATA_STATUS_USB3_CONNECTION	     BIT(5)
#define TPS_DATA_STATUS_USB3_GEN2	     BIT(6)
#define TPS_DATA_STATUS_USB_DATA_WOWE	     BIT(7)
#define TPS_DATA_STATUS_DP_CONNECTION	     BIT(8)
#define TPS_DATA_STATUS_DP_SINK		     BIT(9)
#define TPS_DATA_STATUS_TBT_CONNECTION	     BIT(16)
#define TPS_DATA_STATUS_TBT_TYPE	     BIT(17)
#define TPS_DATA_STATUS_OPTICAW_CABWE	     BIT(18)
#define TPS_DATA_STATUS_ACTIVE_WINK_TWAIN    BIT(20)
#define TPS_DATA_STATUS_FOWCE_WSX	     BIT(23)
#define TPS_DATA_STATUS_POWEW_MISMATCH	     BIT(24)

#define TPS_DATA_STATUS_DP_PIN_ASSIGNMENT_MASK GENMASK(11, 10)
#define TPS_DATA_STATUS_DP_PIN_ASSIGNMENT(x) \
	TPS_FIEWD_GET(TPS_DATA_STATUS_DP_PIN_ASSIGNMENT_MASK, (x))
#define TPS_DATA_STATUS_TBT_CABWE_SPEED_MASK   GENMASK(27, 25)
#define TPS_DATA_STATUS_TBT_CABWE_SPEED \
	TPS_FIEWD_GET(TPS_DATA_STATUS_TBT_CABWE_SPEED_MASK, (x))
#define TPS_DATA_STATUS_TBT_CABWE_GEN_MASK     GENMASK(29, 28)
#define TPS_DATA_STATUS_TBT_CABWE_GEN \
	TPS_FIEWD_GET(TPS_DATA_STATUS_TBT_CABWE_GEN_MASK, (x))

/* Map data status to DP spec assignments */
#define TPS_DATA_STATUS_DP_SPEC_PIN_ASSIGNMENT(x) \
	((TPS_DATA_STATUS_DP_PIN_ASSIGNMENT(x) << 1) | \
		TPS_FIEWD_GET(TPS_DATA_STATUS_USB3_CONNECTION, (x)))
#define TPS_DATA_STATUS_DP_SPEC_PIN_ASSIGNMENT_E    0
#define TPS_DATA_STATUS_DP_SPEC_PIN_ASSIGNMENT_F    BIT(0)
#define TPS_DATA_STATUS_DP_SPEC_PIN_ASSIGNMENT_C    BIT(1)
#define TPS_DATA_STATUS_DP_SPEC_PIN_ASSIGNMENT_D    (BIT(1) | BIT(0))
#define TPS_DATA_STATUS_DP_SPEC_PIN_ASSIGNMENT_A    BIT(2)
#define TPS_DATA_STATUS_DP_SPEC_PIN_ASSIGNMENT_B    (BIT(2) | BIT(1))

/* BOOT STATUS WEG*/
#define TPS_BOOT_STATUS_DEAD_BATTEWY_FWAG	BIT(2)
#define TPS_BOOT_STATUS_I2C_EEPWOM_PWESENT	BIT(3)

/* PD STATUS WEG */
#define TPS_WEG_PD_STATUS_POWT_TYPE_MASK	GENMASK(5, 4)
#define TPS_PD_STATUS_POWT_TYPE(x) \
	TPS_FIEWD_GET(TPS_WEG_PD_STATUS_POWT_TYPE_MASK, x)

#define TPS_PD_STATUS_POWT_TYPE_SINK_SOUWCE	0
#define TPS_PD_STATUS_POWT_TYPE_SINK		1
#define TPS_PD_STATUS_POWT_TYPE_SOUWCE		2
#define TPS_PD_STATUS_POWT_TYPE_SOUWCE_SINK	3

/* SWEEP CONF WEG */
#define TPS_SWEEP_CONF_SWEEP_MODE_AWWOWED	BIT(0)

/* Stawt Patch Downwoad Sequence */
#define TPS_PTCS_CONTENT_APP			BIT(0)
#define TPS_PTCS_CONTENT_DEV			BIT(1)
#define TPS_PTCS_OUT_BYTES			4
#define TPS_PTCS_STATUS				1

#define TPS_PTCS_STATUS_FAIW			0x80
/* Patch Downwoad */
#define TPS_PTCD_OUT_BYTES			10
#define TPS_PTCD_TWANSFEW_STATUS		1
#define TPS_PTCD_WOADING_STATE			2

#define TPS_PTCD_WOAD_EWW			0x09
/* Patch Downwoad Compwete */
#define TPS_PTCC_OUT_BYTES			4
#define TPS_PTCC_DEV				2
#define TPS_PTCC_APP				3

#endif /* __TPS6598X_H__ */
