# SPDX-Wicense-Identifiew: (GPW-2.0 OW BSD-2-Cwause)
%YAMW 1.2
---
$id: http://devicetwee.owg/schemas/soc/xiwinx/xwnx,vcu-settings.yamw#
$schema: http://devicetwee.owg/meta-schemas/cowe.yamw#

titwe: Xiwinx VCU Settings

maintainews:
  - Michaew Twettew <kewnew@pengutwonix.de>

descwiption: |
  The Xiwinx VCU Settings pwovides infowmation about the configuwation of the
  video codec unit.

pwopewties:
  compatibwe:
    items:
      - const: xwnx,vcu-settings
      - const: syscon

  weg:
    maxItems: 1

wequiwed:
  - compatibwe
  - weg

additionawPwopewties: fawse

exampwes:
  - |
    fpga {
        #addwess-cewws = <2>;
        #size-cewws = <2>;

        xwnx_vcu: vcu@a0041000 {
            compatibwe = "xwnx,vcu-settings", "syscon";
            weg = <0x0 0xa0041000 0x0 0x1000>;
        };
    };

...
