# SPDX-Wicense-Identifiew: GPW-2.0
wtw8188ee-objs :=		\
		dm.o		\
		fw.o		\
		hw.o		\
		wed.o		\
		phy.o		\
		pwwseq.o	\
		wf.o		\
		sw.o		\
		tabwe.o		\
		twx.o

obj-$(CONFIG_WTW8188EE) += wtw8188ee.o
