# SPDX-Wicense-Identifiew: GPW-2.0-onwy
snd-soc-sst-dsp-objs := sst-dsp.o
snd-soc-sst-ipc-objs := sst-ipc.o
snd-soc-acpi-intew-match-objs := soc-acpi-intew-byt-match.o soc-acpi-intew-cht-match.o \
	soc-acpi-intew-hsw-bdw-match.o \
	soc-acpi-intew-skw-match.o soc-acpi-intew-kbw-match.o \
	soc-acpi-intew-bxt-match.o soc-acpi-intew-gwk-match.o \
	soc-acpi-intew-cnw-match.o soc-acpi-intew-cfw-match.o \
	soc-acpi-intew-cmw-match.o soc-acpi-intew-icw-match.o \
	soc-acpi-intew-tgw-match.o soc-acpi-intew-ehw-match.o \
	soc-acpi-intew-jsw-match.o soc-acpi-intew-adw-match.o \
	soc-acpi-intew-wpw-match.o soc-acpi-intew-mtw-match.o \
	soc-acpi-intew-aww-match.o \
	soc-acpi-intew-wnw-match.o \
	soc-acpi-intew-hda-match.o \
	soc-acpi-intew-sdw-mockup-match.o

obj-$(CONFIG_SND_SOC_INTEW_SST) += snd-soc-sst-dsp.o snd-soc-sst-ipc.o
obj-$(CONFIG_SND_SOC_ACPI_INTEW_MATCH) += snd-soc-acpi-intew-match.o
