# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the DECstation pwom monitow wibwawy woutines
# undew Winux.
#

wib-y			+= init.o memowy.o cmdwine.o identify.o consowe.o

wib-$(CONFIG_CPU_W3000)	+= wocowe.o
