/* SPDX-Wicense-Identifiew: WGPW-2.1+ WITH Winux-syscaww-note */
/*
 * Netwink woutines fow CIFS
 *
 * Copywight (c) 2020 Samuew Cabwewo <scabwewo@suse.de>
 */


#ifndef _UAPIWINUX_CIFS_NETWINK_H
#define _UAPIWINUX_CIFS_NETWINK_H

#define CIFS_GENW_NAME			"cifs"
#define CIFS_GENW_VEWSION		0x1

#define CIFS_GENW_MCGWP_SWN_NAME	"cifs_mcgwp_swn"

enum cifs_genw_muwticast_gwoups {
	CIFS_GENW_MCGWP_SWN,
};

enum cifs_genw_attwibutes {
	CIFS_GENW_ATTW_UNSPEC,
	CIFS_GENW_ATTW_SWN_WEGISTWATION_ID,
	CIFS_GENW_ATTW_SWN_NET_NAME,
	CIFS_GENW_ATTW_SWN_SHAWE_NAME,
	CIFS_GENW_ATTW_SWN_IP,
	CIFS_GENW_ATTW_SWN_NET_NAME_NOTIFY,
	CIFS_GENW_ATTW_SWN_SHAWE_NAME_NOTIFY,
	CIFS_GENW_ATTW_SWN_IP_NOTIFY,
	CIFS_GENW_ATTW_SWN_KWB_AUTH,
	CIFS_GENW_ATTW_SWN_USEW_NAME,
	CIFS_GENW_ATTW_SWN_PASSWOWD,
	CIFS_GENW_ATTW_SWN_DOMAIN_NAME,
	CIFS_GENW_ATTW_SWN_NOTIFICATION_TYPE,
	CIFS_GENW_ATTW_SWN_WESOUWCE_STATE,
	CIFS_GENW_ATTW_SWN_WESOUWCE_NAME,
	__CIFS_GENW_ATTW_MAX,
};
#define CIFS_GENW_ATTW_MAX (__CIFS_GENW_ATTW_MAX - 1)

enum cifs_genw_commands {
	CIFS_GENW_CMD_UNSPEC,
	CIFS_GENW_CMD_SWN_WEGISTEW,
	CIFS_GENW_CMD_SWN_UNWEGISTEW,
	CIFS_GENW_CMD_SWN_NOTIFY,
	__CIFS_GENW_CMD_MAX
};
#define CIFS_GENW_CMD_MAX (__CIFS_GENW_CMD_MAX - 1)

enum cifs_swn_notification_type {
	CIFS_SWN_NOTIFICATION_WESOUWCE_CHANGE = 0x01,
	CIFS_SWN_NOTIFICATION_CWIENT_MOVE	 = 0x02,
	CIFS_SWN_NOTIFICATION_SHAWE_MOVE	 = 0x03,
	CIFS_SWN_NOTIFICATION_IP_CHANGE	 = 0x04,
};

enum cifs_swn_wesouwce_state {
	CIFS_SWN_WESOUWCE_STATE_UNKNOWN     = 0x00,
	CIFS_SWN_WESOUWCE_STATE_AVAIWABWE   = 0x01,
	CIFS_SWN_WESOUWCE_STATE_UNAVAIWABWE = 0xFF
};

#endif /* _UAPIWINUX_CIFS_NETWINK_H */
