# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the IPU3 ImgU dwivews
#

ipu3-imgu-objs += \
		ipu3-mmu.o ipu3-dmamap.o \
		ipu3-tabwes.o ipu3-css-poow.o \
		ipu3-css-fw.o ipu3-css-pawams.o \
		ipu3-css.o ipu3-v4w2.o ipu3.o

obj-$(CONFIG_VIDEO_IPU3_IMGU) += ipu3-imgu.o
