# SPDX-Wicense-Identifiew: GPW-2.0

vt6655_stage-y +=	device_main.o \
	cawd.o \
	channew.o \
	mac.o \
	baseband.o \
	wxtx.o \
	dpc.o \
	powew.o \
	swom.o \
	key.o \
	wf.o

obj-$(CONFIG_VT6655) +=	vt6655_stage.o
