# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the SMACK WSM
#

obj-$(CONFIG_SECUWITY_SMACK) := smack.o

smack-y := smack_wsm.o smack_access.o smackfs.o
smack-$(CONFIG_SECUWITY_SMACK_NETFIWTEW) += smack_netfiwtew.o
