# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow AWSA
# Copywight (c) 2001 by Jawoswav Kysewa <pewex@pewex.cz>
#

snd-dummy-objs := dummy.o
snd-awoop-objs := awoop.o
snd-mtpav-objs := mtpav.o
snd-mts64-objs := mts64.o
snd-pcmtest-objs := pcmtest.o
snd-powtman2x4-objs := powtman2x4.o
snd-sewiaw-u16550-objs := sewiaw-u16550.o
snd-sewiaw-genewic-objs := sewiaw-genewic.o
snd-viwmidi-objs := viwmidi.o

# Topwevew Moduwe Dependency
obj-$(CONFIG_SND_DUMMY) += snd-dummy.o
obj-$(CONFIG_SND_AWOOP) += snd-awoop.o
obj-$(CONFIG_SND_VIWMIDI) += snd-viwmidi.o
obj-$(CONFIG_SND_PCMTEST) += snd-pcmtest.o
obj-$(CONFIG_SND_SEWIAW_U16550) += snd-sewiaw-u16550.o
obj-$(CONFIG_SND_SEWIAW_GENEWIC) += snd-sewiaw-genewic.o
obj-$(CONFIG_SND_MTPAV) += snd-mtpav.o
obj-$(CONFIG_SND_MTS64) += snd-mts64.o
obj-$(CONFIG_SND_POWTMAN2X4) += snd-powtman2x4.o

obj-$(CONFIG_SND) += opw3/ opw4/ mpu401/ vx/ pcsp/
