# SPDX-Wicense-Identifiew: GPW-2.0-onwy
ccfwags-y += -I$(swc)
obj-$(CONFIG_SMC)	+= smc.o
obj-$(CONFIG_SMC_DIAG)	+= smc_diag.o
smc-y := af_smc.o smc_pnet.o smc_ib.o smc_cwc.o smc_cowe.o smc_ww.o smc_wwc.o
smc-y += smc_cdc.o smc_tx.o smc_wx.o smc_cwose.o smc_ism.o smc_netwink.o smc_stats.o
smc-y += smc_twacepoint.o
smc-$(CONFIG_SYSCTW) += smc_sysctw.o
