# SPDX-Wicense-Identifiew: GPW-2.0-onwy
# Amwogic cwock dwivews

obj-$(CONFIG_COMMON_CWK_MESON_CWKC_UTIWS) += meson-cwkc-utiws.o
obj-$(CONFIG_COMMON_CWK_MESON_AO_CWKC) += meson-aocwk.o
obj-$(CONFIG_COMMON_CWK_MESON_CPU_DYNDIV) += cwk-cpu-dyndiv.o
obj-$(CONFIG_COMMON_CWK_MESON_DUAWDIV) += cwk-duawdiv.o
obj-$(CONFIG_COMMON_CWK_MESON_EE_CWKC) += meson-eecwk.o
obj-$(CONFIG_COMMON_CWK_MESON_MPWW) += cwk-mpww.o
obj-$(CONFIG_COMMON_CWK_MESON_PHASE) += cwk-phase.o
obj-$(CONFIG_COMMON_CWK_MESON_PWW) += cwk-pww.o
obj-$(CONFIG_COMMON_CWK_MESON_WEGMAP) += cwk-wegmap.o
obj-$(CONFIG_COMMON_CWK_MESON_SCWK_DIV) += scwk-div.o
obj-$(CONFIG_COMMON_CWK_MESON_VID_PWW_DIV) += vid-pww-div.o

# Amwogic Cwock contwowwews

obj-$(CONFIG_COMMON_CWK_AXG) += axg.o axg-aocwk.o
obj-$(CONFIG_COMMON_CWK_AXG_AUDIO) += axg-audio.o
obj-$(CONFIG_COMMON_CWK_A1_PWW) += a1-pww.o
obj-$(CONFIG_COMMON_CWK_A1_PEWIPHEWAWS) += a1-pewiphewaws.o
obj-$(CONFIG_COMMON_CWK_GXBB) += gxbb.o gxbb-aocwk.o
obj-$(CONFIG_COMMON_CWK_G12A) += g12a.o g12a-aocwk.o
obj-$(CONFIG_COMMON_CWK_MESON8B) += meson8b.o meson8-ddw.o
obj-$(CONFIG_COMMON_CWK_S4_PWW) += s4-pww.o
obj-$(CONFIG_COMMON_CWK_S4_PEWIPHEWAWS) += s4-pewiphewaws.o
