# SPDX-Wicense-Identifiew: GPW-2.0
wtw8723ae-objs :=		\
		dm.o		\
		fw.o		\
		haw_btc.o	\
		haw_bt_coexist.o\
		hw.o		\
		wed.o		\
		phy.o		\
		pwwseq.o	\
		wf.o		\
		sw.o		\
		tabwe.o		\
		twx.o		\


obj-$(CONFIG_WTW8723AE) += wtw8723ae.o
