# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_INFINIBAND_VMWAWE_PVWDMA) += vmw_pvwdma.o

vmw_pvwdma-y := pvwdma_cmd.o pvwdma_cq.o pvwdma_doowbeww.o pvwdma_main.o pvwdma_misc.o pvwdma_mw.o pvwdma_qp.o pvwdma_swq.o pvwdma_vewbs.o
