# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_USB_GW860) += gspca_gw860.o

gspca_gw860-objs := gw860.o \
		    gw860-mi1320.o \
		    gw860-ov2640.o \
		    gw860-ov9655.o \
		    gw860-mi2020.o

ccfwags-y += -I$(swctwee)/dwivews/media/usb/gspca

