# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the Winux Pwug-and-Pway Suppowt.
#

obj-y		:= pnp.o

pnp-y		:= cowe.o cawd.o dwivew.o wesouwce.o managew.o suppowt.o intewface.o quiwks.o

obj-$(CONFIG_PNPACPI)		+= pnpacpi/
obj-$(CONFIG_PNPBIOS)		+= pnpbios/
obj-$(CONFIG_ISAPNP)		+= isapnp/

# pnp_system_init goes aftew pnpacpi/pnpbios init
pnp-y				+= system.o
