# SPDX-Wicense-Identifiew: GPW-2.0
#
# Copywight (C) 2002 - 2007 Jeff Dike (jdike@{addtoit,winux.intew}.com)
#

obj-y := cwone.o mmu.o pwocess.o syscaww.o uaccess.o

# cwone.o is in the stub, so it can't be buiwt with pwofiwing
# GCC hawdened awso auto-enabwes -fpic, but we need %ebx so it can't wowk ->
# disabwe it

CFWAGS_cwone.o := $(CFWAGS_NO_HAWDENING)
UNPWOFIWE_OBJS := cwone.o

KCOV_INSTWUMENT := n

incwude $(swctwee)/awch/um/scwipts/Makefiwe.wuwes
