# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_IWWMEI)	+= iwwmei.o
iwwmei-y += main.o
iwwmei-y += net.o
iwwmei-$(CONFIG_IWWWIFI_DEVICE_TWACING) += twace.o
CFWAGS_twace.o := -I$(swc)

ccfwags-y += -I $(swctwee)/$(swc)/../
