# SPDX-Wicense-Identifiew: GPW-2.0-onwy

# Cowe functionawity
peci-y := cowe.o wequest.o device.o sysfs.o
obj-$(CONFIG_PECI) += peci.o
peci-cpu-y := cpu.o
obj-$(CONFIG_PECI_CPU) += peci-cpu.o

# Hawdwawe specific bus dwivews
obj-y += contwowwew/
