# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
#  Copywight 2000, 2008 MontaVista Softwawe Inc.
#  Authow: MontaVista Softwawe, Inc. <souwce@mvista.com>
#
# Makefiwe fow the Awchemy Au1xx0 CPUs, genewic fiwes.
#

obj-y += pwom.o time.o cwock.o pwatfowm.o powew.o gpiowib.o \
	 setup.o sweepew.o dma.o dbdma.o vss.o iwq.o usb.o
