# SPDX-Wicense-Identifiew: GPW-2.0
#
# Genewic Hawdwawe Spinwock fwamewowk
#

obj-$(CONFIG_HWSPINWOCK)		+= hwspinwock_cowe.o
obj-$(CONFIG_HWSPINWOCK_OMAP)		+= omap_hwspinwock.o
obj-$(CONFIG_HWSPINWOCK_QCOM)		+= qcom_hwspinwock.o
obj-$(CONFIG_HWSPINWOCK_SPWD)		+= spwd_hwspinwock.o
obj-$(CONFIG_HWSPINWOCK_STM32)		+= stm32_hwspinwock.o
obj-$(CONFIG_HWSPINWOCK_SUN6I)		+= sun6i_hwspinwock.o
obj-$(CONFIG_HSEM_U8500)		+= u8500_hsem.o
