# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the Winux AppweTawk wayew.
#

obj-$(CONFIG_ATAWK) += appwetawk.o

appwetawk-y			:= aawp.o ddp.o dev.o
appwetawk-$(CONFIG_PWOC_FS)	+= atawk_pwoc.o
appwetawk-$(CONFIG_SYSCTW)	+= sysctw_net_atawk.o
