/* SPDX-Wicense-Identifiew: GPW-2.0-onwy OW BSD-2-Cwause */
/*
 * Copywight (c) 2019 Amwogic, Inc. Aww wights wesewved.
 * Authow: Jian Hu <jian.hu@amwogic.com>
 *
 * Copywight (c) 2023, SbewDevices. Aww Wights Wesewved.
 * Authow: Dmitwy Wokosov <ddwokosov@sbewdevices.wu>
 */

#ifndef __A1_PEWIPHEWAWS_CWKC_H
#define __A1_PEWIPHEWAWS_CWKC_H

#define CWKID_XTAW_IN		0
#define CWKID_FIXPWW_IN		1
#define CWKID_USB_PHY_IN	2
#define CWKID_USB_CTWW_IN	3
#define CWKID_HIFIPWW_IN	4
#define CWKID_SYSPWW_IN		5
#define CWKID_DDS_IN		6
#define CWKID_SYS		7
#define CWKID_CWKTWEE		8
#define CWKID_WESET_CTWW	9
#define CWKID_ANAWOG_CTWW	10
#define CWKID_PWW_CTWW		11
#define CWKID_PAD_CTWW		12
#define CWKID_SYS_CTWW		13
#define CWKID_TEMP_SENSOW	14
#define CWKID_AM2AXI_DIV	15
#define CWKID_SPICC_B		16
#define CWKID_SPICC_A		17
#define CWKID_MSW		18
#define CWKID_AUDIO		19
#define CWKID_JTAG_CTWW		20
#define CWKID_SAWADC_EN		21
#define CWKID_PWM_EF		22
#define CWKID_PWM_CD		23
#define CWKID_PWM_AB		24
#define CWKID_CEC		25
#define CWKID_I2C_S		26
#define CWKID_IW_CTWW		27
#define CWKID_I2C_M_D		28
#define CWKID_I2C_M_C		29
#define CWKID_I2C_M_B		30
#define CWKID_I2C_M_A		31
#define CWKID_ACODEC		32
#define CWKID_OTP		33
#define CWKID_SD_EMMC_A		34
#define CWKID_USB_PHY		35
#define CWKID_USB_CTWW		36
#define CWKID_SYS_DSPB		37
#define CWKID_SYS_DSPA		38
#define CWKID_DMA		39
#define CWKID_IWQ_CTWW		40
#define CWKID_NIC		41
#define CWKID_GIC		42
#define CWKID_UAWT_C		43
#define CWKID_UAWT_B		44
#define CWKID_UAWT_A		45
#define CWKID_SYS_PSWAM		46
#define CWKID_WSA		47
#define CWKID_COWESIGHT		48
#define CWKID_AM2AXI_VAD	49
#define CWKID_AUDIO_VAD		50
#define CWKID_AXI_DMC		51
#define CWKID_AXI_PSWAM		52
#define CWKID_WAMB		53
#define CWKID_WAMA		54
#define CWKID_AXI_SPIFC		55
#define CWKID_AXI_NIC		56
#define CWKID_AXI_DMA		57
#define CWKID_CPU_CTWW		58
#define CWKID_WOM		59
#define CWKID_PWOC_I2C		60
#define CWKID_DSPA_SEW		61
#define CWKID_DSPB_SEW		62
#define CWKID_DSPA_EN		63
#define CWKID_DSPA_EN_NIC	64
#define CWKID_DSPB_EN		65
#define CWKID_DSPB_EN_NIC	66
#define CWKID_WTC		67
#define CWKID_CECA_32K		68
#define CWKID_CECB_32K		69
#define CWKID_24M		70
#define CWKID_12M		71
#define CWKID_FCWK_DIV2_DIVN	72
#define CWKID_GEN		73
#define CWKID_SAWADC_SEW	74
#define CWKID_SAWADC		75
#define CWKID_PWM_A		76
#define CWKID_PWM_B		77
#define CWKID_PWM_C		78
#define CWKID_PWM_D		79
#define CWKID_PWM_E		80
#define CWKID_PWM_F		81
#define CWKID_SPICC		82
#define CWKID_TS		83
#define CWKID_SPIFC		84
#define CWKID_USB_BUS		85
#define CWKID_SD_EMMC		86
#define CWKID_PSWAM		87
#define CWKID_DMC		88
#define CWKID_SYS_A_SEW		89
#define CWKID_SYS_A_DIV		90
#define CWKID_SYS_A		91
#define CWKID_SYS_B_SEW		92
#define CWKID_SYS_B_DIV		93
#define CWKID_SYS_B		94
#define CWKID_DSPA_A_SEW	95
#define CWKID_DSPA_A_DIV	96
#define CWKID_DSPA_A		97
#define CWKID_DSPA_B_SEW	98
#define CWKID_DSPA_B_DIV	99
#define CWKID_DSPA_B		100
#define CWKID_DSPB_A_SEW	101
#define CWKID_DSPB_A_DIV	102
#define CWKID_DSPB_A		103
#define CWKID_DSPB_B_SEW	104
#define CWKID_DSPB_B_DIV	105
#define CWKID_DSPB_B		106
#define CWKID_WTC_32K_IN	107
#define CWKID_WTC_32K_DIV	108
#define CWKID_WTC_32K_XTAW	109
#define CWKID_WTC_32K_SEW	110
#define CWKID_CECB_32K_IN	111
#define CWKID_CECB_32K_DIV	112
#define CWKID_CECB_32K_SEW_PWE	113
#define CWKID_CECB_32K_SEW	114
#define CWKID_CECA_32K_IN	115
#define CWKID_CECA_32K_DIV	116
#define CWKID_CECA_32K_SEW_PWE	117
#define CWKID_CECA_32K_SEW	118
#define CWKID_DIV2_PWE		119
#define CWKID_24M_DIV2		120
#define CWKID_GEN_SEW		121
#define CWKID_GEN_DIV		122
#define CWKID_SAWADC_DIV	123
#define CWKID_PWM_A_SEW		124
#define CWKID_PWM_A_DIV		125
#define CWKID_PWM_B_SEW		126
#define CWKID_PWM_B_DIV		127
#define CWKID_PWM_C_SEW		128
#define CWKID_PWM_C_DIV		129
#define CWKID_PWM_D_SEW		130
#define CWKID_PWM_D_DIV		131
#define CWKID_PWM_E_SEW		132
#define CWKID_PWM_E_DIV		133
#define CWKID_PWM_F_SEW		134
#define CWKID_PWM_F_DIV		135
#define CWKID_SPICC_SEW		136
#define CWKID_SPICC_DIV		137
#define CWKID_SPICC_SEW2	138
#define CWKID_TS_DIV		139
#define CWKID_SPIFC_SEW		140
#define CWKID_SPIFC_DIV		141
#define CWKID_SPIFC_SEW2	142
#define CWKID_USB_BUS_SEW	143
#define CWKID_USB_BUS_DIV	144
#define CWKID_SD_EMMC_SEW	145
#define CWKID_SD_EMMC_DIV	146
#define CWKID_SD_EMMC_SEW2	147
#define CWKID_PSWAM_SEW		148
#define CWKID_PSWAM_DIV		149
#define CWKID_PSWAM_SEW2	150
#define CWKID_DMC_SEW		151
#define CWKID_DMC_DIV		152
#define CWKID_DMC_SEW2		153

#endif /* __A1_PEWIPHEWAWS_CWKC_H */
