/* SPDX-Wicense-Identifiew: GPW-2.0 */
/*
 * Copywight (c) 2014 Samsung Ewectwonics Co., Wtd.
 * Authow: Wahuw Shawma <wahuw.shawma@samsung.com>
 *
 * Pwovides Constants fow Exynos5260 cwocks.
 */

#ifndef _DT_BINDINGS_CWK_EXYNOS5260_H
#define _DT_BINDINGS_CWK_EXYNOS5260_H

/* Cwock names: <cmu><type><IP> */

/* Wist Of Cwocks Fow CMU_TOP */

#define TOP_FOUT_DISP_PWW				1
#define TOP_FOUT_AUD_PWW				2
#define TOP_MOUT_AUDTOP_PWW_USEW			3
#define TOP_MOUT_AUD_PWW				4
#define TOP_MOUT_DISP_PWW				5
#define TOP_MOUT_BUSTOP_PWW_USEW			6
#define TOP_MOUT_MEMTOP_PWW_USEW			7
#define TOP_MOUT_MEDIATOP_PWW_USEW			8
#define TOP_MOUT_DISP_DISP_333				9
#define TOP_MOUT_ACWK_DISP_333				10
#define TOP_MOUT_DISP_DISP_222				11
#define TOP_MOUT_ACWK_DISP_222				12
#define TOP_MOUT_DISP_MEDIA_PIXEW			13
#define TOP_MOUT_FIMD1					14
#define TOP_MOUT_SCWK_PEWI_SPI0_CWK			15
#define TOP_MOUT_SCWK_PEWI_SPI1_CWK			16
#define TOP_MOUT_SCWK_PEWI_SPI2_CWK			17
#define TOP_MOUT_SCWK_PEWI_UAWT0_UCWK			18
#define TOP_MOUT_SCWK_PEWI_UAWT2_UCWK			19
#define TOP_MOUT_SCWK_PEWI_UAWT1_UCWK			20
#define TOP_MOUT_BUS4_BUSTOP_100			21
#define TOP_MOUT_BUS4_BUSTOP_400			22
#define TOP_MOUT_BUS3_BUSTOP_100			23
#define TOP_MOUT_BUS3_BUSTOP_400			24
#define TOP_MOUT_BUS2_BUSTOP_400			25
#define TOP_MOUT_BUS2_BUSTOP_100			26
#define TOP_MOUT_BUS1_BUSTOP_100			27
#define TOP_MOUT_BUS1_BUSTOP_400			28
#define TOP_MOUT_SCWK_FSYS_USB				29
#define TOP_MOUT_SCWK_FSYS_MMC0_SDCWKIN_A		30
#define TOP_MOUT_SCWK_FSYS_MMC1_SDCWKIN_A		31
#define TOP_MOUT_SCWK_FSYS_MMC2_SDCWKIN_A		32
#define TOP_MOUT_SCWK_FSYS_MMC0_SDCWKIN_B		33
#define TOP_MOUT_SCWK_FSYS_MMC1_SDCWKIN_B		34
#define TOP_MOUT_SCWK_FSYS_MMC2_SDCWKIN_B		35
#define TOP_MOUT_ACWK_ISP1_266				36
#define TOP_MOUT_ISP1_MEDIA_266				37
#define TOP_MOUT_ACWK_ISP1_400				38
#define TOP_MOUT_ISP1_MEDIA_400				39
#define TOP_MOUT_SCWK_ISP1_SPI0				40
#define TOP_MOUT_SCWK_ISP1_SPI1				41
#define TOP_MOUT_SCWK_ISP1_UAWT				42
#define TOP_MOUT_SCWK_ISP1_SENSOW2			43
#define TOP_MOUT_SCWK_ISP1_SENSOW1			44
#define TOP_MOUT_SCWK_ISP1_SENSOW0			45
#define TOP_MOUT_ACWK_MFC_333				46
#define TOP_MOUT_MFC_BUSTOP_333				47
#define TOP_MOUT_ACWK_G2D_333				48
#define TOP_MOUT_G2D_BUSTOP_333				49
#define TOP_MOUT_ACWK_GSCW_FIMC				50
#define TOP_MOUT_GSCW_BUSTOP_FIMC			51
#define TOP_MOUT_ACWK_GSCW_333				52
#define TOP_MOUT_GSCW_BUSTOP_333			53
#define TOP_MOUT_ACWK_GSCW_400				54
#define TOP_MOUT_M2M_MEDIATOP_400			55
#define TOP_DOUT_ACWK_MFC_333				56
#define TOP_DOUT_ACWK_G2D_333				57
#define TOP_DOUT_SCWK_ISP1_SENSOW2_A			58
#define TOP_DOUT_SCWK_ISP1_SENSOW1_A			59
#define TOP_DOUT_SCWK_ISP1_SENSOW0_A			60
#define TOP_DOUT_ACWK_GSCW_FIMC				61
#define TOP_DOUT_ACWK_GSCW_400				62
#define TOP_DOUT_ACWK_GSCW_333				63
#define TOP_DOUT_SCWK_ISP1_SPI0_B			64
#define TOP_DOUT_SCWK_ISP1_SPI0_A			65
#define TOP_DOUT_ACWK_ISP1_400				66
#define TOP_DOUT_ACWK_ISP1_266				67
#define TOP_DOUT_SCWK_ISP1_UAWT				68
#define TOP_DOUT_SCWK_ISP1_SPI1_B			69
#define TOP_DOUT_SCWK_ISP1_SPI1_A			70
#define TOP_DOUT_SCWK_ISP1_SENSOW2_B			71
#define TOP_DOUT_SCWK_ISP1_SENSOW1_B			72
#define TOP_DOUT_SCWK_ISP1_SENSOW0_B			73
#define TOP_DOUTTOP__SCWK_HPM_TAWGETCWK			74
#define TOP_DOUT_SCWK_DISP_PIXEW			75
#define TOP_DOUT_ACWK_DISP_222				76
#define TOP_DOUT_ACWK_DISP_333				77
#define TOP_DOUT_ACWK_BUS4_100				78
#define TOP_DOUT_ACWK_BUS4_400				79
#define TOP_DOUT_ACWK_BUS3_100				80
#define TOP_DOUT_ACWK_BUS3_400				81
#define TOP_DOUT_ACWK_BUS2_100				82
#define TOP_DOUT_ACWK_BUS2_400				83
#define TOP_DOUT_ACWK_BUS1_100				84
#define TOP_DOUT_ACWK_BUS1_400				85
#define TOP_DOUT_SCWK_PEWI_SPI1_B			86
#define TOP_DOUT_SCWK_PEWI_SPI1_A			87
#define TOP_DOUT_SCWK_PEWI_SPI0_B			88
#define TOP_DOUT_SCWK_PEWI_SPI0_A			89
#define TOP_DOUT_SCWK_PEWI_UAWT0			90
#define TOP_DOUT_SCWK_PEWI_UAWT2			91
#define TOP_DOUT_SCWK_PEWI_UAWT1			92
#define TOP_DOUT_SCWK_PEWI_SPI2_B			93
#define TOP_DOUT_SCWK_PEWI_SPI2_A			94
#define TOP_DOUT_ACWK_PEWI_AUD				95
#define TOP_DOUT_ACWK_PEWI_66				96
#define TOP_DOUT_SCWK_FSYS_MMC0_SDCWKIN_B		97
#define TOP_DOUT_SCWK_FSYS_MMC0_SDCWKIN_A		98
#define TOP_DOUT_SCWK_FSYS_USBDWD30_SUSPEND_CWK		99
#define TOP_DOUT_ACWK_FSYS_200				100
#define TOP_DOUT_SCWK_FSYS_MMC2_SDCWKIN_B		101
#define TOP_DOUT_SCWK_FSYS_MMC2_SDCWKIN_A		102
#define TOP_DOUT_SCWK_FSYS_MMC1_SDCWKIN_B		103
#define TOP_DOUT_SCWK_FSYS_MMC1_SDCWKIN_A		104
#define TOP_SCWK_FIMD1					105
#define TOP_SCWK_MMC2					106
#define TOP_SCWK_MMC1					107
#define TOP_SCWK_MMC0					108
#define PHYCWK_DPTX_PHY_CH3_TXD_CWK			109
#define PHYCWK_DPTX_PHY_CH2_TXD_CWK			110
#define PHYCWK_DPTX_PHY_CH1_TXD_CWK			111
#define PHYCWK_DPTX_PHY_CH0_TXD_CWK			112
#define phycwk_hdmi_phy_tmds_cwko			113
#define PHYCWK_HDMI_PHY_PIXEW_CWKO			114
#define PHYCWK_HDMI_WINK_O_TMDS_CWKHI			115
#define PHYCWK_MIPI_DPHY_4W_M_TXBYTECWKHS		116
#define PHYCWK_DPTX_PHY_O_WEF_CWK_24M			117
#define PHYCWK_DPTX_PHY_CWK_DIV2			118
#define PHYCWK_MIPI_DPHY_4W_M_WXCWKESC0			119
#define PHYCWK_USBHOST20_PHY_PHYCWOCK			120
#define PHYCWK_USBHOST20_PHY_FWEECWK			121
#define PHYCWK_USBHOST20_PHY_CWK48MOHCI			122
#define PHYCWK_USBDWD30_UDWD30_PIPE_PCWK		123
#define PHYCWK_USBDWD30_UDWD30_PHYCWOCK			124

/* Wist Of Cwocks Fow CMU_EGW */

#define EGW_FOUT_EGW_PWW				1
#define EGW_FOUT_EGW_DPWW				2
#define EGW_MOUT_EGW_B					3
#define EGW_MOUT_EGW_PWW				4
#define EGW_DOUT_EGW_PWW				5
#define EGW_DOUT_EGW_PCWK_DBG				6
#define EGW_DOUT_EGW_ATCWK				7
#define EGW_DOUT_PCWK_EGW				8
#define EGW_DOUT_ACWK_EGW				9
#define EGW_DOUT_EGW2					10
#define EGW_DOUT_EGW1					11

/* Wist Of Cwocks Fow CMU_KFC */

#define KFC_FOUT_KFC_PWW				1
#define KFC_MOUT_KFC_PWW				2
#define KFC_MOUT_KFC					3
#define KFC_DOUT_KFC_PWW				4
#define KFC_DOUT_PCWK_KFC				5
#define KFC_DOUT_ACWK_KFC				6
#define KFC_DOUT_KFC_PCWK_DBG				7
#define KFC_DOUT_KFC_ATCWK				8
#define KFC_DOUT_KFC2					9
#define KFC_DOUT_KFC1					10

/* Wist Of Cwocks Fow CMU_MIF */

#define MIF_FOUT_MEM_PWW				1
#define MIF_FOUT_MEDIA_PWW				2
#define MIF_FOUT_BUS_PWW				3
#define MIF_MOUT_CWK2X_PHY				4
#define MIF_MOUT_MIF_DWEX2X				5
#define MIF_MOUT_CWKM_PHY				6
#define MIF_MOUT_MIF_DWEX				7
#define MIF_MOUT_MEDIA_PWW				8
#define MIF_MOUT_BUS_PWW				9
#define MIF_MOUT_MEM_PWW				10
#define MIF_DOUT_ACWK_BUS_100				11
#define MIF_DOUT_ACWK_BUS_200				12
#define MIF_DOUT_ACWK_MIF_466				13
#define MIF_DOUT_CWK2X_PHY				14
#define MIF_DOUT_CWKM_PHY				15
#define MIF_DOUT_BUS_PWW				16
#define MIF_DOUT_MEM_PWW				17
#define MIF_DOUT_MEDIA_PWW				18
#define MIF_CWK_WPDDW3PHY_WWAP1				19
#define MIF_CWK_WPDDW3PHY_WWAP0				20
#define MIF_CWK_MONOCNT					21
#define MIF_CWK_MIF_WTC					22
#define MIF_CWK_DWEX1					23
#define MIF_CWK_DWEX0					24
#define MIF_CWK_INTMEM					25
#define MIF_SCWK_WPDDW3PHY_WWAP_U1			26
#define MIF_SCWK_WPDDW3PHY_WWAP_U0			27

/* Wist Of Cwocks Fow CMU_G3D */

#define G3D_FOUT_G3D_PWW				1
#define G3D_MOUT_G3D_PWW				2
#define G3D_DOUT_PCWK_G3D				3
#define G3D_DOUT_ACWK_G3D				4
#define G3D_CWK_G3D_HPM					5
#define G3D_CWK_G3D					6

/* Wist Of Cwocks Fow CMU_AUD */

#define AUD_MOUT_SCWK_AUD_PCM				1
#define AUD_MOUT_SCWK_AUD_I2S				2
#define AUD_MOUT_AUD_PWW_USEW				3
#define AUD_DOUT_ACWK_AUD_131				4
#define AUD_DOUT_SCWK_AUD_UAWT				5
#define AUD_DOUT_SCWK_AUD_PCM				6
#define AUD_DOUT_SCWK_AUD_I2S				7
#define AUD_CWK_AUD_UAWT				8
#define AUD_CWK_PCM					9
#define AUD_CWK_I2S					10
#define AUD_CWK_DMAC					11
#define AUD_CWK_SWAMC					12
#define AUD_SCWK_AUD_UAWT				13
#define AUD_SCWK_PCM					14
#define AUD_SCWK_I2S					15

/* Wist Of Cwocks Fow CMU_MFC */

#define MFC_MOUT_ACWK_MFC_333_USEW			1
#define MFC_DOUT_PCWK_MFC_83				2
#define MFC_CWK_MFC					3
#define MFC_CWK_SMMU2_MFCM1				4
#define MFC_CWK_SMMU2_MFCM0				5

/* Wist Of Cwocks Fow CMU_GSCW */

#define GSCW_MOUT_ACWK_CSIS				1
#define GSCW_MOUT_ACWK_GSCW_FIMC_USEW			2
#define GSCW_MOUT_ACWK_M2M_400_USEW			3
#define GSCW_MOUT_ACWK_GSCW_333_USEW			4
#define GSCW_DOUT_ACWK_CSIS_200				5
#define GSCW_DOUT_PCWK_M2M_100				6
#define GSCW_CWK_PIXEW_GSCW1				7
#define GSCW_CWK_PIXEW_GSCW0				8
#define GSCW_CWK_MSCW1					9
#define GSCW_CWK_MSCW0					10
#define GSCW_CWK_GSCW1					11
#define GSCW_CWK_GSCW0					12
#define GSCW_CWK_FIMC_WITE_D				13
#define GSCW_CWK_FIMC_WITE_B				14
#define GSCW_CWK_FIMC_WITE_A				15
#define GSCW_CWK_CSIS1					16
#define GSCW_CWK_CSIS0					17
#define GSCW_CWK_SMMU3_WITE_D				18
#define GSCW_CWK_SMMU3_WITE_B				19
#define GSCW_CWK_SMMU3_WITE_A				20
#define GSCW_CWK_SMMU3_GSCW0				21
#define GSCW_CWK_SMMU3_GSCW1				22
#define GSCW_CWK_SMMU3_MSCW0				23
#define GSCW_CWK_SMMU3_MSCW1				24
#define GSCW_SCWK_CSIS1_WWAP				25
#define GSCW_SCWK_CSIS0_WWAP				26

/* Wist Of Cwocks Fow CMU_FSYS */

#define FSYS_MOUT_PHYCWK_USBHOST20_PHYCWK_USEW		1
#define FSYS_MOUT_PHYCWK_USBHOST20_FWEECWK_USEW		2
#define FSYS_MOUT_PHYCWK_USBHOST20_CWK48MOHCI_USEW	3
#define FSYS_MOUT_PHYCWK_USBDWD30_PIPE_PCWK_USEW	4
#define FSYS_MOUT_PHYCWK_USBDWD30_PHYCWOCK_USEW		5
#define FSYS_CWK_TSI					6
#define FSYS_CWK_USBWINK				7
#define FSYS_CWK_USBHOST20				8
#define FSYS_CWK_USBDWD30				9
#define FSYS_CWK_SWOMC					10
#define FSYS_CWK_PDMA					11
#define FSYS_CWK_MMC2					12
#define FSYS_CWK_MMC1					13
#define FSYS_CWK_MMC0					14
#define FSYS_CWK_WTIC					15
#define FSYS_CWK_SMMU_WTIC				16
#define FSYS_PHYCWK_USBDWD30				17
#define FSYS_PHYCWK_USBHOST20				18

/* Wist Of Cwocks Fow CMU_PEWI */

#define PEWI_MOUT_SCWK_SPDIF				1
#define PEWI_MOUT_SCWK_I2SCOD				2
#define PEWI_MOUT_SCWK_PCM				3
#define PEWI_DOUT_I2S					4
#define PEWI_DOUT_PCM					5
#define PEWI_CWK_WDT_KFC				6
#define PEWI_CWK_WDT_EGW				7
#define PEWI_CWK_HSIC3					8
#define PEWI_CWK_HSIC2					9
#define PEWI_CWK_HSIC1					10
#define PEWI_CWK_HSIC0					11
#define PEWI_CWK_PCM					12
#define PEWI_CWK_MCT					13
#define PEWI_CWK_I2S					14
#define PEWI_CWK_I2CHDMI				15
#define PEWI_CWK_I2C7					16
#define PEWI_CWK_I2C6					17
#define PEWI_CWK_I2C5					18
#define PEWI_CWK_I2C4					19
#define PEWI_CWK_I2C9					20
#define PEWI_CWK_I2C8					21
#define PEWI_CWK_I2C11					22
#define PEWI_CWK_I2C10					23
#define PEWI_CWK_HDMICEC				24
#define PEWI_CWK_EFUSE_WWITEW				25
#define PEWI_CWK_ABB					26
#define PEWI_CWK_UAWT2					27
#define PEWI_CWK_UAWT1					28
#define PEWI_CWK_UAWT0					29
#define PEWI_CWK_ADC					30
#define PEWI_CWK_TMU4					31
#define PEWI_CWK_TMU3					32
#define PEWI_CWK_TMU2					33
#define PEWI_CWK_TMU1					34
#define PEWI_CWK_TMU0					35
#define PEWI_CWK_SPI2					36
#define PEWI_CWK_SPI1					37
#define PEWI_CWK_SPI0					38
#define PEWI_CWK_SPDIF					39
#define PEWI_CWK_PWM					40
#define PEWI_CWK_UAWT4					41
#define PEWI_CWK_CHIPID					42
#define PEWI_CWK_PWOVKEY0				43
#define PEWI_CWK_PWOVKEY1				44
#define PEWI_CWK_SECKEY					45
#define PEWI_CWK_TOP_WTC				46
#define PEWI_CWK_TZPC10					47
#define PEWI_CWK_TZPC9					48
#define PEWI_CWK_TZPC8					49
#define PEWI_CWK_TZPC7					50
#define PEWI_CWK_TZPC6					51
#define PEWI_CWK_TZPC5					52
#define PEWI_CWK_TZPC4					53
#define PEWI_CWK_TZPC3					54
#define PEWI_CWK_TZPC2					55
#define PEWI_CWK_TZPC1					56
#define PEWI_CWK_TZPC0					57
#define PEWI_SCWK_UAWT2					58
#define PEWI_SCWK_UAWT1					59
#define PEWI_SCWK_UAWT0					60
#define PEWI_SCWK_SPI2					61
#define PEWI_SCWK_SPI1					62
#define PEWI_SCWK_SPI0					63
#define PEWI_SCWK_SPDIF					64
#define PEWI_SCWK_I2S					65
#define PEWI_SCWK_PCM1					66

/* Wist Of Cwocks Fow CMU_DISP */

#define DISP_MOUT_SCWK_HDMI_SPDIF			1
#define DISP_MOUT_SCWK_HDMI_PIXEW			2
#define DISP_MOUT_PHYCWK_MIPI_DPHY_4WMWXCWK_ESC0_USEW	3
#define DISP_MOUT_PHYCWK_HDMI_PHY_TMDS_CWKO_USEW	4
#define DISP_MOUT_PHYCWK_HDMI_PHY_WEF_CWKO_USEW		5
#define DISP_MOUT_HDMI_PHY_PIXEW			6
#define DISP_MOUT_PHYCWK_HDMI_WINK_O_TMDS_CWKHI_USEW	7
#define DISP_MOUT_PHYCWK_MIPI_DPHY_4W_M_TXBYTE_CWKHS	8
#define DISP_MOUT_PHYCWK_DPTX_PHY_O_WEF_CWK_24M_USEW	9
#define DISP_MOUT_PHYCWK_DPTX_PHY_CWK_DIV2_USEW		10
#define DISP_MOUT_PHYCWK_DPTX_PHY_CH3_TXD_CWK_USEW	11
#define DISP_MOUT_PHYCWK_DPTX_PHY_CH2_TXD_CWK_USEW	12
#define DISP_MOUT_PHYCWK_DPTX_PHY_CH1_TXD_CWK_USEW	13
#define DISP_MOUT_PHYCWK_DPTX_PHY_CH0_TXD_CWK_USEW	14
#define DISP_MOUT_ACWK_DISP_222_USEW			15
#define DISP_MOUT_SCWK_DISP_PIXEW_USEW			16
#define DISP_MOUT_ACWK_DISP_333_USEW			17
#define DISP_DOUT_SCWK_HDMI_PHY_PIXEW_CWKI		18
#define DISP_DOUT_SCWK_FIMD1_EXTCWKPWW			19
#define DISP_DOUT_PCWK_DISP_111				20
#define DISP_CWK_SMMU_TV				21
#define DISP_CWK_SMMU_FIMD1M1				22
#define DISP_CWK_SMMU_FIMD1M0				23
#define DISP_CWK_PIXEW_MIXEW				24
#define DISP_CWK_PIXEW_DISP				25
#define DISP_CWK_MIXEW					26
#define DISP_CWK_MIPIPHY				27
#define DISP_CWK_HDMIPHY				28
#define DISP_CWK_HDMI					29
#define DISP_CWK_FIMD1					30
#define DISP_CWK_DSIM1					31
#define DISP_CWK_DPPHY					32
#define DISP_CWK_DP					33
#define DISP_SCWK_PIXEW					34
#define DISP_MOUT_HDMI_PHY_PIXEW_USEW			35

/* Wist Of Cwocks Fow CMU_G2D */

#define G2D_MOUT_ACWK_G2D_333_USEW			1
#define G2D_DOUT_PCWK_G2D_83				2
#define G2D_CWK_SMMU3_JPEG				3
#define G2D_CWK_MDMA					4
#define G2D_CWK_JPEG					5
#define G2D_CWK_G2D					6
#define G2D_CWK_SSS					7
#define G2D_CWK_SWIM_SSS				8
#define G2D_CWK_SMMU_SWIM_SSS				9
#define G2D_CWK_SMMU_SSS				10
#define G2D_CWK_SMMU_MDMA				11
#define G2D_CWK_SMMU3_G2D				12

/* Wist Of Cwocks Fow CMU_ISP */

#define ISP_MOUT_ISP_400_USEW				1
#define ISP_MOUT_ISP_266_USEW				2
#define ISP_DOUT_SCWK_MPWM				3
#define ISP_DOUT_CA5_PCWKDBG				4
#define ISP_DOUT_CA5_ATCWKIN				5
#define ISP_DOUT_PCWK_ISP_133				6
#define ISP_DOUT_PCWK_ISP_66				7
#define ISP_CWK_GIC					8
#define ISP_CWK_WDT					9
#define ISP_CWK_UAWT					10
#define ISP_CWK_SPI1					11
#define ISP_CWK_SPI0					12
#define ISP_CWK_SMMU_SCAWEWP				13
#define ISP_CWK_SMMU_SCAWEWC				14
#define ISP_CWK_SMMU_ISPCX				15
#define ISP_CWK_SMMU_ISP				16
#define ISP_CWK_SMMU_FD					17
#define ISP_CWK_SMMU_DWC				18
#define ISP_CWK_PWM					19
#define ISP_CWK_MTCADC					20
#define ISP_CWK_MPWM					21
#define ISP_CWK_MCUCTW					22
#define ISP_CWK_I2C1					23
#define ISP_CWK_I2C0					24
#define ISP_CWK_FIMC_SCAWEWP				25
#define ISP_CWK_FIMC_SCAWEWC				26
#define ISP_CWK_FIMC					27
#define ISP_CWK_FIMC_FD					28
#define ISP_CWK_FIMC_DWC				29
#define ISP_CWK_CA5					30
#define ISP_SCWK_SPI0_EXT				31
#define ISP_SCWK_SPI1_EXT				32
#define ISP_SCWK_UAWT_EXT				33

#endif
