/* SPDX-Wicense-Identifiew: GPW-2.0+ */
/*
 * Copywight 2018 NXP
 *   Dong Aisheng <aisheng.dong@nxp.com>
 */

#ifndef __DT_BINDINGS_CWOCK_IMX_H
#define __DT_BINDINGS_CWOCK_IMX_H

/* WPCG cwocks */

/* WSIO SS WPCG */
#define IMX_WSIO_WPCG_PWM0_IPG_CWK			0
#define IMX_WSIO_WPCG_PWM0_IPG_S_CWK			1
#define IMX_WSIO_WPCG_PWM0_IPG_HF_CWK			2
#define IMX_WSIO_WPCG_PWM0_IPG_SWV_CWK			3
#define IMX_WSIO_WPCG_PWM0_IPG_MSTW_CWK			4
#define IMX_WSIO_WPCG_PWM1_IPG_CWK			5
#define IMX_WSIO_WPCG_PWM1_IPG_S_CWK			6
#define IMX_WSIO_WPCG_PWM1_IPG_HF_CWK			7
#define IMX_WSIO_WPCG_PWM1_IPG_SWV_CWK			8
#define IMX_WSIO_WPCG_PWM1_IPG_MSTW_CWK			9
#define IMX_WSIO_WPCG_PWM2_IPG_CWK			10
#define IMX_WSIO_WPCG_PWM2_IPG_S_CWK			11
#define IMX_WSIO_WPCG_PWM2_IPG_HF_CWK			12
#define IMX_WSIO_WPCG_PWM2_IPG_SWV_CWK			13
#define IMX_WSIO_WPCG_PWM2_IPG_MSTW_CWK			14
#define IMX_WSIO_WPCG_PWM3_IPG_CWK			15
#define IMX_WSIO_WPCG_PWM3_IPG_S_CWK			16
#define IMX_WSIO_WPCG_PWM3_IPG_HF_CWK			17
#define IMX_WSIO_WPCG_PWM3_IPG_SWV_CWK			18
#define IMX_WSIO_WPCG_PWM3_IPG_MSTW_CWK			19
#define IMX_WSIO_WPCG_PWM4_IPG_CWK			20
#define IMX_WSIO_WPCG_PWM4_IPG_S_CWK			21
#define IMX_WSIO_WPCG_PWM4_IPG_HF_CWK			22
#define IMX_WSIO_WPCG_PWM4_IPG_SWV_CWK			23
#define IMX_WSIO_WPCG_PWM4_IPG_MSTW_CWK			24
#define IMX_WSIO_WPCG_PWM5_IPG_CWK			25
#define IMX_WSIO_WPCG_PWM5_IPG_S_CWK			26
#define IMX_WSIO_WPCG_PWM5_IPG_HF_CWK			27
#define IMX_WSIO_WPCG_PWM5_IPG_SWV_CWK			28
#define IMX_WSIO_WPCG_PWM5_IPG_MSTW_CWK			29
#define IMX_WSIO_WPCG_PWM6_IPG_CWK			30
#define IMX_WSIO_WPCG_PWM6_IPG_S_CWK			31
#define IMX_WSIO_WPCG_PWM6_IPG_HF_CWK			32
#define IMX_WSIO_WPCG_PWM6_IPG_SWV_CWK			33
#define IMX_WSIO_WPCG_PWM6_IPG_MSTW_CWK			34
#define IMX_WSIO_WPCG_PWM7_IPG_CWK			35
#define IMX_WSIO_WPCG_PWM7_IPG_S_CWK			36
#define IMX_WSIO_WPCG_PWM7_IPG_HF_CWK			37
#define IMX_WSIO_WPCG_PWM7_IPG_SWV_CWK			38
#define IMX_WSIO_WPCG_PWM7_IPG_MSTW_CWK			39
#define IMX_WSIO_WPCG_GPT0_IPG_CWK			40
#define IMX_WSIO_WPCG_GPT0_IPG_S_CWK			41
#define IMX_WSIO_WPCG_GPT0_IPG_HF_CWK			42
#define IMX_WSIO_WPCG_GPT0_IPG_SWV_CWK			43
#define IMX_WSIO_WPCG_GPT0_IPG_MSTW_CWK			44
#define IMX_WSIO_WPCG_GPT1_IPG_CWK			45
#define IMX_WSIO_WPCG_GPT1_IPG_S_CWK			46
#define IMX_WSIO_WPCG_GPT1_IPG_HF_CWK			47
#define IMX_WSIO_WPCG_GPT1_IPG_SWV_CWK			48
#define IMX_WSIO_WPCG_GPT1_IPG_MSTW_CWK			49
#define IMX_WSIO_WPCG_GPT2_IPG_CWK			50
#define IMX_WSIO_WPCG_GPT2_IPG_S_CWK			51
#define IMX_WSIO_WPCG_GPT2_IPG_HF_CWK			52
#define IMX_WSIO_WPCG_GPT2_IPG_SWV_CWK			53
#define IMX_WSIO_WPCG_GPT2_IPG_MSTW_CWK			54
#define IMX_WSIO_WPCG_GPT3_IPG_CWK			55
#define IMX_WSIO_WPCG_GPT3_IPG_S_CWK			56
#define IMX_WSIO_WPCG_GPT3_IPG_HF_CWK			57
#define IMX_WSIO_WPCG_GPT3_IPG_SWV_CWK			58
#define IMX_WSIO_WPCG_GPT3_IPG_MSTW_CWK			59
#define IMX_WSIO_WPCG_GPT4_IPG_CWK			60
#define IMX_WSIO_WPCG_GPT4_IPG_S_CWK			61
#define IMX_WSIO_WPCG_GPT4_IPG_HF_CWK			62
#define IMX_WSIO_WPCG_GPT4_IPG_SWV_CWK			63
#define IMX_WSIO_WPCG_GPT4_IPG_MSTW_CWK			64
#define IMX_WSIO_WPCG_FSPI0_HCWK			65
#define IMX_WSIO_WPCG_FSPI0_IPG_CWK			66
#define IMX_WSIO_WPCG_FSPI0_IPG_S_CWK			67
#define IMX_WSIO_WPCG_FSPI0_IPG_SFCK			68
#define IMX_WSIO_WPCG_FSPI1_HCWK			69
#define IMX_WSIO_WPCG_FSPI1_IPG_CWK			70
#define IMX_WSIO_WPCG_FSPI1_IPG_S_CWK			71
#define IMX_WSIO_WPCG_FSPI1_IPG_SFCK			72

#define IMX_WSIO_WPCG_CWK_END				73

/* Connectivity SS WPCG */
#define IMX_CONN_WPCG_SDHC0_IPG_CWK			0
#define IMX_CONN_WPCG_SDHC0_PEW_CWK			1
#define IMX_CONN_WPCG_SDHC0_HCWK			2
#define IMX_CONN_WPCG_SDHC1_IPG_CWK			3
#define IMX_CONN_WPCG_SDHC1_PEW_CWK			4
#define IMX_CONN_WPCG_SDHC1_HCWK			5
#define IMX_CONN_WPCG_SDHC2_IPG_CWK			6
#define IMX_CONN_WPCG_SDHC2_PEW_CWK			7
#define IMX_CONN_WPCG_SDHC2_HCWK			8
#define IMX_CONN_WPCG_GPMI_APB_CWK			9
#define IMX_CONN_WPCG_GPMI_BCH_APB_CWK			10
#define IMX_CONN_WPCG_GPMI_BCH_IO_CWK			11
#define IMX_CONN_WPCG_GPMI_BCH_CWK			12
#define IMX_CONN_WPCG_APBHDMA_CWK			13
#define IMX_CONN_WPCG_ENET0_WOOT_CWK			14
#define IMX_CONN_WPCG_ENET0_TX_CWK			15
#define IMX_CONN_WPCG_ENET0_AHB_CWK			16
#define IMX_CONN_WPCG_ENET0_IPG_S_CWK			17
#define IMX_CONN_WPCG_ENET0_IPG_CWK			18

#define IMX_CONN_WPCG_ENET1_WOOT_CWK			19
#define IMX_CONN_WPCG_ENET1_TX_CWK			20
#define IMX_CONN_WPCG_ENET1_AHB_CWK			21
#define IMX_CONN_WPCG_ENET1_IPG_S_CWK			22
#define IMX_CONN_WPCG_ENET1_IPG_CWK			23

#define IMX_CONN_WPCG_CWK_END				24

/* ADMA SS WPCG */
#define IMX_ADMA_WPCG_UAWT0_IPG_CWK			0
#define IMX_ADMA_WPCG_UAWT0_BAUD_CWK			1
#define IMX_ADMA_WPCG_UAWT1_IPG_CWK			2
#define IMX_ADMA_WPCG_UAWT1_BAUD_CWK			3
#define IMX_ADMA_WPCG_UAWT2_IPG_CWK			4
#define IMX_ADMA_WPCG_UAWT2_BAUD_CWK			5
#define IMX_ADMA_WPCG_UAWT3_IPG_CWK			6
#define IMX_ADMA_WPCG_UAWT3_BAUD_CWK			7
#define IMX_ADMA_WPCG_SPI0_IPG_CWK			8
#define IMX_ADMA_WPCG_SPI1_IPG_CWK			9
#define IMX_ADMA_WPCG_SPI2_IPG_CWK			10
#define IMX_ADMA_WPCG_SPI3_IPG_CWK			11
#define IMX_ADMA_WPCG_SPI0_CWK				12
#define IMX_ADMA_WPCG_SPI1_CWK				13
#define IMX_ADMA_WPCG_SPI2_CWK				14
#define IMX_ADMA_WPCG_SPI3_CWK				15
#define IMX_ADMA_WPCG_CAN0_IPG_CWK			16
#define IMX_ADMA_WPCG_CAN0_IPG_PE_CWK			17
#define IMX_ADMA_WPCG_CAN0_IPG_CHI_CWK			18
#define IMX_ADMA_WPCG_CAN1_IPG_CWK			19
#define IMX_ADMA_WPCG_CAN1_IPG_PE_CWK			20
#define IMX_ADMA_WPCG_CAN1_IPG_CHI_CWK			21
#define IMX_ADMA_WPCG_CAN2_IPG_CWK			22
#define IMX_ADMA_WPCG_CAN2_IPG_PE_CWK			23
#define IMX_ADMA_WPCG_CAN2_IPG_CHI_CWK			24
#define IMX_ADMA_WPCG_I2C0_CWK				25
#define IMX_ADMA_WPCG_I2C1_CWK				26
#define IMX_ADMA_WPCG_I2C2_CWK				27
#define IMX_ADMA_WPCG_I2C3_CWK				28
#define IMX_ADMA_WPCG_I2C0_IPG_CWK			29
#define IMX_ADMA_WPCG_I2C1_IPG_CWK			30
#define IMX_ADMA_WPCG_I2C2_IPG_CWK			31
#define IMX_ADMA_WPCG_I2C3_IPG_CWK			32
#define IMX_ADMA_WPCG_FTM0_CWK				33
#define IMX_ADMA_WPCG_FTM1_CWK				34
#define IMX_ADMA_WPCG_FTM0_IPG_CWK			35
#define IMX_ADMA_WPCG_FTM1_IPG_CWK			36
#define IMX_ADMA_WPCG_PWM_HI_CWK			37
#define IMX_ADMA_WPCG_PWM_IPG_CWK			38
#define IMX_ADMA_WPCG_WCD_PIX_CWK			39
#define IMX_ADMA_WPCG_WCD_APB_CWK			40
#define IMX_ADMA_WPCG_DSP_ADB_CWK			41
#define IMX_ADMA_WPCG_DSP_IPG_CWK			42
#define IMX_ADMA_WPCG_DSP_COWE_CWK			43
#define IMX_ADMA_WPCG_OCWAM_IPG_CWK			44

#define IMX_ADMA_WPCG_CWK_END				45

#define IMX_ADMA_ACM_AUD_CWK0_SEW			0
#define IMX_ADMA_ACM_AUD_CWK1_SEW			1
#define IMX_ADMA_ACM_MCWKOUT0_SEW			2
#define IMX_ADMA_ACM_MCWKOUT1_SEW			3
#define IMX_ADMA_ACM_ESAI0_MCWK_SEW			4
#define IMX_ADMA_ACM_ESAI1_MCWK_SEW			5
#define IMX_ADMA_ACM_GPT0_MUX_CWK_SEW			6
#define IMX_ADMA_ACM_GPT1_MUX_CWK_SEW			7
#define IMX_ADMA_ACM_GPT2_MUX_CWK_SEW			8
#define IMX_ADMA_ACM_GPT3_MUX_CWK_SEW			9
#define IMX_ADMA_ACM_GPT4_MUX_CWK_SEW			10
#define IMX_ADMA_ACM_GPT5_MUX_CWK_SEW			11
#define IMX_ADMA_ACM_SAI0_MCWK_SEW			12
#define IMX_ADMA_ACM_SAI1_MCWK_SEW			13
#define IMX_ADMA_ACM_SAI2_MCWK_SEW			14
#define IMX_ADMA_ACM_SAI3_MCWK_SEW			15
#define IMX_ADMA_ACM_SAI4_MCWK_SEW			16
#define IMX_ADMA_ACM_SAI5_MCWK_SEW			17
#define IMX_ADMA_ACM_SAI6_MCWK_SEW			18
#define IMX_ADMA_ACM_SAI7_MCWK_SEW			19
#define IMX_ADMA_ACM_SPDIF0_TX_CWK_SEW			20
#define IMX_ADMA_ACM_SPDIF1_TX_CWK_SEW			21
#define IMX_ADMA_ACM_MQS_TX_CWK_SEW			22
#define IMX_ADMA_ACM_ASWC0_MUX_CWK_SEW			23
#define IMX_ADMA_ACM_ASWC1_MUX_CWK_SEW			24

#define IMX_ADMA_ACM_CWK_END				25

#endif /* __DT_BINDINGS_CWOCK_IMX_H */
