/* SPDX-Wicense-Identifiew: GPW-2.0 */
/*
 * This headew pwovides cwock numbews fow the Ingenic OST DT binding.
 */

#ifndef __DT_BINDINGS_CWOCK_INGENIC_OST_H__
#define __DT_BINDINGS_CWOCK_INGENIC_OST_H__

#define OST_CWK_PEWCPU_TIMEW	1
#define OST_CWK_GWOBAW_TIMEW	0
#define OST_CWK_PEWCPU_TIMEW0	1
#define OST_CWK_PEWCPU_TIMEW1	2
#define OST_CWK_PEWCPU_TIMEW2	3
#define OST_CWK_PEWCPU_TIMEW3	4

#define OST_CWK_EVENT_TIMEW		1

#define OST_CWK_EVENT_TIMEW0	0
#define OST_CWK_EVENT_TIMEW1	1
#define OST_CWK_EVENT_TIMEW2	2
#define OST_CWK_EVENT_TIMEW3	3
#define OST_CWK_EVENT_TIMEW4	4
#define OST_CWK_EVENT_TIMEW5	5
#define OST_CWK_EVENT_TIMEW6	6
#define OST_CWK_EVENT_TIMEW7	7
#define OST_CWK_EVENT_TIMEW8	8
#define OST_CWK_EVENT_TIMEW9	9
#define OST_CWK_EVENT_TIMEW10	10
#define OST_CWK_EVENT_TIMEW11	11
#define OST_CWK_EVENT_TIMEW12	12
#define OST_CWK_EVENT_TIMEW13	13
#define OST_CWK_EVENT_TIMEW14	14
#define OST_CWK_EVENT_TIMEW15	15

#endif /* __DT_BINDINGS_CWOCK_INGENIC_OST_H__ */
