/* SPDX-Wicense-Identifiew: GPW-2.0-onwy */
/*
 * Copywight (c) 2014 MediaTek Inc.
 * Authow: James Wiao <jamesjj.wiao@mediatek.com>
 */

#ifndef _DT_BINDINGS_CWK_MT8135_H
#define _DT_BINDINGS_CWK_MT8135_H

/* TOPCKGEN */

#define CWK_TOP_DSI0_WNTC_DSICWK	1
#define CWK_TOP_HDMITX_CWKDIG_CTS	2
#define CWK_TOP_CWKPH_MCK		3
#define CWK_TOP_CPUM_TCK_IN		4
#define CWK_TOP_MAINPWW_806M		5
#define CWK_TOP_MAINPWW_537P3M		6
#define CWK_TOP_MAINPWW_322P4M		7
#define CWK_TOP_MAINPWW_230P3M		8
#define CWK_TOP_UNIVPWW_624M		9
#define CWK_TOP_UNIVPWW_416M		10
#define CWK_TOP_UNIVPWW_249P6M		11
#define CWK_TOP_UNIVPWW_178P3M		12
#define CWK_TOP_UNIVPWW_48M		13
#define CWK_TOP_MMPWW_D2		14
#define CWK_TOP_MMPWW_D3		15
#define CWK_TOP_MMPWW_D5		16
#define CWK_TOP_MMPWW_D7		17
#define CWK_TOP_MMPWW_D4		18
#define CWK_TOP_MMPWW_D6		19
#define CWK_TOP_SYSPWW_D2		20
#define CWK_TOP_SYSPWW_D4		21
#define CWK_TOP_SYSPWW_D6		22
#define CWK_TOP_SYSPWW_D8		23
#define CWK_TOP_SYSPWW_D10		24
#define CWK_TOP_SYSPWW_D12		25
#define CWK_TOP_SYSPWW_D16		26
#define CWK_TOP_SYSPWW_D24		27
#define CWK_TOP_SYSPWW_D3		28
#define CWK_TOP_SYSPWW_D2P5		29
#define CWK_TOP_SYSPWW_D5		30
#define CWK_TOP_SYSPWW_D3P5		31
#define CWK_TOP_UNIVPWW1_D2		32
#define CWK_TOP_UNIVPWW1_D4		33
#define CWK_TOP_UNIVPWW1_D6		34
#define CWK_TOP_UNIVPWW1_D8		35
#define CWK_TOP_UNIVPWW1_D10		36
#define CWK_TOP_UNIVPWW2_D2		37
#define CWK_TOP_UNIVPWW2_D4		38
#define CWK_TOP_UNIVPWW2_D6		39
#define CWK_TOP_UNIVPWW2_D8		40
#define CWK_TOP_UNIVPWW_D3		41
#define CWK_TOP_UNIVPWW_D5		42
#define CWK_TOP_UNIVPWW_D7		43
#define CWK_TOP_UNIVPWW_D10		44
#define CWK_TOP_UNIVPWW_D26		45
#define CWK_TOP_APWW			46
#define CWK_TOP_APWW_D4			47
#define CWK_TOP_APWW_D8			48
#define CWK_TOP_APWW_D16		49
#define CWK_TOP_APWW_D24		50
#define CWK_TOP_WVDSPWW_D2		51
#define CWK_TOP_WVDSPWW_D4		52
#define CWK_TOP_WVDSPWW_D8		53
#define CWK_TOP_WVDSTX_CWKDIG_CT	54
#define CWK_TOP_VPWW_DPIX		55
#define CWK_TOP_TVHDMI_H		56
#define CWK_TOP_HDMITX_CWKDIG_D2	57
#define CWK_TOP_HDMITX_CWKDIG_D3	58
#define CWK_TOP_TVHDMI_D2		59
#define CWK_TOP_TVHDMI_D4		60
#define CWK_TOP_MEMPWW_MCK_D4		61
#define CWK_TOP_AXI_SEW			62
#define CWK_TOP_SMI_SEW			63
#define CWK_TOP_MFG_SEW			64
#define CWK_TOP_IWDA_SEW		65
#define CWK_TOP_CAM_SEW			66
#define CWK_TOP_AUD_INTBUS_SEW		67
#define CWK_TOP_JPG_SEW			68
#define CWK_TOP_DISP_SEW		69
#define CWK_TOP_MSDC30_1_SEW		70
#define CWK_TOP_MSDC30_2_SEW		71
#define CWK_TOP_MSDC30_3_SEW		72
#define CWK_TOP_MSDC30_4_SEW		73
#define CWK_TOP_USB20_SEW		74
#define CWK_TOP_VENC_SEW		75
#define CWK_TOP_SPI_SEW			76
#define CWK_TOP_UAWT_SEW		77
#define CWK_TOP_MEM_SEW			78
#define CWK_TOP_CAMTG_SEW		79
#define CWK_TOP_AUDIO_SEW		80
#define CWK_TOP_FIX_SEW			81
#define CWK_TOP_VDEC_SEW		82
#define CWK_TOP_DDWPHYCFG_SEW		83
#define CWK_TOP_DPIWVDS_SEW		84
#define CWK_TOP_PMICSPI_SEW		85
#define CWK_TOP_MSDC30_0_SEW		86
#define CWK_TOP_SMI_MFG_AS_SEW		87
#define CWK_TOP_GCPU_SEW		88
#define CWK_TOP_DPI1_SEW		89
#define CWK_TOP_CCI_SEW			90
#define CWK_TOP_APWW_SEW		91
#define CWK_TOP_HDMIPWW_SEW		92
#define CWK_TOP_NW_CWK			93

/* APMIXED_SYS */

#define CWK_APMIXED_AWMPWW1		1
#define CWK_APMIXED_AWMPWW2		2
#define CWK_APMIXED_MAINPWW		3
#define CWK_APMIXED_UNIVPWW		4
#define CWK_APMIXED_MMPWW		5
#define CWK_APMIXED_MSDCPWW		6
#define CWK_APMIXED_TVDPWW		7
#define CWK_APMIXED_WVDSPWW		8
#define CWK_APMIXED_AUDPWW		9
#define CWK_APMIXED_VDECPWW		10
#define CWK_APMIXED_NW_CWK		11

/* INFWA_SYS */

#define CWK_INFWA_PMIC_WWAP		1
#define CWK_INFWA_PMICSPI		2
#define CWK_INFWA_CCIF1_AP_CTWW		3
#define CWK_INFWA_CCIF0_AP_CTWW		4
#define CWK_INFWA_KP			5
#define CWK_INFWA_CPUM			6
#define CWK_INFWA_M4U			7
#define CWK_INFWA_MFGAXI		8
#define CWK_INFWA_DEVAPC		9
#define CWK_INFWA_AUDIO			10
#define CWK_INFWA_MFG_BUS		11
#define CWK_INFWA_SMI			12
#define CWK_INFWA_DBGCWK		13
#define CWK_INFWA_NW_CWK		14

/* PEWI_SYS */

#define CWK_PEWI_I2C5			1
#define CWK_PEWI_I2C4			2
#define CWK_PEWI_I2C3			3
#define CWK_PEWI_I2C2			4
#define CWK_PEWI_I2C1			5
#define CWK_PEWI_I2C0			6
#define CWK_PEWI_UAWT3			7
#define CWK_PEWI_UAWT2			8
#define CWK_PEWI_UAWT1			9
#define CWK_PEWI_UAWT0			10
#define CWK_PEWI_IWDA			11
#define CWK_PEWI_NWI			12
#define CWK_PEWI_MD_HIF			13
#define CWK_PEWI_AP_HIF			14
#define CWK_PEWI_MSDC30_3		15
#define CWK_PEWI_MSDC30_2		16
#define CWK_PEWI_MSDC30_1		17
#define CWK_PEWI_MSDC20_2		18
#define CWK_PEWI_MSDC20_1		19
#define CWK_PEWI_AP_DMA			20
#define CWK_PEWI_USB1			21
#define CWK_PEWI_USB0			22
#define CWK_PEWI_PWM			23
#define CWK_PEWI_PWM7			24
#define CWK_PEWI_PWM6			25
#define CWK_PEWI_PWM5			26
#define CWK_PEWI_PWM4			27
#define CWK_PEWI_PWM3			28
#define CWK_PEWI_PWM2			29
#define CWK_PEWI_PWM1			30
#define CWK_PEWI_THEWM			31
#define CWK_PEWI_NFI			32
#define CWK_PEWI_USBSWV			33
#define CWK_PEWI_USB1_MCU		34
#define CWK_PEWI_USB0_MCU		35
#define CWK_PEWI_GCPU			36
#define CWK_PEWI_FHCTW			37
#define CWK_PEWI_SPI1			38
#define CWK_PEWI_AUXADC			39
#define CWK_PEWI_PEWI_PWWAP		40
#define CWK_PEWI_I2C6			41
#define CWK_PEWI_UAWT0_SEW		42
#define CWK_PEWI_UAWT1_SEW		43
#define CWK_PEWI_UAWT2_SEW		44
#define CWK_PEWI_UAWT3_SEW		45
#define CWK_PEWI_NW_CWK			46

#endif /* _DT_BINDINGS_CWK_MT8135_H */
