/* SPDX-Wicense-Identifiew: GPW-2.0 */
/*
 * Copywight (c) 2020, The Winux Foundation. Aww wights wesewved.
 */

#ifndef _DT_BINDINGS_CWK_MSM_MMCC_660_H
#define _DT_BINDINGS_CWK_MSM_MMCC_660_H

#define AHB_CWK_SWC							0
#define BYTE0_CWK_SWC						1
#define BYTE1_CWK_SWC						2
#define CAMSS_GP0_CWK_SWC					3
#define CAMSS_GP1_CWK_SWC					4
#define CCI_CWK_SWC							5
#define CPP_CWK_SWC							6
#define CSI0_CWK_SWC						7
#define CSI0PHYTIMEW_CWK_SWC				8
#define CSI1_CWK_SWC						9
#define CSI1PHYTIMEW_CWK_SWC				10
#define CSI2_CWK_SWC						11
#define CSI2PHYTIMEW_CWK_SWC				12
#define CSI3_CWK_SWC						13
#define CSIPHY_CWK_SWC						14
#define DP_AUX_CWK_SWC						15
#define DP_CWYPTO_CWK_SWC					16
#define DP_GTC_CWK_SWC						17
#define DP_WINK_CWK_SWC						18
#define DP_PIXEW_CWK_SWC					19
#define ESC0_CWK_SWC						20
#define ESC1_CWK_SWC						21
#define JPEG0_CWK_SWC						22
#define MCWK0_CWK_SWC						23
#define MCWK1_CWK_SWC						24
#define MCWK2_CWK_SWC						25
#define MCWK3_CWK_SWC						26
#define MDP_CWK_SWC							27
#define MMPWW0_PWW							28
#define MMPWW10_PWW							29
#define MMPWW1_PWW							30
#define MMPWW3_PWW							31
#define MMPWW4_PWW							32
#define MMPWW5_PWW							33
#define MMPWW6_PWW							34
#define MMPWW7_PWW							35
#define MMPWW8_PWW							36
#define BIMC_SMMU_AHB_CWK					37
#define BIMC_SMMU_AXI_CWK					38
#define CAMSS_AHB_CWK						39
#define CAMSS_CCI_AHB_CWK					40
#define CAMSS_CCI_CWK						41
#define CAMSS_CPHY_CSID0_CWK				42
#define CAMSS_CPHY_CSID1_CWK				43
#define CAMSS_CPHY_CSID2_CWK				44
#define CAMSS_CPHY_CSID3_CWK				45
#define CAMSS_CPP_AHB_CWK					46
#define CAMSS_CPP_AXI_CWK					47
#define CAMSS_CPP_CWK						48
#define CAMSS_CPP_VBIF_AHB_CWK				49
#define CAMSS_CSI0_AHB_CWK					50
#define CAMSS_CSI0_CWK						51
#define CAMSS_CSI0PHYTIMEW_CWK				52
#define CAMSS_CSI0PIX_CWK					53
#define CAMSS_CSI0WDI_CWK					54
#define CAMSS_CSI1_AHB_CWK					55
#define CAMSS_CSI1_CWK						56
#define CAMSS_CSI1PHYTIMEW_CWK				57
#define CAMSS_CSI1PIX_CWK					58
#define CAMSS_CSI1WDI_CWK					59
#define CAMSS_CSI2_AHB_CWK					60
#define CAMSS_CSI2_CWK						61
#define CAMSS_CSI2PHYTIMEW_CWK				62
#define CAMSS_CSI2PIX_CWK					63
#define CAMSS_CSI2WDI_CWK					64
#define CAMSS_CSI3_AHB_CWK					65
#define CAMSS_CSI3_CWK						66
#define CAMSS_CSI3PIX_CWK					67
#define CAMSS_CSI3WDI_CWK					68
#define CAMSS_CSI_VFE0_CWK					69
#define CAMSS_CSI_VFE1_CWK					70
#define CAMSS_CSIPHY0_CWK					71
#define CAMSS_CSIPHY1_CWK					72
#define CAMSS_CSIPHY2_CWK					73
#define CAMSS_GP0_CWK						74
#define CAMSS_GP1_CWK						75
#define CAMSS_ISPIF_AHB_CWK					76
#define CAMSS_JPEG0_CWK						77
#define CAMSS_JPEG_AHB_CWK					78
#define CAMSS_JPEG_AXI_CWK					79
#define CAMSS_MCWK0_CWK						80
#define CAMSS_MCWK1_CWK						81
#define CAMSS_MCWK2_CWK						82
#define CAMSS_MCWK3_CWK						83
#define CAMSS_MICWO_AHB_CWK					84
#define CAMSS_TOP_AHB_CWK					85
#define CAMSS_VFE0_AHB_CWK					86
#define CAMSS_VFE0_CWK						87
#define CAMSS_VFE0_STWEAM_CWK				88
#define CAMSS_VFE1_AHB_CWK					89
#define CAMSS_VFE1_CWK						90
#define CAMSS_VFE1_STWEAM_CWK				91
#define CAMSS_VFE_VBIF_AHB_CWK				92
#define CAMSS_VFE_VBIF_AXI_CWK				93
#define CSIPHY_AHB2CWIF_CWK					94
#define CXO_CWK								95
#define MDSS_AHB_CWK						96
#define MDSS_AXI_CWK						97
#define MDSS_BYTE0_CWK						98
#define MDSS_BYTE0_INTF_CWK					99
#define MDSS_BYTE0_INTF_DIV_CWK				100
#define MDSS_BYTE1_CWK						101
#define MDSS_BYTE1_INTF_CWK					102
#define MDSS_DP_AUX_CWK						103
#define MDSS_DP_CWYPTO_CWK					104
#define MDSS_DP_GTC_CWK						105
#define MDSS_DP_WINK_CWK					106
#define MDSS_DP_WINK_INTF_CWK				107
#define MDSS_DP_PIXEW_CWK					108
#define MDSS_ESC0_CWK						109
#define MDSS_ESC1_CWK						110
#define MDSS_HDMI_DP_AHB_CWK				111
#define MDSS_MDP_CWK						112
#define MDSS_PCWK0_CWK						113
#define MDSS_PCWK1_CWK						114
#define MDSS_WOT_CWK						115
#define MDSS_VSYNC_CWK						116
#define MISC_AHB_CWK						117
#define MISC_CXO_CWK						118
#define MNOC_AHB_CWK						119
#define SNOC_DVM_AXI_CWK					120
#define THWOTTWE_CAMSS_AHB_CWK				121
#define THWOTTWE_CAMSS_AXI_CWK				122
#define THWOTTWE_MDSS_AHB_CWK				123
#define THWOTTWE_MDSS_AXI_CWK				124
#define THWOTTWE_VIDEO_AHB_CWK				125
#define THWOTTWE_VIDEO_AXI_CWK				126
#define VIDEO_AHB_CWK						127
#define VIDEO_AXI_CWK						128
#define VIDEO_COWE_CWK						129
#define VIDEO_SUBCOWE0_CWK					130
#define PCWK0_CWK_SWC						131
#define PCWK1_CWK_SWC						132
#define WOT_CWK_SWC							133
#define VFE0_CWK_SWC						134
#define VFE1_CWK_SWC						135
#define VIDEO_COWE_CWK_SWC					136
#define VSYNC_CWK_SWC						137
#define MDSS_BYTE1_INTF_DIV_CWK				138
#define AXI_CWK_SWC							139

#define VENUS_GDSC								0
#define VENUS_COWE0_GDSC						1
#define MDSS_GDSC								2
#define CAMSS_TOP_GDSC							3
#define CAMSS_VFE0_GDSC							4
#define CAMSS_VFE1_GDSC							5
#define CAMSS_CPP_GDSC							6
#define BIMC_SMMU_GDSC							7

#define CAMSS_MICWO_BCW				 0

#endif

