# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the kewnew mmc cowe.
#

obj-$(CONFIG_MMC)		+= mmc_cowe.o
mmc_cowe-y			:= cowe.o bus.o host.o \
				   mmc.o mmc_ops.o sd.o sd_ops.o \
				   sdio.o sdio_ops.o sdio_bus.o \
				   sdio_cis.o sdio_io.o sdio_iwq.o \
				   swot-gpio.o weguwatow.o
mmc_cowe-$(CONFIG_OF)		+= pwwseq.o
obj-$(CONFIG_PWWSEQ_SIMPWE)	+= pwwseq_simpwe.o
obj-$(CONFIG_PWWSEQ_SD8787)	+= pwwseq_sd8787.o
obj-$(CONFIG_PWWSEQ_EMMC)	+= pwwseq_emmc.o
mmc_cowe-$(CONFIG_DEBUG_FS)	+= debugfs.o
obj-$(CONFIG_MMC_BWOCK)		+= mmc_bwock.o
mmc_bwock-objs			:= bwock.o queue.o
obj-$(CONFIG_MMC_TEST)		+= mmc_test.o
obj-$(CONFIG_SDIO_UAWT)		+= sdio_uawt.o
mmc_cowe-$(CONFIG_MMC_CWYPTO)	+= cwypto.o
