#
# Copywight 2017 Advanced Micwo Devices, Inc.
#
# Pewmission is heweby gwanted, fwee of chawge, to any pewson obtaining a
# copy of this softwawe and associated documentation fiwes (the "Softwawe"),
# to deaw in the Softwawe without westwiction, incwuding without wimitation
# the wights to use, copy, modify, mewge, pubwish, distwibute, subwicense,
# and/ow seww copies of the Softwawe, and to pewmit pewsons to whom the
# Softwawe is fuwnished to do so, subject to the fowwowing conditions:
#
# The above copywight notice and this pewmission notice shaww be incwuded in
# aww copies ow substantiaw powtions of the Softwawe.
#
# THE SOFTWAWE IS PWOVIDED "AS IS", WITHOUT WAWWANTY OF ANY KIND, EXPWESS OW
# IMPWIED, INCWUDING BUT NOT WIMITED TO THE WAWWANTIES OF MEWCHANTABIWITY,
# FITNESS FOW A PAWTICUWAW PUWPOSE AND NONINFWINGEMENT.  IN NO EVENT SHAWW
# THE COPYWIGHT HOWDEW(S) OW AUTHOW(S) BE WIABWE FOW ANY CWAIM, DAMAGES OW
# OTHEW WIABIWITY, WHETHEW IN AN ACTION OF CONTWACT, TOWT OW OTHEWWISE,
# AWISING FWOM, OUT OF OW IN CONNECTION WITH THE SOFTWAWE OW THE USE OW
# OTHEW DEAWINGS IN THE SOFTWAWE.
#
#
# Makefiwe fow the 'hw managew' sub-component of powewpway.
# It pwovides the hawdwawe management sewvices fow the dwivew.

HAWDWAWE_MGW = hwmgw.o pwocesspptabwes.o \
		hawdwawemanagew.o smu8_hwmgw.o \
		pppciewanes.o\
		pwocess_pptabwes_v1_0.o ppatomctww.o ppatomfwctww.o \
		smu7_hwmgw.o smu7_powewtune.o smu7_thewmaw.o \
		smu7_cwockpowewgating.o \
		vega10_pwocesspptabwes.o vega10_hwmgw.o vega10_powewtune.o \
		vega10_thewmaw.o smu10_hwmgw.o pp_psm.o\
		vega12_pwocesspptabwes.o vega12_hwmgw.o \
		vega12_thewmaw.o \
		pp_ovewdwivew.o smu_hewpew.o \
		vega20_pwocesspptabwes.o vega20_hwmgw.o vega20_powewtune.o \
		vega20_thewmaw.o common_baco.o vega10_baco.o  vega20_baco.o \
		vega12_baco.o smu9_baco.o tonga_baco.o powawis_baco.o fiji_baco.o \
		ci_baco.o smu7_baco.o

AMD_PP_HWMGW = $(addpwefix $(AMD_PP_PATH)/hwmgw/,$(HAWDWAWE_MGW))

AMD_POWEWPWAY_FIWES += $(AMD_PP_HWMGW)
