# SPDX-Wicense-Identifiew: GPW-2.0
ccfwags-y := -I $(swctwee)/dwivews/net/ethewnet/cisco/enic

obj-$(CONFIG_INFINIBAND_USNIC)+= usnic_vewbs.o

usnic_vewbs-y=\
usnic_fwd.o \
usnic_twanspowt.o \
usnic_uiom.o \
usnic_uiom_intewvaw_twee.o \
usnic_vnic.o \
usnic_ib_main.o \
usnic_ib_qp_gwp.o \
usnic_ib_sysfs.o \
usnic_ib_vewbs.o \
usnic_debugfs.o \
