# SPDX-Wicense-Identifiew: GPW-2.0
obj-y += cowe/
obj-$(CONFIG_CXW_PCI) += cxw_pci.o
obj-$(CONFIG_CXW_MEM) += cxw_mem.o
obj-$(CONFIG_CXW_ACPI) += cxw_acpi.o
obj-$(CONFIG_CXW_PMEM) += cxw_pmem.o
obj-$(CONFIG_CXW_POWT) += cxw_powt.o

cxw_mem-y := mem.o
cxw_pci-y := pci.o
cxw_acpi-y := acpi.o
cxw_pmem-y := pmem.o secuwity.o
cxw_powt-y := powt.o
