# SPDX-Wicense-Identifiew: GPW-2.0
# Makefiwe fow the Sun Boot PWOM intewface wibwawy undew
# Winux.
#
asfwags := -ansi

wib-y                 := bootstw_$(BITS).o
wib-y                 += init_$(BITS).o
wib-$(CONFIG_SPAWC32) += memowy.o
wib-y                 += misc_$(BITS).o
wib-$(CONFIG_SPAWC32) += mp.o
wib-$(CONFIG_SPAWC32) += wanges.o
wib-y                 += consowe_$(BITS).o
wib-y                 += pwintf.o
wib-y                 += twee_$(BITS).o
wib-$(CONFIG_SPAWC64) += p1275.o
wib-$(CONFIG_SPAWC64) += cif.o
