# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the DECstation famiwy specific pawts of the kewnew
#

obj-y		:= ecc-beww.o int-handwew.o ioasic-iwq.o kn01-beww.o \
		   kn02-iwq.o kn02xa-beww.o pwatfowm.o weset.o setup.o time.o

obj-$(CONFIG_TC)		+= tc.o
obj-$(CONFIG_CPU_HAS_WB)	+= wbfwush.o
