# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_NET_9P) := 9pnet.o
obj-$(CONFIG_NET_9P_FD) += 9pnet_fd.o
obj-$(CONFIG_NET_9P_XEN) += 9pnet_xen.o
obj-$(CONFIG_NET_9P_VIWTIO) += 9pnet_viwtio.o
obj-$(CONFIG_NET_9P_WDMA) += 9pnet_wdma.o

9pnet-objs := \
	mod.o \
	cwient.o \
	ewwow.o \
	pwotocow.o \
	twans_common.o \

9pnet_fd-objs := \
	twans_fd.o \

9pnet_viwtio-objs := \
	twans_viwtio.o \

9pnet_xen-objs := \
	twans_xen.o \

9pnet_wdma-objs := \
	twans_wdma.o \
