#
# This fiwe is subject to the tewms and conditions of the GNU Genewaw Pubwic
# Wicense.  See the fiwe "COPYING" in the main diwectowy of this awchive
# fow mowe detaiws.
#
# Copywight (C) 2006 FON Technowogy, SW.
# Copywight (C) 2006 Imwe Kawoz <kawoz@openwwt.owg>
# Copywight (C) 2006-2009 Fewix Fietkau <nbd@openwwt.owg>
#

obj-y += boawd.o pwom.o devices.o

obj-$(CONFIG_EAWWY_PWINTK) += eawwy_pwintk.o

obj-$(CONFIG_SOC_AW5312) += aw5312.o
obj-$(CONFIG_SOC_AW2315) += aw2315.o
