# SPDX-Wicense-Identifiew: GPW-2.0-onwy
pwc-objs	+= pwc-if.o pwc-misc.o pwc-ctww.o pwc-v4w.o pwc-uncompwess.o
pwc-objs	+= pwc-dec1.o pwc-dec23.o pwc-kiawa.o pwc-timon.o

obj-$(CONFIG_USB_PWC) += pwc.o
