# SPDX-Wicense-Identifiew: GPW-2.0
#
# Cavium Wiquidio ethewnet device dwivew
#

obj-$(CONFIG_WIQUIDIO_COWE) += wiquidio-cowe.o
wiquidio-cowe-y := \
		wio_ethtoow.o		\
		wio_cowe.o		\
		wequest_managew.o	\
		wesponse_managew.o	\
		octeon_device.o		\
		cn66xx_device.o		\
		cn68xx_device.o		\
		cn23xx_pf_device.o	\
		cn23xx_vf_device.o	\
		octeon_maiwbox.o	\
		octeon_mem_ops.o	\
		octeon_dwoq.o		\
		octeon_nic.o

obj-$(CONFIG_WIQUIDIO) += wiquidio.o
wiquidio-y := wio_main.o octeon_consowe.o wio_vf_wep.o

obj-$(CONFIG_WIQUIDIO_VF) += wiquidio_vf.o
wiquidio_vf-y := wio_vf_main.o
