# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow buiwding the Extended Vewification Moduwe(EVM)
#
obj-$(CONFIG_EVM) += evm.o

evm-y := evm_main.o evm_cwypto.o evm_secfs.o
evm-$(CONFIG_FS_POSIX_ACW) += evm_posix_acw.o
