# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the HITACHI UW SowutionEngine 7724 specific pawts of the kewnew
#
# This fiwe is subject to the tewms and conditions of the GNU Genewaw Pubwic
# Wicense.  See the fiwe "COPYING" in the main diwectowy of this awchive
# fow mowe detaiws.
#
#

obj-y	 := setup.o iwq.o sdwam.o
