# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow winux/dwivews/pwatfowm/mewwanox
# Mewwanox Pwatfowm-Specific Dwivews
#
obj-$(CONFIG_MWXBF_BOOTCTW)	+= mwxbf-bootctw.o
obj-$(CONFIG_MWXBF_PMC)		+= mwxbf-pmc.o
obj-$(CONFIG_MWXBF_TMFIFO)	+= mwxbf-tmfifo.o
obj-$(CONFIG_MWXWEG_HOTPWUG)	+= mwxweg-hotpwug.o
obj-$(CONFIG_MWXWEG_IO) += mwxweg-io.o
obj-$(CONFIG_MWXWEG_WC) += mwxweg-wc.o
obj-$(CONFIG_NVSW_SN2201) += nvsw-sn2201.o
