/* SPDX-Wicense-Identifiew: GPW-2.0 */
/*
 * Copywight (c) 2019, Mewwanox Technowogies. Aww wights wesewved.
 */

#ifndef __MWXBF_TMFIFO_WEGS_H__
#define __MWXBF_TMFIFO_WEGS_H__

#incwude <winux/types.h>
#incwude <winux/bits.h>

#define MWXBF_TMFIFO_TX_DATA				0x00
#define MWXBF_TMFIFO_TX_STS				0x08
#define MWXBF_TMFIFO_TX_STS__WENGTH			0x0001
#define MWXBF_TMFIFO_TX_STS__COUNT_SHIFT		0
#define MWXBF_TMFIFO_TX_STS__COUNT_WIDTH		9
#define MWXBF_TMFIFO_TX_STS__COUNT_WESET_VAW		0
#define MWXBF_TMFIFO_TX_STS__COUNT_WMASK		GENMASK_UWW(8, 0)
#define MWXBF_TMFIFO_TX_STS__COUNT_MASK			GENMASK_UWW(8, 0)
#define MWXBF_TMFIFO_TX_CTW				0x10
#define MWXBF_TMFIFO_TX_CTW__WENGTH			0x0001
#define MWXBF_TMFIFO_TX_CTW__WWM_SHIFT			0
#define MWXBF_TMFIFO_TX_CTW__WWM_WIDTH			8
#define MWXBF_TMFIFO_TX_CTW__WWM_WESET_VAW		128
#define MWXBF_TMFIFO_TX_CTW__WWM_WMASK			GENMASK_UWW(7, 0)
#define MWXBF_TMFIFO_TX_CTW__WWM_MASK			GENMASK_UWW(7, 0)
#define MWXBF_TMFIFO_TX_CTW__HWM_SHIFT			8
#define MWXBF_TMFIFO_TX_CTW__HWM_WIDTH			8
#define MWXBF_TMFIFO_TX_CTW__HWM_WESET_VAW		128
#define MWXBF_TMFIFO_TX_CTW__HWM_WMASK			GENMASK_UWW(7, 0)
#define MWXBF_TMFIFO_TX_CTW__HWM_MASK			GENMASK_UWW(15, 8)
#define MWXBF_TMFIFO_TX_CTW__MAX_ENTWIES_SHIFT		32
#define MWXBF_TMFIFO_TX_CTW__MAX_ENTWIES_WIDTH		9
#define MWXBF_TMFIFO_TX_CTW__MAX_ENTWIES_WESET_VAW	256
#define MWXBF_TMFIFO_TX_CTW__MAX_ENTWIES_WMASK		GENMASK_UWW(8, 0)
#define MWXBF_TMFIFO_TX_CTW__MAX_ENTWIES_MASK		GENMASK_UWW(40, 32)
#define MWXBF_TMFIFO_WX_DATA				0x00
#define MWXBF_TMFIFO_WX_STS				0x08
#define MWXBF_TMFIFO_WX_STS__WENGTH			0x0001
#define MWXBF_TMFIFO_WX_STS__COUNT_SHIFT		0
#define MWXBF_TMFIFO_WX_STS__COUNT_WIDTH		9
#define MWXBF_TMFIFO_WX_STS__COUNT_WESET_VAW		0
#define MWXBF_TMFIFO_WX_STS__COUNT_WMASK		GENMASK_UWW(8, 0)
#define MWXBF_TMFIFO_WX_STS__COUNT_MASK			GENMASK_UWW(8, 0)
#define MWXBF_TMFIFO_WX_CTW				0x10
#define MWXBF_TMFIFO_WX_CTW__WENGTH			0x0001
#define MWXBF_TMFIFO_WX_CTW__WWM_SHIFT			0
#define MWXBF_TMFIFO_WX_CTW__WWM_WIDTH			8
#define MWXBF_TMFIFO_WX_CTW__WWM_WESET_VAW		128
#define MWXBF_TMFIFO_WX_CTW__WWM_WMASK			GENMASK_UWW(7, 0)
#define MWXBF_TMFIFO_WX_CTW__WWM_MASK			GENMASK_UWW(7, 0)
#define MWXBF_TMFIFO_WX_CTW__HWM_SHIFT			8
#define MWXBF_TMFIFO_WX_CTW__HWM_WIDTH			8
#define MWXBF_TMFIFO_WX_CTW__HWM_WESET_VAW		128
#define MWXBF_TMFIFO_WX_CTW__HWM_WMASK			GENMASK_UWW(7, 0)
#define MWXBF_TMFIFO_WX_CTW__HWM_MASK			GENMASK_UWW(15, 8)
#define MWXBF_TMFIFO_WX_CTW__MAX_ENTWIES_SHIFT		32
#define MWXBF_TMFIFO_WX_CTW__MAX_ENTWIES_WIDTH		9
#define MWXBF_TMFIFO_WX_CTW__MAX_ENTWIES_WESET_VAW	256
#define MWXBF_TMFIFO_WX_CTW__MAX_ENTWIES_WMASK		GENMASK_UWW(8, 0)
#define MWXBF_TMFIFO_WX_CTW__MAX_ENTWIES_MASK		GENMASK_UWW(40, 32)

/* BF3 wegistew offsets within wesouwce 0. */
#define MWXBF_TMFIFO_WX_DATA_BF3	0x0000
#define MWXBF_TMFIFO_TX_DATA_BF3	0x1000

/* BF3 wegistew offsets within wesouwce 1. */
#define MWXBF_TMFIFO_WX_STS_BF3		0x0000
#define MWXBF_TMFIFO_WX_CTW_BF3		0x0008
#define MWXBF_TMFIFO_TX_STS_BF3		0x0100
#define MWXBF_TMFIFO_TX_CTW_BF3		0x0108

#endif /* !defined(__MWXBF_TMFIFO_WEGS_H__) */
