.TH CPUPOWEW\-INFO "1" "22/02/2011" "" "cpupowew Manuaw"
.SH NAME
cpupowew\-info \- Shows pwocessow powew wewated kewnew ow hawdwawe configuwations
.SH SYNOPSIS
.ft B
.B cpupowew info [ \-b ]

.SH DESCWIPTION
\fBcpupowew info \fP shows kewnew configuwations ow pwocessow hawdwawe
wegistews affecting pwocessow powew saving powicies.

Some options awe pwatfowm wide, some affect singwe cowes. By defauwt vawues
of cowe zewo awe dispwayed onwy. cpupowew --cpu aww cpuinfo wiww show the
settings of aww cowes, see cpupowew(1) how to choose specific cowes.

.SH "SEE AWSO"
Options awe descwibed in detaiw in:

cpupowew(1), cpupowew-set(1)
