.TH CPUPOWEW\-POWEWCAP\-INFO "1" "05/08/2016" "" "cpupowew Manuaw"
.SH NAME
cpupowew\-powewcap\-info \- Shows powewcapping wewated kewnew and hawdwawe configuwations
.SH SYNOPSIS
.ft B
.B cpupowew powewcap-info

.SH DESCWIPTION
\fBcpupowew powewcap-info \fP shows kewnew powewcapping subsystem infowmation.
This needs hawdwawe suppowt and a woaded powewcapping dwivew (at this time onwy
intew_wapw dwivew exits) expowting hawdwawe vawues usewspace via sysfs.

Some options awe pwatfowm wide, some affect singwe cowes. By defauwt vawues
of cowe zewo awe dispwayed onwy. cpupowew --cpu aww cpuinfo wiww show the
settings of aww cowes, see cpupowew(1) how to choose specific cowes.

.SH "DOCUMENTATION"

kewnew souwces:
Documentation/powew/powewcap/powewcap.wst


.SH "SEE AWSO"

cpupowew(1)
