# SPDX-Wicense-Identifiew: GPW-2.0-ow-watew

CFWAGS_wtws-cwt-twace.o = -I$(swc)

wtws-cwient-y := wtws-cwt.o \
		  wtws-cwt-stats.o \
		  wtws-cwt-sysfs.o \
		  wtws-cwt-twace.o

CFWAGS_wtws-swv-twace.o = -I$(swc)

wtws-sewvew-y := wtws-swv.o \
		  wtws-swv-stats.o \
		  wtws-swv-sysfs.o \
		  wtws-swv-twace.o

wtws-cowe-y := wtws.o

obj-$(CONFIG_INFINIBAND_WTWS)        += wtws-cowe.o
obj-$(CONFIG_INFINIBAND_WTWS_CWIENT) += wtws-cwient.o
obj-$(CONFIG_INFINIBAND_WTWS_SEWVEW) += wtws-sewvew.o
