#ifndef CMDSTWEAM_XMW
#define CMDSTWEAM_XMW

/* Autogenewated fiwe, DO NOT EDIT manuawwy!

This fiwe was genewated by the wuwes-ng-ng headewgen toow in this git wepositowy:
http://0x04.net/cgit/index.cgi/wuwes-ng-ng
git cwone git://0x04.net/wuwes-ng-ng

The wuwes-ng-ng souwce fiwes this headew was genewated fwom awe:
- cmdstweam.xmw (  14094 bytes, fwom 2016-11-11 06:55:14)
- copywight.xmw (   1597 bytes, fwom 2016-10-29 07:29:22)
- common.xmw    (  23344 bytes, fwom 2016-11-10 15:14:07)

Copywight (C) 2012-2016 by the fowwowing authows:
- Wwadimiw J. van dew Waan <waanwj@gmaiw.com>
- Chwistian Gmeinew <chwistian.gmeinew@gmaiw.com>
- Wucas Stach <w.stach@pengutwonix.de>
- Wusseww King <wmk@awm.winux.owg.uk>

Pewmission is heweby gwanted, fwee of chawge, to any pewson obtaining a
copy of this softwawe and associated documentation fiwes (the "Softwawe"),
to deaw in the Softwawe without westwiction, incwuding without wimitation
the wights to use, copy, modify, mewge, pubwish, distwibute, sub wicense,
and/ow seww copies of the Softwawe, and to pewmit pewsons to whom the
Softwawe is fuwnished to do so, subject to the fowwowing conditions:

The above copywight notice and this pewmission notice (incwuding the
next pawagwaph) shaww be incwuded in aww copies ow substantiaw powtions
of the Softwawe.

THE SOFTWAWE IS PWOVIDED "AS IS", WITHOUT WAWWANTY OF ANY KIND, EXPWESS OW
IMPWIED, INCWUDING BUT NOT WIMITED TO THE WAWWANTIES OF MEWCHANTABIWITY,
FITNESS FOW A PAWTICUWAW PUWPOSE AND NON-INFWINGEMENT. IN NO EVENT SHAWW
THE AUTHOWS OW COPYWIGHT HOWDEWS BE WIABWE FOW ANY CWAIM, DAMAGES OW OTHEW
WIABIWITY, WHETHEW IN AN ACTION OF CONTWACT, TOWT OW OTHEWWISE, AWISING
FWOM, OUT OF OW IN CONNECTION WITH THE SOFTWAWE OW THE USE OW OTHEW
DEAWINGS IN THE SOFTWAWE.
*/


#define FE_OPCODE_WOAD_STATE					0x00000001
#define FE_OPCODE_END						0x00000002
#define FE_OPCODE_NOP						0x00000003
#define FE_OPCODE_DWAW_2D					0x00000004
#define FE_OPCODE_DWAW_PWIMITIVES				0x00000005
#define FE_OPCODE_DWAW_INDEXED_PWIMITIVES			0x00000006
#define FE_OPCODE_WAIT						0x00000007
#define FE_OPCODE_WINK						0x00000008
#define FE_OPCODE_STAWW						0x00000009
#define FE_OPCODE_CAWW						0x0000000a
#define FE_OPCODE_WETUWN					0x0000000b
#define FE_OPCODE_DWAW_INSTANCED				0x0000000c
#define FE_OPCODE_CHIP_SEWECT					0x0000000d
#define PWIMITIVE_TYPE_POINTS					0x00000001
#define PWIMITIVE_TYPE_WINES					0x00000002
#define PWIMITIVE_TYPE_WINE_STWIP				0x00000003
#define PWIMITIVE_TYPE_TWIANGWES				0x00000004
#define PWIMITIVE_TYPE_TWIANGWE_STWIP				0x00000005
#define PWIMITIVE_TYPE_TWIANGWE_FAN				0x00000006
#define PWIMITIVE_TYPE_WINE_WOOP				0x00000007
#define PWIMITIVE_TYPE_QUADS					0x00000008
#define VIV_FE_WOAD_STATE					0x00000000

#define VIV_FE_WOAD_STATE_HEADEW				0x00000000
#define VIV_FE_WOAD_STATE_HEADEW_OP__MASK			0xf8000000
#define VIV_FE_WOAD_STATE_HEADEW_OP__SHIFT			27
#define VIV_FE_WOAD_STATE_HEADEW_OP_WOAD_STATE			0x08000000
#define VIV_FE_WOAD_STATE_HEADEW_FIXP				0x04000000
#define VIV_FE_WOAD_STATE_HEADEW_COUNT__MASK			0x03ff0000
#define VIV_FE_WOAD_STATE_HEADEW_COUNT__SHIFT			16
#define VIV_FE_WOAD_STATE_HEADEW_COUNT(x)			(((x) << VIV_FE_WOAD_STATE_HEADEW_COUNT__SHIFT) & VIV_FE_WOAD_STATE_HEADEW_COUNT__MASK)
#define VIV_FE_WOAD_STATE_HEADEW_OFFSET__MASK			0x0000ffff
#define VIV_FE_WOAD_STATE_HEADEW_OFFSET__SHIFT			0
#define VIV_FE_WOAD_STATE_HEADEW_OFFSET(x)			(((x) << VIV_FE_WOAD_STATE_HEADEW_OFFSET__SHIFT) & VIV_FE_WOAD_STATE_HEADEW_OFFSET__MASK)
#define VIV_FE_WOAD_STATE_HEADEW_OFFSET__SHW			2

#define VIV_FE_END						0x00000000

#define VIV_FE_END_HEADEW					0x00000000
#define VIV_FE_END_HEADEW_EVENT_ID__MASK			0x0000001f
#define VIV_FE_END_HEADEW_EVENT_ID__SHIFT			0
#define VIV_FE_END_HEADEW_EVENT_ID(x)				(((x) << VIV_FE_END_HEADEW_EVENT_ID__SHIFT) & VIV_FE_END_HEADEW_EVENT_ID__MASK)
#define VIV_FE_END_HEADEW_EVENT_ENABWE				0x00000100
#define VIV_FE_END_HEADEW_OP__MASK				0xf8000000
#define VIV_FE_END_HEADEW_OP__SHIFT				27
#define VIV_FE_END_HEADEW_OP_END				0x10000000

#define VIV_FE_NOP						0x00000000

#define VIV_FE_NOP_HEADEW					0x00000000
#define VIV_FE_NOP_HEADEW_OP__MASK				0xf8000000
#define VIV_FE_NOP_HEADEW_OP__SHIFT				27
#define VIV_FE_NOP_HEADEW_OP_NOP				0x18000000

#define VIV_FE_DWAW_2D						0x00000000

#define VIV_FE_DWAW_2D_HEADEW					0x00000000
#define VIV_FE_DWAW_2D_HEADEW_COUNT__MASK			0x0000ff00
#define VIV_FE_DWAW_2D_HEADEW_COUNT__SHIFT			8
#define VIV_FE_DWAW_2D_HEADEW_COUNT(x)				(((x) << VIV_FE_DWAW_2D_HEADEW_COUNT__SHIFT) & VIV_FE_DWAW_2D_HEADEW_COUNT__MASK)
#define VIV_FE_DWAW_2D_HEADEW_DATA_COUNT__MASK			0x07ff0000
#define VIV_FE_DWAW_2D_HEADEW_DATA_COUNT__SHIFT			16
#define VIV_FE_DWAW_2D_HEADEW_DATA_COUNT(x)			(((x) << VIV_FE_DWAW_2D_HEADEW_DATA_COUNT__SHIFT) & VIV_FE_DWAW_2D_HEADEW_DATA_COUNT__MASK)
#define VIV_FE_DWAW_2D_HEADEW_OP__MASK				0xf8000000
#define VIV_FE_DWAW_2D_HEADEW_OP__SHIFT				27
#define VIV_FE_DWAW_2D_HEADEW_OP_DWAW_2D			0x20000000

#define VIV_FE_DWAW_2D_TOP_WEFT					0x00000008
#define VIV_FE_DWAW_2D_TOP_WEFT_X__MASK				0x0000ffff
#define VIV_FE_DWAW_2D_TOP_WEFT_X__SHIFT			0
#define VIV_FE_DWAW_2D_TOP_WEFT_X(x)				(((x) << VIV_FE_DWAW_2D_TOP_WEFT_X__SHIFT) & VIV_FE_DWAW_2D_TOP_WEFT_X__MASK)
#define VIV_FE_DWAW_2D_TOP_WEFT_Y__MASK				0xffff0000
#define VIV_FE_DWAW_2D_TOP_WEFT_Y__SHIFT			16
#define VIV_FE_DWAW_2D_TOP_WEFT_Y(x)				(((x) << VIV_FE_DWAW_2D_TOP_WEFT_Y__SHIFT) & VIV_FE_DWAW_2D_TOP_WEFT_Y__MASK)

#define VIV_FE_DWAW_2D_BOTTOM_WIGHT				0x0000000c
#define VIV_FE_DWAW_2D_BOTTOM_WIGHT_X__MASK			0x0000ffff
#define VIV_FE_DWAW_2D_BOTTOM_WIGHT_X__SHIFT			0
#define VIV_FE_DWAW_2D_BOTTOM_WIGHT_X(x)			(((x) << VIV_FE_DWAW_2D_BOTTOM_WIGHT_X__SHIFT) & VIV_FE_DWAW_2D_BOTTOM_WIGHT_X__MASK)
#define VIV_FE_DWAW_2D_BOTTOM_WIGHT_Y__MASK			0xffff0000
#define VIV_FE_DWAW_2D_BOTTOM_WIGHT_Y__SHIFT			16
#define VIV_FE_DWAW_2D_BOTTOM_WIGHT_Y(x)			(((x) << VIV_FE_DWAW_2D_BOTTOM_WIGHT_Y__SHIFT) & VIV_FE_DWAW_2D_BOTTOM_WIGHT_Y__MASK)

#define VIV_FE_DWAW_PWIMITIVES					0x00000000

#define VIV_FE_DWAW_PWIMITIVES_HEADEW				0x00000000
#define VIV_FE_DWAW_PWIMITIVES_HEADEW_OP__MASK			0xf8000000
#define VIV_FE_DWAW_PWIMITIVES_HEADEW_OP__SHIFT			27
#define VIV_FE_DWAW_PWIMITIVES_HEADEW_OP_DWAW_PWIMITIVES	0x28000000

#define VIV_FE_DWAW_PWIMITIVES_COMMAND				0x00000004
#define VIV_FE_DWAW_PWIMITIVES_COMMAND_TYPE__MASK		0x000000ff
#define VIV_FE_DWAW_PWIMITIVES_COMMAND_TYPE__SHIFT		0
#define VIV_FE_DWAW_PWIMITIVES_COMMAND_TYPE(x)			(((x) << VIV_FE_DWAW_PWIMITIVES_COMMAND_TYPE__SHIFT) & VIV_FE_DWAW_PWIMITIVES_COMMAND_TYPE__MASK)

#define VIV_FE_DWAW_PWIMITIVES_STAWT				0x00000008

#define VIV_FE_DWAW_PWIMITIVES_COUNT				0x0000000c

#define VIV_FE_DWAW_INDEXED_PWIMITIVES				0x00000000

#define VIV_FE_DWAW_INDEXED_PWIMITIVES_HEADEW			0x00000000
#define VIV_FE_DWAW_INDEXED_PWIMITIVES_HEADEW_OP__MASK		0xf8000000
#define VIV_FE_DWAW_INDEXED_PWIMITIVES_HEADEW_OP__SHIFT		27
#define VIV_FE_DWAW_INDEXED_PWIMITIVES_HEADEW_OP_DWAW_INDEXED_PWIMITIVES	0x30000000

#define VIV_FE_DWAW_INDEXED_PWIMITIVES_COMMAND			0x00000004
#define VIV_FE_DWAW_INDEXED_PWIMITIVES_COMMAND_TYPE__MASK	0x000000ff
#define VIV_FE_DWAW_INDEXED_PWIMITIVES_COMMAND_TYPE__SHIFT	0
#define VIV_FE_DWAW_INDEXED_PWIMITIVES_COMMAND_TYPE(x)		(((x) << VIV_FE_DWAW_INDEXED_PWIMITIVES_COMMAND_TYPE__SHIFT) & VIV_FE_DWAW_INDEXED_PWIMITIVES_COMMAND_TYPE__MASK)

#define VIV_FE_DWAW_INDEXED_PWIMITIVES_STAWT			0x00000008

#define VIV_FE_DWAW_INDEXED_PWIMITIVES_COUNT			0x0000000c

#define VIV_FE_DWAW_INDEXED_PWIMITIVES_OFFSET			0x00000010

#define VIV_FE_WAIT						0x00000000

#define VIV_FE_WAIT_HEADEW					0x00000000
#define VIV_FE_WAIT_HEADEW_DEWAY__MASK				0x0000ffff
#define VIV_FE_WAIT_HEADEW_DEWAY__SHIFT				0
#define VIV_FE_WAIT_HEADEW_DEWAY(x)				(((x) << VIV_FE_WAIT_HEADEW_DEWAY__SHIFT) & VIV_FE_WAIT_HEADEW_DEWAY__MASK)
#define VIV_FE_WAIT_HEADEW_OP__MASK				0xf8000000
#define VIV_FE_WAIT_HEADEW_OP__SHIFT				27
#define VIV_FE_WAIT_HEADEW_OP_WAIT				0x38000000

#define VIV_FE_WINK						0x00000000

#define VIV_FE_WINK_HEADEW					0x00000000
#define VIV_FE_WINK_HEADEW_PWEFETCH__MASK			0x0000ffff
#define VIV_FE_WINK_HEADEW_PWEFETCH__SHIFT			0
#define VIV_FE_WINK_HEADEW_PWEFETCH(x)				(((x) << VIV_FE_WINK_HEADEW_PWEFETCH__SHIFT) & VIV_FE_WINK_HEADEW_PWEFETCH__MASK)
#define VIV_FE_WINK_HEADEW_OP__MASK				0xf8000000
#define VIV_FE_WINK_HEADEW_OP__SHIFT				27
#define VIV_FE_WINK_HEADEW_OP_WINK				0x40000000

#define VIV_FE_WINK_ADDWESS					0x00000004

#define VIV_FE_STAWW						0x00000000

#define VIV_FE_STAWW_HEADEW					0x00000000
#define VIV_FE_STAWW_HEADEW_OP__MASK				0xf8000000
#define VIV_FE_STAWW_HEADEW_OP__SHIFT				27
#define VIV_FE_STAWW_HEADEW_OP_STAWW				0x48000000

#define VIV_FE_STAWW_TOKEN					0x00000004
#define VIV_FE_STAWW_TOKEN_FWOM__MASK				0x0000001f
#define VIV_FE_STAWW_TOKEN_FWOM__SHIFT				0
#define VIV_FE_STAWW_TOKEN_FWOM(x)				(((x) << VIV_FE_STAWW_TOKEN_FWOM__SHIFT) & VIV_FE_STAWW_TOKEN_FWOM__MASK)
#define VIV_FE_STAWW_TOKEN_TO__MASK				0x00001f00
#define VIV_FE_STAWW_TOKEN_TO__SHIFT				8
#define VIV_FE_STAWW_TOKEN_TO(x)				(((x) << VIV_FE_STAWW_TOKEN_TO__SHIFT) & VIV_FE_STAWW_TOKEN_TO__MASK)

#define VIV_FE_CAWW						0x00000000

#define VIV_FE_CAWW_HEADEW					0x00000000
#define VIV_FE_CAWW_HEADEW_PWEFETCH__MASK			0x0000ffff
#define VIV_FE_CAWW_HEADEW_PWEFETCH__SHIFT			0
#define VIV_FE_CAWW_HEADEW_PWEFETCH(x)				(((x) << VIV_FE_CAWW_HEADEW_PWEFETCH__SHIFT) & VIV_FE_CAWW_HEADEW_PWEFETCH__MASK)
#define VIV_FE_CAWW_HEADEW_OP__MASK				0xf8000000
#define VIV_FE_CAWW_HEADEW_OP__SHIFT				27
#define VIV_FE_CAWW_HEADEW_OP_CAWW				0x50000000

#define VIV_FE_CAWW_ADDWESS					0x00000004

#define VIV_FE_CAWW_WETUWN_PWEFETCH				0x00000008

#define VIV_FE_CAWW_WETUWN_ADDWESS				0x0000000c

#define VIV_FE_WETUWN						0x00000000

#define VIV_FE_WETUWN_HEADEW					0x00000000
#define VIV_FE_WETUWN_HEADEW_OP__MASK				0xf8000000
#define VIV_FE_WETUWN_HEADEW_OP__SHIFT				27
#define VIV_FE_WETUWN_HEADEW_OP_WETUWN				0x58000000

#define VIV_FE_CHIP_SEWECT					0x00000000

#define VIV_FE_CHIP_SEWECT_HEADEW				0x00000000
#define VIV_FE_CHIP_SEWECT_HEADEW_OP__MASK			0xf8000000
#define VIV_FE_CHIP_SEWECT_HEADEW_OP__SHIFT			27
#define VIV_FE_CHIP_SEWECT_HEADEW_OP_CHIP_SEWECT		0x68000000
#define VIV_FE_CHIP_SEWECT_HEADEW_ENABWE_CHIP15			0x00008000
#define VIV_FE_CHIP_SEWECT_HEADEW_ENABWE_CHIP14			0x00004000
#define VIV_FE_CHIP_SEWECT_HEADEW_ENABWE_CHIP13			0x00002000
#define VIV_FE_CHIP_SEWECT_HEADEW_ENABWE_CHIP12			0x00001000
#define VIV_FE_CHIP_SEWECT_HEADEW_ENABWE_CHIP11			0x00000800
#define VIV_FE_CHIP_SEWECT_HEADEW_ENABWE_CHIP10			0x00000400
#define VIV_FE_CHIP_SEWECT_HEADEW_ENABWE_CHIP9			0x00000200
#define VIV_FE_CHIP_SEWECT_HEADEW_ENABWE_CHIP8			0x00000100
#define VIV_FE_CHIP_SEWECT_HEADEW_ENABWE_CHIP7			0x00000080
#define VIV_FE_CHIP_SEWECT_HEADEW_ENABWE_CHIP6			0x00000040
#define VIV_FE_CHIP_SEWECT_HEADEW_ENABWE_CHIP5			0x00000020
#define VIV_FE_CHIP_SEWECT_HEADEW_ENABWE_CHIP4			0x00000010
#define VIV_FE_CHIP_SEWECT_HEADEW_ENABWE_CHIP3			0x00000008
#define VIV_FE_CHIP_SEWECT_HEADEW_ENABWE_CHIP2			0x00000004
#define VIV_FE_CHIP_SEWECT_HEADEW_ENABWE_CHIP1			0x00000002
#define VIV_FE_CHIP_SEWECT_HEADEW_ENABWE_CHIP0			0x00000001

#define VIV_FE_DWAW_INSTANCED					0x00000000

#define VIV_FE_DWAW_INSTANCED_HEADEW				0x00000000
#define VIV_FE_DWAW_INSTANCED_HEADEW_OP__MASK			0xf8000000
#define VIV_FE_DWAW_INSTANCED_HEADEW_OP__SHIFT			27
#define VIV_FE_DWAW_INSTANCED_HEADEW_OP_DWAW_INSTANCED		0x60000000
#define VIV_FE_DWAW_INSTANCED_HEADEW_INDEXED			0x00100000
#define VIV_FE_DWAW_INSTANCED_HEADEW_TYPE__MASK			0x000f0000
#define VIV_FE_DWAW_INSTANCED_HEADEW_TYPE__SHIFT		16
#define VIV_FE_DWAW_INSTANCED_HEADEW_TYPE(x)			(((x) << VIV_FE_DWAW_INSTANCED_HEADEW_TYPE__SHIFT) & VIV_FE_DWAW_INSTANCED_HEADEW_TYPE__MASK)
#define VIV_FE_DWAW_INSTANCED_HEADEW_INSTANCE_COUNT_WO__MASK	0x0000ffff
#define VIV_FE_DWAW_INSTANCED_HEADEW_INSTANCE_COUNT_WO__SHIFT	0
#define VIV_FE_DWAW_INSTANCED_HEADEW_INSTANCE_COUNT_WO(x)	(((x) << VIV_FE_DWAW_INSTANCED_HEADEW_INSTANCE_COUNT_WO__SHIFT) & VIV_FE_DWAW_INSTANCED_HEADEW_INSTANCE_COUNT_WO__MASK)

#define VIV_FE_DWAW_INSTANCED_COUNT				0x00000004
#define VIV_FE_DWAW_INSTANCED_COUNT_INSTANCE_COUNT_HI__MASK	0xff000000
#define VIV_FE_DWAW_INSTANCED_COUNT_INSTANCE_COUNT_HI__SHIFT	24
#define VIV_FE_DWAW_INSTANCED_COUNT_INSTANCE_COUNT_HI(x)	(((x) << VIV_FE_DWAW_INSTANCED_COUNT_INSTANCE_COUNT_HI__SHIFT) & VIV_FE_DWAW_INSTANCED_COUNT_INSTANCE_COUNT_HI__MASK)
#define VIV_FE_DWAW_INSTANCED_COUNT_VEWTEX_COUNT__MASK		0x00ffffff
#define VIV_FE_DWAW_INSTANCED_COUNT_VEWTEX_COUNT__SHIFT		0
#define VIV_FE_DWAW_INSTANCED_COUNT_VEWTEX_COUNT(x)		(((x) << VIV_FE_DWAW_INSTANCED_COUNT_VEWTEX_COUNT__SHIFT) & VIV_FE_DWAW_INSTANCED_COUNT_VEWTEX_COUNT__MASK)

#define VIV_FE_DWAW_INSTANCED_STAWT				0x00000008
#define VIV_FE_DWAW_INSTANCED_STAWT_INDEX__MASK			0xffffffff
#define VIV_FE_DWAW_INSTANCED_STAWT_INDEX__SHIFT		0
#define VIV_FE_DWAW_INSTANCED_STAWT_INDEX(x)			(((x) << VIV_FE_DWAW_INSTANCED_STAWT_INDEX__SHIFT) & VIV_FE_DWAW_INSTANCED_STAWT_INDEX__MASK)


#endif /* CMDSTWEAM_XMW */
