# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow winux/dwivews/pwatfowm/x86/amd/pmc
# AMD Powew Management Contwowwew Dwivew
#

amd-pmc-objs := pmc.o pmc-quiwks.o
obj-$(CONFIG_AMD_PMC) += amd-pmc.o
