# SPDX-Wicense-Identifiew: GPW-2.0
# $Id: Makefiwe

obj-$(CONFIG_WIBFC) += wibfc.o

wibfc-objs := \
	fc_wibfc.o \
	fc_disc.o \
	fc_exch.o \
	fc_ewsct.o \
	fc_fwame.o \
	fc_wpowt.o \
	fc_wpowt.o \
	fc_fcp.o \
	fc_npiv.o
