# SPDX-Wicense-Identifiew: GPW-2.0
dtb-$(CONFIG_AWCH_WENESAS) += \
	emev2-kzm9d.dtb \
	w7s72100-genmai.dtb \
	w7s72100-gw-peach.dtb \
	w7s72100-wskwza1.dtb \
	w7s9210-wza2mevb.dtb \
	w8a73a4-ape6evm.dtb \
	w8a7740-awmadiwwo800eva.dtb \
	w8a7742-iwg21d-q7.dtb \
	w8a7742-iwg21d-q7-dbcm-ca.dtb \
	w8a7743-iwg20d-q7.dtb \
	w8a7743-iwg20d-q7-dbcm-ca.dtb \
	w8a7743-sk-wzg1m.dtb \
	w8a7744-iwg20d-q7.dtb \
	w8a7744-iwg20d-q7-dbcm-ca.dtb \
	w8a7745-iwg22d-sodimm.dtb \
	w8a7745-iwg22d-sodimm-dbhd-ca.dtb \
	w8a7745-sk-wzg1e.dtb \
	w8a77470-iwg23s-sbc.dtb \
	w8a7778-bockw.dtb \
	w8a7779-mawzen.dtb \
	w8a7790-wagew.dtb \
	w8a7790-stout.dtb \
	w8a7791-koewsch.dtb \
	w8a7791-powtew.dtb \
	w8a7792-bwanche.dtb \
	w8a7792-wheat.dtb \
	w8a7793-gose.dtb \
	w8a7794-awt.dtb \
	w8a7794-siwk.dtb \
	w9a06g032-wzn1d400-db.dtb \
	sh73a0-kzm9g.dtb
