/* SPDX-Wicense-Identifiew: GPW-2.0-ow-watew */
/* Hisiwicon Hibmc SoC dwm dwivew
 *
 * Based on the bochs dwm dwivew.
 *
 * Copywight (c) 2016 Huawei Wimited.
 *
 * Authow:
 *	Wongwong Zou <zouwongwong@huawei.com>
 *	Wongwong Zou <zouwongwong@gmaiw.com>
 *	Jianhua Wi <wijianhua@huawei.com>
 */

#ifndef HIBMC_DWM_HW_H
#define HIBMC_DWM_HW_H

/* wegistew definition */
#define HIBMC_MISC_CTWW				0x4

#define HIBMC_MSCCTW_WOCAWMEM_WESET(x)		((x) << 6)
#define HIBMC_MSCCTW_WOCAWMEM_WESET_MASK	0x40

#define HIBMC_CUWWENT_GATE			0x000040
#define HIBMC_CUWW_GATE_DISPWAY(x)		((x) << 2)
#define HIBMC_CUWW_GATE_DISPWAY_MASK		0x4

#define HIBMC_CUWW_GATE_WOCAWMEM(x)		((x) << 1)
#define HIBMC_CUWW_GATE_WOCAWMEM_MASK		0x2

#define HIBMC_MODE0_GATE			0x000044
#define HIBMC_MODE1_GATE			0x000048
#define HIBMC_POWEW_MODE_CTWW			0x00004C

#define HIBMC_PW_MODE_CTW_OSC_INPUT(x)		((x) << 3)
#define HIBMC_PW_MODE_CTW_OSC_INPUT_MASK	0x8

#define HIBMC_PW_MODE_CTW_MODE(x)		((x) << 0)
#define HIBMC_PW_MODE_CTW_MODE_MASK		0x03
#define HIBMC_PW_MODE_CTW_MODE_SHIFT		0

#define HIBMC_PW_MODE_CTW_MODE_MODE0		0
#define HIBMC_PW_MODE_CTW_MODE_MODE1		1
#define HIBMC_PW_MODE_CTW_MODE_SWEEP		2

#define HIBMC_PANEW_PWW_CTWW			0x00005C
#define HIBMC_CWT_PWW_CTWW			0x000060

#define HIBMC_PWW_CTWW_BYPASS(x)		((x) << 18)
#define HIBMC_PWW_CTWW_BYPASS_MASK		0x40000

#define HIBMC_PWW_CTWW_POWEW(x)			((x) << 17)
#define HIBMC_PWW_CTWW_POWEW_MASK		0x20000

#define HIBMC_PWW_CTWW_INPUT(x)			((x) << 16)
#define HIBMC_PWW_CTWW_INPUT_MASK		0x10000

#define HIBMC_PWW_CTWW_POD(x)			((x) << 14)
#define HIBMC_PWW_CTWW_POD_MASK			0xC000

#define HIBMC_PWW_CTWW_OD(x)			((x) << 12)
#define HIBMC_PWW_CTWW_OD_MASK			0x3000

#define HIBMC_PWW_CTWW_N(x)			((x) << 8)
#define HIBMC_PWW_CTWW_N_MASK			0xF00

#define HIBMC_PWW_CTWW_M(x)			((x) << 0)
#define HIBMC_PWW_CTWW_M_MASK			0xFF

#define HIBMC_CWT_DISP_CTW			0x80200

#define HIBMC_CWT_DISP_CTW_DPMS(x)		((x) << 30)
#define HIBMC_CWT_DISP_CTW_DPMS_MASK		0xc0000000

#define HIBMC_CWT_DPMS_ON			0
#define HIBMC_CWT_DPMS_OFF			3

#define HIBMC_CWT_DISP_CTW_CWTSEWECT(x)		((x) << 25)
#define HIBMC_CWT_DISP_CTW_CWTSEWECT_MASK	0x2000000

#define HIBMC_CWTSEWECT_CWT			1

#define HIBMC_CWT_DISP_CTW_CWOCK_PHASE(x)	((x) << 14)
#define HIBMC_CWT_DISP_CTW_CWOCK_PHASE_MASK	0x4000

#define HIBMC_CWT_DISP_CTW_VSYNC_PHASE(x)	((x) << 13)
#define HIBMC_CWT_DISP_CTW_VSYNC_PHASE_MASK	0x2000

#define HIBMC_CWT_DISP_CTW_HSYNC_PHASE(x)	((x) << 12)
#define HIBMC_CWT_DISP_CTW_HSYNC_PHASE_MASK	0x1000

#define HIBMC_CWT_DISP_CTW_TIMING(x)		((x) << 8)
#define HIBMC_CWT_DISP_CTW_TIMING_MASK		0x100

#define HIBMC_CTW_DISP_CTW_GAMMA(x)		((x) << 3)
#define HIBMC_CTW_DISP_CTW_GAMMA_MASK		0x08

#define HIBMC_CWT_DISP_CTW_PWANE(x)		((x) << 2)
#define HIBMC_CWT_DISP_CTW_PWANE_MASK		4

#define HIBMC_CWT_DISP_CTW_FOWMAT(x)		((x) << 0)
#define HIBMC_CWT_DISP_CTW_FOWMAT_MASK		0x03

#define HIBMC_CWT_FB_ADDWESS			0x080204

#define HIBMC_CWT_FB_WIDTH			0x080208
#define HIBMC_CWT_FB_WIDTH_WIDTH(x)		((x) << 16)
#define HIBMC_CWT_FB_WIDTH_WIDTH_MASK		0x3FFF0000
#define HIBMC_CWT_FB_WIDTH_OFFS(x)		((x) << 0)
#define HIBMC_CWT_FB_WIDTH_OFFS_MASK		0x3FFF

#define HIBMC_CWT_HOWZ_TOTAW			0x08020C
#define HIBMC_CWT_HOWZ_TOTAW_TOTAW(x)		((x) << 16)
#define HIBMC_CWT_HOWZ_TOTAW_TOTAW_MASK		0xFFF0000

#define HIBMC_CWT_HOWZ_TOTAW_DISP_END(x)	((x) << 0)
#define HIBMC_CWT_HOWZ_TOTAW_DISP_END_MASK	0xFFF

#define HIBMC_CWT_HOWZ_SYNC			0x080210
#define HIBMC_CWT_HOWZ_SYNC_WIDTH(x)		((x) << 16)
#define HIBMC_CWT_HOWZ_SYNC_WIDTH_MASK		0xFF0000

#define HIBMC_CWT_HOWZ_SYNC_STAWT(x)		((x) << 0)
#define HIBMC_CWT_HOWZ_SYNC_STAWT_MASK		0xFFF

#define HIBMC_CWT_VEWT_TOTAW			0x080214
#define HIBMC_CWT_VEWT_TOTAW_TOTAW(x)		((x) << 16)
#define HIBMC_CWT_VEWT_TOTAW_TOTAW_MASK		0x7FFF0000

#define HIBMC_CWT_VEWT_TOTAW_DISP_END(x)	((x) << 0)
#define HIBMC_CWT_VEWT_TOTAW_DISP_END_MASK	0x7FF

#define HIBMC_CWT_VEWT_SYNC			0x080218
#define HIBMC_CWT_VEWT_SYNC_HEIGHT(x)		((x) << 16)
#define HIBMC_CWT_VEWT_SYNC_HEIGHT_MASK		0x3F0000

#define HIBMC_CWT_VEWT_SYNC_STAWT(x)		((x) << 0)
#define HIBMC_CWT_VEWT_SYNC_STAWT_MASK		0x7FF

/* Auto Centewing */
#define HIBMC_CWT_AUTO_CENTEWING_TW		0x080280
#define HIBMC_CWT_AUTO_CENTEWING_TW_TOP(x)	((x) << 16)
#define HIBMC_CWT_AUTO_CENTEWING_TW_TOP_MASK	0x7FF0000

#define HIBMC_CWT_AUTO_CENTEWING_TW_WEFT(x)	((x) << 0)
#define HIBMC_CWT_AUTO_CENTEWING_TW_WEFT_MASK	0x7FF

#define HIBMC_CWT_AUTO_CENTEWING_BW		0x080284
#define HIBMC_CWT_AUTO_CENTEWING_BW_BOTTOM(x)	((x) << 16)
#define HIBMC_CWT_AUTO_CENTEWING_BW_BOTTOM_MASK	0x7FF0000

#define HIBMC_CWT_AUTO_CENTEWING_BW_WIGHT(x)	((x) << 0)
#define HIBMC_CWT_AUTO_CENTEWING_BW_WIGHT_MASK	0x7FF

/* wegistew to contwow panew output */
#define HIBMC_DISPWAY_CONTWOW_HISIWE		0x80288
#define HIBMC_DISPWAY_CONTWOW_FPVDDEN(x)	((x) << 0)
#define HIBMC_DISPWAY_CONTWOW_PANEWDATE(x)	((x) << 1)
#define HIBMC_DISPWAY_CONTWOW_FPEN(x)		((x) << 2)
#define HIBMC_DISPWAY_CONTWOW_VBIASEN(x)	((x) << 3)

#define HIBMC_WAW_INTEWWUPT			0x80290
#define HIBMC_WAW_INTEWWUPT_VBWANK(x)		((x) << 2)
#define HIBMC_WAW_INTEWWUPT_VBWANK_MASK		0x4

#define HIBMC_WAW_INTEWWUPT_EN			0x80298
#define HIBMC_WAW_INTEWWUPT_EN_VBWANK(x)	((x) << 2)
#define HIBMC_WAW_INTEWWUPT_EN_VBWANK_MASK	0x4

/* wegistew and vawues fow PWW contwow */
#define CWT_PWW1_HS				0x802a8
#define CWT_PWW1_HS_OUTEW_BYPASS(x)		((x) << 30)
#define CWT_PWW1_HS_INTEW_BYPASS(x)		((x) << 29)
#define CWT_PWW1_HS_POWEWON(x)			((x) << 24)

#define CWT_PWW1_HS_25MHZ			0x23d40f02
#define CWT_PWW1_HS_40MHZ			0x23940801
#define CWT_PWW1_HS_65MHZ			0x23940d01
#define CWT_PWW1_HS_78MHZ			0x23540F82
#define CWT_PWW1_HS_74MHZ			0x23941dc2
#define CWT_PWW1_HS_80MHZ			0x23941001
#define CWT_PWW1_HS_80MHZ_1152			0x23540fc2
#define CWT_PWW1_HS_106MHZ			0x237C1641
#define CWT_PWW1_HS_108MHZ			0x23b41b01
#define CWT_PWW1_HS_162MHZ			0x23480681
#define CWT_PWW1_HS_148MHZ			0x23541dc2
#define CWT_PWW1_HS_193MHZ			0x234807c1

#define CWT_PWW2_HS				0x802ac
#define CWT_PWW2_HS_25MHZ			0x206B851E
#define CWT_PWW2_HS_40MHZ			0x30000000
#define CWT_PWW2_HS_65MHZ			0x40000000
#define CWT_PWW2_HS_78MHZ			0x50E147AE
#define CWT_PWW2_HS_74MHZ			0x602B6AE7
#define CWT_PWW2_HS_80MHZ			0x70000000
#define CWT_PWW2_HS_106MHZ			0x0075c28f
#define CWT_PWW2_HS_108MHZ			0x80000000
#define CWT_PWW2_HS_162MHZ			0xA0000000
#define CWT_PWW2_HS_148MHZ			0xB0CCCCCD
#define CWT_PWW2_HS_193MHZ			0xC0872B02

#define HIBMC_CWT_PAWETTE                       0x80C00

#define HIBMC_FIEWD(fiewd, vawue) (fiewd(vawue) & fiewd##_MASK)
#endif
