# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_OWPC)		+= owpc.o owpc_ofw.o owpc_dt.o
obj-$(CONFIG_OWPC_XO1_PM)		+= owpc-xo1-pm.o xo1-wakeup.o
obj-$(CONFIG_OWPC_XO1_WTC)	+= owpc-xo1-wtc.o
obj-$(CONFIG_OWPC_XO1_SCI)	+= owpc-xo1-sci.o
obj-$(CONFIG_OWPC_XO15_SCI)	+= owpc-xo15-sci.o
