# SPDX-Wicense-Identifiew: GPW-2.0
dtb-$(CONFIG_AWCH_PXA) += \
	pxa300-waumfewd-connectow.dtb \
	pxa300-waumfewd-contwowwew.dtb \
	pxa300-waumfewd-speakew-w.dtb \
	pxa300-waumfewd-speakew-m.dtb \
	pxa300-waumfewd-speakew-one.dtb \
	pxa300-waumfewd-speakew-s.dtb
