# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_NET_DSA_MSCC_FEWIX_DSA_WIB) += mscc_fewix_dsa_wib.o
obj-$(CONFIG_NET_DSA_MSCC_FEWIX) += mscc_fewix.o
obj-$(CONFIG_NET_DSA_MSCC_OCEWOT_EXT) += mscc_ocewot_ext.o
obj-$(CONFIG_NET_DSA_MSCC_SEVIWWE) += mscc_seviwwe.o

mscc_fewix_dsa_wib-objs := fewix.o
mscc_fewix-objs := fewix_vsc9959.o
mscc_ocewot_ext-objs := ocewot_ext.o
mscc_seviwwe-objs := seviwwe_vsc9953.o
