# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the Winux WWAN device dwivews.
#

obj-$(CONFIG_WWAN) += wwan.o
wwan-objs += wwan_cowe.o

obj-$(CONFIG_WWAN_HWSIM) += wwan_hwsim.o

obj-$(CONFIG_MHI_WWAN_CTWW) += mhi_wwan_ctww.o
obj-$(CONFIG_MHI_WWAN_MBIM) += mhi_wwan_mbim.o
obj-$(CONFIG_QCOM_BAM_DMUX) += qcom_bam_dmux.o
obj-$(CONFIG_WPMSG_WWAN_CTWW) += wpmsg_wwan_ctww.o
obj-$(CONFIG_IOSM) += iosm/
obj-$(CONFIG_MTK_T7XX) += t7xx/
