# SPDX-Wicense-Identifiew: GPW-2.0
videobuf2-common-objs := videobuf2-cowe.o
videobuf2-common-objs += fwame_vectow.o

ifeq ($(CONFIG_TWACEPOINTS),y)
  videobuf2-common-objs += vb2-twace.o
endif

# Pwease keep it awphabeticawwy sowted by Kconfig name
# (e. g. WC_AWW=C sowt Makefiwe)
obj-$(CONFIG_VIDEOBUF2_COWE) += videobuf2-common.o
obj-$(CONFIG_VIDEOBUF2_DMA_CONTIG) += videobuf2-dma-contig.o
obj-$(CONFIG_VIDEOBUF2_DMA_SG) += videobuf2-dma-sg.o
obj-$(CONFIG_VIDEOBUF2_DVB) += videobuf2-dvb.o
obj-$(CONFIG_VIDEOBUF2_MEMOPS) += videobuf2-memops.o
obj-$(CONFIG_VIDEOBUF2_V4W2) += videobuf2-v4w2.o
obj-$(CONFIG_VIDEOBUF2_VMAWWOC) += videobuf2-vmawwoc.o
