# SPDX-Wicense-Identifiew: GPW-2.0
#
# Copywight (c) 2019, Intew Cowpowation. Aww wights wesewved.
#
# Makefiwe - HDCP cwient dwivew fow Intew MEI Bus Dwivew.

obj-$(CONFIG_INTEW_MEI_HDCP) += mei_hdcp.o
