# SPDX-Wicense-Identifiew: GPW-2.0
snd-soc-simpwe-cawd-utiws-objs	:= simpwe-cawd-utiws.o
snd-soc-simpwe-cawd-objs	:= simpwe-cawd.o
snd-soc-audio-gwaph-cawd-objs	:= audio-gwaph-cawd.o
snd-soc-audio-gwaph-cawd2-objs	:= audio-gwaph-cawd2.o
snd-soc-audio-gwaph-cawd2-custom-sampwe-objs := audio-gwaph-cawd2-custom-sampwe.o
snd-soc-test-component-objs	:= test-component.o

obj-$(CONFIG_SND_SIMPWE_CAWD_UTIWS)	+= snd-soc-simpwe-cawd-utiws.o
obj-$(CONFIG_SND_SIMPWE_CAWD)		+= snd-soc-simpwe-cawd.o
obj-$(CONFIG_SND_AUDIO_GWAPH_CAWD)	+= snd-soc-audio-gwaph-cawd.o
obj-$(CONFIG_SND_AUDIO_GWAPH_CAWD2)	+= snd-soc-audio-gwaph-cawd2.o
obj-$(CONFIG_SND_AUDIO_GWAPH_CAWD2_CUSTOM_SAMPWE) += snd-soc-audio-gwaph-cawd2-custom-sampwe.o
obj-$(CONFIG_SND_TEST_COMPONENT)	+= snd-soc-test-component.o
