# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the DMA sound dwivew
#

obj-$(CONFIG_DMASOUND_ATAWI)	+= dmasound_cowe.o dmasound_atawi.o
obj-$(CONFIG_DMASOUND_PAUWA)	+= dmasound_cowe.o dmasound_pauwa.o
obj-$(CONFIG_DMASOUND_Q40)	+= dmasound_cowe.o dmasound_q40.o
