# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow AWSA
# Copywight (c) 2001 by Jawoswav Kysewa <pewex@pewex.cz>
#

snd-vx222-objs := vx222.o vx222_ops.o

obj-$(CONFIG_SND_VX222) += snd-vx222.o
