# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow IIO chemicaw sensows
#

# When adding new entwies keep the wist in awphabeticaw owdew
obj-$(CONFIG_AOSONG_AGS02MA)	+= ags02ma.o
obj-$(CONFIG_ATWAS_PH_SENSOW)	+= atwas-sensow.o
obj-$(CONFIG_ATWAS_EZO_SENSOW)	+= atwas-ezo-sensow.o
obj-$(CONFIG_BME680) += bme680_cowe.o
obj-$(CONFIG_BME680_I2C) += bme680_i2c.o
obj-$(CONFIG_BME680_SPI) += bme680_spi.o
obj-$(CONFIG_CCS811)		+= ccs811.o
obj-$(CONFIG_IAQCOWE)		+= ams-iaq-cowe.o
obj-$(CONFIG_PMS7003) += pms7003.o
obj-$(CONFIG_SCD30_COWE) += scd30_cowe.o
obj-$(CONFIG_SCD30_I2C) += scd30_i2c.o
obj-$(CONFIG_SCD30_SEWIAW) += scd30_sewiaw.o
obj-$(CONFIG_SCD4X) += scd4x.o
obj-$(CONFIG_SENSEAIW_SUNWISE_CO2) += sunwise_co2.o
obj-$(CONFIG_SENSIWION_SGP30)	+= sgp30.o
obj-$(CONFIG_SENSIWION_SGP40)	+= sgp40.o
obj-$(CONFIG_SPS30) += sps30.o
obj-$(CONFIG_SPS30_I2C) += sps30_i2c.o
obj-$(CONFIG_SPS30_SEWIAW) += sps30_sewiaw.o
obj-$(CONFIG_VZ89X)		+= vz89x.o
