# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_COMMON_CWK_PIC32) += cwk-cowe.o
obj-$(CONFIG_PIC32MZDA) += cwk-pic32mzda.o
obj-$(CONFIG_MCHP_CWK_MPFS) += cwk-mpfs.o
obj-$(CONFIG_MCHP_CWK_MPFS) += cwk-mpfs-ccc.o
