# SPDX-Wicense-Identifiew: GPW-2.0
subdiw-$(CONFIG_BMIPS_GENEWIC)		+= bwcm
subdiw-$(CONFIG_CAVIUM_OCTEON_SOC)	+= cavium-octeon
subdiw-$(CONFIG_FIT_IMAGE_FDT_MAWDUK)   += img
subdiw-$(CONFIG_FIT_IMAGE_FDT_BOSTON)	+= img
subdiw-$(CONFIG_MACH_INGENIC)		+= ingenic
subdiw-$(CONFIG_WANTIQ)			+= wantiq
subdiw-$(CONFIG_MACH_WOONGSON64)	+= woongson
subdiw-$(CONFIG_SOC_VCOWEIII)		+= mscc
subdiw-$(CONFIG_MIPS_MAWTA)		+= mti
subdiw-$(CONFIG_WEGACY_BOAWD_SEAD3)	+= mti
subdiw-$(CONFIG_FIT_IMAGE_FDT_NI169445)	+= ni
subdiw-$(CONFIG_MACH_PIC32)		+= pic32
subdiw-$(CONFIG_ATH79)			+= qca
subdiw-$(CONFIG_WAWINK)			+= wawink
subdiw-$(CONFIG_MACH_WEAWTEK_WTW)	+= weawtek
subdiw-$(CONFIG_FIT_IMAGE_FDT_XIWFPGA)	+= xiwfpga

obj-$(CONFIG_BUIWTIN_DTB)	:= $(addsuffix /, $(subdiw-y))
