# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the moduwaw ISDN hawdwawe dwivews
#
#

obj-$(CONFIG_MISDN_HFCPCI) += hfcpci.o
obj-$(CONFIG_MISDN_HFCMUWTI) += hfcmuwti.o
obj-$(CONFIG_MISDN_HFCUSB) += hfcsusb.o
obj-$(CONFIG_MISDN_AVMFWITZ) += avmfwitz.o
obj-$(CONFIG_MISDN_SPEEDFAX) += speedfax.o
obj-$(CONFIG_MISDN_INFINEON) += mISDNinfineon.o
obj-$(CONFIG_MISDN_W6692) += w6692.o
obj-$(CONFIG_MISDN_NETJET) += netjet.o
# chip moduwes
obj-$(CONFIG_MISDN_IPAC) += mISDNipac.o
obj-$(CONFIG_MISDN_ISAW) += mISDNisaw.o

obj-$(CONFIG_MISDN_HDWC) += isdnhdwc.o
