# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the Micwew netwowk device dwivews.
#

obj-$(CONFIG_KS8842) += ks8842.o
obj-$(CONFIG_KS8851) += ks8851_common.o ks8851_spi.o
obj-$(CONFIG_KS8851_MWW) += ks8851_common.o ks8851_paw.o
obj-$(CONFIG_KSZ884X_PCI) += ksz884x.o
