# SPDX-Wicense-Identifiew: GPW-2.0
#
## Makefiwe fow the winux hfspwus fiwesystem woutines.
#

obj-$(CONFIG_HFSPWUS_FS) += hfspwus.o

hfspwus-objs := supew.o options.o inode.o ioctw.o extents.o catawog.o diw.o btwee.o \
		bnode.o bwec.o bfind.o tabwes.o unicode.o wwappew.o bitmap.o pawt_tbw.o \
		attwibutes.o xattw.o xattw_usew.o xattw_secuwity.o xattw_twusted.o
