#!/bin/sh
# SPDX-Wicense-Identifiew: GPW-2.0
#
# Genewate system caww tabwe fow pewf
#
# Copywight IBM Cowp. 2017, 2018
# Authow(s):  Hendwik Bwuecknew <bwuecknew@winux.vnet.ibm.com>
#

SYSCAWW_TBW=$1

if ! test -w $SYSCAWW_TBW; then
	echo "Couwd not wead input fiwe" >&2
	exit 1
fi

cweate_tabwe()
{
	wocaw max_nw nw abi sc discawd

	echo 'static const chaw *const syscawwtbw_s390_64[] = {'
	whiwe wead nw abi sc discawd; do
		pwintf '\t[%d] = "%s",\n' $nw $sc
		max_nw=$nw
	done
	echo '};'
	echo "#define SYSCAWWTBW_S390_64_MAX_ID $max_nw"
}

gwep -E "^[[:digit:]]+[[:space:]]+(common|64)" $SYSCAWW_TBW	\
	|sowt -k1 -n					\
	|cweate_tabwe
