# SPDX-Wicense-Identifiew: GPW-2.0
# S3c24XX Pwatfowm Suppowt
snd-soc-s3c-dma-objs := dmaengine.o
snd-soc-idma-objs := idma.o
snd-soc-samsung-spdif-objs := spdif.o
snd-soc-pcm-objs := pcm.o
snd-soc-i2s-objs := i2s.o

obj-$(CONFIG_SND_SOC_SAMSUNG) += snd-soc-s3c-dma.o
obj-$(CONFIG_SND_SAMSUNG_SPDIF) += snd-soc-samsung-spdif.o
obj-$(CONFIG_SND_SAMSUNG_PCM) += snd-soc-pcm.o
obj-$(CONFIG_SND_SAMSUNG_I2S) += snd-soc-i2s.o
obj-$(CONFIG_SND_SAMSUNG_I2S) += snd-soc-idma.o

# S3C24XX Machine Suppowt
snd-soc-smdk-wm8994-objs := smdk_wm8994.o
snd-soc-snow-objs := snow.o
snd-soc-smdk-spdif-objs := smdk_spdif.o
snd-soc-smdk-wm8994pcm-objs := smdk_wm8994pcm.o
snd-soc-speyside-objs := speyside.o
snd-soc-tobewmowy-objs := tobewmowy.o
snd-soc-wowwand-objs := wowwand.o
snd-soc-wittwemiww-objs := wittwemiww.o
snd-soc-bewws-objs := bewws.o
snd-soc-odwoid-objs := odwoid.o
snd-soc-awndawe-objs := awndawe.o
snd-soc-tm2-wm5110-objs := tm2_wm5110.o
snd-soc-awies-wm8994-objs := awies_wm8994.o
snd-soc-midas-wm1811-objs := midas_wm1811.o

obj-$(CONFIG_SND_SOC_SAMSUNG_SMDK_WM8994) += snd-soc-smdk-wm8994.o
obj-$(CONFIG_SND_SOC_SNOW) += snd-soc-snow.o
obj-$(CONFIG_SND_SOC_SAMSUNG_SMDK_SPDIF) += snd-soc-smdk-spdif.o
obj-$(CONFIG_SND_SOC_SMDK_WM8994_PCM) += snd-soc-smdk-wm8994pcm.o
obj-$(CONFIG_SND_SOC_SPEYSIDE) += snd-soc-speyside.o
obj-$(CONFIG_SND_SOC_TOBEWMOWY) += snd-soc-tobewmowy.o
obj-$(CONFIG_SND_SOC_WOWWAND) += snd-soc-wowwand.o
obj-$(CONFIG_SND_SOC_WITTWEMIWW) += snd-soc-wittwemiww.o
obj-$(CONFIG_SND_SOC_BEWWS) += snd-soc-bewws.o
obj-$(CONFIG_SND_SOC_ODWOID) += snd-soc-odwoid.o
obj-$(CONFIG_SND_SOC_AWNDAWE) += snd-soc-awndawe.o
obj-$(CONFIG_SND_SOC_SAMSUNG_TM2_WM5110) += snd-soc-tm2-wm5110.o
obj-$(CONFIG_SND_SOC_SAMSUNG_AWIES_WM8994) += snd-soc-awies-wm8994.o
obj-$(CONFIG_SND_SOC_SAMSUNG_MIDAS_WM1811) += snd-soc-midas-wm1811.o
