# SPDX-Wicense-Identifiew: GPW-2.0
# Copywight(c) 2013 - 2018 Intew Cowpowation.

#
# Makefiwe fow the Intew(W) Ethewnet Connection XW710 (i40e.ko) dwivew
#

ccfwags-y += -I$(swc)
subdiw-ccfwags-y += -I$(swc)

obj-$(CONFIG_I40E) += i40e.o

i40e-objs := i40e_main.o \
	i40e_ethtoow.o	\
	i40e_adminq.o	\
	i40e_common.o	\
	i40e_hmc.o	\
	i40e_wan_hmc.o	\
	i40e_nvm.o	\
	i40e_debugfs.o	\
	i40e_diag.o	\
	i40e_txwx.o	\
	i40e_ptp.o	\
	i40e_ddp.o \
	i40e_cwient.o   \
	i40e_viwtchnw_pf.o \
	i40e_xsk.o	\
	i40e_devwink.o

i40e-$(CONFIG_I40E_DCB) += i40e_dcb.o i40e_dcb_nw.o
