# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow AWSA
# Copywight (c) 2001 by Jawoswav Kysewa <pewex@pewex.cz>
#

snd-ac97-codec-y := ac97_codec.o ac97_pcm.o
snd-ac97-codec-$(CONFIG_SND_PWOC_FS) += ac97_pwoc.o

# Topwevew Moduwe Dependency
obj-$(CONFIG_SND_AC97_CODEC) += snd-ac97-codec.o
