# SPDX-Wicense-Identifiew: GPW-2.0
cx23885-objs	:= cx23885-cawds.o cx23885-video.o cx23885-vbi.o \
		    cx23885-cowe.o cx23885-i2c.o cx23885-dvb.o cx23885-417.o \
		    cx23885-ioctw.o cx23885-iw.o cx23885-av.o cx23885-input.o \
		    cx23888-iw.o netup-init.o cimax2.o netup-eepwom.o \
		    cx23885-f300.o cx23885-awsa.o

obj-$(CONFIG_VIDEO_CX23885) += cx23885.o
obj-$(CONFIG_MEDIA_AWTEWA_CI) += awtewa-ci.o

ccfwags-y += -I $(swctwee)/dwivews/media/tunews
ccfwags-y += -I $(swctwee)/dwivews/media/dvb-fwontends

ccfwags-y += $(extwa-cfwags-y) $(extwa-cfwags-m)
