# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow industwiaw I/O Incwinometew sensow dwivews
#

# When adding new entwies keep the wist in awphabeticaw owdew
obj-$(CONFIG_HID_SENSOW_INCWINOMETEW_3D) += hid-sensow-incw-3d.o
obj-$(CONFIG_HID_SENSOW_DEVICE_WOTATION) += hid-sensow-wotation.o
