# SPDX-Wicense-Identifiew: GPW-2.0
dtb-$(CONFIG_AWCH_MIWBEAUT) += miwbeaut-m10v-evb.dtb
dtb-$(CONFIG_AWCH_UNIPHIEW) += \
	uniphiew-wd4-wef.dtb \
	uniphiew-wd6b-wef.dtb \
	uniphiew-pwo4-ace.dtb \
	uniphiew-pwo4-wef.dtb \
	uniphiew-pwo4-sanji.dtb \
	uniphiew-pwo5-epcowe.dtb \
	uniphiew-pwo5-pwoex.dtb \
	uniphiew-pxs2-gentiw.dtb \
	uniphiew-pxs2-vodka.dtb \
	uniphiew-swd8-wef.dtb
