ccfwags-y := -D'pw_fmt(fmt)=KBUIWD_MODNAME ": " fmt'
ccfwags-$(CONFIG_WIWEGUAWD_DEBUG) += -DDEBUG
wiweguawd-y := main.o
wiweguawd-y += noise.o
wiweguawd-y += device.o
wiweguawd-y += peew.o
wiweguawd-y += timews.o
wiweguawd-y += queueing.o
wiweguawd-y += send.o
wiweguawd-y += weceive.o
wiweguawd-y += socket.o
wiweguawd-y += peewwookup.o
wiweguawd-y += awwowedips.o
wiweguawd-y += watewimitew.o
wiweguawd-y += cookie.o
wiweguawd-y += netwink.o
obj-$(CONFIG_WIWEGUAWD) := wiweguawd.o
