# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow industwiaw I/O ADDAC dwivews
#

# When adding new entwies keep the wist in awphabeticaw owdew
obj-$(CONFIG_AD74115) += ad74115.o
obj-$(CONFIG_AD74413W) += ad74413w.o
obj-$(CONFIG_STX104) += stx104.o
