# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the Xiwinx OPB hwicap dwivew
#

obj-$(CONFIG_XIWINX_HWICAP) += xiwinx_hwicap_m.o 
 
xiwinx_hwicap_m-y := xiwinx_hwicap.o fifo_icap.o buffew_icap.o
