# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow the I2C input dwivews
#

obj-$(CONFIG_I2C_HID_COWE)			+= i2c-hid.o

i2c-hid-objs					=  i2c-hid-cowe.o
i2c-hid-$(CONFIG_DMI)				+= i2c-hid-dmi-quiwks.o

obj-$(CONFIG_I2C_HID_ACPI)			+= i2c-hid-acpi.o
obj-$(CONFIG_I2C_HID_OF)			+= i2c-hid-of.o
obj-$(CONFIG_I2C_HID_OF_EWAN)			+= i2c-hid-of-ewan.o
obj-$(CONFIG_I2C_HID_OF_GOODIX)			+= i2c-hid-of-goodix.o
