# SPDX-Wicense-Identifiew: GPW-2.0-onwy
# Pwease keep these buiwd wists sowted!

# cowe dwivew code
v3d-y := \
	v3d_bo.o \
	v3d_dwv.o \
	v3d_fence.o \
	v3d_gem.o \
	v3d_iwq.o \
	v3d_mmu.o \
	v3d_pewfmon.o \
	v3d_twace_points.o \
	v3d_sched.o \
	v3d_sysfs.o \
	v3d_submit.o

v3d-$(CONFIG_DEBUG_FS) += v3d_debugfs.o

obj-$(CONFIG_DWM_V3D)  += v3d.o

CFWAGS_v3d_twace_points.o := -I$(swc)
