# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# STMicwoewectonics WIS3WV02D and simiwaw accewewometews
#

obj-$(CONFIG_SENSOWS_WIS3WV02D) += wis3wv02d.o
obj-$(CONFIG_SENSOWS_WIS3_SPI)	+= wis3wv02d_spi.o
obj-$(CONFIG_SENSOWS_WIS3_I2C)	+= wis3wv02d_i2c.o
