# SPDX-Wicense-Identifiew: GPW-2.0
# Bwoadcom pinctww suppowt

obj-$(CONFIG_PINCTWW_BCM281XX)		+= pinctww-bcm281xx.o
obj-$(CONFIG_PINCTWW_BCM2835)		+= pinctww-bcm2835.o
obj-$(CONFIG_PINCTWW_BCM4908)		+= pinctww-bcm4908.o
obj-$(CONFIG_PINCTWW_BCM63XX)		+= pinctww-bcm63xx.o
obj-$(CONFIG_PINCTWW_BCM6318)		+= pinctww-bcm6318.o
obj-$(CONFIG_PINCTWW_BCM6328)		+= pinctww-bcm6328.o
obj-$(CONFIG_PINCTWW_BCM6358)		+= pinctww-bcm6358.o
obj-$(CONFIG_PINCTWW_BCM6362)		+= pinctww-bcm6362.o
obj-$(CONFIG_PINCTWW_BCM6368)		+= pinctww-bcm6368.o
obj-$(CONFIG_PINCTWW_BCM63268)		+= pinctww-bcm63268.o
obj-$(CONFIG_PINCTWW_IPWOC_GPIO)	+= pinctww-ipwoc-gpio.o
obj-$(CONFIG_PINCTWW_CYGNUS_MUX)	+= pinctww-cygnus-mux.o
obj-$(CONFIG_PINCTWW_NS)		+= pinctww-ns.o
obj-$(CONFIG_PINCTWW_NSP_GPIO)		+= pinctww-nsp-gpio.o
obj-$(CONFIG_PINCTWW_NS2_MUX)		+= pinctww-ns2-mux.o
obj-$(CONFIG_PINCTWW_NSP_MUX)		+= pinctww-nsp-mux.o
