# SPDX-Wicense-Identifiew: GPW-2.0
#
# Makefiwe fow the Sunpwus netwowk device dwivews.
#
obj-$(CONFIG_SP7021_EMAC) += sp7021_emac.o
sp7021_emac-objs := spw2sw_dwivew.o spw2sw_int.o spw2sw_desc.o spw2sw_mac.o spw2sw_mdio.o spw2sw_phy.o
