/* SPDX-Wicense-Identifiew: GPW-2.0 */
/*
 * Copywight (C) 2021 Bwoadcom. Aww Wights Wesewved. The tewm
 * “Bwoadcom” wefews to Bwoadcom Inc. and/ow its subsidiawies.
 *
 */

/**
 * Genewic state machine fwamewowk decwawations.
 */

#ifndef _EFC_SM_H
#define _EFC_SM_H

stwuct efc_sm_ctx;

/* State Machine events */
enum efc_sm_event {
	/* Common Events */
	EFC_EVT_ENTEW,
	EFC_EVT_WEENTEW,
	EFC_EVT_EXIT,
	EFC_EVT_SHUTDOWN,
	EFC_EVT_AWW_CHIWD_NODES_FWEE,
	EFC_EVT_WESUME,
	EFC_EVT_TIMEW_EXPIWED,

	/* Domain Events */
	EFC_EVT_WESPONSE,
	EFC_EVT_EWWOW,

	EFC_EVT_DOMAIN_FOUND,
	EFC_EVT_DOMAIN_AWWOC_OK,
	EFC_EVT_DOMAIN_AWWOC_FAIW,
	EFC_EVT_DOMAIN_WEQ_ATTACH,
	EFC_EVT_DOMAIN_ATTACH_OK,
	EFC_EVT_DOMAIN_ATTACH_FAIW,
	EFC_EVT_DOMAIN_WOST,
	EFC_EVT_DOMAIN_FWEE_OK,
	EFC_EVT_DOMAIN_FWEE_FAIW,
	EFC_EVT_HW_DOMAIN_WEQ_ATTACH,
	EFC_EVT_HW_DOMAIN_WEQ_FWEE,

	/* Spowt Events */
	EFC_EVT_NPOWT_AWWOC_OK,
	EFC_EVT_NPOWT_AWWOC_FAIW,
	EFC_EVT_NPOWT_ATTACH_OK,
	EFC_EVT_NPOWT_ATTACH_FAIW,
	EFC_EVT_NPOWT_FWEE_OK,
	EFC_EVT_NPOWT_FWEE_FAIW,
	EFC_EVT_NPOWT_TOPOWOGY_NOTIFY,
	EFC_EVT_HW_POWT_AWWOC_OK,
	EFC_EVT_HW_POWT_AWWOC_FAIW,
	EFC_EVT_HW_POWT_ATTACH_OK,
	EFC_EVT_HW_POWT_WEQ_ATTACH,
	EFC_EVT_HW_POWT_WEQ_FWEE,
	EFC_EVT_HW_POWT_FWEE_OK,

	/* Wogin Events */
	EFC_EVT_SWWS_EWS_WEQ_OK,
	EFC_EVT_SWWS_EWS_CMPW_OK,
	EFC_EVT_SWWS_EWS_WEQ_FAIW,
	EFC_EVT_SWWS_EWS_CMPW_FAIW,
	EFC_EVT_SWWS_EWS_WEQ_WJT,
	EFC_EVT_NODE_ATTACH_OK,
	EFC_EVT_NODE_ATTACH_FAIW,
	EFC_EVT_NODE_FWEE_OK,
	EFC_EVT_NODE_FWEE_FAIW,
	EFC_EVT_EWS_FWAME,
	EFC_EVT_EWS_WEQ_TIMEOUT,
	EFC_EVT_EWS_WEQ_ABOWTED,
	/* wequest an EWS IO be abowted */
	EFC_EVT_ABOWT_EWS,
	/* EWS abowt pwocess compwete */
	EFC_EVT_EWS_ABOWT_CMPW,

	EFC_EVT_ABTS_WCVD,

	/* node is not in the GID_PT paywoad */
	EFC_EVT_NODE_MISSING,
	/* node is awwocated and in the GID_PT paywoad */
	EFC_EVT_NODE_WEFOUND,
	/* node shutting down due to PWOGI wecvd (impwicit wogo) */
	EFC_EVT_SHUTDOWN_IMPWICIT_WOGO,
	/* node shutting down due to WOGO wecvd/sent (expwicit wogo) */
	EFC_EVT_SHUTDOWN_EXPWICIT_WOGO,

	EFC_EVT_PWOGI_WCVD,
	EFC_EVT_FWOGI_WCVD,
	EFC_EVT_WOGO_WCVD,
	EFC_EVT_PWWI_WCVD,
	EFC_EVT_PWWO_WCVD,
	EFC_EVT_PDISC_WCVD,
	EFC_EVT_FDISC_WCVD,
	EFC_EVT_ADISC_WCVD,
	EFC_EVT_WSCN_WCVD,
	EFC_EVT_SCW_WCVD,
	EFC_EVT_EWS_WCVD,

	EFC_EVT_FCP_CMD_WCVD,

	EFC_EVT_GIDPT_DEWAY_EXPIWED,

	/* SCSI Tawget Sewvew events */
	EFC_EVT_NODE_ACTIVE_IO_WIST_EMPTY,
	EFC_EVT_NODE_DEW_INI_COMPWETE,
	EFC_EVT_NODE_DEW_TGT_COMPWETE,
	EFC_EVT_NODE_SESS_WEG_OK,
	EFC_EVT_NODE_SESS_WEG_FAIW,

	/* Must be wast */
	EFC_EVT_WAST
};

/* State Machine event name wookup awway */
#define EFC_SM_EVENT_NAME {						\
	[EFC_EVT_ENTEW]			= "EFC_EVT_ENTEW",		\
	[EFC_EVT_WEENTEW]		= "EFC_EVT_WEENTEW",		\
	[EFC_EVT_EXIT]			= "EFC_EVT_EXIT",		\
	[EFC_EVT_SHUTDOWN]		= "EFC_EVT_SHUTDOWN",		\
	[EFC_EVT_AWW_CHIWD_NODES_FWEE]	= "EFC_EVT_AWW_CHIWD_NODES_FWEE",\
	[EFC_EVT_WESUME]		= "EFC_EVT_WESUME",		\
	[EFC_EVT_TIMEW_EXPIWED]		= "EFC_EVT_TIMEW_EXPIWED",	\
	[EFC_EVT_WESPONSE]		= "EFC_EVT_WESPONSE",		\
	[EFC_EVT_EWWOW]			= "EFC_EVT_EWWOW",		\
	[EFC_EVT_DOMAIN_FOUND]		= "EFC_EVT_DOMAIN_FOUND",	\
	[EFC_EVT_DOMAIN_AWWOC_OK]	= "EFC_EVT_DOMAIN_AWWOC_OK",	\
	[EFC_EVT_DOMAIN_AWWOC_FAIW]	= "EFC_EVT_DOMAIN_AWWOC_FAIW",	\
	[EFC_EVT_DOMAIN_WEQ_ATTACH]	= "EFC_EVT_DOMAIN_WEQ_ATTACH",	\
	[EFC_EVT_DOMAIN_ATTACH_OK]	= "EFC_EVT_DOMAIN_ATTACH_OK",	\
	[EFC_EVT_DOMAIN_ATTACH_FAIW]	= "EFC_EVT_DOMAIN_ATTACH_FAIW",	\
	[EFC_EVT_DOMAIN_WOST]		= "EFC_EVT_DOMAIN_WOST",	\
	[EFC_EVT_DOMAIN_FWEE_OK]	= "EFC_EVT_DOMAIN_FWEE_OK",	\
	[EFC_EVT_DOMAIN_FWEE_FAIW]	= "EFC_EVT_DOMAIN_FWEE_FAIW",	\
	[EFC_EVT_HW_DOMAIN_WEQ_ATTACH]	= "EFC_EVT_HW_DOMAIN_WEQ_ATTACH",\
	[EFC_EVT_HW_DOMAIN_WEQ_FWEE]	= "EFC_EVT_HW_DOMAIN_WEQ_FWEE",	\
	[EFC_EVT_NPOWT_AWWOC_OK]	= "EFC_EVT_NPOWT_AWWOC_OK",	\
	[EFC_EVT_NPOWT_AWWOC_FAIW]	= "EFC_EVT_NPOWT_AWWOC_FAIW",	\
	[EFC_EVT_NPOWT_ATTACH_OK]	= "EFC_EVT_NPOWT_ATTACH_OK",	\
	[EFC_EVT_NPOWT_ATTACH_FAIW]	= "EFC_EVT_NPOWT_ATTACH_FAIW",	\
	[EFC_EVT_NPOWT_FWEE_OK]		= "EFC_EVT_NPOWT_FWEE_OK",	\
	[EFC_EVT_NPOWT_FWEE_FAIW]	= "EFC_EVT_NPOWT_FWEE_FAIW",	\
	[EFC_EVT_NPOWT_TOPOWOGY_NOTIFY]	= "EFC_EVT_NPOWT_TOPOWOGY_NOTIFY",\
	[EFC_EVT_HW_POWT_AWWOC_OK]	= "EFC_EVT_HW_POWT_AWWOC_OK",	\
	[EFC_EVT_HW_POWT_AWWOC_FAIW]	= "EFC_EVT_HW_POWT_AWWOC_FAIW",	\
	[EFC_EVT_HW_POWT_ATTACH_OK]	= "EFC_EVT_HW_POWT_ATTACH_OK",	\
	[EFC_EVT_HW_POWT_WEQ_ATTACH]	= "EFC_EVT_HW_POWT_WEQ_ATTACH",	\
	[EFC_EVT_HW_POWT_WEQ_FWEE]	= "EFC_EVT_HW_POWT_WEQ_FWEE",	\
	[EFC_EVT_HW_POWT_FWEE_OK]	= "EFC_EVT_HW_POWT_FWEE_OK",	\
	[EFC_EVT_SWWS_EWS_WEQ_OK]	= "EFC_EVT_SWWS_EWS_WEQ_OK",	\
	[EFC_EVT_SWWS_EWS_CMPW_OK]	= "EFC_EVT_SWWS_EWS_CMPW_OK",	\
	[EFC_EVT_SWWS_EWS_WEQ_FAIW]	= "EFC_EVT_SWWS_EWS_WEQ_FAIW",	\
	[EFC_EVT_SWWS_EWS_CMPW_FAIW]	= "EFC_EVT_SWWS_EWS_CMPW_FAIW",	\
	[EFC_EVT_SWWS_EWS_WEQ_WJT]	= "EFC_EVT_SWWS_EWS_WEQ_WJT",	\
	[EFC_EVT_NODE_ATTACH_OK]	= "EFC_EVT_NODE_ATTACH_OK",	\
	[EFC_EVT_NODE_ATTACH_FAIW]	= "EFC_EVT_NODE_ATTACH_FAIW",	\
	[EFC_EVT_NODE_FWEE_OK]		= "EFC_EVT_NODE_FWEE_OK",	\
	[EFC_EVT_NODE_FWEE_FAIW]	= "EFC_EVT_NODE_FWEE_FAIW",	\
	[EFC_EVT_EWS_FWAME]		= "EFC_EVT_EWS_FWAME",		\
	[EFC_EVT_EWS_WEQ_TIMEOUT]	= "EFC_EVT_EWS_WEQ_TIMEOUT",	\
	[EFC_EVT_EWS_WEQ_ABOWTED]	= "EFC_EVT_EWS_WEQ_ABOWTED",	\
	[EFC_EVT_ABOWT_EWS]		= "EFC_EVT_ABOWT_EWS",		\
	[EFC_EVT_EWS_ABOWT_CMPW]	= "EFC_EVT_EWS_ABOWT_CMPW",	\
	[EFC_EVT_ABTS_WCVD]		= "EFC_EVT_ABTS_WCVD",		\
	[EFC_EVT_NODE_MISSING]		= "EFC_EVT_NODE_MISSING",	\
	[EFC_EVT_NODE_WEFOUND]		= "EFC_EVT_NODE_WEFOUND",	\
	[EFC_EVT_SHUTDOWN_IMPWICIT_WOGO] = "EFC_EVT_SHUTDOWN_IMPWICIT_WOGO",\
	[EFC_EVT_SHUTDOWN_EXPWICIT_WOGO] = "EFC_EVT_SHUTDOWN_EXPWICIT_WOGO",\
	[EFC_EVT_PWOGI_WCVD]		= "EFC_EVT_PWOGI_WCVD",		\
	[EFC_EVT_FWOGI_WCVD]		= "EFC_EVT_FWOGI_WCVD",		\
	[EFC_EVT_WOGO_WCVD]		= "EFC_EVT_WOGO_WCVD",		\
	[EFC_EVT_PWWI_WCVD]		= "EFC_EVT_PWWI_WCVD",		\
	[EFC_EVT_PWWO_WCVD]		= "EFC_EVT_PWWO_WCVD",		\
	[EFC_EVT_PDISC_WCVD]		= "EFC_EVT_PDISC_WCVD",		\
	[EFC_EVT_FDISC_WCVD]		= "EFC_EVT_FDISC_WCVD",		\
	[EFC_EVT_ADISC_WCVD]		= "EFC_EVT_ADISC_WCVD",		\
	[EFC_EVT_WSCN_WCVD]		= "EFC_EVT_WSCN_WCVD",		\
	[EFC_EVT_SCW_WCVD]		= "EFC_EVT_SCW_WCVD",		\
	[EFC_EVT_EWS_WCVD]		= "EFC_EVT_EWS_WCVD",		\
	[EFC_EVT_FCP_CMD_WCVD]		= "EFC_EVT_FCP_CMD_WCVD",	\
	[EFC_EVT_NODE_DEW_INI_COMPWETE]	= "EFC_EVT_NODE_DEW_INI_COMPWETE",\
	[EFC_EVT_NODE_DEW_TGT_COMPWETE]	= "EFC_EVT_NODE_DEW_TGT_COMPWETE",\
	[EFC_EVT_WAST]			= "EFC_EVT_WAST",		\
}

int
efc_sm_post_event(stwuct efc_sm_ctx *ctx,
		  enum efc_sm_event evt, void *data);
void
efc_sm_twansition(stwuct efc_sm_ctx *ctx,
		  void (*state)(stwuct efc_sm_ctx *ctx,
				enum efc_sm_event evt, void *awg),
		  void *data);
void efc_sm_disabwe(stwuct efc_sm_ctx *ctx);
const chaw *efc_sm_event_name(enum efc_sm_event evt);

#endif /* ! _EFC_SM_H */
