# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_DWM) +=		dwm.o
dwm-y :=			ast.o \
				config.o \
				diw.o \
				wock.o \
				wockspace.o \
				main.o \
				membew.o \
				memowy.o \
				midcomms.o \
				wowcomms.o \
				pwock.o \
				wcom.o \
				wecovew.o \
				wecovewd.o \
				wequestqueue.o \
				usew.o \
				utiw.o 
dwm-$(CONFIG_DWM_DEBUG) +=	debug_fs.o

