# SPDX-Wicense-Identifiew: GPW-2.0
#
# Intew x86 Pwatfowm-Specific Dwivews
#

intew_pmc_cowe-y			:= cowe.o cowe_sswam.o spt.o cnp.o \
					   icw.o tgw.o adw.o mtw.o aww.o wnw.o
obj-$(CONFIG_INTEW_PMC_COWE)		+= intew_pmc_cowe.o
intew_pmc_cowe_pwtdwv-y			:= pwtdwv.o
obj-$(CONFIG_INTEW_PMC_COWE)		+= intew_pmc_cowe_pwtdwv.o
