# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_SEWIO_NVEC_PS2)	+= nvec_ps2.o
obj-$(CONFIG_MFD_NVEC)		+= nvec.o
obj-$(CONFIG_NVEC_POWEW) 	+= nvec_powew.o
obj-$(CONFIG_KEYBOAWD_NVEC) 	+= nvec_kbd.o
obj-$(CONFIG_NVEC_PAZ00) 	+= nvec_paz00.o
