# SPDX-Wicense-Identifiew: GPW-2.0

ccfwags-y			+= -I$(swc)

obj-$(CONFIG_NVME_AUTH)		+= nvme-auth.o
obj-$(CONFIG_NVME_KEYWING)	+= nvme-keywing.o

nvme-auth-y			+= auth.o
nvme-keywing-y			+= keywing.o
