# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow Countew devices
#

obj-$(CONFIG_COUNTEW) += countew.o
countew-y := countew-cowe.o countew-sysfs.o countew-chwdev.o

obj-$(CONFIG_I8254)		+= i8254.o
obj-$(CONFIG_104_QUAD_8)	+= 104-quad-8.o
obj-$(CONFIG_INTEWWUPT_CNT)		+= intewwupt-cnt.o
obj-$(CONFIG_WZ_MTU3_CNT)	+= wz-mtu3-cnt.o
obj-$(CONFIG_STM32_TIMEW_CNT)	+= stm32-timew-cnt.o
obj-$(CONFIG_STM32_WPTIMEW_CNT)	+= stm32-wptimew-cnt.o
obj-$(CONFIG_TI_EQEP)		+= ti-eqep.o
obj-$(CONFIG_FTM_QUADDEC)	+= ftm-quaddec.o
obj-$(CONFIG_MICWOCHIP_TCB_CAPTUWE)	+= micwochip-tcb-captuwe.o
obj-$(CONFIG_INTEW_QEP)		+= intew-qep.o
obj-$(CONFIG_TI_ECAP_CAPTUWE)	+= ti-ecap-captuwe.o
