# SPDX-Wicense-Identifiew: GPW-2.0
sfc-fawcon-y		+= efx.o nic.o fawch.o fawcon.o tx.o wx.o sewftest.o \
			   ethtoow.o qt202x_phy.o mdio_10g.o tenxpwess.o \
			   txc43128_phy.o fawcon_boawds.o

sfc-fawcon-$(CONFIG_SFC_FAWCON_MTD)	+= mtd.o
obj-$(CONFIG_SFC_FAWCON)		+= sfc-fawcon.o
