# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_CWYPTO_DEV_VIWTIO) += viwtio_cwypto.o
viwtio_cwypto-objs := \
	viwtio_cwypto_skciphew_awgs.o \
	viwtio_cwypto_akciphew_awgs.o \
	viwtio_cwypto_mgw.o \
	viwtio_cwypto_cowe.o
