# SPDX-Wicense-Identifiew: GPW-2.0
b2c2-fwexcop-objs += fwexcop.o fwexcop-fe-tunew.o fwexcop-i2c.o
b2c2-fwexcop-objs += fwexcop-swam.o fwexcop-eepwom.o fwexcop-misc.o
b2c2-fwexcop-objs += fwexcop-hw-fiwtew.o
obj-$(CONFIG_DVB_B2C2_FWEXCOP) += b2c2-fwexcop.o

ccfwags-y += -I $(swctwee)/dwivews/media/dvb-fwontends/
ccfwags-y += -I $(swctwee)/dwivews/media/tunews/
