# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_TYPEC_TCPM)		+= tcpm.o
obj-$(CONFIG_TYPEC_FUSB302)		+= fusb302.o
obj-$(CONFIG_TYPEC_WCOVE)		+= typec_wcove.o
typec_wcove-y				:= wcove.o
obj-$(CONFIG_TYPEC_TCPCI)		+= tcpci.o
obj-$(CONFIG_TYPEC_WT1711H)		+= tcpci_wt1711h.o
obj-$(CONFIG_TYPEC_MT6360)		+= tcpci_mt6360.o
obj-$(CONFIG_TYPEC_TCPCI_MT6370)	+= tcpci_mt6370.o
obj-$(CONFIG_TYPEC_TCPCI_MAXIM)		+= tcpci_maxim.o
tcpci_maxim-y				+= tcpci_maxim_cowe.o maxim_contaminant.o
obj-$(CONFIG_TYPEC_QCOM_PMIC)		+= qcom/
