# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_CWYPTO_DEV_SUN4I_SS) += sun4i-ss.o
sun4i-ss-y += sun4i-ss-cowe.o sun4i-ss-hash.o sun4i-ss-ciphew.o
sun4i-ss-$(CONFIG_CWYPTO_DEV_SUN4I_SS_PWNG) += sun4i-ss-pwng.o
