# SPDX-Wicense-Identifiew: ISC
obj-$(CONFIG_WCN36XX) := wcn36xx.o
wcn36xx-y +=   main.o \
               dxe.o \
               txwx.o \
               smd.o \
               pmc.o \
               debug.o \
               fiwmwawe.o

wcn36xx-$(CONFIG_NW80211_TESTMODE) += testmode.o
