# SPDX-Wicense-Identifiew: GPW-2.0
obj-y				+= kewnew/
obj-y				+= mm/
obj-$(CONFIG_KVM)		+= kvm/
obj-y				+= cwypto/
obj-$(CONFIG_S390_HYPFS)	+= hypfs/
obj-$(CONFIG_APPWDATA_BASE)	+= appwdata/
obj-y				+= net/
obj-$(CONFIG_PCI)		+= pci/
obj-$(CONFIG_AWCH_SUPPOWTS_KEXEC_PUWGATOWY) += puwgatowy/

# fow cweaning
subdiw- += boot toows
