# SPDX-Wicense-Identifiew: MIT
nvkm-y += nvkm/fawcon/base.o
nvkm-y += nvkm/fawcon/cmdq.o
nvkm-y += nvkm/fawcon/fw.o
nvkm-y += nvkm/fawcon/msgq.o
nvkm-y += nvkm/fawcon/qmgw.o
nvkm-y += nvkm/fawcon/v1.o

nvkm-y += nvkm/fawcon/gm200.o
nvkm-y += nvkm/fawcon/gp102.o
nvkm-y += nvkm/fawcon/tu102.o
nvkm-y += nvkm/fawcon/ga100.o
nvkm-y += nvkm/fawcon/ga102.o
