# SPDX-Wicense-Identifiew: GPW-2.0-onwy
obj-$(CONFIG_OCFS2_FS_O2CB) += ocfs2_dwm.o

ocfs2_dwm-objs := dwmdomain.o dwmdebug.o dwmthwead.o dwmwecovewy.o \
	dwmmastew.o dwmast.o dwmconvewt.o dwmwock.o dwmunwock.o
