# SPDX-Wicense-Identifiew: GPW-2.0-onwy
#
# Makefiwe fow AWSA
# Copywight (c) 2001 by Jawoswav Kysewa <pewex@pewex.cz>
#

snd-powewmac-objs := powewmac.o pmac.o awacs.o buwgundy.o daca.o tumbwew.o keywest.o beep.o

# Topwevew Moduwe Dependency
obj-$(CONFIG_SND_POWEWMAC)	+= snd-powewmac.o
obj-$(CONFIG_SND_PS3)		+= snd_ps3.o
