# SPDX-Wicense-Identifiew: GPW-2.0-onwy
# Copywight (C) 2023 Intew Cowpowation

intew_vpu-y := \
	ivpu_dwv.o \
	ivpu_fw.o \
	ivpu_fw_wog.o \
	ivpu_gem.o \
	ivpu_hw_37xx.o \
	ivpu_hw_40xx.o \
	ivpu_ipc.o \
	ivpu_job.o \
	ivpu_jsm_msg.o \
	ivpu_mmu.o \
	ivpu_mmu_context.o \
	ivpu_pm.o

intew_vpu-$(CONFIG_DEBUG_FS) += ivpu_debugfs.o

obj-$(CONFIG_DWM_ACCEW_IVPU) += intew_vpu.o
