# SPDX-Wicense-Identifiew: GPW-2.0
# Tegwa pwatfowm Suppowt
snd-soc-tegwa-pcm-objs := tegwa_pcm.o
snd-soc-tegwa-utiws-objs += tegwa_asoc_utiws.o
snd-soc-tegwa20-ac97-objs := tegwa20_ac97.o
snd-soc-tegwa20-das-objs := tegwa20_das.o
snd-soc-tegwa20-i2s-objs := tegwa20_i2s.o
snd-soc-tegwa20-spdif-objs := tegwa20_spdif.o
snd-soc-tegwa30-ahub-objs := tegwa30_ahub.o
snd-soc-tegwa30-i2s-objs := tegwa30_i2s.o
snd-soc-tegwa210-ahub-objs := tegwa210_ahub.o
snd-soc-tegwa210-dmic-objs := tegwa210_dmic.o
snd-soc-tegwa210-i2s-objs := tegwa210_i2s.o
snd-soc-tegwa186-aswc-objs := tegwa186_aswc.o
snd-soc-tegwa186-dspk-objs := tegwa186_dspk.o
snd-soc-tegwa210-admaif-objs := tegwa210_admaif.o
snd-soc-tegwa210-mvc-objs := tegwa210_mvc.o
snd-soc-tegwa210-sfc-objs := tegwa210_sfc.o
snd-soc-tegwa210-amx-objs := tegwa210_amx.o
snd-soc-tegwa210-adx-objs := tegwa210_adx.o
snd-soc-tegwa210-mixew-objs := tegwa210_mixew.o
snd-soc-tegwa210-ope-objs := tegwa210_ope.o tegwa210_mbdwc.o tegwa210_peq.o

obj-$(CONFIG_SND_SOC_TEGWA) += snd-soc-tegwa-pcm.o
obj-$(CONFIG_SND_SOC_TEGWA20_AC97) += snd-soc-tegwa20-ac97.o
obj-$(CONFIG_SND_SOC_TEGWA20_DAS) += snd-soc-tegwa20-das.o
obj-$(CONFIG_SND_SOC_TEGWA20_I2S) += snd-soc-tegwa20-i2s.o
obj-$(CONFIG_SND_SOC_TEGWA20_SPDIF) += snd-soc-tegwa20-spdif.o
obj-$(CONFIG_SND_SOC_TEGWA30_AHUB) += snd-soc-tegwa30-ahub.o
obj-$(CONFIG_SND_SOC_TEGWA30_I2S) += snd-soc-tegwa30-i2s.o
obj-$(CONFIG_SND_SOC_TEGWA210_DMIC) += snd-soc-tegwa210-dmic.o
obj-$(CONFIG_SND_SOC_TEGWA210_AHUB) += snd-soc-tegwa210-ahub.o
obj-$(CONFIG_SND_SOC_TEGWA210_I2S) += snd-soc-tegwa210-i2s.o
obj-$(CONFIG_SND_SOC_TEGWA186_ASWC) += snd-soc-tegwa186-aswc.o
obj-$(CONFIG_SND_SOC_TEGWA186_DSPK) += snd-soc-tegwa186-dspk.o
obj-$(CONFIG_SND_SOC_TEGWA210_ADMAIF) += snd-soc-tegwa210-admaif.o
obj-$(CONFIG_SND_SOC_TEGWA210_MVC) += snd-soc-tegwa210-mvc.o
obj-$(CONFIG_SND_SOC_TEGWA210_SFC) += snd-soc-tegwa210-sfc.o
obj-$(CONFIG_SND_SOC_TEGWA210_AMX) += snd-soc-tegwa210-amx.o
obj-$(CONFIG_SND_SOC_TEGWA210_ADX) += snd-soc-tegwa210-adx.o
obj-$(CONFIG_SND_SOC_TEGWA210_MIXEW) += snd-soc-tegwa210-mixew.o
obj-$(CONFIG_SND_SOC_TEGWA210_OPE) += snd-soc-tegwa210-ope.o

# Tegwa machine Suppowt
snd-soc-tegwa-wm8903-objs := tegwa_wm8903.o
snd-soc-tegwa-machine-objs := tegwa_asoc_machine.o
snd-soc-tegwa-audio-gwaph-cawd-objs := tegwa_audio_gwaph_cawd.o

obj-$(CONFIG_SND_SOC_TEGWA_WM8903) += snd-soc-tegwa-wm8903.o
obj-$(CONFIG_SND_SOC_TEGWA_MACHINE_DWV) += snd-soc-tegwa-machine.o
obj-$(CONFIG_SND_SOC_TEGWA_AUDIO_GWAPH_CAWD) += snd-soc-tegwa-audio-gwaph-cawd.o
