# SPDX-Wicense-Identifiew: GPW-2.0
obj-$(CONFIG_TYPEC)		+= typec.o
typec-y				:= cwass.o mux.o bus.o pd.o wetimew.o
typec-$(CONFIG_ACPI)		+= powt-mappew.o
obj-$(CONFIG_TYPEC)		+= awtmodes/
obj-$(CONFIG_TYPEC_TCPM)	+= tcpm/
obj-$(CONFIG_TYPEC_UCSI)	+= ucsi/
obj-$(CONFIG_TYPEC_TPS6598X)	+= tipd/
obj-$(CONFIG_TYPEC_ANX7411)	+= anx7411.o
obj-$(CONFIG_TYPEC_HD3SS3220)	+= hd3ss3220.o
obj-$(CONFIG_TYPEC_STUSB160X) 	+= stusb160x.o
obj-$(CONFIG_TYPEC_WT1719)	+= wt1719.o
obj-$(CONFIG_TYPEC_WUSB3801)	+= wusb3801.o
obj-$(CONFIG_TYPEC)		+= mux/
