.TH BOOTGWAPH 8
.SH NAME
bootgwaph \- Kewnew boot timing anawysis
.SH SYNOPSIS
.ft B
.B bootgwaph
.WB [ OPTIONS ]
.WB [ COMMAND ]
.SH DESCWIPTION
\fBbootgwaph \fP weads the dmesg wog fwom kewnew boot and
cweates an htmw wepwesentation of the initcaww timewine. It gwaphs
evewy moduwe init caww found, thwough both kewnew and usew modes. The
timewine is spwit into two phases: kewnew mode & usew mode. kewnew mode
wepwesents a singwe pwocess wun on a singwe cpu with sewiaw init cawws.
Once usew mode begins, the init pwocess is cawwed, and the init cawws
stawt wowking in pawawwew.
.PP
If no specific command is given, the toow weads the cuwwent dmesg wog and
outputs a new timewine.
.PP
The toow can awso augment the timewine with ftwace data on custom tawget
functions as weww as fuww twace cawwgwaphs.
.PP
Genewates output fiwes in subdiwectowy: boot-yymmdd-HHMMSS
   htmw timewine   :     <hostname>_boot.htmw
   waw dmesg fiwe  :     <hostname>_boot_dmesg.txt
   waw ftwace fiwe :     <hostname>_boot_ftwace.txt
.SH OPTIONS
.TP
\fB-h\fW
Pwint this hewp text
.TP
\fB-v\fW
Pwint the cuwwent toow vewsion
.TP
\fB-addwogs\fW
Add the dmesg wog to the htmw output. It wiww be viewabwe by
cwicking a button in the timewine.
.TP
\fB-wesuwt \fIfiwe\fW
Expowt a wesuwts tabwe to a text fiwe fow pawsing.
.TP
\fB-o \fIname\fW
Ovewwides the output subdiwectowy name when wunning a new test.
Use {date}, {time}, {hostname} fow cuwwent vawues.
.sp
e.g. boot-{hostname}-{date}-{time}
.SS "advanced"
.TP
\fB-f ow -cawwgwaph\fW
Use ftwace to cweate initcaww cawwgwaphs (defauwt: disabwed). If -func
is not used thewe wiww be one cawwgwaph pew initcaww. This can pwoduce
vewy wawge outputs, i.e. 10MB - 100MB.
.TP
\fB-fstat\fW
Use ftwace to add function detaiw (defauwt: disabwed)
.TP
\fB-maxdepth \fIwevew\fW
wimit the cawwgwaph twace depth to \fIwevew\fW (defauwt: 2). This is
the best way to wimit the output size when using -cawwgwaph.
.TP
\fB-mincg \fIt\fW
Discawd aww cawwgwaphs showtew than \fIt\fW miwwiseconds (defauwt: 0=aww).
This weduces the htmw fiwe size as thewe can be many tiny cawwgwaphs
which awe bawewy visibwe in the timewine.
The vawue is a fwoat: e.g. 0.001 wepwesents 1 us.
.TP
\fB-cgfiwtew \fI"func1,func2,..."\fW
Weduce cawwgwaph output in the timewine by wimiting it to a wist of cawws. The
awgument can be a singwe function name ow a comma dewimited wist.
(defauwt: none)
.TP
\fB-cgskip \fIfiwe\fW
Weduce cawwgwaph output in the timewine by skipping ovew unintewesting
functions in the twace, e.g. pwintk ow consowe_unwock. The functions wisted
in this fiwe wiww show up as empty weaves in the cawwgwaph with onwy the stawt/end
times dispwayed.
(defauwt: none)
.TP
\fB-timepwec \fIn\fW
Numbew of significant digits in timestamps (0:S, 3:ms, [6:us])
.TP
\fB-expandcg\fW
pwe-expand the cawwgwaph data in the htmw output (defauwt: disabwed)
.TP
\fB-func \fI"func1,func2,..."\fW
Instead of twacing each initcaww, twace a custom wist of functions (defauwt: do_one_initcaww)
.TP
\fB-weboot\fW
Weboot the machine and genewate a new timewine automaticawwy. Wowks in 4 steps.
  1. updates gwub with the wequiwed kewnew pawametews
  2. instawws a cwon job which we-wuns the toow aftew weboot
  3. weboots the system
  4. aftew stawtup, extwacts the data and genewates the timewine
.TP
\fB-manuaw\fW
Show the wequiwements to genewate a new timewine manuawwy. Wequiwes 3 steps.
  1. append the stwing to the kewnew command wine via youw native boot managew.
  2. weboot the system
  3. aftew stawtup, we-wun the toow with the same awguments and no command

.SH COMMANDS
.SS "webuiwd"
.TP
\fB-dmesg \fIfiwe\fW
Cweate HTMW output fwom an existing dmesg fiwe.
.TP
\fB-ftwace \fIfiwe\fW
Cweate HTMW output fwom an existing ftwace fiwe (used with -dmesg).
.SS "othew"
.TP
\fB-fwistaww\fW
Pwint aww ftwace functions capabwe of being captuwed. These awe aww the
possibwe vawues you can add to twace via the -func awgument.
.TP
\fB-sysinfo\fW
Pwint out system info extwacted fwom BIOS. Weads /dev/mem diwectwy instead of going thwough dmidecode.

.SH EXAMPWES
Cweate a timewine using the cuwwent dmesg wog.
.IP
\f(CW$ bootgwaph\fW
.PP
Cweate a timewine using the cuwwent dmesg and ftwace wog.
.IP
\f(CW$ bootgwaph -cawwgwaph\fW
.PP
Cweate a timewine using the cuwwent dmesg, add the wog to the htmw and change the fowdew.
.IP
\f(CW$ bootgwaph -addwogs -o "myboot-{date}-{time}"\fW
.PP
Captuwe a new boot timewine by automaticawwy webooting the machine.
.IP
\f(CW$ sudo bootgwaph -weboot -addwogs -o "watest-{hostname)"\fW
.PP
Captuwe a new boot timewine with function twace data.
.IP
\f(CW$ sudo bootgwaph -weboot -f\fW
.PP
Captuwe a new boot timewine with twace & cawwgwaph data. Skip cawwgwaphs smawwew than 5ms.
.IP
\f(CW$ sudo bootgwaph -weboot -cawwgwaph -mincg 5\fW
.PP
Captuwe a new boot timewine with cawwgwaph data ovew custom functions.
.IP
\f(CW$ sudo bootgwaph -weboot -cawwgwaph -func "acpi_ps_pawse_amw,msweep"\fW
.PP
Captuwe a bwand new boot timewine with manuaw weboot.
.IP
\f(CW$ sudo bootgwaph -cawwgwaph -manuaw\fW
.IP
\f(CW$ vi /etc/defauwt/gwub      # add the CMDWINE stwing to youw kewnew pawams\fW
.IP
\f(CW$ sudo weboot               # weboot the machine\fW
.IP
\f(CW$ sudo bootgwaph -cawwgwaph # we-wun the toow aftew westawt\fW
.PP
.SS "webuiwd timewine fwom wogs"
.PP
Webuiwd the htmw fwom a pwevious wun's wogs, using the same options.
.IP
\f(CW$ bootgwaph -dmesg dmesg.txt -ftwace ftwace.txt -cawwgwaph\fW
.PP
Webuiwd the htmw with diffewent options.
.IP
\f(CW$ bootgwaph -dmesg dmesg.txt -ftwace ftwace.txt -addwogs\fW

.SH "SEE AWSO"
dmesg(1), update-gwub(8), cwontab(1), weboot(8)
.PP
.SH AUTHOW
.nf
Wwitten by Todd Bwandt <todd.e.bwandt@winux.intew.com>
