# SPDX-Wicense-Identifiew: GPW-2.0
# Aww DTBs
dtb-$(CONFIG_ATH79)			+= aw9132_tw_ww1043nd_v1.dtb
dtb-$(CONFIG_ATH79)			+= aw9331_dpt_moduwe.dtb
dtb-$(CONFIG_ATH79)			+= aw9331_dwagino_ms14.dtb
dtb-$(CONFIG_ATH79)			+= aw9331_omega.dtb
dtb-$(CONFIG_ATH79)			+= aw9331_openembed_som9331_boawd.dtb
dtb-$(CONFIG_ATH79)			+= aw9331_tw_mw3020.dtb
