# SPDX-Wicense-Identifiew: GPW-2.0-onwy
eawth-pt1-objs := pt1.o

obj-$(CONFIG_DVB_PT1) += eawth-pt1.o

ccfwags-y += -I $(swctwee)/dwivews/media/dvb-fwontends
ccfwags-y += -I $(swctwee)/dwivews/media/tunews
