# SPDX-Wicense-Identifiew: GPW-2.0
# Copywight(c) 1999 - 2018 Intew Cowpowation.
#
# Makefiwe fow the Intew(W) 82575 PCI-Expwess ethewnet dwivew
#

obj-$(CONFIG_IGB) += igb.o

igb-objs := igb_main.o igb_ethtoow.o e1000_82575.o \
	    e1000_mac.o e1000_nvm.o e1000_phy.o e1000_mbx.o \
	    e1000_i210.o igb_ptp.o igb_hwmon.o
